### ISSUE TITLE
Improve Gene pages for Tripal v3

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#100]
There has often been well-deserved criticism of gene pages in Tripal which is an unfortunate consequence of being a general platform supporting both genomics and/or breeding focused websites.

However, with Tripal v3 we can greatly improve gene pages without losing that generality! Entities in Tripal v3 will allow for pages dedicated to genes (rather then generic "feature" pages in Tripal 2) and the use of fields allows admin to easily choose what to show on these pages. By making fields specific to gene pages available to admin they can build the more traditional EnSEMBL-like gene pages through the interface.

This issue is to keep track of suggestions for field types with this goal in mind.

**Comment by laceysanderson** [comment]
Examples of Custom Tripal Gene Pages:
 - I5K: https://i5k.nal.usda.gov/OFAS001265
 - LegumeInfo: https://legumeinfo.org/feature/Arachis/duranensis/gene/Aradu.00992
 - PeanutBase: https://peanutbase.org/feature/Arachis/duranensis/gene/Aradu.000JC
 - GDR: https://www.rosaceae.org/node/1031
 - PlanoSphere: https://planosphere.stowers.org/feature/Schmitea/mediterranea-sexual/transcript/SMED30002427

Examples of non-Tripal Gene Pages:
 - NCBI: https://www.ncbi.nlm.nih.gov/gene/11420841
 - EnSEMBL: http://metazoa.ensembl.org/Aedes_aegypti/Gene/Summary?g=AAEL017009;r=supercont1.180:1754172-1755591;t=AAEL017009-RA;db=core
 - FlyMine: http://www.flymine.org/flymine/report.do?id=1007664&trail=|1007664
- ThaleMine: https://apps.araport.org/thalemine/report.do?id=69086080&trail=|69086080

**Comment by laceysanderson** [comment]
Tripal Field Ideas:
 - Transcript listing: Shows all the transcripts for a given gene including all the functional information & annotation for each transcript. 
   - Could simply embed Transcript view modes (e.g. Teaser) allowing admin to change the view mode and completely customize what shows up in this sub-listing.
- JBrowse Field to show a region of a JBrowse instance on any page. 
  - This will be included in the JBrowse integration module when it has a Tripal3 release
  - And configuration to allow you to highlight a specific gene for example
- Sequence Field: Shows the sequence for the Gene, any transcripts and proteins
- Typical Interpro, Go, BLAST homology results
  - should be provided by each Tripal Analysis Extension module

**Comment by kyrenya** [comment]
Hi there! I'm interested in using Jbrowse in my tripal v3_based site, but I found this: 
![image](https://user-images.githubusercontent.com/43243429/47731199-879abd80-dc5b-11e8-9f07-405565f86e56.png)
so apparently that module is not compatible with tripal v3?  but then I saw this thread.. and I'm a bit confused now. Is Jbrowse already integrated in tripal v3?  Thanks in advance!

**Comment by laceysanderson** [comment]
Hi @kyrenya, I can't speak for the Tripal JBrowse API extension but there is also my module [Tripal JBrowse](https://github.com/tripal/tripal_jbrowse), which integrates Tripal3 and JBrowse. This module currently creates pages for already existing JBrowse instances allowing you to embed them into the Drupal/Tripal ecosystem.

A couple of things to note about my current version:
- it uses iFrames currently although the next release will no longer need to
- it doesn't have any Tripal3 fields as wished for above (again -next release will) which means you can't yet embed JBrowse on your gene pages.
- it allows you to set which tracks to show by default and where to start for each JBrowse page.

You can see an example of what my module currently provides here: http://knowpulse.usask.ca/portal/jbrowse/Lentil.

Note: I'm not sure what my timeline is for the field as I'm currently bogged down with some impending grant deadlines but I would happily welcome contribution if you wanted to take it on :-)

**Comment by kyrenya** [comment]
Hi! thanks a lot for your reply, I will take a look and come back if I don't manage! I wish I could help taking it on, but this is my first contact with tripal or any similar tool, so I'm more like struggling to understand how everything works...  good luck with your grants!

**Comment by laceysanderson** [comment]
Great :-) Make sure to report any problems, wishes, UX questions to the issue queue for [that module](https://github.com/tripal/tripal_jbrowse/issues) -I Love feedback!

**Comment by kyrenya** [comment]
thanks!

**Comment by bradfordcondon** [comment]
@laceysanderson I *just* opened this issue for I5K.  My first target was what you call the transcript view, what i was thinking of as a child feature view.

What im thinking is it should could list each child feature as a collapsible one, which could be expanded to view all children/grandchildren of that feature and annotations etc.

Do you think this would be a core field?  I was planning on developing as a standalone field but it fits right in with this list (and im also interested in other things, namely the JBrowse embedding and/or graphic display)

**Comment by laceysanderson** [comment]
Awesome @bradfordcondon! I was thinking along similar lines I think. I had pictured something similar to the BLAST display where by default everything is collapsed and you see a clean list/table. Then the user can expand any portion and see a full display of that particular transcript. We could use Drupal View modes to make customization easy both for us and site admin. By default it could use the teaser view mode?

I think good gene pages are something Tripal needs to prioritize so yes, I think it could be a core field. Maybe we should open an issue specific for that field and make it open to a PMC vote?

**Comment by ekcannon** [comment]
It often helpful, if depressing, to see what the "human" folks are up to. Here's a gene page to aspire to:

[https://www.genecards.org/cgi-bin/carddisp.pl?gene=MYC]()

**Comment by Ferrisx4** [comment]
Thanks @spficklin for the new functionality provided by https://github.com/tripal/tripal/pull/1169

It was suggested to be able to include additional transcript types such as lnc_RNA. Would it be possible to detect existing types on a site?

**Comment by spficklin** [comment]
Now that we have a solution in Tripal v3.5 I think we can close this out and if there are issues with that solution we can open a new issue. I'm going to add the Inc_RNA suggestions made by @Ferrisx4 as a separate new issue.
