### ISSUE TITLE
schema__publication field only populates data after an entity has been "viewed"

### ISSUE THREAD

**Issue by par12005** [tripal/tripal#1001]
### System information

* Tripal Version: 7.x-3.x
* Drupal Version: 7.56
* PostgreSQL Version: 9.5.7
* PHP Version: 7.0.30-0ubuntu0.16.04.1

### Issue description

Information in the schema__publication Tripal Field only gets populated for an entity after the entity has been viewed. When entities are created through the `bio_data/add` form this is not a problem because the form redirects to the view of the entity immediately after saving. However, when entities are created programmatically (for example, by publishing Tripal Content), viewing the entity does not take place, so the publication information doesn't get loaded.

#### Steps to reproduce
The easiest way I have found to reproduce this problem is as follows:

 - Comment out [line 728 of tripal/includes/TripalEntityUIController.inc](https://github.com/tripal/tripal/blob/7.x-3.x/tripal/includes/TripalEntityUIController.inc#L728) 
 - Navigate to `bio_data/add` on your Tripal site
 - Select "Project"
 - Add a title
 - Select a publication (if you don't have any publications on your site already you may need to create a new one)
 - Scroll to the bottom of the form and click "Save"
 - Navigate to `admin/content/bio_data`
 - Filter by Content Type = Project
 - Mouse over (don't click!) the project entity you just created, and look at the link to see what Tripal Entity id number your project has. You can also do this by right-clicking the entity, selecting "copy link address", and pasting the link in a notepad to see the Tripal Entity id number.
 - Run the drush command: 

```
drush php-eval "print_r(current(tripal_load_entity('TripalEntity', array(<Your Entity ID Number>)))->schema__publication['und'][0]['value'])"
```

 - Note that this outputs nothing
 - Now go back to your browser and click on the entity
 - Note that the publication appears in the entity view
 - Re-run the above drush command. You should now get an array with information about the publication you linked to the project.

You can also use the following code snippet to reproduce the problem:

```php
// Come up with a name of a project/publication that won't conflict with existing ones.
$name = 'new pub/project name';

// Create new publication.
$pub = chado_insert_record('pub', array(
  'uniquename' => $name,
  'type_id' => 1,
));

// Create new project.
$project = chado_insert_record('project', array(
  'name' => $name,
));

// Link them with project_pub table
chado_insert_record('project_pub', array(
  'project_id' => $project['project_id'],
  'pub_id' => $pub['pub_id'],
));

$pub_bundle = tripal_load_bundle_entity(array(
  'label' => 'Publication',
));

// Publish the pub entity.
chado_publish_records(array(
  'bundle_name' => $pub_bundle->name,
));

$project_bundle = tripal_load_bundle_entity(array(
  'label' => 'Project',
));

// Publish the project entity.
chado_publish_records(array(
  'bundle_name' => $project_bundle->name,
));

// Get the entity id of the project.
$entity_id = chado_get_record_entity_by_bundle($project_bundle, $project['project_id']);

// Check the schema__publication field of the project.
$entity = current(tripal_load_entity('TripalEntity', array($entity_id)));
print_r("publication info before viewing:\n");
print_r($entity->schema__publication['und'][0]['value']);

// Trigger a "view" of the project.
$controller = entity_get_controller('TripalEntity');
$controller->view(array($entity->id => $entity));

// Reload the project entity and check the schema__publication field again.
$entity_reloaded = current(tripal_load_entity('TripalEntity', array($entity_id)));
print_r("\npublication info after viewing:\n");
print_r($entity_reloaded->schema__publication['und'][0]['value']);
```

I have tried loading entities with the `$reset` parameter of tripal_load_entity, such as:

```
tripal_load_entity('TripalEntity', array($entity_id), TRUE);
```

But I still ran into the same issue. I have found the same issue with content types other than Project.

**Comment by par12005** [comment]
Wow, I can't believe I just spent all morning on this.

The schema__publication field has a field setting `'auto_attach' => FALSE`, which prevents it from being attached during a load without being explicitly included in the `$field_ids` parameter of tripal_load_entity. To fix the "issue" I described above, you simply need to include the field id of the schema__publication field when calling tripal_load_entity. If you want to automatically load all fields, you can simply use the built-in Drupal entity_load function as well. Closing this issue.

**Comment by laceysanderson** [comment]
Hi @par12005, I'm glad you were able to figure this out! Can you provide a code sample here so we can better document it and help others who may run into the same observation you did?

**Comment by par12005** [comment]
Hi @laceysanderson, sure! Did you want the code sample in a separate file,
or in a comment on this issue similar to the snippet above?

**Comment by bradfordcondon** [comment]
either is fine although if it's a separate file, please link to it here from a stable place (use a gist for example).  the idea is the next user with a similar problem might find this issue and benefit from your solution.  And, thank you :)

**Comment by par12005** [comment]
Here is a code snippet that you can run which demonstrates the issue and a solution to it:

```php
// Come up with a name of a project/publication that won't conflict with existing ones.
$name = 'new pub/project name';

// Create new publication.
$pub = chado_insert_record('pub', array(
  'uniquename' => $name,
  'type_id' => 1,
));

// Create new project.
$project = chado_insert_record('project', array(
  'name' => $name,
));

// Link them with project_pub table
chado_insert_record('project_pub', array(
  'project_id' => $project['project_id'],
  'pub_id' => $pub['pub_id'],
));

$pub_bundle = tripal_load_bundle_entity(array(
  'label' => 'Publication',
));

// Publish the pub entity.
chado_publish_records(array(
  'bundle_name' => $pub_bundle->name,
));

$project_bundle = tripal_load_bundle_entity(array(
  'label' => 'Project',
));

// Publish the project entity.
chado_publish_records(array(
  'bundle_name' => $project_bundle->name,
));

// Get the entity id of the project.
$entity_id = chado_get_record_entity_by_bundle($project_bundle, $project['project_id']);

// Check the schema__publication field of the project.
$entity = current(tripal_load_entity('TripalEntity', array($entity_id)));
print_r("publication info with tripal_load_entity():\n");
print_r($entity->schema__publication['und'][0]['value']);
// Note that loading the entity this way does not produce the publication information.
// This is because the schema__publication field instance has a setting 'auto_attach' = FALSE.
// That means that loading the entity through tripal_load_entity will not automatically load the publication information.

// We can check the auto_attach setting with field_info_instance():
$field_info = field_info_instance('TripalEntity', 'schema__publication', $project_bundle->name);
print_r("auto_attach setting: ");
$field_info['settings']['auto_attach'] ? print_r("True\n") : print_r("False\n");

// The easiest way to load the entity such that the publication information comes along with it is to simply pass along the field id to tripal_load_entity():
$entity_with_field_ids = current(tripal_load_entity('TripalEntity', array($entity_id), TRUE, array($field_info['field_id'])));
print_r("publication info with tripal_load_entity() and field ids:\n");
print_r($entity_with_field_ids->schema__publication['und'][0]['value']);
// This will load only the fields whose ids we passed to the function.

// To load ALL of the fields associated with an entity we can do something like this:
// Get each field id associated with the bundle.
$bundle_details = tripal_get_bundle_details($project_bundle->name);
$field_ids = array();
foreach ($bundle_details['fields'] as $field) {
  $field_ids[] = field_info_field($field['name'])['id'];
}

// Load the entity with all of its fields attached.
$entity_all_field_ids = current(tripal_load_entity('TripalEntity', array($entity_id), TRUE, $field_ids));
print_r("entity with all fields loaded:\n");
print_r($entity_all_field_ids);
```

I hope someone finds this to be helpful!

**Comment by laceysanderson** [comment]
This is great! Thank you @par12005!
