### ISSUE TITLE
Trying to upgrade or install of latest Tripal

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#1003]
### System information

* Tripal Version: 3.2?
* Drupal Version: 7.61
* PostgreSQL Version: 9.2.24
* PHP Version: 5.6

### Issue description
During clone from the latest Tripal git in an attempt to upgrade to latest version, I get the following error:

```
PHP Parse error:  syntax error, unexpected '?' in /var/www/html/sites/all/modules/tripal/tripal/includes/tripal.registration.inc on line 296
Drush command terminated abnormally due to an unrecoverable error.                  [error]
Error: syntax error, unexpected '?' in
/var/www/html/sites/all/modules/tripal/tripal/includes/tripal.registration.inc, line
296

```

**Comment by bradfordcondon** [comment]
https://github.com/tripal/tripal/blob/e4d4c57fa53bb0d9d8807b3e99ee84c77769bc63/tripal/includes/tripal.registration.inc#L296

PHP 7 vs 5.6 is the problem.  I'd just disable those lines if you must keep using PHP 5.6, but we have dropped support for PHP 5.6 as it is [past its EOL](https://www.php.net/supported-versions.php)

**Comment by risharde** [comment]
Thanks @bradfordcondon, will up to 7

**Comment by risharde** [comment]
Updated rapid installer to now install PHP 7 instead of 5.6. Check it out at https://gitlab.com/TreeGenes/tripal_rapid_installer_for_centos_7
