### ISSUE TITLE
Deleting a Database results in the following error message

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#1005]
Tripal: 3.0
Postgres: 9.x
PHP: 7.2

Deleting a created 'TEST' database results in the following error, just a heads up? I have added a test vocabulary and also a test cv term. I suspect it may be failing since this data exists? Maybe a better way would be to have a checkbox that forces the removal of the database and all tied in data?

```
PDOException: SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "dbxref_id" violates not-null constraint DETAIL: Failing row contains (2989, 57, test_content_type, , null, 0, 0). CONTEXT: SQL statement "UPDATE ONLY "chado"."cvterm" SET "dbxref_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "dbxref_id"": DELETE FROM chado.db WHERE db_id = :db_id ; Array ( [:db_id] => 44 ) in chado_query() (line 1715 of /var/www/html/sites/all/modules/tripal/tripal_chado/api/tripal_chado.query.api.inc).

```

**Comment by bradfordcondon** [comment]
its true.  I dont think we get a ton of use out of the delete db interface, but, if someone did want it to cascade, the would probably want to know how many attached records would be deleted.

I could also see us just adding instructions that you need to remove all dbxrefs from the db before this would work.

**Comment by bradfordcondon** [comment]
i built it out to just block the delete and provide a notice as its easiest/safest and definitely laziest: https://github.com/tripal/tripal/commit/cd5a9c55a7c8a7645cd418e979276bba594018ce#diff-ad8ca83a8fb3d11bfdc15152c7a9a956

what do we think?  worth adding to prevent the SQL error?

**Comment by laceysanderson** [comment]
PR Merged
