### ISSUE TITLE
Warnings when adding a new field to a Tripal Content Type

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#1006]
Adding a new arbitrary field seems to output this error. It does not affect field addition.

Notice: Undefined index: name in tripal_field_instance_settings_form_alter_process() (line 523 of /var/www/html/sites/all/modules/tripal/tripal/includes/tripal.fields.inc).
Notice: Undefined index: description in tripal_field_instance_settings_form_alter_process() (line 523 of /var/www/html/sites/all/modules/tripal/tripal/includes/tripal.fields.inc).

**Comment by laceysanderson** [comment]
Hi @risharde are you still experiencing this? I attempted to replicate your problem by
1. Going to an arbitrary content type (e.g. Gene) Manage Fields page.
2. Adding a new field through "Add new field" with a type of "Chado Property"
3. Clicking Save without selecting a term.

This produced the following errors which are similar to yours:
```
Notice: Undefined index: term_vocabulary in tripal_field_instance_settings_form_alter_validate() (line 728 of /Users/laceysanderson/Sites/tripal-TEST/sites/all/modules/tripal/tripal/includes/tripal.fields.inc).
Notice: Undefined index: term_accession in tripal_field_instance_settings_form_alter_validate() (line 728 of /Users/laceysanderson/Sites/tripal-TEST/sites/all/modules/tripal/tripal/includes/tripal.fields.inc).
```

Can you confirm if this is the same process you used and if your errors match mine when you use the most recent version of Tripal dev?

**Comment by risharde** [comment]
Sorry for the late response @laceysanderson, I didn't add my fields via the UI like you did but via code programmatically (similar to you UI procedure) - looks like it applies to both our methods

**Comment by laceysanderson** [comment]
I can no longer replicate this. Closing and a new issue can be created if it re-appears
