### ISSUE TITLE
Notice errors when checking for new fields created programmatically

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#1007]
Tripal: 3.2
Drupal. 7.67
Postgres: 9.x
PHP: 7.2

Experiencing multiple warnings like the following when I click on check new fields for the Tripal Contact Profile content type. Any ideas what would be causing this? It's more of a nuisance - functionality does not seem to be affected. @bradfordcondon @spficklin ?

Notice: Undefined variable: pkey in tripal_chado_bundle_instances_info_linker() (line 2518 of /var/www/html/sites/all/modules/tripal/tripal_chado/includes/tripal_chado.fields.inc).

Example code for creation of these fields can be found here, wondering if I left something out of the code:
https://gitlab.com/TreeGenes/tripal_contact_profile/blob/master/tripal_contact_profile.admin.inc#L91

**Comment by risharde** [comment]
Could it be that type_id needs to be specified via the chado_insert_property function?

**Comment by bradfordcondon** [comment]
Entities are assumed to have a primary key.  In the case of most chado content, the primary key is `[table_name]_id`.  I'd imagine that this isnt set properly on your custom bundle somehow?

(heres an example usage, i know its not where you are seeing the error but it should demonstrate what it expects)

https://github.com/tripal/tripal/blob/dd88e9fa9b497fe046913e97110b4f4721431edc/tripal_chado/includes/TripalFields/chado_linker__prop/chado_linker__prop_widget.inc#L26-L31

**Comment by laceysanderson** [comment]
Steps to duplicate:
1. Use the following code to add a property on your site. I execute this in the devel "Execute PHP"
```
$record = array('table' => 'contact', 'id' => 1);
$status = chado_insert_property(
    $record, [
        'type_name' =>'sequence_variant',
        'cv_name' => 'sequence', 
        'value' => 'anything',  
]);
```
2. Go to Admin > Structure > Tripal Content Types > Contact > Manage Fields and click "    Check for new fields"

**This affects all content types with property tables.**

**Comment by laceysanderson** [comment]
See PR #1015 for a potential fix. @risharde could you test this for me?
