### ISSUE TITLE
tripal_daemon parallelization

### ISSUE THREAD

**Issue by heh30** [tripal/tripal#1008]
Documentation surrounding the tripal_daemon is a little sparse.  I've not found anything explicitly saying this can/cannot be done, I'm just not sure how to enable it if it is currently available.

Not Urgent
Tripal 7.x-3.2

### Description
Allow ability to specify parallel=1 when starting the tripal_daemon

### Your Specific Use Case
When manually running drush trp_run-jobs it's possible to specify parallel=1 so more than one job can run at a time.  I've not identified a way that this can also be configured with the tripal_daemon

### Generally Applicable
Some jobs, like GFF loads take a large amount of time to complete.  If parallel=1 could be specified with the tripal_daemon smaller jobs could run concurrently with the GFF loads

**Comment by laceysanderson** [comment]
Hello @bcuser30, I'm sorry we haven't written that information into ReadtheDocs yet. If you run `drush trpjob-daemon --help` within your Drupal root you recieve

```
Use Tripal Jobs Deamon to manage Tripal Job execution.

Examples:
 drush trpjob-daemon start                 Start the daemon.                       
 drush trpjob-daemon status                Show the current status of the daemon.  
 drush trpjob-daemon stop                  Stop the daemon.                        
 drush trpjob-daemon show-log              Show the last 10 lines of the log file. 
 drush trpjob-daemon show-log              Show the last 10 lines of the log file. 
 --num_lines=50

Arguments:
 start                                     Start the daemon.                            
 status                                    Display status information about the daemon. 
 stop                                      Stop the daemon.                             
 show-log                                  Show the log file.

Options:
 --max_jobs                                Indicate the maximum number of concurrent jobs. Default is 3; use -1 (unlimited). Ignore if not running parallel jobs          
 --num_lines                               The number of lines of the log file to show.                                                                                   
 --parallel                                Normally jobs are executed one at a time. But if you are certain no conflicts will occur with other currently running jobs you 
                                           may set this argument to a value of 1 to make the job run in parallel with other running jobs.

Aliases: trpjob-daemon
```

Specifically, in answer to your question, yes the Tripal Daemon does support parallel jobs! When you start your daemon do so as follows `drush trpjob-daemon start --parallel=1 --max_jobs=3` This will allow at most 3 jobs to run in parallel at any given time. I recommend choosing your max jobs setting taking into consideration the power of your server and the amount of resources jobs run on your site typically take.

I'm going to tag this issue with "documentation" as a reminder that the documentation needs to be improved for Tripal Daemon. Also, if you happen to be participating in [Hacktoberfest](https://hacktoberfest.digitalocean.com/) and would like to submit a documentation PR we would greatly appreciate it :-)

**Comment by laceysanderson** [comment]
PS. You can monitor your Daemon by going to your Drupal site and clicking on Dashboard in the administration menu.
![tripaldaemondashboard](https://user-images.githubusercontent.com/1566301/66799125-1f290880-eecd-11e9-9e35-0fb1aef0b1b9.png)

**Comment by heh30** [comment]
Thank you so much for your help.  I swore I'd invoked the help menu and did not see those details before.  

Additional thank you on the dashboard.  That's not something we had configured.

One more question, related but not.  When running jobs manually we're able to see progress details output to the terminal.  When using the daemon, is there a way to also see this output?  It's available on the jobs page when the job is complete, but it would be beneficial to see real-time while longer running jobs are active.  This is not available in the daemon log.

**Comment by laceysanderson** [comment]
Unfortunately those details are not available during the job. I cannot make them available through the interface during job execution due to transactions and I cannot print them to the daemon log due to jobs running in parallel (output for separate jobs would end up mixed in the log). I agree real-time job logging would be beneficial but have yet to figure out a good way to accomplish it 🤷‍♀
