### ISSUE TITLE
Not able to search existing Chado Databases in Admin menu 

### ISSUE THREAD

**Issue by jhumann** [tripal/tripal#1009]
### System information

Tripal Version: 7.x-3.2
Drupal Version: 7.67
PostgreSQL Version: 10.10
PHP Version: 7.0.33

### Issue description
I have the need to edit the URLs in existing Chado Databases on our sites.  The Tripal admin menu has a page to do this (/admin/tripal/loaders/chado_db), but I cannot see all existing dbs by clicking Search or by entering a search term.  I always get no results.  There used to be a patch that would fix this (we have had this issue in T2 and T3), but I guess it doesn't exist anymore.

#### Steps to reproduce
Go to the admin page for chado databases and you can add new databases, but cannot access/search the list of existing databases.  I used to be able to click "search" and all the existing dbs would appear.  But that and trying to search with the db name results in the error message below (well, really not a true error message).

#### Error messages and screenshots
"No databases match the supplied criteria."

**Comment by laceysanderson** [comment]
Hi @jhumann,

The patch is still available it has just moved into the [tripal_chado_views](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado_views/views-sql-compliant-three-tier-naming-1971160-30.patch) submodule.

Applying the patch should fix your issue 🤞

**Comment by spficklin** [comment]
For reference, the instructions for applying that patch are here in the User's Guide:

https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/manual_install/install_tripal.html#apply-patches

**Comment by jhumann** [comment]
Yep, that solved the problem.  Thanks!!
