### ISSUE TITLE
feature_relationship/sequence change

### ISSUE THREAD

**Issue by abretaud** [tripal/tripal#101]
Hi,
While chasing a bug in the docker image, I found that the change in [this commit](https://github.com/tripal/tripal/commit/eb19a57b02a8842ffbc043489492f2c7145542b2#diff-7fa69e7fdb5f641ffbb18f79fcb8ef88L236) was reverted in the [next commit](https://github.com/tripal/tripal/commit/9a34e7512e98d290e749ac8c780d35a4a4c980a9#diff-7fa69e7fdb5f641ffbb18f79fcb8ef88L236). Looking at the last commit, I feel like this could be an unintended revert, so I'm just reporting it to you just in case. I have no real idea of what problem it could cause though.

**Comment by laceysanderson** [comment]
@spficklin did you see this? Thanks for pointing it out @abretaud!

**Comment by spficklin** [comment]
Thanks for having such a careful eye with the code!   I think though that the second commit is correct.  The tripal_get_default_cv() function looks for the controlled vocabulary to use for type_id fields in Chado tables.  There is no 'sequence' table but there is a 'feature_relationship' table and the second commit looks like the proper call of the function.

Did this line of code cause a problem for you or you just noticed the change?

**Comment by abretaud** [comment]
No problem, I just noticed the change while looking for something else. No problem to close this if you think it's ok

**Comment by spficklin** [comment]
Great. I'll close it.  Thanks again for contributing!
