### ISSUE TITLE
Web Services - Invalid Content Type

### ISSUE THREAD

**Issue by reynoldtan** [tripal/tripal#1010]
### System information

* Tripal Version: 7.x-3.x
* Drupal Version: 7
* PostgreSQL Version: 11.3
* PHP Version: 7.1.30

### Issue description

When content types comprise of multiple words separated by spaces, Web Services format the url with a + (plus sign) instead of _ (underscore) as seen in other section. This causes invalid content type error.

### **AN UPDATE**
I was able to load an expanded field (beyond the invalid content type error) and found out that the + plus sign issue was also present at this point. 

![invalid-content-type](https://user-images.githubusercontent.com/15472253/67040360-91be0200-f0e0-11e9-9a9e-ce6de439a395.gif)

#### Steps to reproduce

Access /web-services/content/v0.1 in your site and click on @id link of a content type that contains multiple words (ie. Genetic Marker, F1 Breeding Crosses etc), keep accessing @id until you reach content resource where @id now contains plus symbol as part of the url.

#### Error messages and screenshots

@see image above
```
error message
`Invalid Content Type`

**Comment by bradfordcondon** [comment]
Thank you for contributing this fix
