### ISSUE TITLE
travis builds failing w/ postgres

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#1012]
## BUG/ERROR report
bug is in CI builds.

```
 connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"

```

Probably a change in how it supports postgres:  https://docs.travis-ci.com/user/database-setup/#postgresql

**Comment by laceysanderson** [comment]
PR Merged -Thank you for the fix @bradfordcondon!
