### ISSUE TITLE
Web Services - hydra:member not rendered

### ISSUE THREAD

**Issue by reynoldtan** [tripal/tripal#1019]
### System information

* Tripal Version: 7.x-3.x
* Drupal Version: 7
* PostgreSQL Version: 11.3
* PHP Version: 7.1.30

### Issue description

An empty array or list in members.

![Screen Shot 2019-11-01 at 10 48 32 AM](https://user-images.githubusercontent.com/15472253/68041391-15a5eb80-fc96-11e9-8dda-42de0d9e1b8e.png)

When implementing an instance of hydra:member in the field's load() function, such as the code below;

```
foreach ($items as $i => $item) {
  $entity->{$field_name}['und'][$delta]['value']['hydra:member'][$i] = array( 
    'rdfs:label' => $item['label'],
    'local:count' => $item['count'], 
   );
}
```
expected result should look like
![Screen Shot 2019-11-01 at 11 09 03 AM](https://user-images.githubusercontent.com/15472253/68042266-16d81800-fc98-11e9-8069-6ccd121dcac6.png)

but instead, the output is an empty array.
![Screen Shot 2019-11-01 at 11 11 26 AM](https://user-images.githubusercontent.com/15472253/68042404-69b1cf80-fc98-11e9-9019-5c412a614e3d.png)

#### Steps to reproduce

In the load() method of your field, create additional information for Tripal Web service and use hydra:member as the key (see code sample above). Clear your cache and reload page.

#### Error messages and screenshots

```
error message
```

**Comment by laceysanderson** [comment]
PR Merged
