### ISSUE TITLE
Web Services - Limited access works only in viewing an entity (for anonymous user).

### ISSUE THREAD

**Issue by reynoldtan** [tripal/tripal#1022]
### System information

* Tripal Version: 7.x-3.x
* Drupal Version: 7
* PostgreSQL Version: 11.3
* PHP Version: 7.1.30

### Issue description

Limited access to content only works in viewing an entity and does not work in listing and viewing content types. For example:

I've limited access to Genetic Maps to anonymous user in the permissions panel.
![Screen Shot 2019-11-05 at 1 10 17 PM](https://user-images.githubusercontent.com/15472253/68245968-86723e00-ffdd-11e9-9217-644c73e95aa0.png)

It works on **web-services/v0.1/content type/entity id**
![Screen Shot 2019-11-05 at 1 19 45 PM](https://user-images.githubusercontent.com/15472253/68246068-b3beec00-ffdd-11e9-8ea8-c57cb5323720.png)

but not in the following sections:

A. EntryPoint
**web-services/v0.1**
![Screen Shot 2019-11-05 at 1 20 24 PM](https://user-images.githubusercontent.com/15472253/68246161-e1a43080-ffdd-11e9-8829-d485fbf3cf7a.png)

B. Content Type
**web-services/v0.1/content type**
![Screen Shot 2019-11-05 at 1 21 30 PM](https://user-images.githubusercontent.com/15472253/68246205-f4b70080-ffdd-11e9-8a24-4fc33514c70f.png)

#### Error messages and screenshots

```
error message
```

**Comment by laceysanderson** [comment]
PR Merged
