### ISSUE TITLE
New Proposed Module: Tripal File Module

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal#1025]
As mentioned in the [Tripal User's Meeting on Nov 5, 2019](https://docs.google.com/document/d/1o-7fAYxhtvMwdKErTr2a5Nu0dyRiv_OKd5MUUQ5JmaQ/edit#), several groups have expressed interest in the development of a Tripal File module. The design and goals of this module can be found in the [original specification sheet (2017)](https://docs.google.com/document/d/12ON7YpYwj2Iy81vnogu4ixfqWJydKM2SicoAMgbB4-M/edit?ts=5d91ff16) as well as the [more recent document](https://docs.google.com/document/d/1a8Z0kCo82hgnooGjcSLgWVdj3sHKpw53_kyFXsSFG3o/edit#heading=h.olm9ep1d277p).

Presently, module will be known as the Tripal File module, machine/module name `tripal_file`

A summary of these goals is below:
 - Original
   - Allow files to be associated with any content/bundle type
   - Flexible filetypes - types can be added in the future
   - Files accessible and discoverable through webservices   
   - Create download links automatically
   - Access control (permissions, published yet)
   - Data retrieval from indexed files that are not in Chado 
   - Search page for file types including filters by association
   - View a list of associations that a file has with site content
 - New
   - File management API to allow workflows to upload files and associate them automatically
   - Manage files that are local as well as remote to the webserver (Remote mechanism to be determined)
   - File housekeeping 
      - Does the file still exist and is it accessible
      - Not corrupt (particularly after upload, but at any point in management period)
   - Standards and File Sanity
      - Version control
      - Basic file format checking
      - DOI and licensing support
   - When files are uploaded via a loader, they become available for re-use in a dropdown of existing files

Any further feedback for this module would be greatly appreciated.

**Comment by Ferrisx4** [comment]
Currently, the development of this module is on hold due to its hugely overlapping feature set with functionality that will be provided natively in Drupal 8.

In order to avoid duplication of work, development of this module will focus primarily on Tripal 4.

**Comment by spficklin** [comment]
The Tripal File module has a beta release and is being tested. So, I'm going to close this out.
