### ISSUE TITLE
API function for adding files to the user's quota system.

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1026]
## Feature Request/Discussion

* This feature [does / does not] attempt to solve an existing problem with Tripal
* I [am/am not] open to developing or collaborating on an extension module if this is not a good fit for Tripal Core

* This feature is [URGENT/Not Urgent]

### Description

It would be helpful if extension modules were able to easily add files to the User's quota system so they don't have to manage those files on their own. Right now, the only way for an extension module to tie into that functionality is to use the Tripal uploader. But there are cases when files can be generated outside of that (e.g. Tripal Blast UI module).

### Your Specific Use Case

This issue arose due to a short discussion about it on the Slack #general channel related to the Blast UI module.

### Generally Applicable

This would be applicable to any extension module that generates files.

**Comment by laceysanderson** [comment]
Closing as there is no bandwidth to work on this enhancement and it hasn't been requested yet by extension module developers.
