### ISSUE TITLE
Registration page opt-out confusion

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1028]
### System information

* Tripal Version: 3.2
* Drupal Version: 7.x
* PostgreSQL Version: N/A
* PHP Version: N/A

### Issue description

On a brand new install of Tripal the user is asked to register the site. They can opt-out if they want. When they check the opt-out checkbox, nothing happens, and the message at the top of the page asking to opt-out doesn't go away.

**Comment by laceysanderson** [comment]
Good catch, I'll try to get to the associated PR today!

**Comment by laceysanderson** [comment]
PR Merged
