### ISSUE TITLE
New form to create nested analyses

### ISSUE THREAD

**Issue by mpoelchau** [tripal/tripal#1031]
## Feature Request/Discussion

* This feature does attempt to solve an existing problem with Tripal (or rather, Chado) - see https://github.com/GMOD/Chado/issues/113
* I am open to developing or collaborating on an extension module if this is not a good fit for Tripal Core 
* This feature is Not Urgent

### Description
At the PAG Tripal Codefest, we petitioned to expand the description of the chado analysis table (https://github.com/GMOD/Chado/issues/113). The idea is to allow the analysis table to accommodate multiple programs per analysis (since most Tripal users currently do this anyway). Participants at the Codefest were generally supportive of this idea. 

Once this change is approved by the Chado PMC, we would like to create a new form that would allow site admins to create nested analyses in a single form. The admin user would be able to generate the 'parent' analysis, and nested 'child' analyses, and optionally the child analyses' rank (=order of execution in a workflow), in a single form. Parent and child analyses would be connected via the analysis_relationship table, via a part_of relationship.  

### Your Specific Use Case
This expanded form would be useful for any 'workflow' type of analysis. A specific use case is a genome assembly. The 'parent' analysis would have program/programversion in a format that we'd recommend (e.g.  Lab/data generator - organism - genome assembly name or identifier - pipeline/ version, e.g. ‘Staton lab Quercus lobata genome assembly pipeline/v1.0'). The admin could then click a 'add child analysis' (or sub analysis) button, which would show a new set of analysis fields. Here, the admin would enter the first analysis step (e.g. from a read trimming program). Etc for the remaining analysis steps. The form would then populate multiple analysis records, and link them via the analysis_relationship table.  

We'd recommend that the admin link features generated by the workflow to the parent analysis.

### Generally Applicable

Most Tripal databases likely store analyses that are actually workflows/pipelines that contain multiple components. 

- gene expression analyses
- genome annotation analyses

### Additional information/screenshots
Notes from the meeting are here: https://docs.google.com/document/d/1QlFSE_YBrSW7P8tC_aABwapgkX9PpFuAxUrcQM0F7O4/edit

### Related issues
- https://github.com/tripal/tripal/issues/804
- https://github.com/tripal/tripal_doc/issues/115

**Comment by laceysanderson** [comment]
I support this and feel it is a good fit for Tripal Core as it would encourage increased metadata for analysis pipelines. I can see this being done a number of ways:

A. Creating a child analysis field. 
   - This allows child analyses to be added during analysis creation through the core Tripal form.
   - Users will have a visual cue to add extra detail to all analysis.
   - Also handles rendering of sub-analysis on an analysis page.
   - More complex to develop.
   - Needs good help text/design to make it intuitive.

B. A stand-alone form. 
   - This may be more intuitive.
   - Easier to provide help text for how to name the parent analysis.
   - Less generic.
   - Users have to go to a separate location/URL to add complex analysis.

C. A TripalImporter.
   - More intuitive location then a stand-alone form.
   - Can support a file for sub-analysis if you choose. Importers also do not need to have a file.
   - Can auto generate the parent analysis name based on our own internal pattern and independent form elements.
   - Less generic.

For Tripal core, I support either a TripalImporter specific to genome assemblies (C) or make a generic sub-analysis field (A).

**Comment by spficklin** [comment]
Quick question. Is this something we want for Tripal v3 or can we punt it to Tripal v4?

**Comment by laceysanderson** [comment]
I think we move this to Tripal 4 development. What do you feel @mpoelchau?

**Comment by mpoelchau** [comment]
@laceysanderson @spficklin sure, at this rate I think we can punt it to Tripal4 :).
