### ISSUE TITLE
Exception: String could not be parsed as XML in SimpleXMLElement->__construct() 

### ISSUE THREAD

**Issue by cornellyujy** [tripal/tripal#1036]
Hi,

I have installed drupal-7.x and tripal-7.x-2.x in my server. After finished, I got this error:
###################################################
Exception: String could not be parsed as XML in SimpleXMLElement->__construct() (line 16 of /var/www/html/sites/all/modules/tripal/tripal_core/includes/tripal_core.extensions.inc).
###################################################
This error is from this directory :/Tripal/Extension/Import Extensions.
Do you have some ideas? Thanks a lot

Best,

**Comment by cornellyujy** [comment]
And there is a warning here:
Warning: file_get_contents(http://tripal.info/rss/extensions.xml): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in tripal_core_extensions_form() (line 10 of /var/www/html/sites/all/modules/tripal/tripal_core/includes/tripal_core.extensions.inc).
Exception: String could not be parsed as XML in SimpleXMLElement->__construct() (line 16 of /var/www/html/sites/all/modules/tripal/tripal_core/includes/tripal_core.extensions.inc).

This is the code:
<?php

function tripal_core_extensions_form($form, &$form_state = NULL) {
  // Get the RSS feed XML from the tripa.info website and save it to
  // a temp file so that we don't have to keep pulling the XML
  // everythime the page is loaded. If the temp file is older than 1 hours
  // then we'll pull it again. The number of seconds in an hour is 3600
  $tmp_file = sys_get_temp_dir() . '/tripal_rss_extensions.xml';
  if (!file_exists($tmp_file) or time() - filemtime($tmp_file) > 3600) {
    $content = file_get_contents("http://tripal.info/rss/extensions.xml");
    file_put_contents($tmp_file, $content);
  }
  else {
    $content = file_get_contents($tmp_file);
  }
  $xml = new SimpleXmlElement($content);  ### **#line 16**  
  $namespace = "http://tripal.info/rss/extensions/";

**Comment by cornellyujy** [comment]
And there is a warning here:
Warning: file_get_contents(http://tripal.info/rss/extensions.xml): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in tripal_core_extensions_form() (line 10 of /var/www/html/sites/all/modules/tripal/tripal_core/includes/tripal_core.extensions.inc).
Exception: String could not be parsed as XML in SimpleXMLElement->__construct() (line 16 of /var/www/html/sites/all/modules/tripal/tripal_core/includes/tripal_core.extensions.inc).
This is the code:
3600) { $content = file_get_contents("http://tripal.info/rss/extensions.xml"); file_put_contents($tmp_file, $content); } else { $content = file_get_contents($tmp_file); } 
$xml = new SimpleXmlElement($content); ### #line 16 
$namespace = "http://tripal.info/rss/extensions/";

**Comment by par12005** [comment]
Hello @cornellyujy, thanks for submitting this issue!

It looks like the RSS feed at that location no longer exists, which is probably why you're getting this error.

My first question is: is there a reason you're using Tripal `7.x-2.x` instead of `7.x-3.x`? As far as I know, `7.x-3.x` does not have the problems you're describing here.

Next, if you are going to continue using `7.x-2.x`, could you provide a bit more information here about what you were trying to do when you came across this error? Is it appearing on every page, or only specific pages? In general, it's a good idea to use the provided [bug report template](https://github.com/tripal/tripal/issues/new?template=bug_report.md) when submitting a bug report.

**Comment by spficklin** [comment]
Thanks @par12005 for responding on this.  

@cornellyujy I'm going to close this out as there has been no further conversation since March.  If you would like further response please respond and we will reopen it. 

@all-contributors add @par12005 for question
