### ISSUE TITLE
Unable to submit OBO Loading job.

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#104]
When I select a OBO file from the dropdown on admin/tripal/loaders/chado_obo_loader and click the "Load OBO file" button I receive the following errors and a job is not scheduled.
```
Strict warning: Accessing static property OBOImporter::$file_required as non static in TripalImporter->create() (line 290 of /var/www/dev/kp-tripal3/sites/all/modules/tripal/tripal/includes/TripalImporter.inc).
Notice: Undefined property: OBOImporter::$file_required in TripalImporter->create() (line 290 of /var/www/dev/kp-tripal3/sites/all/modules/tripal/tripal/includes/TripalImporter.inc).
Cannot submit import: Cannot create importer: SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "tripal_import" does not exist LINE 1: INSERT INTO tripal_import (uid, class, submit_date, argument... ^
```

I'm using the most recent dev code; commit: e7310eee02a48c2c624fcd71d7d07f979fcce8e8.
I created this Tripal3 site from scratch (no upgrade) at commit f3ea847 and then pulled the most recent changes when I encountered an error. I did run the database updates.

**Comment by spficklin** [comment]
This should be fixed.  Can you test?

**Comment by laceysanderson** [comment]
Confirmed that it's fixed 👍
