### ISSUE TITLE
Documentation typo for "Manual Creation of a Tripal Field"

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1041]
This typo had me stuck for quite some time, so hopefully fixing it will help others in the future.
On page
https://tripal.info/http%3A//tripal.info/tutorials/v3.x/developers_handbook/custom-field/manual

`/sites/all/modules/[your_module]/includes/TripalField/[field_name]/[field_name].inc`
`/sites/all/modules/[your_module]/includes/TripalField/[field_name]/[field_name]_widget.inc`
`/sites/all/modules/[your_module]/includes/TripalField/[field_name]/[field_name]_formatter.inc`

should instead be

`/sites/all/modules/[your_module]/includes/TripalFields/[field_name]/[field_name].inc`
`/sites/all/modules/[your_module]/includes/TripalFields/[field_name]/[field_name]_widget.inc`
`/sites/all/modules/[your_module]/includes/TripalFields/[field_name]/[field_name]_formatter.inc`

**Comment by bradfordcondon** [comment]
thanks @dsenalik .  want to submit a PR fix for the credit? 
https://github.com/tripal/tripal/edit/7.x-3.x/docs/dev_guide/custom_field/manual_field_creation.rst
