### ISSUE TITLE
Agricola Pub Importer can be restored to functionality

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1043]
### System information

* Tripal Version: 7.x-3.x
* Drupal Version: 7.69
* PostgreSQL Version: 12.2
* PHP Version: 7.2

### Issue description

The issue is as described in closed issue #71, which is that the National Ag Library publication importer has been disabled because it doesn't work. I have made quite a few changes to restore it to working order.

Relevant pull request is #1044

One issue I was not able to resolve was to have year range limits on the search be functional. I have implemented this client-side, but the problem is that all search results must be downloaded, and are still displayed to the user on a test of the search. Nevertheless, this is still faster than the database queries that would need to be done to detect old publications that have already been loaded. If this unsightly hack is objectionable, we could just eliminate the year restriction fields.

**Comment by spficklin** [comment]
This was resolved with the PR. Thanks @dsenalik.
