### ISSUE TITLE
Add cvterm as a base table for Tripal entities

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#105]
This will be useful for phenotypes, in particular, because the attr_id specifies the trait but the phenotype table is mean to store actual measured values.  So it doesn't make sense to use the phenotype table as a base table.  Perhaps take the phenotype table out as a base table.

**Comment by spficklin** [comment]
Solution is 
1) To add 'cvterm' as a base table
2) If the user selects 'cvterm' then allow the user to specify a 'cv' that is the selector for the records.

**Comment by spficklin** [comment]
Done... Can you test @laceysanderson and let me know if this works for you?
BTW... you'll have to prepare your Chado site again to pick up some new ontology terms I added.

**Comment by laceysanderson** [comment]
Tested and this perfectly meets my needs 👍  Thanks!
Since this is in the main 7.x-3.x branch, I'm marking this as closed. :-)

**Comment by spficklin** [comment]
I just pushed a fix for another content type creation problem so you might want to pull again.

**Comment by laceysanderson** [comment]
Thanks, pulled and re-confirmed 👍
