### ISSUE TITLE
National Ag Library publication loader UTF-8 mixed with HTML entities

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1055]
### System information

* Tripal Version: 7.x-3.x
* Drupal Version: 7.69
* PostgreSQL Version: 12.2
* PHP Version: 7.2

### Issue description
Some publications imported from the National Ag Library will have UTF-8 characters mixed with characters encoded as HTML entities. When the information, for example the abstract, is passed through
mb_convert_encoding($pub['Abstract'], 'UTF-8', 'HTML-ENTITIES')
the entites are converted to UTF-8, but existing UTF-8 characters are corrupted. To make the matter worse, some HTML entities are double encoded e.g. `&amp;#x2018;` and these are only half-converted.

A second issue is that rarely, a publication will have two fields in the MARC record 35a "System Control Number", which represents the publication accession number at AGL. The second number will have a "ns" prefix. The simple solution is to ignore values with a "ns" prefix.

I am providing a pull request #1056 to correct these problems.

#### Steps to reproduce
Example of a publication with second "ns" accession number, create an importer for a publication with the title "Integrated Molecular and Morphological Studies of the Daucus guttatus Complex" and click Test Importer.
```
<datafield tag="035" ind1=" " ind2=" ">
    <subfield code="a">ns3947</subfield>
  </datafield>
  <datafield tag="035" ind1=" " ind2=" ">
    <subfield code="a">4782120</subfield>
  </datafield>
```

Example of a publication with UTF-8 + HTML entity corruption problems, load publication with the title "First Report of Ceratocystis lukuohia on Metrosideros polymorpha"

**Comment by spficklin** [comment]
Fixed with PR. Thanks @dsenalik
