### ISSUE TITLE
Broken link in PMC section of v3 users guide

### ISSUE THREAD

**Issue by scottcain** [tripal/tripal#1058]
## BUG/ERROR report
In https://tripal.readthedocs.io/en/latest/contributing/governance.html#the-tripal-project-management-committee-pmc https://tripal.readthedocs.io/en/latest/contributing/governance.html#committers and  there is a link whose anchors are  "guidelines for contribution(s)" but those links are broken.

Presumably, they should be fixed to point at https://tripal.readthedocs.io/en/latest/contributing/pull_requests.html#pull-request-pr-guideline

### System information
N/A

### Issue description
N/A

#### Steps to reproduce

N/A

```
error message
```

**Comment by spficklin** [comment]
Thanks @scottcain the bad link is now fixed.
