### ISSUE TITLE
Sequence box outputs wrong exon splice pattern for - strand mRNA features

### ISSUE THREAD

**Issue by mdondrup** [tripal/tripal#106]
This seems to be introduced in 2.1 release.

We are testing version 2.1 on our test system. When looking at features with alignment based sequence on the reverse strand, the exon coloring is seemingly wrong, showing the whole transcript as one exon. This did not happen on a 2.0 based Tripal. Here are some examples:  

https://blowfly-test.cbu.uib.no/?q=EMLSAT00000000011 compare to
https://licebase.org/?q=EMLSAT00000000011 (seemingly correct)

https://blowfly-test.cbu.uib.no/?q=EMLSAT00000000017
vs. https://licebase.org/?q=EMLSAT00000000017

But not for https://blowfly-test.cbu.uib.no/?q=EMLSAT00000000015 where the splicing is seemingly correct.

The correct gene structure can also be seen from View in Gbrowse link.

**Comment by spficklin** [comment]
Hi @mdondrup Thanks for posting these issues.   Apologies with the slowness in getting to them.  We've been focused on the Tripal v3 release.   I believe we'll be able to get to this and the other feature requests you've added once we get through the v3 business.

**Comment by mdondrup** [comment]
Now, the test server is also running 2.1, so there is no more difference. I would assume that the splice pattern in GBrowse is correct, but not always the one in Tripal. However, I checked the splicing pattern our examples and it seems to be correct now, so possibly there has been some progress in the meantime?

**Comment by laceysanderson** [comment]
Looks like this was fixed in PR #668. As such, I'm closing this issue but please comment if I'm mistaken :-)
