### ISSUE TITLE
Chado 1.2-1.3 upgrade - nonexistent sequences are not created

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal#1064]
### System information

* Tripal Version: 7.x-3.1 (540e0795e4bd63d97254e2d8ee058f361a8ed667)
* Drupal Version: 7.68
* PostgreSQL: 10.12
* PHP Version: 7.2.24

### Issue description

Upgrading from Chado 1.2 to 1.3 via the GUI process causes numerous errors about relations not existing. These relations are the sequences listed in the tripal_chado.install.inc file (linked below in **Steps to reproduce**) in the `tripal_chado_upgrade_chado_1_2_to_1_3_pre_alter()` function.

This code [was removed](https://github.com/tripal/tripal/commit/6cd8b469b8ead4304970eac7b650e8ee8431d78c#diff-1d2ba65756645ba7ee3de90f8f1066da) from the raw SQL file (default_schema-1.2-1.3-diff.sql) and executed with PHP due to 
```sql
CREATE SEQUENCE IF NOT EXISTS ...
``` 
functionality not existing prior to Postgres 9.5.

#### Steps to reproduce
Upgrade Chado from version 1.2 to 1.3 on a site/database where the sequences from https://github.com/tripal/tripal/blob/d40b939ed9330350b6b66896e8cf7e42c2047693/tripal_chado/includes/tripal_chado.install.inc#L504 do not exist for whatever reason (likely legacy site issues).

#### Errors
```
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] FAILED. Line  3025, 0SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "analysis_cvterm_analysis_cvterm_id_seq" does not exist:ALTER SEQUENCE analysis_cvterm_analysis_cvterm_id_seq OWNED BY analysis_cvterm.analysis_cvterm_id;
```
#### Full error screenshot: 
![Screen Shot 2020-05-27 at 3 09 48 PM](https://user-images.githubusercontent.com/9593623/83062215-47184700-a02c-11ea-8a74-ba3715dc2b75.png)

**Comment by Ferrisx4** [comment]
Note: for the purposes of i5k and Tripal 2 to Tripal 3 migration, including Chado upgrade from 1.2 to 1.3, uncommenting the CREATE SEQUENCE statements from the upgrade SQL file and adding IF NOT EXISTS allows the Chado upgrade to succeed on a test version of the site.

**Comment by spficklin** [comment]
Hi @Ferrisx4 .  This seems like a logical fix to me.  Did you want to submit a small little PR with your fix?

**Comment by Ferrisx4** [comment]
Hi @spficklin, I have a PR ready on my fork if we're OK with the hard requirement of Postgres 9.5+

**Comment by bradfordcondon** [comment]
https://www.postgresql.org/support/versioning/

the previous version's (9.4) final release was Feb 2020 so not so long ago but also past its EOL so there's an argument for dropping support for it.

**Comment by laceysanderson** [comment]
I'm not against the hard requirement of Postgres 9.5+. However, I think we should include a warning message about this requirement when people choose upgrade 1.2 => 1.3 as well as in RTD on install and in the README.

**Comment by laceysanderson** [comment]
PR Merged
