### ISSUE TITLE
"Annotation Term Accession" filter in searches not working

### ISSUE THREAD

**Issue by martacsilva** [tripal/tripal#1066]
Hi!
I have opened an issue on tripal_analysis_interpro (https://github.com/tripal/tripal_analysis_interpro/issues/31) but I haven't had an answer yet, and I'm not even sure if that is the right place. I am cross posting here in hopes that somebody will point me in the right direction.
I am trying to filter my features my Annotation Term Accession (IPR and GO terms). I have uploaded them and they show up in both the individual pages and the search results.
![Screenshot (60)](https://user-images.githubusercontent.com/47527249/84770490-8ef91100-afcf-11ea-9e41-e79ec59d9d0e.png)
My problem is that the filter "Annotation Term Accession" is not actually filtering anything? If I write an IPR term that I know exists and then click Search, it outputs the table as if it was empty search.
I'm not very well-versed in Tripal/Chado and the few things that I've tried haven't fixed the issue, and at this point I don't what else to try.

I would greatly appreciate your help! Or at least that you point me to the right place to ask this question.

Thanks again!

P.S.: Tripal v3, Drupal 7, IPR and GO terms uploaded to both Polypeptides and Genes but only visible in the first ones. I have the module tripal_analysis_expression and its search function is working well with the Gene's Annotation Terms Accessions

**Comment by laceysanderson** [comment]
Hi @martacds, unfortunately I'm not familiar with this extension module enough to help. Perhaps @spficklin may be able to help but he's away this week. I'm tagging him here in the hopes he sees this once he gets back but if there is still no answer in 2 weeks, please ping us again. Sorry for the delay you've been experiencing receiving an help!

**Comment by martacsilva** [comment]
Thanks for the quick answer! And no worries on the delay, it happens.
Alright, 2 weeks. See you then!

**Comment by martacsilva** [comment]
Hi!
It's been 2 weeks so I'm back :) Still need help with this issue.

Thanks!

**Comment by martacsilva** [comment]
Hi @laceysanderson @spficklin 

Sorry to keep bothering you with this, but I would really like to see if I can fix this issue.

Thank you!

**Comment by laceysanderson** [comment]
Commented on the original issue https://github.com/tripal/tripal_analysis_interpro/issues/31 -thank you for the reminder!

**Comment by martacsilva** [comment]
Thank you @laceysanderson !

**Comment by laceysanderson** [comment]
Closing out here for discussion to be carried on in the original repo
