### ISSUE TITLE
Multiple-insertion Chado Query API function

### ISSUE THREAD

**Issue by par12005** [tripal/tripal#1068]
## Feature Request/Discussion

* This feature does not attempt to solve an existing problem with Tripal (although it could help with the performance of several other Tripal tools)
* I am open to developing or collaborating on an extension module if this is not a good fit for Tripal Core

* This feature is Not Urgent

### Description
It would be nice to have a Chado Query API function that can insert multiple records in a single `InsertQuery` statement. Currently the only way to make bulk insertions into Chado while using the Chado Query API is to make multiple calls to the `chado_insert_record` function, which gets foreign key values where applicable, checks that there will be no conflicts with unique constraints, and checks that all not null fields will have some value. The function is very convenient, but it also needs to create a new `InsertQuery` statement for every call, which results in a significant drop in performance. For tools such as the GFF Importer and the FASTA Importer, which make many repetitive chado insertions, a function like this could greatly improve performance.

I have developed a similar function for the TPPS module which uses a single `InsertQuery` to insert multiple records to a table. If you would like to take a look at that function, you can find it [here](https://github.com/par12005/TPPS/blob/7.x-1.x/includes/chado_utils.inc#L141). If you would like to test the performance differences between using a single `InsertQuery` vs multiple, I have written some test code:

```php
<?php

function multiple_statements($records) {
  db_query('delete from test_table');
  $start = microtime(TRUE);
  foreach ($records as $record) {
    db_insert('test_table')
      ->fields($record)
      ->execute();
  }
  return microtime(TRUE) - $start;
}

function single_statement($records) {
  db_query('delete from test_table');
  $start = microtime(TRUE);
  $insert = db_insert('test_table')
    ->fields(array('col1', 'col2', 'col3'));
  foreach ($records as $record) {
    $insert->values($record);
  }
  $insert->execute();
  return microtime(TRUE) - $start;
}

if (!db_table_exists('test_table')) {
  db_query('create sequence test_table_seq start 1');
  db_query("create table test_table(
      col0 int primary key default nextval('test_table_seq'::regclass),
      col1 int,
      col2 text,
      col3 varchar(255)
    );");
}

$num_trials = 5;
$num_records = 100000;

$multiple_time = 0;
$single_time = 0;
$records = array();

for ($i = 1; $i <= $num_records; $i++) {
  $records[] = array(
    'col1' => $i,
    'col2' => "abcd$i",
    'col3' => "efgh$i",
  );
}

for ($trial = 1; $trial <= $num_trials; $trial++) {
  print_r("Starting trial $trial...\n");
  $multiple_time += multiple_statements($records);
  $single_time += single_statement($records);
}

$avg_multiple = $multiple_time / $num_trials;
$avg_single = $single_time / $num_trials;
print_r("Average multiple statement time: $avg_multiple\n");
print_r("Average single statement time:   $avg_single\n");
```

When I ran the tests myself, I got the following results:
Number of records | Multiple `InsertQuery` average time | Single `InsertQuery` average time
----- | ----- | -----
10,000 | 6.33s | 0.18s
100,000 | 64.14s | 1.86s

**Comment by risharde** [comment]
Version for testing released: https://github.com/risharde/tripal/blob/7.x-3.x-chadoapi-insertquery/tripal_chado/api/ChadoRecord.inc

- Function name changed to insertMultiple to conform with similar function names within the ChadoRecord class.
- Function name setInsertPartitionLimit(int) can be used to set partition limit to insert per specified number of rows (default: 10000)
- Function name ChadoRecord_test_insertMultiple() can be used within /devel/php for testing but make sure you don't have any records in chado.organism since it uses this table for testing.

**Comment by par12005** [comment]
Thanks @risharde! This looks pretty good! I just have a couple notes:

- It looks like the current implementation doesn't support loading default values, since it uses all of the table columns when specifying the fields: `->fields($this->column_names)`
- There isn't any validation for the `$records` array to make sure that all of the not null columns are provided and that there are no columns that the table doesn't have
- It would be nice to return the result of `$insert->execute()` since that can be used to determine the primary keys of the new records

I think it might make sense to have a separate class for multiple insert since the methods like `setValue()`, `getValue()`, etc. don't really make sense if you are working with multiple records. Maybe you could have a class that extends the `ChadoRecord` class like `ChadoRecordMultiple`? Then you could just have your overridden implementations of the `setValues()`, `find()`, `insert()`, etc methods within that class.

**Comment by risharde** [comment]
Thanks for the suggestions @par12005 , I'm going ahead and tag the other core devs just to see if they agree as well on the suggestions @laceysanderson @spficklin 

The second suggestion, I'm wondering if we need that validation versus the cpu time required to check each record before performing inserts. If the insert does not conform to the db specification, it should fail (safely) as is?

Third point, I definitely think that is useful so for sure I'll make a mod to this.

Curious what the other devs think about the separate class before I go ahead

Thanks for the suggestions!

**Comment by risharde** [comment]
@par12005 I tried returning results from the insertMultiple function but unfortunately it seems to only return the last primary key created, not the entire list. I'm not sure if there is a way to retrieve all primary keys / ids created using multiple inserts. If you have experience in this area, I'd loved to hear of some suggestions on this?

**Comment by par12005** [comment]
@risharde You're right, there is no way to return all of the id's created when doing a multiple insert. I was just thinking you could return the results of the last `$insert->execute()` statement. I have created a [PR on your fork](https://github.com/risharde/tripal/pull/1) with the changes I had in mind regarding return values and I also added an `$options` parameter since that can be used to alter the return value of the `$insert->execute()` statement (whether you want to return the sql statement, the number of affected rows, the last id, or `NULL`. The default is the last id).

**Comment by risharde** [comment]
@par12005 thanks for the PR, just merged it in to the code, I have never used the options array and I find there is little documentation regarding it but I surely believe it is good to have since the main db_insert function has it so we can continue to support the core functionality

**Comment by par12005** [comment]
Thanks @risharde! That was my thought exactly.

**Comment by laceysanderson** [comment]
See #1071 for design of a ChadoRecordList class aimed at filling this requirement.

**Comment by laceysanderson** [comment]
Closing as discussion is in #1071
