### ISSUE TITLE
Tripal 2 -> Tripal 3 Upgrade - Tripal Chado Views index issues

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal#1069]
# Background
A site is being upgraded from Tripal 2 to Tripal 3. After removing the previous Tripal and cloning the latest, and while attempting to enable tripal_chado, the following database error is received:
```
drush pm-enable tripal_chado
The following projects have unmet dependencies:                                                                            [ok]
tripal_chado requires redirect
Would you like to download them? (y/n): y
Project redirect (7.x-1.0-rc3) downloaded to /var/www/i5k/sites/all/modules/contrib/redirect.                              [success]
The following extensions will be enabled: tripal_chado, tripal_chado_views, redirect, tripal
Do you really want to continue? (y/n): y
WD tripal_chado_views: PDOException: SQLSTATE[23505]: Unique violation: 7 ERROR:  could not create unique index            [error]
"tripal_views_priority_idx2"
DETAIL:  Key (table_name, priority)=(eimage, 10) is duplicated.: CREATE UNIQUE INDEX tripal_views_priority_idx2 ON
tripal_views2 USING btree (table_name, priority); Array
(
)
 in tripal_chado_views_upgrade_v2_v3_pre_enable() (line 336 of
/var/www/i5k/sites/all/modules/contrib/tripal/tripal_chado_views/tripal_chado_views.install).
WD tripal_chado_views: PDOException: SQLSTATE[23505]: Unique violation: 7 ERROR:  could not create unique index            [error]
"tripal_views_join_pkey2"
DETAIL:  Key (view_join_id)=(708) is duplicated.: CREATE UNIQUE INDEX tripal_views_join_pkey2 ON tripal_views_join2 USING
btree (view_join_id); Array
(
)
 in tripal_chado_views_upgrade_v2_v3_pre_enable() (line 377 of
/var/www/i5k/sites/all/modules/contrib/tripal/tripal_chado_views/tripal_chado_views.install).
PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "tripal_views_priority_idx2" does not exist in          [error]
/var/www/i5k/includes/database/database.inc:2227
```

The tripal_views table with the offending key:
```sql
tripal_i5k=# select * from tripal_views where table_name='eimage' and priority=10;
 setup_id | mview_id | base_table | table_name | priority |     name     |              comment              
----------+----------+------------+------------+----------+--------------+-----------------------------------
       46 |          |          0 | eimage     |       10 | Chado Eimage |  
      288 |          |          0 | eimage     |       10 | Chado Eimage | TODO: please describe this table!
```
Various basic database integrity techniques have been employed including vacuuming and recreating indexes prior to running through the upgrade process and enabling tripal_chado. This includes using `reindex` on all tables and indexes involved, and then the entire database, all to no avail.

# Questions
1. Has anybody else experienced an issue like this?
2. From a Tripal/Chado point-of-view, are any of these relations expendable?

# Links
 - [Place in code where error originates](https://github.com/tripal/tripal/blob/e28738e8ebc9244e68f321c239db3bbe8c46e044/tripal_chado_views/tripal_chado_views.install#L312)
 - [Official upgrade process](https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/upgrade_from_tripal2.html)
 - [Site-specific (i5k) upgrade process](https://github.com/Ferrisx4/T2-T3_Ferris-Saga/blob/master/Saga_Condensed.md)

**Comment by laceysanderson** [comment]
> 1. Has anybody else experienced an issue like this?

I have not experienced this personally, nor have I heard of anyone else receiving this error.

> 2. From a Tripal/Chado point-of-view, are any of these relations expendable?

Tripal/Chado Views integrations can be easily rebuilt. The first step is to check whether you use this functionality to define any custom integrations. This can be done by going to Admin > Tripal > Data Storage > Chado > Chado Views Integrations (`yoursite/admin/tripal/storage/chado/views-integration`) and sorting your integrations by priority. Any integration with a priority not 10 will need to be exported and then re-imported afterwards. If all integrations have a priority of 10, you can simply click "Delete ALL Integrations" and confirm. This will remove the duplicate and then the system will rebuild all of the integrations. You should then be able to check tripal_views table and see that there are no duplicates which will allow the unique index to be rebuilt.

**Of course Test this on a Cloned site first**

**Comment by Ferrisx4** [comment]
Thanks @laceysanderson, this solution worked immediately. We had gone down a rabbit hole of exploring possible database corruption and I was thrown off by the process dying due to a specific row in the middle of the table, not realizing that there could exist no duplicates (there were in fact many other duplicates).
I'm going to close for now, thanks again.
