### ISSUE TITLE
Make it easier to select and copy from feature sequence box.

### ISSUE THREAD

**Issue by mdondrup** [tripal/tripal#107]
It might be unnecessarily tedious copying sequence to clip board under chrome and firefox on mac, I have seen users struggling even more on windows especially without a mouse.

- It is hard to select all the text in the box. Sometimes double click works, but not in all boxes, ⌘-A selects all the text on the web page. Therefore one has to scroll the text box to select everything. 
- While the sequence is displayed with line breaks on the web, when copying to text, these are converted to spaces, which confuses tools like Jalview to introduce gaps.

Maybe provide a "copy sequence to clipboard javascript button"?

**Comment by spficklin** [comment]
Great idea... We've also thought about adding a download button in Tripal v3 to each pane....

**Comment by spficklin** [comment]
This is a bit old, and is necessary but given the larger issues that have priority I'm not sure we can get to this quickly. @mdondrup do you have any ability to work out a suggested solution?

**Comment by laceysanderson** [comment]
@mdondrup I am going to close this issue since as @spficklin noted we just don't have time to develop a solution. We would welcome a PR from you if you work out a solution and we will keep in mind easy download of page data for Tripal 4. Thank you for your feedback ❤️
