### ISSUE TITLE
ChadoRecordList Class

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1071]
## Feature Request/Discussion

* This feature does  attempt to solve an existing problem with Tripal
* I am open to developing or collaborating on an extension module if this is not a good fit for Tripal Core

* This feature is URGENT

### Description

In order to manage multiple records at once it was suggested in the Tripal Dev Call that we add a new `ChadlRecordList` class.  

### Your Specific Use Case

Primarily, we're interested in a way to handle multiple inserts in one batch rather than individually.  The ChadoRecord class only handles one record at a time.   The idea is that someone could instantiate a ChadoRecordList class, add new ChadoRecords for insert and then those records could be batch "inserted" once a certain number of records are added (or manually).

### Generally Applicable

We believe this will help improve performance of loaders and can be used to test improvments to PR #1057.

### Additional information/screenshots

It was decided in the Core Dev Meeting that we would use this issue to discuss a design for this. Also, it requires approval by other members of the PMC (i.e. @laceysanderson and/or @bradfordcondon)

**Comment by spficklin** [comment]
@risharde @par12005 had indicated they will work on this.

**Comment by risharde** [comment]
Initial work, creation of the class file, added the insertMultiple code to the new class, included the ChadoRecordList.inc file to the module for boot

https://github.com/risharde/tripal/tree/7.x-3.x-chadoapi-chadorecordlist/

Thinking about if we need to change the current names used as the functions so any suggestions or confirmations about the current method names would be appreciated.

Also idea functions, something like insertRow($values) and maybe insert($rows). insertRow would append an additional row to the values variable while insert would set the values variable to what is in $rows.

Would an ordered insertRow be useful? something like insertRow($index_location, $values) which would insert the row into a particular index of the array?

**Comment by laceysanderson** [comment]
I think the method names should try to follow the ChadoRecords class for consistency. For example, 
```
$multiInsert= new \ChadoRecordList('organism');
foreach($lines as $line) {
    // Add values to the object to be saved for later insert in bulk.
    $multiInsert->addValues( ['genus' => $line[0], 'species' => $line[1] );

    // Save values. This will insert/update if the number of records has been reached.
   $multiInsert->save();
}

// Alternatively set all values at once.
$multiInsert->setValues([
    ['genus' => 'Tripalus', 'species' => 'databasica'],
    ['genus' => 'Tripalus', 'species' => 'ferox'],
    ['genus' => 'Chado', 'species' => 'schemata'],
    ['genus' => 'Drupalus', 'species' => 'databasica'],
]);
$multiInsert->save();
```

We should make sure that column checking, etc still happen in this class but do so in an efficient manner. For example, we can grab the table schema information once in the constructor rather then repeatedly.

I also thing this should handle both insert and update.

**Comment by risharde** [comment]
Thanks @laceysanderson . Request for discussion on this update based on @laceysanderson suggestion to conform to naming conventions inherited from ChadoRecord.

https://github.com/risharde/tripal/commit/9d8f819e15b3bc3e1eb5c97d10a53b5093173e7c

Things to discuss can be found by searching for string:
COMMENT: (FROM RISH)

**Comment by risharde** [comment]
Based on an hour meeting held on 09/02/2020, @spficklin generated the following specs for comments regarding ChadoRecordList class. If there's anything you think we need to change, please let us know. I'll begin working on this soon, thanks!

# ChadoRecordList Class
## Protected Members
// Holds the ChadoRecord objects.
$chado_records = array[]

// Holds the number of records 
$action_limit = 1000

// Holds the name of the table that this record belongs to.
$table_name = ''

// Holds the Drupal schema definition for this table.
$schema = ''

// If the action has already been performed  set this to TRUE.
$action_performed = FALSE

## Functions
**__contruct($table_name, $action_limit = 1000)**

**setValues($values = array[][])**
_Description_: receives a list of values that would be appropriate for the ChadoRecord->setValues() function but can have multiple elements.  

_Functionality_:  It will create a new ChadoRecord for element element of the $values array.
Iterates through the elements of the $values array and calls addValues on each one.

**addValues($values = array[])**
_Description_: creates a chado record for the value and adds it to the list.
_Functionality_ If $action_performed is TRUE do not allow a new value to be added. throw an exception.

**insert($return_keys = FALSE)**
_Description_: performs a bulk database insert.
_Functionality_:

1. Check to make sure the $action_perfomd is FALSE. If TRUE throw exception.
2. Start the SQL for the insert.
3. loop through all entries in the $chado_records array 
    * validate the current ChadoRecord is safe to be inserted with the ChadoRecord->validateInsert. 
    * Add to the SQL for the insert (i.e. VALUES placeholders and actual values array)
6. perform the bulk insert
7. set $action_performed =  TRUE
8. If the $return_keys is TRUE then 
    * execute the find() function to get the matching inserted records.
    * loop through the $chado_records array and put the keys into an array
    * return the array of keys.
12. else  return TRUE
14. On failure, throw an error.

**update()**

**delete()**

**find()**
_Description_: performs a bulk select

_Functionality_:

1. Loop through all entries in the $chado_records array and build the SQL for selecting records.
2. Loop through the results, create a new ChadoRecord array.
3. Updates the $chado_records array to use the new ChadoRecord list
4. Return the $chado_records list.
5. On failure, throw an error.
6. Example code for bulk inserts can be found in the GFF loader in Tripal v3 branch 1040-tv3-gff3_performance.

**reset()**
_Description_:  resets the chado record list to be empty.

_Functionality_
Set the $chado_record variable to an empty array
Sets the $action_performed to FALSE

**setActionLimit()**

**getActionLimit()**

**getChadoRecords()**
_Description_: returns the $chado_records array.

**getChadoRecord($pkey)**
_Description_:  returns a ChadoRecrod object from the list that matches the primary key.

**getTable()**
_Description_:  performs the same functionality as the ChadoRecord->getTable()

**getSchema()**
_Description_:  performs the same functionality as the ChadoRecord->getSchema()

**Comment by risharde** [comment]
@spficklin also suggested that ChadoRecordList should not extend ChadoRecord but rather use the ChadoRecords class to create records.

**Comment by risharde** [comment]
Main upates: https://github.com/risharde/tripal/tree/7.x-3.x-chadoapi-chadorecordlist
Commits: https://github.com/risharde/tripal/commits/7.x-3.x-chadoapi-chadorecordlist

This code uses some of Stephen/Peter's code from GFF for inserts and then uses an additional clause in SQL to return the insert ids so validation is not necessary - still to test any performance gains but 1000 records takes about 6ms on a single core running at 60%

**Comment by spficklin** [comment]
In the process of testing the TripalFile module I got the following error:

```
ChadoRecord::setValue(). The column named, "is_obsolete", requires a value for the table: "cvterm".
[site http://default] [TRIPAL ERROR] [TRIPAL_JOB] ChadoRecord::setValue(). The column named, "is_obsolete", requires a value for the table: "cvterm".
```

It seems somewhere in last few months when we updated this class we failed to add in a triple equals, `===`,  when comparing values in some places.  So, it was interpreting a 0 value as a NULL value when trying to do a comparison.  This is an easy fix and I'll do a PR.

**Comment by spficklin** [comment]
This class will be deprecated in Tripal v4 so I'm closing this issue.
