### ISSUE TITLE
Upgrade to Tripal v3 stalled at "Prepare Chado" with error: ERROR:  relation "tripal_custom_tables" does not exist

### ISSUE THREAD

**Issue by mdhar1980** [tripal/tripal#1072]
Hello,

I am trying to upgrade from Tripal v2 to v3. I was able to make it much of the way through the guide for Tripal 3 upgrade (https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/upgrade_from_tripal2.html), but I'm stalled at the Prepare Chado step. I get a lot of errors of the type:

```
WD tripal_chado: PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "tripal_custom_tables" does not exist                [error]
LINE 1: SELECT * FROM tripal_custom_tables WHERE table_name = 'conta...
                      ^: SELECT * FROM {tripal_custom_tables} WHERE table_name = :table_name; Array

```
Up until that point, I was able to get the other steps to work. However, I was not able to enable any modules using Drush. I had to use the Modules page on the website. With Drush, I would get errors like the following. I'm not sure if that's related:

```
DatabaseSchemaObjectExistsException: Table chado_bundle already exists. in DatabaseSchema->createTable() (line 663 of /var/www/html/includes/database/schema.inc).
Drush command terminated abnormally due to an unrecoverable error.  

```
and:

```
DatabaseSchemaObjectExistsException: Table redirect already exists. in DatabaseSchema->createTable() (line 663 of /var/www/html/includes/database/schema.inc).
Drush command terminated abnormally due to an unrecoverable error. 

```

Thanks for any insight.

--Michael

**Comment by bradfordcondon** [comment]
hi @mdhar1980 .
`tripal_custom_tables` is defined upon enabling the `tripal_chado` module.  Your error indicates the module was not successfully installed.

https://github.com/tripal/tripal/blob/5b10e3616314307c564058b0c2f9c731d3d42738/tripal_chado/tripal_chado.install#L159

Similarly your error that `Table chado_bundle already exists` indicates that the `chado_bundle` table defined by the `tripal_chado` module already existed, so something has likely gone wrong.  

Is this a live site with production data?  Can you try disabling and re-enabling the `tripal_chado` module?  If you look in your database, is the `tripal_custom_tables` present?

**Comment by mdhar1980** [comment]
Hi, @bradfordcondon,

Thanks for your response. This is a development version, thankfully, so in theory I can disable modules. However, both through drush and the GUI, the same error regarding the nonexistent table is thrown when trying to disable. I will probably have to restore to a backup. Before that, I will try looking into the database once I can remind myself how that is done.

Thanks,
Michael

**Comment by mdhar1980** [comment]
I can confirm that I'm unable to disable tripal_chado. Running the drush disable command, I get the following errors:

```
WD php: PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "tripal_custom_tables" does not exist                         [error]
LINE 1: SELECT table_name FROM tripal_custom_tables
                               ^: SELECT table_name FROM {tripal_custom_tables}; Array

(
)
 in chado_get_table_names() (line 509 of /var/www/html/sites/all/modules/contrib/tripal/tripal_chado/api/tripal_chado.schema.api.inc).
Cannot modify header information - headers already sent by (output started at /usr/share/php/drush/includes/output.inc:37)               [warning]
bootstrap.inc:1499
PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "tripal_custom_tables" does not exist
LINE 1: SELECT table_name FROM tripal_custom_tables
                               ^: SELECT table_name FROM {tripal_custom_tables}; Array
(
)
 in chado_get_table_names() (line 509 of /var/www/html/sites/all/modules/contrib/tripal/tripal_chado/api/tripal_chado.schema.api.inc).
Drush command terminated abnormally due to an unrecoverable error.
```


Attempting to disable via the website Modules page (where Tripal Chado IS listed as enabled), there is, of course, a cascade of modules that require Tripal Chado that would have to be disabled first. The lowest on that cascade is Tripal Feature. Attempting to uncheck it gives the following error:

`PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "tripal_custom_tables" does not exist LINE 1: SELECT table_name FROM tripal_custom_tables ^: SELECT table_name FROM {tripal_custom_tables}; Array ( ) in chado_get_table_names() (line 509 of /var/www/html/sites/all/modules/contrib/tripal/tripal_chado/api/tripal_chado.schema.api.inc)`

**Comment by mdhar1980** [comment]
Hi, again, @bradfordcondon -- looking into the database, I see the following. So, for many of the tables in the database, I see an original and one with "2" at the end. I'm guessing that should not be? Perhaps the result of previous attempts to upgrade (I've already tried once, failed, and reverted to a backup to try again). Or perhaps from trying to install Tripal in the beginning, failing and trying again? For tripal_custom_tables, however (as well, as, it seems, some others), there is ONLY tripal_custom_tables2. Below is a sample of what I see in the database:

```
 public | tripal_custom_quota                            | table | drupal
 public | tripal_custom_quota2                           | table | drupal
 public | tripal_custom_tables2                          | table | drupal
 public | tripal_cv_defaults                             | table | drupal
 public | tripal_cv_obo2                                 | table | drupal
 public | tripal_ds                                      | table | drupal
```

**Comment by bradfordcondon** [comment]
@mdhar1980  yes this indicates that you have tables left over from a failed upgrade attempt from tripal 2 to 3, and the presence of both  (for example `tripal_custom_quota` and `tripal_custom_quota2`)  is going to prevent upgrading.

These tables are present in your backup?  If you can restore a backup.   If you cant roll back to a state where you only have a single copy of the tables, you'll probably have to investigate which one is empty and safe to drop, and rename them to the table name without the "2" suffix.

**Comment by mdhar1980** [comment]
So, weirdly, the tripal_custom_quota2 sorts of tables do NOT appear on our live site's database. So, I backed up our development version to the live site's SQL backup -- and the "2" type tables reappeared! So, I went through and dropped the duplicates or renamed if it was the only one that appeared.

Then, going through the upgrade, many of the same errors as before reappeared. As did many of the "2" tables. I was able to get past the errors and get the Tripal 3 upgrade completed by renaming the "2" tables when the original was not present. Finally, however, at Migration, content cannot be published, and there were errors related to Pub_Import when preparing Chado, though that job completed. I went in and fixed table tripal_pub_import, which had a 2. Then tried rerunning the prepare Chado job, but it did not complete, with the error: 

```
Job execution failed: PDOException: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint                                [error]
"tripal_bundle_variables_tripal_bundle_variables_c1_key"
DETAIL:  Key (bundle_id, variable_id, rank)=(1, 0, 0) already exists. in /var/www/html/includes/database/database.inc:2227
```
I may have to restore to backup again and try again, making sure to get tripal_pub_import2 fixed before Chado prep job. But if you have any insights as to why I keep getting these table2 things or why publication might be failing, please let me know.

Thank you!
--Michael

**Comment by mdhar1980** [comment]
This is the error I get on the publishing step:

```
INFO (PUBLISH_RECORDS): There are 1 records to publish.
WD tripal: PDOException: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint                                           [error]
"tripal_bundle_variables_tripal_bundle_variables_c1_key"
DETAIL:  Key (bundle_id, variable_id, rank)=(1, 0, 0) already exists.: INSERT INTO tripal_bundle_variables (bundle_id, variable_id, value) VALUES
(:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2); Array
(
)
 in drupal_write_record() (line 7460 of /var/www/html/includes/common.inc).
[site http://default] [TRIPAL ERROR] [PUBLISH_RECORDS] Could not publish record: Could not create entity.
Could not save the TripalEntity: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint                                   [error]
"tripal_bundle_variables_tripal_bundle_variables_c1_key"
DETAIL:  Key (bundle_id, variable_id, rank)=(1, 0, 0) already exists.
```

**Comment by mdhar1980** [comment]
This is what I see in the tripal_bundle_variables table:
<img width="522" alt="Screen Shot 2020-08-08 at 2 46 15 PM" src="https://user-images.githubusercontent.com/18684260/89718663-15a1ed00-d986-11ea-9861-bcc8f2f69343.png">

**Comment by mdhar1980** [comment]
This is resolved. There were remnants from a failed upgrade remaining in the database which I was able to remove by creating a fresh database and "restoring" it to the pre-upgrade backup. Tripal 3 upgrade then worked. Thanks!

**Comment by spficklin** [comment]
Thanks @mdhar1980 for the udpate!
