### ISSUE TITLE
Handling legacy content from T2 GFF Loader in Tripal 3

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal#1077]
In the Tripal 2 GFF loader, mRNA features such as polypeptides were loaded as `part_of` the parent whereas in the Tripal 3 GFF loader, these are now loaded as `derives_from`.
As such, in Tripal 3, the Protein Sequence field expects the `derives_from` relationship as well, which will only show features loaded with the Tripal 3 GFF loader, and **not** ones loaded from the Tripal 2 GFF loader.

There seems to be two possible paths for sites upgrading from Tripal 2 to Tripal 3 to allow these fields to be properly populated:
 1. Update the existing relationships of this type in the database from `part_of` to `derives_from` _during the migration process_.
 2. Alter the Protein Sequence field to show sequences of both relationship types.

**Comment by laceysanderson** [comment]
I personally think option 2 is best as it will support sites which have already completed the upgrade. Furthermore, I think it's important to minimize altering legacy chado data as much as possible.

There are two paths to fix this issue:
1. Simply add the `part_of` cvterm [here](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalFields/data__protein_sequence/data__protein_sequence.inc#L96)
2. Add configuration to the field to allow the relationship cvterm be a configurable list of terms including these two by default. This is more involved and would involve creating an [instance_settings_form() as done in the relationship field](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalFields/sbo__relationship/sbo__relationship.inc#L693).

Both are acceptable though the second future proofs the field in case others have data with different terms.

**Comment by bradfordcondon** [comment]
I vote for @laceysanderson 's first proposal (adding `part_of` to the field query).  If others have different relationship terms we could vote to support but i don't think its likely, as this is arising specifically because of how Tripal 2 loaded the data.  So building a UI etc not worth the work.

I have to say that I would also support converting the relationships from `part_of` to `derives_from` given that [I don't believe part-of is the proper term for the mRNA/polypeptide relationship](http://wiki.geneontology.org/index.php/Annotation_Extension_Relation:part_of) but then we're writing a migration script that is messing with people's data which is probably an "overbearing" solution.

**Comment by Ferrisx4** [comment]
Thanks @laceysanderson and @bradfordcondon 
After discussing it, we agree, Lacey, that adding `part_of` to the clause will be the simplest solution that should work for all sites affected.
For your second path suggestion, we had also discussed making it configurable. Are there any other relationship terms that would be applicable specifically to mRNA and polypeptides?

Bradford, as for your suggestion of including this in a migration script, we can leave it up to individual sites if they want to convert their data or not so as to avoid being overbearing. For instance, i5k plans to convert so that all data previously loaded and all data that will be loaded in the future will be using the same _correct_ relationship term. This would also make the text change in the **Relationships** field to use the proper term.
If a site doesn't want to do this, at least Lacey's solution above will get the sequences to appear on pages.

**Comment by Ferrisx4** [comment]
In the meantime, I've tested adding `part_of` the SQL clause for that field. The sequences are shown.
https://github.com/Ferrisx4/tripal/commit/8ff7ed636959bbfc3465c5cfc729eb7760638040
