### ISSUE TITLE
Content Page Time Values Incorrect

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal#1078]
### System information

* Tripal Version: 3 (multiple sites)
* Drupal Version: 7

### Issue description
Certain time-based fields, such as `Time Last Modified` and `Time Accessioned` on content pages such as Gene or mRNA do not read the values from the database but instead report the current time, or when the page was loaded. This is seen on multiple Tripal 3 sites.

#### Steps to reproduce

Load up a content page that has `Time Last Modified` and `Time Accessioned` fields and observe that these fields have the current time. Upon refresh, it will always reflect the current time (see caching note below).

##### Page load:
![1_49](https://user-images.githubusercontent.com/9593623/90169599-cfc19c00-dd6c-11ea-85c5-b4e0ec9b47a3.png)

##### After refreshing a few minutes later:
![1_56](https://user-images.githubusercontent.com/9593623/90169616-d51ee680-dd6c-11ea-9475-cf888c5f6bdf.png)

#### Notes
 - On the Hardwoods site, and possibly others, the time is reported on the page as +1 hour to whatever time it is (server is set to EDT). This may be an issue of time zone support on that field which is configurable.
 - Caching: This bug is affected by caching, refreshing on some sites is not enough to get the value to change, but the originally reported value is still incorrect.

**Comment by Ferrisx4** [comment]
Due to some [comments](https://github.com/tripal/tripal/blob/c9940778f7c29f4640e9d5d8a313804a23cc0ed9/tripal/includes/tripal.fields.inc#L868) and [descriptions](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/tripal_chado.fields.inc#L1066) in the code, it appears that this might be partly intentional. Perhaps the Discussion tag might be appropriate here

**Comment by Ferrisx4** [comment]
After discussing it briefly during a Tripal Dev meeting, it seems that having these two fields display the current time is **not** intentional. The code was only favoring the current time over the value stored in the database for the purposes of create/edit content forms.

Setting the field to display as "Plain" instead of "Date and Time" makes the field display the value from the database, but not in a pretty format: `2013-10-18 13:58:24.761174`.

**Comment by spficklin** [comment]
Oops I just added a similar issue #1147 and a fix in PR #1148

**Comment by spficklin** [comment]
I believe this is fixed with PR #1148.
