### ISSUE TITLE
Error: There are 1 jobs queued.  Calling: tripal_chado_prepare_chado() 

### ISSUE THREAD

**Issue by MoradMokhtar** [tripal/tripal#1080]
Dear, 
The error occurs when setup Tripal 3. 
Chado is installed but Tripal has not yet prepared Drupal and Chado. Please prepare both Drupal and Chado before continuing. and when I clicked the button prepare this site, the following error appears "2020-08-23 17:28:38: There are 1 jobs queued. 2020-08-23 17:28:38: Job ID 12. 2020-08-23 17:28:38: Calling: tripal_chado_prepare_chado() " 
*Error: Call to undefined function drush_print() in tripal_chado_prepare_chado() (line 214 of /var/www/html/sites/all/modules/tripal/tripal_chado/includes/setup/tripal_chado.setup.inc).*
what I can do

**Comment by bradfordcondon** [comment]
Hi @MoradMokhtar 

Are you following the [Tripal setup guide?](https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/manual_install/install_tripal.html#prepare-chado-and-drupal)

Your error looks like you don't have drush installed: here is the page for [how to install drush](https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/drush_installation.html#drush-installation).    Drush is the command-line interface for interacting with Drupal.  You'll want to ensure you have the correct version of Drush installed for your site's Drupal version.

**Comment by MoradMokhtar** [comment]
Dear,  @bradfordcondon 
Thanks for your response
I checked the drush --version from web console   (Drush version 8.4.1) 
and cheked drupal --version by http://websit/CHANGELOG.txt and it look the follwing 
Drupal 7.xx, xxxx-xx-xx (development version)
-----------------------
Drupal 7.69, 2019-12-18
-----------------------
- Fixed security issues:
   - SA-CORE-2019-012
Drupal 7.68, 2019-12-04

**Comment by bradfordcondon** [comment]
those Drush and Drupal versions are compatible.

Are you running the Chado prepare job via `drush trp-run-jobs --username=administrator --root=$DRUPAL_HOME` as described in the guide (not via the Drupal interface)?

**Comment by MoradMokhtar** [comment]
Dear, @bradfordcondon 
Thanks for your effort
I searched a lot and I read that php7.4 not compatible, so I changed it and used php7.3 and Now I try to install again 
I changed database and run set up as mention at  Tripal setup guide, but Now setup 1 run but in the end of step "Finished"  as attach file but now error appear (Notice: Trying to access array offset on value of type int in element_children() (line 6656 of /var/www/html/includes/common.inc).) 

at the end of the page 
Congratulations, you installed Drupal!
Review the messages above before **visiting your new site**
and when I clicked **visiting your new site** that open empty web page
![Screenshot from 2020-08-24 22:07:39](https://user-images.githubusercontent.com/70106628/91091266-a64f1d00-e656-11ea-9998-18213410ae65.png)

**Comment by bradfordcondon** [comment]
looks like it was successful.  If you click on the "visit your new site" button, do you have a functional Drupal site?  That error notice you see isnt particular concerning.

**Comment by MoradMokhtar** [comment]
yes when I clicked it it opened web page with the same massage error 
![Screenshot from 2020-08-24 23:07:19](https://user-images.githubusercontent.com/70106628/91096821-f0d49780-e65e-11ea-981d-bba51a74c79e.png)

and then I try to install as mention 
by use web consol "cd $DRUPAL_HOME/sites/all/modules" 
drush pm-download entity
the below error apear
![Screenshot from 2020-08-24 23:03:05](https://user-images.githubusercontent.com/70106628/91097002-3b561400-e65f-11ea-94c8-128e895721ba.png)

**Comment by bradfordcondon** [comment]
Your posted error indicates PHP cant load the postgres PDO driver.  This error leads me to believe that postgres isnt correctly configured with PHP, see for example https://stackoverflow.com/questions/10085039/postgresql-pdoexception-with-message-could-not-find-driver

I think you'll want to take a step back and confirm that your system requirements are all met.  Can you reach the Drupal system admin area (`Administration Toolbar > Reports > Status Report`)?   Either way, check your postgres version, that PHP has the postgres driver enabled...
Regarding PHP 7.3,  I think the Tripal community is only using up to PHP 7.2 so i can't confirm that we'll be compatible with 7.3. I dont think its the cause of this error but it probably will result in more notices etc.

**Comment by MoradMokhtar** [comment]
@bradfordcondon
Many Thanks for your support, I dropped this setup from an online host and started from the first in localhost and it's run successfully
