### ISSUE TITLE
OBO Importer fails loading obi.obo

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1086]
### System information

* Tripal Version: 3.4
* Drupal Version: 7.70
* PostgreSQL Version: 12.4
* PHP Version: 7.2.33

### Issue description

A pull request #1087 is provided to fix several errors, and a few assorted typographical errors.

Loading the OBI ontology as found at http://www.obofoundry.org/ontology/obi.html
failed due to several problems.

Line 310 the example URL is no longer correct, this was updated here and at line 358

This obo file does not include a default namespace, and the loader web form indicated "Additionally, if a default namespace is not provided in the OBO header this name will be used as the default_namespace." but was not the case. New code was added at line 890 to make this true.

Some warnings due to more strict behavoir with a more recent php version have received additional array_key_exists() checks, e.g. this error:
array_key_exists() expects parameter 2 to be array, null given OBOImporter.inc:925

Line 986 "decrease" changed to "increase" in printed message.

Error message "TypeError: Argument 2 passed to t() must be of the type array, integer given, called in .../sites/all/modules/tripal/tripal/includes/TripalImporter.inc on line 580" was due to an extra t() call wrapping a logMessage() call line 1019.

Line 2082 a variable was assigned to itself instead of using the variable created in the preceding line.

#### Steps to reproduce
Tripal → Data Loaders → Chado Vocabularies → OBO Vocabulary Loader → ADD A NEW ONTOLOGY OBO REFERENCE
New Vocabulary Name: obi
Local File: path/obi.obo
Import OBO File

**Comment by laceysanderson** [comment]
PR Merged
