### ISSUE TITLE
PHP 7.4 + 8.0 Issues

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1088]
Just pointing out that for PHP 7.4 the `array_key_exists` [function is deprecated.](https://www.php.net/manual/en/migration74.deprecated.php#:~:text=Using%20array_key_exists()%20on%20objects%20is%20deprecated.,property_exists()%20should%20be%20used.)  Ubuntu 20.04 uses php 7.4 so as folks upgrade they will see this warning on their Tripal sites.  

![image](https://user-images.githubusercontent.com/1719352/95007709-9e748800-05c7-11eb-9a7b-04b97a906cec.png)

**Comment by spficklin** [comment]
I'm renaming this as a place to post problems that occur with PHP 7.4

**Comment by bradfordcondon** [comment]
> array_key_exists

I think it’s only deprecated for use on objects, not arrays

For others finding and fixing this usage, note that `property_exists` reverses the arguments for the property/key vs the object/array.  See my PR #1096

**Comment by spficklin** [comment]
More issue with 7.4 that don't show up on earlier versions of PHP.

![image](https://user-images.githubusercontent.com/1719352/96526114-8d678000-1231-11eb-8bc7-89abaa33aa62.png)

**Comment by laceysanderson** [comment]
![Screen Shot 2020-11-13 at 6 13 43 PM](https://user-images.githubusercontent.com/1566301/99132467-f1385b00-25db-11eb-8c2b-2d97645dc2ba.png)

**Comment by lilicamd** [comment]
Tripal Crop Docker
![Screenshot from 2021-02-11 16-41-34](https://user-images.githubusercontent.com/8963698/107713332-3ece6d80-6c88-11eb-9ef0-c50a1d0461a7.png)

**Comment by lilicamd** [comment]
Tripal Crop Docker
![Screenshot from 2021-02-11 17-13-16](https://user-images.githubusercontent.com/8963698/107715453-8e169d00-6c8c-11eb-8eb6-300b91a5641f.png)

**Comment by laceysanderson** [comment]
Heads up: I need to upgrade KnowPulse + Tripal Crop Docker to PHP8 thanks to urging from our IT department. Since there are still a number of incompatibilities, I've started a branch `1088-update-to-php8` to resolve them :-) Feel free to post more that you've noticed here so I can do a more thorough job!

**Comment by dsenalik** [comment]
I have a tripal field issue that was a warning before, but with php8 becomes an error rendering a page not editable. This is while editing an "assay" page:

**php 7**: Warning: array_key_exists() expects parameter 2 to be array, null given in sep__protocol_widget->form() (line 44 of .../sites/all/modules/tripal/tripal_chado/includes/TripalFields/sep__protocol/sep__protocol_widget.inc).

**php 8**: TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in sep__protocol_widget->form() (line 44 of .../sites/all/modules/tripal/tripal_chado/includes/TripalFields/sep__protocol/sep__protocol_widget.inc).

Easy to fix, I will provide a pull request

**Comment by spficklin** [comment]
I think this is fixed with PR #1291 . Closing Thanks for posting the issue and the fix :-)

**Comment by spficklin** [comment]
Whoops, I guess this issue was meant to be a catch-all for PHP 7.4 issues and then 8.0 but I think I'll leave it closed unless @laceysanderson or @Ferrisx4 think otherwise.   It's easier to just post each issue separately and fix them rather than have an open ended issue.
