### ISSUE TITLE
Alter hooks for the field info and instances info arrays.

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1089]
### Description
When creating a new extension module that creates custom tables we want to be able to create fields for the columns of those tables, but the `tripal_chado` module automatically generates fields for all new content types that are mapped to Chado tables.   This isn't a problem if the extension module comes before the `tripal_chado` module when the `hook_file_bundle_fields_info` is called. But if not, then the the extension module has no way to adjust any of the default settings set by the `tripal_chado` module.  We need an alter hook.

I propose two new hooks:
`hook_bundle_fields_info_alter(&$info, $entity_type, $bundle)`: for altering the info array of the fields.
`hook_bundle_instances_info_alter(&$info, $entity_type, $bundle) `:   for altering the info array of the field instances.

Unfortunately, these hooks can allow a module to change field settings for fields that they do not manage, but this isn't an uncommon problem with any Drupal hook.

**Comment by spficklin** [comment]
I should also add. The reason I need this is because I'm working on the Tripal v3 compatible Tripal File module and it adds several new custom tables to Chado for associating files with Chado data.  the `tripal_chado` module automatically creates the fields (yeah!) but I need to adjust some of instance defaults.

**Comment by spficklin** [comment]
So apparently, the alter functions already were supported but not documented in the API and also were not called everywhere they should have been.  I updated the PR to fix this.  So this is actually a bug too because the code in the cron job that updates the dashboard notifications isn't calling the alter hooks like it should.

**Comment by laceysanderson** [comment]
PR Merged
