### ISSUE TITLE
Issue with tripal_ds and legacy templates

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#109]
This code was added to line 780 of the tripal_chado.module file in the tripal_chado_theme function:

```
        db_delete('tripal_ds')
          ->condition('entity_type', 'TripalEntity')
          ->condition('bundle', $bundle->name)
          ->execute();
```
I think this code should be in the tripal_ds module rather than the tripal module as the table won't exist if the tripal_ds module isn't enabled.  Also, the 'entity_type' field doesn't exist in the table and the code breaks.

**Comment by shawnawsu** [comment]
That's very odd, I must have accidentally dropped that in the wrong place. It's been removed in the latest 7.x-3.x-dashboard push.
