### ISSUE TITLE
Infraspecific nomenclature updates in tripal_chado.organism.api.inc

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1093]
## BUG/ERROR report

Pull request #1095 

### System information

* Tripal Version: 3.4
* Drupal Version: 7.70
* PostgreSQL Version: 12.4
* PHP Version: 7.2.33

### Issue description
Chado v1.3 introduced infraspecific nomenclature in the organism table. I am providing several changes to  
`tripal_chado/api/modules/tripal_chado.organism.api.inc`  
to better implement this for sites that use this feature.

SQL calls with ORDER BY genus, species now check if the infraspecific nomenclature is present, and if so then include them in the ORDER BY. This results in an alphabetical list in, for example, the biosample loader  
Tripal → Data Loaders → Chado Biological Sample (Biomaterial) Loader

Code like  
`= $org->genus . ' ' . $org->species;`  
replaced with  
`= chado_get_organism_scientific_name($org);`

Fix trailing white space in `chado_get_organism_scientific_name()` related to the 'no_rank' cv term

Various typos or spelling corrections

#### Steps to reproduce

Site must be Chado V1.3 and using infraspecific nomenclature

Tripal → Data Loaders → Chado Biological Sample (Biomaterial) Loader

In the "Organism" field, list of organisms will not be alphabetically sorted by infraspecific names, e.g.  
Daucus carota subsp. sativus  
might come before  
Daucus carota subsp. carota

**Comment by laceysanderson** [comment]
PR Merged, thanks for the fix!
