### ISSUE TITLE
sio__references tripal field hits php execution limit, time out if too many features present

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1100]
I have a genome publication, and if I try to view the publication it times out due to php execution time limit (currently set at 30 seconds). The reason is that this publication is linked to a large number of genetic markers in several linkage maps used for that publication.
If I increase the php time limit, eventually the page is rendered in a couple of minutes, with an enormously long list of markers.

The time seems to be occupied mostly in the call to `chado_generate_var()`

It would be helpful to have a mechanism to limit the number of records of a given type that are returned. Does anyone have any suggestions?

**Comment by spficklin** [comment]
HI @dsenalik I'm actually working on creating new fields for an extension module I'm working on.  So since I'm in the "fields" zone I can take a look at this field for you.   Increasing the PHP limit could potentially get you around the problem but it still means your users are waiting a very long time for the page to load, which isn't good.

**Comment by spficklin** [comment]
Just curious @dsenalik how many records do you have linked to this publication?

**Comment by dsenalik** [comment]
I have 2505 total references. 2473 of those are genetic markers, the major culprit. The page took just over 2 minutes to render on my test site with php execution limit increased.

**Comment by spficklin** [comment]
@dsenalik can you test this branch and see if it fixes the problem: `1100-tv3-references_field`

**Comment by dsenalik** [comment]
After about 40 seconds I received these errors:

- Notice: Undefined index: foreign keys in sio__references->load() (line 106 of /var/www/2020-02-18/drupal-7.69/sites/all/modules/tripal/tripal_chado/includes/TripalFields/sio__references/sio__references.inc).
- Warning: Invalid argument supplied for foreach() in sio__references->load() (line 107 of /var/www/2020-02-18/drupal-7.69/sites/all/modules/tripal/tripal_chado/includes/TripalFields/sio__references/sio__references.inc).
- Warning: array_key_exists() expects parameter 2 to be array, null given in sio__references->load() (line 119 of /var/www/2020-02-18/drupal-7.69/sites/all/modules/tripal/tripal_chado/includes/TripalFields/sio__references/sio__references.inc).
- PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "chado.tripal_megasearch" does not exist LINE 1: ...tripal_megasearch_pub LINK INNER JOIN chado.trip... ^: SELECT REF.* FROM chado.tripal_megasearch_pub LINK INNER JOIN chado.tripal_megasearch REF on LINK.stockprop_id = REF.stockprop_id WHERE LINK.pub_id = :pub_id; Array ( [:pub_id] => 509 ) in chado_query() (line 1790 of /var/www/2020-02-18/drupal-7.69/sites/all/modules/tripal/tripal_chado/api/tripal_chado.query.api.inc).

I can investigate further later today.

**Comment by spficklin** [comment]
hmmm.... I think the megasearch module must have a `tripal_megasearch_pub` table but not a corresponding tripal_megasearch table.?  I'm not too familiar with that module.  But I think I can add in an easy fix to check for this.

**Comment by dsenalik** [comment]
Correct, here are all the megasearch tables:
```
 Schema |                              Name                               | Type  |       Owner        
--------+-----------------------------------------------------------------+-------+--------------------
 chado  | tripal_megasearch_contact                                       | table | drupal_carrotomics
 chado  | tripal_megasearch_featuremap                                    | table | drupal_carrotomics
 chado  | tripal_megasearch_gene                                          | table | drupal_carrotomics
 chado  | tripal_megasearch_marker                                        | table | drupal_carrotomics
 chado  | tripal_megasearch_pub                                           | table | drupal_carrotomics
 chado  | tripal_megasearch_qtl                                           | table | drupal_carrotomics
 chado  | tripal_megasearch_stock                                         | table | drupal_carrotomics
```

I would think we should ignore this table entirely, as it is a materialized view for a search function.

**Comment by dsenalik** [comment]
Your fix is awesome! I threw in a
```if (!preg_match('/megasearch/', $chado_table)) {```
to test, this eliminated all of the errors, and the page rendered in < 10 seconds
![Screenshot_2020-10-13_10-55-55](https://user-images.githubusercontent.com/8419404/95885387-ce97f580-0d42-11eb-9321-cc785d25f47b.png)

**Comment by spficklin** [comment]
So 10 seconds is still a long time for a user to wait for a response.... I tested with about 3000 records linked to a pub and on my test it loaded really fast.  I wonder if there is something else slowing the page load down.

BTW... I'm not going to have time today to get back to it. But if you want to change out your regular expression check for this function `chado_table_exists` (http://api.tripal.info/api/tripal/tripal_core%21api%21tripal_core.chado_schema.api.inc/function/chado_table_exists/2.x).  Then I think we have a working fix.

**Comment by dsenalik** [comment]
When you can get back to this, it was more like 6 seconds.

4.318 seconds of that was occupied in ```sio__references.inc``` in ```function load()``` processing table ```feature_pub```

Each of my 2476 records is taking about 0.0018 seconds each to process in the final loop in that function.

It appears that most of that time is from this line:
```$entity_id = chado_get_record_entity_by_table($reference_table, $record->$ref_pkey);```
(which of course is an essential bit of information to have)

Still, 6 seconds is way better than the ~90 seconds I was seeing before.

**Comment by spficklin** [comment]
Okay, I have an idea for how to speed that up....

**Comment by spficklin** [comment]
@dsenalik I managed to squeeze in some multitasking time and did another fix that I think might speed things up from 6 seconds... although I'm not 100% sure because it was running fast for me before. But now, Instead of the call to `chado_get_record_entity_by_table` I've got it all built into the initial SQL so hopefully that speeds things up for you.  Let me know.  

Also, I fixed the issue with it wanting to search the `megasearch` table.  I added two additional tests that will ensure it never looks down any table with a `_pub` in the name that doesn't have the proper foreign keys.

**Comment by dsenalik** [comment]
this is the first error, should be an easy fix

Notice: Undefined index: foreign keys in sio__references->load() (line 106 of /var/www/2020-02-18/drupal-7.69/sites/all/modules/tripal/tripal_chado/includes/TripalFields/sio__references/sio__references.inc).

this is the other error

PDOException: SQLSTATE[21000]: Cardinality violation: 7 ERROR: more than one row returned by a subquery used as an expression: SELECT REF.* , (SELECT entity_id FROM public.chado_bio_data_2 CBD2 WHERE record_id = LINK.analysis_id UNION SELECT entity_id FROM public.chado_bio_data_13 CBD13 WHERE record_id = LINK.analysis_id UNION SELECT entity_id FROM public.chado_bio_data_14 CBD14 WHERE record_id = LINK.analysis_id UNION SELECT entity_id FROM public.chado_bio_data_28 CBD28 WHERE record_id = LINK.analysis_id UNION SELECT entity_id FROM public.chado_bio_data_30 CBD30 WHERE record_id = LINK.analysis_id) as entity_id FROM chado.analysis_pub LINK INNER JOIN chado.analysis REF on LINK.analysis_id = REF.analysis_id WHERE LINK.pub_id = :pub_id; Array ( [:pub_id] => 509 ) in chado_query() (line 1790 of /var/www/2020-02-18/drupal-7.69/sites/all/modules/tripal/tripal_chado/api/tripal_chado.query.api.inc).

The subquery returns two values, one from bundle 2 (analysis) and one from bundle 13 (genome assembly analysis)

Now I have to investigate why I have this situation, they both ultimately point to the same analysis_id.

**Comment by spficklin** [comment]
Oh okay.  Yeah, I suppose it is possible to have the same record synced under two different content types.

**Comment by spficklin** [comment]
Okay, I made two more fixes... one for each of the issues you just posted.  It limits the nested query to only return 1 item, no matter what.

**Comment by dsenalik** [comment]
Excellent work! Now total elapsed time for feature_pub is 0.2542 second, for everything just 0.3668 second

**Comment by spficklin** [comment]
Okay. That's like a proper fix :-)  I'll submit the PR for it. Can you approve it as functionally reviewed? I'll post the link to it here.

**Comment by laceysanderson** [comment]
PR Merged and it sounds like it fixes this issue? @dsenalik please comment back here or open a new issue if you have any additional concerns :-)
