### ISSUE TITLE
Tripal field URLs should be clickable

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1108]
## Feature Request/Discussion

* This feature does attempt to solve an existing problem with Tripal
* This feature is Not Urgent

### Description
When the tripal field ```tpub__url``` displays a URL for a publication, it is not clickable

I propose a simple change to ```chado_linker__prop_formatter``` that will make any string matching a regex unto a clickable link ```/^https?:/i```

Pull request #1109 

### Additional information/screenshots
Example

![url-not-clickable](https://user-images.githubusercontent.com/8419404/96269147-99ccae00-0f8f-11eb-96cf-41bbca6f2af7.png)

becomes

![url-is-clickable](https://user-images.githubusercontent.com/8419404/96269169-a0f3bc00-0f8f-11eb-8b5c-0cca1c463012.png)

**Comment by spficklin** [comment]
The PR that fixes this got merged so closing this out. Thanks @dsenalik
