### ISSUE TITLE
Survey of Computational Resources

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1114]
Recent questions have been posed about what are the requirements in terms of CPU, RAM and disk storage when setting up a Tripal site.   This will vary greatly depending on the size of the database.  So, to help get handle on that questions, we'd like to ask folks to submit here their specs for their Tripal sites, whether development or production.    Please consider posting here the spec's of the machine you have running Tripal and if you can, the number of records in the table that holds the most prominent data on your site.

**Comment by spficklin** [comment]
Site Type:  Development
RAM: 16GB
CPU cores:  12
Storage:  2TB single drive
Max Features: 3million 
Performance: good

**Comment by laceysanderson** [comment]
Site Type: Production with very few users
RAM: 6GB
CPU cores: 4
Storage: 20GB
Performance: good
Small amount of breeding-focused data for 3 organisms

**Comment by laceysanderson** [comment]
From slack:
> I've run Tripal on a AWS t2.small instance with 2G RAM and around 20G memory. This was with a PHP memory cap of ~250M. I would guess the server could support around 4 concurrent users without crashing. These seem like reasonable specs for the proposed use case, provided  the 250M PHP limit is not exceeded.

**Comment by laceysanderson** [comment]
Site Type: Large Production with > 5000 unique users per year
RAM: 256 GB
CPU Cores: 24
Storage: 5.6 TB usable space (after RAID 10)
Performance: Good
NOTE: includes storage of large scale genotypic and phenotypic data

**Comment by almasaeed2010** [comment]
Provider: Digital Ocean
Site Type: Large with ~ 5000 users per year
RAM: 16 GB
CPU Cores: 6
Storage: 1 TB SSD
Performance: With optimizations such as opcache and memcache we get really good performance.
Organisms: 71 (with genes, polypeptides, interpro scans, blast, kegg, expression data and more)

**Comment by risharde** [comment]
A base line type version of specifications (what people can use to at least get running / testing)
Oracle VirtualBox 6.1 (Virtual Machine)
Site type: Near empty
RAM: 1GB
CPU Cores: 1 running at 60% (mostly to save laptop when using battery) - Ryzen 5 4500U processor.
Storage: 50 GB M2 NVMe
Performance: Loads fine, used for development and testing
Organisms: 1
