### ISSUE TITLE
Table of Contents should be sorted by weight to match order in Manage Display

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#112]
The Table of Contents on Tripal Content Pages is generated by the tripal_content_type_toc view (a listing of TripalPanes). This view has no sort applied to it. Furthermore, there is no "weight" exposed to views so I cannot even alter the view to be sorted by weight.

Note: Often the orders seem to match by chance. To confirm that the orders do not ALWAYS match, simply update the title of a Tripal pane lower down the list. After clicking "Save" on manage display, you will see that the order has not changed in manage display but it has on the actual content page.

The following screenshot shows the table of contents with Relationship first" but in the manage display, the overview is listed first:
![screen shot 2017-05-24 at 1 01 24 pm](https://cloud.githubusercontent.com/assets/1566301/26420881/419d6098-4081-11e7-8a54-509c6d3f344f.png)

@shawnawsu what are your thoughts, since Tripal DS is your baby?

**Comment by shawnawsu** [comment]
We just pushed an update that should now order the toc items in the order they are listing under the 'manage display' tab. I'm just working on making the initial order alpha but you should now be able to reorder items on the manage display tab, the alpha order will only apply to new content types or 'apply default tripal layout'. The update does require an drush updatedb.

**Comment by laceysanderson** [comment]
Awesome, confirmed that it now works as expected 👍
