### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable in include()

### ISSUE THREAD

**Issue by Xaiku** [tripal/tripal#1128]
### System information

* Tripal Version: v3
* Drupal Version: 7.69
* PostgreSQL Version: PostgreSQL 13.0 (Ubuntu 13.0-1.pgdg18.04+1)
* PHP Version: 7.3.23-1+ubuntu18.04.1+deb.sury.org+1)

### Issue description
Hey everybody, I'm trying to use genotype loader to load in some vcf files. Genotype loader has some sample files and instructions in their README.md to test it. Everything was fine until the last part where I had to make a chromosome feature (LcChr1, type: sequence:chromosome). After creating it I'm getting: 'Warning: count(): Parameter must be an array or an object that implements Countable in include()'. 

PS. I know that there is also an warning with fwrite(), but you can ignore that part.

#### Steps to reproduce
First you need an organism named Tripalus databasica. Follow these steps after that:
add content -> feature (Tripal v2 legacy) -> Feature name = LcChr1, Unique name = LcChr1, feature type = chromosome and organism = Tripalus databasica. 
#### Error messages and screenshots
![warning tripal](https://user-images.githubusercontent.com/73877812/97975305-3cc35b80-1dc9-11eb-92cf-476b1b3b8276.png)
```
Warning: count(): Parameter must be an array or an object that implements Countable in include() (line 16 of /var/www/html/sites/all/modules/tripal/legacy/tripal_feature/theme/templates/tripal_feature_analyses.tpl.php).
Warning: count(): Parameter must be an array or an object that implements Countable in include() (line 8 of /var/www/html/sites/all/modules/tripal/legacy/tripal_feature/theme/templates/tripal_feature_properties.tpl.php).
Warning: count(): Parameter must be an array or an object that implements Countable in include() (line 10 of /var/www/html/sites/all/modules/tripal/legacy/tripal_feature/theme/templates/tripal_feature_publications.tpl.php).
Warning: count(): Parameter must be an array or an object that implements Countable in include() (line 15 of /var/www/html/sites/all/modules/tripal/legacy/tripal_feature/theme/templates/tripal_feature_references.tpl.php).
Warning: count(): Parameter must be an array or an object that implements Countable in include() (line 10 of /var/www/html/sites/all/modules/tripal/legacy/tripal_feature/theme/templates/tripal_feature_synonyms.tpl.php).
Warning: count(): Parameter must be an array or an object that implements Countable in include() (line 41 of /var/www/html/sites/all/modules/tripal/legacy/tripal_featuremap/theme/templates/tripal_feature_featurepos.tpl.php).
Warning: count(): Parameter must be an array or an object that implements Countable in include() (line 11 of /var/www/html/sites/all/modules/tripal/legacy/tripal_library/theme/templates/tripal_feature_libraries.tpl.php).
Warning: count(): Parameter must be an array or an object that implements Countable in include() (line 69 of /var/www/html/sites/all/modules/tripal/legacy/tripal_natural_diversity/theme/templates/tripal_feature_nd_genotypes.tpl.php).
Warning: fwrite() expects parameter 2 to be string, array given in include() (line 22 of /var/www/html/sites/all/modules/tripal/legacy/tripal_phenotype/theme/templates/tripal_feature_phenotypes.tpl.php).
Warning: count(): Parameter must be an array or an object that implements Countable in include() (line 25 of /var/www/html/sites/all/modules/tripal/legacy/tripal_phenotype/theme/templates/tripal_feature_phenotypes.tpl.php).
```

**Comment by laceysanderson** [comment]
Hi @Xaiku 

It looks like you are using a Tripal 3 site in legacy mode, is this correct? 
For creating new Tripal v3 content you want to go to Admin > Content > Tripal Content > Add Tripal Content. 

To recover from your current situation, delete your content from Admin > Content. This will delete the pages but not the records in chado. Then go to Admin > Content > Tripal Content > Publish Tripal Content and publish both Organisms and Chromosomes. This creates Tripal 3 pages for your existing chado content.

Note: It is not recommended to enable the Legacy modules on your Tripal3 site unless absolutely needed. Regardless, new content should be created using the Tripal 3 functionality described above.

**Comment by Xaiku** [comment]
Hey @laceysanderson 

Thank you for your help. I tried to add or publish chromosome, but there is no option for it. Do you know how I can add this on my site? 
![image](https://user-images.githubusercontent.com/73877812/98662265-d51c8b80-2347-11eb-8a05-ee9f1a63a979.png)

**Comment by spficklin** [comment]
Hi @Xaiku 

Tripal comes pre-populated with many content types which is why the list you show in the screen shot is available.  But you can store a lot more in Chado that is not provided by default.  By default, Tripal does not provide a 'Chromosome' Content Type because chromosome's can be problematic for databases that are primarily genomic and have huge chromosomal sequences.  The chromosome pages will take too long to load.   I'm not as familiar with the Genotype module you're using but if you do need Chromosomal content types, you can create one by following the instructions in the Tripal User's Guide here:  

https://tripal.readthedocs.io/en/latest/user_guide/content_types.html

**Comment by Xaiku** [comment]
Hi @spficklin 

Thank you for your response! I followed the instructions and I have the option for chromosome now, but when I try to add LcChr1 as tripal chromosome content it gives me the following warning:
![image](https://user-images.githubusercontent.com/73877812/98837646-7b998700-2443-11eb-852b-2187cbbb533e.png)

This is my chromosome content type:
![image](https://user-images.githubusercontent.com/73877812/98837801-aedc1600-2443-11eb-97aa-3ccd1f39b4b0.png)

and this is what I try to add:
![image](https://user-images.githubusercontent.com/73877812/98837864-c6b39a00-2443-11eb-8ca0-039af1825d84.png)

**Comment by spficklin** [comment]
So it looks like those warnings are coming from problems in the legacy module templates and are there due to updates in PHP (they probably don't show up in PHP version  below 7.2).  Which PHP version are you using?  My guess is 7.3 or 7.4.  We don't generally make fixes to the legacy modules because they are meant to be phased out.   Do you need to use the legacy modules?  If not, if you turn them off this problem will go away.  If you do need them let us know.

**Comment by Xaiku** [comment]
Hey @spficklin 

I am using PHP 7.3 and the warnings disappeared after disabling the legacy modules. I'm still not sure if I need the legacy modules, because I don't really know how genotype loader works and what it needs. I tried loading in the sample files again that comes with genotype loader, but it doesn't work. The warnings are gone now, so thank you for your help! I'll open an issue on the genotype loader github, and hopefully they can help me with loading the vcf files.
