### ISSUE TITLE
errors if Tripal Pane exists but tripal_ds disabled

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#113]
If a content type has the Tripal Pane fieldgroup but the tripal_ds module is disabled a bunch of errors appear on the content type admim page:

> Notice: Undefined index: tripal_ds_feature in _ds_field_ui_table_layouts_preview() (line 1892 of /var/www/html/sites/all/modules/ds/includes/ds.field_ui.inc).
> Notice: Undefined index: tripalpane in field_group_table_field_group_format_settings() (line 87 of /var/www/html/sites/all/modules/field_group_table/field_group_table.module).
> Notice: Undefined index: tripalpane in field_group_field_group_format_settings() (line 461 of /var/www/html/sites/all/modules/field_group/field_group.module).
> Notice: Undefined index: tripalpane in field_group_table_field_group_format_settings() (line 87 of /var/www/html/sites/all/modules/field_group_table/field_group_table.module).
> Notice: Undefined index: tripalpane in field_group_field_group_format_settings() (line 461 of /var/www/html/sites/all/modules/field_group/field_group.module).
> Notice: Undefined index: tripalpane in field_group_table_field_group_format_settings() (line 87 of /var/www/html/sites/all/modules/field_group_table/field_group_table.module).
> Notice: Undefined index: tripalpane in field_group_field_group_format_settings() (line 461 of /var/www/html/sites/all/modules/field_group/field_group.module).
> Notice: Undefined index: tripalpane in field_group_table_field_group_format_settings() (line 87 of /var/www/html/sites/all/modules/field_group_table

**Comment by shawnawsu** [comment]
@spficklin I've put a hook_disable function in the install file that will output an error message when tripal_ds is disabled. The function checks for tripal panes and then lists any content types with associated tripal panes. The message will look like this: 
```
$ drush dis tripal_ds
The following extensions will be disabled: tripal_ds
Do you really want to continue? (y/n): y
tripal_ds was disabled successfully.                                   [ok]
You have disabled the Tripal DS module but Tripal Panes were found in  [warning]
the following Content Types:  Project Map Publication mRNA Blast
Analysis Chromosome Lentil Sequence Feature Supercontig Organism
Analysis Gene
```
