### ISSUE TITLE
Tripal field sbo__database_cross_reference timeout, can't handle many cross references

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1138]
## BUG/ERROR report
I thought it would be nice to link all NCBI sequence accessions to corresponding publications, using the ```pub_dbxref``` table. Well it works great, except for publications with many NCBI sequence accessions, the page can actually timeout, and even if not, the list is too long.

First, we would need a pager for the sbo__database_cross_reference field, but

Second, it takes way too long to render the page, both the call to ```chado_expand_var``` in ```load()```
as well as the formatter takes too much time also.

I could try to work on this field, but maybe there is a better way to do this? Maybe even a new tripal field specific for links to GenBank? Mainly I am wondering if anyone has any advice.

**Comment by spficklin** [comment]
Hi @dsenalik, I think the solution to this problem is the same with a few other fields you're recently reported on (#1100). The solution was to not use the `chado_expland_var` function but to rewrite the `load` function to use strategic SQL.  I can try to take a look at it but it might take me a few days before I can get to it.

**Comment by dsenalik** [comment]
I'm working on it. I have the SQL working, just need to add the pager.

**Comment by dsenalik** [comment]
My pager appears to be working, rendering >3000 cross references is only 75 ms SQL query and store, 105 ms in view() YAY!

But I have a question, if there is only one cross reference (the more usual case) it now takes more screen space. What about only triggering the pager if there is > one page of cross references?
Before:
![before](https://user-images.githubusercontent.com/8419404/102377722-9a32f680-3f8a-11eb-8100-bfc2fb4c9788.png)

After:
![after](https://user-images.githubusercontent.com/8419404/102377741-9f904100-3f8a-11eb-9999-670673172f95.png)

**Comment by laceysanderson** [comment]
Hi @dsenalik,

I personally like the consistency of the bullets so I would be hesitant to change the current behavior. Anyway, thank you for the PR! I have merged it which solves the issue reported so I'm going to close this issue. However, if you feel strongly regarding the additional white space feel free to submit another PR :-) 

Thank you! (Both for the bug report and the fix!)

**Comment by dsenalik** [comment]
No, I am quite happy with the appearance, I was just wondering what others thought.
Thank you
