### ISSUE TITLE
Tripal Dashboard vs. Drupal Dashboard

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#114]
@spficklin , why did we create a Tripal-specific "dashboard" at admin/tripal/dashboard when Drupal already provides a Dashboard at admin/dashboard?

## Advantages of Tripal-specific dashboard (feel free to edit)
- Conveniently located under the Tripal administration menu

## Advantages of Drupal dashboard
- Conveniently located on the Drupal Administration Toolbar
- Allows admin to see both Drupal and Tripal notifications in the same spot
- Provides two columns to arrange blocks in
- We don't have to maintain it ;-)

Currently Tripal Fields use the Tripal Dashboard and Tripal Daemon uses the Drupal Dashboard. We should decide moving forward which one to use to maintain consistency.

**Comment by shawnawsu** [comment]
In dashboard-7.x-3.x branch. To see the notifications block move (if you already have the dashboard setup) you'll need to update the block by hand.
