### ISSUE TITLE
Post Migration T2->T3 Delete Tv2 features

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal#1146]
### System information

* Tripal Version: 7.x-3.x
* Drupal Version: 7.77
* PostgreSQL Version: 11.9
* PHP Version: 7.2.24

#### Steps to reproduce

After upgrading a site from Tripal 2 to Tripal 3, and using the migration page (admin/tripal/storage/chado/migrate) to delete All Tripal 2 content, all content of type "Feature" still remains. These are not Tripal Content, just regular Drupal content.

Furthermore, this content is mostly an empty shell (see second screenshot below)

#### Error messages and screenshots

![Tv2 Delete](https://user-images.githubusercontent.com/9593623/103905386-86336e00-50cc-11eb-96e9-7caea3887e1a.png)

![Empty Feature](https://user-images.githubusercontent.com/9593623/103905468-a4996980-50cc-11eb-85b6-74278e30f7c1.png)

**Comment by spficklin** [comment]
Hmmm.... that sounds like a bug that needs fixing.  In the meantime did you get these removed?  In Tripal v2 there was an interface to remove orphaned pages I just can't remember off the top of my head where it was and I no longer have a Tripal v2 site up and running to go look.  If you can find that it may clean these up for you.
