### ISSUE TITLE
Link an organism page to its chromosome

### ISSUE THREAD

**Issue by shmenolin** [tripal/tripal#1149]
Hello,
I am trying to set up a model organism website with Tripal and currently working with Tripal 3 until the 4 gets released. I had some questions:
1. I loaded the chromosome sequence for an organism but saw that I cannot directly search for the loaded chromosome. How do I search for such features loaded to the database? I can see gene search but not for the chromosome.
2. For a particular organism, can I link its chromosome (loaded to the database) with in the organism page?
3. What would be the best way to see the records stored in the chado database installed through Tripal? I cannot access it through command line terminal

**Comment by spficklin** [comment]
Hi @shmenolin. It looks like this may have been submitted twice.  The duplicate issue is here #1150 .  So, I'm going to close this one out and we can communicate on the other one.
