### ISSUE TITLE
Purpose of Tripal V2 legacy modules

### ISSUE THREAD

**Issue by shmenolin** [tripal/tripal#1154]
Hello all,
Can someone please help me understand why Tripal V2 legacy modules are present in Tripal V3?
Thank you!

**Comment by spficklin** [comment]
Hi @shmenolin .  When we updated Tripal v2 to Tripal v3 we changed from using Dupal 7 templates to using fields.  This gives site admins greater control over how the site pages look without having to write any PHP code.   However, some sites needed the flexibility to upgrade slowly as their site were quite large.  So, we kept some of the Tripal v2 functionality around in those legacy modules.  If you have never used Tripal v2 you shouldn't need these modules at all and can ignore them.

**Comment by shmenolin** [comment]
Thank you
