### ISSUE TITLE
Search genes according to product names

### ISSUE THREAD

**Issue by shmenolin** [tripal/tripal#1157]
How can I search for a gene based on its product? (for example: I want to search for all polymerase genes in the database). While loading the gff file, only the ID and Name are stored but not the product description in the feature table and I cannot find a way to link featureprop table in search results while searching through the genes. 
 
Also, is it possible to create teaser links for tripal contents using Drupal views (saw it to be possible in Tripal v2 but when I tried for V3, I can only get the list of contents which cannot be linked to their pages). 

Thank you

**Comment by mpoelchau** [comment]
In terms of search - you may want to install tripal elasticsearch (https://github.com/tripal/tripal_elasticsearch). You can set the product field as 'high priority' in the tuning page. 

No idea about the teaser links, sorry.

**Comment by spficklin** [comment]
Just checking @shmenolin if @mpoelchau 's suggestion worked for you?

**Comment by spficklin** [comment]
Hi @shmenolin .  Since there's not been conversation on this for awhile I'm going to close it out,  but please feel free to comment again and we can reopen it if you want to chat more on it.
