### ISSUE TITLE
Call to undefined function _tripal_feature_load_relationships() in tripal_feature_get_aggregate_relationships()

### ISSUE THREAD

**Issue by abretaud** [tripal/tripal#116]
Hi,
It looks like commit f828e9f586dd7f9011671321db022390bd83af8d broke something: I get this error when viewing a simple mRNA page loaded from gff:

`Error: Call to undefined function _tripal_feature_load_relationships() in tripal_feature_get_aggregate_relationships() (line 300 of /var/www/html/sites/all/modules/tripal/tripal_feature/theme/tripal_feature.theme.inc).`

Looking at the commit, I think the problem is [there](https://github.com/tripal/tripal/commit/f828e9f586dd7f9011671321db022390bd83af8d#diff-3d0c45f0fdb134cb204a8eff4458d136L300), I don't understand exactly why the function call has been renamed and the function it self disappeared.

Reverting this part of the commit fixes the problem

Anthony

**Comment by laceysanderson** [comment]
@spficklin did you see this? @chunhuaicheng commented as well on the commit directly.

**Comment by spficklin** [comment]
I believe this was a problem with the 2.x branch of Tripal (not 3.x).  Apologies for the missing function!  It has been corrected and added back.  Can you test and make sure it's working for you?  I've just committed to the 7.x-2.x branch a fix.

**Comment by abretaud** [comment]
Thanks, it's fixed now!

**Comment by spficklin** [comment]
Great! closing this issue then.
