### ISSUE TITLE
Using drush --include=. tripal-generic-install command tries to install tripal version 7.x-3.5 which does not seem to exist

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#1162]
This repo [Tripal Rapid Installer for CENTOS 7](https://gitlab.com/TreeGenes/tripal_rapid_installer_for_centos_7/-/blob/master/tripal_rapid_installer_centos7.sh) is a small script and corresponding configuration files that will set up Tripal 3 on a clean CENTOS 7 distribution. This worked fine previously but does not work correctly anymore with the following issue which stems from the drush command:

`drush --include=. tripal-generic-install`

Attached is a screenshot of where the issue happens. I'm tagging @spficklin and @laceysanderson who may know more about this one.

![image](https://user-images.githubusercontent.com/33866403/106500733-9a0b9d80-64db-11eb-86f2-729613c7fed9.png)

This leads to numerous errors and failure to properly install Tripal 3 on the environment.

**Comment by spficklin** [comment]
This is my fault. I updated it to pull the Tripal 3.5 release anticipating that the release would come just a few short hours after I did it.  The release did not.

**Comment by risharde** [comment]
Issue has been resolved with PR! Thanks @spficklin for your assistance!
