### ISSUE TITLE
Bulk Loader optional setting

### ISSUE THREAD

**Issue by btski** [tripal/tripal#1164]
### System information

* Tripal Version: 7.x-3.3
* Drupal Version: 7.78
* PostgreSQL Version: 9.5.24
* PHP Version: 7.0.33

### Issue description

Attempting to get the Bulk Loader optional setting working. Currently, the optional setting only works for required values (not null?) that are absent. I'm not sure what criteria is used to define "required" values. I believe the intended behavior for the optional setting is that if a null value is provided for a field that is required to be non-null, the field and all children are omitted from upload. To reflect this understanding, I made a simple [modification](https://github.com/btski/tripal/commit/63734c169e8c54cf6b8181baa09040b0576a8068#diff-6c01ec69165fffbaf8e13dc21f320027a78d8c66619bfac7a6d3858dc49001a1). If this logic appears correct, I'll push the correction to the main branch.

Edit - Corrected previous problem with my bulk loader template format to resolve an error.

**Comment by spficklin** [comment]
I believe this is fixed as per the merged PR.
