### ISSUE TITLE
Bulk Loader null value error

### ISSUE THREAD

**Issue by btski** [tripal/tripal#1165]
### System information

* Tripal Version: 7.x-3.3
* Drupal Version: 7.78
* PostgreSQL Version: 9.5.24
* PHP Version: 7.0.33

### Issue description

Null value would trigger a false error when the null value is called as a foreign key in another table. My proposed solution can be found [here](https://github.com/btski/tripal/commit/be4642efe82578c77c241c6d969213586ab6b43e#diff-347452757b032417e3eef4c4019ba6bbecefc8a29cc595bd0ced49510d0a979c). If this change appears correct, I'll push the correction to the main branch.

#### Steps to reproduce

Attempting to link biomaterial to the contact table via "biosourceprovider_id" foreign key when contact "name" field contains null value.

#### Error messages and screenshots

Two errors below were encountered **while fixing**:

Error 1
```
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] chado_insert_record: Too many records match the criteria supplied for biosourceprovider_id foreign key constraint (Array())
ERROR (TRIPAL_BULK): 
Line 1998 biomaterial (insert) Unable to insert record into biomaterial where values:Array
(
    [taxon_id] => Array
        (
            [abbreviation] => PRRSV
        )

    [biosourceprovider_id] => Array
        (
        )

    [dbxref_id] => 872192
    [name] => GB000001
)
```

Error 2
```
ERROR (TRIPAL_CHADO): chado_update_record: When trying to find update values, too many records match the criteria supplied for biosourceprovider_id foreign key constraint (Array
(
)
)
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] chado_update_record: When trying to find update values, too many records match the criteria supplied for biosourceprovider_id foreign key constraint (Array())
ERROR (TRIPAL_BULK): 
Line 2 biomaterial (insert) Unable to insert record into biomaterial where values:Array
(
    [taxon_id] => Array
        (
            [abbreviation] => SVA
        )

    [biosourceprovider_id] => Array
        (
        )

    [dbxref_id] => 872194
    [name] => GB078389
    [description] => SVA_7_2
)
```

**Comment by spficklin** [comment]
Closing out as I think this is fixed!

**Comment by btski** [comment]
@spficklin problem has not been fixed. 

To reiterate the problem:
Empty value that is part of non-required field is correctly omitted. However, associated fields that reference the omitted field as an optional foreign key attempt to match value (NULL) to an existing key. This produces multiple matches, resulting in an error. I don't think `chado_schema_get_foreign_key()` should be run if provided `$value` is an empty array. 

All my proposed solution does is omit running foreign key matching if values to match are absent. This is probably a patchwork solution. I think it's more likely that the bug is in tripal_bulk_loader.loader.inc. The empty array triggering the error in `chado_schema_get_foreign_key()` is provided by `process_data_array_for_line()`. You can make `chado_schema_get_foreign_key()` more robust to handle the error (my original solution) or fix `process_data_array_for_line()` to prohibit the invalid input (convert empty array to NULL).

**Comment by spficklin** [comment]
Hey @btski .  Thanks for the test files.  I ran those through and I did not encounter the error.   But this code fix simple and it makes sense.   The template you shared is quite complex and if this fix is working for you I'm inclined to believe it's not going to cause problems elsewhere.  So, I'm merging. Thanks for submitting the fix.

**Comment by spficklin** [comment]
Whoops that last comment was meant to be on the PR not the issue. But I merged the PR and closed the issue.
