### ISSUE TITLE
sbo__relationship tripal field does not work for publications

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1167]
### System information

* Tripal Version: 7.x-3.3 (more or less)
* Drupal Version: 7.78
* PostgreSQL Version: 12.5
* PHP Version: 7.3.26

### Issue description
If two publications are linked by the ```pub_relationship``` table, such as a chapter linked to the containing book, the ```sbo__relationship``` tripal field will produce an error and not display the relationship.

I have a pull request (#1168) to fix this, as well as a related issue with titles longer that the ```chado_expand_var()``` length limit not displaying.

#### Error messages and screenshots
```
     Notice: Undefined property: stdClass::$name in sbo__relationship->getRelationshipSubject() (line 292 of /var/www/2020-02-18/drupal-7.69/sites/all/modules/tripal/tripal_chado/includes/TripalFields/sbo__relationship/sbo__relationship.inc).
    Notice: Undefined property: stdClass::$name in sbo__relationship->getRelationshipObject() (line 349 of /var/www/2020-02-18/drupal-7.69/sites/all/modules/tripal/tripal_chado/includes/TripalFields/sbo__relationship/sbo__relationship.inc).
```

**Comment by spficklin** [comment]
I believe this has been fixed with the pull request that was recently merged so I'm going to close this out.
