### ISSUE TITLE
Cannot access options under 'tripal' menu

### ISSUE THREAD

**Issue by shmenolin** [tripal/tripal#1171]
I have incurred a problem in Tripal where I cannot access any options under the tripal menu as in the image below. I am not sure what is causing this situation, it was working fine a day before. 
I would greatly appreciate any help. Thank you.

![image](https://user-images.githubusercontent.com/61807957/109348036-027f3d80-7842-11eb-9a4c-c3a8d1b438fb.png)

**Comment by spficklin** [comment]
That is bizarre.  Do you have that same message under any other admin menu item?  Also, just to check... have you fully cleared the Drupal cache?  Did you make any adjustments since it was working yesterday?

**Comment by shmenolin** [comment]
Other menu items work fine. The changes I did are deleted some "bulk loading" jobs I had performed and tried different drupal themes. And yes, I cleared all drupal cache.

**Comment by spficklin** [comment]
That's a bit bizarre.  Sorry for the delay in response. Have you figured it out yet?   If not, does the Tripal content on the site still work?  Have the Tripal modules moved from their location on the file system?

**Comment by spficklin** [comment]
Hi @shmenolin any updates on the problem?

**Comment by shmenolin** [comment]
Everything is in its place in the file system as before. I haven't figured it out yet so I am thinking of reinstalling Tripal.

**Comment by spficklin** [comment]
If you still have the problem on Monday feel free to join on Gathertown get-together and someone can help you look at it. in a breakout room in real-time.

**Comment by spficklin** [comment]
I'm going to close this out, but if you continue to have the issue please comment again and we cant try to help further.

**Comment by shmenolin** [comment]
An update to this problem. I disabled the "toolbar" module from Drupal and replace it with "Administrative menu" module. It brought the options back.
