### ISSUE TITLE
Ajax error in Drupal forms for Tripal File module

### ISSUE THREAD

**Issue by katherynbuble** [tripal/tripal#1173]
Tripal Version: 7.x-3.5+
Drupal Version: 7.77
PostgreSQL Version: 12.4
PHP Version: 7.3

### Issue description
Ajax error occurs when using Drupal form elements, after installing Tripal File module 7.x-1.x.

Example 1:
1. When installing the Tripal File module, https://github.com/tripal/tripal_file, to install the EDAM vocabulary, navigated to Administration > Tripal > Data Loaders > Chado Vocabularies > OBO Vocabulary Loader page via the administrative menu. 
2. Then selected EDAM vocabulary from the Ontology OBO File Reference drop down. 
3. Before attempting to click the Import OBO File, an AJAX error occurred:

Drupal log message:
Location: https://dev.cottongen.org/system/ajax
Referrer: https://dev.cottongen.org/admin/tripal/loaders/chado_vocabs/obo_loader
Message: Undefined index: clicked_button in OBOImporter->formValidate() (line 474 of /local/sites/dev.cottongen.org/drupal7/sites/all/modules/tripal/tripal_chado/includes/TripalImporter/OBOImporter.inc).
Severity: notice

Example 2:
When attempting to use any Drupal form elements (ex. check box or selector list) for the Tripal MapViewer module, an AJAX error occurs:

<img width="1066" alt="Screen Shot 2021-03-04 at 10 10 39 AM" src="https://user-images.githubusercontent.com/59714566/110009917-874ed900-7cd2-11eb-9374-48d5dfd1052e.png">

**Comment by katherynbuble** [comment]
This issue should be transferred to the Tripal File module repository. After further investigation found Ajax error stops once tripal_file is disabled/uninstalled.

**Comment by dsenalik** [comment]
It appears to be this existing issue at tripal_file
https://github.com/tripal/tripal_file/issues/7

**Comment by spficklin** [comment]
@katherynbuble I believe this is fixed now thanks to the PR submitted by @dsenalik.  If you can pull the dev version of the Tripal File module and test it.  Since this is a tripal_file issue I'm going to close this out.  But if you still have issues please feel free to comment on this issue:  https://github.com/tripal/tripal_file/issues/7
