### ISSUE TITLE
Chado Bulk Loader miscounts number of lines in a file

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1178]
### System information

* Tripal Version: 7.x-3.5
* Drupal Version: 7.78
* PostgreSQL Version: 12.6 (Ubuntu 12.6-1.pgdg16.04+1)
* PHP Version: 7.3.27-9+ubuntu16.04.1+deb.sury.org+1

### Issue description
Chado Bulk Loader progress messages indicate one line too many for number of lines in data file.
This happens because after all bytes have been read, ```feof()``` still returns false until the next read occurs.
It works as intended only when the last line does not end in a return.
The reason is explained in detail here for c++: https://stackoverflow.com/questions/5431941/why-is-while-feof-file-always-wrong
I propose to copy the exact same logic from the loader section where blank lines are ignored. This will catch the case of counting a null string on the last loop, as well as better match the loader logic.

#### Steps to reproduce
Compare value from ```wc -l``` to value reported by loader

#### Error messages and screenshots
Drush output for a file with header line and one data line
```
File: /somepath/test.tsv (3 lines)
```
```
Progress:
[|||||||||||||||||||||||||||||||||||||||||||||||||||] 100.00%. (3 of 3) Memory: 54444328
```

**Comment by spficklin** [comment]
I think this is fixed with the PR so closing. Thanks @dsenalik
