### ISSUE TITLE
TripalPane Close button only works on Panes open on initial page load.

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#118]
On a Tripal Content Type Page, clicking the "X" icon in the top right corner only works on Panes open on initial page load. For example, looking at an mRNA page if only the summary is shown when the page first loads then that pane is the only the X icon works for (actually removes the pane). For any other panes opened via the table of contents, the "X" icon does nothing. Furthermore, once I use the table of contents to move the summary back to the top, the "X" icon no longer works for it either. This is repeatable on all my content types.

@shawnawsu do you have any ideas what is causing this?

## Background
I'm testing the upgrade process of a basic Tripal 2 site to Tripal 3. Completing the entire upgrade process with Tripal 3 dev (3df04d6) or Tripal 3 dev (7a22316) produces the same behaviour. PS. I tried the full upgrade without the last commit because it was a "Fix" on my part to the prepare code related to the DS module. I wanted to confirm the problem wasn't my fix and the fact I see it in both cases proves that to me.

**Comment by shawnawsu** [comment]
Ok, a few tweaks in the hierarchy caused my css not to be targeted enough, that's all fixed now in the 7.x-3.x branch.
