### ISSUE TITLE
Chado Bulk Loader shouldn't count header line in line count

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1180]
### Description
I alluded to this in pull #1179 
Since pull #1179 was merged, the chado bulk loader reports the number of non-blank lines in a file. One of those lines is optionally a header line.
It would be conceptually more clear if the loader reports the exact number of lines of data loaded. The code already skips counting that line when loading, but the way the code was written, at the end it updates with the total number of lines, thus including the header line.

### Your Specific Use Case
My use case is loading any file with a header line lol.

**Comment by spficklin** [comment]
This issue has been resolved with the recent PR. Thanks again @dsenalik
