### ISSUE TITLE
schema__publication tripal field bug if multiple publications

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1183]
### System information

* Tripal Version: 7.x-3.5
* Drupal Version: 7.78
* PostgreSQL Version: 12.6 (Ubuntu 12.6-1.pgdg16.04+1)
* PHP Version: 7.3.27-9+ubuntu16.04.1+deb.sury.org+1

### Issue description
This appeared on an analysis page, specifically a Genome Annotation page but this bug would show up anywhere the field was used. For an analysis with two linked publications, when editing the analysis and trying to save, the following appeared:
Could not save the TripalEntity: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "analysis_pub_c1" DETAIL: Key (analysis_id, pub_id)=(9, 509) already exists.

The log message is a bit more informative:
PDOException: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "analysis_pub_c1" DETAIL: Key (analysis_id, pub_id)=(9, 509) already exists.: UPDATE chado.analysis_pub SET analysis_pub_id = :analysis_pub_id, analysis_id = :analysis_id, pub_id = :pub_id WHERE analysis_pub_id = :old_analysis_pub_id ; Array ( [:analysis_pub_id] => 14 [:analysis_id] => 9 [:pub_id] => 509 [:old_analysis_pub_id] => 14 )

To see why this fails, look at my current content
```
SELECT * FROM chado.analysis_pub WHERE analysis_id=9;

 analysis_pub_id | analysis_id | pub_id 
-----------------+-------------+--------
              12 |           9 |    509
              14 |           9 |    358
(2 rows)
```
So it is trying to save 9|509 under analysis_pub_id=14 on top of the 9|358 instead of properly on analysis_pub_id=12 thus leaving two 9|509 at the same time which triggers the duplicate key violation.

I found out why, too, it's this line in ```schema__publication.inc```:
```$entity->{$field_name}['und'][$i]['chado-' . $field_table . '__' . $pkey] = $linker->$pkey;```
where $linker is defined inside the loop above where we process each publication. Thus it only contains the last-encountered value.

I will submit a pull request for a possible fix #1184 

#### Steps to reproduce
I think that this will only trigger an error if the order of publications causes them to be updated in the (in-)appropriate order. I can get it to trigger if I:
1. Add a second publication to an Genome annotation analysis and save that
2. Edit, change the publication order (0 becomes 1 and 1 becomes 0) and save
I just tested this on a regular analysis page and this also triggered the error.

**Comment by spficklin** [comment]
Hi @dsenalik .  This PR didn't seem to fix the problem for me.  I've pulled the fix and tested by creating an analysis with two pubs and then swapping the order of the pubs and saving. I get the error message as before. I'm going to look into this and see why it's not working.

Edit: whoops, I meant to post this on the PR #1184

**Comment by spficklin** [comment]
Okay, I got it to work when I cleared the record cache

**Comment by spficklin** [comment]
This issue should be fixed with the recent PR. Thanks for submitting @dsenalik !
