### ISSUE TITLE
OBO Loader: chado.tripal_obo_temp ID field length

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal#1185]
### System information

* Tripal Version: 7.x-3.0-rc2
* Drupal Version: 7.59
* PostgreSQL Version: 9.2.23
* PHP Version: 7.1.15

### Issue description
Loading a KEGG OBO file (converted using the [json_to_obo.php](https://github.com/tripal/tripal_analysis_kegg/tree/7.x-3.x/kegg_OBO_builder) converter), some entries are too long to fit into the `id` field - varchar(255). It is a rare occurrence but not without precedent. 

#### Steps to reproduce
This issue was discovered when trying to load [*Cimex lectularius* (bed bug) data from KEGG](https://www.genome.jp/kegg-bin/show_organism?menu_type=gene_catalogs&org=clec) which had been converted from JSON to OBO format using the aforementioned script. Two of the lines exceed the 255 character limit as specified in Chado.

#### Error messages and screenshots

```sql
ERROR:  value too long for type character varying(255)
STATEMENT:  INSERT INTO chado.tripal_obo_temp (id, stanza, type) VALUES ('KEGG:106667345 SWI/SNF-related matrix-associated actin-dependent regulator of chromatin subfamily A containing DEAD/H box 1 homolog isoform X1K14439 SMARCAD1; SWI/SNF-related matrix-associated actin-dependent regulator of chromatin subfamily A containing DEAD/H box 1 [EC:3.6.4.12]', 'YTozOntzOjI6ImlkIjthOjE6e2k6MDtzOjI4MToiS0VHRzoxMDY2NjczNDUgU1dJL1NORi1yZWxhdGVkIG1hdHJpeC1hc3NvY2lhdGVkIGFjdGluLWRlcGVuZGVudCByZWd1bGF0b3Igb2YgY2hyb21hdGluIHN1YmZhbWlseSBBIGNvbnRhaW5pbmcgREVBRC9IIGJveCAxIGhvbW9sb2cgaXNvZm9ybSBYMUsxNDQzOSBTTUFSQ0FEMTsgU1dJL1NORi1yZWxhdGVkIG1hdHJpeC1hc3NvY2lhdGVkIGFjdGluLWRlcGVuZGVudCByZWd1bGF0b3Igb2YgY2hyb21hdGluIHN1YmZhbWlseSBBIGNvbnRhaW5pbmcgREVBRC9IIGJveCAxIFtFQzozLjYuNC4xMl0iO31zOjQ6Im5hbWUiO2E6MTp7aTowO3M6Mjc2OiIxMDY2NjczNDUgU1dJL1NORi1yZWxhdGVkIG1hdHJpeC1hc3NvY2lhdGVkIGFjdGluLWRlcGVuZGVudCByZWd1bGF0b3Igb2YgY2hyb21hdGluIHN1YmZhbWlseSBBIGNvbnRhaW5pbmcgREVBRC9IIGJveCAxIGhvbW9sb2cgaXNvZm9ybSBYMUsxNDQzOSBTTUFSQ0FEMTsgU1dJL1NORi1yZWxhdGVkIG1hdHJpeC1hc3NvY2lhdGVkIGFjdGluLWRlcGVuZGVudCByZWd1bGF0b3Igb2YgY2hyb21hdGluIHN1YmZhbWlseSBBIGNvbnRhaW5pbmcgREVBRC9IIGJveCAxIFtFQzozLjYuNC4xMl0iO31zOjQ6ImlzX2EiO2E6MTp7aTowO3M6NzI6IktFR0c6MDMwMzYgQ2hyb21vc29tZSBhbmQgYXNzb2NpYXRlZCBwcm90ZWlucyBbQlI6Y2xlYzAzMDM2XSAoY2xlYzAwMDAxKSI7fX0=', 'Term')
```

### Proposed solution
It is not wholly unexpected for this field to contain long strings. Increasing the valid length of this chado field would be the simplest solution.

There was also discussion of having the json_to_obo.php script perform some truncation. We noticed that in the offending line above, as well as the rest of the file, much of the content is repeated. Stripping out the repeated portion (while preserving important artifacts like EC), but this discussion is more appropriate on the [Tripal Analysis KEGG](https://github.com/tripal/tripal_analysis_kegg/) repository.

**Comment by spficklin** [comment]
@Ferrisx4 and I spoke about this issue this morning and the solution is to fix the  `json_to_obo.php` script so that it doesn't create such long IDs.  So, I'm going to close this out. But please reopen @Ferrisx4 if you think more needs to be discussed.
