### ISSUE TITLE
How to add Gene/Protein Families information

### ISSUE THREAD

**Issue by mario-lopez-c** [tripal/tripal#1186]
Hello, I have a question...
I wonder if there is a way to add gene/protein families to the chado database (with Tripal 7.x-3.5), In order to display my genes as a member of a set of defined families.
Thank you!

**Comment by spficklin** [comment]
Hi @mario-lopez-c just a few more questions about your request.  Do you want to have gene family pages with all of the genes in that family listed or are you looking to have the gene family name listed on the gene, or both?

**Comment by mario-lopez-c** [comment]
Hi @spficklin! I would like to know how both options works, but I am more interested in the first option...
Thank you so much!

**Comment by spficklin** [comment]
Okay, one more question.  What kind of data do you have to represent gene families?  Is it just gene family names or do you have additional data to go with it?  That's not something I've stored before so more details about it can help me tell you how best to get it organized. Also others here who are lurking and stored this type of data may chime in too :-)

**Comment by mario-lopez-c** [comment]
Sure, I want to present it as a list of gene families (https://grassius.org/browsefamily.php?sp=Maize&typ=transcription_factor), and genes that belong to the same family, just like this (https://grassius.org/family.php?family=ABI3-VP1&species=Maize&type=transcription_factor). Each gene will have at least five information elements: 1) GeneID, Name, CloneID, Targets, Link_to_external_DB. Some of these elements need to have a link to the corresponding data, e.g., GeneID should take me to a gene page with the corresponding DNA and protein sequences. Or,  a table with a list of genes ( for instance,  the  "Targets" fields)

**Comment by spficklin** [comment]
Again, I've not actually worked with gene families in Chado or Tripal.  Chado is flexible and it's important to try to store the data in a common way as others so that it's easier to share modules/components.   I've requested on our Slack workspace asking that others chime in.  At first glance, I don't see a good way to do this in Chado.  There is a `group` module for Chado  (http://gmod.org/wiki/Chado_Group_Module) that was not fully vetted, I think some groups may use it, and it has some grouping tables that can be used for this, but as far as I know it's not officially in Chado and currently not supported out-of-the-box by Tripal.   Maybe @scottcain can give some insight on the status of the Group module.  

If you have a bit of time to wait on responses from others then I think we can get a solution.

**Comment by mario-lopez-c** [comment]
Sure, thanks, I can wait...

**Comment by srobb1** [comment]
Hello. I have implemented gene group usage on a Tripal 2 site.  You can see a gene page [here with a gene group tab]( https://cuttingclass.stowers.org/en/feature/Girardia/sp/mRNA/Gsp_009731). I used the Chado group module. Each member of the gene group has a gene page of its own. I can go into the details if anyone is interested.

**Comment by mario-lopez-c** [comment]
Great, sure, I am interesting in knowing how you did it, I exactly need to group some genes by their type of family in common, I would like to know how you loaded the data to relate the gene to the family and then how you publish them in a table and that each gene has its own page...Thank you!

**Comment by srobb1** [comment]
My genes are genes from a variety of planarian (flatworm) species. We grouped the translations with orthomcl. Here is an example of the contents of one group. The first three letters indicate a different species. This group we believe to be innexin.

GG549   SMU15000918
GG549   SMU15003648
GG549   SMU15003649
GG549   Ddo_019521
GG549   Ddo_023720
GG549   Gsp_005528
GG549   Gsp_009731
GG549   Pgr_014738
GG549   Pgr_015079
GG549   Pgr_016503
GG549   Pgr_025217
GG549   Pgr_029537
GG549   Pmo_002029
GG549   Pmo_032051

I added the Group module tables to my chado db. 

Here is how I added my genes which were already loaded into my chado db using tripal loaders. I created a script which read in my two column gene groups from above and generated the sql below, which I ran to load the data into group module tables. Here you will see two genes being added to the tables.

Group that I called GG549 is being created with SMU15000918.
```
INSERT INTO grp (uniquename,type_id)  SELECT 'GG549', (SELECT cvterm_id FROM cvterm WHERE name = 'gene_group')
  WHERE NOT EXISTS (SELECT uniquename FROM grp WHERE uniquename='GG549');


INSERT INTO analysisgrp (analysis_id,grp_id)
SELECT   (SELECT analysis_id FROM analysis WHERE name = 'Planarian Gene Groups') , (SELECT grp_id FROM grp WHERE uniquename = 'GG549')
    WHERE NOT EXISTS (
    SELECT analysisgrp.grp_id FROM analysisgrp,grp WHERE analysisgrp.grp_id = grp.grp_id and grp.uniquename = 'GG549' );


INSERT INTO feature_grp (feature_id,grp_id)
  SELECT (SELECT feature_id FROM feature WHERE uniquename = 'SMU15000918'), (SELECT grp_id FROM grp WHERE uniquename = 'GG549')
  WHERE NOT EXISTS (
      SELECT feature_grp.feature_id,grp.grp_id
      FROM feature_grp, feature, grp
      WHERE feature_grp.feature_id = feature.feature_id
        AND feature.uniquename = 'SMU15000918'
        AND feature_grp.grp_id = grp.grp_id
        AND  grp.uniquename =  'GG549' );

```


Group GG549 won't get created because it already exists. SMU15003648 is being added to this group.
```

INSERT INTO grp (uniquename,type_id)  SELECT 'GG549', (SELECT cvterm_id FROM cvterm WHERE name = 'gene_group')
  WHERE NOT EXISTS (SELECT uniquename FROM grp WHERE uniquename='GG549');


INSERT INTO analysisgrp (analysis_id,grp_id)
SELECT   (SELECT analysis_id FROM analysis WHERE name = 'Planarian Gene Groups') , (SELECT grp_id FROM grp WHERE uniquename = 'GG549')
    WHERE NOT EXISTS (
    SELECT analysisgrp.grp_id FROM analysisgrp,grp WHERE analysisgrp.grp_id = grp.grp_id and grp.uniquename = 'GG549' );


INSERT INTO feature_grp (feature_id,grp_id)
  SELECT (SELECT feature_id FROM feature WHERE uniquename = 'SMU15003648'), (SELECT grp_id FROM grp WHERE uniquename = 'GG549')
  WHERE NOT EXISTS (
      SELECT feature_grp.feature_id,grp.grp_id
      FROM feature_grp, feature, grp
      WHERE feature_grp.feature_id = feature.feature_id
        AND feature.uniquename = 'SMU15003648'
        AND feature_grp.grp_id = grp.grp_id
        AND  grp.uniquename =  'GG549' );
```

**Comment by mario-lopez-c** [comment]
Great, thank you so much! I will do it that way

**Comment by spficklin** [comment]
Thanks @srobb1 .  That's helpful.  After discussion on the Slack space it seems the the group module tables are the only way to do this.  @mario-lopez-c, getting these tables to be visible to Tripal and then create pages from them will be another hurdle but when you get to that stage let us know and we can try to help.

**Comment by mario-lopez-c** [comment]
Ok, great! I will let you know, Thanks @srobb1 @spficklin

**Comment by mario-lopez-c** [comment]
Hello @srobb1, I wonder if this is the module you mean: [https://github.com/astralarya/Chado-group-module]? And my question is how can I install that module into Chado? An the other question is: I just want to show a list of mRNA that are related to an organism, how can I show that list? I already have the data into feature table and I wonder how publish or create that gene group tab that shows a table of the data? How can I do a simple table just with the information that I have in my database? Thank you so much for your help!

**Comment by spficklin** [comment]
@mario-lopez-c . Yes that's the module she was referring to.  But I would recommend against installing it as is.  It's overly broad and from my understanding had performance issues when it was fully implemented. So it has never been baked into Chado fully.  Chado is a community developed database schema and it would take someone to volunteer to spearhead the discussion to get the module fixed up and perhaps finally worked into an updated version of Chado.  

Having said that. My recommendation would be to create just the subset of tables that @srobb1 recommends and manually create those via the Tripal custom table creation tool:  https://tripal.readthedocs.io/en/latest/user_guide/custom_tables.html 

If you create them using Tripal, then Tripal can see them and work with them just like any other Chado table.

**Comment by mario-lopez-c** [comment]
Ok great, I'll do that! Thank you for your recommendation @spficklin

**Comment by mario-lopez-c** [comment]
Hello! I already create my custom table to store the family name per each gene Id, and I have put a column that contains the foreign key that relates that family with the gene id. But I don't know how to show this, I mean I can see the gene Id through the mRNA Content-Type, but I haven't found the way to show the relation of each gene ID with the family that I have stored in my Custom Table, could you help me with this? thanks

**Comment by laceysanderson** [comment]
Hello @mario-lopez-c -sorry for the lack of response! It must have gotten missed because the issue is closed. I'll re-open it now! Have you made any progress on this in the meantime?

**Comment by mario-lopez-c** [comment]
Hi  @laceysanderson thanks! If I could already solve it, don't create a custom table, just use the feature table that is related to the table that stores the genes, and by this means I can show the relationship with the family! Thank you!
