### ISSUE TITLE
Some recent fixes won't work for cached records.

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1187]
### System information

* Tripal Version: 7.x-3.5
* Drupal Version: 7.x
* PostgreSQL Version: N/A
* PHP Version: N/A

### Issue description

Recently a fix was provided by @dsenalik for publications. If you reordered publications on an analysis page (for example) and saved then you would get an error.  He provided a PR that fixed it, but if the analysis page is cached then the fix still won't work because the problem is in the field loading.   I think the solution is to force a cache reload anytime anyone clicks the `edit` button on a page.

**Comment by laceysanderson** [comment]
👍 Yes, 100% Agree. We've (KnowPulse) seen glitchy behaviour on the edit page before due to caching (specifically related to relationships that were added by the other record).

**Comment by laceysanderson** [comment]
Closing this as it will not be fixed in Tripal 3 and does not apply to Tripal 4.
