### ISSUE TITLE
organism not linked to analysis

### ISSUE THREAD

**Issue by shmenolin** [tripal/tripal#1188]
I have linked every analysis to respective organism using analysis_organism table in the chado schema. However, in the analysis web page, I cannot see the organism to be linked to the analysis and I need to do it manually by editing each analysis page. I am using tripal_manage_analysis package. Is there any way to automate the link?

**Comment by dsenalik** [comment]
Interesting, I have started to use this module and have organism links, and was very surprised to see my ```analysis_organism``` table is empty!
For me, it turns out that this table is in the ```public``` schema not ```chado```.

There is also a ```chado.organism_analysis table``` where all my links are.

**Comment by shmenolin** [comment]
Yes I just realized it creates a new table organism_analysis. I could also find mine under the chado schema. Thank you for pointing it out.

**Comment by dsenalik** [comment]
I'm glad this helped. But I still wonder about the history of ```public.analysis_organism``` There is a function in ```tripal_manage_analyses/tripal_manage_analyses.install```:

```
/**
 * Installs the organism_analysis table, migrates analysis_organism.
 */
function create_organism_analysis_table() {
...
  // Now, migrate existing analysis_organism records to the proper linker table.
...
```

**Comment by spficklin** [comment]
@all-contributors please add @dsenalik  for question

**Comment by spficklin** [comment]
HI @shmenolin . Just curious, did you run these two steps: 
- https://github.com/statonlab/tripal_manage_analyses#adding-the-fields
- https://github.com/statonlab/tripal_manage_analyses#enabling-the-fields

**Comment by shmenolin** [comment]
Yes I did. It read the data after I loaded it to the chado.organism_analysis table. It was the existing chado.analysis_organism table it did not read from.

**Comment by spficklin** [comment]
@shmenolin I'm following up to see how things are coming along. Were you able to get the help you needed?

**Comment by laceysanderson** [comment]
Closing as there was no response from the submitter.
