### ISSUE TITLE
Display a list of mRNA sequences associated with a organism

### ISSUE THREAD

**Issue by mario-lopez-c** [tripal/tripal#1190]
Hello! I am using Tripal V3 and I have uploaded a sequence list through a FASTA file, these sequences are associated with a maize organism. I already published the mRNAs in the _Publish Tripal Content_ option, but I would like to know how I can publish a list or table of the mRNA id and when clicking it, the sequence can be displayed...

**Comment by spficklin** [comment]
Hi @mario-lopez-c . I think we have a discussion related to this on issue #1192. So, I'm going to close this one out,  but let me know if I'm wrong and we can re-open.

**Comment by mario-lopez-c** [comment]
Sure! Thanks
