### ISSUE TITLE
Access to each feature through the results table

### ISSUE THREAD

**Issue by mario-lopez-c** [tripal/tripal#1192]
Hi! I wonder if you can help me with an issue...
I have uploaded sequences for an organism, like show the next pic:
![image](https://user-images.githubusercontent.com/45463665/114909174-da946b00-9dea-11eb-92f2-eb2bd58b4174.png)
So, I want to click on each feature to redirect me to its page. But I don't know how to do it, if I click, I get this page:
![image](https://user-images.githubusercontent.com/45463665/114910082-7920cc00-9deb-11eb-8a6f-ad20f298f4b3.png)
And if I change the link path of the field, like this:
![image](https://user-images.githubusercontent.com/45463665/114909286-fa2b9380-9dea-11eb-805d-ad1a846dea84.png)
I get access denied:
![image](https://user-images.githubusercontent.com/45463665/114909336-0a437300-9deb-11eb-8151-906be0afd0f3.png)
I would appreciate if you could help me solve this, thanks

**Comment by Ferrisx4** [comment]
Hi @mario-lopez-c, what is the URL in your browser when you encounter the 'Access denied' page? Also, have you made sure in the Permissions section of the site (`http://site.url/admin/people/permissions`) that users are able to view whatever feature type you are linking to?

**Comment by mario-lopez-c** [comment]
Hi @Ferrisx4, this is the URL in my browser when I encounter the 'Access denied' page: http://52.4.24.39/bio_data/[id]
And yes, I have all the admin permissions, in fact, I am logging in as administrator, and I have all the administrator permissions, and even so, I get access denied. Thank you for your help!

**Comment by spficklin** [comment]
@mario-lopez-c This looks like an old view from the tripal_feature legacy module.   The legacy modules are meant to help  folks transition from Tripal v2 to Tripal v3 but are not required for Tripal v3.     What state is your site in? Are you transitioning over from a Tripal v2 site or setting up a new Tripal v3 site?

**Comment by mario-lopez-c** [comment]
Hi @spficklin, I am setting up a new Tripal v3 site, so is not a transition over form a Tripal v2 site. So do you know how can a publish mRNA content in a table format for a specific organism?

**Comment by spficklin** [comment]
First you'll want to disable/uninstall  the legacy modules as you don't need them.  

Next, you can use the built-in search tools that Tripal provides.  Tripal will automatically create a Drupal View for searching any content type.   You can read about it here:  https://tripal.readthedocs.io/en/latest/user_guide/searching/default_pages.html.

This search tool is a Drupal View that Tripal creates. If you aren't familiar with Drupal Views you can read more about them here (https://www.drupal.org/docs/7/modules/views). They let you create custom search or tabular views of data without any programming. It's a great feature of Drupal. 

Once you have added any customizations to the search tool, you can add it to your site's menu and provide them to users.

**Comment by mario-lopez-c** [comment]
Thank you @spficklin, this helps me a lot! I will write to you again if I have any questions! Thanks
