### ISSUE TITLE
sio__references using wrong cvterm as label when linking to a tripal map

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1202]
### System information

* Tripal Version: 7.x-3.5
* Drupal Version: 7.78
* PostgreSQL Version: 12.6 (Ubuntu 12.6-1.pgdg16.04+1)
* PHP Version: 7.3.27-9+ubuntu16.04.1+deb.sury.org+1

### Issue description
This issue occurs when the tripal field ```sio__references``` displays a link to a linkage map (Tripal Map).
The label (```rdfs:type```) is the unit type used for the linkage map. This is almost always CM (centiMorgans) for a genetic map, but may be bp (base pairs) for a physical map.
The issue is that the field will only display one or the other of these, regardless of the actual units. In my case it always displayed **Bp(s)** instead of **CM(s)**
This occurs because the code in ```tripal/tripal_chado/includes/TripalFields/sio__references/sio__references.inc```
looks for a ```type_id``` value and uses this to set the ```type_name``` value. A map uses ```unittype_id``` instead so it doesn't find a value. In this case it defaults to the value from ```$ref_type->name```, which in my case was always "bp", which came from
```$ref_type = chado_get_cvterm(['cvterm_id' => $ref_mapping->cvterm_id]);```
which just gets the one that by chance appears first in the ```chado_cvterm_mapping``` table.

### Discussion
I have a fix for this, but is this how we want to label linkage maps, though? **CM(s)**

#### Steps to reproduce
You would need a map of each of two different unit types and see how they are each displayed in the ```sio__references``` field.

#### Error messages and screenshots
Before fixing this:
![before](https://user-images.githubusercontent.com/8419404/117672893-e2d49180-b16f-11eb-9157-7f7f31e20cb8.png)

And after:
![after](https://user-images.githubusercontent.com/8419404/117672915-e9fb9f80-b16f-11eb-9ccd-fc410956e8db.png)

**Comment by dsenalik** [comment]
I have a pull request #1204 which bypasses the Bp vs. CM problem by calling these **Map(s)**

**Comment by spficklin** [comment]
Fixed with PR.  Thanks @dsenalik
