### ISSUE TITLE
Bulk loader editing bug when deleting first record

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1205]
### Issue description
It is not possible to delete the first record when editing a bulk loader template, if attempted the following error appears
![CBL-delete-first-item](https://user-images.githubusercontent.com/8419404/118364038-75a07200-b55c-11eb-8dbf-3782b142e961.png)

#### Steps to reproduce
Select Delete on the first record, e.g.
![CBL-edit-template-box](https://user-images.githubusercontent.com/8419404/118363991-54d81c80-b55c-11eb-9b5f-10b8cc8f565a.png)

**Comment by laceysanderson** [comment]
To my understanding, this issue was solved by the merged PR. If not please comment and I will re-open :-)
