### ISSUE TITLE
User's Guide Update

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1207]
I'm currently working on reorganizing the User's Guide to make it easier to find things. Right now it reads like a tutorial and that's not helpful when folks just need to look up how to do something.  

Please add your comments here if you would like to see specific improvements to the user's guide.

**Comment by CFGrote** [comment]
Hi, hope this is the right place to report such things:

Looking at the C.sinensis example at https://tripal.readthedocs.io/en/latest/user_guide/example_genomics/genomes_genes.html#loading-fasta-files

There's a typo in the regex to pull out the accession:  ~`^.*PAC:(d+).*$`~ should read `^.*PAC:(\d+).*$`

**Comment by laceysanderson** [comment]
Closing this as the documentation has been reorganized for Tripal 4 and is now hosted in https://github.com/tripal/tripal_doc
