### ISSUE TITLE
Is it possible to draw PCA plot and/or bar charts in Tripal?

### ISSUE THREAD

**Issue by felipead6** [tripal/tripal#1210]
## Feature Request/Discussion

* This feature [does / does not] attempt to solve an existing problem with Tripal
* I [am/am not] open to developing or collaborating on an extension module if this is not a good fit for Tripal Core

* This feature is [URGENT/Not Urgent]

**Comment by spficklin** [comment]
Hi @felipead6.  I'm not aware of any Tripal extension module that automatically creates PCA plots for data.  However, it is possible to create such a plot with PHP/Javascript coding. What sort of data are you interested in creating a PCA plot for?

**Comment by spficklin** [comment]
@felipead6 . I'm going to close this out due to no comments in awhile. If you want to chat more on this just respond and we can reopen it.
