### ISSUE TITLE
Unable to change Field formatter settings due to AJAX error

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1213]
### System information

* Tripal Version: 3.6
* Drupal Version:  7.x
* PostgreSQL Version: N/A
* PHP Version: 7.4

### Issue description

When managing a Tripal content type display each Tripal Pane and Table has a little cog for changing the settings.  For example, below is a screen shot for the Organism content type, Publicaation Pane.  Note the cog on the far right for changing settings.

![image](https://user-images.githubusercontent.com/1719352/121931532-99d8a580-ccf8-11eb-9c4a-1f9d7a3e3699.png)

If you click that you will get the following error message:

![image](https://user-images.githubusercontent.com/1719352/121930749-909b0900-ccf7-11eb-90fc-b5d13f0a6404.png)

**Comment by spficklin** [comment]
Here's the error message in in the Reports log for when this error occurs:

```
Error: Unsupported operand types in element_children()(line 6695 of /var/www/html/includes/common.inc).
```

On that line of code in Drupal it's trying to get the weights of the children elements that appear in the form.  It seems the weights for these elements are arrays instead of a single value which causes the Ajax error. I can get around it by adding an if statement to the Drupal code right before the line indicated in the error and if the weight is an array I just have it return the first value.  It works then.  But that's not a good fix.  So, we need to find out why it's doubling/tripling up the weights into an array.

**Comment by laceysanderson** [comment]
Closing as we are no longer supporting Drupal 7 / Tripal 2/3 and this is specific to the field formatters which have been completely rewritten.
