### ISSUE TITLE
Show Synonyms in mRNA Content Type

### ISSUE THREAD

**Issue by mario-lopez-c** [tripal/tripal#1214]
Hello! Do you know to show synonyms in the mRNA Content-Type? I mean, I have loaded into the synonym table some data and related it to the feature table through feature_synonym table, but I don't know how to publish those synonyms within the mRNA content type, I have only been able to publish the information that is within the featureprop table.
Thank you!

**Comment by spficklin** [comment]
Hi @mario-lopez-c apologies for the slow reply.  So, after investigating this issue it seems we have a very simple bug in the code that prevented synonyms from appearing.   I will make a quick fix and it should resolve the problem for you.  If you could test the pull request for me to make sure its fixed on your site that would be great and should speed up getting this fix into the next release.  I'll tag you in the pull request.

**Comment by spficklin** [comment]
Okay, the PR is submitted with the rfix.  @mario-lopez-c can you test it on your site to make sure you can now get synonyms?   Here's the link to the PR:  #1223

**Comment by spficklin** [comment]
I believe this issue has been fixed in the recent PR.  I'm going to close out the issue. Please comment if there's still a problem.

**Comment by mario-lopez-c** [comment]
Thank you so much! That worked! Thank you!
