### ISSUE TITLE
Publish mRNA content error

### ISSUE THREAD

**Issue by Bobo22331** [tripal/tripal#1219]
### System information

* Tripal Version: 7.x-3.6
* Drupal Version: 7.69
* PostgreSQL Version: 10
* PHP Version: 7.0

### Issue description
Publish mRNA content error

#### Steps to reproduce
When I update tripal from version 3.4 to 3.6, and then I import a genome gff file and publish mRNA pages, the error occurs.

#### Error messages and screenshots

```

2021-07-15 14:23:36
Tripal Job Launcher
Running as user 'admin'
-------------------
2021-07-15 14:23:36: There are 1 jobs queued.
2021-07-15 14:23:36: Job ID 15398.
2021-07-15 14:23:36: Calling: chado_publish_records(Array)
Job execution failed: SQLSTATE[42703]: Undefined column: 7 ERROR:  column t.featuremap does not exist                                                                                                 [error]
LINE 1: ...ND T.type_id = '425' AND T.organism_id = '16' AND T.featurem...
                                                             ^
HINT:  Perhaps you meant to reference the column "t.feature_id".
```

**Comment by dsenalik** [comment]
Do you have the tripal map module loaded? I suspect it may be the same issue I ran into here

https://gitlab.com/mainlabwsu/tripal_map/-/issues/61

My fix was just merged two weeks ago, so if it's this, you can update tripal map to fix it.

**Comment by Bobo22331** [comment]
@dsenalik Yeah, maybe it's the same issue with tripal_map module. I'll try to update it. 
Thank you!

**Comment by Bobo22331** [comment]
@dsenalik I've update tripal_map module and the error occurs again!

**Comment by Bobo22331** [comment]
Publish gene pages didn't occur this error.

**Comment by dsenalik** [comment]
Check the file 

```sites/all/modules/tripal_map/includes/tripal_map.fields.inc```

line 154 and make sure the fix is there, if correct, it should be
```
          'chado_column' => 'feature_id',
```

Another thing to try is to temporarily disable the tripal_map module and see if the problem goes away. If not, it is coming from somewhere else.

**Comment by Bobo22331** [comment]
OK. I'll try it. Thank you!

**Comment by Bobo22331** [comment]
@dsenalik 
I've tried as you said. When I temporarily disable the tripal_map module, the error didn't occur.
Thank you for your suggestion.

**Comment by dsenalik** [comment]
I am still having some publishing errors with a slightly different error message. See tripal map issue [#61](https://gitlab.com/mainlabwsu/tripal_map/-/issues/61) and merge request [!55](https://gitlab.com/mainlabwsu/tripal_map/-/merge_requests/55) for description and resolution.
