### ISSUE TITLE
A security bug?

### ISSUE THREAD

**Issue by chunhuaicheng** [tripal/tripal#1220]
### System information

* Tripal Version: 3.4, 3.5, 3.6, and 7.x-3.x
* Drupal Version: 7.82
* PostgreSQL Version: 13.3
* PHP Version: 7.4.3

### Issue description

After editing a Tripal page (such as an Organism), the logged-in user gains privileges of the user who previously created the page.

#### Steps to reproduce
1. Log in as a user who is authorized to edit a Tripal page, such as a curator.
2. Edit a Tripal page that is created by a different user, such as an admin.
3. Click on 'Update' to save the page
4. Now you're logged in as the user who created the Tripal page. (the admin)

#### Error messages and screenshots

Step1: Log in as curator
![step1](https://user-images.githubusercontent.com/14333886/126852856-cdd75fa5-d5c9-4549-8f34-5223426d4730.png)

Step2: Edit a Tripal page
![step2](https://user-images.githubusercontent.com/14333886/126852858-80b0d60b-7894-4571-be10-8d770e7209db.png)

Step3: Save
![step3](https://user-images.githubusercontent.com/14333886/126852859-bf09868f-5859-4db4-a7d5-c728255787a7.png)

Step4: Now you are the admin
![step4](https://user-images.githubusercontent.com/14333886/126852861-226ad496-246e-4661-8982-85999f47dff6.png)

**Comment by jcrabbwsu** [comment]
To add to the behavior described above:
When the authenticated user is also the author of the page, the steps described above result in the user being logged out.

**Comment by spficklin** [comment]
I've added a PR (#1224) to fix this if anyone watching this thread wants to test.  Once this gets tested and merged in we'll make a new Tripal release to get this fix out.

**Comment by risharde** [comment]
@spficklin Just tested your commit and it resolved the security issue on my side.

**Comment by spficklin** [comment]
Issue resolved in dev branch with recent PR.
