### ISSUE TITLE
chado_delete_feature() deletes too much on failure to match

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal#1229]
### System information

* Tripal Version: 7.x-3.6
* Drupal Version: 7.67
* PostgreSQL Version: 11.3
* PHP Version: 7.3.3

### Issue description

When using the function [chado_delete_record()](https://github.com/tripal/tripal/blob/fe1f70dc607eb8108814e675f4d11abe453cdb6a/tripal_chado/api/tripal_chado.query.api.inc#L1002), for instance on trying to delete features tied to an organism:
```php
$values =  array(
  'organism_id' => array(
      'genus' => 'Citrus',
      'species' => 'sinensis',
   ),
  'type_id' => array (
      'cv_id' => array (
         'name' => 'sequence',
      ),
      'name' => 'gene',
      'is_obsolete' => 0
   ),
);

$result = chado_delete_record(
   'feature',                      // table to select from
   $values                         // records to delete (see variable defn. above)
);
```
if there is no organism found matching Citrus sinensis, the function will simply leave the organism_id clause out of the SQL and will try to delete all other features matching the rest of the specified parameters (in this example, type_id).
Compare the following generated SQL
SQL generated with matching organism found in the db:
```sql
DELETE FROM {feature} WHERE  organism_id = :organism_id AND  type_id = :type_id 
```
SQL generated with no matching organism found in the db:
```sql
DELETE FROM {feature} WHERE  type_id = :type_id
```

#### Steps to reproduce

Try to delete features for a particular organism that doesn't exist.

#### Comments
I'm not sure if this is the intended functionality, but it seems dangerous to continue to delete records when any of the filters do not match. The language in the inline documentation seems to indicate that the parameters will be treated as AND but it seems to be operating as OR.

**Comment by laceysanderson** [comment]
Closing this as it will not be fixed in Tripal 3 and is not applicable to Tripal 4.
