### ISSUE TITLE
Error when loading GFF with GO terms not found in CVTERMS

### ISSUE THREAD

**Issue by srobb1** [tripal/tripal#1230]
* Tripal Version: 3.7
* Drupal Version: drupal-7.78
* PostgreSQL Version: 12.8
* PHP Version: 7.4.3

### Issue description
When loading a GFF I get this error if I have an Ontology_term in my GFF that is not in my db.

```
SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block
[site http://default] [TRIPAL ERROR] [TRIPAL_JOB] SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

After I got this error I was able to find this in my postgres log
```
2021-09-17 19:22:25.907 UTC [29090] drupal@drupal ERROR:  null value in column "cvterm_id" violates not-null constraint
2021-09-17 19:22:25.907 UTC [29090] drupal@drupal DETAIL:  Failing row contains (156798, 85589, null, 1, f, 0).
```
This is for an insert into feature_cvterm with these columns 
```
 feature_cvterm_id | feature_id | cvterm_id | pub_id | is_not | rank
-------------------+------------+-----------+--------+--------+------
```

I got the uniquename for feature_id 85589 and tracked down the line in my gff. I checked to see if any of my GO terms were not in the db. One was not in the db. Turns out it is an alt_id. I removed that GO term from my gff and successfully reloaded. 

Doesn't the GFF loader create placeholder cvterms for terms not found in the DB?

Thanks,
Sofia

**Comment by mpoelchau** [comment]
@srobb1 thanks for posting this - I ran into the same issue this week as well (I should have loaded an ontology prior to the gff but forgot). Having this documented helped me figure out the problem a lot faster. Not sure if it would be possible to have more information printed out about the error (e.g. not having to dig through the postgres logs).

**Comment by srobb1** [comment]
Hi @mpoelchau. @spficklin and I chatted about this. If I remember correctly, I think we decided it might be possible to print out a more informative error message with the offending ontology ID. I wanted to dig back in and try to figure this out, but got wrapped up in other things. This is definitely something I want to get fixed, it was a big pain to track it down. Maybe your message will motivate me to figure this out once and for all. Thank you :)

**Comment by mpoelchau** [comment]
Glad to provide some motivation :). No rush on my part though - I was just grateful that you posted the issue since it saved me some time!

**Comment by laceysanderson** [comment]
Moving this discussion over to Tripal 4.

**Comment by laceysanderson** [comment]
Do either of you have a short test file for this so I can check if it's still a problem in T4? 

That way if it is we can get a better error message printed while @risharde is working on that loader.

**Comment by spficklin** [comment]
In an effort to cleanup open issues, and since this one is really old. @srobb1 if you have a short file as per @laceysanderson 's requst we can reopen.
