### ISSUE TITLE
I need a reverse of function chado_abbreviate_infraspecific_rank()

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1243]
## Feature Request/Discussion
There is a function in ```tripal/tripal_chado/api/modules/tripal_chado.organism.api.inc``` named
```chado_abbreviate_infraspecific_rank```. It takes an infraspecific type, e.g. subspecies, and returns the abbreviation, e.g. subsp.

I am working on the newick tree loader to add organism associations, and I have a need of the inverse of this function.

I propose to add ```function chado_unabbreviate_infraspecific_rank($rank)```

### Your Specific Use Case
I would use this to lookup organism_id from a label when loading a newick format tree file

**Comment by spficklin** [comment]
I think this issue is resolved with PR #1244 .  But please comment if issues still remain.
