### ISSUE TITLE
The newick phylotree loader does not link to organisms when loading "taxonomic" trees

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1245]
### Description

I've been working on the newick tree loader for a while, and this issue will be a placeholder for an eventual pull request, currently a work in progress.

A couple of issues I am working on here:
1. A lot of the job progress output is only viewable by running the drush job at the command line, so there needs to be some fixes for logging.
2. More log messages to show if leaf nodes were or were not associated with features.
3. A tree of type "taxonomy" (cv term "Species tree") should link to organisms instead of features. This does not happen because there is no code to look up organisms. This needs to be added. Pull request #1243 is going to be part of this.
4. There is a bug in the regular expression option because the option exists but is a null string, I added a fix for that.
5. A few typos.
6. The "Feature Name Regular Expression" does not work for taxonomy trees, but there is no reason it can't be made to work.
7. The ```operation__phylotree_vis_formatter``` field always says ```Click a species to view its species page.```, it should have a different message for non-taxonomic trees which link to a feature.
8. Taxonomy tree loader on rare occasions gets an incorrect taxid from NCBI, e.g. https://www.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=taxonomy&term=Torilis+arvensis+subspecies+neglecta returns 1924105 which is a bacterium.
9. I think there is a typo to be fixed, ```=``` instead of ```==``` in ```TaxonomyImporter.inc```
```
           if ($branch_set[$j]['name'] == $node['name'] and
            $branch_set[$j]['depth'] = $node['depth']) {
```
10. Implement the "to-do" in ```TaxonomyImporter.inc``` to use NCBI taxid linked to organism, if present, to avoid a query. This brings up an issue if we have a heterotypic synonym. In this case, we should use the site taxon name rather than the returned NCBI taxon name.
11. In ```function tripal_phylogeny_parse_newick_name``` an arbitrary bootstrap value is created (incrementing integers) for internal nodes and used for the 'name' field. If this is not actually used anywhere, a null string would seem more appropriate. This is not changed in the current pull request.

**Comment by spficklin** [comment]
Issue fixed with PR #1262
