### ISSUE TITLE
create_point problems

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#125]
Whenever the featureloc.fmin and fmax columsn are queried it uses several indexes that call the create_point() PgPLsql function.  But, because chado is not in the search_path the query fails.   The SQL statements below fix this problem, but requires that the chado database be in the 'chado' schema, which may not always be the case for every Tripal site.  We need a way to perhaps fix these indexes without causing additional scope problems. 

```
CREATE OR REPLACE FUNCTION boxrange (bigint, bigint) RETURNS box AS
 'SELECT box (chado.create_point(0, $1), chado.create_point($2,500000000))'
LANGUAGE 'sql' IMMUTABLE;

CREATE OR REPLACE FUNCTION boxquery (bigint, bigint) RETURNS box AS
 'SELECT box (chado.create_point($1, $2), chado.create_point($1, $2))'
LANGUAGE 'sql' IMMUTABLE;

CREATE OR REPLACE FUNCTION boxrange (bigint, bigint, bigint) RETURNS box AS
 'SELECT box (chado.create_point($1, $2), chado.create_point($1,$3))'
LANGUAGE 'sql' IMMUTABLE;

CREATE OR REPLACE FUNCTION boxquery (bigint, bigint, bigint) RETURNS box AS
 'SELECT box (chado.create_point($1, $2), chado.create_point($1, $3))'
LANGUAGE 'sql' IMMUTABLE;
```

**Comment by laceysanderson** [comment]
I didn't find the above fixed fmin/fmax in views for me... However, simply creating a duplicate of the functions in the public schema (including create point) fixed it for me.

```sql
SET search_path TO public;
-- create a point
CREATE OR REPLACE FUNCTION create_point (bigint, bigint) RETURNS point AS
 'SELECT point ($1, $2)'
LANGUAGE 'sql';

-- create a range box
-- (make this immutable so we can index it)
CREATE OR REPLACE FUNCTION boxrange (bigint, bigint) RETURNS box AS
 'SELECT box (create_point(0, $1), create_point($2,500000000))'
LANGUAGE 'sql' IMMUTABLE;

-- create a query box
CREATE OR REPLACE FUNCTION boxquery (bigint, bigint) RETURNS box AS
 'SELECT box (create_point($1, $2), create_point($1, $2))'
LANGUAGE 'sql' IMMUTABLE;
```
This works b/c Postgresql allows the same function to exist in multiple schema and then it simply uses the first one it comes across. Thus even if you have both public and chado in the search_path this won't cause a problem.

This solution fixes the hard-coding of the name of the schema although it does still require chado be in the same database (as does all of views).

**Comment by bradfordcondon** [comment]
@spficklin @laceysanderson any insight into this?

Should tripal install the function public schema?  Should we mark this closed? Let it exist as an open issue in the "done" pipeline?

**Comment by spficklin** [comment]
Since we have bigger fish to fry and I think we've got plenty of work arounds for this for major functionality I think we can close until someone hits on the problem again elsewhere.
