### ISSUE TITLE
Add option for radio-button instead of checkbox on tripal_get_term_lookup_form()

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1258]
## Feature Request/Discussion

* This feature does attempt to solve an existing problem with Tripal
* This feature is Not Urgent

### Description
In ```tripal/tripal/api/tripal.terms.api.inc``` line 594 ```function tripal_get_term_lookup_form()``` is used to select one cvterm from among several. I think the typical use case is to only select one term. This function currently uses checkboxes, and can return more than one term. An option to use a radio button instead of a checkbox would make it clear that only one option can be returned.

I am adding in a fix for a bug I found in here. CVs with long definitions are not getting expanded as intended. There is a separate commit to this pull request that adds a fix for this. The bug manifests as a notice of the form
```Notice: Undefined property: stdClass::$definition in tripal_get_term_lookup_form() (line 712 of .../sites/all/modules/tripal/tripal/api/tripal.terms.api.inc).```

### Your Specific Use Case
This would be incorporated into https://github.com/tripal/tripal_analysis_expression/pull/392 to make it clear that only one term can be returned.

### Generally Applicable
There may be a small number of other places this could be incorporated, _e.g._ in ```tripal/tripal/includes/TripalBundleUIController.inc``` line 605 only the first item is returned, so a radio button could be used here also
```
    $selected = tripal_get_term_lookup_form_result($form, $form_state);
    if ($selected) {
      $selected_term = $selected[0];
    }
```

### Additional information/screenshots
The bad thing about this is that we would be adding one more parameter to ```tripal_get_term_lookup_form()```, and it already has 12 parameters!

**Comment by spficklin** [comment]
I agree, this is an important issue that needs fixing. The function that provides the form element is meant to only return a single selected item and if more than one is clicked it will be confusing for the end-user and may break some forms.

**Comment by spficklin** [comment]
Issue fixed with PR merge.  Thanks @dsenalik
