### ISSUE TITLE
Tripal field obi__organism infraspecific type no_rank displaying

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1260]
### System information

* Tripal Version: 7.x-3.8
* Drupal Version: 7.88
* PostgreSQL Version: 13.4
* PHP Version: 7.2.24-0

### Issue description

CarrotOmics.org makes extensive use of infraspecific nomenclature, e.g. subspecies, and the organisms without infraspecific nomenclature use the CV term ```taxonomic_rank:no_rank``` for the ```chado.organism``` table ```type_id``` column. This shows up in the output of the ```obi__organism``` field. A special case override is needed to mask "no_rank" from appearing in the field.

#### Steps to reproduce

Need: Chado v1.3 + organism with type_id taxonomic_rank:no_rank

View a page using this field, e.g. a stock page of Germplasm Accession with an organism without infraspecific nomenclature, but which has the ```no_rank``` CV term for the chado.organism table type_id column. Note that this does not happen entering an organism manually via web page, the type_id column in that case will be ```NULL```. We use a chado bulk loader for organisms.

#### Error messages and screenshots
Example
![obi__organism](https://user-images.githubusercontent.com/8419404/159573589-82eba0f3-9c88-4f6b-9927-9eb9b9f3ba84.png)

**Comment by spficklin** [comment]
Fixed with PR #1261
