### ISSUE TITLE
GFF3 loader invalid characters check broken?

### ISSUE THREAD

**Issue by jhumann** [tripal/tripal#1265]
### System information
* Tripal Version: 3.8
* Drupal Version: 7.88
* PostgreSQL Version: 12.9
* PHP Version: 7.3

### Issue description
I am testing the GFF loader on our dev site with a genome I previously loaded on our production site (Tripal v3.3).  When I am loading the GFF file of the scaffolds it tells me a landmark name has invalid characters.  We can't figure out which character is an issue.

#### Steps to reproduce
Opened 'Chado GFF3 File Loader' page.  Added path to GFF3 file for genome scaffolds.  Selected Analysis Name and Organism and entered 'supercontig' as landmark type.  Then clicked 'Import GFF3 file' and ran drush command from terminal.  I can send the gff file I used on request.

BTW, it looks like the 3 sections at the bottom of the loader page (Proteins, Targets, Additional Options) that should be expandable are always expanded and can't be collapsed.

#### Error messages and screenshots
```
2022-03-31 14:36:13: Calling: tripal_run_importer(87)

Running 'Chado GFF3 File Loader' importer
NOTE: Loading of file is performed using a database transaction.
If it fails or is terminated prematurely then all insertions and
updates are rolled back and will not be found in the database

Opening /mainlab/research/vaccinium/Massimo_BlueberryGenome-Nov2021/W85-20-scaffolds.gff
Opening temporary cache file: /mainlab/web/temp/vaccinium/TripalGFF3Import_iJIZP8
Step  1 of 27: Caching GFF3 file...
Removing temporary cache file: /mainlab/web/temp/vaccinium/TripalGFF3Import_iJIZP8
Landmark/seqid Vcev1_p0.Chr01_V_caesariense_W85-20_v1 contains invalid
        characters. Only characters included in this regular expression is
        allowed [a-zA-Z0-9.:^*$@!+_?-|]
[site http://default] [TRIPAL ERROR] [TRIPAL_JOB] Landmark/seqid Vcev1_p0.Chr01_V_caesariense_W85-20_v1 contains invalid        characters. Only characters included in this regular expression is        allowed [a-zA-Z0-9.:^*$@!+_?-|]
```

**Comment by spficklin** [comment]
Hey @jhumann if you want to get me a copy of your GFF3 file I can test what's going on.

**Comment by jhumann** [comment]
I have sent you the file via other methods, but since the data is public now here is the GFF file saved with a .txt extension so Github lets me attach it.  I also tried this with the most recent version of Tripal on our dev site and I get the same error.

[W85-20-scaffolds.txt](https://github.com/tripal/tripal/files/9376501/W85-20-scaffolds.txt)

**Comment by dsenalik** [comment]
I found the problem in the regex, "-" was not escaped. I'll make a pull request to fix it.
```    preg_match('/[a-zA-Z0-9\.:\^\*\$@!\+_\?-\|]*/', $ret['landmark'], $matches);```
should be
```    preg_match('/[a-zA-Z0-9\.:\^\*\$@!\+_\?\-\|]*/', $ret['landmark'], $matches);```

**Comment by dsenalik** [comment]
Note that this bug would have let through some "not-valid" characters, i.e. ```[  ]  `  {```
everything from ascii ```?``` to ```|``` was allowed

**Comment by jhumann** [comment]
Thanks Doug!

**Comment by spficklin** [comment]
Thanks @dsenalik .  I've merged the fix. @jhumann  does this resolve the problem for you?

**Comment by jhumann** [comment]
Yes, we manually applied the fix and have been testing it.  It has resolved the issue.

**Comment by spficklin** [comment]
Great. I'll close this out.  This fix will be in the next Tripal release. If you need it sooner than later we can just do a quick release to get it out. Let us know.
