### ISSUE TITLE
GFF3 bug detected by Stephen

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#1271]
GFF3 loader

Line 2270:
$sql = "SELECT name, uniquename, feature_id FROM {feature} WHERE uniquename in (:landmarks)";
 
Stephen mentioned we need to perform a query that should include the organism ID here

referencing @spficklin

**Comment by spficklin** [comment]
Yes, this needs to be fixed because it doesn't include the unique constraint in the query (uniquename, organism_id, type_id).  Which means the GFF3 loader could accidentally pickup a landmark from another organism if it had the same name.

**Comment by gdroc** [comment]
I had the same issue that I fixed by adding the organism
Line 2270 add this line
$organism_id =  $this->organism->getID();
$sql = "SELECT name, uniquename, feature_id FROM {feature} WHERE uniquename in (:landmarks) AND organism_id=:organism_id";
Line 2290
          $args = [':landmarks' => $names,':organism_id' => $organism_id];

Gaetan

**Comment by dsenalik** [comment]
@gdroc I made this into a pull request :+1:

**Comment by laceysanderson** [comment]
The organism_id is now included in the query on the main branch 🎉 
That said, you may also be interested in Issue #1324 if you ended up on this issue which addresses the type_id not being in the query.
