### ISSUE TITLE
Add Tripal Content shows term definition instead of content type description.

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#1273]
## BUG/ERROR report

If you look on the Edit page for a Tripal Content Type you will see that the help text under the description implies this text will be displayed on the Add new content page (see pink in below screenshot). Yet when you change it and then check the add content page, you see the term definition which is not the text you entered... (see second screenshot from the admin/content/bio_data/add page).

You can confirm this is the term definition being displayed by [looking at the code for that listing](
https://github.com/tripal/tripal/blob/7.x-3.x/tripal/includes/TripalEntityUIController.inc#L865). We need to fix this so the admin sees the bundle description text on the add content page as expected.

### Screenshot 1: Edit Research Experiment Tripal Content Type
![EditTripalContentType](https://user-images.githubusercontent.com/1566301/165645722-850f6d50-9f75-4472-b01f-b13a11179b4b.png)

### Screenshot 2: Research Experiment listed on the "Add Tripal Content" listing page
<img width="725" alt="Screen Shot 2022-04-27 at 5 05 28 PM" src="https://user-images.githubusercontent.com/1566301/165645752-59aba436-4567-4be7-a14b-733802a9c276.png">

**Comment by spficklin** [comment]
Fixed with PR #1274
