### ISSUE TITLE
Radio buttons in function tripal_get_term_lookup_form() are not linked by name

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1277]
### Issue description
The cvterm lookup form uses radio buttons to select a term. Right now, once checked, the button cannot be unchecked and multiple buttons can be checked.

This is defined by ```function tripal_get_term_lookup_form()``` in ```tripal/api/tripal.terms.api.inc``` and the form needs something like ```'#name' => $appropriate_unique_value,``` at about line 712. I'm not sure what that value should be, though. ```$delta``` is working, but is it guaranteed unique? Actually that doesn't work, the selected value is not returned.

#### Error messages and screenshots
![radiobuttons](https://user-images.githubusercontent.com/8419404/171287386-09264fda-84a9-4e73-b085-772ae8fc0147.png)

**Comment by dsenalik** [comment]
This same bug affects editing semantic web terms ```/admin/tripal/storage/chado/semweb```
Presumably if I figure it out, the fix will be the same.

**Comment by spficklin** [comment]
You should be able to uncheck by holding the shift button while clicking (I believe). But that's not obvious....

**Comment by dsenalik** [comment]
It doesn't work, because each radio is an individual, not joined to the others. Still working on it...

**Comment by dsenalik** [comment]
This was a tricky thing to fix. I converted the individual 'radio' elements into a single 'radios', but then drupal 7 does not allow individual descriptions for each radio. But this can be added with a callback (relatively simple after you spend a long time to figure it all out).

It's important to fix this, because the current version does not reliably return the selected item, and the inability to unclick a radio and select multiple radios is not so good. I'll test some more then submit a pull request.
