### ISSUE TITLE
Field Debugging Mode

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#128]
If you are writing a new field, it can be challenging to determine where problems may be occurring when it doesn't work as expected.  We need a way to turn on some helpful debugging to help developers work through debugging their custom fields.

**Comment by bradfordcondon** [comment]
Tripal Test Suite!  Still we haven't taken the time to figure out how this should work.

**Comment by laceysanderson** [comment]
See #671 for how to test fields, widgets and formatters using TripalTestSuite.

**Comment by laceysanderson** [comment]
It is still very difficult/impossible to test fields/widget/formatters using TripalTestSuite... Perhaps some documentation on how to debug custom fields might be more realistic.

**Comment by spficklin** [comment]
This is awesome but I think will be a lot of work.  I'm marking as 'Maybe Later'.
