### ISSUE TITLE
Automated testing is broken due to multi-schema querying bug in Drupal 7

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1281]
### Issue description

See pull #1279 and I replicated it with a branch with just a single typo change, same errors.

There are actually two errors
```
[site http://127.0.0.1:8080] [TRIPAL ERROR] [TRIPAL_CHADO] Missing $object argument to the chado_expand_var function from tripal_chado_field_storage_load (line: 426)
```
and
```
Error: PDOException: SQLSTATE[42602]: Invalid name: 7 ERROR:  invalid name syntax
LINE 6: AND pg_attribute.attrelid = '.chado.cv'::regclass
                                    ^
```

The first one does not trigger failure, but the second one does. 

The SQL comes from ```includes/database/pgsql/schema.inc``` line 136,
which is in ```function queryTableInformation($table)```
The table name ```.chado.cv``` should not start with a period.

I need help figuring out what is causing this, what calls that with a period prefix. The testing process is still a mystery to me. I need to figure out how to run the tests locally I think...

The first error has been there for a while at least since April 28 I see it in https://github.com/tripal/tripal/pull/1274/checks

**Comment by dsenalik** [comment]
Related drupal issue https://www.drupal.org/project/drupal/issues/3284424

**Comment by dsenalik** [comment]
That issue is a patch that would resolve this error.
The error was introduced in Drupal with https://git.drupalcode.org/project/drupal/-/commit/0a7ef860a854dbe83783211d14ffe2d31300605d

**Comment by spficklin** [comment]
Yeah, it looks like we may just have to wait until the next minor release of Drupal 7 for this to go away.

**Comment by laceysanderson** [comment]
The above PR adds the Drupal 7 patch that fixes this. Once that patch is incorporated into Drupal 7 then we will want to remove it from the automated testing.

**Comment by laceysanderson** [comment]
I'm re-opening this as the PR fixes the automated testing but the bug still remains in Drupal core. This issue should remain open until the patch is incorporated into Drupal 7 in a release and the patch is removed from the automated testing workflow.

**Comment by laceysanderson** [comment]
closing this as it's no longer needed with the move towards Drupal 9/10 it is unlikely the linked fix will ever be incorporated into Drupal 7.
