### ISSUE TITLE
Vocabulary warnings shown to end-users

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal#1283]
### Issue description

Occasionally, a warning about missing details for a vocabulary is generated. This warning was enhanced in #500 by suggesting a fix.
This issue is not about the fact that the warning gets generated, but that it is shown to the end-user.

It would be a simple fix to make a check to see if the user is an admin or not.

#### Error messages and screenshots

![Cropped](https://user-images.githubusercontent.com/9593623/175560977-10a99c95-6087-47a5-8f6e-187082024c7b.png)

**Comment by spficklin** [comment]
Fixed with recent PR
