### ISSUE TITLE
Warning in Feature Search response: htmlspecialchars() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by CFGrote** [tripal/tripal#1285]
### System information
* Tripal Version: 7.x-3.8
* Drupal Version: 7.78
* PostgreSQL Version: 10.21
* PHP Version: 7.2.24

### Issue description
Searching via the Feature Search (/search/features) field returns a long list of Warnings such as
```
Warning: htmlspecialchars() expects parameter 1 to be string, array given in check_plain() (line 1858 of /var/www/html/includes/bootstrap.inc).
```
and
```
Warning: strip_tags() expects parameter 1 to be string, array given in tripal_field_property_get() (line 399 of /var/www/html/sites/all/modules/tripal/tripal/tripal/includes/tripal.entity.inc).
```

#### Steps to reproduce
* Navigate to http://pflu.evolbio.mpg.de
* Click on "Feature Search" in the left menu
* Enter "wssH" nto the Feature Search field, hit [Enter]
* Observe the Warnings before the search results.

#### Error messages and screenshots
See above and

![image](https://user-images.githubusercontent.com/15476807/177209632-367b98eb-3e4a-46df-b5e7-7c9af33748f4.png)

#### Feature search config
![image](https://user-images.githubusercontent.com/15476807/177210044-e7007939-a8e5-464e-87bc-f730921cc946.png)
![image](https://user-images.githubusercontent.com/15476807/177210091-c996ac30-aef5-4edd-aa4e-1edf9a691b73.png)

#### Further observations
Searching for the same string via /chado/feature does not produce this or similar warnings.

**Comment by laceysanderson** [comment]
Hi @CFGrote, 

It looks like your using the Search API integration described here: https://tripal.readthedocs.io/en/latest/user_guide/searching/search_api.html. Is that correct?

If yes, what search backend/server are you using?

Can you remove the "Indexed Tripal Content: Locus Tag" field from your view, save and check if this removes the errors. I'm wondering if something has changed in the Drupal Search API's expectations for empty values.

**Comment by CFGrote** [comment]
> Hi @CFGrote,
> 
> It looks like your using the Search API integration described here: https://tripal.readthedocs.io/en/latest/user_guide/searching/search_api.html. Is that correct?
That is correct
> 
> If yes, what search backend/server are you using?
Honestly, I'm not entirely sure anymore. I tried and tested so many different config settings, have to dig into my notes and server configuration.
> 
> Can you remove the "Indexed Tripal Content: Locus Tag" field from your view, save and check if this removes the errors. I'm wondering if something has changed in the Drupal Search API's expectations for empty values.

I tried that. The Warnings are still present. Additionally, the search results are now an empty table:
![image](https://user-images.githubusercontent.com/15476807/177365993-932594e2-9d75-4442-85a4-169cf50c02ca.png)

**Comment by laceysanderson** [comment]
Did you remove only the locus tag? Or also the search Excerpt? For each field can you click into the settings and add a label so it's easier to see what's going on?

**Comment by CFGrote** [comment]
I removed only the Locus Tag.
I'm using the default search backend (no solr or elasticsearch)

**Comment by CFGrote** [comment]
I tried reindexing the site but now I always get this:
![image](https://user-images.githubusercontent.com/15476807/177743558-ab1f8554-23af-49f1-9a48-c4b231441d82.png)

I get the feeling my site is severely unstable and I consider rebuilding it from scratch... . Any advise how to avoid running into situations like this again?

**Comment by CFGrote** [comment]
hm, it seems to be indexing now. Quite mysterious...

**Comment by laceysanderson** [comment]
Closing as it mysteriously disappeared 🤷‍♀️
