### ISSUE TITLE
PHP8 error, fetchCol passed a non-integer parameter

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1294]
### Issue description
This is the same issue as 
https://github.com/tripal/tripal_elasticsearch/issues/277
but only shows up under PHP8

Specifically, ```fetchCol()``` accepts an integer parameter, but a string is passed.

Easy fix to line 211 of ```tripal_chado/includes/TripalFields/data__sequence_record/data__sequence_record.inc```

### Error message
TypeError: PDOStatement::fetchAll(): Argument #2 must be of type int, string given in PDOStatement->fetchAll() (line 2310 of .../includes/database/database.inc).

**Comment by dsenalik** [comment]
P.S. I did a ```grep -nr "fetchAll('"``` and ```grep -nr 'fetchAll("'``` and did not find any other occurrences

**Comment by spficklin** [comment]
Fixed with recent PR.
