### ISSUE TITLE
Bug in GFF3 loader related to derives_from

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#1299]
### Issue description
Encountered problem with the TAIR10.
If the feature does not exist in the GFF, the derives_from will break

Chr5	TAIR10	transposable_element_gene	26258459	26259916	.	+	.	ID=AT5G65676;Note=transposable_element_gene;Name=AT5G65676;Derives_from=AT5TE94555

```
GFF import fails
```

@spficklin

**Comment by dsenalik** [comment]
This issue will be fixed by pull request #1305

**Comment by dsenalik** [comment]
Closed with merge of #1305
