### ISSUE TITLE
local__source_data widget not respecting proper field length limits

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1302]
### System information

* Tripal Version: 7.x-3.9
* Drupal Version: 7.92
* PostgreSQL Version: 13.3
* PHP Version: 8.0.23

### Issue description

The widget for the tripal field ```local__source_data``` does not have the correct length limits for the "Data Source Name", "Data Source Version", and "Data Source URI" fields, they are defaulting to drupal defaults which do not match the schema values. Fix this by copying from the table schema, or for the URI field which has no limit, set it to a large value 8192. In Tripal4 this will become a textarea.

#### Steps to reproduce

Try entering a very long URI and observe it being truncated.

**Comment by spficklin** [comment]
Fixed as per PR

**Comment by dsenalik** [comment]
I'm reopening since there is a subsequent pull request on this branch

**Comment by dsenalik** [comment]
This was completed with merged pull #1304
