### ISSUE TITLE
Can't enable 7.x-3.0-rc1

### ISSUE THREAD

**Issue by GreenInnovator** [tripal/tripal#131]
$drush pm-enable tripal
Do you really want to continue? (y/n): y
PHP Fatal error:  Can't use function return value in write context in /var/www/html/sites/all/modules/tripal/tripal/includes/tripal.entity.inc on line 385
Drush command terminated abnormally due to an unrecoverable error.                                                               [error]
Error: Can't use function return value in write context in
/var/www/html/sites/all/modules/tripal/tripal/includes/tripal.entity.inc, line 385

**Comment by laceysanderson** [comment]
This error looks like it's related to the PHP version you are running Drupal/Tripal with. **Tripal requires at least PHP 5.5**. Are you using a lower version of PHP? And if so, does upgrading fix your problem?

**Comment by GreenInnovator** [comment]
$ php -v
PHP 5.6.25 (cli) (built: Oct 21 2016 18:00:07) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
$ sudo drush pm-enable tripal
The following extensions will be enabled: tripal
Do you really want to continue? (y/n): y
PHP Fatal error:  Can't use function return value in write context in /var/www/html/sites/all/modules/tripal/tripal/includes/tripal.entity.inc on line 385
Drush command terminated abnormally due to an unrecoverable error.                                                               [error]
Error: Can't use function return value in write context in
/var/www/html/sites/all/modules/tripal/tripal/includes/tripal.entity.inc, line 385

**Comment by GreenInnovator** [comment]
Sorry,  was to fast with previous response. Used "scl enable rh-php56 bash" there. Stable update to php 7.0 solved the problem.

**Comment by spficklin** [comment]
Marking as closed as it looks like this has been resolved.
