### ISSUE TITLE
Organism image field not returning an array (re: Views)

### ISSUE THREAD

**Issue by marchoeppner** [tripal/tripal#1317]
### System information

* Tripal Version: 3.9
* Drupal Version:
* PostgreSQL Version: 
* PHP Version: 

### Issue description
![tripal_image_Error](https://user-images.githubusercontent.com/22975/200383913-8799970c-5f00-4452-9c2a-f89fb2b012da.png)

I have created a view to list all organisms currently defined on my Tripal page. If I include the image field into the result, I get an error  - see attachment. Apparently this means that the organism image field is not, or does not return, an array, which is why the count fails. 

#### Steps to reproduce

Create one or several organisms, each with an image. Then create a view to list all these organisms as e.g. a table. Enable image as a result item. Error as per attached screenshot.

**Comment by laceysanderson** [comment]
Thanks for the bug report @marchoeppner :-)
For a bit more context, this was originally reported over on slack and here are my comments from over there in case it is helpful to whoever looks into this bug.

> Interesting. Fields in Drupal 7 all store their values as an array which is what this code is counting on. Even fields which only support a single value were always arrays. This error is implying that your organism image field is not an array and thus not countable.
> 
> I would suggest opening a bug report on github (https://github.com/tripal/tripal) so we can get that fixed. It's likely a simple fix of checking if it's an array before using count and then handling the item directly if it's not. I'm focused on Tripal 4 right now but one of the others on the team should see the bug report on github.
>
> If you wanted to take a try at diagnosing this yourself, I would download + install the devel module then then add a `dpm($values);` at the beginning of the render function there to see what it looks like. If I were to hazard a guess I would expect they maybe changed the field to be a single object. Regardless, you would want to look for a fid somewhere which is the file ID. Once you find that you can just set `$fid` appropriately and then rest of the code inside the `if () {}` should work happily again :slightly_smiling_face:

**Comment by dsenalik** [comment]
This is both a PHP 8 problem and a real bug too!
Look at this line and see if you can spot it, I didn't notice right away 🙈
```if (count($value == 1)) {```

The PHP8 part is that count fails on a NULL, or as in this case, a boolean. Everything can be fixed on this one line, see pull #1442 

I did a recursive grep to see if there were any other instances of this type of error, but this was the only one.

**Comment by spficklin** [comment]
This issue should be resolved with the recent fix provided by @dsenalik and committed via PR #1442
