### ISSUE TITLE
Tripal fields don't exist for all of the linker tables, e.g. link analysis and project

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1318]
## Feature Request/Discussion

* This feature does attempt to solve an existing problem with Tripal
* I am open to developing or collaborating on an extension module if this is not a good fit for Tripal Core
* This feature is Not Urgent

### Description
Correct me if I'm wrong, but right now in core tripal, there is not a field to link between project and analysis or even assay. I wrote one for CarrotOmics, but is there a reason this field does not already exist, the table ```project_analysis``` exists, so why not a field for it?

### Your Specific Use Case
Here is an example of linking a project to an analysis and assays
https://www.carrotomics.org/Project/291804
and each of those then has a link back to the project. 

### Generally Applicable
I "overloaded" the field so a project also links to assays for example, and that's why I never finished the widget. Is there a possibility of a more general "linker" field that will just use all linker tables in chado? Sort of like the ```sio__references``` field does for publications? However that field doesn't have a widget so couldn't be used to add links.

### Testing
See https://github.com/tripal/tripal/pull/1319#issuecomment-1329543545

**Comment by spficklin** [comment]
Linking to this discussion about the analysis -> project link:  https://github.com/tripal/tripal/issues/804

**Comment by laceysanderson** [comment]
Yes, I use the project tables A LOT. There are a number of these project-focused linker tables in Chado but not for all my purposes. As such I've created the following additional ones using Tripal Custom Tables: project_feature and project_stockcollection. We group all our data via project although this is usually done via Tripal Data Importers and then used in our custom searches. We don't have a field to display these connections on the page unfortunately as we just didn't get around to it.

For the beautiful generic linker fields we have in Tripal, they generally just don't get created unless someone asks and/or has time to help make the field 🙈 I do not see a reason not to have a such a field though and we would also benefit from it so I'm happy to see / review/ help as I'm able :-) Even if it's just focused on display for now, it would be a great addition to core in my opinion! <3

**Comment by dsenalik** [comment]
Okay, what is the best CV term for the field, then. I used ```local__project_analysis``` for example on CarrotOmics, is that reasonable or is there a better term?

**Comment by laceysanderson** [comment]
For making a generic project linker field we would want to do chado_linker__project to follow convention. Then the term should be generic so [NCIT:C47885 (Project)](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C47885) would be a good candidate.

Here are a couple of examples of these fields in code form:
- [chado_linker__prop](https://github.com/tripal/tripal/tree/7.x-3.x/tripal_chado/includes/TripalFields/chado_linker__prop)
- [chado_linker__contact](https://github.com/tripal/tripal/tree/7.x-3.x/tripal_chado/includes/TripalFields/chado_linker__contact)

Actually, I'm just noticing that sbo__relationship doesn't follow that naming convention. @spficklin do you think this field should be chado_linker__project or ncit__project after the ontology term?

**Comment by spficklin** [comment]
A generic project linker field could be used to link any base table with a project. For the ontology term we could use this: 
[NCIT:C47885 (Project)](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C47885)

Then in the field load function we tweak the loader based on the base table it's linked to.

**Comment by dsenalik** [comment]
Proposal of fields that could be created, I'll edit this with updates
| field links to | proposed cvterm | field name | tripal 3 core linker tables |
| --- | --- | --- | --- |
| analysis | [NCIT:C25391 (Analysis)]( https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C25391)<sup>3,4</sup> | chado_linker__analysis<br>(local__analysis_browser<sup>2</sup>) | analysisfeature<sup>1</sup>, analysis_organism[mview], organism_analysis, project_analysis |
| assay | [NCIT:C60819 (Assay)]( https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C60819)<sup>4</sup> | chado_linker__assay | assay_biomaterial, assay_project, study_assay |
| biomaterial | [NCIT:C43376 (Biologically-Derived Material)]( https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C43376)<sup>4</sup> | chado_linker__biomaterial | assay_biomaterial<sup>7</sup>, biomaterial_project, biomaterial_treatment |
| contact (existing) | local:contact<br>[NCIT:C47594 (Communication Contact)]( https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C47594) | chado_linker__contact | feature_contact, featuremap_contact, library_contact, nd_experiment_contact, project_contact |
| feature | [NCIT:C73619 (Feature)]( https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C73619)<sup>4</sup> | chado_linker__feature | analysisfeature<sup>1</sup>, feature_contact, library_feature, project_feature<sup>5</sup>, stock_feature<sup>6</sup>, +some others? |
| featuremap | EDAM [data:1274 (map)](https://edamontology.github.io/edam-browser/#data_1274) | chado_linker__featuremap | featuremap_contact, featuremap_organism, stock_featuremap |
| organism | [NCIT:C14250 (Organism)]( https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C14250) |chado_linker__organism<br>(obi__organism_linker<sup>2</sup>) |organism_analysis, analysis_organism[mview], featuremap_organism, organism_pub, phylonode_organism |
| project | [NCIT:C47885 (Project)](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C47885) | chado_linker__project | project_analysis, assay_project, project_contact, project_feature<sup>5</sup>, biomaterial_project, project_stock<sup>5</sup> |
| stock | [NCIT:C48288 (Stock)]( https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C48288)<sup>4</sup> | chado_linker__stock | stock_feature<sup>6</sup>, stock_featuremap, stock_genotype, stock_library, project_stock<sup>5</sup>, stockcollection_stock |
| study | [NCIT:C63536 (Study)]( https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C63536) | chado_linker__study | study_assay |

Proposed CV Term for the summary view: [NCIT:C25463 (Count)]( https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C25463)

chado_linker__contact currently uses local:contact but there is [NCIT:C47954 (Communication Contact)](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C47954)

<sup>1</sup>analysisfeature can be used to link every gene in a genome annotation to one analysis, so tens of thousands of links 
<sup>2</sup>Not core, provided by tripal_manage_analyses module
<sup>3</sup>operation__analysis field uses operation:2945 for content types with an analysis_id in the base table
<sup>4</sup>Term does not currently exist in tripal_chado module
<sup>5</sup>mainlab tripal defines stock_project, feature_stock, and feature_project tables, watch out!
<sup>6</sup>chado.stock_feature table has a type_id and rank column
<sup>7</sup>chado.assay_biomaterial table has a channel_id and rank column

**Comment by laceysanderson** [comment]
That sounds awesome @dsenalik! 

I will add the note that we have connections in the millions for single project/analysis and our newest genetic marker set will push us into the billions soon. So I suggest supporting a paged functionality where the field only grabs the first couple of pages and then additional pages are loaded via field-specific webservices. Otherwise KnowPulse will time out ;-p

**Comment by dsenalik** [comment]
To handle cases of large numbers of links, the fields will switch over to a **Summary View** when the total number of records exceeds a limit stored in the variable ```load_limit```, defaulting to 500, _i.e._
```
$load_limit = array_key_exists('load_limit', $this->instance['settings'])
            ? $this->instance['settings']['load_limit'] : 500;
$sql1 = 'SELECT COUNT(*) FROM {'.$linker_table.'} WHERE '.$fkey_lcolumn.' = :analysis_id';
$args1 = [':analysis_id' => $record->$fkey_lcolumn];
$count = chado_query($sql1, $args1)->fetchField();
```

**Comment by dsenalik** [comment]
The majority of the code to implement these new fields will be moved to a new module [chado_linker_fields](https://github.com/tripal/chado_linker_fields)

Some of the code is best kept in core tripal like the api functions for autocompletes.

These changes can be found in pull #1487

The fields themselves, and admin page for setting max_delta will be moved to this new module.

**Comment by dsenalik** [comment]
The new module [chado_linker_fields](https://github.com/tripal/chado_linker_fields) now contains the remaining code from this issue, so closing.
