### ISSUE TITLE
GFF3Importer possible bug when checking for null Pub 

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#1320]
I cannot explain unfortunately how to get this bug to show up since I'm actually testing the T4 version which uses most of the code from T3 but a quick inspection should show the issue

https://github.com/tripal/tripal/blob/48e2affdfc8f267018677b28d095f4da25415f74/tripal_chado/includes/TripalImporter/GFF3Importer.inc#L834

On this line, there seems to be no options/arguments for :name and :type_id so this chado_query function would error out

**Comment by dsenalik** [comment]
That is odd because ```$psql``` is not defined anywhere in that file, and as you note no args are supplied. A fine juicy bug you have found.

**Comment by dsenalik** [comment]
I have a not-yet-merged branch for the GFF3 loader https://github.com/tripal/tripal/pull/1316
Do you want me to add the fix to that?

\* Making this a separate pull request like I should.

**Comment by dsenalik** [comment]
Testing

Before code changes, you can trigger the error by deleting the null publication and then importing a gff3
```delete from chado.pub where uniquename='null';```

then load a one-feature gff3 file to test
```
Opening /var/www/carrotomics/ftpupload/test.gff3
Opening temporary cache file: /tmp/TripalGFF3Import_WSw8Ce
Step  1 of 27: Caching GFF3 file...                             
Removing temporary cache file: /tmp/TripalGFF3Import_WSw8Ce
SQLSTATE[HY000]: General error
[site http://default] [TRIPAL ERROR] [TRIPAL_JOB] SQLSTATE[HY000]: General error
```

After some code changes the import continues fully without errors and the null pub is recreated.

But if the ```null``` cv also does not exist this will fail. I wonder where these are created, it has a cv_id of 1 and cvterm_id of 1 so must be a basic thing done on install? Maybe we don't need the code here to create it, just an error message.

**Comment by dsenalik** [comment]
Today I tested setting up an empty tripal 3 site, and the null pub is installed as I suspected. The version in the GFF3 module is redundant (unless someone manually deleted the null pub thinking it wasn't useful). See pull request #1321 for the changes.

**Comment by laceysanderson** [comment]
Just for a bit of extra information:
The null cv/cvterm/dbxref/contact/pub are all added when chado is installed during the initialization step. You can see everything added in that step here: https://github.com/tripal/tripal/blob/4f19a230b82f8ed3c949349b7ebd1137bdfb74bb/tripal_chado/chado_schema/initialize-1.3.sql

This code was added because it became obvious that people do often accidentally remove the null publication.

**Comment by laceysanderson** [comment]
@risharde, did you fix this is t4d8? the linked PR shows how if you haven't :-)
