### ISSUE TITLE
v3.0-rc1 "Prepare the site" tripal job not executed

### ISSUE THREAD

**Issue by cguttai5k** [tripal/tripal#133]
currently we are using tripal v2.1 & trying to upgrade it to v3.0-rc1 and facing an issue with one of the final step in Step1 from the [documentation](http://tripal.info/tutorials/v3.x/upgrade/2.x-to-3.x).

Modules are updated to v3.0-rc1

![image](https://user-images.githubusercontent.com/24276916/28592806-21d24a0a-7158-11e7-8f8d-22efd8717bc2.png)

![image](https://user-images.githubusercontent.com/24276916/28592596-8c4e62e8-7157-11e7-8a2e-5d7eed8c323f.png)

the next step is to "prepare the site" to add any additional views, vocabularies or custom tables into the chado database and prepare drupal & chado database by running a tripal job. I did run the tripal job by command line yesterday around 03:45 PM but it is still running and not executed till now. 

![image](https://user-images.githubusercontent.com/24276916/28592575-7e0becb4-7157-11e7-8244-0f066e0e5579.png)

any help would be appreciated. Thanks!

**Comment by laceysanderson** [comment]
@cguttai5k could you provide me with the following information:
- the full command used to execute the tripal job on the command-line
- any output from that command so far
- information about your server (e.g. linux distribution, PHP and PostgreSQL versions)

Thanks!

**Comment by cguttai5k** [comment]
Thank you Lacey for following up this issue, now i'm able to execute the command when i reinstalled the whole setup again & to answer your question here are the details:

- drush trp-run-jobs --username=administrator --root=(Drupalbase path)
- php - 5.6.31
- psql - 9.3.17
- redhat

After tripal job is successful here is the display db error i received:

![image](https://user-images.githubusercontent.com/24276916/28672705-79e5187e-72ae-11e7-8629-8d12af4b6765.png)

I tried to visit the list of chado organism pages on our site but it is not rendering & getting an error like this on drupal "recent log messages":

`chado_select_record: the foreign key definition for 'type_id' on table 'feature' returned no results where the definition supplied was Array ( [name] => Array ( [0] => ) )`

FYI, I still didn't migrated the content types from v2.x to v3.x . Thanks!

**Comment by laceysanderson** [comment]
### Focusing on the first error (during site preparation):
This error is confusing as the insertion of that cvterm is set to update an existing term if present. 

Can you look at the controlled vocabularies in your live Tripal 2.1 site (pre-upgrade) for me. Either go to Tripal > Chado Modules > Controlled Vocabularies > Terms and enter "Analysis Type" into the "Name Contains" filter. What is the Vocabulary, DB and Accession (you can see the last two by clicking on edit beside the term) for the "Analysis Type" term?

**Comment by cguttai5k** [comment]
Lacey, actually live site is running on tripal v2.0 it has:

- Vocabulary - analysis_property
- Database - Tripal
- Accession - Analysis Type

But dev & stage environments are upgraded to v2.1 which is not pushed to prod yet, I checked the controlled vocabularies on stg but it seems like there are no terms associated with this selected vocabulary.

**Comment by laceysanderson** [comment]
Hmm... So just to clarify: 
- the database dump you are using for the upgrade process as your starting point is your current staging site?
- the staging site doesn't have any terms associated with the analysis_property vocabulary?
- does the staging site have an "Analysis Type" term in general (associated with a different vocabulary or dbxref)?

**Comment by cguttai5k** [comment]
I pulled all the code, db from prod base & after that I upgraded tripal v2.0 to v2.1 on dev site, In this process of upgradation, I also applied "drush updatedb" cmd as per the documentation which results in the below image:

![db_update1](https://user-images.githubusercontent.com/24276916/28942371-21faab9a-7869-11e7-9d48-e579dd1c400a.PNG)
![image](https://user-images.githubusercontent.com/24276916/28975963-09ddaa34-790a-11e7-8dcd-ec0968e463b0.png)


After this I tested all the functionality and pushed to stage (smells like there are no terms associated with "**analysis_property**" or "**Analysis Type**" after upgrading the site from v2.0 to 2.1 ) 

Now I'm working on upgrading tripal v2.1 to v.3.0-rc1 on dev site but leads to errors which I mentioned earlier. Although I'll post it again:

![image](https://user-images.githubusercontent.com/24276916/28943290-3b880500-786c-11e7-9437-fd285d58aefb.png)
![analysis type](https://user-images.githubusercontent.com/24276916/28942642-2986d644-786a-11e7-94a2-82df65274a8d.PNG)

when I tried to open organism pages here is the "recent log message" on dev site :

`chado_select_record: the foreign key definition for 'type_id' on table 'feature' returned no results where the definition supplied was Array ( [name] => Array ( [0] => ) )`

Thanks!

**Comment by laceysanderson** [comment]
@cguttai5k sorry for the delay on this -I've just gone on maternity leave. @spficklin could you help? The Prepare Chado code is failing on ensuring the "Analysis Type" term is there. The check determines the term is not there but then insert fails due to duplicate term... I wonder if it's not related to this bug: https://github.com/tripal/tripal/issues/136#issuecomment-318715792

**Comment by cguttai5k** [comment]
Congratulations Lacey!! no worries, I actually was able to fix that "**Analysis_type**" or "**analysis_property**" term issue by replacing some of the deprecated functions which I missed earlier to update on our custom modules. 

now the only issue was with recent log messages :

`chado_select_record: the foreign key definition for 'type_id' on table 'feature' returned no results where the definition supplied was Array ( [name] => Array ( [0] => ) )`

any ideas or suggestions? Thanks!

**Comment by spficklin** [comment]
Hi @cguttai5k I'm sorry you're having issues with the upgrade.   Does the most recent error message you list above occur during the prepare chado phase?  If so can you cut-and-paste any surrounding messages.

**Comment by cguttai5k** [comment]
Thanks for looking into this @spficklin. issue had been resolved when i tried reinstalling it.

**Comment by spficklin** [comment]
Okay. Great. Thanks for letting us know.  I suspect there may be some residual problem with upgrading that is causing this.   But, I'm glad you got it.
