### ISSUE TITLE
HTML5 File Upload: issues trying to re-upload files

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#1339]
Referenced here: https://github.com/tripal/t4d8/issues/139#issuecomment-957960963

The temp folder with the file chunks were not being deleted. This somehow affected when trying to reupload the file. The problem seems to resolve by deleted the attempted reconstituted file and / or emptying the temp folder.

**Comment by risharde** [comment]
Permissions and perhaps a further inspection of this code might be required.

**Comment by risharde** [comment]
P.S Cache clear did not work during trying to resolve this issue (it was unrelated to the problem)

**Comment by laceysanderson** [comment]
Tried again with the most recent Tripal and was not able to replicate. Please comment and attach a file causing the problem, if you come across this error in your system.
