### ISSUE TITLE
Error when trying to drop default chado schema

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#1344]
I discovered this possible bug after an attempt to drop chado schema 'chado (default schema)' from the following screen:
![image](https://user-images.githubusercontent.com/33866403/173460920-6513ac3a-fda2-40d4-b918-c2f0f2cd0ff9.png)

The error causes the WSOD (white screen of death with the following message)
![image](https://user-images.githubusercontent.com/33866403/173461049-a6d0197e-00e4-483d-8feb-075187df8f5e.png)

The error in the log is:
![image](https://user-images.githubusercontent.com/33866403/173461142-6b62172b-9e3c-46b1-8c41-2957b5b45a28.png)

I'm tagging maybe @guignonv to see whether he can reproduce the error and resolve.

I am assuming this is using biodb from core since my branch is from core 9.x-4.x branch

**Comment by risharde** [comment]
Confirming that even when manually deleting the chado schema, reinstalling the chado schema and going back to try to drop it shows the same error.

I also updated my branch with the latest 9.x-4.x and cleared cache and it shows the same error.

**Comment by spficklin** [comment]
@Ferrisx4 ran a test with the current Drupal 10.2 and couldn't reproduce.  @risharde if you still have this issue let us know and we can reopen.
