### ISSUE TITLE
FASTAImporter

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1346]
This issue is for tracking progress on the FASTA Importer. It should be implemented on the code that is part of PR https://github.com/tripal/t4d8/pull/230

**Comment by spficklin** [comment]
Please use branch tv4g4-232-FASTAImporter for this work. I've copied in the FASTAImporter code as it was when @risharde left off with it.

**Comment by laceysanderson** [comment]
A lot of work has been done on this importer already by @risharde.

The original version that @spficklin mentioned in the above comment can be found in this file: 
[FASTAImporter.php.txt](https://github.com/tripal/tripal/files/10178827/FASTAImporter.php.txt)

The most recent version was in @risharde branch `tv4g4-232-FASTAImporter-new` in the t4d8 repository and has been moved to `tv4g4-1346-FASTAImporter` in this repository.

You can see the most recent review from the work in this branch here: https://github.com/tripal/t4d8/pull/288

**Comment by laceysanderson** [comment]
Closing as the FASTA importer was merged
