### ISSUE TITLE
TaxonomyImporter

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1347]
This issue is for tracking progress on the TaxonomyImporter. It should be implemented on the code that is part of PR https://github.com/tripal/t4d8/pull/230

**Comment by spficklin** [comment]
Please use branch `tv4g4-233-TaxonomyImporter` for this work. I've copied in the TaxonomyImporter code as it was when @risharde left off with it.

**Comment by laceysanderson** [comment]
Here is the current progress that @spficklin mentioned above:
[TaxonomyImporter.php.txt](https://github.com/tripal/tripal/files/10178957/TaxonomyImporter.php.txt)

**Comment by laceysanderson** [comment]
Closing as there is a taxonomy importer in core. Instead open specific issues with this importer for further development.
