### ISSUE TITLE
NewickImporter

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1348]
This issue is for tracking progress on the NewickImporter. It should be implemented on the code that is part of PR https://github.com/tripal/t4d8/pull/230

**Comment by spficklin** [comment]
Please use branch `tv4g4-234-NewickImporter` for this work. I've copied in the NewickImporter code as it was when @risharde left off with it.

**Comment by laceysanderson** [comment]
Here is the current progress that @spficklin mentioned above:
[NewickImporter.php.txt](https://github.com/tripal/tripal/files/10178974/NewickImporter.php.txt)

We will also want to look at the improvements by @dsenalik in PR #1262

**Comment by laceysanderson** [comment]
Closing as there is a newick importer in core. Instead open specific issues with this importer for further development.
