### ISSUE TITLE
PubBulkImporter

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1349]
This issue is for tracking progress on the PubBulkImporter. It should be implemented on the code that is part of PR https://github.com/tripal/t4d8/pull/230

**Comment by spficklin** [comment]
Please use branch `tv4g4-235-PubBulkImporter` for this work. I've copied in the PubBulkImporter code as it was when @risharde left off with it.

**Comment by laceysanderson** [comment]
Here is the current progress that @spficklin mentioned above:
[PubBulkImporter.php.txt](https://github.com/tripal/tripal/files/10178986/PubBulkImporter.php.txt)

**Comment by laceysanderson** [comment]
Closing this as much work has been done on the importer making this obsolete.
