### ISSUE TITLE
Organism nomenclature in GFF3/FASTA loaders

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1356]
This is just a note to make sure we bring in the recent fix by @dsenalik in Tv3 into Tv4.  @risharde this affects the GFF3 loader and FASTA loader once we get that going.

**Comment by spficklin** [comment]
https://github.com/tripal/tripal/issues/1300

**Comment by laceysanderson** [comment]
I believe this is done as the importers now show organisms with their infraspecific nomenclature
