### ISSUE TITLE
Error Occurs When Adding a New ChadoField

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#136]
It appears that inserting a new cvterm as part of hook_instance_bundle_fields_info() issues the error below.

```
Notice: Undefined variable: dbxref in tripal_insert_cvterm() (line 1254 of /home/vagrant/sites/HWG/sites/all/modules/tripal/tripal_chado/api/modules/tripal_chado.cv.api.inc).
Notice: Trying to get property of non-object in tripal_insert_cvterm() (line 1254 of /home/vagrant/sites/HWG/sites/all/modules/tripal/tripal_chado/api/modules/tripal_chado.cv.api.inc).
```

Here is the function call:
```php
tripal_insert_cvterm([
      'id' => 'local:jbrowse_instance',
      'name' => 'jbrowse_instance',
      'cv_name' => 'jbrowse',
      'definition' => 'Provides a JBrowse link',
]);
```

Thanks!

**Comment by laceysanderson** [comment]
Interesting. It looks like you caught a weird edge case where checking the cvterm name and cv says the term doesn't exist but checking using the dbxref says the term does exist. Thanks for pointing out the bug :-)

Note to self for fixing this one: We need to select the dbxref on tripal/tripal_chado/api/modules/tripal_chado.cv.api.inc line 1230 to ensure it is available in this edge case.

On an unrelated note, why are you creating the cvterm for your new Chado Field in hook_instance_bundle_fields_info()? It should have been created in hook_bundle_fields_info() when you first introduced you field (see https://github.com/tripal/tripal_example/blob/7.x-3.x/trpexp_fields/includes/trpexp_fields.fields.inc#L46).

**Comment by almasaeed2010** [comment]
Oh my bad, the name of the module is `tripal_jbrowse_instance` and I copied `instance` with it by mistake. I am actually using `hook_bundle_fields_info()`.

Thanks!

**Comment by almasaeed2010** [comment]
Here is a link to the module in case it could help : https://github.com/statonlab/tripal_jbrowse_instance

(it doesn't currently do anything other than create the field)

**Comment by almasaeed2010** [comment]
This apparently has been fixed since I am using the same function in multiple different instances (including the term mentioned here) without any issues.
