### ISSUE TITLE
Migration of tripal 2 to 3 type: table of content

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#137]
After migration, we're looking for what happens to additional content we've added to our organism nodes (manually).  This content is of the Tripal type Table of Content, so we're hoping it is ( will be ?) migrated.  Our new 3.0 nodes don't have this content.  Please see for example [the predicted SSR pane of this organism.](http://160.36.205.61:9090/organism/Persea/borbonia?pane=tripal_organism_pane_0) 

Thank you!

Bradford

**Comment by laceysanderson** [comment]
@bradfordcondon, unfortunately I don't know the answer to this one. I've tagged @spficklin and @chunhuaicheng since they worked more on the upgrade path and should have more insight. FYI. there might be a bit of a lag in response as @spficklin is just coming back from a month off ;-)

**Comment by chunhuaicheng** [comment]
Yes, Tripal v3 migration will also migrate those additional resource content. Can you go 'Structure » Tripal Content Types » manage fields (Organism)' and see if a new field was created with the machine name 'bio_data_1_rsc_<your_ssr_pane>'?

**Comment by bradfordcondon** [comment]
I don't believe so.  Below are my available fields for organism.  There's no sign of the ssr pane here or on the organism page. 

![screen shot 2017-07-29 at 4 54 44 pm](https://user-images.githubusercontent.com/7063154/28748164-b60ca732-747e-11e7-9258-6097e97e8ff4.png)



I see I'm able to add fields such as tripal_ssr_motify but those fields are blank when added.  No options with biodata...

**Comment by spficklin** [comment]
Hi @bradfordcondon how did you add the data to your organism pages?  Did you use the supported method described in the User's Guide: http://tripal.info/node/290?  If so, then @chunhuaicheng is correct that those should be migrated automatically. If you used a different approach then they probably won't be migrated, @chunhuaicheng, can you confirm?  If you used the documented approach and it didn't migrate them then perhaps we have an issue.

**Comment by bradfordcondon** [comment]
@almasaeed2010 @MingChen0919 Can you help answer?

**Comment by almasaeed2010** [comment]
They are added using the the extra panes form on the node's edit page as shown below:

<img width="1252" alt="screen shot 2017-07-30 at 6 46 47 pm" src="https://user-images.githubusercontent.com/1512664/28757742-870f4262-7557-11e7-833a-609a459a9992.png">

**Comment by spficklin** [comment]
Can you take a screenshot of the Node admin page at Structure > Content Types  and click the 'manage fields' link.  I'd like to see the naming of the fields.

**Comment by chunhuaicheng** [comment]
Yes, Stephen. The migration code will try to migrate 'resource_titles',
'resource_blocks', and 'resource_links' fields if they were found in the
process. If the fields were named otherwise, they won't be migrated.

Chun-Huai

**Comment by almasaeed2010** [comment]
Structure > Content Types > Organism > Manage Fields

![download](https://user-images.githubusercontent.com/1512664/28782865-80e5ddda-75dc-11e7-95f0-a2376d73cff8.png)

**Comment by spficklin** [comment]
So it looks like the naming of these fields is different from what is expected which explains why they aren't migrated.  How much time would it take you to manually move this content?

**Comment by bradfordcondon** [comment]
So the machine name of the would want to be `field_extra_pane_blocks` instead of `field_extra_pane_content` ?  I'm assuming just renaming the table wouldn't work... sounds like the easiest way would be to manually migrate.

**Comment by chunhuaicheng** [comment]
Actually, the only machine names that would work are
'field_resource_titles', 'field_resource_blocks', and
'field_resource_links', as Stephen mentioned in the online document
http://tripal.info/node/290

**Comment by spficklin** [comment]
I'm closing this as there's not been any further comment.  But please reopen if it still needs attention.
