### ISSUE TITLE
How to Attach to Table of Contents

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#138]
Hello,

Is it possible to attach to the table of contents in Tripal v3? If so, any direction would be appreciated.

We are trying to develop a new field and would like the content to be visible in a Tripal Pane.

Thanks!

**Comment by laceysanderson** [comment]
Yes, it's not only possible but is also more flexible than in Tripal 2.x. 

## From a system administrators perspective:
To add to the Tripal Table of Contents, go to Structure > Tripal Content Types > [Content Type of interest] > Manage Display then click on "Create an empty Tripal Pane". The label you give the Tripal Pane is what will be displayed in the Tripal Table of Contents and any fields you nest within it will be shown when the user selects that pane. Furthermore, the order of links in the Table of Contents directly reflects the order of Tripal Panes in the Manage Display interface.

## From a module developers perspective:
@shawnawsu did we end up creating an api function so module developers can create a Tripal Pane programatically and add their custom field to it?

**Comment by shawnawsu** [comment]
That API has been started but it's not finished. I've got it on the radar for the next release.

**Comment by laceysanderson** [comment]
Switching this to a release blocker so we remember to add the API to do this programatically. In the meantime does the UI solution meet your needs @almasaeed2010?

**Comment by almasaeed2010** [comment]
Stephen clarified to me that auto attaching the field to a tripal pane programmatically is only useful  if the user has Tripal DS enabled and therefore we have to account for users who don't have that enabled anyway. For now, we can develop our modules and attach the new fields to panes using the GUI.

Thank you all for the help!

**Comment by spficklin** [comment]
Marking as closed...
