### ISSUE TITLE
GFF3Importer Unit Tests

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#1386]
The GFF3 importer still needs automated testing. This issue acts as a reminder of that.

**Comment by laceysanderson** [comment]
This work was started by @risharde in the tripal/t4d8 repository.

I have moved the existing work from there to this repository as we are switching back to our main repo now. The name changes of branches is shown below:

- `t4d8/tv4g4-277-GFF3ImporterUnitTests` to `tv4g4-issue1386-GFF3ImporterUnitTests`
- `t4d8/tv4g4-277-GFF3ImporterUnitTestsV2` to `tv4g4-issue1386-GFF3ImporterUnitTestsV2`

The plan is to do any new development here. That said, the old repo will be kept open for the next couple of weeks to collect any local changes which may not have been pushed. @risharde please push any such changes to the t4d8 repo and let me know as soon as you get a chance :-)

**Comment by laceysanderson** [comment]
Closing as this PR was merged
