### ISSUE TITLE
Validation error when leaving optional fields empty

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#1387]
When I create a gene through the UI, I get an error indicating that the sequence length is not of the correct primitive type when I leave it empty and try to save. The validation error is "This value should be of the correct primitive type. " with the "Sequence Length" field highlighted in red. Since this field is not required, I should be able to leave it empty without a validation error. 

## Steps to recreate

1. Spin up a new Tripal site.
2. Create an organism through the UI (i.e. Go to Tripal > Content > Organism)
3. Create a  Gene through the UI (i.e. Go to Tripal > Content > Gene) leaving the "Sequence Length" field at the bottom of the page empty.
4. Note the validation error that occurs preventing save.
5. Enter a number of any type in the "Sequence Length" field and save.
6. Note that if the sequence length is filled in then the gene is saved as expected.

**Comment by spficklin** [comment]
The fix for this should be in PR #1419

**Comment by laceysanderson** [comment]
Updated fix in #1650 for the sequence length field specifically. That said, it would be good to ensure that no-required, integer type fields can be left empty and not throw validation errors ;-)

**Comment by spficklin** [comment]
I just tested this on PR #1729 and this problem is no longer present.  I don't think we have any more fields in core Tripal that have a property with an integer type that isn't required.  I think we'll hit on some as we go along, but I don't think we need to keep this open for now.  But reopen if you disagree.

**Comment by dsenalik** [comment]
I would like to reopen this because we will have a number of optional integer fields on the ArrayDesign content type
![20240109_arraydesign](https://github.com/tripal/tripal/assets/8419404/643bfe94-0008-4fdd-b8c3-3b9ec9f78708)

**Comment by dsenalik** [comment]
Because, as Stephen said, there are no optional integer fields currently, I will fix this in #1704 because there we have the ArrayDesign fields added and we can then easily test.

Commit https://github.com/tripal/tripal/pull/1704/commits/8e8ef9dd645a92a58f9d933844d2a39b101c1164
