### ISSUE TITLE
Creation of content types & fields with YML

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1393]
### Description

This issue is for the task of moving the ability to create content types and field out of the Chado prepare step and into YML files. This will make it easier for module developers to create new content types and attach fields to them without having to write code to automate the process.

As a side fix, as discussed in the codefest, we want to rename the fields to use CamelCase rather than the current naming system. There is no need, as there was in Tripal 3, for field names to have the CVterm identifier in the name.    I might as well fix this while I'm doing the YML infrastructure.

I'll use this issue to track both of these.

**Comment by spficklin** [comment]
As per our discussion today we are going to add these considerations to this design:

- update fields to include Chado schema
- move content types and fields out of the prepare step and into install 
- Services that create content types and add fields should be called in the hook_install of the module creating those.
- Separate current content type YML into two separate YML files: one for content types and one for fields so they can be created independently (e.g. some modules will only add fields to existing content types).

**Comment by laceysanderson** [comment]
Competed and finally merged! 🎉 Thank you for all your work on this @spficklin
