### ISSUE TITLE
Tripal Extensions menu page 

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal#1397]
## Feature Request/Discussion

* This feature does attempt to solve an existing problem with Tripal
* This feature is semi-urgent

### Description
With the first Alpha release in the wild, groups will be starting to create and/or upgrade their extension modules to work with Tripal 4. Currently, the administrative page for Extension modules says "Not yet upgraded".

Changing the controller for this path (`admin/tripal/extension`) from
```php
    _controller: '\Drupal\tripal\Controller\TripalController::tripalExtensions'
```
to
```php
    _controller: '\Drupal\system\Controller\SystemController::systemAdminMenuBlockPage'
```
lets Drupal's menu system assume responsibility for collecting any Tripal extension modules that are enabled and have admin-style menu links.

This change will follow the paradigm from Tripal 3 of having a single admin menu for Tripal Extensions that extension modules could tap into. This is preferable so that all Tripal Extension modules' config pages appear in one unified place.

### Question
Was there a reason to have the controller be handled by Tripal or should we let Drupal handle it?

### Documentation
If this change is approved, we would also update the documentation to describe how to get a link on this page for your own Tripal extension module. This could include an example such as
```php
# Tripal Sequence Similarity Search - Tripal Extensions link
tripal_seq.config:
  route_name: tripal_seq.config
  title: 'Tripal Sequence Similarity Search'
  description: 'Configure Tripal Sequence Similarity Search'
  parent: tripal.extension
  weight: 30
```

### Extras
Optionally, we could encourage the use of the Tripal Extension menu by having it as one of the requirements on the Tripal Rating system.

**Comment by Ferrisx4** [comment]
I am investigating to see if it possible to have a better message for when there are no Tripal Extension modules installed with this change in place. If none are installed, the site unhelpfully reports that "You have no administrative items".

**Comment by laceysanderson** [comment]
Yes! I'd forgotten about this -good catch Sean!

> Was there a reason to have the controller be handled by Tripal or should we let Drupal handle it?

No, the plan was to have Drupal handle it. This message was added universally to all admin pages when the routing was upgrading without specific thoughts for how that page would be implemented in the future :-) 

> I am investigating to see if it possible to have a better message for when there are no Tripal Extension modules installed with this change in place. If none are installed, the site unhelpfully reports that "You have no administrative items".

Yes, it would be helpful to have a better message here 🤔 But if Drupal won't let us, it's not the end of the world. Especially with the new movement of genomic functionality to an extension module, most sites will have ones installed so it will be a very short time this is empty.
