### ISSUE TITLE
Terms without Chado

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1400]
We will be moving the creation of content types and fields into YML files as mentioned in issue #1393 .  But this means that if an extension modules tries to install content types without the tripal_chado module being enabled there won't be a place to store terms because currently the only backend we support is Chado, although, the IDSpace Vocabulary and Terms class support other backends.  

The goal is to allow modules to use Tripal services in their `hook_install` functions to create the content types, etc. needed but we nee this issue fixed before that can happen.

**Comment by laceysanderson** [comment]
Fixed by merged PR
