### ISSUE TITLE
tv3g4 chado bulk loader templates in random order

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1406]
# BUG/ERROR report

## System information
* Tripal Version: 3.9dev
* Drupal Version: 7.94
* PostgreSQL Version: 13.3
* PHP Version: 8.0.27

### Issue description
This not so much a bug as an annoying user interface issue. On the chado bulk loader job creation page
/node/add/tripal-bulk-loader
the templates are presented in random order. It would be quite pleasant to have them in sorted order.

**Comment by spficklin** [comment]
Fixed with PR #1407 Thanks for the issue and the fix @dsenalik
