### ISSUE TITLE
tv3g4 PHP8 errors in publication api

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1411]
# BUG/ERROR report

## System information

* Tripal Version: 3.9dev
* Drupal Version: 7.94
* PostgreSQL Version: 13.3
* PHP Version: 8.0.27

### Issue description
More issues with PHP8, this time related to loading publications. The error shows up when my module tries to use the ```chado_pub_create_citation()``` api function, so for demonstration and testing let's call that from the devel module php window.

```
$pub_id = 6;  // Make sure this pub_id exists otherwise you get other errors

// need to include function tripal_pub_get_publication_array()
$tripal_chado_module_path = DRUPAL_ROOT . '/' . drupal_get_path('module', 'tripal_chado');
require_once($tripal_chado_module_path . '/includes/loaders/tripal_chado.pub_importers.inc');

$pub_arr = tripal_pub_get_publication_array($pub_id, FALSE);
if ($pub_arr) {  // actually you will always get something here, even if pub_id does not exist
  $citation = chado_pub_create_citation($pub_arr);
  print "Success, returned citation = \"$citation\"\n";
}
else {
  print "Fail, no pub_arr\n";
}
```

Currently under php8 this fails, and you will see this in the site log:
```TypeError: count(): Argument #1 ($value) must be of type Countable|array, stdClass given in tripal_pub_get_publication_array() (line 1548 of .../sites/all/modules/tripal/tripal_chado/includes/loaders/tripal_chado.pub_importers.inc).```
and this in the apache log:
```[TRIPAL ERROR] [TRIPAL_CHADO] Missing $object argument to the chado_expand_var function from tripal_pub_get_publication_array (line: 1586), referer: https://test.carrotomics.org/devel/php```

**Comment by spficklin** [comment]
This should be fixed with PR #1412
