### ISSUE TITLE
Chado GFF3 File Loader uploads GFF3 data without identifying chromosome ID.

### ISSUE THREAD

**Issue by cxvxc** [tripal/tripal#1416]
My level is very low. How to solve the following problem?

[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] chado_select_record: the foreign key definition for 'type_id' on table 'feature' returned no results where the definition supplied was Array(    [name] => Superscaffold)
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] chado_select_record: the foreign key definition for 'type_id' on table 'feature' returned no results where the definition supplied was Array(    [name] => Superscaffold)
The landmark '<em class="placeholder">Superscaffold1</em>' cannot be found for this organism (<em class="placeholder">Prunus dulcis</em>) Please add the landmark and then retry the import of this GFF3 file
[site http://default] [TRIPAL ERROR] [TRIPAL_JOB] The landmark '<em class="placeholder">Superscaffold1</em>' cannot be found for this organism (<em class="placeholder">Prunus dulcis</em>) Please add the landmark and then retry the import of this GFF3 file

**Comment by laceysanderson** [comment]
Hi @cxvxc, these errors are saying that Tripal cannot find the `Superscaffold` controlled vocabulary term. 

Note: the search is case sensitive and I believe the term would be lowercase based on http://sequenceontology.org/browser/current_svn/term/SO:0000719. I would try entering the landmark as `ultracontig` since that is the term that `superscaffold` is a synonym of.

**Comment by dsenalik** [comment]
I am not 100% sure this is your problem, but I think you need to add a controlled vocabulary term for "Superscaffold" to your local site ontology. To do this, go to this address on your site

```/admin/tripal/loaders/chado_vocabs/chado_cvterms```

then click on "+ Add Term"

"Controlled Vocabulary (Ontology) Name *" select "```local```"

"Term Name *" enter "```Superscaffold```"

"Database *" enter "```local```"

"Accession *" enter "```Superscaffold```"

Click the "Add Term" button

**Comment by dsenalik** [comment]
What @laceysanderson suggested is better because then you use a standard ontology term instead of one you create 🤔

**Comment by cxvxc** [comment]
> Hi @cxvxc, these errors are saying that Tripal cannot find the `Superscaffold` controlled vocabulary term.
> 
> Note: the search is case sensitive and I believe the term would be lowercase based on http://sequenceontology.org/browser/current_svn/term/SO:0000719. I would try entering the landmark as `ultracontig` since that is the term that `superscaffold` is a synonym of.


Thank you very much for your help. I still report the same mistake according to your method. What is the name of my GFF3 chromosome ID Tripal can identify.

**Comment by cxvxc** [comment]
> I am not 100% sure this is your problem, but I think you need to add a controlled vocabulary term for "Superscaffold" to your local site ontology. To do this, go to this address on your site
> 
> `/admin/tripal/loaders/chado_vocabs/chado_cvterms`
> 
> then click on "+ Add Term"
> 
> "Controlled Vocabulary (Ontology) Name *" select "`local`"
> 
> "Term Name *" enter "`Superscaffold`"
> 
> "Database *" enter "`local`"
> 
> "Accession *" enter "`Superscaffold`"
> 
> Click the "Add Term" button

Thank you very much for your help. I still report the same mistake according to your method.

**Comment by cxvxc** [comment]
> 

Thank you very much. What format of chromosome ID does Tripal recognize?

**Comment by dsenalik** [comment]
Can you share the first few lines of your gff3 file?

**Comment by dsenalik** [comment]
Also, I would like to confirm that you first loaded the fasta file. The recommended procedure is to load the fasta file for the sequence that the gff3 file is using as a reference, and when doing this for the box "Sequence Type *" you will enter "ultracontig" for example.
Later when you load the gff3 file, the landmarks should exist from being loaded in the fasta file, and for the "Landmark Type" in this loader, select "ultracontig" again.

**Comment by dsenalik** [comment]
[20230209test.gff3.txt](https://github.com/tripal/tripal/files/10698527/20230209test.gff3.txt)
I made a small test file, and loaded it using "ultracontig" and it worked, even without first loading a fasta file. If you can share part of your gff3 file that would help figuring out the problem.

**Comment by cxvxc** [comment]
> Can you share the first few lines of your gff3 file?



> [20230209test.gff3.txt](https://github.com/tripal/tripal/files/10698527/20230209test.gff3.txt) I made a small test file, and loaded it using "ultracontig" and it worked, even without first loading a fasta file. If you can share part of your gff3 file that would help figuring out the problem.

Thank you very much for your help. According to your prompt, I uploaded chromosome data, and then uploaded GFF3, and succeeded.

**Comment by cxvxc** [comment]
> 



> Also, I would like to confirm that you first loaded the fasta file. The recommended procedure is to load the fasta file for the sequence that the gff3 file is using as a reference, and when doing this for the box "Sequence Type *" you will enter "ultracontig" for example. Later when you load the gff3 file, the landmarks should exist from being loaded in the fasta file, and for the "Landmark Type" in this loader, select "ultracontig" again.

Thank you very much for your answer. The data was uploaded successfully according to your method.

**Comment by dsenalik** [comment]
Since this seems to be resolved, I will close this issue. Please reopen it if you have further problems.
