### ISSUE TITLE
Taxonomy Importer Node Issue

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#142]
When importing a large number of species the following error was observed:

> 130234	Picea maximowiczii var. senanensis
> 130227	Picea maximowiczii
> 39833	Picea mexicana 
> 308685	Picea meyeri var. meyeri
> tripal_chado_ncbi_taxonomy_import(): Node no longer exists tripal_chado.taxonomy_importer.inc:208                                                                              [warning]

The word "node" is related to the XML parser, not a Drupal node and it probably doesn't affect import, but it's annoying and causes concern. It should be looked at.

**Comment by spficklin** [comment]
This is such low hanging fruit I think we can fix for 3.2 release.

**Comment by laceysanderson** [comment]
I'm closing this as there has been no movement on it for over 2 years and there is not actually something broken -just a message causing concern. Please reopen @spficklin if you would still like to work on it.
