### ISSUE TITLE
Docker is not being automatically built since we moved back to this repo.

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#1420]
# Core Tripal 4 Development Task

## Branch Name: tv4g0-issue1420-fixDockerBuild

As mentioned in the title, our docker is no longer being automatically built when we merge to 4.x. This is due to the name change of the branch and may be affecting other workflows.

Also, we will want to add more docker tags to help extension modules develop good testing grids.

**Comment by spficklin** [comment]
Fixed with PR #1427
