### ISSUE TITLE
tv3g4 fix publish update progress

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1422]
# BUG/ERROR report

## System information
* Tripal Version: 7.9
* Drupal Version: 7.94
* PostgreSQL Version: 13.3
* PHP Version: 8.0.27

### Issue description
When publishing more than 100 entities, the progress is not updating correctly.

#### Steps to reproduce
Load a whole genome gff3 file with thousands of genes, and then publish mRNA for example
 
#### Error messages and screenshots
```
Percent complete: 0%. Memory: 54,711,184 bytes.
Percent complete: 1%. Memory: 55,774,848 bytes. Duration: 0.20 mins
```
and then no further updates

**Comment by laceysanderson** [comment]
Fixed in merged PR. Thanks @dsenalik 🎉
