### ISSUE TITLE
tv3g9 Error in every automated test run

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1428]
# BUG/ERROR report

### Issue description
If you look at **any** test run for tripal 3, both successful or failed, you will see in there somewhere:
```[site http://127.0.0.1] [TRIPAL ERROR] [TRIPAL_CHADO] Missing $object argument to the chado_expand_var function from tripal_chado_field_storage_load (line: 426)```

This line is inside ```function tripal_chado_field_storage_load()```
The line referenced looks like 
```$record = chado_expand_var($record, 'field', "$field_table.$field_column");```
and when the error occurs, ```$record``` is NULL 🙈 field_name="schema__description" ```$field_table```="organism" ```$field_column```="comment"

The test where this is generated is ```testPermissionsForUser()``` in file ```tests/tripal/entities/PermissionsTest.php``` and it occurs at this line ```$entity_load = entity_load('TripalEntity', [$entity_id]);```

I don't see anything wrong with the test, and even if I add a comment to the mock data the error persists.
In ```function tripal_chado_field_storage_load()``` in one place there is a check for a NULL ```$record```, and if we do a similar check at line 425 our error will go away.

I don't see any problem fixing it this way, since if ```$record``` is NULL, we are not saving any values anyway.

**Comment by laceysanderson** [comment]
Fixed in merged PR. Thanks @dsenalik 🎉
