### ISSUE TITLE
tv4g4 OBO importer validation error

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1444]
# BUG/ERROR report

### Issue description
This issue is to port the bugfix from pull #1443 to the tripal 4 version. But there may be additional validation problems...

#### Steps to reproduce

Tripal -> Data Loaders -> OBO Vocabulary Loader
Select "The Sequence Ontology"
Make both "Remote URL" and "Local File" blank
Click "Update Ontology Details" button
There should be a validation error, but the blank values are saved.
Now put ```xxx``` for "Local File" and click "Update Ontology Details" button
There should be a validation error that the file does not exist, but again it is accepted.

**Comment by dsenalik** [comment]
Also this is in the log
```Deprecated function: trim(): Passing null to parameter #1 ($string) of type string is deprecated in Drupal\tripal_chado\Plugin\TripalImporter\OBOImporter->formValidate() (line 482 of /var/www/drupal9/web/modules/contrib/tripal/tripal_chado/src/Plugin/TripalImporter/OBOImporter.php) ```
~we can copy the ```array_key_exists``` version from tripal 3 to fix this.~
Let's fix this with the null coalescing operator

**Comment by laceysanderson** [comment]
Fixed by merged PR -thanks @dsenalik 🎉
