### ISSUE TITLE
Unable to run Tripal 3 jobs daemon (error in archived PHP-Daemon)

### ISSUE THREAD

**Issue by btski** [tripal/tripal#1445]
# BUG/ERROR report

### Tripal Version: 7.x-3.9
* Drupal Version: 7.94
* PostgreSQL Version: 14.7 (Ubuntu 14.7-0ubuntu0.22.04.1)
* PHP Version: 8.1.2-1ubuntu2.11

## Issue description and error message

I've been running into issues trying to setup a new (updated) Tripal 3 server. Main goal is to update to highest versions of Ubuntu and PHP possible. Everything was going somewhat OK; a decent amount of backwards compatibility issues (mostly custom modules), but I was working through it. Then I noticed that my tripal jobs daemon wasn't running. Trying to run `drush trpjob-daemon start` produced the following error:
```
PHP Fatal error:  Uncaught TypeError: daemon_exception(): Argument #1 ($e) must be of type Exception, TypeError given in /var/www/html/sites/all/libraries/PHP-Daemon/Core/error_handlers.php:111
Stack trace:
#0 [internal function]: daemon_exception()
#1 {main}
  thrown in /var/www/html/sites/all/libraries/PHP-Daemon/Core/error_handlers.php on line 111
Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Uncaught TypeError: daemon_exception(): Argument #1 ($e) must
be of type Exception, TypeError given in
/var/www/html/sites/all/libraries/PHP-Daemon/Core/error_handlers.php:111
Stack trace:
#0 [internal function]: daemon_exception()
#1 {main}
  thrown in
/var/www/html/sites/all/libraries/PHP-Daemon/Core/error_handlers.php,
line 111
```
It's not a very informative error. From what I gathered, the error log is breaking due to unexpected values (backward incompatibility with PHP?). Searching the error, I found a very old github post (https://github.com/UofS-Pulse-Binfo/tripal_daemon/issues/9). Unfortunately, I don't think the user issue was ever resolved.

My current guess is that PHP-Daemon isn't compatible with my version of PHP.

**Comment by dsenalik** [comment]
This appears to be a bug in PHP-Daemon that becomes an error in PHP8.x
https://github.com/shaneharter/PHP-Daemon

Because the repo is archived and we can't submit new issues, I will provide a patch here to indicate what I did to fix it. The problem is that sometimes a TypeError is passed instead of an exception, and the function is defined to only accept an exception, and in PHP8 this becomes a fatal error. The fix is to just not enforce that it must be an exception in the function definition.
[20230310_PHP-Daemon.patch.txt](https://github.com/tripal/tripal/files/10944811/20230310_PHP-Daemon.patch.txt)

**Comment by dsenalik** [comment]
If you get this error from PHP-Daemon:
```Note: The PHP error_log at  is not writable! Errors will be written to STDERR. Fix the permissions problem or correct the error_log path.```

this is because ```error_log``` is not set in your ```php.ini``` file. The simple fix is to uncomment this one line
```
; Log errors to specified file. PHP's default behavior is to leave this value
; empty.
; http://php.net/error-log
; Example:
error_log = php_errors.log      <-- uncomment this line
; Log errors to syslog (Event Log on Windows).
;error_log = syslog
```
and then restart Apache of course...
