### ISSUE TITLE
Undefined Variable $type

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#145]
The OBOImporter uses an undefined variable while inserting a record to chado::tripal_obo_tmp.

Please review line 1159 where the variable $type is not previously defined: https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalImporter/OBOImporter.inc#L1159

Also review line 1079 where the variable $name is undefined: https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalImporter/OBOImporter.inc#L1079

Thanks!

**Comment by laceysanderson** [comment]
@spficklin could you take a look at this? I'm not sure what the $type was meant to be...

**Comment by spficklin** [comment]
Thanks for pointing out the two problems.  The code has been fixed for both Tripal v3 and v2.
