### ISSUE TITLE
Tripal 4 add PHP 8.2 to automated testing

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1455]
# Core Tripal 4 Development Task

Add PHP8.2 to the automated testing for Tripal 4. This was added to Tripal 3 automated testing with #1435, however due to the numerous deprecations this creates, and work required to fix, Tripal 3 will not officially support PHP 8.2. (Issue #1454)

**Comment by laceysanderson** [comment]
Now that we have support for Drupal 10, I am tackling this. I have changed the branch name slightly as I will be doing the following in one:

- Add PHP 8.2 to workflows
- Drop Drupal 9.2.x and 9.3.x support
- Add testing on Drupal 10.1.x
- Perhaps add other PostgreSQL versions to testing.

**Comment by dsenalik** [comment]
Resolved with merged PR #1519
