### ISSUE TITLE
Rename fields using standard tripal 4 naming scheme

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1468]
# Core Tripal 4 Development Task

## Pull #1470

Tripal fields in core no longer use a name based on a cv term as in Tripal 3
Link to [Naming convention documentation](https://tripaldoc.readthedocs.io/en/latest/dev_guide/module_dev/fields.html#naming-convention)
So, a few fields currently defined using this old method need to be renamed as follows:

`chado_linker__prop` ⟹ `ChadoLinkerPropertyDefault`
`obi__organism` ⟹ `ChadoOrganismDefault`
`schema__additional_type` ⟹ `ChadoAdditionalTypeDefault`

This will apply to both file names and internal `id` and function names

**Comment by laceysanderson** [comment]
PR Merged -Thank you @dsenalik!

**Comment by dsenalik** [comment]
Okay, I am going to reopen this because I didn't follow the rules for "Type" and some others need fixing. I know that `ChadoAdditionalTypeTypeDefault` looks weird but it follows the rules.
## PR #1709

| current | change to |
| --- | --- |
| ChadoBooleanTypeItem.php | ChadoBooleanTypeDefault.php |
| ChadoIntegerTypeItem.php | ChadoIntegerTypeDefault.php |
| ChadoStringTypeItem.php | ChadoStringTypeDefault.php |
| ChadoTextTypeItem.php | ChadoTextTypeDefault.php |
| ChadoAdditionalTypeDefault.php | ChadoAdditionalTypeTypeDefault.php |
| ChadoAnalysisDefault.php | ChadoAnalysisTypeDefault.php |
| ChadoContactDefault.php | ChadoContactTypeDefault.php |
| ChadoLinkerPropertyDefault.php | ChadoLinkerPropertyTypeDefault.php |
| ChadoOrganismDefault.php | ChadoOrganismTypeDefault.php |
| ChadoSequenceChecksumDefault.php | ChadoSequenceChecksumTypeDefault.php |
| ChadoSequenceDefault.php | ChadoSequenceTypeDefault.php |
| ChadoSequenceLengthDefault.php | ChadoSequenceLengthTypeDefault.php |
| ChadoSourceDataDefault.php | ChadoSourceDataTypeDefault.php |
| ChadoSynonymDefault.php | ChadoSynonymTypeDefault.php |
| ChadoUnitDefault.php | ChadoUnitTypeDefault.php |
