### ISSUE TITLE
Tripal 4 code review bug in OBO importer

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1472]
# BUG/ERROR report

### Issue description
I noticed this in the code, but didn't encounter an error until I copied and pasted it elsewhere. Error is
`Error: Cannot use object of type Drupal\Core\Form\FormState as array`

Line 464 of `tripal_chado/src/Plugin/TripalImporter/OBOImporter.php`:
```
$form_state['rebuild'] = TRUE
```
should be
```
$form_state->setRebuild(True);
```

#### Steps to reproduce
Not sure, this is found with code review 🧐

**Comment by laceysanderson** [comment]
Fixed in merged PR -good catch/fix @dsenalik <3
