### ISSUE TITLE
Phpunit workflows not running on PRs from a forked repo

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#1477]
# BUG/ERROR report

### Issue description

Something seems to have changed recently with github actions. In the past collaborators have been able to submit a PR from a forked version of our repo and our workflows would all run in this repo to validate the PR. This is needed because we can't merge PRs until they pass certain required checks.

However now no workflows are run on PRs from forked repositories. [This GitHub doc](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) says we can approve these workflows to run. However, in practice we can only approve running of the assert branch name workflow and not our automated testing.

Based on [this GitHub discussion](https://github.com/orgs/community/discussions/25012), we can change our action to pull_request for the phpunit workflow to enable it to run in our repo for PRs triggered by forked repos... however, I believe this will only be triggered when the PR is first made and not on any additional commits which improve or fix things in the PR...

I have seen this in both @srobb1 PR #1419 and @pdtouch PR #1476. I was able to merge @pdtouch's PR but only after forcing override of branch protections which is not ideal.

The weird thing is I could have sworn this used to work. Specifically, I remember the phpunit workflow running on #1419 when it was first created and again after Sofia added commits. It's only now after I resolved the merge conflicts that it won't run.

#### Steps to reproduce

1. Fork the tripal/tripal repo
2. make a small change on a branch and submit a PR
3. The automated testing workflows will not run:
 
<img width="837" alt="Screen Shot 2023-04-10 at 7 00 30 PM" src="https://user-images.githubusercontent.com/1566301/231028246-ebb85a19-47b5-42ba-99e4-8bf146ef7842.png">

**Comment by pdtouch** [comment]
Lacey,
Is it possible that other code in my repo have bugs that is causing this ?
I have incomplete ChadoLocalSourceData field in my pdtouch repo.
Thanks
Sukha

**Comment by laceysanderson** [comment]
I don't think so @pdtouch bugs should never stop workflows from running unless they are in the workflow yml files and even then -it is still triggered but will fail. Also only the branch you made a PR with will affect tests on that PR so you should be good 👍 

I submitted PR #1478 as I think I've found the problem 🤞

**Comment by laceysanderson** [comment]
<img width="836" alt="Screen Shot 2023-04-11 at 11 34 05 AM" src="https://user-images.githubusercontent.com/1566301/231243491-ec95dbcf-ab25-49bc-8e3a-580fd62a5957.png">

Fixed 🎉  As shown in the screenshot. The PHPunit workflow was now run in our repo on Sofia's remote branch which allows our merge requirements to actually be met for forked repo PRs :-)
