### ISSUE TITLE
cvterm not in database, field cannot be shown

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#148]
@almasaeed2010 and I both have the following problem when trying attach a field to organism [(here is the simple module with the problem)](https://github.com/statonlab/tripal_ssr/tree/use_SO_term). 

>WARNING: The controlled vocabulary term, 'so:so__microsatellite (so__microsatellite)', assigned to the field, 'so__microsatellite', is not in the database. The field cannot be shown. Please add the term and the field will appear below.

The term is indeed in the database.  Through `dpm` I've traced the problem to the below call in `tripal_chado.vocab_storage.inc`, but trying to look at `chado_generate_var` is pretty tough.

```
  $cvterm = chado_generate_var('cvterm', $match);
```
The variables look right in `tripal_chado.vocab_storage.inc`: the vocabulary is `so` and the accession is set to `so_microsatellite` (which is wrong of course, but matches the code).  

Any ideas what the problem might be?  We got the same warning using an entirely different CV term (NCI__short_tandem_repeat).

**Comment by laceysanderson** [comment]
@bradfordcondon and @almasaeed2010, I ran into this error as well when working on fields. 

The problem is in your Tripal Field class: https://github.com/statonlab/tripal_ssr/blob/use_SO_term/includes/TripalFields/so__microsatellite/so__microsatellite.inc#L64. 
```php
public static $default_instance_settings = [
        // The short name for the vocabulary (e.g. schema, SO, GO, PATO, etc.).
        'term_vocabulary' => 'so',
        // The name of the term.
        'term_name' => 'so__microsatellite',
        // The unique ID (i.e. accession) of the term.
        'term_accession' => 'so__microsatellite',
        // Set to TRUE if the site admin is not allowed to change the term
        // type, otherwise the admin can change the term mapped to a field.
        'term_fixed' => false,
        // Indicates if this field should be automatically attached to display
        // or web services or if this field should be loaded separately. This
        // is convenient for speed.  Fields that are slow should for loading
        // should have auto_attach set to FALSE so tha their values can be
        // attached asynchronously.
        'auto_attach' => false,
        // The table in Chado that the instance maps to.
        'chado_table' => 'organism',
        // The column of the table in Chado where the value of the field comes from.
        'chado_column' => 'organism_id',
        // The base table.
        'base_table' => '',
    ];
```

The `term_accession` should be the chado dbxref.accession field (in your example, `microsatellite`) as shown here: https://github.com/tripal/tripal_example/blob/7.x-3.x/trpexp_fields/includes/TripalFields/local__germplasm_summary/local__germplasm_summary.inc#L63. 
```php
  public static $default_instance_settings = array(
    // The short name for the vocabulary (e.g. schema, SO, GO, PATO, etc.).
    'term_vocabulary' => 'local',
    // The name of the term.
    'term_name' => 'germplasm_summary',
    // The unique ID (i.e. accession) of the term.
    'term_accession' => 'germplasm_summary',
    // Set to TRUE if the site admin is not allowed to change the term
    // type, otherwise the admin can change the term mapped to a field.
    'term_fixed' => FALSE,
    // Indicates if this field should be automatically attached to display
    // or web services or if this field should be loaded separately. This
    // is convenient for speed.  Fields that are slow should for loading
    // should have auto_attach set to FALSE so tha their values can be
    // attached asynchronously.
    'auto_attach' => FALSE,
    // The table in Chado that the instance maps to.
    'chado_table' => 'organism',
    // The column of the table in Chado where the value of the field comes from.
    'chado_column' => 'organism_id',
    // The base table.
    'base_table' => 'organism',
  );
```

**Comment by bradfordcondon** [comment]
That was the problem, thank you!

**Comment by laceysanderson** [comment]
Great :-)
