### ISSUE TITLE
Tripal 4 testing badges do not work

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1496]
# BUG/ERROR report

### Tripal Version: 4.alpha.1
* Drupal Version: automated testing versions
* PostgreSQL Version: ditto
* PHP Version: likewise

### Issue description
Updating the testing badges in the tripal_doc repo broke the badge images.
See the discussion at https://github.com/tripal/tripal_doc/pull/36#pullrequestreview-1400697835

I think the version in the PHP unit test files didn't get updated with the move from the t4d8 repo. `9.x-4.x` needs to get changed to `4.x` in for example
https://github.com/tripal/tripal/blob/98567469d8350ae983acfd6a59a89fa3e2ad9b56/.github/workflows/MAIN-phpunit-php8.1_D9_4x.yml#L6

#### Steps to reproduce
This link should show a testing badge, but displays `Not Found`
https://github.com/tripal/tripal/actions/workflows/MAIN-phpunit-php8.1_D10_0x.yml/badge.svg

**Comment by dsenalik** [comment]
sorry ignore this comment

**Comment by laceysanderson** [comment]
Wow, yup I missed that! That would be it exactly.

**Comment by dsenalik** [comment]
One last change needed as noted by @laceysanderson is to fix the badge URLs in the tripal README

## Branch Name: tv4g9-issue1496-update-testing-badge-urls

## Pull #1499
