### ISSUE TITLE
Adding an Analysis Field: new module or add here?

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#150]
I'm creating this issue at @spfickli 's request.  

We are creating a simple field to attach to Organism that will list analyses associated with the organism, to mirror our V2 hardwood genomics set up.  

My first instinct was that this functionality was too small for its own module, doesn't fit in neatly with our other modules, and therefore would make a good addition to the tripal core, so i was adding it in `tripal_chado`.  Stephen raised the issue of keeping Tripal lean.
A possible alternative solution raised by Stephen...
>it makes me wonder if perhaps we should have a location other than modules where folks can put these.  That way you don't have to build a full blown module.

Cheers!

**Comment by spficklin** [comment]
I just committed a fix to this that will allow you to place your fields in the sites/all/libraries/TripalFields directory.  This way you don't need to create a new module to add new fields.   You'll need to pull the most recent copy of the code and enable the [libraries API module](https://www.drupal.org/project/libraries).  If you don't enable the libraries API module then it won't work but Tripal won't complain either.   Let me know if this woks for you and we can close the issue.

**Comment by bradfordcondon** [comment]
@spficklin I'm tryin this now, but what about the `module_name.fields.inc` file? 

![screen shot 2017-12-14 at 12 04 38 pm](https://user-images.githubusercontent.com/7063154/34004835-fc5381b6-e0c6-11e7-84e7-e1739131d302.png)
