### ISSUE TITLE
Tripal 4 update YAML for various missing fields

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1509]
# BUG/ERROR report

### Issue description

Currently publication content type has no fields defined except for "Authored by".
Presumably these are missing from
`tripal_chado/config/install/tripal.tripalfield_collection.default_chado.yml`

Other fields are also missing from various content types

#### Steps to reproduce
`/bio_data/add/bio_data_6`
 
#### Error messages and screenshots
![add-publication](https://github.com/tripal/tripal/assets/8419404/ba4913d9-021d-4fa0-9f0a-6d0d592e0be5)

**Comment by spficklin** [comment]
I think this issue is corrected with the last alpha release, but please reopen if I'm wrong.
