### ISSUE TITLE
Vocabulary term: Analysis

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#151]
As suggested in the tripal documentation, I'll be creating issues for discussion about CVterms that effect the community.

I think that moving all central terms over from local to CV is in the spirit of Tripal 3.  If I'm going overboard, just let me know: maybe we like having local terms for things like this.

First on the block is analysis (to match the simple field we're adding: #150 ).  I see that the bundle is currently associated with `local__analysis`.  I would propose that the EDAM/SWO term analysis is the best one:
http://www.ebi.ac.uk/ols/ontologies/swo/terms?iri=http%3A%2F%2Fedamontology.org%2Foperation_2945

Based on my newfound understanding of how we deal with confusing ontologies in Chado (particularly EDAM), this would be:
```

  $term = tripal_insert_cvterm(array(
    'id' => 'operation:2945',
    'name' => 'Analysis',
    'cv_name' => 'EDAM',
    'definition' => 'Apply analytical methods to existing data of a specific type.',
  ));
```

For comparison, we currently use a dictionary definition of analysis:
>A process as a method of studying the nature of something or of determining its essential features and their relations. (Random House Kernerman Webster's College Dictionary, © 2010 K Dictionaries Ltd).

**Comment by spficklin** [comment]
Yep, I agree that this is a better term than the local term we were using. I've adjusted the code to use this term when creating new Analysis content types.
