### ISSUE TITLE
Tripal 4 - NCBI Taxonomy and Newick Loader

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#1513]
GOAL: To make the NCBI Taxonomy Loader compatible with Tripal 4
Branch: tv4g4-1513-taxonomyloader
Pull #1560

**Comment by dsenalik** [comment]
After pull #1560 is merged, the following still needs to be done. I renamed this issue slightly, and this issue will remain open for now to implement:
  * Implement the Newick file importer
  * Tests for the Newick importer
  * add kernel tests for the phylotree API functions that require the Newick file importer

Branch: tv4g4-issue1513-newickloader

**Comment by laceysanderson** [comment]
Closing in favour of #1586
