### ISSUE TITLE
Tripal 4 - Publish Chado Content

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal#1515]
# Core Tripal 4 - Publish Chado Content

This issue is for the development and progress tracking of initial and naive Chado content publishing.
Goals of this branch/issue:
 - [ ] List available content types (e.g. Organism, Analysis, etc.).
 - [ ] Publish content found in Chado to content pages (naively, without checking if the Tripal entities have already been created and/or published.
 - [ ] Any Chado storage plugin functionality to allow Tripal to query Chado about content and which content is published or not.

Building off of this issue (following completion of this issue):
 - [ ] Non-Chado storage plugin functionality to allow Tripal to query any data store about content and its published status.
 - [ ] On the Publish Content form, allow filters to only publish content that fits certain criteria.

**Comment by spficklin** [comment]
The following items were moved here from our PMC discussion list. These are things that need to be discussed/addressed as part of the publishing step:

- How do we tell if it is already published? 
- Maybe we use entityQuery and add a primary key field? 
- Then each tripal entity type just needs to know the primary key/table in chado for that content type. 
- For handling multi-chado we just make that key support multiple values where each is a schema/pkey value pair.
- T3 publishing was in tripal_chado, should it stay here for T4 considering that publishing will/should be chado agnostic?

**Comment by spficklin** [comment]
The only item left for this issue is publishing of fields on content types that have a `type_id` in the prop tables of Chado.

**Comment by spficklin** [comment]
This issue is resolved as per the muliptle recent PRs,
