### ISSUE TITLE
install chado report SQL syntax error

### ISSUE THREAD

**Issue by jmzhuzhonghua** [tripal/tripal#1516]
My system info：
Drupal Version 10.0.9
PHP Version 8.1.18 
Database Version PostgreSQL 14.7

When install Chado, there errors as following: 

2023-05-17 01:09:23
Tripal Job Launcher
Running as user 'zzh'
-------------------
2023-05-17 01:09:23: Job ID 3.
2023-05-17 01:09:23: Calling: tripal_chado_install_chado(chado, 1.3)
 [error]  SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "1"
LINE 2:         INSERT INTO 1:chadoprop (type_id, value)
                            ^:
        INSERT INTO 1:chadoprop (type_id, value)
          VALUES (
           (SELECT cvt.cvterm_id
            FROM 1:cvterm cvt
              INNER JOIN 1:cv cv ON cvt.cv_id = cv.cv_id
             WHERE cv.name = 'chado_properties' AND cvt.name = 'version'),
           :version); Array
(
    [:version] => 1.3
)

 [error]  Message: Job execution failed: Failed to complete Chado installation task.
SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "1"
LINE 2:         INSERT INTO 1:chadoprop (type_id, value)
                             ^:
         INSERT INTO 1:chadoprop (type_id, value)
           VALUES (
            (SELECT cvt.cvterm_id
             FROM 1:cvterm cvt
               INNER JOIN 1:cv cv ON cvt.cv_id = cv.cv_id
              WHERE cv.name = 'chado_properties' AND cvt.name = 'version'),
            :version); Array
(
     [:version] => 1.3
)

**Comment by laceysanderson** [comment]
Yes, we are not quite compatible with Drupal 10 yet but should be within the week (I have this exact piece working in a branch already).

You can always see our current Drupal versions supported on the Tripal 4 Readme. This is validated with automated testing so it's a pretty good picture of support.
https://github.com/tripal/tripal/tree/4.x#compatibility

**Comment by laceysanderson** [comment]
Also, just to let you know our current target Drupal version is 9.5 but it will be switching to 10.0 within the week once I have tests passing.

**Comment by dsenalik** [comment]
I am closing this issue as we now support Drupal 10. Feel free to reopen or to post a new issue if this is still a problem.
