### ISSUE TITLE
Run jobs on internal cluster

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal#152]
Would it be possible to have jobs run on an internal cluster?
 Example: the BLAST UI module spawning BLAST+ jobs on cluster instead of web server.

**Comment by spficklin** [comment]
What cluster scheduler would you like supported?

**Comment by Ferrisx4** [comment]
Our cluster uses SLURM but for our purposes it would be useful if it was just able to utilize a remote server (not the webserver). In our case we have a dedicated app server (not part of cluster) that would work better to run BLAST.

**Comment by spficklin** [comment]
I think this would call for a new tripal_remote_job module.  We'd have to add a hook to let other modules handle job submission into the core of Tripal and then this new module could be used to launch any job remotely.  As time progressed it could be used for running a job on a remote server or submitting a job to a cluster.

**Comment by spficklin** [comment]
Marking this as closed as we have a new module in development to handle this at https://github.com/Ferrisx4/tripal-remote-job
