### ISSUE TITLE
Tripal 4 Drupal 10.1 compatibility

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1523]
# Core Tripal 4 Development Task

## Branch Name: tv4g9-issue1523-drupal-10.1-compatibility

This issue might overlap with #1510 

Automated testing is now extended to PHP 8.2 and Drupal 10.1 as of pull #1519

Pull #1521 fixes the PHP8.2 deprecations, but there are some testing errors with Drupal 10.1

Here's a summary of what to work on from https://github.com/tripal/tripal/actions/runs/5059338817/jobs/9080721693?pr=1521

### Errors

1) Drupal\Tests\tripal_chado\Functional\ChadoStorageTest::testChadoStorage
Drupal\tripal\TripalDBX\Exceptions\SchemaException: Invalid or unsupported Chado schema version ''.

2) Drupal\Tests\tripal_chado\Functional\ChadoVocabTermsTest::testTripalVocabularyClasses
Drupal\tripal\TripalDBX\Exceptions\SchemaException: Invalid or unsupported Chado schema version ''.

3) Drupal\Tests\tripal_chado\Functional\Task\ChadoPreparerTest::testChadoPreparer
Drupal\tripal_biodb\Exception\TaskException: Failed to complete schema integration (i.e. Prepare) task.
Cannot prepare. Currently only Chado v1.3 is supported.

### Failures

1) Drupal\Tests\tripal\Functional\TripalDBX\SchemaTest::testTripalDbxSchemaPrefixInfo
Prefix ok.
Failed asserting that two arrays are equal.

2) Drupal\Tests\tripal\Functional\TripalDBX\SchemaTest::testTripalDbxSchemaScenario1
Tables found.
Failed asserting that an array is not empty.

3) Drupal\Tests\tripal_chado\Functional\ChadoConnectionTest::testFindVersion
Unable to extract the version from INIT_CHADO_EMPTY test schema with no parameters provided.
Failed asserting that two strings are equal.

4) Drupal\Tests\tripal_chado\Functional\Task\ChadoInstallerFunctionalTest::testPerformTaskInstaller
Table created.
Failed asserting that false is true.

5) Drupal\Tests\tripal_chado\Functional\Task\ChadoPreparerTest::testPrepareTestChadoSimulation
The Tripal Custom Table tripal_gff_temp doesn't exist but should have been created during the prepare step.
Failed asserting that false is true.

**Comment by spficklin** [comment]
I believe @laceysanderson stated there were still some issues that weren't part of the PR #1636 so I'm leaving this issue open for now.  Please close if I'm wrong.

**Comment by laceysanderson** [comment]
Originally there were a few issues not addressed in the PR but then I had a brainwave and actually fixed them! 🎉 As such, we are now at 100% compatibility to my knowledge 😁
