### ISSUE TITLE
PDO exception feature not supported, Cross db error when run solr indexing

### ISSUE THREAD

**Issue by cguttai5k** [tripal/tripal#153]
when I'm indexing content to apache solr, getting this exception error in recent logs:

`PDOException: SQLSTATE[0A000]: Feature not supported: 7 ERROR: cross-database references are not implemented: "chado.chado.feature_synonym" LINE 1: select s.synonym_id, s.name from chado.chado.feature_synonym... ^: select s.synonym_id, s.name from chado.chado.feature_synonym fs, chado.synonym s where fs.synonym_id=s.synonym_id and fs.feature_id=:feature_id; Array ( [:feature_id] => 7218386 ) in chado_query() (line 1533 of /sites/all/modules/contrib/tripal/tripal_core/api/tripal_core.chado_query.api.inc).`

Any help would be appreciated? Thanks!

**Comment by cguttai5k** [comment]
issue has been resolved, it was due to the chado query

**Comment by spficklin** [comment]
Was it just an incorrectly implemented call to chado_query or was there a problem with the function?

**Comment by cguttai5k** [comment]
incorrect implementation of chado_query @spficklin
