### ISSUE TITLE
Update node.js from version 12 to 16

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1530]
# Core Tripal 4 Development Task

## Branch Name: tv4g0-issue1530-update-node.js-from-12-to-16

The motivation for this issue is to fix the warnings emitted during the docker build process, for example, the first of eight warnings at https://github.com/tripal/tripal/actions/runs/5122451673 is:

Docker Build (drupal9.4.x-dev)
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by laceysanderson** [comment]
Fixed! 🎉
