### ISSUE TITLE
Tripal 3 PHP8 error in chado storage

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1532]
# BUG/ERROR report

### Tripal Version: 3.10
* Drupal Version: 7.97
* PostgreSQL Version: 15.3
* PHP Version: 8.1.18

### Issue description
I can't save a new license with the tripal_file module. This looks like another PHP8 error that would not have been visible under PHP 7.x

#### Steps to reproduce

1.  Install tripal_file module
2. Try to create a new license. The following error occurs
`The website encountered an unexpected error. Please try again later. `
and in the log we see:
`TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in tripal_chado_field_storage_write_table() (line 232 of .../sites/all/modules/tripal/tripal_chado/includes/tripal_chado.field_storage.inc).`
also an empty license entity is created, all the fields are null ☹️

**Comment by laceysanderson** [comment]
Fixed in tagged PR!
