### ISSUE TITLE
Chado Cvterm Autocomplete

### ISSUE THREAD

**Issue by reynoldtan** [tripal/tripal#1534]
## Tripal 4 Feature Request

* This feature does not attempt to solve an existing problem with Tripal
* I am open to developing or collaborating on an extension module if this is not a good fit for Tripal Core

* This feature is Not Urgent

### Description

![image](https://github.com/tripal/tripal/assets/15472253/cb9e442d-ae82-415b-b3ba-d27015b6eb84)

Recent completion of a feature to autocomplete cvterm (https://github.com/tripal/tripal/pull/1486) lacks a method to display the equivalent formatted text (cvterm.name (db.name:dbxref.accession) given a cvterm id number. This is useful for setting the default value of an autocomplete cvterm type field.

**Comment by laceysanderson** [comment]
Haha, Yes we definitely need this in core!

**Comment by dsenalik** [comment]
Completed with merged PR #1535
