### ISSUE TITLE
Tripal 3 loader error

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#154]
Currently getting the following error with all new Loaders (Chado FASTA loader, GFF3 loader)...  after pressing "Upload File" on both local dev and our Hardwoods dev site:
`SyntaxError: Unepected token { in JSON at position 48`

![screen shot 2017-08-28 at 10 02 06 am](https://user-images.githubusercontent.com/7063154/29776869-15b5673a-8bd8-11e7-924e-010e70b767e9.png)

Currently investigating `tripal/theme/js/TripalUploadFile.js` to see if I can figure out the problem but if anyone knows the issue please let me know!

**Comment by bradfordcondon** [comment]
output: I have 1 chunk successfully written. Below is the contents of `tripal_upload.log`
 
`a:1:{s:14:"chunks_written";a:1:{i:0;s:2:"27";}}`

**Comment by spficklin** [comment]
Is this the case where the file is only the size of a single chunk?  Otherwise, I've not encountered this problem before.

**Comment by bradfordcondon** [comment]
Yes it was.  However the chunk size is pretty large (2GB I believe?) so i'd imagine it will occur.

Edit:  oops its 2MB.  `this.chunk_size = (1024 * 2000); // 2024MB` the human name is 2GB though :P

**Comment by spficklin** [comment]
Hi @bradfordcondon I submitted a fix for this problem that is different from your pull request #155.  I'll comment on that pull request but the fix proposed didn't quite fix the real issue which was an accidental incorrect naming of a function that made it look like a hook when it wasn't.

**Comment by bradfordcondon** [comment]
Hi Stephen, the current branch works for us, thank you so much!
