### ISSUE TITLE
Chado project autocomplete

### ISSUE THREAD

**Issue by reynoldtan** [tripal/tripal#1553]
## Tripal 4 Feature Request

* This feature [does not] attempt to solve an existing problem with Tripal
* I [am] open to developing or collaborating on an extension module if this is not a good fit for Tripal Core

* This feature is [Not Urgent]

### Description

Provide a controller to autocomplete project name. The controller can limit number of suggestions to show in an autocomplete field and a type_id option to limit/restrict projects to only match project type set in projectprop.type_id field. 

### Your Specific Use Case

![Screen Shot 2023-06-21 at 1 32 32 PM](https://github.com/tripal/tripal/assets/15472253/f03c1eeb-61d7-4047-b750-65bdd6a525b7)

Autocomplete field that requires project name to be entered.

**Comment by dsenalik** [comment]
I added an autocomplete for project for Tripal 3, but of course it looks like this is implemented differently in Tripal 4. I also suspect we will need autocompletes for a lot more things than just project!
