### ISSUE TITLE
Tripal 4 Drupal 10: All hook invocation delegated to Module Handler service

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1556]
# BUG/ERROR report

### Tripal Version: 4.alpha-dev docker
* Drupal Version: 10.1
* PostgreSQL Version: 13
* PHP Version: 8.2

### Issue description

This popped up trying to run the OBO importer under Drupal 10.1 + PHP 8.2, we are seeing that getImplementations() is no longer in Drupal core.

#### Steps to reproduce
 1. Build a docker under Drupal 10.1 and PHP 8.2 `docker build --tag=tripaldocker:testing-xxxx --build-arg drupalversion="10.1.x-dev" --file tripaldocker/Dockerfile-php8.2-pgsql13 ./`
 2. Go to Tripal -> Data Loaders -> OBO Vocabulary Loader
 3. Select the Gene Ontology (GO)
 4. Import OBO File
 5. `drush trp-run-jobs --job_id=1 --username=drupaladmin --root=/var/www/drupal9/web`
 
#### Error messages and screenshots
`Running 'OBO Vocabulary Loader' importer
 [notice] Running 'OBO Vocabulary Loader' importer
NOTE: Loading of this file is performed using a database transaction. If it fails or is terminated prematurely then all insertions and updates are rolled back and will not be found in the database
 [notice] NOTE: Loading of this file is performed using a database transaction. If it fails or is terminated prematurely then all insertions and updates are rolled back and will not be found in the database
 [error]  Error: Call to undefined method Drupal\Core\Extension\ModuleHandler::getImplementations() in tripal_run_importer() (line 122 of /var/www/drupal9/web/modules/contrib/tripal/tripal/src/api/tripal.importer.api.php) #0 [internal function]: tripal_run_importer('5', Object(Drupal\tripal\Services\TripalJob))`

#### Reason
A different drupal module is having this problem too, apparently:
[[10.0] ModuleHandlerInterface::getImplementations() removed from core](https://www.drupal.org/project/rules/issues/3346842)

According to [the change log](https://www.drupal.org/node/3000490) we will need to update all our custom hooks to use the new structure. Introduced in Drupal 9.4, so it should be possible to update this for all of our currently supported Drupal versions.

#### To-Do List
```
$ grep -nr getImplementations
tripal/src/api/tripal.importer.api.php:122:    $modules = \Drupal::moduleHandler()->getImplementations('importer_start');
tripal/src/api/tripal.importer.api.php:135:    $modules = \Drupal::moduleHandler()->getImplementations('importer_finish');
$ grep -nr implementsHook
```

**Comment by laceysanderson** [comment]
Custom Hooks currently documented in Tripal 4:

- hook_handle_uploaded_file($file, $type) ➙ tripal/src/api/tripal.importer.api.php:40
- hook_importer_start($importer) ➙ tripal/src/api/tripal.importer.api.php:53
- hook_importer_finish($importer) ➙ tripal/src/api/tripal.importer.api.php:67
- hook_file_upload_check($action, $details, &$message) ➙ tripal/src/api/tripal.upload.api.php:133
- hook_tripal_default_title_format($tokens) ➙ tripal/src/api/tripal.entities.api.php:80
- hook_tripalstorage_info_alter() ➙ only mentioned in a comment tripal/src/Plugin/Annotation/TripalStorage.php:11
- hook_exclude_field_from_tablename_by_default() ➙ only mentioned in a comment tripal_chado/src/api/tripal_chado.variables.api.php:73
- hook_exclude_type_by_default() ➙ tripal_chado/src/api/tripal_chado.variables.api.php:1071
- hook_tripal_chado_column_upgrade_alter() ➙ tripal_chado/src/Task/ChadoUpgrader.php:2313

For hook_file_upload_check() it seems to be restricted to "the module that will own the file" and thus determines the function name on it's own using that assumption 😬 See tripal/src/api/tripal.upload.api.php.

hook_tripalstorage_info_alter() is specified as an alter hook in the plugin manager and handled by Drupal so no need to update this one I believe.

Others appear to be implemented using `\Drupal::moduleHandler()->invokeAll()` to invoke all versions of the hook without needing to get implementations 🤷‍♀️

**Comment by laceysanderson** [comment]
I'm closing this as I don't think it is a problem any more. From what I can remember of talking about this with @dsenalik, the two instances in the importer were the only ones actually affected by this change. The others I listed are times we use custom hooks but use approaches which were not affected.
