### ISSUE TITLE
Jobs not running

### ISSUE THREAD

**Issue by ligmanowski** [tripal/tripal#156]
![tripal error](https://user-images.githubusercontent.com/31517564/29936776-d1e322f2-8e59-11e7-95a9-d7701c1136a6.PNG)

Hi there Tripal community, howdy? I recently installed a GMOD Cloud image at Amazon AWS where I intend to deposit 30+ organisms - black yeast specifically - to form a HUB of these family. But, Im having an issue I have no clue how to fix it. Attached at this you can see my Jobs, all of them are pending at "Waiting" status. How did I miss? Am I using a too old version of it? If so, is there another image or Tripal Template I can install at another Drupal server?

Thanks in advance and best regards,

Raphael

**Comment by spficklin** [comment]
Hi Raphael,

Thanks for posting the issue. There are three ways to get your jobs to launch:

1)  Run the jobs manually:  to do this log on to your VM instance and change to the directory where Drupal is installed and run this command:

drush trp-run-jobs --user=administrator


2)  Setup the site cron.  You can find instructions on the Tripal install docs for this:  http://tripal.info/tutorials/v2.x/installation/tripal#toc-tripal-installation-QYNtNgJU.    This method will have the VM's cron system launch jobs on a periodic basis.  Any jobs in the queue will be run when the cron runs. 

3)  Use the Tripal Daemon module.  This is probably the best way to get your jobs to run.  It will cause jobs to run almost instantly when they are submitted.  I don't think the image you used comes with this module, so you'll have to install it.  You can find information about it here:  https://www.drupal.org/project/tripal_daemon

I think the cloud instance you are using will run Tripal v2.  It certainly helps you get it up and running faster, but we do have a new Tripal v3-rc1 version out now, but there's no cloud instance for it yet.  If you're up to installing it on your own we do have an online tutorial for that:   http://tripal.info/tutorials/v3.x

**Comment by spficklin** [comment]
Hi Raphael, were you able to get this resolved?

**Comment by ligmanowski** [comment]
Hi Stephen, thanks for reaching me out, I appreciate.

I stopped the AWS instance I had running and started one based on Docker
using Tripal 2.X. Im doing locally at a VM than Ill send it to cloud one
step at the time (hehe).

As soon as I finished that, what I expect to do at this weekend Ill let you
know.

Thanks for the help,

Raphael

Em 7 de set de 2017 12:52, "Stephen Ficklin" <notifications@github.com>
escreveu:

**Comment by ligmanowski** [comment]
Hi Stephen, sorry for the delay.

I tried to use cron and running manually, in both cases I got this error:
$ /var/www$ drush trp-run-jobs --user=ubuntu
The drush command 'trp-run-jobs' could not be found.  Run `drush     [error]
cache-clear drush` to clear the commandfile cache if you have
installed new extensions.

I trying this command at GMOD Cloud running at AWS

Can you help me please? Sorry for any stupid question.


Thanks and best regards,

Raphael

**Comment by spficklin** [comment]
Typically the directory for the Drupal installation is /var/www/html rather than /var/www.  Although it doesn't have to be.  Should you run this in the /var/www/html directory?  The drush command must be run from withing the Drupal installation somewhere.  

Sorry for the delay in response.  This week has been a bit to busy!

**Comment by ligmanowski** [comment]
No worries to take your time to answer. Ill double check in what folder Im trying to run the commands. Ill let you know if I made any progress. Thanks and best regards.

**Comment by spficklin** [comment]
Just checking in on this one as well @ligmanowski .   Do you need additional help on this one?

**Comment by spficklin** [comment]
Marking this as closed. If you're still having issues please re-open.
