### ISSUE TITLE
OBO Importer: legacy_ro.obo does not exist or cannot be read. 

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#1568]
# BUG/ERROR report

### Tripal Version:
* Drupal Version: 10.0.11-dev 
* PostgreSQL Version: 13.11 (Debian 13.11-0+deb11u1) 
* PHP Version: 8.1.20 

### Issue description

Trying to load the legacy Relationship ontology produces an error:

```
The specified path, /var/www/drupal9/web/modules/contrib/tripal/tripal_chado/files/legacy_ro.obo, does not exist or cannot be read. 
```

![image](https://github.com/tripal/tripal/assets/1566301/846228c7-7051-4e83-ab16-657538ae863b)

I've confirmed this file does not exist in Tripal 4.x. [Here it is in Tripal 3.x](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/files/legacy_ro.obo). The fix should be as simple as moving this file into the correct place in Tripal 4

#### Steps to reproduce

1. Go to the OBO Importer (Tripal Admin > Data Loaders > OBO Vocabulary Loader; http://localhost/admin/tripal/loaders/chado_obo_loader)
2. Under "Use a Saved Ontology OBO Reference" select "Relationship Ontology (legacy)" from the drop down. 
3. Scroll to the bottom of the page and click the "Import OBO button".
4. Observe the error message shown above.

**Comment by dsenalik** [comment]
Fixing this wasn't quite as simple as hoped, but hopefully the few minor fixes found will prevent errors with other ontologies.

**Comment by laceysanderson** [comment]
Thank you @dsenalik! 💞 Your fixed are merged!
