### ISSUE TITLE
Docker builds are too restrictive for automated testing in extension modules

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#1572]
# Core Tripal 4 Development Task

## Branch Name: tv4g9-1572-expandDockerBuild

We are working on expanding our automated test suite in extension modules I develop and are finding the current docker builds restrictive. Specifically, we want to ensure we are testing with chado stored in a schema with a different name (e.g. `testchado`) just like is done in the Tripal core github workflows. However, all the docker builds install chado in a schema named `chado`.

We tried simply dropping the `chado` schema and installing a `testchado` schema but this causes other problems as the `chado` schema was already prepared and content types created.

A suggested fix to this is to have Tripal core build an additional set of Tripaldocker images that do not have chado installed or prepared. This gives a lot more flexibility to those using the images. These versions will be in addition to those already built so this addition will not negatively affect anyone.

**Comment by dsenalik** [comment]
Completed with merged PR #1575
