### ISSUE TITLE
Tripal 3 PHP 8.1 deprecation notices

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1573]
# BUG/ERROR report

### Tripal Version: 7.x-3.10
Drupal Version: 7.98

### Issue description
Various deprecation notices with PHP 8.1 - easy to fix
`
Deprecated function: Optional parameter $form_state declared before required parameter $mode is implicitly treated as a required parameter in require_once() (line 26 of .../sites/all/modules/tripal/tripal_bulk_loader/tripal_bulk_loader.module).

Deprecated function: Optional parameter $job_id declared before required parameter $node_type is implicitly treated as a required parameter in require_once() (line 24 of .../sites/all/modules/tripal/legacy/tripal_core/tripal_core.module).

Deprecated function: Optional parameter $input declared before required parameter $form_state is implicitly treated as a required parameter in require_once() (line 30 of .../sites/all/modules/tripal/legacy/tripal_core/tripal_core.module).

Deprecated function: Optional parameter $input declared before required parameter $form_state is implicitly treated as a required parameter in require_once() (line 30 of .../sites/all/modules/tripal/legacy/tripal_core/tripal_core.module).

Deprecated function: Optional parameter $analysis_id declared before required parameter $property is implicitly treated as a required parameter in require_once() (line 15 of .../sites/all/modules/tripal/legacy/tripal_feature/tripal_feature.module).

Deprecated function: Optional parameter $feature_id declared before required parameter $property is implicitly treated as a required parameter in require_once() (line 15 of .../sites/all/modules/tripal/legacy/tripal_feature/tripal_feature.module).

Deprecated function: Optional parameter $analysisfeature_id declared before required parameter $property is implicitly treated as a required parameter in require_once() (line 15 of .../sites/all/modules/tripal/legacy/tripal_feature/tripal_feature.module).

Deprecated function: Optional parameter $do_contact declared before required parameter $do_update is implicitly treated as a required parameter in require_once() (line 21 of .../sites/all/modules/tripal/legacy/tripal_pub/tripal_pub.module).
`

#### Steps to reproduce
Sorry, this is kind of a difficult procedure to see this, see the alternative procedure below.

Running under PHP 8.1, update Drupal to 7.98 and then run database updates
![drupalupdate](https://github.com/tripal/tripal/assets/8419404/c0763ea6-4c3d-4e08-a5fa-efa63ba714ae)

Then check the log
![log](https://github.com/tripal/tripal/assets/8419404/3d7e8e0c-616d-4964-916e-4ebd80ab653a)

#### Alternative procedure
In the `/devel/php` window, execute the following
`$x = tripal_pub_import_by_dbxref('bogus', true, true);`
and this seems to be enough to trigger a bunch of deprecation notices in the log

**Comment by laceysanderson** [comment]
Fixed via linked PR. Thanks Doug!

**Comment by dsenalik** [comment]
New message
`Deprecated function: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in chado_replace_tokens() (line 432 of .../sites/all/modules/tripal/tripal_chado/api/tripal_chado.api.inc`

**Comment by dsenalik** [comment]
Closed again with merged PR #1624
