### ISSUE TITLE
Tripal 4 importer logging enhancement

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1579]
# Core Tripal 4 Development Task

This issue is a place to put some cleanup of some of the logging and error messages with any of the importers.

## Branch Name: tv4g4-issue1579-logging

Dependent on #1585 (now merged)

**Comment by laceysanderson** [comment]
Completed with PR merge

**Comment by dsenalik** [comment]
Sorry, reopening, because this issue is a placeholder for some log messages I wanted to (but haven't) worked on.
1. Removing commented-out Tripal 3 versions
2. Log calls that don't use variable substitution
_e.g._
`$this->logger->error("Failed to update feature '$name'");`
should be
`$this->logger->error("Failed to update feature '@name'", ['@name' => $name]);`

This will take a slow tedious examination of all the importers - that's why I haven't done it yet 🙈

Notes for myself from https://drupalize.me/blog/how-log-messages-drupal-8
**Placeholder types**

&commat;variable — Use this style of placeholder for most use-cases. Special characters in the text will be converted to HTML entities.

%variable — Use this style of placeholder to pass text through drupal_placeholder() which will result in HTML escaped text, then wrapped with <em> tags.

&colon;variable — Use this style of placeholder when substituting the value of an href attribute. Values will be HTML escaped, and filtered for dangerous protocols.
