### ISSUE TITLE
Tripal Importer Plugin Submit Button

### ISSUE THREAD

**Issue by reynoldtan** [tripal/tripal#1580]
# BUG/ERROR report

I have an implementation of the Tripal Importer plugin and noticed that even with a **false** value set to **use_button** definition the form will render with a submit button (Please see screenshot below).

![Screen Shot 2023-07-18 at 11 50 39 AM (2)](https://github.com/tripal/tripal/assets/15472253/264b1866-6ac1-4ab6-b663-45802db48029)

![Screen Shot 2023-07-18 at 11 50 39 AM](https://github.com/tripal/tripal/assets/15472253/2e81fea3-7f20-469e-a65d-228a2f4d8274)

### Tripal Version:
* Drupal Version: 9.5.10-dev 
* PostgreSQL Version: 13.11
* PHP Version: 8.1.20

#### Steps to reproduce
1. Create an instance of Tripal Importer Plugin
2. Set the annotation definition **use_button** to False

 
#### Error messages and screenshots

```
no error message
```

**Comment by laceysanderson** [comment]
I can confirm this will happen based on the code.

You can see here in [tripal/src/Form/ImporterForm.php](https://github.com/tripal/tripal/blob/4.x/tripal/src/Form/TripalImporterForm.php#L122-L126)
```php
    // Add the importer custom form elements
    $importer_form = $importer->form($form, $form_state);
    if (is_array($importer_form)) {
      $form = array_merge($form, $importer_form);
    }


    $form['button'] = [
      '#type' => 'submit',
      '#value' => $importer_def['button_text'],
      '#weight' => 10,
    ];

    return $form;
  }
```

That there is no control structure which ensures the submit button is only added when that value is TRUE.

## Solution

The boolean indicating whether the button should be shown or not is defined in the annotation at the top of the importer. This is accessed within the Importer form by using the Drupal plugin API:

Higher up in the same buildForm() method quoted above, you see the following lines
```php
    // Load the specific importer from the plugin_id
    $importer_manager = \Drupal::service('tripal.importer');
    $importer = $importer_manager->createInstance($plugin_id);
    $importer_def = $importer_manager->getDefinitions()[$plugin_id];
```
This block of code uses the Drupal plugin api to grab the annotion block for this specific importer and store it as an associative array in `$importer_def`.

To fix this bug, you will add an if statement surrounding the button code shown above that is only true if $importer_def['use_button'] is not false. Note: this solution is by memory so make sure to check that the $importer_def variable is set up as I describe here and alter the solution as needed.
