### ISSUE TITLE
Debug level logging is not documented and has a gotchya

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1581]
# BUG/ERROR report

### Issue description
Testing for pull #1577 (thanks @laceysanderson) showed that using the debug level of the tripal logger did not print any messages.
It turns out that the debug level only provides output if the environment variable `TRIPAL_DEBUG` is set to `1`
This is behavior from Tripal 3, but is not documented except in the code.

So, has anybody used this, and is this behavior desirable? @laceysanderson and I think the debug function should always print something if you use it. Maybe the environment variable is better used to control toggling the backtrace output on or off? I am assuming you would only use the debug level during development, but maybe it is intended for a production site to allow toggling on and off?

If no one objects, I might propose to have the debug level default to printing output in Tripal 4. Maybe if no one responds, I will propose doing nothing 🙈

Regardless, this should be added to the docs. https://github.com/tripal/tripal_doc/issues/39

#### Steps to reproduce
Tripal 4 Testing as described in issue #1576 

In devel module php window execute this
```
$message_opts = [
  'drupal_set_message' => TRUE,
];
\Drupal::service('tripal.logger')->debug(
  'This next text should be substituted: "@fail".', 
  ['@fail' => 'testpassed'], 
  $message_opts
);
```

**Comment by laceysanderson** [comment]
> If no one objects, I might propose to have the debug level default to printing output in Tripal 4. Maybe if no one responds, I will propose doing nothing 🙈

I support the proposal to print by default for the debug logging level in Tripal 4.

I also support removing the environmental variable if no one responds as needing it. If someone does use this or we feel like being more cautious, I would suggest switching from an environment var to a config value saved in YAML.

**Comment by dsenalik** [comment]
The documentation pull request https://github.com/tripal/tripal_doc/pull/40 assumes that pull #1596 is merged, i.e. always print debug messages, so it does not mention the old environment variable `TRIPAL_DEBUG`

**Comment by laceysanderson** [comment]
Merged! Thanks @dsenalik <3
