### ISSUE TITLE
Feature request: Select multiple files for TripalImporter file upload

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#159]
I love the new TripalImporter!  We have a few cases where it would be nice to select multiple files for upload.

It's worth noting that supplying a directory in Server Path works as well, so you can switch to the TripalImporter class and direct users to supply a path for multiple files.

**Comment by spficklin** [comment]
I added a new $cardinality parameter to the TripalImporter class.  You can set this to be any  number of files you want to allow to be uploaded.  By default it will be 1.  If you want an unlimited number then set it to 0 in your class.  Can you test it?  Also, if I remember correctly it should give you as a result a set of file IDs separated by a '|' character when the form submits.

**Comment by spficklin** [comment]
Actually, I am incorrect with the IDs. I had to make some additional fixes.  Now, when you write your own importer there is a new 'files' entry in the arguments:

`$file_path = $this->arguments['files']`

You should be able to loop on those files to iterate through all those that were uploaded.  So disregard what I said above.

**Comment by spficklin** [comment]
Oh, you'll need to run a 'drush updatedb' to get all the proper fixes with the update.

**Comment by bradfordcondon** [comment]
Great!  Looks like it's working ok.

As a future improvement, it would be better if the file selector could allow shift-clicking instead of having to press the "upload file" button for each individual file for cases when you have hundreds of files.

(or, perhaps, allow specifying a directory if thats easier to implement)

**Comment by spficklin** [comment]
Yes, a shift-click would be nice, we can put that on our TODO list...

To clarify, you should be able to press the upload button at the very end after selecting your files and all of them get uploaded at once!
