### ISSUE TITLE
Better Debugging of ChadoStorage for Field Development

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#1594]
# Core Tripal 4 Development Task

## Branch Name: tv4g2-1594-debuggingChadoStorage

As we have been developing more fields, it's becomming apparent that ChadoStorage is too much of a black box at this point. For example, in cases where you've defined the properties as expected based on documentation but they still don't work --you just don't get your data... There is no way for you to see the queries created by chadostorage, get an idea of how chadostorage is processing your properties, etc. This basically means there is no way to debug your properties without adding debugging statements into chado storage yourself. This is not friendly to non-core developers... and since many extension module developers will be developing fields we need to fix this!

## Design

Create a debugging ChadoStorage trait to contain debugging specific functions. Where possible I will also put functions in a debugging TripalStorage trait if they are not specific to ChadoStorage.

Fields will be able to implement a debugging flag in the annotation and doing so will turn on the debugging trait. You can also turn on the debugging trait using chadostorage directly. Output will be both to the screen and to the watchdog log using the TripalLogger debugging level.

### Debugging Info to Provide

- [x] Report the complete SQL that chadostorage would execute.
- [x] Show simplified reporting of the contents of the property types, field definition and property values so you can confirm they match what you expected.
- [ ] Give hints when things are not present but are expected. This will be organically figured out in buildRecords() and may or may not be feasible. I will need to think on this one. We may be able to tell developers that if they provide a single store_link that they should also have additional properties expected for this type of link such as the store_pkey.

**Comment by laceysanderson** [comment]
Ok, I'm calling this done for now. It doesn't make suggestions but it is already very helpful IMO and prints a lot 😬 so I think I'll leave it here.

You can use the branch now, I'm just waiting to make a PR until I have time to document how to use it -for now it's bedtime!

If you are excited to try this before the PR is made, debugging is enabled for a field through the field settings UI. 
For example, for the organism field on the gene content type, you would 
1. go to Admin Toolbar > Tripal > Page Structure > Gene > Manage Fields. 
2. Then beside the organism field you would clicked edit. 
3. The field edit page now has a simple "Enable Debugging" checkbox. Select this and save. 
4. Now whenever you create, edit, load gene pages you will see a lot of debugging output. 
5. To disable once done, just uncheck the debugging checkbox and save.

Here is an example of loading a gene page:
![image](https://github.com/tripal/tripal/assets/1566301/7efc55fb-bd1b-4a62-9dc1-f30980fb67bf)

**Comment by dsenalik** [comment]
Closing as this was nicely done with merged PR #1604
