### ISSUE TITLE
Question about chado_node_sync_select_query usage

### ISSUE THREAD

**Issue by srobb1** [tripal/tripal#160]
I have question about using the hook_chado_node_sync_select_query()

I have created a custom module and am trying to sync select cvterms to create cvterm pages. I have successfully altered the sync form, now I want to apply my results from the sync form in a mymodule_chado_node_sync_select_query call. I am a bit confused and have not been able to find any examples. I want to incorporate the cv_id and organism_id from my form results in a specialized query. I have the query all worked out, but am not sure how to get my form results into mymodule_chado_node_sync_select_query. Can I add &$form_state as a argument to this function call? Or is there way that I have not noticed of supplying my sync form results into this query? 

Thanks!
Sofia

**Comment by bradfordcondon** [comment]
Hi Sofia,
Youre right, both the examples using this hook only pass in `null` for the where argument, not a variable one would retrieve from the form state.  I don't think you can pass the form state into the hook.

Is there some way to get the organism_id as part of your SQL query?  It only exists in the form state?

Can you elaborate a bit on what youa re trying to do in a broader sense?  Maybe there is a different approach.  Code would also help.

Cheers

Bradford

**Comment by srobb1** [comment]
Thank you for your reply Bradford,

I want to create nodes for only cvterms that are in the expression_cvterm table for a specific organism and cv library. 

In my sync form, I want to be able to select the cv library and an organism to use in a query for cvterms to sync.

here is the query i want to use:
```
SELECT  cvt.cvterm_id
          FROM {cvterm} cvt, {expression_cvterm} ec , {feature_expression} fe, {feature} f, {organism} o
          WHERE f.feature_id = fe.feature_id
           AND ec.expression_id = fe.expression_id
           AND ec.cvterm_id = cvt.cvterm_id
           AND cvt.cv_id = :cv_id
           AND f.organism_id = o.organism_id
           AND f.organism_id = :org_id";
 ```
The :cv_id and :org_id are values I retrieve from the sync form.


In case you want to see it, here is my cvterm_chado_sync_form:
```
function tripal_expression_cvterm_chado_sync_form($form, &$form_state) {

  $form = array();

  if (isset($form_state['build_info']['args'][0])) {
    $module = $form_state['build_info']['args'][0];
    $node_type = $form_state['build_info']['args'][1];
    $node_info = call_user_func($module . '_node_info');

    // If a linking table is set in the node_info array then use that,
    // otherwise ues the node_type as the linking table.
    if (array_key_exists('linking_table', $node_info[$node_type]['chado_node_api'])) {
      $linking_table = $node_info[$node_type]['chado_node_api']['linking_table'];
    }
    else {
      $linking_table = 'chado_' . $node_info[$node_type]['chado_node_api']['base_table'];
    }
    $args = $node_info[$node_type]['chado_node_api'];
    $form_state['chado_node_api'] = $args;
  }

  $form['linking_table'] = array(
    '#type' => 'hidden',
    '#value' => $linking_table
  );

  $form['node_type'] = array(
    '#type' => 'hidden',
    '#value' => $node_type
  );

  // define the fieldsets
  $form['sync'] = array(
    '#type' => 'fieldset',
    '#title' => 'Sync ' . $args['record_type_title']['plural'],
    '#descrpition' => '',
  );

  $form['sync']['description'] = array(
    '#type' => 'item',
    '#value' => t("%title_plural of the types listed " .
      "below in the %title_singular Types box will be synced (leave blank to sync all types). You may limit the " .
      "%title_plural to be synced by a specific organism. Depending on the " .
      "number of %title_plural in the chado database this may take a long " .
      "time to complete. ",
    array(
      '%title_singular' => $args['record_type_title']['singular'],
      '%title_plural' => $args['record_type_title']['plural']
    )),
  );



  // get the list of CV Libraries
  if ($args['sync_filters']['cv_id']) {
    $sql = "SELECT distinct cv.cv_id , cv.name
         FROM {cv} cv , {expression_cvterm} ec , {cvterm} cvt
         WHERE ec.cvterm_id = cvt.cvterm_id
          AND cvt.cv_id = cv.cv_id
          ORDER BY cv.name";
    $results = chado_query($sql);
    $libraries[] = '';
    foreach ($results as $library) {
      $libraries[$library->cv_id] = $library->name;
    }
    $form['sync']['cv_id'] = array(
      '#title' => t('CV Library'),
      '#type' => t('select'),
      '#description' => t("Choose the CV Library for which %title_plural types set above will be synced.",
      array(
        '%title_singular' => $args['record_type_title']['singular'],
        '%title_plural' => $args['record_type_title']['plural']
      )),
      '#options' => $libraries,
      '#default_value' => (isset($form_state['values']['cv_id'])) ? $form_state['values']['cv_id'] : 0,
    );
  }
  // get the list of CV Libraries


  // get the list of organisms
  if ($args['sync_filters']['organism_id']) {
    $sql = "SELECT distinct o.organism_id, genus, species, common_name
        FROM {feature_expression} fe , {feature} f , {organism} o
        WHERE fe.feature_id = f.feature_id
          AND f.organism_id = o.organism_id ORDER BY genus, species";
    $results = chado_query($sql);
    $organisms[] = '';
    foreach ($results as $organism) {
      $organisms[$organism->organism_id] = "$organism->genus $organism->species ($organism->common_name)";
    }
    $form['sync']['organism_id'] = array(
      '#title' => t('Organism'),
      '#type' => t('select'),
      '#description' => t("Choose the organism for which %title_plural types set above will be synced.",
      array(
        '%title_singular' => $args['record_type_title']['singular'],
        '%title_plural' => $args['record_type_title']['plural']
      )),
      '#options' => $organisms,
      '#default_value' => (isset($form_state['values']['organism_id'])) ? $form_state['values']['organism_id'] : 0,
    );
  }
  // get the list of organisms

  $form['sync']['button'] = array(
    '#type' => 'submit',
    '#value' => t('Sync ' . $args['record_type_title']['plural']),
    '#weight' => 3,
  );

  $form['cleanup'] = array(
    '#type' => 'fieldset',
    '#title' => t('Clean Up')
  );
  $form['cleanup']['description'] = array(
    '#markup' => t("<p>With Drupal and chado residing in different databases " .
      "it is possible that nodes in Drupal and " . strtolower($args['record_type_title']['plural']) . " in Chado become " .
      "\"orphaned\".  This can occur if a node in Drupal is " .
      "deleted but the corresponding chado records is not and/or vice " .
      "versa. Click the button below to resolve these discrepancies.</p>"),
    '#weight' => -10,
  );
  $form['cleanup']['cleanup_batch_size'] = array(
    '#type' => 'textfield',
    '#title' => t('Batch Size'),
    '#description' => t('The number of records to analyze together in a batch. If you are having memory issues you might want to decrease this number.'),
    '#default_value' => variable_get('chado_node_api_cleanup_batch_size', 25000),
  );
  $form['cleanup']['button'] = array(
    '#type' => 'submit',
    '#value' => 'Clean up orphaned ' . strtolower($args['record_type_title']['plural']),
    '#weight' => 2,
  );

  // Allow each module to alter this form as needed
  $hook_form_alter = $args['hook_prefix'] . '_chado_node_sync_form';
  if (function_exists($hook_form_alter)) {
    $form = call_user_func($hook_form_alter, $form, $form_state);
  }
  return $form;
}
```

**Comment by bradfordcondon** [comment]
I apologize, I haven't used this hook or the expression module/tables at all.
Hopeflly someone more central to Tripal can join us.

I have a stupid suggestion.  Are you sure `tripal_expression_cvterm_chado_sync_form` is properly hooking in?  I ask because i the hook to me looks like `chado_node_sync_form`: are you sure you arent missing the *node* between chado and sync?


Actually, looking at your code.  Did you use `chado_node_sync_form` as a starting point for your form?  I think that instead you want to hook into it.

That still doesn't solve the problem that you wont be able to pass the variable to your query... which makes me think you want to be approachin this problem from a different angle....

**Comment by srobb1** [comment]
Good Catch!! TYPO!! I forgot the 'node' part. Ok, I will try again and see what happens. I had some ideas last night on some things to try to get my query working.

**Comment by srobb1** [comment]
Ok, I almost have it. I hijacked type_id to hold my cv_id and retrieved the value from the original query before rewriting my select, joins, where_clauses, and where_args.  

I get records in my node table!! Yeah!! 

But I have one more issue. How do I get records in my linker table? I assumed that when nodes got entered into node table a corresponding record would be entered into the linker table. That isn't happening. I think I am missing something again.

Thank you again for taking the time to help. Your observation of my hook name helped me SOOOO much.

Thanks,
Sofia

**Comment by bradfordcondon** [comment]
Hi Sofia,

>How do I get records in my linker table? I assumed that when nodes got entered into node table a corresponding record would be entered into the linker table. That isn't happening. I think I am missing something again.

Looking at `function chado_node_sync_form_submit($form, $form_state) {`
...

```
 $module = $form_state['chado_node_api']['hook_prefix'];
    $base_table = $form_state['chado_node_api']['base_table'];
    $linking_table = $form_state['values']['linking_table'];
    $node_type = $form_state['values']['node_type'];

```
Can you confirm that your `$form_state` contains the right linking table upon submission (and everything else while we're at it?)

It defaults to `'chado_ ' . $base_table` if you dont supply a linking table.

While we're at it, which linking table?  Do you get records in the base table?

**Comment by srobb1** [comment]
Hi Bradford,

Everything looks correct to me.

```
chado_node_api (Array, 5 elements)
  base_table (String, 17 characters ) expression_cvterm
  hook_prefix (String, 23 characters ) chado_expression_cvterm
  linking_table (String, 23 characters ) chado_expression_cvterm
  record_type_title (Array, 2 elements)
    singular (String, 6 characters ) Cvterm
    plural (String, 7 characters ) Cvterms
  sync_filters (Array, 2 elements)
    type_id (Boolean) TRUE
    organism_id (Boolean) TRUE
```

As you can see my base table is expression_cvterm and I created a table called chado_expression_cvterm in the public schema. I made it manually. I plan to incorporate its creation into the install of my module, but have not gotten that far yet. Are there permissions that I need to change on tables? I have not been getting any errors in my postgres log about my linking table. I hope this is about permissions. That seems like an easy fix :)

**Comment by bradfordcondon** [comment]
If you made the table manually can you verify that the columns are correct?  vid nid expression_cvterm I guess from looking at the other node-entity linker tables in public, compare it to one of the existing linking tables....


I can verify that the issue isnt permissions unfortunately.  My bet is that the table isnt set up right or we aren't understanding the hook properly.

**Comment by srobb1** [comment]
Here is what I have:

```
drupal=# select * from public.chado_expression_cvterm;
 vid | nid | expression_cvterm_id | sync_date
-----+-----+----------------------+-----------
(0 rows)
```

Too bad!! Permissions seems like such a nice problem to have :)

**Comment by srobb1** [comment]
@laceysanderson @spficklin Maybe one of you might have an idea on what I should try next. To summarize, I created a custom module, which adds selected records of a new content type (chado_expression_cvterm) to the node table. This actually happens!! Yea!! 

@bradfordcondon has been super awesome in helping to get me to this point!

The issue I am having is that when the records are added to the node table I thought records would be added to my linking table (public.chado_expression_cvterm) but this does not happen. 

See previous comments to see the contents of chado_node_sync_form_submit chado_node_api and the columns of my public.chado_expression_cvterm table.

Is there a hook for adding records to the linking table? 


Thank you! Any hints, tips, ideas are greatly appreciated!
Sofia

**Comment by laceysanderson** [comment]
Hi Sofia,
Do you have this module up on github? I'll have a lot easier of time spotting the problem when I can see the context (and you might get additional tips while I'm at it ;-) )?

**Comment by laceysanderson** [comment]
When you implemented hook_node_info() did you add the chado_node_api keys as shown in this example: [chado_node_sync_form](http://api.tripal.info/api/tripal/tripal_core%21api%21tripal_core.chado_nodes.api.inc/function/chado_node_sync_form/2.x)?

**Comment by srobb1** [comment]
Hi Lacey,

I just put my [code](https://github.com/srobb1/tripal_expression_cvterm) up on github.  I very carefully went over the examples. I *believe* that I followed them to a 'T'. But I could have messed up something somewhere (quite likely).  

[Here](https://github.com/srobb1/tripal_expression_cvterm/blob/master/tripal_expression_cvterm.module#L85) is my set up of chado_node_api.

THANK YOU!!!!!

**Comment by laceysanderson** [comment]
My guess is simply that you haven't gotten far enough yet :-). The sync functionality uses the same hooks as when a node is created through the interface; however, you haven't yet implemented this functionality (likely because our documentation didn't make it clear enough that you needed to). Thus it's creating the node just fine but it has no association with chado because you have yet to tell it how to make that association.

Next steps: implement chado_expression_cvterm_form(), chado_expression_cvterm_validate(), chado_expression_cvterm_insert(). For an example see [tripal_example module implementation](https://github.com/tripal/tripal/blob/7.x-2.x/tripal_example/includes/tripal_example.chado_node.inc). See [this check](https://github.com/tripal/tripal/blob/7.x-2.x/tripal_example/includes/tripal_example.chado_node.inc#L383) in the example module? That checks to see if the record is being added via sync or the UI. Then [this section](https://github.com/tripal/tripal/blob/7.x-2.x/tripal_example/includes/tripal_example.chado_node.inc#L464) adds the linking record :-). Since you are mostly concerned with the sync right now your chado_expression_cvterm_insert() could look something like this (untested code):
```php
/**
 *  Implementation of hook_insert(). This function is called after the node is
 * inserted into the database. We need it so that we can insert appropriate
 * fields as provided by the user into the database. And so that we can link the
 * new Drupal node to the data in Chado via the chado_example linking table. We
 * can get to this function also during "syncing".
 * With syncing, however, the data already exists in Chado and we do not want
 * to try to re-add it. But we do need to add an entry to the chado_example
 * table to link the Drupal node with the data in the 'example' table of Chado.
 *
 *  This function is not required if the hook_node_info() does not define
 *  any custom node types.
 *
 * @ingroup tripal_example
 */
function chado_expression_cvterm_insert($node) {

  $expression_cvterm_id = '';
  // if there is an expression_cvterm_id in the $node object then this must be a sync so
  // we can skip adding the expression_cvterm as it is already there, although we do need
  // to proceed with insertion into the chado/drupal linking table.
  if (!property_exists($node, 'expression_cvterm_id')) {
    // Add code later to create expression_cvterm based on form.
  }
  else {
    $expression_cvterm_id = $node-> expression_cvterm_id;
  }

  // Make sure the entry for this expression_cvterm doesn't already exist in the
  // chado_ expression_cvterm table if it doesn't exist then we want to add it.
  // This is also how the linking record gets added during a sync.
  $check_org_id = chado_get_id_from_nid('expression_cvterm', $node->nid);
  if (!$check_org_id) {
    $record = new stdClass();
    $record->nid = $node->nid;
    $record->vid = $node->vid;
    $record-> expression_cvterm_id = $expression_cvterm_id;
    drupal_write_record('chado_ expression_cvterm', $record);
  }
}
```

### Suggestions that I don't think are causing your problems ;-):
- Looking at your chado_node_api you should change [this bit](https://github.com/srobb1/tripal_expression_cvterm/blob/e2eb4c0ac405c0b1e2869ab320cd649c13a853a7/tripal_expression_cvterm.module#L96) to:
```php
         'sync_filters' => array(
           'type_id'     => FALSE,     // expression_cvterm has no type_id
           'organism_id' => FALSE,     // expression_cvterm has no organism_id
         ),
```
- Also change [this line](https://github.com/srobb1/tripal_expression_cvterm/blob/master/tripal_expression_cvterm.module#L78) to `'name' => t('Expression CV terms'),` or something similar. This is the name of your node type in the UI.

**Comment by srobb1** [comment]
Great! I need to digest all of this, but I *think* I get it :) I will likely have more questions along the way.

Question about your suggestion about the sync filters. I want to use cv_id and organism_id in the selection of cvterms to sync. In the code I have now, I got the values for my sync query from the sync filters. If I set these to 'FALSE' how do I get cv_id and organism_id into the query?

**Comment by srobb1** [comment]
I have included the new chado_expression_cvterm_insert hook into my tripal_expression_cvterm.module.

I don't think my hook is being called.  I added a print statement, [here](https://github.com/srobb1/tripal_expression_cvterm/blob/master/tripal_expression_cvterm.module#L262), and I don't see it print to the screen when I run my job with drush. And another hint that it isn't running is that no records are added to my chado_expression_cvterm table.

**Comment by laceysanderson** [comment]
## Question about sync filters
Oh, I missed that. The API was designed with the intent that you wouldn't have to implement the sync form. That's why in hook_menu() it says to call chado_node_sync_form. Are you seeing the effects of changes in [chado_expression_cvterm_chado_node_sync_form](https://github.com/srobb1/tripal_expression_cvterm/blob/master/tripal_expression_cvterm.module#L113) because it shouldn't even be being called...

## chado_expression_cvterm_insert() not being called.
Try adding chado_expression_cvterm_form() as well? Are you seeing the validate print?

**Comment by srobb1** [comment]
**Question about sync filters**
I do in fact see my changes to chado_expression_cvterm_chado_node_sync_form. It looks like it definitely should be called [here](https://github.com/tripal/tripal/blob/de8a5bdbac42892d38dabdef503dfd310ace545b/tripal_core/api/tripal_core.chado_nodes.api.inc#L645)

**chado_expression_cvterm_insert() not being called.**
I added [chado_expression_cvterm_form](https://github.com/srobb1/tripal_expression_cvterm/blob/master/tripal_expression_cvterm.module#L322)() with a print statement, and still none from the 3 new hooks (insert, validate, form) are being called. 

I am naming them correctly right? $hook_prefix . "_insert"

**Comment by laceysanderson** [comment]
## Question about sync filters
Good call, missed that -sorry my brain is not fully recovered from childbirth yet :-p. In that case, you should be good to ignore my suggested changes to the sync filters.

## chado_expression_cvterm_insert() not being called.
Weird. You are naming them correctly. Have you cleared the cache multiple times? Maybe you also need chado_expression_cvterm_update() and chado_expression_cvterm_delete() (Drupal could be checking that all the hooks are implemented for a custom node before making it available). Can you check through the UI to see if your node type shows up under Administration toolbar > content > add content?

**Comment by srobb1** [comment]
**Question about sync filters**
I know what you mean!! Some days are worse than others for the brain :) Congratulations by the way! 

**chado_expression_cvterm_insert() not being called.**
- Yes, I tried clearing the cache a few times.
- Added chado_expression_cvterm_update(), no luck, this one isn't being called either.
- Added chado_expression_cvterm_delete(), no luck, this one isn't being called either.
- It is beautiful, my content type shows up in the list!!

I have updated my code in github.

**Comment by srobb1** [comment]
Maybe this info will spark some ideas:

I am probably missing some important hook.


**Functions used in tripal_example and used(bold) or not used(Strikethrough) in tripal_expression_cvterm**
-------------------------------------------------------------------------------

**tripal_example.module:function tripal_example_permission()**
**tripal_example.module:function tripal_example_menu()**
~~tripal_example.module:function tripal_example_views_api()~~
~~tripal_example.module:function tripal_example_theme($existing, $type, $theme, $path)~~
~~tripal_example.module:function tripal_example_help ($path, $arg)~~
~~tripal_example.module:function tripal_example_cron()~~
~~tripal_example.module:function tripal_example_form_alter(&$form, &$form_state, $form_id)~~
~~tripal_example.views_default.inc:function tripal_example_views_default_views()~~
~~includes/tripal_example.admin.inc:function tripal_example_admin_examples_listing()~~
**includes/tripal_example.admin.inc:function tripal_example_admin()**
**includes/tripal_example.admin.inc:function tripal_example_admin_validate($form, &$form_state)**
**includes/tripal_example.chado_node.inc:function tripal_example_node_info()**
~~includes/tripal_example.chado_node.inc:function tripal_example_node_access($node, $op, $account)~~
~~includes/tripal_example.chado_node.inc:function chado_example_form($node, &$form_state)~~
~~includes/tripal_example.chado_node.inc:function chado_example_validate($node, $form, &$form_state)~~
~~includes/tripal_example.chado_node.inc:function chado_example_insert($node)~~
~~includes/tripal_example.chado_node.inc:function chado_example_update($node)~~
~~includes/tripal_example.chado_node.inc:function chado_example_delete($node)~~
~~includes/tripal_example.chado_node.inc:function chado_example_load($nodes)~~
~~includes/tripal_example.chado_node.inc:function tripal_example_node_presave($node)~~
~~includes/tripal_example.chado_node.inc:function tripal_example_node_insert($node)~~
~~includes/tripal_example.chado_node.inc:function tripal_example_node_update($node)~~
~~includes/tripal_example.chado_node.inc:function tripal_example_node_view($node, $view_mode, $langcode)~~
~~includes/tripal_example.chado_node.inc:function chado_example_chado_node_default_title_format()~~
~~includes/tripal_example.chado_node.inc:function chado_example_chado_node_default_url_format()~~


**Functions not in tripal_example but are being used in tripal_expression_cvterm**
------------------------------------------------------------------------------------

function chado_expression_cvterm_chado_node_sync_form($form, &$form_state)
function chado_expression_cvterm_chado_node_sync_create_new_node($new_node, $record)
function chado_expression_cvterm_chado_node_sync_select_query($query)

**Comment by laceysanderson** [comment]
The hooks needed for a custom node type (ones you're missing are crossed out):
- includes/tripal_example.chado_node.inc:function tripal_example_node_info()
- ~~includes/tripal_example.chado_node.inc:function tripal_example_node_access($node, $op, $account)~~ (not sure if this one is required since I've always needed it ;-) )
- includes/tripal_example.chado_node.inc:function chado_example_form($node, &$form_state)
- includes/tripal_example.chado_node.inc:function chado_example_validate($node, $form, &$form_state)
- includes/tripal_example.chado_node.inc:function chado_example_insert($node)
- includes/tripal_example.chado_node.inc:function chado_example_update($node)
- includes/tripal_example.chado_node.inc:function chado_example_delete($node)
- ~~includes/tripal_example.chado_node.inc:function chado_example_load($nodes)~~
For your module replace `tripal_example` with `tripal_expression_cvterm` and `chado_example` with `chado_expression_cvterm `.

My next step would be to make a simple form in hook_form() that provides the expression_cvterm_id via a textfield. Then test that the correct functions are being called and the link created through the interface. That way you can ensure the code in hook_insert() is working... Also, perhaps you need hook_load() at this point as well. The Drupal magic happening in between hook calls is not well documented and I've always just implemented all the above hooks at once with dpms.

**Comment by srobb1** [comment]
Ok, probably a silly question, but where can I find the form that I create with hook_form()?

**Comment by srobb1** [comment]
I think I know, When I edit the entry from the contents page, or add a new content type of my type. If this is true, I do not see my fields, only the default body field.

**Comment by srobb1** [comment]
BTW, I added:
- hook_access()
- hook_load()

**Comment by srobb1** [comment]
Ok, a little bit of progress. I just added tripal_expression_cvterm_form_alter() and removed the body like in the tripal_example. My print statement "I am here: tripal_expression_cvterm_form_alter" appears in the top of my browser and I don't have body in my newly added record! So this hook is working! Yeah! It isn't really accomplishing anything with my main issue, but at least I know I can make something work!

But none of my other newly added hooks are being called, and still no entries in my linking table.

**Comment by srobb1** [comment]
I added tripal_expression_cvterm_node_presave() and it gets called!!
But something weird, is I added this print statement:

`
print "I am here: tripal_expression_cvterm_node_presave\n";
`

and this get printed in the terminal when I run my job with drush:

<pre>
I am here: tripal_expression_cvterm_node_presavey: 41,296,728 bytes.  
I am here: tripal_expression_cvterm_node_presavery: 42,237,312 bytes.
</pre>

Where are the 'y' and 'ry' tacked onto the 'presave' coming from??? 

btw, I think it is printed 2x because I have 2 terms syncing.

**Comment by laceysanderson** [comment]
All of the hook_node_X() functions will be called for all node types (not just your custom one) so unfortunately that doesn't help you. The same is said for hook_form_alter() which is called for all forms. I'm just starting up my Tripal2 dev site and then I'll install your module and see if I can see what's going on. It seems like your node type is not being detected properly by the drupal magic which is hard to describe how to debug ;-p

PS. [node type]_form should be seen at Admin > Content > Add Content > [Node Type]

**Comment by srobb1** [comment]
If you are installing my module, warning, I have not tested any of the code in tripal_expression_cvterm.install 

- I made my linking table with the tripal custom table tool and then in psql altered the schema to public.
- I created my content type manually in the structure->Add content type.

One of these might be why my code isn't working...

**Comment by laceysanderson** [comment]
Ahhh! Neither is good... The custom table tool creates tables in the chado schema whereas your linking table needs to be in the public schema. Also hook_node_info should programatically create the content type so if you did it manually there will be a conflict. Personally, I would start with a clean development site...

### Good News
When I installed your module it created the linking table correctly due to your code in hook_schema() so that is working 👍  Also, I can see the content type at Admin > Content > Add Content (Called "example" b/c you have yet to change [this line](https://github.com/srobb1/tripal_expression_cvterm/blob/master/tripal_expression_cvterm.module#L78)) and when I click to add it, I see your form fields due to hook_form() as well as the print from hook_form() and hook_form_alter().

**Comment by srobb1** [comment]
Oh Good!  That is great news. 

As an aside: I did change the schema to public on my linking table because I saw it was in chado. But, if it get created...

Yeah, happy that you tested my hook_schema for me :) I had not tested it yet.

Yeah, yeah, you told me to change it, but I got side tracked :)

Okay, let me know when what happens when you try to sync something.

I have a bulk loader template for adding images to the expression module and a bulk loader for adding cvterms to feature_expression and expression_cvterms. I will add them to my repo when my dev server comes back online. Something happened and it is down. Our IT is looking into it.

**Comment by laceysanderson** [comment]
I made some quick changes for testing: https://github.com/laceysanderson/tripal_expression_cvterm
Basically, commented some things out, removed a few functions and changes prints to drupal_set_message() since I find it works better for testing (you won't always see all prints through the UI).

I was able to confirm that your form, insert, update, load and delete are all being called when explored through the UI. Unfortunately, testing the sync is much harder for me since I have no test data of this type (really none at all in my current test site ;-p ) and my baby has woken up so I'll have to take a break... I'll let you try testing on a clean dev site to see if your code works now *fingers crossed*.

**Comment by srobb1** [comment]
Thank you. I will let you know how it goes!

**Comment by srobb1** [comment]
I know you said fresh install, but that requires a lot of work with my IT to get a new VM.

So, deleted my linker table, deleted all nodes of my content type, deleted my content type, uninstalled and moved my module out, cloned your version, changed 'example' to my content type like you said, and activated the module. I cleared the cache in between some of the events.

My content type gets created and I can see the form with my fields.
My Sync form looks like it should.
But, I do not get my linking table created and therefore my sync fails.

What did I miss when I was cleaning up? (I know it would be better to get a fresh install)

**Comment by srobb1** [comment]
Is the hook_schema supposed to be $hook_prefix . "_schema" ? or $module_name . "_schema"?

Mine is called tripal_expression_cvterm_schema()

**Comment by laceysanderson** [comment]
Yours is named correctly 👍 . Unfortunately I have no idea what you missed cleaning up :-(

Another idea:
Do you have permission to create new databases on your VM? If you do, simply drop the database -this effectively gives you a clean install since almost everything for your drupal site is stored in the database. You then start at [this point in the Tripal2 install guide](http://tripal.info/tutorials/v2.x/installation/drupal) and recreate the database, ignore the downloading files part and install through the browser.

**Comment by srobb1** [comment]
Ok. 
- My linking table gets created!!! This is a step in the right direction!
- I get records in my node table
- I see my content type and the insert/edit form with the fields I created in the hook
- I get **NO** records in my linking table :(
- I get these two checks printing when I run my job:
      - I am here: chado_expression_cvterm_validate 
      - I am here chado_expression_cvterm_insert
- I see these checks two checks in the browser when I access the form:
      - I am here: chado_expression_cvterm_load
      - I am here: chado_expression_cvterm_form

**Comment by laceysanderson** [comment]
Nice! So close! That means the problem is either in the if statement creating the linking record or in the SQL pulling out the records to be sync'. I would check in the _insert() to make sure the variables contain what they're supposed to.

**Comment by bradfordcondon** [comment]
Thanks for stepping in Lacey, I have no experience with any of these hooks so great learning experience for me too.   PS Jealous of your baby time, enjoy and thanks for making time for us.

**Comment by laceysanderson** [comment]
No problem 👍  It helps to keep my brain working. Plus I get bored during baby naps ;-)

Might the problem be as silly as a misplaced space during copy/paste? It looks like there's a space before expression_cvterm_id in both [this line](https://github.com/srobb1/tripal_expression_cvterm/blob/master/tripal_expression_cvterm.module#L271) and [this line](https://github.com/srobb1/tripal_expression_cvterm/blob/master/tripal_expression_cvterm.module#L282) (after the `->`).

**Comment by laceysanderson** [comment]
Also, Sofia I added my changes as a pull request so that if you want them you can just click the merge the button and keep working with your own repository. It will make downstream changes easier this way ;-)

**Comment by srobb1** [comment]
I noticed that this morning when my little guy was having breakfast. He insists that I sit right next to him, so I was going over the code on my phone. I saw that space! 

I will get the code all fixed up and try it out, I know it will work this time.

Yes thank you for helping out. I really appreciate your time. And if you need more brain teasers, I am sure I could give you a steady list. Just let me know next time your are bored during nap time ;)

**Comment by srobb1** [comment]
Yes! It did work! Finally!

THANK YOU @laceysanderson and @bradfordcondon !!!!!

**Comment by laceysanderson** [comment]
Yay! 👍  Ironically I also saw the space while sitting beside my older son who insists I sit right next to him at breakfast while he watches cartoons & ignores me ;-)

**Comment by srobb1** [comment]
That is exactly!!! the same with me!!

**Comment by spficklin** [comment]
Thanks @bradfordcondon and @laceysanderson!
