### ISSUE TITLE
Bug in GFF Loader

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1602]
# BUG/ERROR report

### Tripal Version:
* Drupal Version:  9.x
* PostgreSQL Version:  15.1
* PHP Version:  8.1

### Issue description

The GFF3 loader works but has two issues that will cause problems.

1.  When submitting the form, if the user enters the 'Default Landmark Type' and allows the autocompleteo work then it will submit the value with the ontolgoy term Id (e.g. "chromosome (SO:0000340)").  This breaks the loader as it seesm to want just the term name (e.g. "chromsome").  If you just put the term name it works fine.  
2.  The alignment species target drop-down does not have an empty value, therefore, it defaults to the first species in the list.   I think it should be empty at first so that the user can set it or not.  

#### Steps to reproduce

1. Simply use the automplete when setting the landmark type.  If you download the MSU rice genome it doesn't have the chromosome as features so you have to enter the landmark type to force it to creat them.  You can downloa this from here:  http://rice.uga.edu/pub/data/Eukaryotic_Projects/o_sativa/annotation_dbs/pseudomolecules/version_7.0/all.dir/ (Download the `all.gff3` file).
2. For the alignment target that just something to observe in the form.

**Comment by dsenalik** [comment]
@risharde this is kind of my fault, I forgot to fully integrate the new cvterm select, I only did it for the validation, not for the run. I already see what to do!

**Comment by laceysanderson** [comment]
@dsenalik does this mean we have similar issues that we missed in the FASTA importer too as it was included in the cvterm autocomplete PR? 🤔

**Comment by dsenalik** [comment]
Excellent question, I was going to investigate that but other tasks intruded

**Comment by dsenalik** [comment]
Looks like I did add the necessary code to the fasta loader 😄

**Comment by risharde** [comment]
@dsenalik @spficklin thanks for the tag! Okay so I think I'll await Doug's fix for autocomplete? Alternatively as a 'hotfix' we could remove the (value) part within the loader code depending on the timing of your fix Doug?

**Comment by dsenalik** [comment]
@risharde  My PR is ready for review!

**Comment by dsenalik** [comment]
Resolved with merged PR #1603
