### ISSUE TITLE
Tripal 4: Tripal Display Suite & Field Group usage

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal#1615]
# Core Tripal 4 Development Task

In order for us to provide a familiar look and feel to content pages, we can continue to use the Display Suite and Field Group modules as we have in Tripal 3.
This is just an issue to mark that development will begin on the Tripal 4 version of the Tripal DS module. For now, the plan is to have this module live within Tripal core but not necessarily be required. If this is unsuitable, please indicate so in the comments.

After a brief investigation period, it seems that the current Field Group and Display Suite (5.x) modules are compatible with Tripal content types. The purpose of the Tripal DS module would be to provide default templates for users. These templates would follow the templates used in Tripal 3.

## Branch Name: tv4g7-issue1615-t4_display_suite

**Comment by Ferrisx4** [comment]
We may be able to leverage this module to provide an additional layout that is more friendly to assistive technology or to design our default template with this in mind, see https://github.com/tripal/tripal/issues/1227

**Comment by spficklin** [comment]
Just a note.  We may be able to use the built-in Drupal 10 Layout Builder module to create default layouts for Tripal 4 contnet types.   We can then use these two extension modules to provide styles (classes) that can be associated with layouts and the asset injector module to add CSS/JS inline without having to edit any template or config files.  

https://www.drupal.org/project/layout_builder_styles
https://www.drupal.org/project/asset_injector

There is also a way to create built-in layouts as part of a module:  https://www.drupal.org/docs/drupal-apis/layout-api/how-to-register-layouts

**Comment by spficklin** [comment]
Just FYI... I've started working on this on branch `tv4g7-issue1615-default_layouts`

**Comment by spficklin** [comment]
Now that we have a solution for layouts, merged and described on PR #1792 and a list of TODOs on issue #1794 I'm going to close out this issue.
