### ISSUE TITLE
Tripal Importer class doesn't validate if a remote filepath exists

### ISSUE THREAD

**Issue by carolyncaron** [tripal/tripal#1629]
### Tripal Version

4.x

### Drupal Version

10.0.11-dev

### PostgreSQL Version

The tripaldocker version

### PHP Version

8.1.22

### Branch

tv4-issue1629-importer-file-validation
Pull #1630 

### General Description

I am trying to create a custom Tripal Importer and during testing, I entered something random for the remote path:

<img width="818" alt="Screen Shot 2023-09-08 at 3 29 06 PM" src="https://github.com/tripal/tripal/assets/7927760/840d6b70-22bc-4cbf-ab54-bfcdfa906182">
And the job was submitted successfully. 

Here is the relevant section of the annotation for my new importer class:
```
file_upload = True,
file_load = True,
file_remote = True,
file_required = True,
```

Let me know if any more information or context would be helpful!

### Steps to reproduce

I checked if this issue can be reproduced using one of the existing Tripal Importers. Steps I did to repeat this for the FASTA Importer:

1.   I modified "file_remote" and "file_required" to be True in `tripal/tripal_chado/src/Plugin/TripalImporter/FASTAImporter.php`
2. Cleared the cache using `drush cr` to have the Remote path option show up in the form
3. Created an organism and an analysis, if none existed already, and selected these in the dropdowns in the form
4. Entered the same nonsensical `lalalalalalalalala` as before as the Remote path and submitted the form

Interestingly, I get an error this time, but my job also gets submitted:

<img width="1008" alt="Screen Shot 2023-09-08 at 4 09 21 PM" src="https://github.com/tripal/tripal/assets/7927760/46574dce-8767-45a5-b3c3-b40e9ea9dc52">

**Comment by dsenalik** [comment]
I confirm this happening with the FASTA importer
The tripal 3 FASTA importer includes server path and remote path, so we should definitely add that
_i.e._ in addition to your testing changes, need to also add ` *    file_local = True,`

So, the validation in `tripal_chado/src/Plugin/TripalImporter/FASTAImporter.php` needs some fixes to handle this...

**Comment by laceysanderson** [comment]
I've been digging in the base tripal importer class and we will actually want to add the validation for files there so all importers benefit. This should affect the GFF3 importer as well 😬 Specifically, we'll want to add the validation here: https://github.com/tripal/tripal/blob/4.x/tripal/src/Form/TripalImporterForm.php#L234-L261

**Comment by dsenalik** [comment]
Validation is added. It is a bit tricky to validate the remote file, to do so we have to actually try reading it, or at least the headers. Any my stupid home internet intercepts invalid URLs and redirects to a "helpful" search page. I have tried to add a simple check for this. But most people's "real" sites will not have this problem.

Now I need to test and fix the importers, as they have never been tried with remote files in Tripal 4 since it wasn't an option before. There's some old tripal 3 logging to be upgraded. I'll set up a pull request when that is done.
