### ISSUE TITLE
Tripal 4 Pub Importer

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#1631]
### Task Description

Publication Importer development - more will be posted as progress occurs.

### Branch Name

tv4g4-1631-Pub-Importer

**Comment by dsenalik** [comment]
@rish, be aware of what I did for #1461 branch tv4g4-issue1461-pub_importer.
My work so far was 100% on the forms and ajax callbacks and such, I never got to the actual importing code, I got stuck on the second-level ajax callback, then we had design discussions https://github.com/tripal/tripal/issues/1595#issuecomment-1660694700
Now that the National Ag Library importer is dead (Issue #1628) for the foreseeable future, maybe you want to just make this a single standalone PubMed importer and avoid the first level of ajax callbacks?
![ajax-1](https://github.com/tripal/tripal/assets/8419404/daf3937d-a987-4b8b-aaec-0e422a851df5)

**Comment by risharde** [comment]
@dsenalik thanks for messaging in about this! Stephen mentioned to me to get in contact back with you - maybe I can use your code since this is the way Stephen thinks is the best way going forward. I'll try to load in your branch and see what you were able to complete and try to build upon that, will try to keep you updated! Thanks for the heads up!

**Comment by laceysanderson** [comment]
Closing as a duplicate. Discussion moved to https://github.com/tripal/tripal/issues/1461#issuecomment-1724540500.

@risharde  you can use your same branch if you want but please continue all discussion in #1461
