### ISSUE TITLE
Hooking into Bundle Forms

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#164]
Hello,

We are wondering if there is a way to hook into the bundle create form to alter the form. For example, when creating a new Gene, we'd like to alter the options of the organisms field programmatically by running an SQL query. Since running SQL is not possible through the GUI, we'd need a way to do this programmatically.

This is most useful to us when modifying fields that Tripal Bundles automatically create using the tripal_create_bundle function. Currently, we can't find a way to alter the form without creating a full blown TripalField to do a simple task.

Does a hook already exists that we can use to alter the form?

Thanks!

**Comment by spficklin** [comment]
The form that appears for a bundle (i.e. Content type) is generated by the collection of fields attached to the bundle.  So, if you want to alter the form for a specific field (e.g. the organism) then you have to create a new widget for that field.  In Tripal we have abstracted the Drupal hooks for working with fields into three classes:  TripalField, TripalFieldWidget and TripalFieldFormatter.  If you are not changing what get's loaded/written to the database by a field and you just want the form for field to be more dynamic then you can implement a new TripalFieldWidget class that does what you want.  Then go into the content management page on your site and change the default widget to be the new one you created.

**Comment by almasaeed2010** [comment]
Ok this makes sense. Thanks for the explanation!

**Comment by spficklin** [comment]
FYI... a new commit was just added to allow you to add your new field classes to sites/all/libraries/TripalFields if you don't have a module.  So if you want a new organism widget you can either place it in a custom module in the includes/TripalFields directory. Or, if you don't have a module you can place it in the libraries folder.
