### ISSUE TITLE
Tripal Content Listing is VERY SLOW when you have lots of content

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#1647]
### Tripal Version

4.x

### Drupal Version

9+

### PostgreSQL Version

n/a

### PHP Version

n/a

### General Description

Currently the more Tripal content you add to `admin/content/bio_data` the slower it gets... to the point it will time out. This page is generated by [TripalEntityListBuilder](https://github.com/tripal/tripal/blob/4.x/tripal/src/ListBuilders/TripalEntityListBuilder.php) which extends Drupal's core EntityListBuilder. 

The Drupal inherited methods of this class, load the entire entity for each and every one. I assume this is because Drupal core deals with smaller data and has more performance enhancements / caching for their fields then we do. However, it is completely unnecessary to load all the fields!

We need to override this bit of core Drupal functionality (should just be extending a specific method) to ensure we only load fields who are used as tokens in the title/URL. This will also likely need changes to TripalStorage so that we can indicate during load if we want a partial or full load.

Note: Some of the functionality for figuring out which fields/properties to load is in TripalTokenParser.

### Steps to reproduce

Add 20+ entries and you will start to notice the slow down if not earlier. This will be a really big problem once publishing is ready...

**Comment by spficklin** [comment]
I'm here the night before the Codefest and itching to get this alpha release done.  @laceysanderson I'm not sure where you're at with this one. I'm going to work on it. If you've started let me know.

**Comment by spficklin** [comment]
branch name: `tv4g2-issue1647-slow_content_listing`

**Comment by laceysanderson** [comment]
I haven't started this yet but essentially my plan was to
1. Add a tag to TripalEntity to indicate partial loading
2. When that tag is set the entity::postLoad would know not to invoke the various storage backends. Instead only the Drupal information would be loaded.
3. Override the [load](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Entity%21EntityListBuilder.php/function/EntityListBuilder%3A%3Aload/10) in our entity list builder to ensure that we indicate the tag for the entities on loading.

**Comment by spficklin** [comment]
This is similar to what I did.  I'm not sure what you mean by tag but I used a session variable.  PR is forthcoming.

**Comment by spficklin** [comment]
Fixed with PR
