### ISSUE TITLE
Request to support additional abbreviations for infraspecific ranks

### ISSUE THREAD

**Issue by carolyncaron** [tripal/tripal#1648]
### This feature attempts to solve an existing problem

None

### I am open to developing or collaborating on an extension module if this is not a good fit for Tripal Core

No

### Is this feature urgent?

No

### Description

I am developing an importer for germplasm accessions, and while writing documentation I noticed a slight discrepancy between the infraspecific ranks that are listed in the Multi-Crop Passport Descriptors (MCPD) (see here: https://www.genesys-pgr.org/documentation/basics#mcpd-descriptors) and by this function: https://github.com/tripal/tripal/blob/4.x/tripal_chado/src/api/tripal_chado.organism.api.php#L495

Specifically, the MCPD descriptor **Subtaxa** lists "convar. (for convariety)" and "Group (for cultivar group)" so it would be nice to have these supported by Tripal, as well. :smile:

### Your specific use case

Current documentation on file format supported by my module (in progress 😜 Subtaxa is column 5): https://github.com/TripalCultivate/docs/blob/master/_docs/curation/germplasm-data.md#file-format

### Additional information/screenshots

MCPD is used by Bioversity (Valentin) and BrAPI which is why we care what they list for infraspecific ranks

**Comment by dsenalik** [comment]
Carolyn, is this for Tripal 3, Tripal 4, or both?
It should be an easy thing to add, I am just wondering if it needs to be backported to Tripal 3 also.

**Comment by carolyncaron** [comment]
Sorry, it is for Tripal 4! 😅 Our group specifically won't need it to be backported to Tripal 3

**Comment by dsenalik** [comment]
Carolyn, check pull #1649 and see if this fits your needs
