### ISSUE TITLE
Feature Request: Tripal Pane Browser History

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#165]
Hi,

Recently we encountered a situation with Tripal Panes where we needed a specific pane to be auto displayed if the pane had paginated content and the user requested a page other than the first. We are not sure if a solution for this has already been implemented, but we'd be happy to help create it if it hasn't been created yet.

I'd propose using [browser history](https://developer.mozilla.org/en-US/docs/Web/API/History_API), which is now supported by all major browsers, along with simple url query parsing to implement this. If you agree this solution would work, I wouldn't mind implementing it.

Thanks!

**Comment by spficklin** [comment]
Ah... thanks for noticing this issue.  I'm looping in @shawnawsu so we can talk on this one.

**Comment by bradfordcondon** [comment]
Hi @spficklin @shawnawsu  @almasaeed2010 

Bumping this issue, another situation arose on HWG where we wish we had this feature.  When Elasticsearch fails, we want to reload the page and have the elasticsearch box open with a "no results found" message. Very disorienting for the entity to reload in its starting configuration instead of with the elasticsearch pane open.

**Comment by almasaeed2010** [comment]
Hello all,

I think the best solution for this is if we can somehow pass the tripal pane information (html ids and classes of the container pane) to the field formatter one way or another. Is this possible?

Thanks!

**Comment by bradfordcondon** [comment]
@almasaeed2010 I *think* this is resolved as we can keep panes open.  Is it?

**Comment by almasaeed2010** [comment]
Hi! I don't think this has been resolved yet on core. We do implement our own workaround but it works only on our site. Also, the fields that we developed work but the ones we didn't won't work (for us) so we still need an implementation on the core side that makes it consistent across sites.

Thanks!

**Comment by bradfordcondon** [comment]
oops thanks for the clarification.  Moving this out of Q&A and into the backlog.  I think the need for this is self-evident without PMC voting as a new feature, its more of a bug fix (ah which stephen already labeled as).

**Comment by bradfordcondon** [comment]
Discussing with @spficklin 

"If you use AJAX this isnt a problem"

So the tripal field has coding that allows you to do paging via AJAX.  Its in the base field and/or the formatter.


We're going to add documentation.  Then we'll check with @almasaeed2010 and see if thats good enough or if it still should be added somehow to core.

**Comment by almasaeed2010** [comment]
I've used the AJAX paging before and it does work 👍 we just have to make sure all fields implement this method. I still would recommend adding basic browser history support, which would allow users to share an open tab simply by sharing the link. I've implemented this for HWG and can easily port over to tripal ds if desired.

Here is an example of what I mean. Results for gene search in an organism page can be shared:

https://hardwoodgenomics.org/organism/Fraxinus/excelsior?search_term=IPR020575&tripal_pane=group_feature_search&organism=Fraxinus%20excelsior

**Comment by spficklin** [comment]
I removed the bug tag because this isn't a bug, the AJAX-enabled pager exists to handle the underlying problem.  I have submitted a pull request that provides new documentation that describes how to add an AJAX-enabled pager to a field formatter.  For now I think that should satisfy the need.

@almasaeed2010 and @bradfordcondon I don't quite understand the browser history solution nor the exact problem with ElasticSearch not opening the page the way you want.  If you both would like to look more at the browser history perhaps we should open a new issue to get a clean discussion on it?

**Comment by almasaeed2010** [comment]
Hello @spficklin 

Currently, when visiting a page, the summary pane shows up by default. If I click on any other tab, such as `sequences` on a Gene page, the pane is displayed and brought to the top. If I then copy the link to share it, the link will show only the summary pane again and more navigation has to be done to get to the sequences tab. With the browser history solution, when the URL is shared it will auto open the pane.

We currently have the solution implemented in HWG where the link I shared auto opens the feature search tab instead of the summary tab: https://hardwoodgenomics.org/organism/Fraxinus/excelsior?search_term=IPR020575&tripal_pane=group_feature_search&organism=Fraxinus%20excelsior

If this behavior is wanted in `tripal.js`, I can port over the functionality for consideration.

Thanks!

**Comment by spficklin** [comment]
Oh, I understand now.  Thanks for the explanation. Yes, I think this is a good thing.  I approve of this feature being added.

**Comment by laceysanderson** [comment]
I approve as well!

**Comment by spficklin** [comment]
@almasaeed2010 .  I just did a quick read through of this again.  Is this still being worked on?

**Comment by almasaeed2010** [comment]
Hello @spficklin unfortunately the solution isn't suitable for all cases and I couldn't figure out a way to make it more general. So perhaps we should mark this as `Maybe Later`.

**Comment by almasaeed2010** [comment]
For reference if anyone is interested, this is how we re-implemented TripalDS to save the state.

```javascript

$(function () {
    function TripalDS() {
      this.init();
      this.openDefaultPane();
    }

    /**
     * Initiate TripalDS.
     */
    TripalDS.prototype.init = function () {
      var links = $('.tripal_pane-toc-list-item-link');
      var _that = this;

      links.each(function () {
        var id = '.tripal_pane-fieldset-' + $(this).attr('id');
        if ($(id).length === 0) {
          $(this).parents('.views-row').first().remove();
          return;
        }

        if ($(id).children().not('.field-group-format-title').text().trim().length === 0) {
          $(this).parents('.views-row').first().remove();
        }
      });

      links.unbind('click');
      links.on('click', function (e) {
        e.preventDefault();

        // Add active class to the element that was just clicked
        $(this).parents('.ds-left')
            .find('.tripal_pane-toc-list-item-link.active')
            .removeClass('active');
        $(this).addClass('active');

        var pane = $('.tripal_pane-fieldset-' + $(this).attr('id'));
        if (pane.is('.hideTripalPane')) {
          $('.tripal_pane').not('.hideTripalPane').addClass('hideTripalPane');
          pane.removeClass('hideTripalPane');
          var event = $.Event('tripal_ds_pane_expanded');
          $(this).trigger(event);

          var id = $(this).attr('id');
          _that.pushToHistory(id);
          $('input[type="hidden"][name="tripal_pane"]').attr('value', id);
        }
      });
    };

    /**
     * Show the pane that's selected in the url.
     */
    TripalDS.prototype.openDefaultPane = function () {
      var params = this.getURLParameters().filter(function (param) {
        return param.name.toLowerCase() === 'tripal_pane';
      });

      var pane_id = params.length > 0 ? params[0].value : null;

      if (!pane_id) {
        // We are done here
        return;
      }

      // Find the wanted pane and its link
      var $pane_link = $('#' + pane_id);

      if (!$pane_link || $pane_link.length === 0) {
        if (window.console) {
          console.warn('Given pane id does not exist: ' + pane_id + '. Please check the url for more info.');
        }

        return;
      }

      // Disable the active link
      $('.ds-left')
          .find('.tripal_pane-toc-list-item-link.active')
          .removeClass('active');

      // Hide the active pane
      $('.ds-right .showTripalPane').removeClass('showTripalPane').addClass('hideTripalPane');

      // Click the link!
      $pane_link.trigger('click');
    };

    /**
     * Get the URL params
     *
     * @return {Array}
     */
    TripalDS.prototype.getURLParameters = function () {
      // Check browser href for a pane to open
      var params = window.location.search;
      if (params.length > 0) {
        // remove the "?" char
        var qIndex = params.indexOf('?');
        if (qIndex !== -1) {
          params = params.slice(qIndex + 1, params.length);
        }

        // split it into array
        return params.split('&').map(function (param) {
          var broken = param.split('=');
          if (broken.length === 2) {
            return {
              name: broken[0],
              value: broken[1]
            };
          }
          else if (broken.length === 1) {
            return {
              name: broken[0],
              value: null
            };
          }
          else {
            return null;
          }
        });
      }

      return [];
    };

    /**
     * Push the new state to history
     *
     * @param {String} id The id of the pane's link
     */
    TripalDS.prototype.pushToHistory = function (id) {
      var params = this.getURLParameters();
      var added = false;
      for (var i = 0; i < params.length; i++) {
        if (params[i] && params[i].name === 'tripal_pane') {
          params[i].value = id;
          added = true;
        }
      }

      if (!added) {
        params.push({
          name: 'tripal_pane',
          value: id
        });
      }

      var query = [];
      for (i = 0; i < params.length; i++) {
        var param = params[i];
        query.push(param.name + '=' + param.value);
      }

      query = query.join('&');

      if (window.history) {
        var state = window.history.state;
        var title = document.title;
        var path = window.location.pathname;
        window.history.replaceState(state, title, path + '?' + query);
      }
    };

    return new TripalDS();
  });

```

The issue with this solution is that there is no way for the PHP side in field formatters to know about the ID of the pane. Not to my knowledge at least. So, creating links to the pane from php becomes a bit hard and would require hardcoding the ID `?tripal_pane=MY_ID`.

**Comment by spficklin** [comment]
Okay Thanks for the update @almasaeed2010 !
