### ISSUE TITLE
Disable submit button in Importer

### ISSUE THREAD

**Issue by reynoldtan** [tripal/tripal#1652]
### This feature attempts to solve an existing problem

No

### I am open to developing or collaborating on an extension module if this is not a good fit for Tripal Core

No

### Is this feature urgent?

Yes

### Description

We have implemented the Tripal Importer Plugin in our module using Accordion layout where each header is a stage and each stage has to be completed in order to proceed to the next stage. We would like to be able to disable the Submit button on importers based on variable in the form state until a user is in a particular stage.

![image](https://github.com/tripal/tripal/assets/15472253/26fdbc1b-e02a-4a73-964e-eac2ef0434ae)

### Your specific use case

n/a

### Generally Applicable

n/a

### Additional information/screenshots

n/a

**Comment by laceysanderson** [comment]
Working on this in branch `tv4g4-issue1652-disableSubmit`.
