### ISSUE TITLE
Setting annotation for Tripal Importer Form file_upload to false still causes validation to require a file upload

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#1658]
### Tripal Version

4.x

### Drupal Version

9.x

### PostgreSQL Version

9

### PHP Version

8.1.3

### General Description

Currently working on the Pub Importer forms, we set the initial pub importer annotation to file_upload = FALSE.
However I was not seeing the formSubmit() function being called and noticed the error 'You must provide a file location or upload a file.'

I've tried to naively fix this in TripalImporterForm but I'm getting strange internal server errors (white screens) with report logs looking like this which baffles me.

TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, no array or string given in call_user_func_array() (line 114 of /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormSubmitter.php)
#0 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormSubmitter.php(114): call_user_func_array()
#1 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormSubmitter.php(52): Drupal\Core\Form\FormSubmitter->executeSubmitHandlers()
#2 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(592): Drupal\Core\Form\FormSubmitter->doSubmitForm()
#3 /var/www/html/drupal/web/core/lib/Drupal/Core/Form/FormBuilder.php(320): Drupal\Core\Form\FormBuilder->processForm()
#4 /var/www/html/drupal/web/core/lib/Drupal/Core/Controller/FormController.php(73): Drupal\Core\Form\FormBuilder->buildForm()
#5 [internal function]: Drupal\Core\Controller\FormController->getContentResult()
#6 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array()
#7 /var/www/html/drupal/web/core/lib/Drupal/Core/Render/Renderer.php(564): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#8 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext()
#9 /var/www/html/drupal/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext()
#10 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(158): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#11 /var/www/html/drupal/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#12 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle()
#13 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle()
#14 /var/www/html/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#15 /var/www/html/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
#16 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle()
#17 /var/www/html/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#18 /var/www/html/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#19 /var/www/html/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(709): Stack\StackedHttpKernel->handle()
#20 /var/www/html/drupal/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#21 {main}
.

### Steps to reproduce

Checkout this none functional Tripal Pub Importer branch (tv4g4-1642-Pub-Importer-V2), go to Add a Publication Importer
Select the pub med importer
Click on the criteria add button, you should see the page reload with this error.

### Screenshots

![image](https://github.com/tripal/tripal/assets/33866403/25e8b9bc-7cfd-4f28-bd00-d08fd58ec414)

**Comment by dsenalik** [comment]
This is what I fixed in #1644 and Stephen reported in issue #1651
@risharde if you want to review #1644 that would be great!

**Comment by risharde** [comment]
Thanks Doug, woops I also 'fixed' it in my branch now lol I will revert it
tomorrow and try to check on your PR

Thanks for the response. I am responding via email so apologies for the
footer message!

**Comment by risharde** [comment]
Doug, this was why the submit function wasn't being called from what I
noticed

**Comment by laceysanderson** [comment]
Fixed in #1644 which is now merged :-)
