### ISSUE TITLE
Migrating "other" content type

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#166]
Similar to my previous issue migrating Biomaterials, we also need to support migrating Protocol and Array_design types.  HWG doesn't actually use these content types, but in the interest of saying the Tripal Analysis Expression module supports Tripal 3, we need to address this.

I'm open to how it could be solved.  Specifying terms for these types in the Tripal Migration, allowing for custom terms to be specified, a migration hook are some ideas.

**Comment by laceysanderson** [comment]
@bradfordcondon did you find a solution for this? and/or is it still needed?

**Comment by bradfordcondon** [comment]
I think we can close this and if a user needs a specific content type not supported by the current migration, they can ask and we can try to make it happen.
