### ISSUE TITLE
ChadoStorage read value from base table

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#1662]
### Task Description

As found in #1619, we need the ability to read a value from the base table. Currently you have the choice of a variety of store* actions for the base table and join for linked tables but no read on the base table.

This is needed for fields which do not handle editing of a base table column, as well as, fields which add additional functionality or specialized displays for a specific column in addition to another field which handles editing.

### Branch Name

tv4g2-issue1662-loadBaseValues

**Comment by pdtouch** [comment]
This is a very useful feature that helps in the development of Tripal fields to read values from base table column which can be input in the Tripal GUI widget and carried over to other screens/pages of the field without storing it in Chado database. Sometimes a field needs this value for display or process in another page where this can be used. 

It has been tested and works as described:
<img width="618" alt="Screenshot 2023-10-06 at 2 09 48 PM" src="https://github.com/tripal/tripal/assets/2090189/bb04e474-f916-4e4f-8892-4e98dfb7e229">

<img width="449" alt="Screenshot 2023-10-11 at 1 53 35 PM" src="https://github.com/tripal/tripal/assets/2090189/a62576d0-ba2e-4903-b81f-a147ab96e650">

<img width="243" alt="Screenshot 2023-10-11 at 1 53 49 PM" src="https://github.com/tripal/tripal/assets/2090189/5a307449-f695-40ef-97e8-da31d2cd2f0c">

<img width="377" alt="Screenshot 2023-10-11 at 1 54 01 PM" src="https://github.com/tripal/tripal/assets/2090189/af59bfab-28fb-46b9-9d3f-dae5b81ab38e">

<img width="351" alt="Screenshot 2023-10-11 at 2 04 25 PM" src="https://github.com/tripal/tripal/assets/2090189/880eeee3-9857-44c7-8242-4dcb76498a1c">

The field was added to the Gene page. When Organism and Gene content were added  providing a value for Read Feature Name Type, the value provided in the widget is not available for edit and cannot change its value no matter what it is set to in the widget. This property can now be used in other pages in development of a new field.
