### ISSUE TITLE
label callback function doesnt exist?

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#168]
The relation module is calling the [`entity_label` method.](https://api.drupal.org/api/drupal/includes%21common.inc/function/entity_label/7.x)  I see that Tripal entities have the label callback function correctly defined as `tripal_entity_label`.  However, `function_exists(tripal_entity_label)` returns false and I cant find the callback in the code.  Am I missing something or is this still on the To Do list?

edit:  Maybe we are supposed to define the callback function for each bundle?  That would make some sense but it there's no implementation of it for the core Tripal entity types.

edit 2: I just made a simple PR that returns the node title.  I imagine you all have a solution with more finesse in mind, interested in hearing it.

Thanks!

**Comment by spficklin** [comment]
Pull request has been applied.  Thanks for providing the fix.
