### ISSUE TITLE
Unable to prepare an existing chado database from Tripal 3

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#1698]
### Tripal Version

4.x

### Drupal Version

10.1.x-dev

### PostgreSQL Version

13

### PHP Version

8.2

### General Description

I've been starting to play around with testing Tripal 4 with data from my Tripal 3 site and kept finding that prepare was failing. In order to remove the variable that my particular Chado instance was different than it should be, I thought I'd try running the Tripal 4 prepare on a blank Tripal 3 chado database... and it failed :cry

### Steps to reproduce

NOTE: I created a fresh Tripal 3 site using my [Drupal 7 Docker](https://hub.docker.com/r/laceysanderson/drupal7dev) which uses the Tripal3 version for 7 months ago. I setup the site, installed chado and prepared it. Then I exported the chado schema into the file you see attached here.

1. Create a fresh Tripal 4 docker that doesn't have chado installed yet.
```
docker run --publish=80:80 --name=tripalUpgrade -tid tripalproject/tripaldocker:drupal10.1.x-dev-php8.2-pgsql13-noChado
docker exec tripalUpgrade service postgresql restart
```
2. Download [tripal3.prepared-chado.sql.txt](https://github.com/tripal/tripal/files/13444624/tripal3.prepared-chado.sql.txt) then on the terminal from your downloads folder, use docker copy to get this file inside your new container.
```
docker cp tripal3.prepared-chado.sql.txt tripalUpgrade:/var/www/drupal/web
```
3. Use drush to apply this database dump to your current site.
```
docker exec -it tripalUpgrade drush sql:query --file tripal3.prepared-chado.sql.txt
```
4. Navigate to the chado schema listing in your browser: http://localhost/admin/tripal/storage/chado/manager. You should see an entry for "chado" and under "In Tripal" it says "No".
5. Click "Add to Tripal" (I find I need to do this 2X in order to see it show "Yes") and then click "Set as Default".
6. Navigate to submit a prepare job for this schema: http://localhost/admin/tripal/storage/chado/prepare and click "Prepare".
7. Run the tripal job and receive errors 🙈 

### Error messages

```shell
2023-11-22 22:00:00
Tripal Job Launcher
Running as user 'drupaladmin'
-------------------
2023-11-22 22:00:00: Job ID 1.
2023-11-22 22:00:00: Calling: tripal_chado_prepare_chado(chado)
 [notice] Creating Tripal Custom Tables...
 [notice] Creating Tripal Materialized Views...
 [notice] Loading Terms and Ontologies...
 [error]  SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint "cvterm_c2"
DETAIL:  Key (dbxref_id)=(3338) already exists.: INSERT INTO "chado"."cvterm" ("cv_id", "dbxref_id", "name", "definition", "is_obsolete", "is_relationshiptype") VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5) RETURNING cvterm_id; Array
(
)
 
 [error]  Message: Job execution failed: Failed to complete schema integration (i.e. Prepare) 
task.
SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates 
unique constraint "cvterm_c2"
DETAIL:  Key (dbxref_id)=(3338) already exists.: INSERT INTO "chado"."cvterm" 
("cv_id", "dbxref_id", "name", "definition", "is_obsolete", 
"is_relationshiptype") VALUES (:db_insert_placeholder_0, 
:db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, 
:db_insert_placeholder_4, :db_insert_placeholder_5) RETURNING cvterm_id; 
Array
(
)

Original Exception Trace:
#0 
/var/www/drupal/web/core/modules/pgsql/src/Driver/Database/pgsql/Insert.php(106): 
Drupal\Core\Database\ExceptionHandler->handleExecutionException(Object(PDOException), 
Object(Drupal\Core\Database\StatementWrapperIterator), Array, Array)
#1 
/var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/Plugin/TripalIdSpace/ChadoIdSpace.php(717): 
Drupal\pgsql\Driver\Database\pgsql\Insert->execute()
#2 
/var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/Plugin/TripalIdSpace/ChadoIdSpace.php(504): 
Drupal\tripal_chado\Plugin\TripalIdSpace\ChadoIdSpace->insertTerm(Object(Drupal\tripal\TripalVocabTerms\TripalTerm), 
Array)
#3 
/var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/Services/ChadoTermsInit.php(106): 
Drupal\tripal_chado\Plugin\TripalIdSpace\ChadoIdSpace->saveTerm(Object(Drupal\tripal\TripalVocabTerms\TripalTerm))
#4 
/var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/Task/ChadoPreparer.php(159): 
Drupal\tripal_chado\Services\ChadoTermsInit->installTerms()
#5 
/var/www/drupal/web/modules/contrib/tripal/tripal_chado/src/legacyFunctions.php(154): 
Drupal\tripal_chado\Task\ChadoPreparer->performTask()
#6 [internal function]: tripal_chado_prepare_chado('chado', 
Object(Drupal\tripal\Services\TripalJob))
#7 
/var/www/drupal/web/modules/contrib/tripal/tripal/src/Services/TripalJob.php(366): 
call_user_func_array('tripal_chado_pr...', Array)
#8 
/var/www/drupal/web/modules/contrib/tripal/tripal/src/api/tripal.jobs.api.php(443): 
Drupal\tripal\Services\TripalJob->run()
#9 
/var/www/drupal/web/modules/contrib/tripal/tripal/src/Commands/TripalCommands.php(77): 
tripal_launch_job(0, '1', -1, 0)
#10 [internal function]: 
Drupal\tripal\Commands\TripalCommands->runJobs(Array)
#11 
/var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(276): 
call_user_func_array(Array, Array)
#12 
/var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): 
Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, 
Object(Consolidation\AnnotatedCommand\CommandData))
#13 
/var/www/drupal/vendor/consolidation/annotated-command/src/CommandProcessor.php(175): 
Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, 
Array, Object(Consolidation\AnnotatedCommand\CommandData))
#14 
/var/www/drupal/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(387): 
Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), 
Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#15 /var/www/drupal/vendor/symfony/console/Command/Command.php(326): 
Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), 
Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/drupal/vendor/symfony/console/Application.php(1081): 
Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), 
Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/drupal/vendor/symfony/console/Application.php(320): 
Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), 
Object(Symfony\Component\Console\Input\ArgvInput), 
Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/drupal/vendor/symfony/console/Application.php(174): 
Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), 
Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/drupal/vendor/drush/drush/src/Runtime/Runtime.php(110): 
Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), 
Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/drupal/vendor/drush/drush/src/Runtime/Runtime.php(40): 
Drush\Runtime\Runtime->doRun(Array, 
Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/drupal/vendor/drush/drush/drush.php(139): 
Drush\Runtime\Runtime->run(Array)
#22 /var/www/drupal/vendor/drush/drush/drush(4): 
require('/var/www/drupal...')
#23 {main}
```

**Comment by laceysanderson** [comment]
Some differences I've found in terms:

| T4 Vocab          | T4 Accession  | T3 Vocab | T3 Accession  |
|-------------------|---------------|----------|---------------|
| organism_property | local:rank    | local    | local:rank    |
| library_property  | local:library | local    | local:library |

These can be fixed via the following queries:
```sql
UPDATE chado.cvterm SET cv_id=(SELECT cv_id FROM chado.cv WHERE name='organism_property') WHERE name='rank' AND cv_id=(SELECT cv_id FROM chado.cv WHERE name='local');
UPDATE chado.cvterm SET cv_id=(SELECT cv_id FROM chado.cv WHERE name='library_property') WHERE name='Library' AND cv_id=(SELECT cv_id FROM chado.cv WHERE name='local');
```

**Comment by spficklin** [comment]
I was under the impression we were deprecating those xxxx_property vocabularies.  

Update: In Tripal 3 we moved away from those xxxx_property vocabs  that were used in Tripal v2 and this seems to put them back....

**Comment by laceysanderson** [comment]
I'm happy to hear that is the intent but it's not the reality in Tripal 4 right now. All those *_property vocabs are defined in [tripal.tripal_content_terms.chado_content_terms.yml](https://github.com/tripal/tripal/blob/4.x/tripal_chado/config/install/tripal.tripal_content_terms.chado_content_terms.yml#L348-L655) and used all over 🙈 

The two commands above just move terms in a Tripal3 database into the form expected by Tripal 4 right now.

All that said, I do hate those *_property type vocabs and definitely want to remove them! I don't remember the conversation where that was decided 🤷‍♀️ 

Should we make a separate issue to update the term yaml moving all those terms into a `tripal` cv and `tripal` db namespace and updating where those terms are used throughout core? Some may even be able to be replaced with real, non-local terms :-) 

This might make the problem in this issue even bigger though 🤔

**Comment by spficklin** [comment]
> I'm happy to hear that is the intent but it's not the reality in Tripal 4 right now. All those *_property vocabs are defined in [tripal.tripal_content_terms.chado_content_terms.yml](https://github.com/tripal/tripal/blob/4.x/tripal_chado/config/install/tripal.tripal_content_terms.chado_content_terms.yml#L348-L655) and used all over 🙈

Oh, okay. I think we should fix those then to be local rather than the prop vocabs we had before. But this will cause the same problem you mention above.  Looking at the code, the problem happens when the `cv.name` changed but the `db.name` and the `dbxref.accession` are the same.   The message above indicates there is a duplicated `cvterm.dbxref`. When the `ChadoIdSpace::saveTerm()`  function is run, it first checks to see if the cvterm is present and it does that by joining the `cvterm`, `cv`, `dbxref` and `db` tables. The names all have to match.  Since the `cv.name`  is changed it doesn't find the CV term record.  So, it moves on to insert. But before it can insert it checks to see if the `dbxref.dbxref_id` already exists for the term.  It finds one because the `db.name` and accession are still the same.  You get the error above because it then tries to insert the cvterm with a`dbxref_id` that already exists for another record in the `cvterm` table.  

Here's what I think we need to do.

1. Let's fix all of the chado table prop vocabularies so they use `local` instead.
2. Add a check to the `ChadoIdSpace::saveTerm()` function so that it adds another sanity check to make sure the dbxref_id isn't already used by another term.  If it is, then it should log an error to the user and continue on.  For module developers this will be a clue to them that they need to fix their term.
3. For upgrading, I think we can proceed with the your idea @laceysanderson of providing an interface that finds these problematic terms and lets the user change them.

**Comment by laceysanderson** [comment]
I'm circling back around to this.
I've created a branch `tv4g2-issue1698-termCleanup` which will contain the cleanup that Stephen mentioned above. There have been some improvements in the logging for terms but I will make sure in this branch that we have very clear: we expect a term with this cv name, db name and accession. 

This will help admin clean-up their chado to match expectations during an upgrade. That said, this PR will not actually add a way to automate fixing of these terms. That will have to come later.

**Comment by laceysanderson** [comment]
@dsenalik and @risharde:

I feel the wrong term is being used in the Taxonomy importer here:

[TaxonomyImporter::run()](https://github.com/tripal/tripal/blob/4.x/tripal_chado/src/Plugin/TripalImporter/TaxonomyImporter.php#L174-L187)
```php
    // TRIPAL 4 - Could not find a genetic_code record even after importing TAXRANK - Ask Stephen
    $genetic_code_cvterm = chado_get_cvterm([
      'name' => 'genetic_code',
      'cv_id' => ['name' => 'organism_property'],
    ], [], $this->chado_schema_main);

    // If genetic code cvterm not found, try to create it in organism_property CV
    // This cvterm is used in code further down in code
    if(!isset($genetic_code_cvterm)) {
      chado_insert_cvterm([
        'name' => 'genetic_code',
        'cv_name' => 'organism_property'
      ], [], $this->chado_schema_main);
    }
```

I came across this while cleaning up the terms as the organism_property cv is being removed with it's terms going in the `local` cv. We have the following terms in local: `genetic_code_name`, `mitochondrial_genetic_code`, `mitochondrial_genetic_code_name`. Should it have been one of these? Or, more ideally, is there one in TAXRANK we should use instead?

**Update to include:**
There are appropriate terms in EDAM we could use: 
- [Genetic code](http://www.ebi.ac.uk/ols4/ontologies/edam/classes/http%253A%252F%252Fedamontology.org%252Fdata_1598) EDAM:1598
- [Genetic code identifier](http://www.ebi.ac.uk/ols4/ontologies/edam/classes/http%253A%252F%252Fedamontology.org%252Fdata_2127) EDAM:2127
- [Genetic code name](http://www.ebi.ac.uk/ols4/ontologies/edam/classes/http%253A%252F%252Fedamontology.org%252Fdata_2128) EDAM:2128

**Comment by dsenalik** [comment]
Looking at Tripal 3 it creates four "code" terms here in `tripal_chado/includes/tripal_chado.semweb.inc`
```
  //-----------------------------
  // NCBI Organism Property Terms
  //-----------------------------
  // TODO: these probably have real terms we can use.

  $term = chado_insert_cvterm([
    'id' => 'local:rank',
    'name' => 'rank',
    'definition' => 'A taxonmic rank',
    'cv_name' => 'local',
  ]);

  $terms = [
    'lineage',
    'genetic_code',
    'genetic_code_name',
    'mitochondrial_genetic_code',
    'mitochondrial_genetic_code_name',
    'division',
...
```
and it looks like in the Tripal 4 yaml for `organism_property` the genetic code term was left out
`tripal_chado/config/install/tripal.tripal_content_terms.chado_content_terms.yml`:
```
    -   name: 'organism_property'
        label: 'A local vocabulary that contains locally defined properties for organisms'
        url: 'cv/lookup/local'
        idSpaces:
            -   name: 'local'
        terms:
            -   id: 'local:rank'
                name: 'rank'
                description: 'A taxonmic rank'
            -   id: 'local:lineage'
                name: 'lineage'
            -   id: 'local:lineage'
                name: 'lineage'
            -   id: 'local:genetic_code_name'
                name: 'genetic_code_name'
            -   id: 'local:mitochondrial_genetic_code'
                name: 'mitochondrial_genetic_code'
            -   id: 'local:mitochondrial_genetic_code_name'
                name: 'mitochondrial_genetic_code_name'
            -   id: 'local:division'
...
```

**Comment by laceysanderson** [comment]
Ok, I'll just add it then for now and open an issue with other options for the taxonomy importer instead of always using local terms. Thanks @dsenalik!

**Comment by dsenalik** [comment]
@laceysanderson your suggestion to use a "real" term though is a good idea!

**Comment by laceysanderson** [comment]
🥰 I'm trying to avoid task creep so I've created a new issue for that: https://github.com/tripal/tripal/issues/1726

**Comment by laceysanderson** [comment]
Things I still need to clean up:

- [x] organism_property used throughout Taxonomy Importer
- [x] Update the test chado dump
- [x] tripal_chado/src/Plugin/Field/FieldWidget/ChadoUnitWidgetDefault.php uses the featuremap_units cv to determine what to put in the select list

All the other cv's don't see to be mentioned anywhere in our current code base by cv.name.

**Comment by laceysanderson** [comment]
The mentioned PR makes the changes to vocabularies mentioned by @spficklin. It does not fix the issue mentioned by this issue.

**Comment by spficklin** [comment]
I tried to test this but I can't see the job log (either on the terminal or in the UI) as per issue #1786 . I'll come back to this once that's resolved.

**Comment by spficklin** [comment]
Okay, issue #1786 is resolved... it was a problem with my current instance of Drupal/Tripal. I reinstalled and it went away.  I tested performing a prepare on a site that was already prepared and it worked just fine.  It looks like all of the fixes prior to this have resolved the issue.

**Comment by spficklin** [comment]
This should be reopened. I misunderstood the problem.  The problem is that a site prepared under Tripal 3, then Chado moved to a Tripal 4 site fails in the prepare.

**Comment by laceysanderson** [comment]
This issue is now closed as there is a drush command added via the linked PR to help users with an older Chado clean up any inconsistencies that have crept in over time.

**Comment by laceysanderson** [comment]
See Issue https://github.com/tripal/tripal_doc/issues/82 for instructions on how to use it and other info about upgrading an existing chado.
