### ISSUE TITLE
No drush command given when importing content  types

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1705]
### Tripal Version

4.x

### Drupal Version

10.x

### PostgreSQL Version

N/A

### PHP Version

N/A

### General Description

When importing content types via the `admin/structure/bio_data` link, it tells you a job was successful but it doesn't give you the drush command to run if you want to run the job manually on the command-line.  It all works, just fine, but I just wanted to point that out.  

### Steps to reproduce

Go to `admin/structure/bio_data`, click the 'Import type collection` button.  Select all of the content  types and click the 'Import; button.

**Comment by dsenalik** [comment]
Fixed with merged PR #1745
