### ISSUE TITLE
Tripal 3 pub importer "The Publication Type is a required property but is missing"

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1712]
### Tripal Version

3.10

### Drupal Version

7.98

### PostgreSQL Version

15.3

### PHP Version

8.1.2

### General Description

There is at least one pubmed record that causes the error
"The Publication Type is a required property but is missing."

### Steps to reproduce

Create a publication importer for PMID accession 30000852 and test the importer.

### Error messages

```shell
Importing of publications for this importer is performed using a database transaction. If the load fails or is terminated prematurely then the entire set of insertions/updates is rolled back and will not be found in the database
Executing Importer: z PubMed Single Pub. Loader.
Page 1 of ?. Querying PMID for up to 100 pubs that match the criteria.
Found 1 publications.
The Publication Type is a required property but is missing.
Publishing publications with Drupal...
There are 0 records to publish.
Successfully published 0 Publication record(s).
Done. Publication importer summary: error=1 inserted=0 skipped=0 updated=0
```

### Screenshots

![30000852](https://github.com/tripal/tripal/assets/8419404/3617e0ca-5bd5-449f-9909-52a3ed5106ff)

**Comment by spficklin** [comment]
I believe this is fixed with PR #1713
