### ISSUE TITLE
More questions about custom modules

### ISSUE THREAD

**Issue by srobb1** [tripal/tripal#172]
If you have time @laceysanderson can you look at this since you are the one who is most familiar with my code? Sorry to bug you. Feel free to ignore me.

I realized the my last module was not quite what I needed. I was syncing too many records. I created a new module with a couple of tweaks that works much better! 

I am having an issue when I want to edit content that was created by my module. I must have missed something because in my expresssion_cvterm_organism_form() function the [property expression_cvterm_organism does not exist](https://github.com/srobb1/tripal_expression_cvterm/blob/9059a820b60dbb032df5bf0ff74f5cce7532d64c/tripal_expression_cvterm_organism.module#L395-L397) and therefore the web form is not populated with the current/existing values.  [My else statement ](https://github.com/srobb1/tripal_expression_cvterm/blob/9059a820b60dbb032df5bf0ff74f5cce7532d64c/tripal_expression_cvterm_organism.module#L409-L410)is being called and my "does not exisit" warning is being printed.

How do I, where do I, make sure that 'expression_cvterm_organism' with all its info is added to $node?

Thank you!!
Sofia

**Comment by srobb1** [comment]
It now exists. I uncommented and modified the code in chado_expression_cvterm_organism_load().

I am having a new issue now, but this one is solved!!

My new issue is that now I get a error when loading the 'edit' page. I get a very nondescript 'The website encountered an unexpected error. Please try again later.'

I will investigate. Any tips are appreciated :)

Thanks!

**Comment by srobb1** [comment]
I got this one too!!

dpm() helped me out!

I  had to change [line](https://github.com/srobb1/tripal_expression_cvterm/blob/13521065c0fe69c9c54e166beddc9d3267aabca9/tripal_expression_cvterm_organism.module#L401) this:
    `$cvterm_id  = $expression_cvterm_organism->cvterm_id;`

to this:
    `$cvterm_id  = $expression_cvterm_organism->cvterm_id->cvterm_id;`

my $expression_cvterm_organism->cvterm_id is an object not a value.

Not sure if I understand why yet, but I am going to investigate further!

**Comment by spficklin** [comment]
HI Sofia, it's been a bit of time since you posted this.  Are you still having issues?  If so, do you have your code on GitHub so we can take a look at it?

**Comment by srobb1** [comment]
I think I have this all worked out.
