### ISSUE TITLE
Taxonomy importer is requesting a gff3 file

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1733]
### Tripal Version

4.x

### Drupal Version

n/a

### PostgreSQL Version

n/a

### PHP Version

n/a

### General Description

If I recall, but I don't really, this may be a simple annotation problem. The taxonomy importer is asking for a gff3 file

### Steps to reproduce

Data Loaders -> Taxonomy Loader

### Screenshots

![20240108_taxonomy_importer_gff3](https://github.com/tripal/tripal/assets/8419404/fcec012b-8d6c-4f5d-99b5-5016f9ae5f91)

**Comment by risharde** [comment]
Thank Doug for discovering this one!
@dsenalik Small PR in for the file upload (removal) for review - https://github.com/tripal/tripal/pull/1737
