### ISSUE TITLE
Sept 29th online Tripal training

### ISSUE THREAD

**Issue by btski** [tripal/tripal#174]
Does anybody happen to have a recording of the training? I wasn't able to follow along with the demonstrations, and I believe solutions to problems I'm currently having were covered.

Thanks,
Blake

**Comment by spficklin** [comment]
Hi @btski.  Yes!  we do have a two hour recording of that training session.  Although it has not yet been posted to YouTube. We're working on that and we will have it up shortly.  It needs to be chopped into smaller chunks for viewing pleasure..

**Comment by btski** [comment]
Any update on the training recording @spficklin? I haven't been able to find a link on the Tripal site directing to the video, and I haven't been able to find it on YouTube either.

**Comment by spficklin** [comment]
I'm still working on it.  Apologies. I'll try and have it up by this Friday.

**Comment by btski** [comment]
Any update on training videos @spficklin?

**Comment by spficklin** [comment]
Oh goodness. This never got done.  Apologies @btski but at this point I think it's fair to say you don't need it and I don't know where that recording went....
