### ISSUE TITLE
create_point function is borked

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1746]
### Tripal Version

4.x

### Drupal Version

10.x

### PostgreSQL Version

N/A

### PHP Version

N/A

### General Description

When deleting a feature in Chado in Tripal v4 you get the following error message:

![image](https://github.com/tripal/tripal/assets/1719352/c6acac7c-1c10-448c-bcbd-b8b1455f689b)

It seems our version of Chado with Tripal is missing the `create_point` function

### Steps to reproduce

Add a feature to Chado and try to delete it using your favorite postgres editor.  Also, try cloning Chado via Admin > Tripal > Data Storage > Chado > Chado Schemas and click the 'clone' button on your current Chado instance.

**Comment by dsenalik** [comment]
Fixed with merged PR #1748
