### ISSUE TITLE
Installation failing

### ISSUE THREAD

**Issue by ligmanowski** [tripal/tripal#175]
Im trying to install Tripal but no success. I tried two methods and both failed at different points. Here I brougth the automatic drush installation I created the drupal DB and drupal user at Postgres than I add another DB and user to check if it was the problem, but both failed. 

Thanks and best regards,

Raphael Carvalho

Drush was not able to start (bootstrap) Drupal.                      [error]
Hint: This error can only occur once the database connection has
already been successfully initiated, therefore this error generally
points to a site configuration issue, and not a problem connecting to
the database.

Drush was attempting to connect to: 
 Drupal version                  :  7.56                            
 Site URI                        :  http://default                  
 Database driver                 :  pgsql                           
 Database hostname               :  localhost                       
 Database username               :  drupal                          
 Database name                   :  drupal                          
 Default theme                   :  bartik                          
 Administration theme            :  bartik                          
 PHP executable                  :  /usr/bin/php                    
 PHP configuration               :  /etc/php/7.0/cli/php.ini        
 PHP OS                          :  Linux                           
 Drush script                    :  /home/rcarvalho/.config/compose 
                                    r/vendor/drush/drush/drush.php  
 Drush version                   :  7.4.0                           
 Drush temp directory            :  /tmp                            
 Drush configuration             :                                  
 Drush alias files               :                                  
 Install profile                 :  standard                        
 Drupal root                     :  /var/www/html                   
 Site path                       :  sites/default                   
 File directory path             :  sites/default/files             
 Temporary file directory path   :  /tmp                            

Adding permissions for the administrator to view, edit, create, and delete all the newly created content types.
pg_query(): Query failed: ERROR:  relation "tripal_bundle" does not  [warning]
exist
LINE 1: SELECT name FROM tripal_bundle
                         ^ tripal_install.drush.inc:216
An error occurred.
Drush command terminated abnormally due to an unrecoverable error.   [error]

**Comment by btski** [comment]
Raphael,

I saw in previous posts you were using AWS to host Tripal. Assuming you're still trying to use AWS and aren't hosting locally, I can share the series of commands I used to get my Tripal instance working. Unfortunately, I'm still new and unable to help with specific issues.

-Blake

**Comment by btski** [comment]
I'm not familiar enough with Tripal to troubleshoot specific problems, but I see that earlier you were attempting to launch Tripal through AWS. Here's some command line documentation for starting a Tripal instance. At the very least, it should get you a working site. Then perhaps we can learn how to use the Tripal features together.

When launching an ubuntu instance, make sure you have ports 22 (default, SSH) and 80 (HTTP) enabled. My notes for launching Tripal through AWS are as follows:
Ubuntu Installation - http://tripal.info/tutorials/v3.x/installation/server-setup/ubuntu-16.04
sudo apt-get update
sudo apt-get install apache2
cd /etc/apache2/mods-enabled
sudo ln -s ../mods-available/rewrite.load
sudo apt-get install gedit
cd /etc/apache2/sites-available/
sudo vim 000-default.conf
#refer to instructions on how to edit (‘a’ to edit, esc to stop editing, ‘:wq’ to save changes)
sudo service apache2 restart
sudo apt-get install php php-dev php-cli libapache2-mod-php
sudo apt-get install php-pgsql php-gd php-xml-parser
sudo vi /etc/php/7.0/apache2/php.ini (change memory limit to 1024M and :wq)
sudo service apache2 restart
sudo apt-get install postgresql
sudo apt-get install phppgadmin
sudo vi /etc/apache2/conf-available/phppgadmin.conf (comment out required local)
sudo vi /etc/apache2/sites-enabled/000-default.conf (comment out inserted block from referred instructions)
sudo service apache2 restart
Load page: http://ec2...compute-1.amazonaws.com/phppgadmin

Drush install
sudo apt-get install drush

Installation method 1, rapid install
sudo su - postgres
createuser -P drupal (pw =)
createdb drupal -O drupal 
exit
cd /var/www/html
sudo git clone https://github.com/tripal/tripal_install.git
sudo mv tripal_install/* ./
sudo drush --include=. tripal-generic-install
	Site Name: Tripal practice 
        Site email address: enter_email
        Administrator username: admin (spaces seem to crash code)
        Administrator password: enter_password
database name = 'drupal’, database user = 'drupal’,  'host' = localhost, port = 5432
Launch Chado v1.3 (option 1)
sudo vi /etc/apache2/sites-enabled/000-default.conf (edit back in added lines)
sudo service apache2 restart

Permission to write to file (corrects error in configuration)
http://tripal.info/tutorials/v3.x/installation/drupal
mkdir -p /var/www/html/sites/default/files
sudo chgrp www-data /var/www/html/sites/default/files
sudo chmod g+rw /var/www/html/sites/default/files

Enable bulk loader
https://www.washington.edu/computing/unix/permissions.html
Directory /home/ubuntu/.drush/cache/default exists, but is not writable      [error]
ls -lg /home/ubuntu/.drush/cache/default (file has read/write enabled for owner only, not a directory)
sudo chmod a+wr /home/ubuntu/.drush/cache/default
cd /var/www/html
drush pm-enable tripal_bulk_loader

**Comment by spficklin** [comment]
Hi @ligmanowski let us know if @btski's suggestions work.   If not we can try to dig deeper.    If you're getting this messge: "pg_query(): Query failed: ERROR: relation "tripal_bundle" does not"  Then there must have been something that went wrong well before this message appeared.

**Comment by ligmanowski** [comment]
Hi @btski @spficklin Ill try some of @btski ideas. In this thread I was trying to install only Tripal without all GMOD Cloud features and tools. In this case I was doing a clean installation at my machine running Ubuntu 16.04. Its not a virtual machine to remove any variable from equation... hehehe I saw that you use sudo to install drush, is that working for you guys? Because tutorial says its not a good idea, thats why I avoid it. 

Anyway Ill try everything and let you know how much I progress this time.

Thanks all and best regards,

Raphael

**Comment by btski** [comment]
Any deviation from recommended commands was likely a result of trial and error. I can try relaunch an instance without running sudo for the drupal installation. It takes about 15 minutes to launch a Tripal site from scratch. I don't think running sudo commands on a new cloud instance is risky (easily replaceable if something happens). Probably less advisable to use sudo in a developed instance or on a physical/local computer (in your case).

**Comment by spficklin** [comment]
HI @ligmanowski Any updates on this issue?  Do you need any further input?  If so let us know. If not , I'll close this out.  Thanks.

**Comment by spficklin** [comment]
Marking this as closed as well. If this is still an issue for you please re-open.
