### ISSUE TITLE
Chado Custom Table functionality

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal#1758]
### Tripal Version

4.0.alpha2

### Drupal Version

10.2.2

### PostgreSQL Version

15.5

### PHP Version

8.1.27

### General Description

Several functions provided by the Chado Custom Table service do not work as [documented](https://github.com/tripal/tripal_doc/pull/59). Testing with Devel-PHP, the following behaviors were observed:
 - getTables(); - returns an empty array. Expected an array of key/value pairs representing the custom tables as seen in the `tripal_custom_tables` table.
 - loadById(); - works as intended
 - loadByName(); - returns NULL
 - delete(); - Undefined: `Call to undefined method Drupal\tripal_chado\ChadoCustomTables\ChadoCustomTable::delete()`

The code itself indicates that these functions can take the name of the Chado instance as an argument, but are optional. They default to NULL, which when querying the database, returns no rows because the `chado` column in the `tripal_custom_tables` table defaults to 'chado'. The functions work as expected when the `chado_schema` argument is passed.

There is an additional undocumented function, `findByName()`. It also is similarly affected by not passing a second argument.

The delete function is undefined, however.

---

Note: these functions were mentioned in https://github.com/tripal/tripal/issues/1345 which calls for functional testing.

### Steps to reproduce

Either use Devel PHP or write code in a custom module to call the functions that exist in the Chado Custom Table service:

### Without chado_schema argument:

```php
$ct_service = \Drupal::service('tripal_chado.custom_tables');
$custom_table = $ct_service->loadByName('db2cv_mview');

print_r($custom_table);
```
result:
```
NULL
```

### With chado_schema argument:

```php
$ct_service = \Drupal::service('tripal_chado.custom_tables');
$custom_table = $ct_service->loadByName('db2cv_mview', 'chado');

print_r($custom_table);
```

result:

```
(
    [table_name:Drupal\tripal_chado\ChadoCustomTables\ChadoCustomTable:private] => db2cv_mview
    [table_id:Drupal\tripal_chado\ChadoCustomTables\ChadoCustomTable:private] => 10
    [chado_schema:Drupal\tripal_chado\ChadoCustomTables\ChadoCustomTable:private] => chado
)

**Comment by Ferrisx4** [comment]
My initial approach was just going to be to set the default value for the `chado_schema` argument to be `chado`, since that is the default name for the Chado schema on most sites. However, it might be more prudent to add a little logic to detect the name of the Chado instance that is installed (or the first one that is listed in the `chado_installations` table).
Thoughts, @spficklin?

**Comment by Ferrisx4** [comment]
Decided to use the existing `chado_get_schema_name()` function and providing 'chado' as the default. Is this a viable approach?
https://github.com/tripal/tripal/commit/404623c792d21a6daaf495e62dcd5399f5eecc4f

Functional testing still in progress

@dsenalik thanks for the labels!

**Comment by laceysanderson** [comment]
Ah, yes -thank you for commenting again with an update. I had meant to reply but got lost in sickness 🙈 

This also reminds me that we need to document this and make is more obvious/easier!

There are currently two ways to get the default chado schema.
1. When you create a fresh chado connection, it sets the main schema to the default one. This means you can get the default schema as follows:
```php
$chado = \Drupal::service('tripal_chado.database');
$default_chado_schema = $chado->getSchemaName();
```

This information is also stored in configuration and changed via the Admin > Tripal > Data Storage > Chado > Chado Schemas (admin/tripal/storage/chado/manager) UI. You can access the configuration directly as follows:

```php
$default_chado_schema = \Drupal::config('tripal_chado.settings')->get('default_schema');
```

**Comment by Ferrisx4** [comment]
@laceysanderson suggested a new getDefault() function, to be included in the ChadoSchema class, to be used in cases such as this. This new feature is pending in https://github.com/tripal/tripal/pull/1768
Once that is in, the rest of the functionality in this issue will be built out.

**Comment by laceysanderson** [comment]
Fixed by linked PR -thank you @Ferrisx4 ❤️
