### ISSUE TITLE
Organism name is incorrectly case sensitive for taxonomy loader

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1761]
### Tripal Version

4.alpha2

### Drupal Version

NA

### PostgreSQL Version

NA

### PHP Version

NA

### General Description

The taxonomy loader, when you import existing species
![20240123_existing_species](https://github.com/tripal/tripal/assets/8419404/c1d200f5-2ed8-4a7e-b217-27437b03406b)
is failing due to NCBI returning all lower case organism names.

### Steps to reproduce

1. Create a real organism, e.g. `Citrus sinensis`
2. Run the taxonomy importer, just with defaults, don't enter anything.
3. When the job is run you will see ` [warning] WARNING: Partial match "citrus sinensis" to query "Citrus sinensis", no taxid available`
This should have matched, ignoring case. NCBI returned all lower case.

**Comment by dsenalik** [comment]
The same thing happens in Tripal 3. Probably a change in the NCBI API.

**Comment by pdtouch** [comment]
Thanks.
