### ISSUE TITLE
Tripal Importer class doesn't appear to be rolling back database transactions when exception is thrown

### ISSUE THREAD

**Issue by carolyncaron** [tripal/tripal#1764]
### Tripal Version

4.0.alpha3

### Drupal Version

10.0.12-dev

### PostgreSQL Version

13.13

### PHP Version

 8.1.27

### General Description

I've been developing a new importer and Lacey and I have been having trouble getting the database transaction to roll back once an exception has been thrown: https://github.com/TripalCultivate/TripalCultivate-Germplasm/pull/6#pullrequestreview-1778536959 

I decided to test the FASTA importer to see if I could reproduce the problem there. I did this by adding an if statement in the FASTA importer code to throw an exception after the 5th feature in my FASTA file. Once I ran the job, my error was successfully printed to the terminal, but the first 5 features were committed to the database (out of the 9 total features in the file).

### Steps to reproduce

1. I cloned the tripal repo and made sure I was on the `4.x` branch, then created a fresh tripaldocker container that mounted to this repo so I could make code changes:
```
docker run --publish=8880:80 --name=t4 -tid --volume=$(pwd):/var/www/drupal/web/modules/contrib/tripal tripalproject/tripaldocker:latest
docker exec t4 service postgresql start
```
2. I added the following code to line 645 of `tripal_chado/src/Plugin/TripalImporter/FASTAImporter.php`:
```
      if ($j == 5) {
        throw new \Exception(
          t("Reached sequence 5, exception thrown.")
        );
      }
```
3. I logged into my new tripal site at `http://localhost:8880` and created an Organism (**Citrus sinensis**) and Analysis (**Whole Genome Assembly and Annotation of Citrus sinensis**) through the interface

4. For my test FASTA file ([Citrus sinensis-orange1.1g015632m.g.fasta](http://tripal.info/sites/default/files/Citrus_sinensis-orange1.1g015632m.g.fasta)), I grabbed it from the Tripal 3 docs here: https://tripal.readthedocs.io/en/latest/user_guide/example_genomics/genomes_genes.html 

5. I filled out the FASTA Importer form as follows:

Field Name | Value
-- | --
FASTA file | Upload the file named Citrus_sinensis-orange1.1g015632m.g.fasta
Analysis | Whole Genome Assembly and Annotation of Citrus sinensis
Organism | Citrus sinensis (Sweet orange)
Sequence type | mRNA
Method | Insert and update*
Name Match | Name

*Note that this is the only change I made from the Tripal 3 docs since there are currently no features loaded in this site

6. I submitted the form and ran my job on the command line:
```
docker exec t4 drush trp-run-jobs --job_id=1 --username=drupaladmin --root=/var/www/drupal/web
```
See output under "Error Messages".

7. I checked the database using `docker exec -it t4 drush php:cli` to see that the first 5 sequences were in the chado.feature table:
```
$connection = \Drupal::service('tripal_chado.database');
= Drupal\tripal_chado\Database\ChadoConnection {#6115}

> $feature_query = $connection->select('1:feature','f')->fields('f', ['organism_id', 'name', 'uniquename', 'type_id']);
= Drupal\pgsql\Driver\Database\pgsql\Select {#6176}

> $feature_record = $feature_query->execute()->fetchAll();
= [
    {#6141
      +"organism_id": "1",
      +"name": "orange1.1g015632m",
      +"uniquename": "orange1.1g015632m",
      +"type_id": "166",
    },
    {#6140
      +"organism_id": "1",
      +"name": "orange1.1g015662m",
      +"uniquename": "orange1.1g015662m",
      +"type_id": "166",
    },
    {#6130
      +"organism_id": "1",
      +"name": "orange1.1g018514m",
      +"uniquename": "orange1.1g018514m",
      +"type_id": "166",
    },
    {#6138
      +"organism_id": "1",
      +"name": "orange1.1g015615m",
      +"uniquename": "orange1.1g015615m",
      +"type_id": "166",
    },
    {#6137
      +"organism_id": "1",
      +"name": "orange1.1g015645m",
      +"uniquename": "orange1.1g015645m",
      +"type_id": "166",
    },
  ]
```

### Error messages

```shell
2024-01-24 22:01:38
Tripal Job Launcher
Running as user 'drupaladmin'
-------------------
2024-01-24 22:01:38: Job ID 1.
2024-01-24 22:01:38: Calling: tripal_run_importer(5)
Running 'Chado FASTA File Loader' importer
 [notice] Running 'Chado FASTA File Loader' importer
NOTE: Loading of this file is performed using a database transaction. If it fails or is terminated prematurely then all insertions and updates are rolled back and will not be found in the database
 [notice] NOTE: Loading of this file is performed using a database transaction. If it fails or is terminated prematurely then all insertions and updates are rolled back and will not be found in the database
Step 1: Finding sequences...
 [notice] Step 1: Finding sequences...
Step 2: Importing sequences...
 [notice] Step 2: Importing sequences...
Found 9 sequence(s).
 [notice] Found 9 sequence(s).
Percent complete: 0%. Memory: 32,514,184 bytes.
 [notice] Percent complete: 0%. Memory: 32,514,184 bytes.
Percent complete: 0%. Memory: 32,661,680 bytes.
 [notice] Percent complete: 0%. Memory: 32,661,680 bytes.
Percent complete: 11.11 %. Memory: 32,661,680 bytes.
 [notice] Percent complete: 11.11 %. Memory: 32,661,680 bytes.
Percent complete: 22.22 %. Memory: 32,661,784 bytes.
 [notice] Percent complete: 22.22 %. Memory: 32,661,784 bytes.
Percent complete: 33.33 %. Memory: 32,661,912 bytes.
 [notice] Percent complete: 33.33 %. Memory: 32,661,912 bytes.
Percent complete: 44.44 %. Memory: 32,661,912 bytes.
 [notice] Percent complete: 44.44 %. Memory: 32,661,912 bytes.
ERROR: Reached sequence 5, exception thrown.
 [error]  ERROR: Reached sequence 5, exception thrown. 
[site http://default] [TRIPAL] ERROR: Reached sequence 5, exception thrown.
```

**Comment by dsenalik** [comment]
Just a note, this code
`    $transaction->rollback();`
in `tripal/src/api/tripal.importer.api.php`
IS being called.

**Comment by carolyncaron** [comment]
Thank you! That was really helpful, I believe I've found a solution 😄 I will make a PR for it shortly!
