### ISSUE TITLE
view the Organism, throw this Exception

### ISSUE THREAD

**Issue by a2htray** [tripal/tripal#178]
`PDOException: SQLSTATE[42703]: Undefined column: 7 ERROR: column orel.object_organism_id does not exist LINE 1: ...tionship ORel INNER JOIN chado.organism O on ORel.objec... ^: SELECT O.genus, O.species, O.organism_id, CO.nid, CVT.name as rel_type FROM chado.organism_relationship ORel INNER JOIN chado.organism O on ORel.object_organism_id = O.organism_id INNER JOIN chado.cvterm CVT on ORel.type_id = CVT.cvterm_id LEFT JOIN chado_organism CO on O.organism_id = CO.organism_id WHERE ORel.subject_organism_id = :organism_id ; Array ( [:organism_id] => 2 ) in chado_query() (line 1538 of /var/www/html/sites/all/modules/tripal/tripal_core/api/tripal_core.chado_query.api.inc).`

**Comment by spficklin** [comment]
Hi @a2htray Are you using an Chado v1.2 where you added the organism_relationship table?  Or have you upgraded from Chado v1.2 where you added the organism_relationship table prior to upgrading to Chado v1.3?  The query above is trying to join on the organism table via the organism_relationship.object_organism_id field.  The organism_relationship table was added new in Chado v1.3 and it does not have a field named object_organism_id.  The field is just object_id.  So, I wonder if you had added the organism_relationship table manually as a custom table?

If so, you may want to rename those fields to match the current version in Chado v1.3 and adjust any custom code you have that uses the object_organism_id or subject_organism_id fields.

**Comment by a2htray** [comment]
thanks for your comment, i will try to add the organism_relationship table.

**Comment by a2htray** [comment]
i find the this `create table` statement via [https://raw.githubusercontent.com/GMOD/Chado/master/chado/schemas/1.31/default_schema.sql](https://raw.githubusercontent.com/GMOD/Chado/master/chado/schemas/1.31/default_schema.sql)

**Comment by spficklin** [comment]
Hi @a2htray. Just curious if this is resolved for you.  If so, I'll go ahead and close out this issue. If not let us know if we can help further.

**Comment by spficklin** [comment]
Closing this out. If you are still having issues please reopen.
