### ISSUE TITLE
Setting CV terms on non Tripal fields attached to Tripal content types

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#1789]
### Task Description

Currently, users can only set CV terms on Tripal fields.  But someone can attach an existing Drupal field to a Tripal content type. For example, if a user wants to add an image to an organism content type they can do so using the Drupal image field. But that image field doesn't have a CV term associated with it.  For web services to work correctly all fields attached to a Tripal content type must be associated with a CV term.  

### Branch Name

tv4g1-issue1789-terms_on_fields

**Comment by laceysanderson** [comment]
Completed by merged PR
