### ISSUE TITLE
Prepare database from command line

### ISSUE THREAD

**Issue by abretaud** [tripal/tripal#179]
Hi, I'm working on updating https://github.com/erasche/docker-tripal to tripal 3
I need to be able to run the "Prepare Drupal for Chado" from the command line while starting up the container. Would it be possible maybe to create a drush task for it?

**Comment by MingChen0919** [comment]
Hi @abretaud, there is a drush task for installing tripal 3 (including Prepare Drupal for Chado). here are the links:
http://tripal.info/tutorials/v3.x/installation/rapid
https://github.com/tripal/tripal_install

**Comment by abretaud** [comment]
Ah yes, I saw it
I can't use it as is though as it does some things that are already done elsewhere in the build/startup process
Maybe I'll just make a light version of it (that's why I created https://github.com/tripal/tripal_install/issues/2)

**Comment by spficklin** [comment]
Hi @abretaud .  @shawnawsu did that work on the rapid install.  Can you explain the issues you have with it on your docker image and maybe we can accommodate?

**Comment by abretaud** [comment]
So, here's a first draft of our tripal3 docker image:
https://github.com/erasche/docker-tripal/tree/v3.x

And the light version of the rapid install script: https://github.com/erasche/docker-tripal/blob/v3.x/tripal_install.drush.inc

I've just removed things that are already done elsewhere in our case: settings, drupal install, db loading, ...

I wonder if this should be merged to https://github.com/tripal/tripal_install as a special "light" mode, or kept like this in the docker repo

**Comment by shawnawsu** [comment]
Hi @abretaud,

Thanks for the info. It looks like you're calling this once the drupal site is already installed and functional so it would make more sense to put the drush command into the existing tripal drush file. Let me chat with Stephen to see if that will work.

Thanks!
Shawna

**Comment by shawnawsu** [comment]
Hi @abretaud ,

Sorry for the delay. The new drush commands for tripal are now available in the 7.x-3.x branch. Can you pull and test if they work for your docker setup process?

Thanks!
Shawna

**Comment by abretaud** [comment]
Cool, thanks!
Looking at the code, the `trp-prepare-chado` command will be perfect (I haven't tested it yet though)

For `trp-set-permissions`, the code I use is not prompting for the db credentials nor using pg_query (see https://github.com/erasche/docker-tripal/blob/v3.x/tripal_install.drush.inc). Do you think it would be possible for you to to skip this prompt (it is needed for me as everything should be automated at startup)?

**Comment by shawnawsu** [comment]
Hi @abretaud ,

Sorry for the delay, I think this got buried in github notifications! In regards to the 'skip this prompt' request for the `trp-set-permissions`, you're right, there is no need for that.  I've just pushed an update that removes that prompt.
 
Thanks!
Shawna

**Comment by abretaud** [comment]
Thanks, it looks great!
Is there a specific reason why you use a db_select instead of writing `$bundles = tripal_get_content_types();` (just curious!)
