### ISSUE TITLE
Edit Field Settings WSOD on Drupal 10.2

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#1791]
### Tripal Version

4.x-dev

### Drupal Version

10.2.x-dev

### PostgreSQL Version

13

### PHP Version

8.3

### General Description

In Drupal 10.2 the UI for adding custom fields has changed quite a lot. This seems to have caused some incompatibilities as when you try to edit a Tripal/Chado field, you are greeted with the following WSOD:
![image](https://github.com/tripal/tripal/assets/1566301/a8923feb-5d59-4bf5-be94-b582f78a1eac)

The same happens when you try to create a new tripal/chado field.

### Steps to reproduce

1. Start a fresh site on Drupal 10.2.x-dev and PHP 8.3 (or use Tripaldocker)
2. Go to Admin > Tripal > Page Structure > Organism > Manage Fields
3. Click on "Edit" for any Tripal/Chado field

### Error messages

```shell
The website encountered an unexpected error. Try again later.

RuntimeException: The subform and parent form must contain the #parents property, which must be an array. Try calling this method from a #process callback instead. in Drupal\Core\Form\SubformState->getParents() (line 80 of core/lib/Drupal/Core/Form/SubformState.php).

Drupal\Core\Form\SubformState->getValues() (Line: 26)
Drupal\Core\Form\SubformState->getValue(Array) (Line: 44)
Drupal\tripal_chado\TripalField\ChadoFieldItemBase->storageSettingsForm(Array, Object, ) (Line: 123)
Drupal\field_ui\Form\FieldStorageConfigEditForm->form(Array, Object) (Line: 107)
Drupal\Core\Entity\EntityForm->buildForm(Array, Object) (Line: 85)
Drupal\field_ui\Form\FieldStorageConfigEditForm->buildForm(Array, Object, Object) (Line: 199)
Drupal\field_ui\Form\FieldConfigEditForm->form(Array, Object) (Line: 107)
Drupal\Core\Entity\EntityForm->buildForm(Array, Object)
call_user_func_array(Array, Array) (Line: 536)
Drupal\Core\Form\FormBuilder->retrieveForm('field_config_edit_form', Object) (Line: 283)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 73)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 627)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 121)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 181)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 76)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 28)
Drupal\Core\StackMiddleware\ContentLength->handle(Object, 1, 1) (Line: 32)
Drupal\big_pipe\StackMiddleware\ContentLength->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 36)
Drupal\Core\StackMiddleware\AjaxPageState->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object, 1, 1) (Line: 704)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

**Comment by laceysanderson** [comment]
This is happening because in Drupal 10.2 the field settings and field storage settings have each become subforms and then been merged into a single form page. This means that where we originally were given the full form state, now we are given a subformstate which only has the values specific to our subform in it.

I've fixed this initial issue in the linked branch by checking if we have a subformstate and if so, then retrieving the full form state.

However, the use of subforms here has also broken the ajax which results in the base table update ajax not firing properly. As such, the edit field works perfectly in the branch but we still cannot create a field in the branch.

**Comment by laceysanderson** [comment]
Ok, I've got to jump back to another project so someone else can take up this issue.

There is quite a bit of progress in branch `tv4g1-1791-editFieldWSOD`. Specifically, within that branch, 
- we do not get the WSOD described above
- the form renders as expected
- updated form to have a `base_table_dependant` wrapper around both the base columns and linking table elements which is triggered by ajax
- updated the ajax to replace the fields correctly.

Known outstanding issues:
- the existing base table value stored in the form state is not being properly pulled out (remains NULL on ajax)
- since the base table is not being updated properly, the base column and linking table options are also not being selected properly
- the linking table and base column fields remain disabled on ajax.

Here is the original change record in Drupal pulled up by @dsenalik:
https://www.drupal.org/node/3386675

There is a small chance that the remaining issues are caused by the following paragraph; however, I don't think so since the ajax is being triggered 🤔 

> Ajax handlers on \Drupal\field_ui\Form\FieldStorageConfigEditForm

In order for the two forms to remain in sync, the form is updated using AJAX whenever changes to the values of the \Drupal\field_ui\Form\FieldStorageConfigEditForm fields are being made. Since a form element can contain single AJAX event listener, modules using #ajax on form elements within \Drupal\field_ui\Form\FieldStorageConfigEditForm, including those returned by \Drupal\Core\Field\FieldItemInterface::storageSettingsForm may need to manually trigger the form update. This can be done by triggering \Drupal\field_ui\Form\FieldConfigEditForm::fieldStorageSubmit submit handler and by doing a full re-render of the complete form after the AJAX event.

**Comment by laceysanderson** [comment]
Notes for testing: 
- Test linking table form element by adding a Chado Contact field
- Test Base column form element by adding a Chado Text Field Type
- This code has only been tested on Drupal 10.2. I tried to write it with other versions in mind but am not sure that it is working as planned.

**Comment by dsenalik** [comment]
Trying to edit the description field on the organism content type. Go to edit, and save without making any changes, receive this error
`The website encountered an unexpected error. Try again later.`
`Exception: Cannot create a StorageProperty object for entity type "tripal_entity", field type "chado_text_type_default", key "value" as no term was provided in Drupal\tripal\TripalStorage\StoragePropertyBase->__construct() (line 88 of modules/contrib/tripal/tripal/src/TripalStorage/StoragePropertyBase.php). `

A temporary fix: `$base_column = $settings['base_column'] ?? $settings['base_table_dependant']['base_column'];`
