### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by abretaud** [tripal/tripal#180]
Just a minor thing I noticed: tripal.info mentions that tripal is released uneder GPL license, but I couldn't find a LICENSE file distributed in the release tarballs or in the github repo.
I think it would be good (and probably easy) to add this file, I thing github provide an automatic way to do it.

**Comment by spficklin** [comment]
Hi @abretaud 

Drupal requires that modules do not have a LICENSE file as it wants to add it to the modules when it packages them up for release.  And Drupal enforces GPLv2 license for everything.  Although I went searching just now to find those instructions and cannot find them....  You make a good point thought, as we are hosting the code in both places (Drupal.org and GitHub) we should probably add that file in and try to see if Drupal complains.

**Comment by abretaud** [comment]
Ah ok, I didn't know about drupal not wanting this file.
If synchronisation between github and drupal is automatic I guess scripting the removal of the file before sending to drupal should be doable?

**Comment by spficklin** [comment]
I've added a license.txt file.  We'll see if Drupal complains :-)
