### ISSUE TITLE
Tripal Layout uses machine name as the module title in Admin -> Extensions

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#1800]
### Task Description

Minor but just to keep it standard on the Admin -> Extensions section, we probably want to show the user readable name
See screenshot of the current display
![image](https://github.com/tripal/tripal/assets/33866403/d53ff746-2ef4-4aab-85df-524095c8b345)
 

### Branch Name
tv4g9-issue1800-tripal_layout_extension_naming

**Comment by risharde** [comment]
PR: https://github.com/tripal/tripal/pull/1801

**Comment by laceysanderson** [comment]
Fixed with PR 👍 Thanks @risharde
