### ISSUE TITLE
Tripal Importer class should replace existing files

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#181]
Right now, if you upload a file with the same name as an existing file using the Tripal Importer, it will skip the upload and use the file existing on the server.  

I would propose that the importer should overwrite the existing file.  Often I will upload a file, test it, make some changes, and re-upload, so renaming it (and remembering to rename it!) is a hassle.  Alternatively, you might upload a file you downloaded from NCBI for example, which uses a default name (for example `biosample_result.xml`) which would almost certainly already exist on the server if it hasnt been cleaned out recently. 

If we keep the current behavior then we should have an alert message to tell people "file already found on server, skipping upload".

**Comment by btski** [comment]
Can you clarify what you mean by 'Tripal Importer'? I don't have problems overwriting files via the scp Linux command for the bulk loader (which can also be used for the fasta/gff3 loaders).

Edit - I was able to reproduce the problem using the file selector (gui) for the fasta/gff3 loaders. As a short term solution, consider using the scp command to load data onto the Tripal server.

**Comment by bradfordcondon** [comment]
Hi, as your edit confirm I'm refering to the GUI of the new TripalImporter class in Tripal 3.  Sorry I wasnt more clear.

**Comment by spficklin** [comment]
Hi Bradford.  Good point.  The purpose of not overwriting the file is because the importer is supposed to pick up where it left off if the upload gets interrupted.  But, it should be easy enough to test if the upload is completed and re-start the upload.

**Comment by bradfordcondon** [comment]
Additional thing I noticed about the loader that complicates this issue:

If the form fails for validation, you lose your uploaded file.  Because it "picks back up" when you reupload, no big deal.  However, for huge files, would be annoying to have to re-upload the file after failing validation.

I came across this with the FASTA uploader and a missed required field...

**Comment by laceysanderson** [comment]
This has gone over a year without progress and feels like an important update. @spficklin do you have time to fix this one? If not, could you explain what your logic would be so someone else can jump in on it?
