### ISSUE TITLE
Locked Mview handling

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal#1815]
### Task Description

As an addition to issue #1779, we need to implement functionality surrounding locking materialized views in Tripal. These include:
 - Setting the locked status in the GUI when creating an mview
 - Not allowing editing if the mview is locked
 - ~~Do not allow populating the mview if it is locked~~

### Branch Name

tv4g2-issue1815-locked-mview-handling

**Comment by Ferrisx4** [comment]
![Screen Shot 2024-04-16 at 2 43 22 PM](https://github.com/tripal/tripal/assets/9593623/32c6d511-b559-499c-8aff-f6f618abc102)

For the second point in the initial issue description, I just switched the "Edit" button to say "Locked" instead, as seen in the screenshot, and clicking the button does nothing. @laceysanderson do you remember if we talked about other functionality instead of just locking it?

---

Also, somewhat unrelated, but for the filter area, do we want to somehow indicate that that is what it is? There's no label on the box and the button just says "Apply". This could be its own issue or it could be a simple fix involved in the changes within this issue.

**Comment by Ferrisx4** [comment]
Alternatively, we can make the default action be "Populate" and only include Edit in the dropdown if the mview is not locked

**Comment by laceysanderson** [comment]
I like the "Locked" on the button but I would change it so that when clicked they see the edit page but the form elements are disabled. This would allow them to at least see what the locked settings are ;-p since we do not have a view. 

I do wonder if we may want to also make the default to populate for all of them. This might be better for usability now that you mention it as that is the most common action done on this page :-)

**Comment by Ferrisx4** [comment]
Ok thanks @laceysanderson, I am on board with these suggestions.

I also remembered this comment from #1779: https://github.com/tripal/tripal/issues/1779#issuecomment-1939299988 which discussed adding a blurb at the top describing mviews and where to edit them.

Would I be able to sneak this into this issue? I've also added the filter description as I mentioned in the second comment above, for your consideration
![Screen Shot 2024-04-26 at 8 54 42 AM](https://github.com/tripal/tripal/assets/9593623/41b43499-72eb-4a79-9013-db0169d52bb0)

**Comment by laceysanderson** [comment]
Yup, feel free to sneak that into this PR :-) I like your added filter description as well 👍

**Comment by Ferrisx4** [comment]
> Setting the locked status in the GUI when creating an mview

I've been thinking about and implementing this. In the current implementation, when adding a new Materialized View, the name in the "name" column in the database is derived from the 'table' value in the schema array. When adding a new materialized view, if the same name is provided as one that already exists, it will overwrite the existing materialized view in the database, and not add it as a new one. I was writing a check in the validateForm() of ChadoMviewForm to detect if the materialized view exists already and is locked when I discovered this.

I think it would be make sense to prohibit the user from overwriting an existing mview with the Add Mview form, regardless if it is locked or not, and only allow this when the form is in the "Edit" mode (reminder: this is determined by the $action variable): https://github.com/tripal/tripal/blob/193e72a4637e2ed1cbf8fe1115eaab768acf0d99/tripal_chado/src/Form/ChadoMviewForm.php#L30

Since we're using the same form for Adding and Editing, I can make additional changes to the Add/Edit form if this jives with you @laceysanderson.

---

By the way, is there a use-case for having multiple materialized views that draw from the same table?

---
Also, after talking with @spficklin, we can also change the list of materialized views to include a "Locked" column, as we do with the Custom Tables list. This is an easy change.

**Comment by laceysanderson** [comment]
> Since we're using the same form for Adding and Editing, I can make additional changes to the Add/Edit form if this jives with you @laceysanderson.

Yes, that sounds prefect. I agree with the add form not ever updating anything in the tables 🙃 🙈 Good catch on that one!

> By the way, is there a use-case for having multiple materialized views that draw from the same table?

You will want to check uniqueness of the schema name + table name combination as if people are using multiple chado instances they may want the same materialized view in each. The MView and custom tables already supports this with a schema name drop down on the forms.

> Also, after talking with @spficklin, we can also change the list of materialized views to include a "Locked" column, as we do with the Custom Tables list. This is an easy change.

Yes, that is perfect. I love the idea of a locked column to make it really clear!
