### ISSUE TITLE
Missing CV Terms

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1816]
### Task Description

Some chado table columns are missing terms.
Example, the `chado.featureloc` table does not have terms defined for: `is_fmin_partial`, `is_fmax_partial`, `residue_info`, and `locgroup`.

To list all chado table columns without terms assigned, this bit of code can be used. Run in devel module php window, or use `drush php:cli` Not everything here may need a term, ones that will be updated in this issue are marked with 🟢. Tables without a schema definition marked with `*` are all materialized view related, so can be ignored.
```
// Get the chado schema
$chado = \Drupal::service('tripal_chado.database');
$chado_schema = $chado->schema();

// Get the existing term mapping
$storage = \Drupal::entityTypeManager()->getStorage('chado_term_mapping');
$mapping = $storage->load('core_mapping');
$tables = $mapping->getTableNames();

foreach ($tables as $table_name) {
  $table_schema_def = $chado_schema->getTableDef($table_name, ['format' => 'Drupal']);
  if (!array_key_exists('fields', $table_schema_def)) {
    print "* No schema definition for table \"$table_name\"\n";
  }
  else {
    foreach ($table_schema_def['fields'] as $field => $properties) {
      $term = $mapping->getColumnTermId($table_name, $field);
      if ((!$term) and !($properties['type'] == 'serial')) {
        print "- $table_name.$field\n";
      }
    }
  }
}
```
output:
```
* No schema definition for table "analysis_organism"  (this is a materialized view)
- 🟢analysisfeature.rawscore
- 🟢analysisfeature.normscore
- 🟢analysisfeature.significance
- 🟢analysisfeature.identity
- analysisfeatureprop.analysisfeature_id
- biomaterial_treatment.treatment_id
- biomaterial_treatment.unittype_id
- cell_line_cvtermprop.cell_line_cvterm_id
- cell_lineprop_pub.cell_lineprop_id
- control.tableinfo_id
- control.row_id
* No schema definition for table "cv_root_mview"
- cvterm.is_relationshiptype
- cvterm_dbxref.is_for_definition
- cvtermpath.pathdistance
* No schema definition for table "db2cv_mview"
- 🟢eimage.eimage_data
- 🟢eimage.eimage_type
- 🟢eimage.image_uri
- expression_cvterm.cvterm_type_id
- expression_cvtermprop.expression_cvterm_id
- feature_cvterm_dbxref.feature_cvterm_id
- feature_cvterm_pub.feature_cvterm_id
- feature_cvtermprop.feature_cvterm_id
- feature_expressionprop.feature_expression_id
- feature_genotype.chromosome_id
- feature_genotype.cgroup
- feature_pubprop.feature_pub_id
- feature_relationship_pub.feature_relationship_id
- feature_relationshipprop.feature_relationship_id
- feature_relationshipprop_pub.feature_relationshipprop_id
- 🟢featureloc.is_fmin_partial
- 🟢featureloc.is_fmax_partial
- 🟢featureloc.residue_info
- 🟢featureloc.locgroup
- featureloc_pub.featureloc_id
- featureposprop.featurepos_id
- featureprop_pub.featureprop_id
- featurerange.leftstartf_id
- featurerange.leftendf_id
- featurerange.rightstartf_id
- featurerange.rightendf_id
- featurerange.rangestr
- library_expressionprop.library_expression_id
* No schema definition for table "library_feature_count"  
- library_featureprop.library_feature_id
- library_relationship_pub.library_relationship_id
- libraryprop_pub.libraryprop_id
* No schema definition for table "materialized_view"
- nd_experiment_analysis.nd_experiment_id
- nd_experiment_contact.nd_experiment_id
- nd_experiment_dbxref.nd_experiment_id
- nd_experiment_genotype.nd_experiment_id
- nd_experiment_phenotype.nd_experiment_id
- nd_experiment_project.nd_experiment_id
- nd_experiment_protocol.nd_experiment_id
- nd_experiment_pub.nd_experiment_id
- nd_experiment_stock.nd_experiment_id
- nd_experiment_stock.stock_id
- nd_experiment_stock_dbxref.nd_experiment_stock_id
- nd_experiment_stockprop.nd_experiment_stock_id
- nd_experimentprop.nd_experiment_id
- 🟢nd_geolocation.latitude
- 🟢nd_geolocation.longitude
- 🟢nd_geolocation.geodetic_datum
- 🟢nd_geolocation.altitude
- nd_protocol_reagent.reagent_id
- organism_cvtermprop.organism_cvterm_id
* No schema definition for table "organism_feature_count"
* No schema definition for table "organism_stock_count"
- organismprop_pub.organismprop_id
- phenotype.observable_id
- phenotype.attr_id
- phenotype.cvalue_id
- phenotype_comparison.genotype1_id
- phenotype_comparison.environment1_id
- phenotype_comparison.genotype2_id
- phenotype_comparison.environment2_id
- phenotype_comparison.phenotype1_id
- phenotype_comparison.phenotype2_id
- phenotype_comparison_cvterm.phenotype_comparison_id
- phylonode.parent_phylonode_id
- phylonode.left_idx
- phylonode.right_idx
- phylonode.label
- phylonode.distance
- 🟢project_stock.stock_id
- protocolparam.datatype_id
- protocolparam.unittype_id
- pubauthor.editor
- pubauthor.surname
- pubauthor.givennames
- pubauthor.suffix
- pubauthor_contact.pubauthor_id
- quantificationprop.quantification_id
- stock_cvtermprop.stock_cvterm_id
- stock_dbxrefprop.stock_dbxref_id
- stock_relationship_cvterm.stock_relationship_id
- stock_relationship_pub.stock_relationship_id
- stockcollection_db.stockcollection_id
- stockcollectionprop.stockcollection_id
- stockprop_pub.stockprop_id
- studyfactorvalue.studyfactor_id
- studyfactorvalue.factorvalue
- studyprop_feature.studyprop_id
- 🟢synonym.synonym_sgml
- tableinfo.primary_key_column
- tableinfo.is_view
- tableinfo.view_on_table_id
- tableinfo.superclass_table_id
- tableinfo.is_updateable
- tableinfo.modification_date
```

Chado modules and tables: http://gmod.org/wiki/Overview#Chado_and_BioSQL
OLS Ontology search page: https://www.ebi.ac.uk/ols4/ontologies

### Branch Name

tv4g2-issue1816-add-missing-terms

**Comment by pdtouch** [comment]
I had to load **OBO vocab loader -> The Sequence Ontology**
for Citrus gene data to be visible in Tripal 4.

**Comment by laceysanderson** [comment]
I modified @dsenalik script above to get a better idea of what kind of columns were missing terms.

```php
// Get the chado schema
$chado = \Drupal::service('tripal_chado.database');
$chado_schema = $chado->schema();

// Get the existing term mapping
$storage = \Drupal::entityTypeManager()->getStorage('chado_term_mapping');
$mapping = $storage->load('core_mapping');
$tables = $mapping->getTableNames();

$missing_schema = [];
$foreign_keys = [];
$required = [];
$other = [];
foreach ($tables as $table_name) {
  $table_schema_def = $chado_schema->getTableDef($table_name, ['format' => 'Drupal']);
  if (!array_key_exists('fields', $table_schema_def)) {
    $missing_schema[] = $table_name;
  }
  else {
    foreach ($table_schema_def['fields'] as $field => $properties) {
      $term = $mapping->getColumnTermId($table_name, $field);
      if ((!$term) and !($properties['type'] == 'serial')) {
        // Assume it's a foreign key if it ends in _id
        if (str_contains($field, '_id')) {
          $foreign_keys[] = $table_name.'.'.$field;
        }
        elseif ($properties['not null']) {
          $required[] = $table_name.'.'.$field;
        }
        else {
          $other[] = $table_name.'.'.$field;
        }
      }
    }
  }
}
print "\n\n\n\n\n";
print " Required Columns missing terms:";
if (empty($required)) { print 'None'; } else { print "\n - " . implode("\n - ", $required); }
print "\n\n Tables missing schema: ";
if (empty($missing_schema)) { print 'None'; } else { print "\n - " .  implode("\n - ", $missing_schema); }
print "\n\n Foreign Keys missing terms: ";
if (empty($foreign_keys)) { print 'None'; } else { print "\n - " . implode("\n - ", $foreign_keys); }
print "\n\n Remaining columns missing terms: ";
if (empty($other)) { print 'None'; } else { print "\n - " . implode("\n - ", $other); }
```

It results in the following...
 Required Columns missing terms:
 - cvterm.is_relationshiptype
 - cvterm_dbxref.is_for_definition
 - feature_genotype.cgroup
 - pubauthor.surname
 - tableinfo.is_view
 - tableinfo.is_updateable
 - tableinfo.modification_date

 Tables missing schema: 
 - analysis_organism
 - cv_root_mview
 - db2cv_mview
 - library_feature_count
 - materialized_view
 - organism_feature_count
 - organism_stock_count

 Foreign Keys missing terms: 
 - analysisfeatureprop.analysisfeature_id
 - biomaterial_treatment.treatment_id
 - biomaterial_treatment.unittype_id
 - cell_line_cvtermprop.cell_line_cvterm_id
 - cell_lineprop_pub.cell_lineprop_id
 - control.tableinfo_id
 - control.row_id
 - expression_cvterm.cvterm_type_id
 - expression_cvtermprop.expression_cvterm_id
 - feature_cvterm_dbxref.feature_cvterm_id
 - feature_cvterm_pub.feature_cvterm_id
 - feature_cvtermprop.feature_cvterm_id
 - feature_expressionprop.feature_expression_id
 - feature_genotype.chromosome_id
 - feature_pubprop.feature_pub_id
 - feature_relationship_pub.feature_relationship_id
 - feature_relationshipprop.feature_relationship_id
 - feature_relationshipprop_pub.feature_relationshipprop_id
 - featureloc_pub.featureloc_id
 - featureposprop.featurepos_id
 - featureprop_pub.featureprop_id
 - featurerange.leftstartf_id
 - featurerange.leftendf_id
 - featurerange.rightstartf_id
 - featurerange.rightendf_id
 - library_expressionprop.library_expression_id
 - library_featureprop.library_feature_id
 - library_relationship_pub.library_relationship_id
 - libraryprop_pub.libraryprop_id
 - nd_experiment_analysis.nd_experiment_id
 - nd_experiment_contact.nd_experiment_id
 - nd_experiment_dbxref.nd_experiment_id
 - nd_experiment_genotype.nd_experiment_id
 - nd_experiment_phenotype.nd_experiment_id
 - nd_experiment_project.nd_experiment_id
 - nd_experiment_protocol.nd_experiment_id
 - nd_experiment_pub.nd_experiment_id
 - nd_experiment_stock.nd_experiment_id
 - nd_experiment_stock.stock_id
 - nd_experiment_stock_dbxref.nd_experiment_stock_id
 - nd_experiment_stockprop.nd_experiment_stock_id
 - nd_experimentprop.nd_experiment_id
 - nd_protocol_reagent.reagent_id
 - organism_cvtermprop.organism_cvterm_id
 - organismprop_pub.organismprop_id
 - phenotype.observable_id
 - phenotype.attr_id
 - phenotype.cvalue_id
 - phenotype_comparison.genotype1_id
 - phenotype_comparison.environment1_id
 - phenotype_comparison.genotype2_id
 - phenotype_comparison.environment2_id
 - phenotype_comparison.phenotype1_id
 - phenotype_comparison.phenotype2_id
 - phenotype_comparison_cvterm.phenotype_comparison_id
 - phylonode.parent_phylonode_id
 - phylonode.left_idx
 - phylonode.right_idx
 - protocolparam.datatype_id
 - protocolparam.unittype_id
 - pubauthor_contact.pubauthor_id
 - quantificationprop.quantification_id
 - stock_cvtermprop.stock_cvterm_id
 - stock_dbxrefprop.stock_dbxref_id
 - stock_relationship_cvterm.stock_relationship_id
 - stock_relationship_pub.stock_relationship_id
 - stockcollection_db.stockcollection_id
 - stockcollectionprop.stockcollection_id
 - stockprop_pub.stockprop_id
 - studyfactorvalue.studyfactor_id
 - studyprop_feature.studyprop_id
 - tableinfo.view_on_table_id
 - tableinfo.superclass_table_id

 Remaining columns missing terms: 
 - cvtermpath.pathdistance
 - featurerange.rangestr
 - phylonode.label
 - phylonode.distance
 - pubauthor.editor
 - pubauthor.givennames
 - pubauthor.suffix
 - studyfactorvalue.factorvalue
 - tableinfo.primary_key_column
