### ISSUE TITLE
Creating backup through AWS

### ISSUE THREAD

**Issue by btski** [tripal/tripal#182]
I'm trying to backup my AWS Tripal instance. The steps I've used are as follows:

- Created a snapshot of the base/current Tripal instance
- Created a volume from that snapshot
- Created a new/empty ubuntu instance with appropriate security permissions
- Attached the volume onto the new/empty instance (now has a total of two volumes)
- Mounted the volume (installed nfs-common when I encountered problems, which hasn't helped)
- Confirmed volume was successfully mounted to a custom directory (lsblk and df -h commands)
- Attempted to load onto Tripal site failed, unable to access any Tripal documents/files through command line.

As best I can tell, the volume was successfully associated with a new instance, but is being ignored (lacks priority). Or perhaps the contents of the snapshot/volume are not what I want them to be.

**Comment by spficklin** [comment]
Hi @btski Are you mounting this volume via NFS or is it available to your instance as a local volume for mounting?  I've not tried to use AWS with Tripal so I'm not sure what the issue might be.

**Comment by btski** [comment]
I'm not entirely sure what you're referring to, but everything was done entirely on the AWS servers (nothing installed locally). I expect to begin working with a Ubuntu server and transitioning away from AWS soon, so this isn't really a pressing issue. AWS is a nice way to test data loading without much risk of overwriting or breaking things. It can be a bit inconvenient to relaunch an instance, so I thought it would be nice to create a backup (especially if I want preloaded data).

**Comment by spficklin** [comment]
It sounds to me that you have a mounting issue on your instance.  You mentioned installing the nfs-common package which would imply you're trying to mount the volume via NFS.  But I wasn't sure how AWS made that backup volume available to your instance.  I think you might need to ask this question to AWS support to help on this one as I've not worked with AWS in quite a while.

**Comment by spficklin** [comment]
Hi @btski .. any updates on this issue?  Let us know if you need additional input or if we can close this out.

Thanks

**Comment by btski** [comment]
I was unable to figure out how to make a backup on AWS cloud servers @spficklin. However, I plan to begin using a local Ubuntu server, which should be much easier to backup. I'll close this thread.
