### ISSUE TITLE
Chado Bulk Loader bug when reordering (Tripal 3)

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1870]
### Tripal Version

3.10

### Drupal Version

7.100

### PostgreSQL Version

15.3

### PHP Version

8.1.2

### General Description

The Chado bulk loader template editor has a bug, it you ever reorder the records, some data is replaced by that from a different record, I think generally from the first one.
This bug from my experience has been there for quite a while.

### Steps to reproduce

 1. Start at `/admin/tripal/loaders/bulk/templates`
 2. Add template ->
   Template Name: issue 1870
   Create Template
 3. If "CURRENT RECORDS" displays "Show row weights" instead of "Hide row weights", then click it. We want to see the row weights.
 4. New Record/Field
   Unique Record Name: Record 1
   Record Type/Action: SELECT
   Type of Field: Constant
   Human-readable Title for Field: CV Name 1
   Chado Table: cv
   Chado Field/Column: name
   Constant Value: local
   Save Changes
 5. New Record/Field
   Unique Record Name: Record 2
   Record Type/Action: SELECT
   Type of Field: Constant
   Human-readable Title for Field: CV Name 2
   Chado Table: cv
   Chado Field/Column: name
   Constant Value: iao  
   Save Changes
 6. Note the incorrect weights in the "ORDER" column.
![issue1870_1](https://github.com/tripal/tripal/assets/8419404/b39f2dcc-8bb2-4db7-8d79-0a25f6c5164c)

 7. Try to fix by clicking "Save Order"
![issue1870_2](https://github.com/tripal/tripal/assets/8419404/68700f50-9d59-4dca-9263-a688cb55098b)

 8. New Record/Field
   Unique Record Name: Record 3
   Record Type/Action: SELECT
   Type of Field: Constant
   Human-readable Title for Field: CV Name 3
   Chado Table: cv
   Chado Field/Column: name
   Constant Value: edam 
   Save Changes
 9. Now we observe that the name "Record 3" was lost and replace by the first one "Record 2". The weights are wonky.
![issue1870_3](https://github.com/tripal/tripal/assets/8419404/4362fe72-3653-4609-b09a-7e222f097d7f)

**Comment by laceysanderson** [comment]
Closing this as won't fix as there currently is not bandwidth within the Tripal core developer community to upgrade the bulk loader.
