### ISSUE TITLE
Adding properties when creating or editing tripal 3 entities

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#190]
Sorry if this is in the documentation and I missed it, but I believe this feature is missing.

When creating an entity manually via  Content->Tripal Content -> Add Tripal Content, there is no widget for adding properties.  For example when manually creating a biological sample I would want to specify a treatment, or when creating a gene feature I might want to specify an intron start.

Because in each case we're inserting into the base table's prop table (Feature -> Featureprop, biomaterial -> biomaterialprop) I would think theres a universal "property" field for this?

The same goes for the display of properties, actually (presumably managed by the same field).  

  Is the plan that each feature type would implement its own property field?  Or that properties are too generic and need to be implemented as specific fields?  if thats the case, it would be a lot of fields for something like biosample properties

**Comment by spficklin** [comment]
Hi @bradfordcondon 

Yes, you can do this.  But, you're right this is missing in our documentation in the User's Guide.   To add a property to an existing content go to Administation > Structure > Tripal Content Types.   Click on the 'manage fields' link for the content type to which you want to add a property.   Scroll to the bottom of the page to the section where you can add a new field.  And under the 'Field Type' drop down select  "Chado Property".  Name it what you like and follow through the configuration pages to finish setting it up.  In the configuration step you have to give the property a CV term.  This is the term that will be used when saving the property to the appropriate [base_table]prop table.

**Comment by bradfordcondon** [comment]
Great, thank you!

**Comment by bradfordcondon** [comment]
Hi Stephen,

How about programmatically?  I'm digging through the code for an example but coming up empty...  is it SIO annotation perhaps?

**Comment by bradfordcondon** [comment]
The behavior here was really really interesting.  I created the chado field as you described manually.
I  then was unable to publish my biosamples.

```
NOTE: publishing records is performed using a database transaction.
If the load fails or is terminated prematurely then the entire set of
is rolled back with no changes to the database

WD tripal: PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: ""                                                                                                                                                         [error]
LINE 1: ...NTO chado_bio_data_8 (entity_id, record_id) VALUES ('4', '')
                                                                    ^: INSERT INTO chado_bio_data_8 (entity_id, record_id) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1); Array
(
)
 in tripal_chado_field_storage_write() (line 68 of /var/www/html/sites/all/modules/tripal/tripal_chado/includes/tripal_chado.field_storage.inc).
WD tripal_chado: Could not publish record: Could not create entity.                                                                                                                                                                                                           [error]
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Could not publish record: Could not create entity.
Could not save the entity: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: ""                                                                                                                                                       [error]
LINE 1: ...NTO chado_bio_data_8 (entity_id, record_id) VALUES ('4', '')
                                                                    ^
Failed publishing record. See recent logs for more details.                                                                                                                                                                                                                   [error]
```
I deleted the original Chado Property field I created, reran the publisher, and was able to publish the biomaterials with no problem.

Performing further testing on this...

**Comment by spficklin** [comment]
Hey @bradfordcondon.  If you're getting errors when creating new fields then there's a bug in the code.  Maybe there's some special case about biosample property table? We'll have to look deeper.  Unless a bug has crept in this method would normally work.  

You shouldn't need to create property fields programmatically because Tripal automatically recognizes new properties for existing bundles that map to Chado tables.  If you have added properties after creating your content type then you can go to Admin > Structure > Tripal Content Types, click the manage fields' link next to the content type and on that page there will be a link to 'Check for new fields'.  Click that and all your new property fields will be automatically added.

**Comment by bradfordcondon** [comment]
Thank you Stephen!

For those who are finding this issue:

>You shouldn't need to create property fields programmatically because Tripal automatically recognizes new properties for existing bundles that map to Chado tables.


Crazy but this is how it works!    So... 
* Use the GUI to add a chado property.
* Programmatically, just insert the property and check for fields!
