### ISSUE TITLE
Improve performance of GFF3 importer

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#1925]
### Task Description

The chado API functions for creating new DBs, terms, dbxref, or properties are painfully slow.
For example, in the Taxonomy importer, creating a new property is taking 7+ seconds to delete and 17+ seconds to add a property, about 25 seconds per property, and about 6 are added for each taxonomy id ⏳.

~~I am thinking to create some functions in the ChadoImporterBase class, because making direct chado queries only takes a handful of milliseconds. What does anybody think about this?~~

See below, we need a "buddy"!

### Branch Name

tv4g10-issue1925-gff-importer-use-buddy

### PR #1944

**Comment by laceysanderson** [comment]
Replacing those aweful chado query api functions is the purpose of the cvterm/dbxref chado buddies 😃 I had made a good start on this but then got pulled away and have been unable to get back to it. The entire framework is in PR https://github.com/tripal/tripal/pull/1844 so now all that's left is adding in the chado queries themselves.

I suggest contributing to this PR rather then adding a few functions to the base chado importer class as it would be about the same amount of work if not less and make these faster versions available beyond the importers.

**Comment by dsenalik** [comment]
This will be implemented for the taxonomy importer by PR #1927
For this issue it will just be the GFF importer needing buddies, so I will change the title of this issue
