### ISSUE TITLE
Windows: Docker build reference to tripaldocker/dockerfile-* file does not seem to be a feature

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#1933]
### Tripal Version

-

### Drupal Version

-

### PostgreSQL Version

-

### PHP Version

-

### General Description

Hi everyone, just for reference, the Dockerfile in the root folder has one line which points to the relative path of the dockerfile in the tripaldocker folder. However trying to perform the following command fails on the Windows version of docker. It's not super critical but maybe there's a different and or more correct way of making a Dockerfile point to another file?

docker build -t tripalproject/tripaldocker:latest .

To get around this in the meanwhile, one can add the -f <file location> to attempt to run docker build on a specific file, example:

docker build -f tripaldocker/Dockerfile-php8.2  -t tripalproject/tripaldocker:latest . 

### Steps to reproduce

Running the commands from the Windows command prompt

**Comment by laceysanderson** [comment]
Ahhh... that's likely because it's a symbolic link which Windows probably doesn't support in the same way.

**Comment by risharde** [comment]
Details to resolve this issue for Windows is in the following issue (Windows related):
https://github.com/tripal/tripal/issues/1934
