### ISSUE TITLE
EDAM ontology

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#196]
We use so many terms from the EDAM ontology that we should probably consider loading it with the install of Tripal.

http://edamontology.org/EDAM.obo

**Comment by matuskalas** [comment]
Hi @spficklin,

This sounds awesome, and we from the EDAM team will gladly help you in case you have troubles or special requests.

One notable issue is that EDAM in **[OBO format](http://edamontology.org/EDAM.obo)** is extremely outdated (2012), and for the last many years we only provide EDAM in **[OWL](http://edamontology.org/EDAM.owl)**, **[TSV](http://edamontology.org/EDAM.tsv)**, and **[CSV](http://edamontology.org/EDAM.csv)**. Is that alright for your purpose?

In case it is absolutely necessary that we start providing **OBO format** again, please let us know in detail what the requirements are.

Thank you!

Details: http://edamontology.org

**Comment by spficklin** [comment]
Thanks @matuskalas for the offer!  That's much appreciated, as well as the info about the outdated OBO.  We currently only have an OBO importer, but we have an OWL importer planned.  If we have issues we'll be sure to let you know.

**Comment by laceysanderson** [comment]
Was there any progress on an OWL importer @spficklin?

**Comment by bradfordcondon** [comment]
I think its a WIP but not near finished.  Given the scale of the OBO loader I think we'd need someone really motivated to finish it.

**Comment by laceysanderson** [comment]
In that case, I'm going to close this issue as it's unlikely to happen with the D8 upgrade looming. If anyone specifically needs the full EDAM ontology, feel free to comment!
