### ISSUE TITLE
Undefined function drush_tripal_trp_run_jobs_install()

### ISSUE THREAD

**Issue by abretaud** [tripal/tripal#197]
Hi,
It looks like https://github.com/tripal/tripal/commit/2f21625b83d223ec2d562a669dea2d794a96fb00 broke something in the chado preparing mechanism, I get this error when my docker starts:

```
tripal_1         | WD php: Error: Call to undefined function                                [error]
tripal_1         | drush_tripal_trp_run_jobs_install() in eval() (line 1 of
tripal_1         | /root/.composer/vendor/drush/drush/commands/core/core.drush.inc(1122)
tripal_1         | : eval()'d code).
tripal_1         | Error: Call to undefined function drush_tripal_trp_run_jobs_install() in eval() (line 1 of /root/.composer/vendor/drush/drush/commands/core/core.drush.inc(1122) : eval()&#039;d code).
```

In the commit, a call to drush_tripal_trp_run_jobs_install() [was added](https://github.com/tripal/tripal/commit/2f21625b83d223ec2d562a669dea2d794a96fb00#diff-10418dd263a5aa72a8da32c41b29e4f9R315) but the function itself [was removed](https://github.com/tripal/tripal/commit/2f21625b83d223ec2d562a669dea2d794a96fb00#diff-10418dd263a5aa72a8da32c41b29e4f9L171).

**Comment by shawnawsu** [comment]
I must have accidentally deleted that while I was cleaning up the new drush commands I put in. I will get a fix for this out today.

**Comment by shawnawsu** [comment]
Hi @abretaud , 

I replaced that drush command. Please let me know if it's working for you. 

Thanks!
Shawna

**Comment by abretaud** [comment]
Thanks, it's ok now
