### ISSUE TITLE
Empty Values for Boolean + Integer

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#1970]
### Tripal Version

4.x-dev

### General Description

The Tripal boolean field, if it is not set to TRUE, does not display on the entity page. We have a display setting (tested that too) to set what to display for each TRUE and FALSE. I feel setting the false value to an empty string should cause it to be hidden, but otherwise it should display 'false' or whatever.
![issue-1966-works](https://github.com/user-attachments/assets/3e24fd8b-06e5-4aec-b6c7-57080fce839a)

For reference, the chado boolean field works is able to display both true and false and has the same settings to change the display.
The chado boolean field works like this
![chadoboolean](https://github.com/user-attachments/assets/aec698cd-6087-4b24-b706-26aedf970149)

For the settings form here, you currently can't set it to display an empty string
![chadoboolean2](https://github.com/user-attachments/assets/7a64a081-af18-4add-889a-82c78a0d9fcf)

However, it might be better to allow support for hiding these fields in the case of an "empty value"... In https://github.com/tripal/tripal/pull/1952#issuecomment-2327320716 it came up that we need to think about what the "default" value of the correct type should be for boolean or integer fields that are required. This was a hard question because FALSE and 0 are also valid true values 🤔 Maybe configuration is how we let users control this?

### Steps to reproduce

1. Add a TripalBoolean field to any content type.
2. Create a page of that content type and select false for that field.

If it is set to false it will be removed from the page but if set to true then it will show up.

**Comment by dsenalik** [comment]
The issue with a tripal boolean false not appearing is a storage problem, a true value is saved to the drupal field table, but a false value is not
```
sitedb=> select * from tripal_entity__field_tripal_boo;
 bundle  | deleted | entity_id | revision_id | langcode | delta | field_tripal_boo_value 
---------+---------+-----------+-------------+----------+-------+------------------------
 contact |       0 |         3 |           3 | und      |     0 | t
(1 row)
```

It might be this:  In the TripalEntity class, the preSave function will flag all falsey property values for deletion when drupal_store is set to TRUE.
