### ISSUE TITLE
TripalPublish: finding unpublished records may need a redesign

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#1986]
### Task Description

This issue is meant to connect a number of issues and provide a place for discussion. We are seeing a number of issues pop-up now that we are trying to publish real live sites that imply a bit of a redesign may be needed.

Specifically,

 - #1984 
 - #1924 
 - #1910 (Draft PR #1983)
 
The current logic for publish depends on
1. getting the titles of existing entities
2. generating titles for records returned by Tripal/ChadoStorage->findValues()
3. finding the set of titles from 2 that is not in 1 and publishing them.

As mentioned in #1910, this has serious performance/memory needs when publishing large numbers of records and requires support of batches. However, both 1 and 2 are large enough to cause issues which causes the above logic to fall apart. Furthermore, #1984 and #1924 adds complexity to the ability to determine which chado records would belong to a content type in a performant way.

The current thought between myself and @dsenalik is to take this approach:
1. Find the unique ids of unpublished records via Tripal/ChadoStorage
2. Batch the set returned by 1 for the next step
3. Use Tripal/ChadoStorage->findValues restricted to these ids to get the full details of the records to be published.

In order to make as few changes as possible, #1983 currently focuses on finding a batch of ids but then still using the titles to determine what is published vs not. 

However, this will fail where there are duplicate titles or where there are too many existing entities. With this in mind it may be better to have a single function in Tripal/ChadoStorage that finds unpublished records. For ChadoStorage this may be easiest by using a join across chado + public schema.

Even with a `findUnpublishedRecordIds()` style method, we still need a generic-ish way to indicate how to filter down to the right set of records in a single chado table. The following scenarios at a minimum need to be supported:
1. content type contains all records from a single table
2. content type contains all records with a specific type_id from a single table
3. content type contains all records with a specific property type associated with that base table.

Additionally, #1984 indicates that both 1 and 2 can be the case for a single chado table 🙈 

This leads me to think maybe we want a way to indicate that a specific field is key to defining the bundle. For example, in many cases our ChadoAdditionalTypeTypeDefault is this field but in some cases other extension modules may need to define additional fields -especially for alternative data backends. Furthermore, some content types won't have any such fields and just contain all records from that base table.

**Comment by dsenalik** [comment]
Just as an update, branch `tv4g1-issue1924-publish-duplicated-titles` fixes #1924 - however currently only for content types that are 1:1 mapping - all records in a table are the content type. It fails for e.g. gene.

What I do there is use the chado record ID as a key instead of title. Given a chado record ID, it is not too hard to find if it has been published. (I put this in the entity lookup service as it is kind of the same thing, just in bulk).

This means that duplicated titles are no longer ambiguous and so are now okay.
And this has a side benefit of being able to re-publish after the title format is changed and updating all of the titles. 

This comment lists tables with more than one entity type: https://github.com/tripal/tripal_doc/issues/32#issuecomment-1837528225

**Comment by laceysanderson** [comment]
Me + @dsenalik had another conversation about this and have a plan of action as follows:

- `tv4g1-issue1924-publish-duplicated-titles` is now the official branch for this issue
- we are moving to the chado record_id as key instead of title. This should be provided by the Tripal/ChadoStorage backend in order to keep TripalPublish backend agnostic. For a more generic definition: the unique key of the backend (e.g. chado) record (returned by the storage backend) is now being used to compare published vs. unpublished instead of the title
- For mapping chado records more clearly to bundles, we are going to add a few more third party settings. Namely we are going to indicate the type table and column for the content type.
  - this gets set in the yaml to create the content type
  - for content types created through the UI, it gets added after the fact by the core Tripal type field just like the base table gets added when the first field is added.
- We are going to continue exploring the use of a `findUnpublishedRecordIds()` style method which would combine (a) the query being done to select the entity id => chado record id for published entities and (b) the query discussed in the point above getting all the potential chado records to be associated with this bundle. By having this in one query, joining across drupal and chado we can add a condition here to restrict the results to only the unpublished chado records. This means we don't have to maintain two large arrays and compare using php and as such is much more performant and handles the case where we have a lot of existing entities already published.

**Comment by dsenalik** [comment]
Notes about the property table. For bundles using this method of definition, there is an additional type field defining a "fixed_value". This fixed value term matches the one used for the content type. Then, in the appropriate property table, there will be an entry using this term. The `value` column may have the CV term name. 
If the type is in the base table, then just the CV term ID is stored there.

Here are all of the fixed values currently defined
### feature table
```
tripal.tripalfield_collection.genetic_chado.yml:331:    -   name: qtl_type
tripal.tripalfield_collection.genetic_chado.yml:332:        content_type: QTL
tripal.tripalfield_collection.genetic_chado.yml:347:            fixed_value: SO:0000771  # "QTL"

tripal.tripalfield_collection.genetic_chado.yml:706:    -   name: sequence_variant_type
tripal.tripalfield_collection.genetic_chado.yml:707:        content_type: sequence_variant
tripal.tripalfield_collection.genetic_chado.yml:722:            fixed_value: SO:0001060  # "sequence_variant"

tripal.tripalfield_collection.genetic_chado.yml:1081:    -   name: genetic_marker_type
tripal.tripalfield_collection.genetic_chado.yml:1082:        content_type: genetic_marker
tripal.tripalfield_collection.genetic_chado.yml:1097:            fixed_value: SO:0001645  # "genetic_marker"

tripal.tripalfield_collection.genetic_chado.yml:1456:    -   name: phenotypic_marker_type
tripal.tripalfield_collection.genetic_chado.yml:1457:        content_type: phenotypic_marker
tripal.tripalfield_collection.genetic_chado.yml:1472:            fixed_value: SO:0001500  # "heritable_phenotypic_marker"

tripal.tripalfield_collection.genomic_chado.yml:167:    -   name: gene_type
tripal.tripalfield_collection.genomic_chado.yml:168:        content_type: gene
tripal.tripalfield_collection.genomic_chado.yml:183:            fixed_value: SO:0000704  # "gene"
tripal.tripalfield_collection.genomic_chado.yml:276:    -   name: gene_is_analysis
tripal.tripalfield_collection.genomic_chado.yml:277:        content_type: gene
tripal.tripalfield_collection.genomic_chado.yml:291:            fixed_value: local:is_analysis
tripal.tripalfield_collection.genomic_chado.yml:303:    -   name: gene_is_obsolete
tripal.tripalfield_collection.genomic_chado.yml:304:        content_type: gene
tripal.tripalfield_collection.genomic_chado.yml:318:            fixed_value: local:is_obsolete

tripal.tripalfield_collection.genomic_chado.yml:599:    -   name: mrna_type
tripal.tripalfield_collection.genomic_chado.yml:600:        content_type: mrna
tripal.tripalfield_collection.genomic_chado.yml:615:            fixed_value: SO:0000234  # "mRNA"
tripal.tripalfield_collection.genomic_chado.yml:708:    -   name: mrna_is_analysis
tripal.tripalfield_collection.genomic_chado.yml:709:        content_type: mrna
tripal.tripalfield_collection.genomic_chado.yml:723:            fixed_value: local:is_analysis
tripal.tripalfield_collection.genomic_chado.yml:735:    -   name: mrna_is_obsolete
tripal.tripalfield_collection.genomic_chado.yml:736:        content_type: mrna
tripal.tripalfield_collection.genomic_chado.yml:750:            fixed_value: local:is_obsolete
```
### featuremap table
missing fixed_value!
### phylotree table
```
tripal.tripalfield_collection.genomic_chado.yml:871:    -   name: phylotree_type
tripal.tripalfield_collection.genomic_chado.yml:872:        content_type: phylotree
tripal.tripalfield_collection.genomic_chado.yml:887:            fixed_value: data:0872  # "Phylogenetic tree"
```
### library table
```
tripal.tripalfield_collection.genomic_chado.yml:1197:    -   name: dna_library_type
tripal.tripalfield_collection.genomic_chado.yml:1198:        content_type: dna_library
tripal.tripalfield_collection.genomic_chado.yml:1213:            fixed_value: NCIT:C16223  # "DNA Library"
```
### analysis table
```
tripal.tripalfield_collection.genomic_chado.yml:1577:    -   name: genome_assembly_type
tripal.tripalfield_collection.genomic_chado.yml:1578:        content_type: genome_assembly
tripal.tripalfield_collection.genomic_chado.yml:1593:            fixed_value: operation:0525  # "genome assembly"

tripal.tripalfield_collection.genomic_chado.yml:1877:    -   name: genome_annotation_type
tripal.tripalfield_collection.genomic_chado.yml:1878:        content_type: genome_annotation
tripal.tripalfield_collection.genomic_chado.yml:1893:            fixed_value: operation:0362  # "Genome annotation"
```
### project table
```
tripal.tripalfield_collection.genomic_chado.yml:2041:    -   name: genome_project_type
tripal.tripalfield_collection.genomic_chado.yml:2042:        content_type: genome_project
tripal.tripalfield_collection.genomic_chado.yml:2057:            fixed_value: local:Genome Project  # "Genome Project"
```
### stock table
```
tripal.tripalfield_collection.germplasm_chado.yml:115:    -   name: germplasm_type
tripal.tripalfield_collection.germplasm_chado.yml:116:        content_type: germplasm
tripal.tripalfield_collection.germplasm_chado.yml:131:            fixed_value: CO_010:0000044  # "accession"

tripal.tripalfield_collection.germplasm_chado.yml:358:    -   name: breeding_cross_type
tripal.tripalfield_collection.germplasm_chado.yml:359:        content_type: breeding_cross
tripal.tripalfield_collection.germplasm_chado.yml:374:            fixed_value: CO_010:0000255  # "generated germplasm"

tripal.tripalfield_collection.germplasm_chado.yml:601:    -   name: germplasm_variety_type
tripal.tripalfield_collection.germplasm_chado.yml:602:        content_type: germplasm_variety
tripal.tripalfield_collection.germplasm_chado.yml:617:            fixed_value: "CO_010:0000029"  # "cultivar"

tripal.tripalfield_collection.germplasm_chado.yml:844:    -   name: ril_type
tripal.tripalfield_collection.germplasm_chado.yml:845:        content_type: ril
tripal.tripalfield_collection.germplasm_chado.yml:860:            fixed_value: CO_010:0000162  # "414 inbred line"
```

**Comment by dsenalik** [comment]
Tripal 3 stores the term used to define the bundle differently, it uses `rdfs:type` for the `type_id` and for the value uses the name of the CV term e.g. `genome_annotation`. Tripal 4 uses the bundle term in the `type_id` column.

Some code to use to migrate a Tripal 3 dump to the current method.
### -- Genome Assembly:
`UPDATE analysisprop SET type_id=(SELECT cvterm_id FROM cvterm T LEFT JOIN dbxref X ON T.dbxref_id=X.dbxref_id LEFT JOIN db D ON X.db_id=D.db_id WHERE D.name='operation' AND X.accession='0525') WHERE type_id=(SELECT cvterm_id FROM cvterm T LEFT JOIN dbxref X ON T.dbxref_id=X.dbxref_id LEFT JOIN db D ON X.db_id=D.db_id WHERE D.name='rdfs' AND X.accession='type') AND value='genome_assembly';`
### -- Genome Annotation:
`UPDATE analysisprop SET type_id=(SELECT cvterm_id FROM cvterm T LEFT JOIN dbxref X ON T.dbxref_id=X.dbxref_id LEFT JOIN db D ON X.db_id=D.db_id WHERE D.name='operation' AND X.accession='0362') WHERE type_id=(SELECT cvterm_id FROM cvterm T LEFT JOIN dbxref X ON T.dbxref_id=X.dbxref_id LEFT JOIN db D ON X.db_id=D.db_id WHERE D.name='rdfs' AND X.accession='type') AND value='genome_annotation';`
### -- Genome Project:
`UPDATE projectprop SET type_id=(SELECT cvterm_id FROM cvterm T LEFT JOIN dbxref X ON T.dbxref_id=X.dbxref_id LEFT JOIN db D ON X.db_id=D.db_id WHERE D.name='local' AND X.accession='Genome Project') WHERE type_id=(SELECT cvterm_id FROM cvterm T LEFT JOIN dbxref X ON T.dbxref_id=X.dbxref_id LEFT JOIN db D ON X.db_id=D.db_id WHERE D.name='rdfs' AND X.accession='type') AND value='genome_project';`
### -- Physical Map
`UPDATE featuremapprop SET type_id=(SELECT cvterm_id FROM cvterm T LEFT JOIN dbxref X ON T.dbxref_id=X.dbxref_id LEFT JOIN db D ON X.db_id=D.db_id WHERE D.name='data' AND X.accession='1280') WHERE type_id=(SELECT cvterm_id FROM cvterm T LEFT JOIN dbxref X ON T.dbxref_id=X.dbxref_id LEFT JOIN db D ON X.db_id=D.db_id WHERE D.name='rdfs' AND X.accession='type') AND value='physical';`
### -- Genetic Map
`UPDATE featuremapprop SET type_id=(SELECT cvterm_id FROM cvterm T LEFT JOIN dbxref X ON T.dbxref_id=X.dbxref_id LEFT JOIN db D ON X.db_id=D.db_id WHERE D.name='data' AND X.accession='1278') WHERE type_id=(SELECT cvterm_id FROM cvterm T LEFT JOIN dbxref X ON T.dbxref_id=X.dbxref_id LEFT JOIN db D ON X.db_id=D.db_id WHERE D.name='rdfs' AND X.accession='type') AND value='genetic';`
