### ISSUE TITLE
Errors using bulk loader

### ISSUE THREAD

**Issue by btski** [tripal/tripal#199]
#I'm trying to load some tab delimited text files using two different bulk loader templates. I encounter the same errors for both:

* Notice: Use of undefined constant STDOUT - assumed 'STDOUT' in tripal_bulk_loader_progress_bar() (line 1094 of /var/www/html/sites/all/modules/tripal/tripal_bulk_loader/includes/tripal_bulk_loader.loader.inc).
* Warning: fputs() expects parameter 1 to be resource, string given in tripal_bulk_loader_progress_bar() (line 1094 of /var/www/html/sites/all/modules/tripal/tripal_bulk_loader/includes/tripal_bulk_loader.loader.inc).
* Error: Call to undefined function drush_set_error() in tripal_bulk_loader_finish_loading() (line 1228 of /var/www/html/sites/all/modules/tripal/tripal_bulk_loader/includes/tripal_bulk_loader.loader.inc).

I have previously used the bulk loader to populate a custom Chado table. Now I'm trying to populate existing tables. Unfortunately, the error code is too specific for me to decipher the general problem.

<b>Edit1</b> - Still haven't been able to troubleshoot a problem. I've tried deconstructing the bulk load template to bare minimum (dbxref and db tables) and get the same errors. File inputs seem fine. 

My reduced template:
[{"table":"dbxref","record_id":"dbxref_swinedb","mode":"insert","fields":[{"type":"table field","title":"accession","field":"accession","required":0,"spreadsheet column":"1","exposed":0,"exposed_description":""},{"type":"foreign key","title":"db_id","field":"db_id","show_all_records":0,"foreign key":"db_swinedb","foreign field":"db_id","required":0}],"select_if_duplicate":1,"update_if_duplicate":0,"select_optional":0,"disable":0,"optional":0},{"table":"db","record_id":"db_swinedb","mode":"select_once","fields":[{"type":"constant","title":"name","field":"name","required":0,"constant value":"SwineDB","exposed":0,"exposed_validate":0}],"select_if_duplicate":0,"update_if_duplicate":0,"select_optional":0,"disable":0,"optional":0}]

My tab delimited text files (with faux data):
[test_RNA_noheader.txt](https://github.com/tripal/tripal/files/1522871/test_RNA_noheader.txt)
[test_AA_noheader.txt](https://github.com/tripal/tripal/files/1522872/test_AA_noheader.txt)

<b>Edit2</b> - It seems like the first two errors are code based and prompt the third error (a drush command for returning an error message). I'll try using a bulk load template that's worked for me in the past to see if the errors persist. I might also try creating a fresh Tripal instance. Any other suggestions appreciated!

<b>Edit3</b> - slight change to template, still doesn't work.

**Comment by btski** [comment]
Still haven't been able to troubleshoot a problem. I've tried deconstructing the bulk load template to bare minimum (dbxref and db tables) and get the same errors. File inputs seem fine. 

My reduced template:
[{"table":"dbxref","record_id":"dbxref_swinedb","mode":"insert","fields":[{"type":"table field","title":"accession","field":"accession","required":0,"spreadsheet column":"1","exposed":0,"exposed_description":""},{"type":"foreign key","title":"db_id","field":"db_id","show_all_records":0,"foreign key":"db_swinedb","foreign field":"db_id","required":0}],"select_if_duplicate":1,"update_if_duplicate":0,"select_optional":1,"disable":0,"optional":0},{"table":"db","record_id":"db_swinedb","mode":"insert_once","fields":[{"type":"constant","title":"name","field":"name","required":0,"constant value":"SwineDB","exposed":0,"exposed_validate":0}],"select_if_duplicate":0,"update_if_duplicate":0,"select_optional":0,"disable":0,"optional":0}]

My tab delimited text files (with faux data):
[test_RNA_noheader.txt](https://github.com/tripal/tripal/files/1522871/test_RNA_noheader.txt)
[test_AA_noheader.txt](https://github.com/tripal/tripal/files/1522872/test_AA_noheader.txt)

**Comment by btski** [comment]
It seems like the first two errors are code based and prompt the third error (a drush command for returning an error message). I'll try using a bulk load template that's worked for me in the past to see if the errors persist. I might also try creating a fresh Tripal instance. Any other suggestions appreciated!

**Comment by shawnawsu** [comment]
Hi @btski,

I'm just looking at this now, it might take me a little while to dig in but the errors look like they are only related to showing the progress bar. Have you tried commenting out lines 1088 to 1138?  That might allow you to load the files while we sort out the problem.

Thanks,
Shawna

**Comment by btski** [comment]
After some additional testing, my other templates (to custom tables, which I am familiar with querying) produce the same error message but generally work. I've seen some odd behavior where only the first line in a document is read in (still trying to figure that one out). I'll try to search through the default chado tables via terminal to see if my templates added anything. I'm still getting used to navigating SQL databases so I might have overlooked some things. Thanks for the feedback @shawnawsu!

<b>Edit1</b> - I see no evidence that any accessions are stored within the chado dbxref table. I used the following query (all of the accessions I've attempted to deposit start with "GenBank"):
select * from chado.dbxref where accession LIKE 'Gen%';

<b>Edit2</b> - Correction, both of the sample files I provided begin with "test". I've tested additional files with accessions that should begin with the "GenBank" root. I've found no matches within the database.

**Comment by spficklin** [comment]
Hi @btski can you export your loader template?  if you go to the page with your bulk loader templates (Here on Tripal v3:  Home » Administration » Tripal » Chado Data Loaders » Bulk Loader and click the Templates tab) then you can export the template.  If you can do that and share a sample input file we could test on our end and see what the problem may be.

**Comment by btski** [comment]
Update:

I'm able to successfully load data to custom tables within Chado. In the process, I get the first two errors concerning line 1094 but the data loads fine ("Loading Completed Successfully" status). The third error (line 1228) only occurs when I attempt to deposit data into the dbxref Chado table ("Errors Encountered" load status). 

The template I'm using is highly simplified:
[{"table":"dbxref","record_id":"dbxref_swinedb","mode":"insert","fields":[{"type":"table field","title":"accession","field":"accession","required":0,"spreadsheet column":"1","exposed":0,"exposed_description":""},{"type":"foreign key","title":"db_id","field":"db_id","show_all_records":0,"foreign key":"db_swinedb","foreign field":"db_id","required":0}],"select_if_duplicate":1,"update_if_duplicate":0,"select_optional":0,"disable":0,"optional":0},{"table":"db","record_id":"db_swinedb","mode":"select_once","fields":[{"type":"constant","title":"name","field":"name","required":0,"constant value":"SwineDB","exposed":0,"exposed_validate":0}],"select_if_duplicate":0,"update_if_duplicate":0,"select_optional":0,"disable":0,"optional":0}]

My test files:
[test_RNA_noheader.txt](https://github.com/tripal/tripal/files/1533062/test_RNA_noheader.txt)
[test_AA_noheader.txt](https://github.com/tripal/tripal/files/1533063/test_AA_noheader.txt)

This is the same information provided in an edit of my initial post. Please let me know if I misunderstood what you were requesting @spficklin.

<b>Edit1</b> - It seems that line 1228 only triggers in the event the load was not completed successfully (generic error message). I'm unsure of how to troubleshoot the problem in this instance.

<b>Edit2</b> - Editting out the function containing line 1228 allowed me to get a "Loading Completed Successfully" status. I'm still struggling to find my data within the table. There are thousands of pre-loaded datum which clutter the table and seem to be unnecessary (example: 21 |     5 | genus                                                                                                     |         | NCBITaxon:genus). There are 3500 lines of pre-loaded data. My data was not loaded.

<b>Edit3</b> - I'm unable to load the file "Fragaria.txt" using the demo template, which has worked for me before in past Tripal instances. I'm fairly confident my current Tripal instance is not functioning correctly, so I'll launch a new Tripal instance and see if that fixes things.

<b>Edit4</b> - The new instance produces the same error messages:

- Notice: Undefined index: select_if_duplicate in tripal_bulk_loader_load_data() (line 203 of /var/www/html/sites/all/modules/tripal/tripal_bulk_loader/includes/tripal_bulk_loader.loader.inc).
- Notice: Undefined index: update_if_duplicate in tripal_bulk_loader_load_data() (line 204 of /var/www/html/sites/all/modules/tripal/tripal_bulk_loader/includes/tripal_bulk_loader.loader.inc).
- Notice: Undefined index: disable in tripal_bulk_loader_load_data() (line 205 of /var/www/html/sites/all/modules/tripal/tripal_bulk_loader/includes/tripal_bulk_loader.loader.inc).
- Notice: Undefined index: optional in tripal_bulk_loader_load_data() (line 206 of /var/www/html/sites/all/modules/tripal/tripal_bulk_loader/includes/tripal_bulk_loader.loader.inc).
- Notice: Undefined index: select_optional in tripal_bulk_loader_load_data() (line 207 of /var/www/html/sites/all/modules/tripal/tripal_bulk_loader/includes/tripal_bulk_loader.loader.inc).
- Notice: Use of undefined constant STDOUT - assumed 'STDOUT' in tripal_bulk_loader_progress_bar() (line 1094 of /var/www/html/sites/all/modules/tripal/tripal_bulk_loader/includes/tripal_bulk_loader.loader.inc).
- Warning: fputs() expects parameter 1 to be resource, string given in tripal_bulk_loader_progress_bar() (line 1094 of /var/www/html/sites/all/modules/tripal/tripal_bulk_loader/includes/tripal_bulk_loader.loader.inc).
- Notice: Undefined offset: 0 in process_data_array_for_line() (line 853 of /var/www/html/sites/all/modules/tripal/tripal_bulk_loader/includes/tripal_bulk_loader.loader.inc).
- Warning: Invalid argument supplied for foreach() in process_data_array_for_line() (line 853 of /var/www/html/sites/all/modules/tripal/tripal_bulk_loader/includes/tripal_bulk_loader.loader.inc).
- Error: Call to undefined function drush_set_error() in tripal_bulk_loader_finish_loading() (line 1228 of /var/www/html/sites/all/modules/tripal/tripal_bulk_loader/includes/tripal_bulk_loader.loader.inc).

The only change I've made in installation protocol is I've changed permissions in a few files/directories (for example, I made this change to enable file download with PHP script: "sudo chmod a+wrx /var/www/html/modules/php/php.module"). I suppose I'll try to make yet another instance referring only to old notes (shared in another thread: https://github.com/tripal/tripal/issues/175)

<b>Edit5</b> - Slight change to custom simple template, still won't work. Installed two fresh Tripal instances. No luck. Will try to compare Tripal versions 2+ months old if available.

**Comment by btski** [comment]
Update:

I think I've figured it out. I was messing up the load order by creating dbxref values before establishing the associated db, which I didn't expect to be significant. Additionally, the problem I was having with the loading the demo file is that the given db name in the instructions ("NCBI Taxonomy") did not exist. Instead, it's "NCBITaxon".
