### ISSUE TITLE
Check for new fields fails on certain content types

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal#1994]
### Tripal Version

4.x

### Drupal Version

10.3.7-dev 

### PostgreSQL Version

16.4 (Debian 16.4-1.pgdg110+2) 

### PHP Version

8.3.12

### General Description

Checking for new fields on some content types works fine but when doing the same for analysis content types, there is a fatal exception due to the array key 'foreign_key' not existing in the TripalDbxSchema::getForeignKeyDef() function.

### Steps to reproduce

Certain basic content types like organism and contact work OK, but ones that are a little more complicated, such as those with foreign keys related to other content types, such as analysis and project, fail.

To test, click the "Check for new fields" for organisms (admin/structure/bio_data/manage/organism/fields) and see that it works, and then do the same for analysis (admin/structure/bio_data/manage/analysis/fields) and see that a fatal exception occurs.

### Error messages

```shell
TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in array_key_exists() (line 707 of modules/contrib/tripal/tripal/src/TripalDBX/TripalDbxSchema.php).

Drupal\tripal\TripalDBX\TripalDbxSchema->getForeignKeyDef('analysis', 'organism') (Line: 726)
Drupal\tripal\TripalDBX\TripalDbxSchema->foreignKeyExists('analysis', 'organism') (Line: 308)
Drupal\tripal_chado\Plugin\Field\FieldType\ChadoOrganismTypeDefault::discover(Object, 'chado_organism_type_default', Array) (Line: 233)
```

**Comment by dsenalik** [comment]
Only two discover functions have only been implemented for two fields, ChadoOrganismTypeDefault and ChadoPropertyTypeDefault, so I wonder if we were negligent in testing somehow 🙈
Looks like a simple fix in `getForeignKeyDef` to first make sure there are any foreign keys

**Comment by Ferrisx4** [comment]
Thanks @dsenalik. I've implemented said simple fix. Would the fact that only those two fields have discover functions written lead to the lack of foreign keys?

**Comment by Ferrisx4** [comment]
Regardless, the scope of this issue only extends to the check for foreign keys, which is now satisfied. I'll run tests (maybe rewrite one?) and then make a PR.

**Comment by dsenalik** [comment]
I am pretty sure the lack of foreign keys is not related to the discover function, or lack thereof, but rather just the fact that there may not be a foreign key in some cases.

**Comment by dsenalik** [comment]
@Ferrisx4 I am hitting this error too. Will you submit a PR or should I?

**Comment by Ferrisx4** [comment]
Oh sorry @dsenalik, I had made these changes in this commit https://github.com/tripal/tripal/commit/04999907314589c2c7eae693ec077793b5f08204 in the branch linked on this issue but forgot to follow up and make a PR.

It looks like your change did the same thing as mine (I based it on your advice, go figure) so we can just go with yours since your branch is more up-to-date.
