### ISSUE TITLE
Create a citation generation service

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#2003]
### Task Description

This comment https://github.com/tripal/tripal/pull/1960#issuecomment-2377718708 points out that we currently generate a citation for a publication in at least two different ways.
We should have a citation generation service so this can be done in a consistent manner.
Bonus: This can also be added to the manual publication entry form, so that we can generate the citation automatically if one was not entered.

### Branch Name

tv4g4-issue2003-citation-generation-service

**Comment by laceysanderson** [comment]
YES! ❤️ 
This work was started in Tripal 3 here: https://github.com/UofS-Pulse-Binfo/tripal_citation so this design/code can inform the new citation service.

The @tripal/project-managent-commitee-pmc already discussed and agreed that the functionality in the above linked extension module should move into core.
