### ISSUE TITLE
tripaldbx extension will not be installed after import

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal#2036]
### Tripal Version

4.0.alpha3

### Drupal Version

10.3.1 

### PostgreSQL Version

16.2 

### PHP Version

8.3.10

### General Description

When trying to import a configuration using Drupal's [Configuration Manager](https://www.drupal.org/docs/administering-a-drupal-site/configuration-management/managing-your-sites-configuration), after exporting a config using the same mechanism, an error is reported:

`Configuration tripaldbx.settings depends on the tripaldbx extension that will not be installed after import.`

This may be caused by artifacts from when tripaldbx was its own module but no longer is. The initial error indicates that the tripaldbx module will not be installed after the import because it is indeed not in the core.extensions.yml file included in the config export (this file lists all of the dependencies required for a successful import). Adding an entry manually for tripaldbx in this file and trying to import (see below for steps) results in the following error:

`Unable to install the tripaldbx module since it does not exist.`

### Steps to reproduce

1. Export a full site configuration using the Configuration Manager: `/admin/config/development/configuration/full/export`
2. Optionally make changes in the configuration (not required).
3. Re-archive the yml files:
    ```shell
    tar -czvf my_config.tar.gz *.yml
    ```
4. Import the config archive: `/admin/config/development/configuration/full/import`
5. Optionally compare changes (if any)
6. Click the "Import all" button: `/admin/config/development/configuration`
7. Get the error message about tripaldbx.settings
8. Optionally clean up your config sync directory (found in the sites/default/files directory, starts with `config_` and has a long string of random characters):
    ```shell
    rm sites/default/files/config_*/sync/*.yml
    ```

### Error messages

```shell
Configuration tripaldbx.settings depends on the tripaldbx extension that will not be installed after import.
```

**Comment by Ferrisx4** [comment]
Noting what does not work here (at least yet)
Drupal seems to be diving deep, looking at what _settings_ each module depend on, and it is picking up on how Tripal still looks for tripaldbx.settings in a few spots:

 - https://github.com/tripal/tripal/blob/0229c9149076fe57b406a7a60395186c9c014f5e/tripal/tripal.install#L70
 - https://github.com/tripal/tripal/blob/0229c9149076fe57b406a7a60395186c9c014f5e/tripal_chado/tripal_chado.install#L20
 - https://github.com/tripal/tripal/blob/0229c9149076fe57b406a7a60395186c9c014f5e/tripal_chado/tripal_chado.install#L41
 - https://github.com/tripal/tripal/blob/0229c9149076fe57b406a7a60395186c9c014f5e/tripal_chado/src/Database/ChadoConnection.php#L251
 - Various commented lines in https://github.com/tripal/tripal/blob/0229c9149076fe57b406a7a60395186c9c014f5e/tripal/src/TripalDBX/TripalDbx.php for keeping things clean

I've tried changing these to point at tripal.settings and bring over the contents of the ~~tripaldbx.settings~~ `tripaldbx.schema.yml` into the ~~tripal.settings~~ `tripal.schema.yml` file to no avail.

The site that I exported the configuration from existed in a state where these changes were not made, however there is no mention or reference to tripaldbx in the exported configuration files.

**Comment by dsenalik** [comment]
I confirmed this on a 4.x on Drupal 11.1
Could it be as simple as adding something to `tripal/config/schema/tripal.schema.yml` - just guessing

**Comment by Ferrisx4** [comment]
Ah yes that is the file I meant, @dsenalik, when I moved the contents of the tripaldbx.schema.yml (tripaldbx.settings, renamed to tripal.settings) to the end of the tripal.schema.yml file. I'll edit my previous comment.


I'll push all my changes to a branch for this issue.

**Comment by Ferrisx4** [comment]
New branch for this as I work on it: https://github.com/tripal/tripal/tree/tv4g2-issue2036-tripaldbx_extension_not_installed

**Comment by dsenalik** [comment]
I was curious because I didn't even know this existed.
Good luck!

**Comment by dsenalik** [comment]
Well I built a docker on your branch and still get the same error message, so I suspect the schema yaml is not it 😞
But it is odd, `tripaldbx.settings` is not mentioned in the source code any more, except in tests, so why is the error message the same?

**Comment by Ferrisx4** [comment]
That is odd. In your database of that newly built docker, in the cache_config table, do you have any rows where cid like '%tripaldbx%'? 
I would guess not since you built the docker on the branch, so it should not have picked up anything from `tripaldbx.schema.yml`, but I want to confirm.

**Comment by dsenalik** [comment]
Well there it is in a 100% new docker not even logged in yet:
` tripaldbx.settings                                                         | a:3:{s:5:"_core";a:1:{s:19:"default_config_hash";s:43:"vvlhhhsmXnxKVzNSg7hSgXoOhVjgCH1DmCtdcU2D4Dk";}s:24:"reserved_schema_patterns";a:1:{s:6:"_test*";s:16:"testing purposes";}s:22:"test_schema_base_names";a:1:{s:7:"default";s:11:"_test_biodb";}}`

I see I still have a `tripal/config/install/tripaldbx.settings.yml` file on this branch, maybe that's why...

**Comment by Ferrisx4** [comment]
Oops I missed that file, good catch! I'm rebuilding now (again) to see. I was even making sure to [clear Docker's build cache earlier](https://gist.github.com/Ferrisx4/5242f20a1b2822d9a0b43780212bcf23)

* I moved the contents of that file into the tripal.settings.yml before removing it, see latest commit.

**Comment by dsenalik** [comment]
`docker builder prune`, built new docker, it's still in the `cache_config` table 😖
Pulled your branch and trying again...

**Comment by Ferrisx4** [comment]
Hmm it did end up disappearing for me, the only remnant of tripaldbx is in the cache_container table, and it refers to the tripaldbx class itself (which rightly still exists). Testing config export and import now.

**Comment by Ferrisx4** [comment]
Config exported and imported correctly, and the expected changes (moving genus after species on organism display pages) took effect. I'm interested to see if re-pulling the branch works for you, and if so, if all the mucking around in Tripal and Tripal Chado does not cause automated tests to fail. 🤞

**Comment by dsenalik** [comment]
~~I don't know what I was doing wrong, but I started a brand new folder, checked out the branch, built the docker, and finally the `cache_container` table is as it should be.~~

**Comment by dsenalik** [comment]
But I am still getting the error message!
`Configuration tripaldbx.settings depends on the tripaldbx extension that will not be installed after import.`
Drupal 11.1 if that is relevant.

**Comment by Ferrisx4** [comment]
In the sites/default/files/config_whatever/sync/ directory, do you still have a tripaldbx.settings.yml file?

**Comment by dsenalik** [comment]
I copied the wrong comment and checked `cache_container` by mistake. `cache_config` still has the entry

**Comment by dsenalik** [comment]
`find . -name '*tripaldbx.settings*'` = no file, that much is good
```
ls tripal/config/schema/
total 24,576
-rw-rw-r-- 1 doug_senalik doug_senalik    408 Nov 21 13:53 tripal.settings.schema.yml
-rwxrwxr-x 1 doug_senalik doug_senalik    848 Nov 21 13:53 tripal_entity_type.schema.yml
-rw-rw-r-- 1 doug_senalik doug_senalik 13,778 Nov 21 13:53 tripal.schema.yml
```

**Comment by dsenalik** [comment]
Probably unrelated, but it looks like you should have moved that chunk of yaml to `tripal.settings.schema.yml` instead of `tripal.schema.yml` because it already has a `tripal.settings` section

**Comment by Ferrisx4** [comment]
Good catch, I see what you mean. I believe https://github.com/tripal/tripal/commit/accca1b816480ee971db8aedabf36fd062d81707 should do the trick.

**Comment by Ferrisx4** [comment]
I'm still not sure why your instance still has tripaldbx.settings remnants hanging around. I'll do a Tripal Docker build myself (I've been using my i5k-specific Docker to re/build).

I wonder if this has anything to do with what @laceysanderson mentioned about the cached version of Tripal that allows the Tripal Docker to spin up so quickly. In my Docker configuration, it builds a Drupal site from scratch each time, installing Tripal along the way.

**Comment by dsenalik** [comment]
I also tried building a drupal docker + tripal docker myself as described in PR #2005 and had the same results.
Inside my drupal docker, no trace of the tripaldbx entry
```
sitedb=> select * from cache_config where cid like '%tripal%';
 cid | data | expire | created | serialized | tags | checksum 
-----+------+--------+---------+------------+------+----------
(0 rows)
```

**Comment by Ferrisx4** [comment]
I wonder where it's coming from, then. 🙃  At one point I had dumped the entire database to a text file and grepped for `tripaldbx` which is how I found this table in the first place, as well as the legitimate one in `cache_container`.

**Comment by Ferrisx4** [comment]
Finally was able to build a Tripal Docker instance as described in https://github.com/tripal/tripal/pull/2005 however I was able to successfully export and re-import a configuration.

To be clear, are you still experiencing `Configuration tripaldbx.settings depends on the tripaldbx extension that will not be installed after import.`?

**Comment by dsenalik** [comment]
I am trying to debug that it might be something I have cached.
I installed docker-ce on a new server and I am still seeing `tripaldbx.settings` in `cache_config`.
To debug that it might be something I have cached, I built on 4.x with an extra thing in the 4.x yaml. That extra item showed up in `cache_config`. Then without clearing anything I built on this branch. The extra thing was not in `cache_config` but this is still there `tripaldbx.settings | a:3:{s:5:"_core";a:1:{s:19:"default_config_hash";s:43:"vvlhhhsmXnxKVzNSg7hSgXoOhVjgCH1DmCtdcU2D4Dk";}s:24:"reserved_schema_patterns";a:1:{s:6:"_test*";s:16:"testing purposes";}s:22:"test_schema_base_names";a:1:{s:7:"default";s:11:"_test_biodb";}}`

**Comment by Ferrisx4** [comment]
tripaldbx.settings is very persistent :( I built on a completely new server (freshly installed Debian inside of a brand new installation of VMWare Workstation), so it couldn't have been cleaner. I did not build on 4.x first though, so some Docker mechanism seems to be keeping it around. Weird that the other extra thing in the 4.x yaml did not stick around...

**Comment by dsenalik** [comment]
I can use a reduced Tripal Dockerfile without the chado install steps, and if I remove this one line where modules are enabled 
`&& vendor/bin/drush en ${allmodules} -y \`
and then enable them myself in the running docker
`vendor/bin/drush en tripal tripal_biodb tripal_chado tripal_layout devel devel_php field_group field_group_table`
everything is good. But if they are enabled when the docker is build, `tripaldbx.settings` appears.

I think that during this step, the "default" tripal is used, not the mounted volume version. 
I put these two lines in the Dockerfile,
`&& ls -l /var/www/drupal/web/modules/contrib/tripal/tripal/config/install/ \`
`&& ls -l /var/www/drupal/web/modules/contrib/tripal/tripal/config/schema/ \`
and will ya look at that:
```
#8 0.252 Starting Apache httpd web server: apache2.
#8 1.364 Starting PostgreSQL 16 database server: main.
#8 3.708 total 44
#8 3.708 -rw-r--r-- 1 root www-data  1340 Nov 22 18:45 tripal.settings.yml
#8 3.708 -rwxr-xr-x 1 root www-data   843 Nov 22 18:45 tripaldbx.settings.yml
#8 3.708 -rw-r--r-- 1 root www-data 34145 Nov 22 18:45 views.view.tripal_jobs.yml
#8 3.709 total 28
#8 3.709 -rw-r--r-- 1 root www-data 13425 Nov 22 18:45 tripal.schema.yml
#8 3.709 -rw-r--r-- 1 root www-data   659 Nov 22 18:45 tripal.settings.schema.yml
#8 3.709 -rwxr-xr-x 1 root www-data   848 Nov 22 18:45 tripal_entity_type.schema.yml
#8 3.709 -rwxr-xr-x 1 root www-data   305 Nov 22 18:45 tripaldbx.schema.yml
#8 3.713 Stopping Apache httpd web server: apache2.
#8 4.836 Stopping PostgreSQL 16 database server: main.
```

**Comment by dsenalik** [comment]
I think I finally figured it out 😀
When the docker is built, it copies your local files OVER a base image of the 4.x tripal files.
This means, a file deleted in a branch IS STILL THERE when the docker is built.
I made two placeholder files with a single `#` each and FINALLY tripaldbx.settings is GONE!

```
diff --git a/tripal/config/install/tripaldbx.settings.yml b/tripal/config/install/tripaldbx.settings.yml
new file mode 100644
index 000000000..792d60054
--- /dev/null
+++ b/tripal/config/install/tripaldbx.settings.yml
@@ -0,0 +1 @@
+#
diff --git a/tripal/config/schema/tripaldbx.schema.yml b/tripal/config/schema/tripaldbx.schema.yml
new file mode 100644
index 000000000..792d60054
--- /dev/null
+++ b/tripal/config/schema/tripaldbx.schema.yml
@@ -0,0 +1 @@
+#
```

**Comment by Ferrisx4** [comment]
That's excellent! Figured it had to be Docker shenanigans at work.

I think this means we're ready for a PR, I can't find any more traces of tripaldbx.settings anywhere.

**Comment by Ferrisx4** [comment]
Right after I clicked the button to make a PR, I thought it might be a good idea to provide unit tests for this configuration export/import function, at least as far as Tripal-centric configurations are concerned. Since Drupal 10+ will be files-as-config heavy, this seems worth it. Not sure it is within the scope of this issue, however -  @laceysanderson @dsenalik, thoughts?

**Comment by dsenalik** [comment]
I think tests would be appropriate here, but I don't feel too strongly either way.
