### ISSUE TITLE
getColumnTermId() on null during full site configuration import 

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal#2041]
### Tripal Version

4.0.alpha3

### Drupal Version

10.3.1

### PostgreSQL Version

16.2

### PHP Version

8.3.10

### General Description

When importing a full site, including Tripal content types with custom field display layouts applied, the following error is encountered:
`Call to a member function getColumnTermId() on null" at /opt/drupal/web/modules/custom/tripal
/tripal_chado/src/Plugin/Field/FieldType/ChadoStringTypeDefault.php line 111`

After this occurs, every site on the page ends with the modern version of WSOD :`The website encountered an unexpected error. Try again later.`

---
*Either base_table or $base_column are NULL and I'm not sure why or which one... yet, will investigate in the morning.*

### Steps to reproduce

1. On a new site, on one of the Tripal content types, rearrange fields and add new field groups.
2. Export this configuration at `/admin/config/development/configuration`
3. Recreate the site, making sure to use cset to set the same UUID from the previous site (this can be found in the system.site.yml file in the exported configuration: `drush cset system.site uuid <uuid> -y`
4. Try to import the exported config from earlier

### Error messages

```shell
Call to a member function getColumnTermId() on null" at /opt/drupal/web/modules/custom/tripal
/tripal_chado/src/Plugin/Field/FieldType/ChadoStringTypeDefault.php line 111
```

### Branch
https://github.com/tripal/tripal/tree/tv4g2-issue2041-getColumTermId_on_null_during_config_import

**Comment by dsenalik** [comment]
🙈 It's likely this  
    `111     $value_term = $mapping->getColumnTermId($base_table, $base_column) ?: 'NCIT:C25712';`
should be
    `111     $value_term = $mapping->getColumnTermId($base_table, $base_column) ?? 'NCIT:C25712';`
but I have the vague recollection we encountered this before...

Nevermind, it was $mapping that was null, wasn't it...

**Comment by Ferrisx4** [comment]
Ah it seems so, I read the error message wrong. This is why I couldn't get anything to trigger when I was testing $base_table and $base_column for NULL, and I should have realized I was reading it wrong when it the error did not include an argument number.

**Comment by Ferrisx4** [comment]
Taking a look at this again, with a more configured site, we've come across similar errors in other field types. For instance, ChadoDbxrefTypeDefault:
https://github.com/tripal/tripal/blob/863c94044fc078235d2f3c13ca576226395c3d39/tripal_chado/src/Plugin/Field/FieldType/ChadoDbxrefTypeDefault.php#L93C17-L93C24

In that file, there are more instances of where $mapping may not be defined and simply using the ternary operator is not enough to detect this. I know these lines are nicely organized based on the column use.

I'll try to write the checks in a way that does not clutter up the code but it may sacrifice the nicely parceled out column categories.

**Comment by Ferrisx4** [comment]
As promised, I've kept it elegant:
https://github.com/tripal/tripal/compare/4.x...tv4g2-issue2041-getColumTermId_on_null_during_config_import

However, there are 210 other instances of this in 25 other files. In the case of a configuration import, is it OK that $mapping is null in all these cases? I can go ahead and make the change, but I want to make sure this approach is not just a band-aid.

**Comment by dsenalik** [comment]
It looks like every field does this
`$storage = \Drupal::entityTypeManager()->getStorage('chado_term_mapping');`
`$mapping = $storage->load('core_mapping');`
so we could make $mapping a class variable and move this to the parent class.
Then we could have a "getter" function in the parent class that would deal with the NULL and return the default.
What do you think?

**Comment by Ferrisx4** [comment]
I think I understand - the parent class (ChadoFieldItembase) would have the getter method as well as keeping track of all the default values?
At first I was hesitant because there would be 210+ defaults for the parent to keep track of but in reality many are repeated/shared among the children so it wouldn't be very many at all.

**Comment by dsenalik** [comment]
As I envisioned it, you would pass in the default to the getter, something like

`$db_term = $mapping->getColumnTermId($object_table, 'db_id') ?: 'ERO:0001716';`

becomes something like

`$db_term = $this->getColumnTermId($object_table, 'db_id', 'ERO:0001716');`

**Comment by Ferrisx4** [comment]
So `$this->getColumnTermId($table, $column, $default)` would be a wrapper around 
```php
$storage = \Drupal::entityTypeManager()->getStorage('chado_term_mapping');
$mapping = $storage->load('core_mapping');
```
inside the parent class? or am I just not understanding your approach

**Comment by dsenalik** [comment]
I was thinking of something like this inside `tripal_chado/src/TripalField/ChadoFieldItemBase.php` - not tested in any way of course. and then we could call like `$db_term = self::getColumnTermId($object_table, 'db_id', 'ERO:0001716');`
```
  protected static $mapping = NULL;

  public static function getColumnTermId(string $table, string $column, string $default_term): string {
    $id = $default_term;
    if (is_null(self::$mapping)) {
      $storage = \Drupal::entityTypeManager()->getStorage('chado_term_mapping');
      self::$mapping = $storage->load('core_mapping');
    }
    if (self::$mapping) {
      $id = $mapping->getColumnTermId($table, $column);
      if (!$id) {
        $id = $default_term;
      }
    }
    return $id;
  }
```

**Comment by laceysanderson** [comment]
I agree with @dsenalik's approach in [the above comment](https://github.com/tripal/tripal/issues/2041#issuecomment-2546982438) except I think we would make it a protected method/variable and not a static one. This way it helps with performance more and we shouldn't need it outside of the object context anyway.

**Comment by Ferrisx4** [comment]
Ok that's good, I just pushed a ton of changes to the branch to reflect that :D 
We're testing it now in an import so we'll know soon!

**Comment by Ferrisx4** [comment]
Other than a few typos that I'm pinging off as we go, I'm stuck on the error `Cannot create a StorageProperty object for entity type "tripal_entity", field type "chado_sequence_coordinates_default", key "uniquename" without a properly formatted term: "schema_name"`

Unless there's an easy typo that I'm missing, I'm not sure if this is a one-off thing with this field or if it's a sign of other issues. Typically through testing the ChadoPubTypeDefault is the first one encountered if there are any issues throughout.

**Comment by laceysanderson** [comment]
Thats because there is a typo in that field. Specifically, you need to make this change (note the `:` instead of `_`:
```diff
- $ft_uniqname_term = self::getColumnTermId('feature', 'name', 'schema_name');
+ $ft_uniqname_term = self::getColumnTermId('feature', 'name', 'schema:name'); 
```

**Comment by Ferrisx4** [comment]
Thanks for the second set of eyes Lacey! The same line is correct in other fields.

**Comment by dsenalik** [comment]
Huh. I thought it had to be static because the tripalTypes function is static. Slowly learning...

**Comment by Ferrisx4** [comment]
Made a small change to the function itself to use the same variable throughout - https://github.com/tripal/tripal/commit/a4135610ba7c3cbb219f9a69ad6be399e7e4c5e2

With this, Tripal is no longer triggering errors during whole-site configuration imports.
