### ISSUE TITLE
Chado installation problem

### ISSUE THREAD

**Issue by mdondrup** [tripal/tripal#2044]
### Tripal Version

0229c91

### Drupal Version

11.0.9

### PostgreSQL Version

17.2

### PHP Version

8.3.14

### General Description

Error occurs during Chado 1.3 installation

### Steps to reproduce

Install  drupal, istall tripal from git.
Datastorage -> Chado -> Install Chado
Run job

### Error messages

```shell
[almalinux@licebase2-alma tripal]$ /var/www/tripal4/vendor/bin/drush trp-run-jobs --job_id=4 --username=lb_admin --root=/var/www/tripal4/web

2024-12-02 14:55:22
Tripal Job Launcher
Running as user 'lb_admin'
-------------------
2024-12-02 14:55:22: Job ID 4.
2024-12-02 14:55:22: Calling: tripal_chado_install_chado(chado, 1.3)
 [error]  ERROR: SQLSTATE[42883]: Undefined function: 7 ERROR:  function create_point(integer, bigint) does not exist
LINE 1: SELECT box (create_point(0, $1), create_point($2,500000000))
                    ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT box (create_point(0, $1), create_point($2,500000000))
CONTEXT:  SQL function "boxrange" during inlining
[site http://default] [TRIPAL] ERROR: SQLSTATE[42883]: Undefined function: 7 ERROR:  function create_point(integer, bigint) does not existLINE 1: SELECT box (create_point(0, $1), create_point($2,500000000))                    ^HINT:  No function matches the given name and argument types. You might need to add explicit type casts.QUERY:  SELECT box (create_point(0, $1), create_point($2,500000000))CONTEXT:  SQL function "boxrange" during inlining
 [error]  Schema installation part 3 of 41 Failed...
Installation (Step 1 of 2) problems!
 [error]  Message: Job execution failed: Failed to complete Chado installation task.
Schema installation part 3 of 41 Failed...
Installation (Step 1 of 2) problems!
```

**Comment by laceysanderson** [comment]
Oh, I hate this error 🙈 

>  [error]  ERROR: SQLSTATE[42883]: Undefined function: 7 ERROR:  function create_point(integer, bigint) does not exist
> LINE 1: SELECT box (create_point(0, $1), create_point($2,500000000))
>                     ^
> HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
> QUERY:  SELECT box (create_point(0, $1), create_point($2,500000000))
> CONTEXT:  SQL function "boxrange" during inlining

That said, I haven't ever seen it show up on install 🤔 I just tested this with PostgreSQL 16.6, PHP 8.3.14, Drupal 11.0.1-dev, Tripal commit 0229c9149076fe57b406a7a60395186c9c014f5e and did not experience this error (or any error) during Chado installation. Perhaps it is specific to the PostgreSQL version or perhaps it is intermittent. 

Could you try the chado install a few times to check if it is repeatable?

**Comment by dsenalik** [comment]
I encountered this error way back in 2017!
Check your search path
`show search_path;`
and if it does not include chado, you will need to add it.

My docker startup script I always do this to include various possible names for chado:
`export PGPASSWORD=drupaldevelopmentonlylocal`
`psql -h localhost -U drupaladmin -d sitedb -c "ALTER DATABASE sitedb SET SEARCH_PATH TO 'public', 'chado', 'testchado', 'teacup'"`

**Comment by laceysanderson** [comment]
> I encountered this error way back in 2017! Check your search path `show search_path;` and if it does not include chado, you will need to add it.
> 
> My docker startup script I always do this to include various possible names for chado: `export PGPASSWORD=drupaldevelopmentonlylocal` `psql -h localhost -U drupaladmin -d sitedb -c "ALTER DATABASE sitedb SET SEARCH_PATH TO 'public', 'chado', 'testchado', 'teacup'"`

Interesting! I don't do this but have never encountered this error in Tripal 4 🤔

**Comment by dsenalik** [comment]
To be clear, I only see the error when restoring the database from a backup, not on initial install.

This is my db restore command
```
cat "$file" \
  | sed -e 's/CREATE INDEX binloc_boxrange/SET search_path = frange, chado, pg_catalog;\nCREATE INDEX binloc_boxrange/' \
  | psql \
  --set ON_ERROR_STOP=on \
  --username="drupaladmin" \
  --host=localhost \
  --dbname=sitedb
```

**Comment by mdondrup** [comment]
I have gone back to a stack more similar to the documentation with postgres 16, drupal 11 on Debian and it works. Possibly, the problems are connected to postgres 17.

**Comment by dsenalik** [comment]
Thanks for the update. I guess this means we should start testing on postgres 17 😮 #2048
