### ISSUE TITLE
Error if field debugger activated but devel module is not installed

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#2059]
### Task Description

As mentioned in this comment
https://github.com/tripal/tripal/issues/1823#issuecomment-2528462108
we have some `dpm()` in Tripal for the field debugger. Also some in the PubParserManager but those are (should be) temporary and be removed.
We always install the devel module in our dockers, but our official traditional install instructions do not mention this module.

I am thinking we could gray out the field debugger toggle if the devel module is not installed, then the dpm's will never be called. Plus maybe add a "requires the devel module" or something when it is grayed out.

### Branch Name

tv4g1-issue2059-field-debugger-if-no-devel-module

**Comment by laceysanderson** [comment]
Another option is to check if devel is installed, if so then keep the dpm because it has better formatting, if not then use a combination of drupal set message and print_r() in pre tags.

**Comment by dsenalik** [comment]
That was such a genius idea, and it is turning out to be not too hard to implement
