### ISSUE TITLE
Remove function tripal_set_default_cv from tripal_chado.cv.api.inc

### ISSUE THREAD

**Issue by shawnawsu** [tripal/tripal#206]
Per the conversation in the closed pull request, https://github.com/tripal/tripal/pull/201, we need to remove function tripal_set_default_cv (line 1617 of tripal/trupal_chado/api/modules/tripal_chado.cv.api.inc) as it's no longer used and we do not want to continue with the use of the tripal_cv_defaults table.

**Comment by bradfordcondon** [comment]
note #200 duplicate issue , I'll just close that one

**Comment by spficklin** [comment]
Yes, this should be removed the Tripal v3 but it should get moved back to the Legacy API for backwards compatibility.

**Comment by spficklin** [comment]
Closing as @bradfordcondon fixed this with a pull request.
