### ISSUE TITLE
Warning during Tripal 3 migration

### ISSUE THREAD

**Issue by dsenalik** [tripal/tripal#2067]
### Tripal Version

4.x

### Drupal Version

11.1, 10.3

### PostgreSQL Version

16

### PHP Version

8.4, 8.3

### General Description

I am migrating my Tripal 3 site as described at
https://tripaldoc.readthedocs.io/en/latest/upgrade_guide/site/migrating_chado.html
At step 6 I see this error
![null](https://github.com/user-attachments/assets/e2fad1e1-c9c0-4fb9-9a32-1e0a646ef9b9)

### Steps to reproduce
I see at 
Tripal → Data Storage → Chado → Prepare Chado
and at 
Tripal → Data Storage → Chado → Chado Schemas

### Error messages

```shell
.
```

### Screenshots

.

**Comment by Ferrisx4** [comment]
Good to know about. I wonder if it has anything to do with the shuffling of the tripal settings that we did in https://github.com/tripal/tripal/pull/2037/files for https://github.com/tripal/tripal/pull/2037, since that part of the code is looking for that particular config.
