### ISSUE TITLE
Just some suggestions about PHP 5.5+

### ISSUE THREAD

**Issue by ghost** [tripal/tripal#207]
I checked the code and I realized that half of it is object-oriented while another half is structural code. I think the code would be more coherent if you'd use only a single paradigm.

Includes in structural code could be totally replaced with [`use` statements](http://php.net/manual/en/language.namespaces.importing.php) and [autoloading](http://php.net/manual/en/language.oop5.autoload.php) and if you include something on the fly, then you could use [dependency injection](https://en.wikipedia.org/wiki/Dependency_injection) and probably an [interface](http://php.net/manual/en/language.oop5.interfaces.php) to do so. Using [namespaces](http://php.net/manual/en/language.namespaces.importing.php) instead of underscores would be a step forward too. By the coding style there are [PSR recommendations](http://www.php-fig.org/psr/) by PHP. All of these are working language features in PHP 5.5 and I think they could make the development and maintenance of this project easier.

**Comment by ghost** [comment]
Hmm I might be wrong and this kind of structure is required because of Drupal.

**Comment by spficklin** [comment]
Hi @inf3rno . Thanks for the suggestions. We're always open for idea towards improvement.   Traditionally, Tripal was 100% non OO.  Drupal was as well.   We are slowly moving towards an object oriented approach but it takes time to make that conversion.  So, that's why you see the mixed implementation right now.  But you're right, Drupal is mixed as well and it's hook system is by nature non-OO so unless Drupal changes that paradigm we're stuck with a mixed bag.  

Drupal has a mechanism to keep the interpreted code light by using includes only when needed by explicitly indicating include files in menu, theme and form definitions and we try to do that as much as possible.  

But we can definitely look more into using namespaces, and if you have suggestions for specific changes we're all ears!

**Comment by spficklin** [comment]
Marking this as closed but feel free to reopen if you want to discuss more on this.

**Comment by ghost** [comment]
@spficklin I think you should decide whether your project wants to depend on Drupal and its future releases or you want to do something independently, which can use Drupal as one of many possible presentations. If the first is true, then you don't have to do anything. If the second is true, then you have an architectural problem and mixing coding paradigms is just a sign that we are talking about 2 very different projects here, which you need to decouple from each other. If we'd talk about DDD projects and the upstream project would affect the domain model of the downstream project, then we'd talk about a [conformist relationship](http://www.markhneedham.com/blog/2009/03/30/ddd-recognising-relationships-between-bounded-contexts/), which can be cured with an anti-corruption layer. I think these terms are valid only in DDD context, but you can use an analogy.  You can design a layer of adapters, which depend on Drupal, and your project would use these adapters instead of calling Drupal functions directly. This way if you designed good enough interfaces for these adapters, then you can replace Drupal with for example Wordpress by implementing the same interfaces in your Wordpress adapters. You can write integration tests for the adapters, and whenever you upgrade Drupal or Wordpress you just need to run the tests and fix the adapters if they are broken. If you are lucky then your projects application services and business logic does not depend on Drupal functions, and you can do for example a [multi-tier architecture](https://en.wikipedia.org/wiki/Multitier_architecture), where Drupal is just a possible presentation without the need for writing adapters. But I somehow doubt that it will be such easy. I am not an experienced software engineer (it's just a hobby), so I might be wrong about everything. :-)

**Comment by spficklin** [comment]
You make a very good point.  It would be ideal if we could layer Tripal in a multi-tier system that separate domain-specific needs from "presentation" that tools like Drupal provides.   Our Tripal core developers have discussed this in the past.  Aside from discussion, we have not explored too deeply.  But, it's definitely something we can revisit.

Just curious, are you working on building a Tripal site?

**Comment by ghost** [comment]
@spficklin No, I just read your introduction by the Hydra mailing list, so I decided to check the code. I follow Hydra for a few years now, I'll develop a few hobby projects with it. On the other hand I am a biochemical engineer too, so I find both topic interesting.
