### ISSUE TITLE
Cron issues

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#208]
In the past for Tv3, the cron would perform a few checks which could end up slowing the site down as Drupal will sometimes initiate the cron as user's visit the page.  So, we moved some of those long running tasks into Tripal jobs and now the cron just submitts them.  But now they pile up in the job queue!   I had 97 jobs to run this morning on my dev site.  

We should adjust that code to not submit the cron jobs again if they are already in the Tripal job queue.

**Comment by bradfordcondon** [comment]
Any update on this?
i had 25,000 jobs this evening on the dev site!  These are the three jobs:

```
tripal_expire_collections()
tripal_galaxy_check_status()
tripal_tripal_cron_notification()
```

**Comment by spficklin** [comment]
Yikes, 25K jobs!  I just committed a fix that should stop this from happening.  If the job already exists in the queue it won't add it again.  When adding a new job you can override this behavior, if you want, by setting the ignore_duplicate parameter to FALSE when using the tripal_add_job() function.    I've tested it and it works, so I'll close the issue, but if you still have a problem please reopen.

**Comment by bradfordcondon** [comment]
Hi Stephen,

Looking at this with @almasaeed2010 ... it looks like manually calling `tripal_add_job()` wont pass the `ignore_duplicate` parameter.

This is because when the job is created:
```
  try {
    $job->create(array(
      'job_name' => $job->getJobName(),
      'modulename' => $job->getModuleName(),
      'callback' => $job->getCallback(),
      'arguments' => $arguments,
      'uid' => $user_id,
      'priority' => $job->getPriority(),
      'includes' => $includes
    ));
```

the ignore duplicate would be in $arguments.

But looking at the create method, it checks for ` $details[‘ignore_duplicate’]` and not   `$details[‘arguments’][‘ignore_duplicate’]`

**Comment by spficklin** [comment]
Good catch.  I forgot to extend that argument to the tripal_add_job() function.  I've fixed it.   Although the code in the TripalJob.create() method should be $details['ignore_duplicate'] as the 'arguments' key is meant for arguments that get passed to the callback function and ignore_duplicate is meant for the create function.  This time I'll leave things open until you're happy with it.

**Comment by bradfordcondon** [comment]
looks good to me, thanks Stephen.  I can't close the issue myself anymore lol so please go ahead and close it when you can ready.

e- oops, it was never mine, go figure.  anyway, we're happy so close away

**Comment by laceysanderson** [comment]
I'm experiencing this again on the most recent dev version :-( I'm looking into the problem.

**Comment by spficklin** [comment]
The issue resurfaced with this fix for issue #280 

I've not hat time to sit down and dig into it....

**Comment by laceysanderson** [comment]
It looks like a parameter was just missed causing a shift in the parameters. Specifically, Priority is missing

```diff
diff --git a/tripal/tripal.module b/tripal/tripal.module
index a67c3e4..512ec39 100755
--- a/tripal/tripal.module
+++ b/tripal/tripal.module
@@ -1059,14 +1059,30 @@ function tripal_cron() {
     $modules = module_implements('tripal_cron_notification');
     foreach ($modules as $module) {
       $function = $module . '_tripal_cron_notification';
-      tripal_add_job("Cron: Checking for '$module' notifications.", 'tripal',
-        $function, $args, 1, $includes, TRUE);
+      tripal_add_job(
+        "Cron: Checking for '$module' notifications.",    // Job Name
+        'tripal',                                         // Module Name
+        $function,                                        // Callback
+        $args,                                            // Arguements
+        1,                                                // User UID
+        1,                                                // Priority (1-10)
+        $includes,                                        // Includes
+        TRUE                                              // Ignore Duplicates
+      );
     }
   }
 
   // Check for expired collections.
-  tripal_add_job('Cron: Checking expired collections', 'tripal',
-    'tripal_expire_collections', $args, 1, $includes, TRUE);
+  tripal_add_job(
+    'Cron: Checking expired collections',             // Job Name
+    'tripal',                                         // Module Name
+    'tripal_expire_collections',                      // Callback
+    $args,                                            // Arguements
+    1,                                                // User UID
+    1,                                                // Priority (1-10)
+    $includes,                                        // Includes
+    TRUE                                              // Ignore Duplicates
+  );
 }
```

Notice that there are two `1` in the updated code versus the original code. I figured it would be good to set the priority low on these jobs and assume you specified `1` as the UID to ensure it was ran by the admin user rather then the current user?

I'm working on another branch and will use a pull request as indicated in the user meeting to ensure tests still pass :-)

**Comment by laceysanderson** [comment]
Fix Merged into 7.x-3.x :-)
