### ISSUE TITLE
SQL Error: Undefined column "is_current" in featuremap_dbxref Chado table

### ISSUE THREAD

**Issue by ksbuble** [tripal/tripal#209]
When loading a published map page ex. (https://<site_base_url>/bio_data/<featuremap_id>) with 
a recent version of Tripal 3 (Nov 17, 2017 or newer) this SQL error occurred:
 
PDOException: SQLSTATE[42703]: Undefined column: 7 ERROR: column "is_current" does not exist LINE 1: ...T featuremap_dbxref_id, featuremap_id, dbxref_id, is_current... ^: SELECT featuremap_dbxref_id, featuremap_id, dbxref_id, is_current FROM chado.featuremap_dbxref WHERE featuremap_id = :featuremap_id0 ; Array ( [:featuremap_id0] => 440 ) in chado_query() (line 1667 of /<site base path>/drupal-7.41/sites/all/modules/tripal/tripal_chado/api/tripal_chado.query.api.inc).

The "is_current" column was not present in the Chado featuremap_dbxref table. After replacing the Tripal code with the tripal-7.x-3.0-rc2 release code the SQL error disappeared.

**Comment by spficklin** [comment]
@ksbuble can you describe what happened when you received this message?  Were you loading a published map page?  Were you trying to publish map pages?

**Comment by ksbuble** [comment]
@spficklin Yes this occurred during loading of a published map page. Please see updated description above.

**Comment by shawnawsu** [comment]
@ksbuble A few follow up questions. When you swap branches are you running update.php and which version of chado are you using?

**Comment by ksbuble** [comment]
Update.php was not run after reverting to tripal-7.x-3.0-rc2 release. The chado version is: 1.2.
@shawnawsu

**Comment by laceysanderson** [comment]
Are you still experiencing this problem @ksbuble ?

**Comment by bradfordcondon** [comment]
hey, I had this problem too!  #372 . (I dont bring up the is_current field there, but its part of my whole host of issues i had trying to upgrade my site's chado install). I manually added the `is_current` column to my site. 
You can see my full pondering and solving of the issue on my site's repo:

https://github.com/statonlab/hardwoods_site/issues/268

Short answer: its a mystery when these tables were added without that column, but our HWG site was also missing it...

**Comment by spficklin** [comment]
It sounds to me that this is an upgrading problem with tables where created manually in Chado v1.2 but are not identical to the Chado v1.3 versions of the same tables that got added later.   

I think since we have not heard back on this and @bradfordcondon confirms the fix is just adding the missing column I'm going to mark this closed.

**Comment by ksbuble** [comment]
We also found the issue related to a missing column in Chado. Adding the column resolved the problem.  (Sorry for the late reply. I am on vacation.)
