### ISSUE TITLE
Views/Chado DB table/Dropdown menu filter?

### ISSUE THREAD

**Issue by srobb1** [tripal/tripal#212]
Hi. I hope this is any easy one.

I have created a view that uses Chado DB Description in a filter. The drop down select is not available only the text box filter. Any ideas on how to get the drop down menu as an option? Other filters in this view allow me to have drop down menus. I checked out the views integration for the description field, "views_handler_filter_string" is selected.

Thank you,
Sofia

**Comment by shawnawsu** [comment]
Hi Sofia, 

Sorry for the delayed response. I'm not entirely clear what you're asking, can you give me a bit more info?

Thanks!
Shawna

**Comment by srobb1** [comment]
Hi Shawa,

Thanks for replying. 

I have a View for which I would like to create a drop down filter of DB descriptions. Currently I have Chado DB names (See first filter: https://planosphere.stowers.org/search/rosetta-stone-transcript-mapper). I would like to replace the DB names with the DB description but I do not have the option of a drop down box, only text box. How do I get a drop box? Is this more clear? Please let me know if you need any more info.

Thank you so much!
Sofia

**Comment by laceysanderson** [comment]
Hi Sofia,

I assume this is for Tripal 2.x? If so, normally you would just need to create a new views integration for the db table that sets the views filter handler (2nd drop-down) for the description field to `tripal_views_handler_filter_select_string`. However, there is currently a bug in Tripal 2.x making this filter not an option (see #176) :-(. There is a fix mentioned but it requires editing core Tripal at the moment. I'll try to get to adding a patch...

> I pointed out that "tripal/tripal_views/includes/tripal_views_integration_UI.inc" was missing those filters at line 1402.
> $handlers[] = 'tripal_views_handler_filter_select_cvterm'; $handlers[] = 'tripal_views_handler_filter_select_string';
> After patching the file and clearing the cache, I was able to select again those handlers and all went back to normal.

**Comment by srobb1** [comment]
Hi Lacey,

Thank you!!! I can edited the code as is described above. It works. 

But I am having a different issue. I am getting back all the descriptions in the DB database even though I set up a views relationship between my custom table and the DB table and require results to use the relationship. In my filter setup I do select the relationship. I used the devel to print all query and "select description from chado.db" is being executed and not filtered on the relationship I think it should be using. Any ideas?

**Comment by srobb1** [comment]
Hi,

I figured this one out. It looks like the relations do not affect the filter if the db table for content type of the view is not the table with the refined list of terms. I had to use form_alter to populate the dropdown list. It is working nicely now.
