### ISSUE TITLE
Tripal version as global variable

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#214]
Consider adding a global variable that indicates the current Tripal version.  Suggestion by @almasaeed2010

**Comment by bradfordcondon** [comment]
this can be accessed via [`system_get_info`](https://api.drupal.org/api/drupal/modules!system!system.module/function/system_get_info/7.x).  so, might not be necessary.  

`dpm(system_get_info('module', 'tripal'));` yield this:

<img width="948" alt="Screen Shot 2019-07-29 at 10 09 52 PM" src="https://user-images.githubusercontent.com/7063154/62095206-a0b5b680-b24d-11e9-9e77-a42e8b795f98.png">

so we would have to *ahem* remember to update the `.info` file for this to work.  We could wrap this in an API call if you thought it would be helpful.  @almasaeed2010 do you still think it would be helpful or is the system_get_info call easy enough?

**Comment by spficklin** [comment]
Oh, I agree @bradfordcondon.  I think this should be sufficient.  We could easily wrap this up in a nice little Tripal API function to make it easy on module developers.

**Comment by laceysanderson** [comment]
Moving this over to Tripal 4 as it will not be done in Tripal 3.
