### ISSUE TITLE
Creating Entities Fail With Unique Key Violation

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#216]
Hello,

We've encountered an odd issue with entities. When deleting an entity then recreating it with identical information, we get this error:
```
Could not save the entity: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "chado_bio_data_1_table_record_key" DETAIL: Key (record_id)=(2) already exists.
Cannot save entity
```

The entity I attempted to create was an Organism in case that matters.

Thanks!

**Comment by almasaeed2010** [comment]
Also, the deleted organism entity still shows up as in the organisms list in the FASTA loader.

**Comment by shawnawsu** [comment]
Hi @almasaeed2010 ,

Was this done programmatically or through the GUI? 

Thanks!

**Comment by almasaeed2010** [comment]
Through the GUI

**Comment by shawnawsu** [comment]
So when you delete the record the chado data is not deleted, merely the tripal entity associated with it. So to publish an entity whose data is already in chado you need to 'Publish Tripal Content'.

**Comment by almasaeed2010** [comment]
Ah I see. So to delete from both, I have to remove the chado records manually?

Thanks!

**Comment by shawnawsu** [comment]
I don't know of a way to delete chado data from Tripal except manually and I'm not seeing one in the GUI.

**Comment by almasaeed2010** [comment]
Alright. Thanks for the response!
