### ISSUE TITLE
Hooking into Publications View to alter query

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#221]
Hi! Can anyone help me out with the hook for Tripal that alters view queries? I've tried hook_views_query_alter(&$view, &$query) but the Publications View in Tripal doesn't answer to that meaning that the hook doesn't seem to execute for this specific view. In desperate need of some advice. The hook worked perfectly on a standard drupal install but not on Tripal. I'm guessing there's something I'm missing since I'm new to Tripal, am I?

The module name is pubsearch_custom. Devel is installed and working.
Example code which works on all typical default Drupal views but NOT this specific Tripal view (publications):

function pubsearch_custom_views_query_alter(&$view, &$query) {
	dpm($view->name);
}

Any help would be appreciated, thanks!

**Comment by spficklin** [comment]
Hi @risharde I'm going to mark this one closed after our online discussion about it.  As there's too much to explain here for anyone that comes afterwards I'm not going to attempt it.  Re-open if you want to discuss further.
