### ISSUE TITLE
biomaterial contact field does not allow editing

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#222]
### Update

the field allows editing.  It does not allow submitting null.

###  Problem

Manually editing a biomaterial causes an SQL error.  Supplying a null contact gives this error

```
Could not save the entity: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "" LINE 1: ... biomaterial_id = '369', biosourceprovider_id = '' WHERE ... ^
Cannot save entity
```

biomaterial doesnt require biomaterialprovider_id so this should work.

On the other hand, if we specify our contact (theres a stock null contact, Mr. "not provided", who has contact entry) we get this error. 

```
PDOException: SQLSTATE[23503]: Foreign key violation: 7 ERROR: insert or update on table "biomaterial" violates foreign key constraint "biomaterial_biosourceprovider_id_fkey" DETAIL: Key (biosourceprovider_id)=(0) is not present in table "contact". in TripalEntityController->save() (line 415 of /data/www/html/hardwoods_dev/drupal-7.52/sites/all/modules/tripal/tripal/includes/TripalEntityController.inc).
```

###  Proposed solution

` "biomaterial_biosourceprovider_id_fkey" DETAIL: Key (biosourceprovider_id)=(0) is not present in table "contact".`

This to me says that its looking for biosourceprovider_id in contact (instead of contact_id)

I think we need to write  in an exception for biomaterial here too.

**Comment by spficklin** [comment]
By default there is a null contact in the contact table for this purpose.  I'm not sure why Chado requires a contact and then adds a NULL contact, but that's the way it is.  The same is true for the NULL pub record.  

The error message you're getting sounds like your query just didn't find the NULL contact record....  Are you sure it's using the right values to query?

**Comment by bradfordcondon** [comment]
Revisiting this.  Submitting works if supplying a valid contact.  

Supplying a null contact results in this still:

```
Could not save the entity: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "" LINE 1: ...', biomaterial_id = '2', biosourceprovider_id = '', descr... ^
Cannot save entity
```

> I'm not sure why Chado requires a contact and then adds a NULL contact, but that's the way it is. 

I'm confused here:  

* Biomaterial's contact_id column (called biosourceprovider_id) **is** nullable.
* is it the user's job to select the null contact?  Or should the field use the null contact if the field's form is submitted empty?

I have two null contacts:  `Not provided` (which is waht the analysis expression module uses) and `null`.  Are you saying that the person creating/editing biosamples should know to select one of these "null" values, even though the field isnt required?  If so maybe this should go in the widget text description?
Seems like it would be better if the validate method switched a blank contact for the "null" value.

>The error message you're getting sounds like your query just didn't find the NULL contact record.... Are you sure it's using the right values to query?

To clarify, this is the **Tripal Chado** field, `local__contact`.  I'm not sure how to answer your question here.  I'm submitting the form with a blank entry.

**Comment by almasaeed2010** [comment]
I've encountered a similar issue with mRNA and Gene content types. When editing an entity then saving, I get the following errors:

```
Notice: Undefined offset: 0 in field_default_form_errors() (line 404 of /data/www/html/hardwoods_dev/drupal-7.52/modules/field/field.form.inc).
Warning: implode(): Invalid arguments passed in form_error() (line 1705 of /data/www/html/hardwoods_dev/drupal-7.52/includes/form.inc).
Could not save the entity: SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "=" LINE 1: DELETE FROM chado.analysis_feature WHERE = : ^
Cannot save entity
```

**Comment by bradfordcondon** [comment]
which server is this one?  We'll need a list of fields attached to figure it out.

**Comment by almasaeed2010** [comment]
I tested on both our dev server and my local machine.

Here is a list of fields:

![download](https://user-images.githubusercontent.com/1512664/42035943-1d290f34-7ab2-11e8-8fb4-a8b9f51ebbbd.png)

**Comment by spficklin** [comment]
I'll see if I can duplicate this one.

**Comment by spficklin** [comment]
I posted a PR to fix this.  Let me know if it resolves the problem for you.

**Comment by bradfordcondon** [comment]
resolved via pr. thank you @spficklin
