### ISSUE TITLE
Anonymous users get access denied to organism node.  Others are fine.

### ISSUE THREAD

**Issue by stevewgithub** [tripal/tripal#223]
Drupal 7.56, Tripal 7.x-2.1

When an anonymous user clicks on the organism http://int-cowpea.org/?q=organism/Vigna/unguiculata
They get access denied.  Administrator can get in fine.
The home page works fine for anonymous users, and the "Group Photo" node is fine. 
All of the links on the other tabs (Initiatives, Other links) work fine.  It looks like only the organism type of node that doesn't work.

Syslog shows: 
Dec 13 18:15:38 H2 drupal: http://int-cowpea.org|1513217738|access denied|##.###.###.###|http://int-cowpea.org/?q=organism/Vigna/unguiculata|http://int-cowpea.org/|0||node/1

Here is what I have tried so far (everything I can think of):
The permissions page has "View published content" enabled for anonymous.
I checked the users table for a uid=0 record and it's there.
I added a 0,1 record to users_roles.
I added the module "Node view permissions" and enabled "Organism: View any content" for all.
I cleared the caches.
I did Rebuild permissions.
I installed the Access denied backtrace module and enabled it for anonymous.  I don't see any output from that in Recent log messages.
I installed the Data integrity checker module and ran that.

Any ideas about what to do?  Thanks.

**Comment by bradfordcondon** [comment]
Hi,

I'm going to start with a super simple suggestion.  

Have you verified that the organism node is published? 

![screen shot 2017-12-14 at 10 34 09 am](https://user-images.githubusercontent.com/7063154/34000115-5b29da08-e0ba-11e7-976c-5a57f0cade4c.png)

Look for the publishing options tab at the bottom of the organism node when editing.  Let's verify its checked first.

**Comment by stevewgithub** [comment]
Yes it's published, promoted to front page, and sticky.  It shows on the front page.  You can go there yourself and see it.  Then click any of the links: "read more" above it, "Vigna unguiculata (cowpea; niebe, blackeye, blackeyed pea)", or the [more] link under the paragraph.  Access denied.

**Comment by bradfordcondon** [comment]
OK in that case I think the issue is somewhere on your permissions page.  
You've clearly done a lot of troubleshooting there with all the extra modules.  You might try disabling them to get back to basics, as it should work without those modules.

 Can you search the page for "organism" and make sure that every instance of it is enabled for anonymous users?  On my site I have a Tripal Organism subsection (ie not the Node subsection) where I can enable anonymous users to view organism.

**Comment by stevewgithub** [comment]
That was easy.  I went to permissions for Tripal from the modules page, and enabled permissions for viewing organisms.  Problem solved.  Thank you.
