### ISSUE TITLE
Analysis prop chado fields

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#224]
Hi all,

This issue relates to collapsing analyses into one bundle.  Right now we have one Chado Property field, `analysis_type`.  I set it to required, great.

Each analysis type had lots of props that it set in the analysisprop table.  The unigene type set the `analysis_unigene_num_contigs` property, for example (we had a view that populated based on these props but I realize future loaded data wont have the prop set).   There are likely more examples.

* Is it the responsibility of the loader to add these properties now?  If so, the FASTA loader form needs to collect the information previously collected by unigene.
* Are there any analyses where we need to set these props but there is no loader?  I  can't think of any but maybe....
* If the bundle creation step collects the fields, then we'll need a lot of fields and we'll want them to only attach once the analysis_type is set (which is why the loader seems like a more appealing option).

**Comment by spficklin** [comment]
HI @bradfordcondon I'm not sure I understand the first bullet point about the FASTA loader as analysis properties aren't loaded via the FASTA loader...  Can you clarify?

There really isn't an "analysis" loader for Tripal.  Usually the analysis is required to already exist and if there are any properties added via loaders it's to the other data types.

Also, you don't have to lump all analyses into a single content type.  That's the way it comes with Tripal by defaul, but you can use different content types per analysis type.  When you create a content type the form let's you use properties (e.g. analysis_type) to differentiate the different types.   When Tripal auto-adds the properties for the content types you won't get unigene related properties showing up in your whole genome analyses.

**Comment by bradfordcondon** [comment]
>HI @bradfordcondon I'm not sure I understand the first bullet point about the FASTA loader as analysis properties aren't loaded via the FASTA loader... Can you clarify?

I think you understand the issue in general:  there are lots of properties that the individual analysis types used to utilize.   I thought maybe the loader could modify the analysis properties, but based on the rest of your message, it sounds like the correct approach is to re-create the analysis subtypes.

>When you create a content type the form let's you use properties (e.g. analysis_type) to differentiate the different types. When Tripal auto-adds the properties for the content types you won't get unigene related properties showing up in your whole genome analyses.

I had not tried creating a content type that didn't represent all entries in the table so hadn't seen this option.  For this following along from home:

<img width="1257" alt="screen shot 2017-12-19 at 9 13 32 am" src="https://user-images.githubusercontent.com/7063154/34160946-ecaae8f6-e49c-11e7-821e-de6a2d28e325.png">

So we can pick a CVterm for the analysis subtype (say, analysis_unigene), point it at the analysis chado table, and say that this content type is going to be defined in the analysis_prop table when the cvterm "analysis_type" is set to unigene.


It sounds like we have a bit of work to do to define all of our old sub-analyses then.  Thanks.

**Comment by bradfordcondon** [comment]
While I'm at it, to do this programmatically, when defining the bundle, we set the Storage Args array to:
`type_linker_table` => the prop table (analysisprop in this case)
`type_column` => `type_id`
`type_id` =>   the CVterm ID for the type_id (in this case, analysis_type)
`type_value` => the text value associated with this content type (in this case, analysis_unigene)

Turns out all of this is also visible if I go to structure -> content type -> edit, listed in the chado mapping table.

**Comment by bradfordcondon** [comment]
@spficklin  I have two questions that stem from doing this:

* How do we change existing Analysis entities to their newly defined subtype? 
* How do we allow migrating tripal 2 analyses to the new subtype?  We would need to hook into migration, right?  Adding the migration to core is problematic because that site might not have the subtype installed....

**Comment by spficklin** [comment]
Hi @bradfordcondon, it's not possible to change an existing content type.  But you can leave it for now and create your new analysis content types and when you're happy with the new pages you can remove the old analysis content type.  They can live side-by-side even if they are using the same data (weird but true).

Here's some example code for programmatically creating a content type using a property value:

```
// Create an Analysis content type using a property value.
$error = '';
$args = array(
  'vocabulary' => 'EDAM_topic',  
  'accession' => '0222',
  'term_name' => 'Genome annotation',
  'storage_args' => array(
    'data_table' => 'analysis',
    'type_linker_table' => 'analysisprop',
    'type_column' => 'type_id',
    'type_id' => $cvterm->cvterm_id,
    'type_value' => 'Whole Genome'
  )
);

// Make sure the bundle doesn't already exist and if not then create it.
$term = tripal_load_term_entity(array('vocabulary' => 'EDAM_topic', 'accession' => '0222'));
if ($term) {
    $bundle = tripal_load_bundle_entity(array('term_id' => $term->id));
}
if (!$term or !$bundle) {
  if (!tripal_create_bundle($args, $error)) {
    throw new Exception($error['!message']);
  }
}
```
In the code above it will set the content type's controlled vocabulary term to be "EDAM_topic:0222" which is a term for a whole genome annotation analysis (you use whatever term makes sense for your analysis type).  The 'storage_args' section is for Chado.  These are arguments that the Chado storage back-end uses to map your content type to data in Chado.  the data_table is the base table (e.g. analysis records).  The type_linker_table is analysisprop because that's where the differentiator is stored.  The type_column is used to specify the type of property.  The type_id is the cvterm ID for the term that is used in the analysisprop.type_id field to specify the the type of analysis.   So, if you use the term 'local:Analysis Type' then you need to lookup that term using the chado_get_cvterm() function and use the cvterm_id from the record returned.  Finally, the type_value is the value in the analysisprop.value column that indicates the type of analysis.

Repeat the above code as many times as needed to create a new Analysis content type.

**Comment by bradfordcondon** [comment]
Hi Stephen,

thanks for the thoughtful reply.  For now I'm implementing the types manually...

How can I migrate my tripal 2 analyses to my new tripal 3 subtype?  I dont see my new bundle appearing as an option under migration.

if i can't change the type of an entity then presumably I need to migrate them from the v2 type still, right? Is there a different way of populating the entities im not thinking of?

**Comment by bradfordcondon** [comment]
@spficklin I am thinking the migration code needs to work more like features here.    Analysis is hard-coded in to migrate analysis 1:1 to analysis.

What do you think?  Is there another way to populate my analysis_unigene entity?

**Comment by bradfordcondon** [comment]
We address this in #241
