### ISSUE TITLE
PDO Exception errors in Tripal 3.0 dev

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#228]
Running on Drupal 7.56 and Tripal 7.x-3.0-rc2+63-dev

The following error message is displayed when trying to edit ANY Chado Views Integration table choice

PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "views-integration" LINE 1: SELECT * FROM tripal_views WHERE setup_id = 'views-integrati... ^: SELECT * FROM {tripal_views} WHERE setup_id = :setup; Array ( [:setup] => views-integration ) in tripal_chado_views_integration_form() (line 244 of /var/www/Drupal/sites/all/modules/tripal/tripal_chado_views/includes/tripal_chado_views_integration_UI.inc).

**Comment by spficklin** [comment]
Okay. Thanks for pointing this out. We'll get it fixed.

**Comment by spficklin** [comment]
You beat us to it! Your pull request has been applied. Thanks for fixing it.   I'm closing this out but reopen if you still have issues.
