### ISSUE TITLE
migrating organism loses image

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#230]
Not sure if this is the same/related to #171 but creating an organism and migrating it will lose the image.

**Comment by spficklin** [comment]
Hmmm... @chunhuaicheng might have some insight.  We specifically worked to make sure this didn't happen.  Maybe there's a bug that got introduced later....

**Comment by chunhuaicheng** [comment]
It seems the 'Cross Reference' field is causing trouble saving organism but I need to confirm this is the culprit. Could you try removing that field (aka. organism_dbxref) and see if the images get migrated?

**Comment by bradfordcondon** [comment]
I deleted the field, deleted the migrated tripal 3 entity, and remigrated.  I get this error with the organism not migrated:

```
Creating default object from empty value tripal_chado.migrate.inc:937                                                                             [warning]
Job execution failed: Missing bundle property on entity of type TripalEntity.                                                                     [error]
Succesfully published 0 Organism record(s).
```

**Comment by bradfordcondon** [comment]
Trying again:

```


NOTE: publishing records is performed using a database transaction.
If the load fails or is terminated prematurely then the entire set of
is rolled back with no changes to the database

WD tripal: PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: ""                             [error]
LINE 1: ...O chado_bio_data_2 (entity_id, record_id) VALUES ('216', '')
                                                                    ^: INSERT INTO chado_bio_data_2 (entity_id, record_id) VALUES
(:db_insert_placeholder_0, :db_insert_placeholder_1); Array
(
)
 in tripal_chado_field_storage_write() (line 68 of
/Users/chet/UTK/tripal/sites/all/modules/tripal/tripal_chado/includes/tripal_chado.field_storage.inc).
WD tripal_chado: Could not publish record: Could not create entity.                                                                               [error]
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] Could not publish record: Could not create entity.

NOTE: publishing records is performed using a database transaction.
If the load fails or is terminated prematurely then the entire set of
is rolled back with no changes to the database

Creating default object from empty value tripal_chado.migrate.inc:937                                                                             [warning]
Could not save the entity: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: ""                           [error]
LINE 1: ...O chado_bio_data_2 (entity_id, record_id) VALUES ('216', '')
                                                                    ^
Failed publishing record. See recent logs for more details.                                                                                       [error]
Job execution failed: Missing bundle property on entity of type TripalEntity.                                                                     [error]
Succesfully published 0 Organism record(s).                                                                                                       [status]
```

**Comment by chunhuaicheng** [comment]
I'm afraid when you delete the organism entities, you might also delete the underlying chado organism record. Can you try it on a site that organisms have not been migrated? (i.e. remove 'Cross Reference' fields, and clear the cache with 'drush cc all' after migration)

If you really want to migrate organisms the second time, you should delete the  'Organism' entity type instead of the organism entities. Here's the procedure:

1. Delete Organism Content Type
'Strucure' > 'Tripal Content Types' > delete 'Organism' > confirm

2. Recreate Organism Content Type
'Add Tripal Content Type' > Look up term > Select 'organism' with OBI vocaculary > check 'Yes' for 'Are all records in the organism table of type organism' > Create content type > ignore the error for now > set view permission for Organism so you can view them later

3. Delete the 'Cross Reference' field
'Strucure' > 'Tripal Content Types' > 'manage fields' for 'Organism' > delete 'Cross Reference' field

4. Migrate 'Organisms' as usual

5. clear cache (Tripal seems to have another layer of cache that needs to be cleared)
drush cc all

6. check if the images are migrated

**Comment by bradfordcondon** [comment]
>I'm afraid when you delete the organism entities, you might also delete the underlying chado organism record

I don't think Tripal ever deletes the underlying chado data on principle

>Can you try it on a site that organisms have not been migrated?

I booted a fresh site.  Deleted the cross reference field from organism, cleared the cache, and migrated a tripal 2 organism.

The resulting entity does not have its image associated. 

I did get this error during migration: 
```
Job execution failed: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: ""                                 [error]
LINE 1: ...ke species',  infraspecific_name = '',  type_id = '',  speci...
                                                             ^
```

**Comment by chunhuaicheng** [comment]
hmm... I'm not sure what went wrong. I can't reproduce the error on my machine. Could you try the second method with 6 steps listed above now and see if you get the same error message please?

**Comment by bradfordcondon** [comment]
nm parallel

**Comment by bradfordcondon** [comment]
Hi @chunhuaicheng I followed your 6-step instructions and my organisms did not migrate with images.

**Comment by chunhuaicheng** [comment]
Thank you for trying Bradford. I have no clue what's causing the problem at this point. Could you provide a Postgres db dump so I can try it with your setup please?

**Comment by bradfordcondon** [comment]
sent via slack: 

https://files.slack.com/files-pri/T5DR44C9Y-F8M2K2EN6/download/1-2-18_dump.bak.zip

**Comment by chunhuaicheng** [comment]
Thank you for providing the DB dump. I've committed a fix for the bug. Could you pull the latest code (7.x-3.x) and try again please? You can simply remove and add back the 'Organism' content type, then perform the migration. You don't need to delete any field or clear cache now. Please let me know if there is still a problem.

**Comment by bradfordcondon** [comment]
Issue is resolved.  Thanks a lot!
