### ISSUE TITLE
Adding fields via library

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#237]
Hi I commented in  #150  but can't reopen the issue so I will ask here:

I've defined a field in `sites/all/libraries/TripalFields/my__field_name`  Tripal does not find the field.

For a module, I would have a `module_name.fields.inc` file that declares and attaches my fields to my desired bundles.  Do we do that here?  If so how?  If not, what am I doing wrong?

![image](https://user-images.githubusercontent.com/7063154/34212057-1084b2ee-e569-11e7-9ca2-51f0cfe6788a.png)

I've cleared caches and looked within the Add existing field dropdown for my field with no luck.  Moving the field to a module resolves the issue.

edit: I also have the libraries module enabled (and I have the elasticsearch library installed here which functions)

**Comment by spficklin** [comment]
Hi @bradfordcondon .  You will want to use the libraries folder for fields that users can add to the GUI themselves or for updated widgets/formatter classes.  Tripal should find those automatically.   If you want the field programmatically added then the only way to do that is with a module.  Which makes sense because then it becomes a single installable package (you get fields and they get added automatically).

**Comment by bradfordcondon** [comment]
Right I agree.

I thought Tripal hadn't discovered my field, I couldn't find it in the dropdown (add existing field).  It appears there now, although It's not a fair test because I defined it in a module and then moved it to library.  I'll close the issue and reopen if my field isn't discovered in the library folder.

**Comment by spficklin** [comment]
Just to check, was your test successful?  Were you able to see the field after deleting it and moving the code to the libraries/TripalFields folder?

**Comment by bradfordcondon** [comment]
Yes I removed the field and reattached it, with it only defined in the libraries folder.  Still, the field is stored somewhere right? Because if i delete the TripalFields library folder (and have no `ero__nucleic..` field defined anywhere), I continue to get this error:

`Notice: Undefined index: ero__nucleic_acid_library in field_ui_existing_field_options() (line 1545 of /Users/chet/UTK/tripal/modules/field_ui/field_ui.admin.inc).`

So I want to try a fresh field and see if it is discovered properly.

Still the field stops showing up in the dropdown box and reappears when re-added ot the libraries folder.  Not sure what my original problem was... clearing cache voodoo I guess.

**Comment by spficklin** [comment]
If you remove the code but still have the field attached to a content type then that doesn't get rid of the field to Drupal.... It just gets rid of the code.  You must first remove all instances of the field from all content types.  I believe that will get rid of the the field.  But if it doesn't, you can delete it from the field_config and field_config_instance tables of Drupal.

After you add the field to the libraries directory are you clearing the cache?

**Comment by bradfordcondon** [comment]
I'm not sure what to say, my library-defined field is not discovered on a new site.
I cloned my field into `libraries/TripalFields`, have the libraries module discovered, and cleared the cache (several times).  Have the latest tripal 3 dev branch. My new field doesnt show up in "add existing field".

It's odd to me that once the field was discovered via a module, it could be found again in the libraries folder after it was deleted from the module.

**Comment by bradfordcondon** [comment]
similarly, if I add a new field to the libraries folder (on my original dev site, where the field is discovered but had been enabled originally in a module).... the new field cannot be discovered.

edit:  could the problem be my term isnt in the database? shoot i bet thats it.  edit: no apparently not.... thought for sure that would be the problem.

**Comment by bradfordcondon** [comment]
https://github.com/statonlab/ero__nucleic_acid_library.git   heres the field if someone else wants to try adding it, the problem could possibly reside with the field itself (even though the field functions within a module?)

**Comment by laceysanderson** [comment]
I had hoped maybe you had switched the `$no_ui` option in the field definition (https://github.com/statonlab/ero__nucleic_acid_library/blob/master/ero__nucleic_acid_library.inc#L79) as this would cause it not to be shown in the drop-down. However, as you can see in the link, that was not the issue. 👍  Adding the comment for others ending up at this issue :-).

**Comment by spficklin** [comment]
Hi @bradfordcondon.  Are you sure you want the field to appear in the 'Add existing field' drop down?  That gets used if you have already created the field (say for another content type) and you want to re-use it on another one.  Perhaps what you're looking for is for it to appear in the 'Add new field'?  Can you describe the behavior you want for this field?  

I downloaded and tested your field and I do see it appear in the 'Add new field' drop down, although I'm not able to add it without an error so there may be some more debugging we need to do.

**Comment by spficklin** [comment]
BTW... for your field you'll want to add the chado mapping settings. Here's a diff:

```
diff --git a/ero__nucleic_acid_library.inc b/ero__nucleic_acid_library.inc
index 07d14f2..b02105c 100644
--- a/ero__nucleic_acid_library.inc
+++ b/ero__nucleic_acid_library.inc
@@ -70,6 +70,13 @@ class ero__nucleic_acid_library extends ChadoField {
     // is convenient for speed.  Fields that are slow should for loading
     // should have auto_attach set to FALSE so tha their values can be
     // attached asynchronously.
+
+    // The table in Chado that the instance maps to.
+    'chado_table' => '',
+    // The column of the table in Chado where the value of the field comes from.
+    'chado_column' => '',
+    // The base table.
+    'base_table' => '',
   ];
 
   // A boolean specifying that users should not be allowed to create
@@ -158,4 +165,4 @@ class ero__nucleic_acid_library extends ChadoField {
 
     }
   }
-}
\ No newline at end of file
+}
```

**Comment by bradfordcondon** [comment]
> Are you sure you want the field to appear in the 'Add existing field' drop down?

In this case it should attach to organism.  But right now I just want Tripal to find the field!

Also, how would I attach it to organism, when thats done in the `fields.inc` file within the module?

>I downloaded and tested your field and I do see it appear in the 'Add new field' drop down, although I'm not able to add it without an error so there may be some more debugging we need to do.

So just to confirm: you didnt add any additional code ie a `fields.inc` file?  You cloned into your TripalFields folder within your libraries folder, and it just worked?  I don't understand why I can't add fields via libraries....

**Comment by bradfordcondon** [comment]
> Are you sure you want the field to appear in the 'Add existing field' drop down? That gets used if you have already created the field (say for another content type) and you want to re-use it on another one. Perhaps what you're looking for is for it to appear in the 'Add new field'? 

I think this is the issue: I was looking for the field in the wrong place!

I'll define a new field and verify this was my mistake and write it up so another thickheaded developer doesn't miss this too

**Comment by bradfordcondon** [comment]
OK-

* Like Stephen pointed out, fields in your library appear under **add new field** not **add existing field**.
* After adding the field, I also got an error.  Returning to the bundle afterwards, the field was not saved.  Looks like we needed to configure the field but couldnt.  Maybe when I update my field stub this will help?

```
The requested page "/admin/structure/bio_data/manage/bio_data_1/fields/field_fake/field-shcef?destinations%5B0%5D=admin/structure/bio_data/manage/bio_data_1/fields/field_fake&destinations%5B1%5D=admin/structure/bio_data/manage/bio_data_1/fields" could not be found.

```

**Comment by bradfordcondon** [comment]
Hi @spficklin 

Specifying the module properly `tripal_chado` does not resolve this error.
neither does having the elementinfo, query, or queryorder method.

after lots of `dpm`ing, my guess is that `tripal_chado_bundle_create_user_field` is executing but perhaps failing silently somewhere.  this is the input parameter in `$new_field`.  Anything obviously wrong to you?


![screen shot 2018-01-22 at 5 12 25 pm](https://user-images.githubusercontent.com/7063154/35247186-71c2caee-ff97-11e7-8d10-88c5bf45a60e.png)

e: actually looking at `tripal_chado_bundle_create_user_field`... it looks to me like it ony does something  if `  if ($new_field['type'] == 'chado_linker__prop') {` and  `  if ($new_field['type'] == 'chado_linker__cvterm') {`.

is that right?  

Or should there be a third case when the user is adding a field that isnt a linker or prop?  I can see that you intend this to be called if the field sets the module to `tripal_chado`...


I also might be off base and the problem is elsewhere...


edit again: Maybe this is because the base table info isnt set properly?  let me double check that. ---->  double checked... no, setting base table etc doesnt resolve.

**Comment by laceysanderson** [comment]
I don't think you are off base @bradfordcondon. You are correct that the tripal_chado implementation of hook_bundle_create_user_field() only handles prop and cvterm linker fields. I recently had to implement this hook myself to have trpfancy_fields work using the "Add new field" functionality.

I would think we would need to add some generic code to [here](https://github.com/tripal/tripal/blob/7.x-3.x/tripal/includes/tripal.fields.inc#L348) so that if the hook is not implemented we create the field and instance. Thoughts @spficklin?

Something like this (untested; would have to handle @hardcoded places better ;-) ):
```php

  // Create the field.
  $field = array(
    'field_name' => $new_field['field_name'],
    'type' => $new_field['type'],
    'cardinality' => 1, // @hard-coded
    'locked' => FALSE,
    'storage' => array(
      'type' => 'tripal_no_storage', // @hardcoded
    ),
  );
  field_create_field($field);

  // Then create the instance.
  $instance =  array(
    'field_name' => $new_field['field_name'],
    'entity_type' => $bundle->type,
    'bundle' => $bundle->name,
    'label' => $new_field['label'],
    'description' => $new_field['label'], // unless there's a more ideal place to pull this from.
    'required' => FALSE,
    'settings' => array(
      'auto_attach' => FALSE, // @hardcoded
    ),
    'widget' => array(
      'type' => $new_fields['widget_type'],
      'settings' => array(),
    ),
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        // @ASSUMPTION: Assumes there is a formatter that matches the field type.
        'type' => $field_name . '_formatter',
        'settings' => array(),
      ),
    ),
  );
  field_create_instance($instance);
```

**Comment by spficklin** [comment]
Yeah, @laceysanderson is right.  We need some generic code to handle fields that aren't attached to modules.

**Comment by laceysanderson** [comment]
There. This should work now @bradfordcondon. I found a generic way to set everything but the field cardinality (which I hard-coded to unlimited). Let me know if you run into more issues :-)

**Comment by bradfordcondon** [comment]
Great thanks @laceysanderson

I have the same error but I think it's from having the module set to `tripal_chado`** : my `$function` is still `tripal_chado_bundle_create_user_field`.  I've cleared my cache, checked for new fields etc so not sure why it's still registering at tripal_chado despite me changing my field...

**Comment by laceysanderson** [comment]
So, just check that I'm understanding correctly: originally you had ` public static $module = 'tripal_chado';` in your field class. However, now you've changed it to something else and you're still receiving the same error?

**Comment by bradfordcondon** [comment]
Actually I deleted the `public static $module = 'tripal_chado';`  line.   setting it to something else (`tripal_not_chado` naturally) allowed me to create the field. 

Thanks!
