### ISSUE TITLE
Attempting to update contact gives error and so contact does not get updated.

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#238]
Attempting to edit the details of a contact results in the following error message. Unfortunately the contact data is not updated due to this error. 

Error:
Could not save the entity: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "contactprop_pkey" DETAIL: Key (contactprop_id)=(10) already exists.
Cannot save entity

**Comment by risharde** [comment]
After further checking, it seems the contactprop_contactprop_id_seq index is showing a value of 40 when there are more items than that in the table. It seems the index became out of sync. Not sure how. Still determining whether it is safe to perform a reindex.

**Comment by laceysanderson** [comment]
Hi @risharde,

You can easily reset the sequence by first determining what the maximum id already used is: 
`SELECT MAX(contactprop_id) FROM chado.contactprop;` 

Then just use the result of that query to update the sequence as follows: 
`SELECT setval('contactprop_contactprop_id_seq', [max contactprop_id+1]);`

You shouldn't need to do anything on the Tripal side of things thanks to the constraints that caused your original error :-). Let me know if this solves the problem!

**Comment by laceysanderson** [comment]
Also, if you happen upon what caused the sequence to become out of sync, I'd love to hear it! Unfortunately/fortunately it happens so rarely and usually unexpectedly that it's hard to debug.

**Comment by risharde** [comment]
Hey Lacey, sorry for the delay in responding, thanks for the suggestion, that did work but now when trying to add a new contact, I get another similar message:

Could not save the entity: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "chado_bio_data_8_table_record_key" DETAIL: Key (record_id)=(12272) already exists.
Cannot save entity

I cannot determine why it went out of sync but I will let you know as I get some light on why  this happened. With this new error, I cannot seem to find chado_bio_data_8_table_record_key so I'm again stumped. If you have any ideas, please let me know.

Thanks!

**Comment by spficklin** [comment]
Hi @risharde.  If you haven't created too many contacts or invested to much effort into creating that content type you may want to delete it and recreate it.   Tripal maintains a chado_bio_data_8 table for mapping your contact entities in Drupal to the record in Chado.  Somehow the values in that table are mismatched still.  So, the easiest thing may be just to delete the 'Contact' content type and start over. This won't remove any data in your Chado tables. It just removes the entities (pages) in Drupal.

**Comment by risharde** [comment]
Hey Steven and Lacey, after doing the seq updates, this seems to have been solved. Thanks to all of you guys for the help!
