### ISSUE TITLE
Tripal3 Prepare Chado Tripal Jobs Errors

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#24]
Tripal Version: 7.x-3.0-beta1

I followed the tutorial (http://tripal.info/tutorials/v3.x/installation/tripal) and the step "prepare both Drupal and Chado" produced many errors when the Tripal job was launched. Furthermore, despite all the errors, my Tripal3 site now says "Your site is prepared." in green.

I've attached the entire log from running the Tripal job. 
[tripal3.preparechado.txt](https://github.com/tripal/tripal/files/772137/tripal3.preparechado.txt)

It seems to be having trouble loading ontologies and later selecting terms. 
* TPUB:0000002 isn't in the dbxref table.
* Tripal publication cv has no cvterms inserted.
* chado.tripal_obo_temp table does exist.
* cvterms do exist for the following cvs (number of terms in brackets).
An additional type for the item, typically used for adding more specific types from external vocabularies in microdata syntax. This is a relationship between something and a class that the thing is in. (1), analysis_property (1), chado_properties (1), EDAM (12), ero (1), featuremap_property (8), featuremap_units (5), featurepos_property (2), IAO (2), iao (1), library_property (1), library_type (6), local (19), ncbitaxon (1), nd_experiment_types (2), nd_geolocation_property (1), null (1), obi (1), ogi (1), organism_property (11), project_property (1), rdfs (2), sbo (3), schema (6), sequence (2), SIO (3), swo (1), synonym_type (4), taxonomic_rank (3), tripal_analysis (2), tripal_phylogeny (4), uo (1).

**Comment by spficklin** [comment]
Oops... Yep, a bug in the order of things that get run during preparing of Chado.   I've just committed a fix.  Can you pull the most recent dev version try it out.

**Comment by laceysanderson** [comment]
Much Better :-)

I now only see a single error
> WD tripal: Cannot create field for "pub.miniref". Missing an appropriate vocabulary term                                                                                            [error]
> [site http://default] [TRIPAL ERROR] [TRIPAL] Cannot create field for "pub.miniref". Missing an appropriate vocabulary term
> Cannot create field for "pub.miniref". Missing an appropriate vocabulary term                                                                                                       [error]

**Comment by spficklin** [comment]
Yep, that's one that we didn't get time to fix.  But not a big deal. It just means you won't have a 'miniref' field on your publication entity.

I'll create a new beta release as this will cause problems for folks.
