### ISSUE TITLE
custom content type with properties unable to add new props on edit

### ISSUE THREAD

**Issue by srobb1** [tripal/tripal#245]
Hi. 
I have been making good progress with a new custom module with a new content type. I think I am almost done with it. It has properties and they get added nicely. BUT, when I edit a new record, I am unable to add more properties. I can remove any that already exist.  When I click the Add button, I get a very nondescript ajax error. Any pointers on how to debug something like this?

I probably screwed something up, I altered the form to have a drop down of options for the values, instead of using a text area. It works well enough that everything gets added to my properties table on the creation of the record.

`
An AJAX HTTP error occurred.
HTTP Result Code: 500
Debugging information follows.
Path: /system/ajax
StatusText: Service unavailable (with message)
ResponseText: 
`

Here is my code: 
https://github.com/srobb1/tripal_onto_term_submit/tree/properites

**Comment by shawnawsu** [comment]
Hi @srobb1 ,

I think we worked on this at PAG, is this resolved now?

Thanks!
Shawna

**Comment by bradfordcondon** [comment]
hi @srobb1 given the lack of response I'm assuming this is resolved? if not please let me know, otherwise ill close this out.

Thanks!
