### ISSUE TITLE
Managing field display settings gets very slow

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#246]
## Issue
Configuring the display of fields for a bundle is prohibitively slow.  Every single transaction takes 15 minutes currently.  This means adding a new field and arranging it can take an hour of waiting easily.  (Side-issue: dragging things around is just broken, usually it autoscrolls to the top of the page.  I can only move a field one space at a time because of this.).  

![screen shot 2018-01-09 at 12 44 29 pm](https://user-images.githubusercontent.com/7063154/34734804-209ad0dc-f53b-11e7-9312-9b1d5810eb92.png)
Just performed this transaction: drag the Transciptome field from "disabled" to the Transcriptome group.

I have 21 individual fields attached, most of which are base table fields but a bunch of custom ones that list other entity types associated with an organism.

Looking at system usage, we never use up a significant portion of memory (5%), but we have lots 
of sql queries populating, idling, waiting, etc.

Please note this isnt a VM (where we have found Drupal can be very very slow because of Docker file system issues) but our dev site.

## Discussion

I think this is extremely problematic, especially if the problem scales with the number of fields attached.  We're almost at the point where it's impossible to configure the fields, which is no good because fields attach with the display disabled.  Because Organism is going to be our "hub" for accessing stuff, most content will want to attach to it.  

A work around - we could programatically define the panes.  This could work but I don't know how to do it.

It's entirely possible this is a problem with our site settings, in which case would appreciate help troubleshooting.

**Comment by bradfordcondon** [comment]
Our site has become clogged with deadlocks. Something is wrong that is probably not related to this issue: I'll report back when we can figure out the problem and if this issue is resolved.

**Comment by bradfordcondon** [comment]
I'm closing out this issue: I think it was a symptom of general poor site performance and not tripal.  

Discussions with stephen brought to light that writing to watchdog can be slow things down.  I had a couple of broken dbxref links in my site that would raise warnings 20+ times when clearing the cache.  It's possible that these were getting written and causing problems.

**Comment by spficklin** [comment]
Just curious.  Has performance improved?

**Comment by bradfordcondon** [comment]
Yes.  Fixing the errors that appeared when clearing the cache sped up the site.

Basically inserting CVterms in the database with bad accessions left bad dbxrefs that didn't get changed when the term is overwritten.  Manually deleting these dbxref entries resolved the problem.

**Comment by spficklin** [comment]
So how did those bad cvterms get in?  I'm just wondering if this could happen to other folks

**Comment by bradfordcondon** [comment]
Sure.  Steps to reproduce:

* Programmaticaly insert a cvterm (tripal_insert_cvterm), but use the wrong accession.  In my case, I think I goofed and put the term name instead of the accession number.
* Realize your mistake, and update the code.  The tripal insert cvterm will update run again, but leave the bad dbxref associated with it.

So, people will only have this problem when coding custom fields. And if they are cautious, they will only have it in their dev instance.

The error is reasonably descriptive: its telling you that the cvterm_id doesnt have a matching dbxref.  So to fix it, you must manually alter the dbxref accession field.
