### ISSUE TITLE
hackathon CV:  NCIT vs local discussion

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#247]
As part of the Controlled Vocabularies breakout session, I thought we'd practice hunting for CVterms for core fields/bundles that still use local.  Turns out most fields are in good shape within core :)

The terms suggested both came from NCIT so I am going to change the issue to NCIT discussion.

## Terms that currently use Local
* contact
* source_data
* project (see chado project)

## Suggested CVs to use

* EDAM
* SIO
* EFO
* ERO
* SBO
* OBI

**Comment by taytayp** [comment]
A possibility for **contact** would be using the NCIT term [contact person](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C25461)

A possible solution for **source_data** could be [data origin](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C103167)

Will look for some other, non-NCIT solutions, if possible.

**Comment by bradfordcondon** [comment]
Thank you Taylor

* I actually dont think contact person is the right term here. 

>A person acting as a channel for communication between groups or on behalf of a group. [ NCI ]

We want our contact term to include contacts that are entire companies.  The contact also may just be an individual, in which case they are not the person acting as a channel between groups.

* Data origin looks pretty reasonable to me (they say "metaphysical source"... which is kind of silly to me?  But if the URI can be a metaphysical source, then we are in business).  

I'm remapping this issue to discuss using the NCIT CV.  @spficklin and I have discussed this before: he raised the good point that we want the CVs we use in core to be as *broad as possible* so that they will be applicable to any Tripal site.  Because of this CVs like SIO or EDAM are the ideals.  NCIT on the other hand is named for the national cancer institute and sounds human/mammalian centric.

In practice though, I don't think that it is.  Rather, I think its the most flexible and exact CV.  It's consistently the only CV that has the term for exactly what I mean.  This is actually problematic because, again, we want our CV terms to be as general as possible, and sometimes NCIT allows us to be *more specific* than we mean to be.

Still, in some cases we find ourselves with a choice: no CVterm (use a local vocabulary) or NCIT.  In these cases I think NCIT is the better choice.   I don't think we would ever want Tripal to load NCIT by default or anything, but it's better than no term.  Perhaps the best choice is to propose an addition to an existing appropriate CV that crossrefs to NCIT... but I haven't tried proposing additions to a CV like EDAM before...

**Comment by spficklin** [comment]
In reference to this issue #217 I think we have no better alternative than NCIT for the contact FKs.   Tripal sites don't often store cancer-related data and I do try to find ontologies that are more closely related to the data we typically store, but at least for the contact FKs the NCIT terms make good sense.
