### ISSUE TITLE
chado property widget needs work

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#249]
* Theres an extra box to start (apparently drupal adds the second one automatically, not Tripal)
* I dont know if setting the cardinality matters: you can keep adding new prop values
* sets one to "delete_me"
* once you add a prop, not a button to remove that prop

<img width="1398" alt="screen shot 2018-01-11 at 7 14 28 pm" src="https://user-images.githubusercontent.com/7063154/34853801-bacb1738-f703-11e7-8cb5-73160bf0ac1d.png">

**Comment by bradfordcondon** [comment]
Related bug: AJAX error adding more and more property items
https://github.com/tripal/tripal/issues/240

**Comment by shawnawsu** [comment]
I'm working on https://github.com/tripal/tripal/issues/240 but everything listed (except delete_me) here is all Drupal based and it's not a good idea to override drupal defaults.

- The extra box is added by drupal as it's an unlimited value field.
- I'm not sure what this second point means but this unlimited value fields allow for drag and drop in drupal.
- delete_me can be rmeoved and a default value set to ''.
- To delete a prop you've added and no longer need you just need to delete the value in the field.

I'm going to close this and wrap the default_value change request into #240.
