### ISSUE TITLE
suggestion: issue template

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#251]
At the first day of the user's meeting, many people requested the ability to add more information to their issues: they wanted to tag them.   Abdullah suggested writing a github issue template instead.  
Check out the issue template [on the react native repo](https://github.com/facebook/react-native/blob/master/.github/ISSUE_TEMPLATE.md) for example.  Basically we just stick a markdown file in `.github/ISSUE_TEMPLATE.md` and we're in business.

Things the template could ask users to do:

* name issue with [Question] or [bug]
* include a v3 or v2 tag
* redirect issues to a submodule ....

**Comment by bradfordcondon** [comment]
I created an example ticket template on my tripal_alchemist page.

[heres when you create a new issue]( https://github.com/statonlab/tripal_alchemist/issues/new)
[heres a blank ticket](https://github.com/statonlab/tripal_alchemist/issues/11) i just filled out

**Comment by spficklin** [comment]
I'm a bit worried if we complicate adding of issues it may deter folks who may be overwhelmed by a template.  But I don't want to discount the idea.  @laceysanderson any thoughts?

**Comment by laceysanderson** [comment]
I think it could be awesome but we would have to be careful not to overwhelm them! I would be tempted to do something like this:
```
-- Please enter the following information (if known) --
Tripal Version:
Drupal Version:
PostgreSQL Version:
PHP Version:
Operating System:

-- Please describe your issue here :-) 
    Some information you might want to include: the page you're seeing the issue on, 
    what behaviour you're experiencing versus what you expect, steps to reproduce... 
    really anything you think might best help us help you! --

-- PS. Also feel free to ask questions, start discussions, suggest improvements
           We welcome any and all feedback! --
```

This way we can give them suggestions which might speed up the debugging process but we're very friendly and clear that all information is optional :-) I would actually be more likely to file an issue if I came across something inviting rather then an empty box. 

Thoughts @spficklin? I agree we don't want to make it more complicated but at least with these templates they can completely ignore it if they want.

**Comment by spficklin** [comment]
Okay, I can be persuaded.   Can we adapt the tripal_alchemist template with Lacey's suggestions and add this text at the top


INSTRUCTIONS: The following template is meant to provide the information that will help other Tripal developers diagnose and reproduce your issue.  Follow the directions below to complete the template.  If the template is not appropriate for your issue you may remove it and describe your issue.

**Comment by bradfordcondon** [comment]
made a basic start of it... i wasn't sure what you wanted from my alchemist draft so let me know...

Ultimately it's just bells and whistles to help issues be more constructive but also encourage people to post who might not otherwise.  If it isn't something that benefits the project no need to include.

**Comment by bradfordcondon** [comment]
well, no one has submitted an issue yet.  i hope thats not because the issue template is intimidating 🤡 

Minor suggestion:  Add a "how to get this information" text or at least linkout.  (all of it except OS is available in the drupal system report admin area so i think its pretty user-friendly to ask for this info)

**Comment by bradfordcondon** [comment]
Abdullah has suggested removing OS from the request: after all, OS is going to be the least frequent offender as opposed to php version.

I like this because then we can say "all information is available in your site's administrator report area.  You can find this in the admin menu at  Administer (or Administration) > Reports > Status report."

**Comment by laceysanderson** [comment]
> I like this because then we can say "all information is available in your site's administrator report area. You can find this in the admin menu at Administer (or Administration) > Reports > Status report."

I Love it! Good suggestion 👍

**Comment by laceysanderson** [comment]
We now have new issues :-) 

@srobb1 would you be willing to share your feelings on the new issue template? We'd be happy to get some constructive criticism so we can find the perfect balance of helpful but not intimidating :-) By the way, if you find it easier to be be critical in an email rather then a public forum, feel free to contact me personally (see [my profile](https://github.com/laceysanderson) for address).

**Comment by spficklin** [comment]
it seems the new template issue is working well.  I'm going to close this out.
