### ISSUE TITLE
Loading OBO without default-namespace

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#253]
When loading vocabularies without a default-namespace the following errors occur.  The URL listed as the default namespace gets used as the database name.

> Downloading URL https://raw.githubusercontent.com/obophenotype/planaria-ontology/master/src/ontology/plana.obo, saving to /tmp/obo_ym1OSl
> Step 1: Preloading File /tmp/obo_ym1OSl...
> This OBO is missing the 'default-namespace' header. It is not possible to determine which vocabulary terms without a 'namespace' key should go.  Instead, those terms will be placed in the 'HTTP://PURL.OBOLIBRARY.ORG/OBO' vocabulary.
> Step 2: Loading type defs...
> Step 3: Loading terms...%. Memory: 38,313,672 bytes.
> Percent complete: 100.00%. Memory: 38,308,672 bytes.
> Done.
> 
> Updating cvtermpath table.  This may take a while...
> - Loading paths for HTTP://PURL.OBOLIBRARY.ORG/OBO
> - Loading paths for uberon
> - Loading paths for Planarian_Anatomy

**Comment by spficklin** [comment]
Also, adds a weird entry to the cvterm table where the name is the full accession number.

```
select DB.name, CVT.name, DBX.*
from dbxref DBX 
  inner join cvterm CVT on CVT.dbxref_id = DBX.dbxref_id
  inner join db DB on DB.db_id = DBX.db_id
where DBX.accession = '0002202' or CVT.name = 'RO:0002202'
```

**Comment by spficklin** [comment]
Adding @srobb1 to this so she knows when this gets worked on.

**Comment by spficklin** [comment]
Fixed with pull request

**Comment by srobb1** [comment]
@shawnawsu @spficklin I am super excited! I will test this out as soon as I get a bit of time. I have been in the weeds. I was just cleaning out my inbox and saw the messages about this. This is a great reason to clean up my inbox :)

**Comment by spficklin** [comment]
@srobb1 we have yet to backport this fix to Tripal v2, so it may not work for you just yet....

**Comment by spficklin** [comment]
I'm reopening just to remind us to backport to Tripal v2.

**Comment by spficklin** [comment]
PR was merged... closing the issue.
