### ISSUE TITLE
[bug] fatal error:   Class 'WebServicesField' not found i

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#257]
I think the latest patch @spficklin fixing the jobs queue broke the jobs admin area at  `admin/tripal/tripal_jobs`. 

 Visiting there returns 

`Fatal error: Class 'WebServicesField' not found in /data/www/html/hardwoods_dev/drupal-7.52/sites/all/modules/tripal/tripal_ws/includes/TripalFields/remote__data/remote__data.inc on line 9`

Same error also prevents cache from being cleared.

**Comment by spficklin** [comment]
Fixed with pull request by @bradfordcondon
