### ISSUE TITLE
Unable to create organism entity

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#26]
Following http://tripal.info/tutorials/v3.x/example-genomic-site/organism, there appears to be a bug adding the image.

If I fill in everything as instructed including **clicking the "upload" button** after browsing for the image then on submit the entity is not created, the form is reset and I see the following error:
> Could not save the entity: SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "field_data_data__image" does not exist LINE 1: INSERT INTO field_data_data__image (entity_type, entity_id, ... ^
> Cannot save entity

If I fill out the form, browse for the image but **don't click upload** before submitting the form then I see the same symptoms as stated above.

If I **don't add an image** but fill out the other fields as instructed then the entity is created but the page I'm redirected to (the entity view page) is a white error page with the following PDO Exception:
> PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "field_data_data__image" does not exist LINE 3: field_data_data__image t ^: SELECT t.* FROM {field_data_data__image} t WHERE (entity_type = :db_condition_placeholder_0) AND (entity_id IN (:db_condition_placeholder_1)) AND (language IN (:db_condition_placeholder_2)) AND (deleted = :db_condition_placeholder_3) ORDER BY delta ASC; Array ( [:db_condition_placeholder_0] => TripalEntity [:db_condition_placeholder_1] => 2 [:db_condition_placeholder_2] => und [:db_condition_placeholder_3] => 0 ) in field_sql_storage_field_storage_load() (line 412 of /var/www/dev/tripal3/modules/field/modules/field_sql_storage/field_sql_storage.module).

I'm able to create other Tripal Content without images (e.g. project) just fine.

**Comment by spficklin** [comment]
This is odd.  We saw this error on an upgrade site, but then it disappeared so we were not able to reproduce it.  On our tests we've been able to create organism pages just fine.  For some reason, when the organism image field is created programmatically, the Drupal Field for Images isn't creating the table to store it's information.   Are you creating a site from scratch or upgrading?

**Comment by laceysanderson** [comment]
I'm creating it from scratch as per the tutorial

**Comment by spficklin** [comment]
Okay, the problem was in the chado_set_active() function.  There was a bug in that it wasn't returning the correct previous database and the 'field_data_data__image' table was being created in the 'chado' schema rather than the 'public' schema.  That function is fixed and I tested loading from scratch and it works now.  You'll need to grab the development version.  

For a quick fix, just move the 'field_data_data__image' and 'field_data_data__image_revision' table back to 'public'.
