### ISSUE TITLE
Dynamic Tripal Pane labels

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#262]
## Request/Question

Tripal Pane labels that are dynamic and/or can be set by fields.  OR a way to change each organism's tripal pane labels individually. 

## Why I'm requesting it

I have two cases so far where I want the Tripal Pane to have a different display name based on properties of the bundle. One is our "Transcriptome/Genome" field attached to organism, which links out to the corresponding analysis.  They are both analysis unigenes but I split them, entirely because I wanted the tripal pane to say genome/transcriptome as appropriate.

I now have another case, for Jbrowse.  For our draft genomes, Jbrowse is an alignment to a reference. For our reference genomes, Jbrowse is the ref sequence with annotations.  We are thinking about having the tripal pane say something other than Jbrowse for the drafts.  But the only way I know of to do this right now is to create two Jbrowse fields, and put each one in an appropriately labeled Tripal Pane.

**Comment by spficklin** [comment]
Hey @bradfordcondon.  Just to make sure I understand.   If you got to Admin -> Structure -> Tripal Content Types, click the content type you are interested in, then find the field and click 'manage fields' link, and on the field you're interested in, click the 'edit' link and change the Label.  Would that resolve the problem?  You could then change the label as needed.

**Comment by bradfordcondon** [comment]
Hi Stephen:

Unfortunately  no, because when the field is attached to organism X I want the label to read genome, and when the field is attached to organism Y I want the label to read transcriptome.

**Comment by spficklin** [comment]
What is the controlled vocabulary term you are using?  Does it really cover both?  Should you consider perhaps using two different terms and that would solve the problem.

**Comment by bradfordcondon** [comment]
That was the solution I did implement.  Two CVterms: one for Transcriptome, one for genome.  I could have more easily implemented a single field: nucleotide assembly, which covered both.  Then have the display change depending on what the field contains.   

In the case of a Jbrowse view... I'd need a cvterm for "Jbrowse of a transcriptome aligned to a reference" and "Jbrowse of a genome".   Here it seems more cumbersome than in the previous example to define two seperate fields.


Sounds like you think any case where one would want this functionality, you should instead define separate fields.

**Comment by spficklin** [comment]
I think if you really do want to differentiate then you should use the differentiating ontology term.  Use of the term is where the distinction really lies.  When sharing data between sites, it wouldn't be fair to make the remote site see 'nucleotide assembly' while local user see a difference in the label.  Everyone should understand what that field is regardless if they view it via the web site, or web services and the only way to do that would be to use the proper term as that is where the true differentiation should occur, and not necessarily on the label.  

It's up to you if you want to distinguish between a view on JBrowse that shows a genome or a transcriptome.  I think that if you simply have a 'JBrowse View' term (or equivalent) then that's adequate to describe it.

**Comment by bradfordcondon** [comment]
>I think if you really do want to differentiate then you should use the differentiating ontology term. 

Pretty fair point I guess.  Thanks for the discussion.
