### ISSUE TITLE
Docs: further explanation of field methods

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#266]
I added the elementinfo, query, and queryorder  methods to my protocol field.  [Here's my progress](https://github.com/statonlab/tripal/blob/protocol_extra_methods/tripal_chado/includes/TripalFields/sep__protocol/sep__protocol.inc).  I have some questions.

I'm also sharing the things that i realized i really didnt understand, not just to embarrass myself but with the hopes that we can address them in the developer documents.

# Questions: 
## elementInfo

Whats the rule for what I need to provide info for here?  For example, obi__organism describes genus, species, infraspecific name, and type.  publication, on the other hand, describes no individual columns.   But, publication does use more than just `value`: it sets the chado-field_table. __ pkey, fkey_column,and pub_id.  Why dont those need to be described in elementinfo? 

## Foreign keys

I don't really understand what to do with foreign keys sofar as elementinfo/query is concerned.  

## query order

the type_id foreign key in the organism field uses `$joins` but this variable is not defined.  
```
 if ($order['column'] == $infraspecific_type_term) {
      if (!in_array('CVT', $joins)) {
        $this->queryJoinOnce($query, 'cvterm', 'CVT', "base.type_id = CVT.cvterm_id");
      }
      $query->orderBy("CVT.name", $order['direction']);
    }
```
I'm kind of copy-pasting too much to truly get what it should be or if its even a mistake....

# Thoughts

I really, really didn't understand the whole "elements" array thing.  Now it looks so obvious:  `$entity->{$field_name}['und'][0]` starts at 0 and increments by one for each entry in this field.

e:  we were also wondering why undefined for language code?  Why not english?

>0 is the cardinality.  Increment by 1 when more than one item is available.

This makes sense in hindsight, but maybe in the dev docs we can hammer on the idea that the field should more clearly define the element concept?

From schema__publication: ` 'chado-' . $field_table . '__' . $pkey`  is one of the keys.  

a) so $field_table is this field's linker table ie organism_publication (if it were attaching to the organism base table), right?
b) Are the recommended naming ocnventions for the keys anywhere?  It seems like your field keys are too the tune of 'chado-table_name__column`.  Needless to say our fields do not follow this convention: is this problematic?

**Comment by spficklin** [comment]
Hey @bradfordcondon rather than answer your question here, I think it might be a good idea to start the document in the Developer's Guide that answers these questions.  Then the answers are accessible to all. Can you wait a bit on answers for us to get that done?

**Comment by bradfordcondon** [comment]
Of course.  I'll hold off on further questions until thats together unless you find my misunderstandings helpful in writing the docs.

Also I'm happy to contribute or provide feedback on the documentation, please let me know.

**Comment by spficklin** [comment]
@bradfordcondon I've added documentation to the Developers Handbook.  There is new information about the **elementInfo** function towards the bottom. I have also started on the **query** function but have not yet finished. Can you check it to see if it makes sense to you and answers your questions?

http://tripal.info/http%3A//tripal.info/tutorials/v3.x/developers_handbook/custom-field/manual

**Comment by bradfordcondon** [comment]
Hi Stephen, this was great.

My main unanswered question is who uses the `query()` method?  Views?  What information should I expect in the `$condition` variable and/or where can i look this up?

I see now that the `$query` variable being passed is an actual Drupal query object!  Cool!  I think I didnt know what that was when  i created this issue so maybe that should go in the guide?  Maybe [link to this guide?](https://www.drupal.org/docs/7/api/database-api/dynamic-queries/introduction-to-dynamic-queries)   You can maybe imagine not understanding this piece made it tough for me to get what was going on here.

**Comment by spficklin** [comment]
We wont' get this done in time for the release and this isn't an issue that affects stability. so I'm taking off the release blocker.

**Comment by laceysanderson** [comment]
Closing this as it's now outdated with the move to Tripal 4.
