### ISSUE TITLE
Small gotcha's related to the tutorial

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#27]
### Gotcha 1)
When creating an analysis (http://tripal.info/tutorials/v3.x/example-genomic-site/analysis), the tutorial specifies the Time Executed as Feb 1, 2011. However, the time executed field in Tripal 3 only provides 2014-2020 as options in the year drop-down. Either we should change the tutorial or configure this field to have a textfield for the year.
![screen shot 2017-02-14 at 3 27 26 pm](https://cloud.githubusercontent.com/assets/1566301/22950112/231f0fa4-f2ca-11e6-90d5-1a1e0a4042ed.png)

**Comment by spficklin** [comment]
Oh, that's interesting. It's a drupal date field and I just noticed that if you edit the field then you can set the range of years that will appear in the dropdown.  The default is +-3 years.  Perhaps we should change the default to +10?

**Comment by spficklin** [comment]
Oh, and for the time being... I fixed the tutorial to not specify an exact date.  Thanks for pointing that out.

**Comment by laceysanderson** [comment]
I figured it could be changed in config :-) Setting a default of +10 might be sufficient...

**Comment by laceysanderson** [comment]
### Gotcha 2)
The tutorial shows screenshots and describes the Tripal Panes layout but due to #28, users following the tutorial won't see those layouts.
![screen shot 2017-02-14 at 4 30 33 pm](https://cloud.githubusercontent.com/assets/1566301/22952498/f0e4ee6a-f2d2-11e6-8c75-e9877c4c6565.png)

**Comment by laceysanderson** [comment]
### Gotcha 3)
The Citrus_sinensis-orange1.1g015632m.g.gff3 GFF3 won't load because scaffold is not a term in the Sequence Ontology.
> Running as user 'tripaladmin'
> Calling: tripal_feature_load_gff3(/var/www/html/sites/default/files/Citrus_sinensis-orange1.1g015632m.g.gff3, 2, 1, 0, 1, 0, 0, 1, , , 0, , , , 0, 5)
> 
> NOTE: Loading of this GFF file is performed using a database transaction. 
> If the load fails or is terminated prematurely then the entire set of 
> insertions/updates is rolled back and will not be found in the database
> 
> Opening /var/www/dev/tripal3/sites/default/files/Citrus_sinensis-orange1.1g015632m.g.gff3
> WD tripal_chado: cannot find feature term 'scaffold' on line 3 of the GFF file                 [error]
> [site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] cannot find feature term 'scaffold' on line 3 of the GFF file

This is confirmed both my searching my database as well as sequenceontology.org. We're supposed to use supercontig: http://www.sequenceontology.org/browser/current_svn/term/SO:0000148 

Fixed File:
[Citrus_sinensis-orange1.1g015632m.g.gff3.txt](https://github.com/tripal/tripal/files/775963/Citrus_sinensis-orange1.1g015632m.g.gff3.txt)

**Comment by laceysanderson** [comment]
Gotcha 4)
When I publish the gene I see the following errors:
> Warning: implode(): Invalid arguments passed in date_limit_format() (line 2262 of /var/www/dev/tripal3/sites/all/modules/date/date_api/date_api.module).
> Warning: implode(): Invalid arguments passed in date_limit_format() (line 2262 of /var/www/dev/tripal3/sites/all/modules/date/date_api/date_api.module).

The genes and mRNA are still published though :-)

**Comment by spficklin** [comment]
For gotcha #2 we'll have a fix for issue #28

**Comment by spficklin** [comment]
For gotcha #3 the cvtermsynonym table was being emptied after OBO loading in the Chado/Drupal prepare step.  This is why 'scaffold' could not be found.  The GFF loader accepts terms and their synonyms so it should have worked.   I've committed a fix and tested and I no longer encounter the problem.

The quick fix is to reinstall the ontologies.

**Comment by spficklin** [comment]
For gotcha 4 that's shows up quite a bit... we need to figure that out.  I'm going to close out this issue. Gotcha #2 will be fixed when Issue #28 is fixed.  And gotcha #4 will get fixed eventually....

**Comment by spficklin** [comment]
BTW... if you think any of these gotchas need to remain open can you post each one as a separate issue so it's easier to close them out :-)
