### ISSUE TITLE
what should my postgres drupal search_path be?

### ISSUE THREAD

**Issue by srobb1** [tripal/tripal#270]
Hi,

What should my search_path be in my drupal db?

Here is what I have:

```
drupal=# show search_path ;
     search_path
----------------------
 chado,"$user",public
(1 row)
```

The reason I am asking, is that I am trying to add a couple of new fields to my user registration form within the manage fields tab (admin->configuration->people->account settings). I keep getting a Duplicate Table error when I hit save the first time.
```
Attempt to update field First Name failed: SQLSTATE[42P07]: Duplicate table: 7 ERROR: relation "field_data_field_first_name" already exists.
```

When I check my db I see this table in only my chado schema and not in public. Shouldn't it be in public?

```
 chado  | field_revision_field_first_name                          | table | drupal
 chado  | field_revision_field_user_first_name                     | table | drupal
```

Thank you,
Sofia

**Comment by laceysanderson** [comment]
Mine is: 
```
psql=# show search_path ;
  search_path   
----------------
 "$user",public
(1 row)
```
And Yes, those tables should be in the public schema. I would drop the table, change the search path and then try again :-)

**Comment by srobb1** [comment]
That is what I suspected it should be. How do I permanently change the search_path? 
`set search_path to public` only changes it temporarily in the open session.

**Comment by laceysanderson** [comment]
I've always done that by altering the search_path for the user connecting to the database (specified in your `sites/default/settings.php` as follows:
```sql
ALTER ROLE [your user] SET search_path TO "$user",public;
```

**Comment by srobb1** [comment]
Great! I will try that. Thank you Lacey!

**Comment by spficklin** [comment]
I concur with @laceysanderson. I'm going to mark this closed but comment again if there are still issues
