### ISSUE TITLE
Drupal index error happens after completing the migration on large sites

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#276]
### System information

* Tripal Version: 3
* Drupal Version: 7.56
* PostgreSQL Version: 9.3.20
* PHP Version: 7.0.26

### Issue description
If you are encountering PHP memory issues when running cron, the problem may be similar to this issue. I am posting this here as informational rather than an issue.

The last step of migrating tripal 2 to tripal 3 is to delete all tripal 2 nodes. When there is a large number of nodes, Drupal's search module (which comes standard with every Drupal installation and is a dependency of Tripal) fails to update the search_total table and gives the following error:

```
<h1>Uncaught exception thrown in shutdown function.</h1><p>PDOException: SQLSTATE[54001]: Statement too complex: 7 ERROR:  stack depth limit exceeded
HINT:  Increase the configuration parameter &amp;quot;max_stack_depth&amp;quot; (currently 9216kB), after ensuring the platform&amp;#039;s stack depth limit is adequate.: DELETE FROM {search_total} 
WHERE ( (word = :db_condition_placeholder_0) OR (word = :db_condition_placeholder_1) OR (word = :db_condition_placeholder_2) OR (word = :db_condition_placeholder_3)

... and son

Array
(
    [:db_condition_placeholder_0] =&amp;gt; 0
    [:db_condition_placeholder_1] =&amp;gt; 000c10c11
    [:db_condition_placeholder_2] =&amp;gt; 001047d04
    [:db_condition_placeholder_3] =&amp;gt; 00400wd
    [:db_condition_placeholder_4] =&amp;gt; 0140j
    [:db_condition_placeholder_5] =&amp;gt; 01p131
    [:db_condition_placeholder_6] =&amp;gt; 01v1a
    [:db_condition_placeholder_7] =&amp;gt; 0308236a
    [:db_condition_placeholder_8] =&amp;gt; 03140a
    [:db_condition_placeholder_9] =&amp;gt; 03bb102
    [:db_condition_placeholder_10] =&amp;gt; 03bb108
    [:db_condition_placeholder_11] =&amp;gt; 03v1b

 ... and so on

)  in search_update_totals() (line 396 of /var/www/html/modules/search/search.module).</p><hr />
```
This error only becomes available only when giving PHP a memory limit of 15+GB. Otherwise, it fails with a max memory reached error (which is much harder to diagnose).

Our solution to this was to simply truncate the search_total and search_index tables and ask Drupal to reindex and that cleared the error.

#### Fix
Run the queries somewhere within your drupal installation:
```php
db_query('TRUNCATE {search_total}')
db_query('TRUNCATE {search_index}')
```
Then visit `/admin/config/search/settings` and click the reindex button. Cron should start reindexing thereafter.

Hope this helps.

Thanks!

**Comment by spficklin** [comment]
Hey @almasaeed2010 what module are you using that is updating those tables?  We do not instruct users to use the Drupal search indexing with a default Tripal install, so I'm curious what you did with your Tv2 site to get those tables populated?

**Comment by almasaeed2010** [comment]
Hi,

It seems that our site uses the default search module that comes bundled with Drupal 7. You can find the module in `/drupal-path/modules/search` (not in sites/all/modules). It's automatically enabled during the installation process of Drupal. 

Thanks!

**Comment by almasaeed2010** [comment]
This might also help. In the modules page, the search module appears as a dependency of Tripal.
<img width="1328" alt="screen shot 2018-02-07 at 8 42 00 am" src="https://user-images.githubusercontent.com/1512664/35919367-dde6c6ce-0be2-11e8-9bf5-24a10c7d15e1.png">

**Comment by laceysanderson** [comment]
Do we know if this is still an issue?

**Comment by spficklin** [comment]
I think this will be an issue with few sites.  So, I'm going to mark this as closed. Thanks @almasaeed2010 for documenting the problem and the fix!

**Comment by spficklin** [comment]
I added your tips to the upgrade documentation @almasaeed2010
