### ISSUE TITLE
DB deadlock caused by tripal_chado

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#278]
### System information

* Tripal Version: 3.0-rc1
* Drupal Version: 7.5
* PostgreSQL Version: 9.3
* PHP Version: 7.0

### Issue description

We discovered an odd issue where deadlocks occur with Tripal when parallel or threaded executions happen simultaneously (or very close to each other). Example, when 5 users visit the site at the same time, our site takes a while to load and eventually displays this error:
```
PDOException: SQLSTATE[40P01]: Deadlock detected: 7 ERROR: deadlock detected DETAIL: Process 12272 waits for ShareLock on transaction 290919939; blocked by process 12228. Process 12228 waits for ShareLock on transaction 290920181; blocked by process 12272. HINT: See server log for query details.: UPDATE variable SET value=:db_update_placeholder_0 WHERE ( (name = :db_condition_placeholder_0) ); Array ( [return] =&gt; 2 [already_prepared] =&gt; 1 ) in variable_set() (line 1245 of /var/www/html/includes/bootstrap.inc).
```

We managed to track it down to this variable_set() call in TripalChado:
https://github.com/tripal/tripal/blob/cd364447d64118e0d85fd48cd197897e72b28d57/tripal_chado/api/tripal_chado.schema.api.inc#L277

Which results in this query:
```sql
UPDATE variable SET value='\x623a303b'
WHERE ( (name = 'chado_schema_exists') )
```

Commenting out the variable_set lines in `chado_is_local()` stops deadlocks from occurring.

Would it make sense to move the variable_set() calls to the install file instead? Or somehow prevent them from executing on every page load?

Thanks!

**Comment by spficklin** [comment]
Hey @almasaeed2010. I applied a fix that I hope will fix the issue.  Do you have a way to test the fix?

**Comment by almasaeed2010** [comment]
Hi, I just tested the code with 6 threads and the error hasn't happened so looks like this is fixed!

Thanks!
