### ISSUE TITLE
No Tripal Panes by default when Tripal DS is enabled

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#28]
When following the Tripal 3 tutorial (http://tripal.info/tutorials/v3.x/installation/tripal), you
1. Install Tripal Core
2. Install Tripal Chado
3. Install Chado schema & prepare chado/drupal (created basic content types including organism)
4. Install Tripal DS

Following this workflow I don't get the default arrangement of Tripal Panes for all the original basic content types created via preparing your Chado/Drupal database. Tripal panes are available as a group formatter and the layout is available but I would have to build the hierarchy myself.

However, any new content types I create (e.g. genetic_marker) will have the default layout. In other words, Any **content types existing before Tripal DS is enabled are not getting a default arrangement**; where as, **content types created after Tripal DS is enabled are**.

This is incongruent with the tutorial which shows the organism and analysis as having Tripal Panes when following the current order of the tutorial doesn't actually produce that effect.

Do we want to apply default grouping on pre-existing Tripal Content Types? We would run the risk of overriding custom settings if we did... That said, if we don't then what about those admin that don't enable Tripal DS to begin with thinking they want to customize everything themselves and then change their mind after realizing how much work it is ;-). Thoughts?

**Comment by spficklin** [comment]
Fixed in two ways:

1. Reorganized the Tripal tutorial to have the tripal_ds module installed before Chado/Drupal is prepared
2. Added a link on the "Manage Display" page of each content type that allows you to reset the layout to the default Tripal Layout.  This way if you have a content type that was created prior to have tripal_ds enabled you can still switch it over.
