### ISSUE TITLE
Tripal Job, ignore_duplicates default is TRUE?

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#280]
### System information
* Tripal Version: 3

### Issue Description
With Tripal 3, the option to "ignore duplicates" when submitting jobs was added and the default was set to TRUE. This, however, is not backwards compatible, since it doesn't match the behavior of Tripal 2 which didn't have the ability to detect duplicates. This caused unexpected behavior which broke the Tripal Download API.

## Discussion
**Do we go for backwards compatibility and set the default to FALSE?**

OR

**Do we go for what could be argued as ideal and leave the default as TRUE?**

**Comment by laceysanderson** [comment]
## My Vote
I think we should go for **backwards compatibility**. As I said, this broke the Tripal Download API which shouldn't have needed changes for Tripal 3. 

That said, I'm willing to have my mind changed ;-)

**Comment by spficklin** [comment]
Code has been fixed for backwards compatibility.  Please reopen if you have further issues.
