### ISSUE TITLE
unable to delete CVs via admin interface

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#285]
### System information

* Tripal Version: 3
* Drupal Version: 7.56 
* PostgreSQL Version: 9.6.1
* PHP Version:7.1.7

### Issue description

Manually deleting CVs in the admin interface has no effect- instead I'm looped back to the edit scene with the name box highlighted.

<img width="725" alt="screen shot 2018-02-10 at 1 37 36 pm" src="https://user-images.githubusercontent.com/7063154/36065357-99131ebc-0e67-11e8-896e-d9ec42979f3e.png">

**Comment by spficklin** [comment]
I just pushed a fix for this.  Can you try again?

**Comment by bradfordcondon** [comment]
No change.

For the heck of it i tried changing the name before deleting and have this message:

<img width="1222" alt="screen shot 2018-02-12 at 4 52 39 pm" src="https://user-images.githubusercontent.com/7063154/36121754-2a7e8766-1015-11e8-908c-bf15e94305ac.png">


Another menu item index problem?

**Comment by bradfordcondon** [comment]
There is no `cv_id` value in the form.

<img width="582" alt="screen shot 2018-02-12 at 5 10 01 pm" src="https://user-images.githubusercontent.com/7063154/36122515-97c91096-1017-11e8-9b7d-476868ec79c8.png">




actually looking at the code, there should be  a select element (line 89) but I dont have one?
here is a dpm of $form right after that select:

<img width="1440" alt="screen shot 2018-02-12 at 5 13 32 pm" src="https://user-images.githubusercontent.com/7063154/36122638-19dbfaa8-1018-11e8-94c8-a2c5b9c1e66e.png">

What's going on here?

**Comment by spficklin** [comment]
Oh, I forgot to tell you to clear your menu cache...

**Comment by spficklin** [comment]
Your screen shot isn't quite right.... I replaced the "Delete" button with a link and it uses Drupal's confirm_form instead of that awful popup.

**Comment by bradfordcondon** [comment]
edit argh there i see the comit, nevermind

**Comment by bradfordcondon** [comment]
I see the confusion.  [You pushed the commit to the collections branch, not to master](https://github.com/tripal/tripal/commit/06217513fb1729d5f4a115a85e58bf8d4d66ef93).

**Comment by bradfordcondon** [comment]
I tested that branch and was able to delete 👍 thanks  (leaving issue open until we merge to master)

**Comment by spficklin** [comment]
Oh, sorry about that.... I'll see if I can merge those fixes into the 7.x-3.x branch.

**Comment by shawnawsu** [comment]
@spficklin Has this been merged into master?

**Comment by bradfordcondon** [comment]
this is in #307 @shawnawsu . I'ts not merged yet but will be soon so i think we can reasonably close this issue.
