### ISSUE TITLE
Inconsistent use of CV for feature_relationship between Tripal and Perl Chado backend

### ISSUE THREAD

**Issue by mdondrup** [tripal/tripal#287]
### Issue description

Hi,
I am not sure if I had reported that before, but I have noticed that Tripal does not co-exist well together with a GBrowse instance running on the same Chado database. The symptoms could be that GBrowse is unable to render sub-features (exons, UTR) for genes or transcripts in a Tripal installed Chado. I have analysed the code and have the hypothesis that this might be caused by different names of the relationship ontology. Perl Bio::DB::Das::Chado seems to use the following code: 

```
# get the cvterm relationships here and save for later use
  my $cvterm_query="select ct.cvterm_id,ct.name as name, c.name as cvname
                           from cvterm ct, cv c
                           where ct.cv_id=c.cv_id and
                           (c.name IN (
                               'relationship',
                               'relationship type','Relationship Ontology',
                               'autocreated')
                            OR c.cv_id = ?)";
```
Tripal seems to use "feature_relationship" as the only name for the ontology to determine feature relationships. 

See
https://github.com/tripal/tripal/search?q=feature_relationship&type=Code&utf8=%E2%9C%93
vs. 
http://cpansearch.perl.org/src/SCAIN/Bio-DB-Das-Chado-0.35a/lib/Bio/DB/Das/Chado.pm

### System information

* Tripal Version: 2.x-3.x (seems like to be present in all versions)
* Drupal Version: 7
* PostgreSQL Version: 
* PHP Version: 5.4
* Bio-DB-Das-Chado-0.35a

**Comment by spficklin** [comment]
This problem may be due to the fact that the Relationship Ontology has changed dramatically and as a result we had to force Tripal to use other terms.  Maybe @scottcain has some insight here.

**Comment by spficklin** [comment]
I wonder how GBrowse is dealing with old relationship ontology terms no longer being the same....

**Comment by mdondrup** [comment]
I have for now temporarily fixed the problem on the GBrowse side by adding 'feature_relationship' to the CV names to search in Bio::DB::Das::Chado.

**Comment by spficklin** [comment]
@mdondrup when you say you temporarily fixed it, do you mean you had to change the GBrowse code?

**Comment by laceysanderson** [comment]
I'm closing this as it has been well over a year with no movement. Furthermore, the original submitter has found a solution that is working for him.
