### ISSUE TITLE
Tripal + GBrowse

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#289]
We need to add to our Demo site a GBrowse instance to help ensure compatibility and avoid issues as described by issue #287

**Comment by mdondrup** [comment]
I support that proposition. In addition I would also recommend to test the Tripal instance with content added by the Perl Chado data loaders to ensure compatibility and also mixed imports.

**Comment by spficklin** [comment]
Great ideas here, but due to time constraints, i'm going to close this out, but mark it as "Maybe Later".
