### ISSUE TITLE
Database Reference not formed correctly when loading FASTA

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#29]
Working through the tutorial (http://tripal.info/tutorials/v3.x/example-genomic-site/genomic-data), I load the mRNA FASTA and add in the "Advanced Options" for automatically creating the database references. During loading the Tripal job doesn't report any errors yet when I go to the mRNA page after publishing content, the database reference link is `<a href="https://phytozome.jgi.doe.gov/phytomine/portal.do?externalid=PAC:Phytozome:">Phytozome:</a>`

When I poke in the database, this is what I see:
```
SELECT 
     f.feature_id, 
     f.name, 
     f.uniquename,
     fd.dbxref_id, 
     db.name as db_name, 
     dbxref.accession as dbxref_accession 
  FROM chado.feature f 
    LEFT JOIN chado.feature_dbxref fd ON fd.feature_id=f.feature_id 
    LEFT JOIN chado.dbxref ON dbxref.dbxref_id=fd.dbxref_id 
    LEFT JOIN chado.db ON db.db_id=dbxref.db_id 
  WHERE f.type_id=422 
  ORDER BY feature_id ASC, db.name ASC;

 feature_id |       name        |  uniquename  | dbxref_id |  db_name   | dbxref_accession 
------------+-------------------+--------------+-----------+------------+------------------
          3 | orange1.1g015632m | PAC:18136217 |     77549 | GFF_source | phytozome6
          3 | orange1.1g015632m | PAC:18136217 |     77551 | Phytozome  | 
         20 | orange1.1g015645m | PAC:18136218 |     77549 | GFF_source | phytozome6
         20 | orange1.1g015645m | PAC:18136218 |     77551 | Phytozome  | 
         37 | orange1.1g015615m | PAC:18136219 |     77549 | GFF_source | phytozome6
         37 | orange1.1g015615m | PAC:18136219 |     77551 | Phytozome  | 
         53 | orange1.1g015662m | PAC:18136220 |     77549 | GFF_source | phytozome6
         53 | orange1.1g015662m | PAC:18136220 |     77551 | Phytozome  | 
         68 | orange1.1g017341m | PAC:18136221 |     77549 | GFF_source | phytozome6
         68 | orange1.1g017341m | PAC:18136221 |     77551 | Phytozome  | 
         82 | orange1.1g018514m | PAC:18136222 |     77549 | GFF_source | phytozome6
         82 | orange1.1g018514m | PAC:18136222 |     77551 | Phytozome  | 
         98 | orange1.1g022520m | PAC:18136223 |     77549 | GFF_source | phytozome6
         98 | orange1.1g022520m | PAC:18136223 |     77551 | Phytozome  | 
        110 | orange1.1g022799m | PAC:18136224 |     77549 | GFF_source | phytozome6
        110 | orange1.1g022799m | PAC:18136224 |     77551 | Phytozome  | 
        123 | orange1.1g022797m | PAC:18136225 |     77549 | GFF_source | phytozome6
        123 | orange1.1g022797m | PAC:18136225 |     77551 | Phytozome  | 
(18 rows)
```

Also, just in case it's relevant, the feature.dbxref_id is empty.

I've tried this process three times on two fresh installs and this result is repeatable.

**Comment by spficklin** [comment]
The problem is with the Tutorial and not with the FASTA loader.  There were two problem:

1.  The URL Prefix for the Phytozome database should have been:  https://phytozome.jgi.doe.gov/phytomine/portal.do?externalid=PAC:{accession}.  Note the {accession} token.   Tripal v3 supports two tokens in the URL prefix: {accession} and {db}.  This is because not all URLs schemas want the {db}:{accession} appended to the end.  These tokens provide flexibility. 
2.  There was a typo in the regular expression for finding the accession. It should have been:  ^.\*PAC:(\d+).\*$

I've updated the tutorial to fix both of these issues.  I've also added details about the {db} and {accession} tokens.

**Comment by laceysanderson** [comment]
Oh! That's Awesome new functionality! Glad this one was a documentation issue rather then a bug :-)
