### ISSUE TITLE
newick tree loader db issue

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#290]
### System information

* Tripal Version: 3 
* Drupal Version: 7.56
* PostgreSQL Version: 9.6.1 
* PHP Version: 7.1.7

### Issue description

Two issues:

#### Loader doesnt allow missing accessions despite saying it does

The loader reads:

>Enter a database cross-reference of the form [DB name]:[accession]. The database name must already exist in the database. If the accession does not exist it is automatically added.

However, attempting to insert a tree with an accession not in the db fails validation:
`The dbxref provided does not exist in the database: .`

I think this is because of the below code (line 193, `tripal_chado.phylotree.api.inc`:

```
 $db_name = $matches[1];
    $accession = $matches[2];
    $values = array(
     'accession' => $accession,
      'db_id' => array(
        'name' => $db_name
      ),
    );
    $dbxref = chado_generate_var('dbxref', $values);
    
    if (!$dbxref) {
      $errors['dbxref'] = t('The dbxref provided does not exist in the database: %dbxref.', array('%dbxref' => $dbxref));
      return FALSE;
    }
    $options['dbxref_id'] = $dbxref->dbxref_id;
  }
```
I get confused by chado_generate_var but i can fix this... inserting the term beforehand resolves the issue.

#### Loader can't bulk load

This is the bigger issue.  It really needs to be able to load in mutliple newick trees.  It also needs to be able to assign those trees to accessions in bulk: that part is trickier, unless the name of the tree is the accession.

Anthony has developed this feature for his chado_python module so I'll likely try to adopt that, but i imagine this will be a desired feature for other adopters.

**Comment by bradfordcondon** [comment]
shoot: inserting the term beforehand passes validation, but fails in the load step with 

```

SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "dbxref_id" violates not-null constraint
DETAIL:  Failing row contains (4, null, , 531, null, null).
WD tripal_job: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "dbxref_id" violates not-null constraint     [error]
DETAIL:  Failing row contains (4, null, , 531, null, null).
[site http://default] [TRIPAL ERROR] [TRIPAL_JOB] SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "dbxref_id" violates not-null constraintDETAIL:  Failing row contains (4, null, , 531, null, null).

```

**Comment by laceysanderson** [comment]
Just going through old issues, assigning tags (organizing makes me happy :-) )...
Did you ever make progress on this?

**Comment by bradfordcondon** [comment]
no i havent addressed :(

could it be related to  https://github.com/tripal/tripal/issues/345 ?

**Comment by shawnawsu** [comment]
Hi @almasaeed2010, I know Bradford is on vacation so I don't want to ping him but wanted to check if any movement has happened on this? From the ticket history, it looks like you two have been working on this a bit.

**Comment by almasaeed2010** [comment]
Hello @shawnawsu 
Sorry for the delay! I looked into our issues queue and it looks like this is no longer a problem for us. However, I can't verify that until Bradford gets back. I'll make sure to remind him this coming Monday.

Thanks!

**Comment by bradfordcondon** [comment]
I haven't touched it unfortunately: its not an issue for us because we dont use the loader.  

* Easy to fix the dbxref issue.
* Loading multiple trees (particularly multiple trees per newick file) is a bit trickier.  

I'd like to add these things but not likely I will until HWG needs to load in trees...

**Comment by bradfordcondon** [comment]
## Should fix for release blocker

* type lookup gives ajax error
   - easy resolution: the cv lookup is to the legacy cv module
* `Undefined index: files in NewickImporter->formValidate() (line 182 of /Users/chet/UTK/tripal/sites/all/modules/tripal/tripal_chado/includes/TripalImporter/NewickImporter.inc).`
   - easy resolution: Importers let the base class handle the file validation
* warning while publishing (see below)
  - i get this warning for all my entities right now.  its when the ID is null.  not related to this issue.
*  tree publishes with no name
   - resolved with simple fix in the `run` argument 
* Phylotree type is automatically changed to polypeptide despite mRNA being entered
  - resolved with simple fix in the `run` argument
```
`chado_publish_records(Array) array_flip(): Can only flip STRING and INTEGER values!                       [warning] entity.controller.inc:219

```
## feature request (seperate PR?)

* load multiple trees in a single newick file

**Comment by spficklin** [comment]
This issue is on my TODO list.   Does this new error mean you are now loading trees or is this from unit testing?

**Comment by bradfordcondon** [comment]
I was checking the status of this issue, we are not loading trees into our site.  I am loading via GUI to see the status of the issue.   The bugs i've spotted are from running through just now, quite different frmo the original issue.

Are you actively working on this?  I can work on something else instead.

**Comment by spficklin** [comment]
Not actively now.  I have some test tree data for loading.  One thing I wanted to fix with this loader is that if the features do not exist on the site then the loader fails.  I want to see if we can create a solution for that so that folks don't have to write complex loaders to get their features in first before loading trees.

**Comment by spficklin** [comment]
If you want to work on this one I'd be happy to share the data I have

**Comment by bradfordcondon** [comment]
Here's the tree file with devseed. 

https://github.com/statonlab/tripal_dev_seed/blob/master/Fexcel_mini/sequences/mrna_mini.fasta.tree

We can add that feature too but not sure its a release blocker (like my original request to import newick files with multiple trees inside).

The  bugs i listed above however are probably release blockers (or we cut the loader).

I think its a good issue for me since I know all the parts involved.  I can work on it.  If you want to share your test data so i can ensure it loads too, go ahead.

**Comment by bradfordcondon** [comment]
we have agreed that a) dealing with multiple organisms / file and b) dealing with multple trees per file should each be their own issues.  This issue is just for releaseblockers related to the importer giving errors etc

**Comment by bradfordcondon** [comment]
new error now that i've fixed all of the above (except the array flip thing while publishing): 

```

Remapping Chado Controlled vocabularies to Tripal Terms...
Done.
WD php: Error: Call to a member function fetchObject() on null in                          [error]
tripal_chado_bundle_get_properties() (line 2820 of
/Users/chet/UTK/tripal/sites/all/modules/tripal/tripal_chado/includes/tripal_chado.fields.inc).
Cannot modify header information - headers already sent by (output started at              [warning]
phar:///usr/local/bin/drush/includes/output.inc:41) bootstrap.inc:1486
Error: Call to a member function fetchObject() on null in tripal_chado_bundle_get_properties() (line 2820 of /Users/chet/UTK/tripal/sites/all/modules/tripal/tripal_chado/includes/tripal_chado.fields.inc).
Drush command terminated abnormally due to an unrecoverable error.
```

i actually suspect this was due to the changes just made in https://github.com/tripal/tripal/pull/574 so im going to ignore this for now.

I suspect that the array_flip error warning is also unrelated because i get it for all content types, not just this one.

**Comment by bradfordcondon** [comment]
merged.  for additional feature requests please see #583 or create new issues.  Thanks for reviewing @almasaeed2010 @spficklin
