### ISSUE TITLE
Drupal version 7.56 or 8 for Tripal v3?

### ISSUE THREAD

**Issue by mdhar1980** [tripal/tripal#292]
### System information

* Tripal Version: v3
* Drupal Version: ?

### Issue description
Hello. For Tripal v3, is it still recommended to use Drupal 7.56, as in the tutorial, or should the latest, Drupal v 8, be used? Is Tripal v3 compatible with that version of Drupal?

Thank you

**Comment by bradfordcondon** [comment]
Hi,

Yes, Tripal 3 is designed to work with Drupal 7.  Drupal 8 support is still a ways down the road.

**Comment by mdhar1980** [comment]
Thanks!

**Comment by bradfordcondon** [comment]
Sounds like your question is answered: I'm going to go ahead and close the issue.
