### ISSUE TITLE
Tripal Collections Unable to Create Files Due to Permissions

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#293]
### System information

* Tripal Version: 3 (7.x-3.x)
* Drupal Version: 7.54
* PostgreSQL Version: 9.6
* PHP Version: 7.1

### Issue description

Creating a collection creates the correct folder for each user but fails to detect whether its writable or not. 

The error from the job log looks like this:
```
{"status":"failed","message":"Could not access the directory on the server for storing this file.","file_id":""}Job execution failed: Cannout open collection file:
```

Unfortunately a file name is not provided in the log.

The code block that fails:
```php
$user_dir = 'public://tripal/users/' . $user->uid;
    if (!file_prepare_directory($user_dir, FILE_CREATE_DIRECTORY)) {
      $message = 'Could not access the directory on the server for storing this file.';
     // WORKS WHEN WE COMMENT THIS OUT 
      watchdog('tripal', $message, array(), WATCHDOG_ERROR);
      drupal_json_output(array(
        'status'  => 'failed',
        'message' => $message,
        'file_id' => '',
      ));
      return;
     // UNTIL HERE
    }
```

However, the code functions properly if we ignore the returned value from `file_prepare_directory.` Also, adding `is_dir($user_dir )` and `is_writable($user_dir )` checks in the code both return `true`. So `file_prepare_directory` is failing to detect the correct permissions. Any idea why this is happening?

Thanks!

**Comment by spficklin** [comment]
This is curious.... I'll take a look at it..

**Comment by bradfordcondon** [comment]
hi all @spficklin any thoguhts/updates on this?

**Comment by spficklin** [comment]
I just added a pull request to fix this.  If you can test that would be great.

**Comment by bradfordcondon** [comment]
@almasaeed2010 where were we experiencing this, on HWG?

**Comment by almasaeed2010** [comment]
All my tripal sites (mac os and centos). I test the PR

**Comment by bradfordcondon** [comment]
thanks @spficklin .  merged, closing.
