### ISSUE TITLE
Tripal Jobs warning messages

### ISSUE THREAD

**Issue by shawnawsu** [tripal/tripal#296]
When running tripal jobs the following error message appears: 
`2018-02-21 10:44:47: Calling: tripal_tripal_cron_notification()`
`Invalid argument supplied for foreach() TripalJob.inc:257            [warning]`

When running tripal jobs with the galaxy module installed this additional message appears:
`[warning]`
`2018-02-21 10:44:47: Calling: tripal_galaxy_check_status()`

**Comment by laceysanderson** [comment]
I no longer see this and suspect it has been fixed. Can you duplicate it @shawnawsu ?

**Comment by shawnawsu** [comment]
Nope, this appears to be fixed.
