### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#298]
Travis CI testing will involve a few things:

* Script to install a tripal 3 site from nothing
* Script to upgrade a Tripal 2 site to Tripal 3
* PHPUnit Testing

We agreed that the first stage will be simply tripal installation and upgrade testing.
A first CI setup will do minimal Unit testing.
After that is set up, contributors can create (or port over from the tripal_test module) Unit tests to run on CI.

**Comment by isumoc** [comment]
I put some working travis configs here:
https://github.com/isumoc/drupal_tripal_travis_setup

**Comment by bradfordcondon** [comment]
Thank you for your configs @isumoc , made my life easier for the tripal 2 to tripal 3 upgrade.

We went with docker containers instead.  I think there's the desire to launch docker containers iwth actual data in Chado for the unit testing which will be neat.  We lose out on matrix builds this way which is a shame though.

**Comment by bradfordcondon** [comment]
Some thoughts for discussion while leaving this issue open:

* Should we migrate the upgrade/install process out of dockers and into Travis, enabling matrix builds of multiple PHP/Postgres versions?
* Is the implementation of PHPUnit clear?
* Other thoughts/suggestions?

**Comment by bradfordcondon** [comment]
We've enabled matrix builds with #362 .  We've written a[ tripal test suite](https://github.com/statonlab/TripalTestSuite) to make PHPUnit implementation way easier, and i've written a full guide on how Tripal is using it ( will go on tripal.info soon).  I'm calling this issue done for now.
