### ISSUE TITLE
Cvalue support for the property linker field

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#299]
### Background

* Tripal Version: 3

Cvalue columns are coming to chado prop tables.  You can use cvterms instead of raw text in the v alue column to describe your property values now!  This means that the **value** column can be **superceded** by the cvalue_id column.

The prop linker field will need some recoding to reflect this.   I've gotten started with that [here](https://github.com/statonlab/tripal/tree/7.x-3.x_add_cvalue_prop_support)

### Discussion
These are my thoughts but if you envision something different, chime in.

* What should behavior be for **value** vs **cvalue**? 
  - my suggestion is that the both the field, and the widget, automatically set the **value** to be equal to the cvalue's `cvterm->name`.  We don't want the value differing from the cvalue.  If a cvterm cant express the value, then cvalue should be null.
* How should the new field **widget** look?  A radio box to select if you want free text or a cvterm?
* How should hte formatter support cvalue?  We can make them link-out to the cvterm via that cv's dbxref.

### Help
The cvterm lookup code is easy to paste in.  The issue is the AJAX callbacks.  Specifically, each field needs to have a callback for just its widget.  It needs to rebuild just its own portion of the form.  I think this means having dynamic wrappers and dynamic callbacks, but drupal doesnt support anonymous functions.  

My thinking was you'd have your wrapper be, say, `$field_name . -cvalue_wrapper`, and your function be `$field_name_cvalue_callback`.   However we cant dynamically create callbacks for each field_name.  Therefore Abdullah has suggested the solution is to make a custom drupal callback, and handle the callback in custom JS instead of using Drupal's AJAX interface.

```

    $widget['cvalue_term'] = array(
      '#type' => 'fieldset',
      '#title' =>  'Value Controlled Vocabulary Term',
      '#prefix' => '<div id = "chado-' . $field_table . $type_id . '__cvalue_term">',
      '#suffix' => '</div>',
    );

    $widget['cvalue_term']['cvalue_text'] = [
      '#type' => 'textfield',
      '#title' => 'Set property value using a cv term.',
      '#autocomplete_path' => "admin/tripal/storage/chado/auto_name/cvterm/",
    ];

    $widget['cvalue_term']['select_button'] = [
      '#type' => 'button',
      '#value' => t('Lookup Term'),
      '#name' => 'select_cvterm',
      '#ajax' => [
        'callback' => "cvalue_ajax_callback",
        'wrapper' => "chado-' . $field_table .'_' . $type_id . '__cvalue_term",
        'effect' => 'fade',
        'method' => 'replace'
      ],
    ];
//code that goes on to build the cvterm lookup table as it does elsewhere
```

Thoughts?  Is there a simple solution?  Sorry if this problem isn't clearly explained here.

**Comment by laceysanderson** [comment]
I'm closing this as it has been over a year with no movement. Please comment if this is still functionality you need and we'll re-open
