### ISSUE TITLE
Assistance installing Tripal on Bluehost server (CentOS 6)

### ISSUE THREAD

**Issue by btski** [tripal/tripal#304]
The Tripal installation guides correspond to Ubuntu and CentOS 7. Will this limit me from installing Tripal on a server with CentOS 6? I'm currently trying to use Bluehost, which exclusively supports CentOS 6. I'd like to avoid losing support if possible. I speculate that my installation problems are caused by cPanel changes to config files or non-compatible operating system (perhaps the Tripal installation calls depreciated language).

**Comment by bradfordcondon** [comment]
Hi,

so you are trying to install, and getting error messages?  Can you share them?

At what steps?

**Comment by spficklin** [comment]
I think the CentOS installation on the User's Guide will get you along fairly well. I'm not 100% sure of the differences between vs 6 and v 7.  But if you want to post to this issue any differences oddities you find we can create a document on our User's Guide for CentOS 6, and we can certainly try to help out if you get stuck on something.

**Comment by bradfordcondon** [comment]
@spficklin if its a question of "will it build" we need only change the starting point of our docker from centos7 to centos6 and see if we the container builds.  I'll try that now.


edit: rebuilding fails from centos6 not surprisingly, becaus we get all our dependencies for centOS6. `remi-release-7.rpm`  I don't have time tonight to set up teh build properly tonight perhaps tomorrow...

**Comment by btski** [comment]
Thanks for the quick replies @bradfordcondon and @spficklin. From what I can tell, my dependencies are adequate. Looks like my SSH privileges have changed (again). Have to reset them so I might be a little slow.

Errors are the following:
```
exception 'Exception' with message '<ul><li>To start over, you must empty your existing database.</li><li>To install to a        [error]
different database, edit the appropriate <em>settings.php</em> file in the <em>sites</em> folder.</li><li>To upgrade an existing
installation, proceed to the <a href="http://default/update.php">update script</a>.</li><li>View your <a
href="http://default">existing site</a>.</li></ul>' in /var/www/html/includes/install.core.inc:301

Enabling modules.
Command pm-enable needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment[error]
to run this command.
The drush command 'en ctools date devel ds link entity libraries redirect token uuid jquery_update views webform field_group     [error]
field_group_table field_formatter_class field_formatter_settings views_ui' could not be executed.

Drush command terminated abnormally due to an unrecoverable error.                                                               [error]
Error: Call to undefined function module_load_include() in /root/drush7/vendor/drush/drush/commands/core/core.drush.inc(1122) :
eval()'d code, line 1
The external command could not be executed due to an application error.                                                          [error]
Drush command terminated abnormally due to an unrecoverable error.                                                               [error]
Error: Call to undefined function module_load_include() in /root/drush7/vendor/drush/drush/commands/core/core.drush.inc(1122) :
eval()'d code, line 1
The external command could not be executed due to an application error.                                                          [error]

Now preparing the site by creating content types.
Drush command terminated abnormally due to an unrecoverable error.                                                               [error]
Error: Call to undefined function module_load_include() in /root/drush7/vendor/drush/drush/commands/core/core.drush.inc(1122) :
eval()'d code, line 1
The external command could not be executed due to an application error.                                                          [error]
Drush command terminated abnormally due to an unrecoverable error.                                                               [error]
Error: Call to undefined function module_load_include() in /root/drush7/vendor/drush/drush/commands/core/core.drush.inc(1122) :
eval()'d code, line 1
The external command could not be executed due to an application error.                                                          [error]

Adding permissions for the administrator to view, edit, create, and delete all the newly created content types.
Drush command terminated abnormally due to an unrecoverable error.                                                               [error]
Error: Call to undefined function pg_pconnect() in /var/www/html/tripal_install.drush.inc, line 211
root@server.gew.bcq.mybluehost.me [html]# packet_write_wait: Connection to 162.241.232.147

```

Edit1:
PHP version: 5.6.33
postgresql version: 9.5.12
drush: 7.4.0 (note, was having problems with v9.2.1)
Drupal: none prior to installation (should be installed during Tripal setup?)

Edit2:
I've been having problems troubleshooting errors due to oddities in the server itself. For example, there was no sudo group. Any calls to sudo would fail (triggering an uninformative error prompt) even when on root user (which has no unique user privileges). The only solution I could find was to designate a environmental path for sudo itself (along the format of sudo env "PATH=$PATH" drush --include=. tripal-generic-install). With the server being quirky, the cPanel being obtrusive, and Tripals behavior on CentOS 6 unknown (at least to me), I wasn't sure how best to proceed.

**Comment by btski** [comment]
PHP version: 5.6.33
postgresql version: 9.5.12
drush: 7.4.0 (note, was having problems with v9.2.1)
Drupal: none prior to installation (should be installed during Tripal setup?)

**Comment by bradfordcondon** [comment]
>Drupal: none prior to installation (should be installed during Tripal setup?)

Drupal [must be installed prior to set up ](http://tripal.info/tutorials/v3.x/installation/drupal), there's a guide for it on tripal.info. 


The Tripal 3 install requires a functional Drupal environment.  Which guide are you following, the quick install or manual step by step?  I think either way you need Drupal installed and set up first.

**Comment by btski** [comment]
I've been having problems troubleshooting errors due to oddities in the server itself. For example, there was no sudo group. Any calls to sudo would fail (triggering an uninformative error prompt) even when on root user (which has no unique user privileges). The only solution I could find was to designate a environmental path for sudo itself (along the format of sudo env "PATH=$PATH" drush --include=. tripal-generic-install). With the server being quirky, the cPanel being obtrusive, and Tripals behavior on CentOS 6 unknown (at least to me), I wasn't sure how best to proceed.

**Comment by btski** [comment]
Pay no attention to the accidental closure. 

I've tried both. In my previous installation of Tripal on an AWS ubuntu server I don't recall manually installing Drupal (it seems to be included during the rapid installation). When attempting to install Tripal step-by-step, I managed to make it to the web-based steps. I've currently got WordPress installed as a pageholder for the site (http://swinepathogendb.org), which might be overriding Drupal (unable to access http://localhost/install.php equivalent).

**Comment by spficklin** [comment]
@btski, our Tripal demo site runs on Bluehost.  http://demo.tripal.info/3.x/

You're right, bluehost gives you a chroot'ed environment and you do not have sudo access. You are at the mercy of the tools that bluehost provides.  So, you won't be able to follow the tutorial as it is currently written.  Fortunately, bluehost provides everything you need, as evidenced by our demo site.  

Have you been through the Tripal install tutorial on a VM or docker image or some other system where you can go through it step-by-step?  It may be better to go that way first, get a feel for everything you need to do and then go back to Bluehost and figure out how you can get done what needs to be done using their CPanel and command-line access.

We don't have the step-by-step instructions for bluehost unfortunately.

**Comment by mdondrup** [comment]
Hi,
we had our site running under CentOS 6 for while and have just recently updated to 7.

One of the major concerns with CentOS 6 is that its stock versions of php (5.3.3) and 
postgres (8.4 ?) were rather old. So you might want to install them from the EPEL 
or another more up to date repository, which as I understand you already did. But then,
even using these archaic ones, for us it worked fine most of the time using Tripal 7.x-2.x. 
We won’t be able to update to Tripal 3 mostly because of postgres 8 if I understand the documentation 
correctly. To provide these old versions with back-ported bug fixes
is part of the “enterprise” philosophy behind CentOS, but there are ways around it.
Another argument against using CentOS 6 is that there exists no viable upgrade path to CentOS 7 except
installing from scratch.

Michael

**Comment by btski** [comment]
Thanks for all the advice and information. I think my plan going forward will be:
1.) uninstall WordPress and see if I can make more progress on the web-based steps for manual Tripal installation
2.) create CentOS 6 AWS instances to practice rapid/manual installations and draw comparisons to bluehost
3.) switch to a different operating system on bluehost (Ubuntu or CentOS 7). I don't believe either is supported by bluehost, but this could also mean that cPanels are not included features (which complicate installation by adding additional config files/directories). Ideally, switching operating systems will result in an empty/clean server so I won't have to worry about required dependencies having odd configurations.

Bluehost is intended to be a short-term hosting solution. We'll eventually switch to a local server when it is made available. Because of this, we're less concerned about using dated tools/programs/operating systems.

Edit1:
I believe you can get sudo permissions on a bluehost virtual private server (VPS). I think the sudo path is strange though, so you have to either edit the path file (which wasn't recommended) or designate the path when run as **sudo env "PATH=$PATH"**.

Edit2:
Bluehost provides custom php and httpd/apache which cannot be uninstalled. The cpanel connection inhibits Tripal installation. I might try to remove all cpanel directories/files, but I think my best bet will be to switch OS. I've been told by bluehost support it's possible but unsupported (and discouraged). Hopefully under a new OS the cpanel will not be an included default feature. Might also just change web host provider. Currently attempting to communicate with NCGAS.

Edit3: Moving to AWS Lightsail for the time being.
