### ISSUE TITLE
Sudden issue with contact record not being created + error

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#305]
HI guys and @spficklin , suddenly I have come across a problem regarding creating a contact. Cannot track this back to any change made. When creating the contact by entering data and clicking submit, I get the following error:
```
Could not save the entity: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "" LINE 1: ...chado_bio_data_8 (entity_id, record_id) VALUES ('65297', '') ^
Cannot save entity
```
After some debugging, I have traced it back to the file:
sites/all/modules/tripal/tripal_chado/includes/tripal_chado.field_storage.inc
```
Line:
$base_record_id = tripal_chado_field_storage_write_table($base_table, $values, $base_table);
```

**$base_record_id is blank**. After some further debugging, it seems
$values is empty for $base_table which shows up as 'contact'

Further backtracking shows that the following array does not contain any data which I think might be causing the problem. Cannot understand why this is happening.
$field_vals[$base_table] returns empty

So in essence $field_vals['contact'] returns empty which I think is why it's not able to create a $base_record_id

Any assistance would be appreciated? This was working before and all of a sudden, it stopped, couldn't trace it back to a custom module or anything like that. Currently contact submission is crippled for me :(

Please help?
Thanks

**Comment by bradfordcondon** [comment]
You're creating contacts directly (ie from add tripal content -> contact) right? Or is this a field widget of some sort?  If thats the case are you able to create contacts directly?

I'm able to create contacts in this manner on current master.  But your error looks to me like a misconfigured field - possibly the column id for contact (contact_id) wasn't specified?

**Comment by risharde** [comment]
Hey @bradfordcondon thanks for your contribution, yes I am trying to create directly from add tripal content -> contact
I thought so as well but no field seems to be misconfigured since no changes were made to the fields since prior to working
A bit stumped on what could have done this

**Comment by spficklin** [comment]
Do you have a custom field that works with records in the contact table?

**Comment by risharde** [comment]
Hey @spficklin , no custom field that works with records in the contact table. It's like I just woke up today to test it and it just spurts the error. It seems as though because it cannot get the $values[] array populated, nothing gets created in the contact table and so no record id is returned for additional inserts

**Comment by spficklin** [comment]
What is bio_data_8 on your site... is it the contact content type?

**Comment by risharde** [comment]
@spficklin Correct!

**Comment by spficklin** [comment]
If you look in your recent logs under the Reports menu do you see any other interesting/related messages?

**Comment by risharde** [comment]
@spficklin Unfortunately not, just the SQL error :(

**Comment by risharde** [comment]
@spficklin 

`
TYPE | tripal -- | -- Friday, March 9, 2018 - 06:35 risharde
/Drupal/bio_data/add/8
PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "" LINE 1: ...chado_bio_data_8 (entity_id, record_id) VALUES ('65300', '') ^: INSERT INTO chado_bio_data_8 (entity_id, record_id) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1); Array ( ) in tripal_chado_field_storage_write() (line 73 of /var/www/Drupal/sites/all/modules/tripal/tripal_chado/includes/tripal_chado.field_storage.inc).
error
`

**Comment by bradfordcondon** [comment]
maybe a weak suggestion but have you tried deleting your contact bundle and re-creating it?

Doing so should not delete your contacts although you may have to republish them afterwards.

**Comment by spficklin** [comment]
What fields do you have attached to your Contact content type?

**Comment by shawnawsu** [comment]
#236

**Comment by shawnawsu** [comment]
Related: #236

**Comment by risharde** [comment]
@spficklin A few fields well, some are custom properties that worked fine and others are some local fields as well like ORCID which stores basic text data etc which all worked fine up to about 2 -3 days ago. Either way, should those fields affect base table array which is suppose to contain fields? Again, it seems to stem there, without any fields in that array, it seems it cannot generate an initial contact record to be inserted. This is where I am stuck. I'm hoping it's something small I may have overlooked or else I might have to do some nasty hacky code which I want to avoid altogether and remain true to the Tripal project 

@bradfordcondon You mean deleting the entire tripal content type?

@shawnawsu  Not sure if it's related in the sense that I believe we go around the issue and it was able to save. I think I recreated the field to resolve this issue.

**Comment by bradfordcondon** [comment]
Yeah I meant the contact bundle type.  A better idea might be to disable all of your custom fields and try to create a contact.  If that works, re-enable custom fields one by one and test contact creation.

**Comment by spficklin** [comment]
I agree with @bradfordcondon.  You can't really disable the field though, you'll have to delete them from the Contact content type.  You can easily add them back later and it doesn't affect the data in your database.

**Comment by risharde** [comment]
Hey guys @spficklin @bradfordcondon @shawnawsu , okay so I have news on this bug, both good and bad...
The good news is that I found where the issue is, the bad news is that it seems to be a bug of some sort.
Time to explain...
After an entire weekend of guessing, trying and having adrenaline rushes lol, I discovered that under the manage fields section of the Tripal Content Type -> Contact
Name was one of the fields detected when using the Check for new fields link which worked fine
With our project, we thought that Name was not descriptive enough so I decided to change the caption for the field to Last Name, First Name
Doing this seems to cause the problem.
I discovered that after changing the caption, the node displaying the content was unable to pull data from the field.
The easiest (but quite inconveniently) to fix is check for new fields which adds back all fields including unwanted fields which have to be deleted accordingly.

Can you guys have a look at the code and perhaps track back why captions does this?

**Comment by bradfordcondon** [comment]
Hi, by caption, do you mean the field label?

I was able to recreate your issue I think by changing the label for name to First name, last name.  (see attached screenshot, which is me submitting a new contact with the modified field).


<img width="724" alt="screen shot 2018-03-12 at 8 16 50 pm" src="https://user-images.githubusercontent.com/7063154/37315877-516a0854-2632-11e8-9582-1a74e6ba2bee.png">


Interestingly changing the label back to name from first name, last name is not enough to resolve the issue.

**Comment by risharde** [comment]
Correct @bradfordcondon Label, sorry about the different terminology

**Comment by spficklin** [comment]
That was really helpful @risharde .  I was able to identify where the problem was coming from and I applied a fix. It's currently in pull request #313 waiting for another core developer to review it.

**Comment by bradfordcondon** [comment]
This PR has been merged.  @risharde please let us know if the isn't wasnt resolved and we'll reopen.
