### ISSUE TITLE
Data Search vs Tripal Search Block

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#309]
There are two search blocks provided by Tripal one named Data Search and the other named Tripal Search Block.  The first provides searching using default views and I think the other is for site-wide searching of Tripal content.  We need better names for these to help the user distinguish them better.

**Comment by spficklin** [comment]
The Tripal Search Block is a legacy item and should stay as is.  All 7.x-3.x searches are in their own new block.  This isn't really a problem I must not have remembered the "Tripal Search Block" was legacy so I'm closing.

**Comment by bradfordcondon** [comment]
we opened the issue because it was confusing which was which (compare for example to Tripal Content vs regular content).  But if the Tripal Search BLock name can't be changed for legacy reasons then so be it.
