### ISSUE TITLE
Tripal style guide

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#310]
I would appreciate some sort of standard Tripal codebase style guide.  I use PHPstorm which lets me set a style and auto-format the code to it.

The XML hosted [here](https://raw.githubusercontent.com/Erikdekamps/phpstorm-drupal/master/Phpstorm.xml)  might be on the money.  Applying the formatter to random lines of code mostly finds minor formatting errors in the code itself (extra spaces etc).

This isnt just anal retentiveness (honest): my PRs that touch core files are full of minor formatting changes from running my linter.... with the linked style, I'm changing 5-10 lines of code per file so I'd like to establish a "correct" format.

**Comment by shawnawsu** [comment]
Drupal has extensive coding standards: https://www.drupal.org/docs/develop/standards/coding-standards

Given Tripal is a contributed module it's best practice to stay within the guidelines set out in their documentation.

I use Visual Studio Code setup using this as a guideline: https://www.drupal.org/docs/develop/development-tools/configuring-visual-studio-code

This page lists most of the popular IDEs with links to suggested configurations: https://www.drupal.org/docs/develop/development-tools/configuring-visual-studio-code

**Comment by bradfordcondon** [comment]
Thanks Shawna.  Looking over the XML I linked, that reflects the style guidelines (which if you are a hack like me you don't want to read and conform to, you want to import and not worry about it).   The IDE guide you link has some configuration files for some editors but not others .

I know the coding standards link is in the developer guide.  I'll add a link to specific style import profiles as people want them.

**Comment by bradfordcondon** [comment]
Summarizing slack discussion:

The new Drupal coding standard conventions use `[]` instead of `array()`.

[Drupal coding standards also discourage pushing changes that are for style only.] <--- edit, contradictory with below... 

edit: after reading the [coding standards](https://www.drupal.org/docs/develop/standards/coding-standards) I have pulled out the two relevant sections:

>Note: Do not squeeze coding standards updates/clean-ups into otherwise unrelated patches. Only touch code lines that are actually relevant. To update existing code for the current standards, always create separate and dedicated issues and patches.



>Please note, short array syntax is unsupported in versions of PHP prior to 5.4. This means that Drupal 7 core and Drupal 7 contributed projects without an explicit PHP 5.4+ requirement must use long array syntax.


Therefore:

* Only the tripal 7.x-3.x branch and future branches should change from `array()` to `[]`
* We should make a single dedicated PR to update our coding standards rather than include in other PRs.

**Comment by bradfordcondon** [comment]
trpial style will update as a 3.1 ie after the stable release.

**Comment by spficklin** [comment]
Code changes are updated.   Do we have the expected code style documented anywhere?

**Comment by bradfordcondon** [comment]
we now follow the up-to-date Drupal style standards.  https://www.drupal.org/docs/develop/standards/coding-standards 
we should link to them here; https://tripal.readthedocs.io/en/latest/dev_guide/contributing.html

we might have more to say about style in the future if we employ code sniffing... for now doesnt have to be much.
