### ISSUE TITLE
Unit Test Protocol

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#311]
I've setup this issue for anyone who wants to discuss how we should organize our unit testing protocols.  In a discussion on pull request #307 @bradfordcondon stated:

> Regarding data for tests. I had originally envisioned using dockers pre-populated with data as an "official test docker". However, I've come to believe that best practice is for each test suite is to insert and remove test data in the buildUp/tearDown (which gets run at the start/end of each test in the class). Because you don't know what order tests will run in, relying on data inserted by a different class isn't great. Additionally, if a FASTA loader didn't remove features the first run through, then the test would probably fail the second run through because the features were already in the database. This wouldn't happen on Travis, but it would happen for local testing.

In response.... I think we may want a combination of both.   I think it is possible to have tests run in a specific order (https://phpunit.de/manual/current/en/organizing-tests.html).  So, perhaps we could organize set of "states" where tests can self-organize themselves, for example we could have several test states such as:

- After Base Install
- Loaded Genomics Test Set
- Loaded Breeding Test Set
- Loaded Genetics Test

**Comment by bradfordcondon** [comment]
Organizing tests is more for subtesting to save you  from running the WHOLE SUITE during TDD.  You are working on a certain feature so you just want to run tests in that group.  I also create a group "failing" so you can just run those failing tests.  Then your CI runs ALL tests when you push (or you just run it before pushing). 

creating and cleaning up database state for tests is called Fixtures in PHPunit 
  https://phpunit.de/manual/current/en/fixtures.html 

Tests and classes can share fixtures.  I think its a much better idea to create fixtures that clean up after themselves and get imported by each test class, rather than trying to orchestrate running test classes in a certain order (and the unintended consequences of changing the database state after a certain test runs!).  

Edit: note phpunit strongly discourages you from sharing fixtures between tests.

I think that what I really mean is you create very simple API calls that insert, and remove, a database object.  And your classes plug into those methods.  Look at a test from my curator module below:  I insert, and remove, objects from the db before/after each test has been run in the class.  I store the inserted cvterm for reference so its easy to access in the classes' tests.  It's more work this way but it keeps your tests seperate which, ultimately, is a major design goal of unit testing.


I've got a lot more to learn on this topic but thats my 💭 

```


  public $cvterm_test;

  public $cvterm_existing;

  public $property;


  protected function setUp() {

    $cvterm = tripal_insert_cvterm(
      [
        'name' => 'Curator Test',
        'definition' => 'A test CVterm.  Should be deleted in test.',
        'cv_name' => 'tripal',
        'is_relationship' => 0,
        'db_name' => 'tripal',
      ]
    );


    $this->cvterm_test = $cvterm;

    $property = new Chado_property();


    $query = [
      'name' => 'comment',
      'cv_id' => ['name' => 'cvterm_property_type'],
    ];

    $cvprop_term = tripal_get_cvterm($query);
    $this->cvterm_existing = $cvprop_term;
    $property->set_cvtermprop_search($cvprop_term->cvterm_id);
    $this->property = $property;


    //create a biomaterial that will be not have a cvalue

    //insert a fake biomaterial
    $biomaterial_id = tripal_biomaterial_create_biomaterial("Tripal Curator blank cvalue", NULL, NULL, NULL, NULL, NULL);

    $query = db_insert('chado.biomaterialprop')
      ->fields([
        'biomaterial_id' => $biomaterial_id,
        "type_id" => $cvterm->cvterm_id,
        "value" => "No cvalue!",
        'cvalue_id' => NULL,
      ]);
    $result = $query->execute();
  }
```

**Comment by spficklin** [comment]
Okay, planning tests on this scale is new for me as well.... So would it make sense then to create some base classes that in their setup set the database a certain way.  So if we need a whole genome loaded we could have a whole genome base class that doesn't have any tests itself but just provides setup.  We can then extend that class for any actual testing classes that need that setup?  It would allow us to re-use a setup without any dependencies between test classes, and without repeating the same setup code over and over again for every test.

**Comment by bradfordcondon** [comment]
Abdullah and I have two projects that I think we can use to great effect for this problem:  
* https://github.com/statonlab/tripal_dev_mini_dataset
* https://github.com/statonlab/TripalTestSuite

The test suite provides a test class with some built in cool stuff, such as db connectivity, transactions, automatic PHPUnit and Travis CI testing setup.
The seed dataset provides a single, standardized dataset that is truncated.

What I'm thinking is can we use these two tools to distribute, or at least facilitate, the creation of seeders like you suggest:

>So if we need a whole genome loaded we could have a whole genome base class that doesn't have any tests itself but just provides setup. We can then extend that class for any actual testing classes that need that setup? 

Except we would provide the genome as a seeder, so it wouldn't be doing test things (because it isnt a test)

We're still discussing and we can't volunteer to write all the seeders ourselves.  But I wanted to throw some thoughts out there.

**Comment by almasaeed2010** [comment]
I am referencing this here in case it matters to anyone

[TripalTestSuite](https://github.com/statonlab/TripalTestSuite) now supports database seeders which allows you to seclude your data providers from your tests. They can also be set to run automatically which would put the data in your DB before the tests start and then roll them back once the tests are done. This makes the seeders shareable, reusable and automated.

Please see the [documentation](https://github.com/statonlab/TripalTestSuite) for more info.

Thanks!

**Comment by bradfordcondon** [comment]
Hi all,

as I work on #357 I wanted post in the discussion thread for opinions on test folder structure.

For starters, re: above discussion: tripal test suite is going to make it very easy for each test file to test a single PHP class or file, and to easily load what you need into the db using factories.  You can share factories between the test files.  So I would **strongly** encourage people to write independent tests.

As for structuring tests:

I've been discussing with @almasaeed2010 and we agree that the structure should be `tests/[submodule]/`.  From there, tests can either be grouped by category (Fields, jobs, Commands, API) or mirroring the directory structure.   There are advantages/disadvantages to each so i'd love some community feedback @shawnawsu @laceysanderson @spficklin 

### Category
Pros:

* Reduces number of folders etc
* could encourage us to organize our code in more functional, meaningful ways

Cons: 

* Developers have to agree on design patterns for organizing tests
* New devs might not know where to locate correct test

### directory structure

Pros:

* No debate about what goes where
* Some files not fit neat dev categories, with API's spanning multiple categories

Cons:

* Paths can be tangled, particularly when you get to testing, say, fields

**Comment by laceysanderson** [comment]
It's a hard call. I prefer the idea of categories but I worry about the time required to come to a consensus and then the possibility of changing our minds and moving around tests :eyes_crossed:. With directory structure you can easily get started.

What if we go for a hybrid? We could follow `tests/[submodule]/[category]` where category often matches directory structure. For example, for `module=tripal` the categories would include `api, theme, views, drush, fields, entities, admin`. The first three are based on directory structure and the last ones flatten the includes directory. Then can we keep anything that doesn't fit those directories in `tests/[submodule]`?

**Comment by almasaeed2010** [comment]
I like the hybrid structure idea! Takes the confusion away and keeps the folders flattened and not deeply nested which is what we are trying to achieve with the categories idea. 👍

**Comment by bradfordcondon** [comment]
I like this as well.  It also encourages better developer patterns so that your subfolders follow expected conventions.
When I make the PR I will write up some document for "testing in tripal core" that will include this.

**Comment by bradfordcondon** [comment]
I'm writing up a guide for this (see below).

We'll have edge cases.  in the example i picked `tripal/api/` has for example a fields, and entities api.  would those go in the entities category or the API category?


##### Submodules

* tripal
* tripal_bulk_loader
* tripal_chado
* tripal_chado_views
* tripal_daemon
* tripal_ds
* tripal_ws

##### Categories
* API
* theme
* views
* drush
* fields
* entities
* admin

So for example, tests for the file `tripal/api/tripal.jobs.api.inc` should go in `tests/tripal/api/tripal.jobs.api.Test.php`. tests that don't fit in any of these categories should be placed in `tests/[submodule]/`.

**Comment by almasaeed2010** [comment]
I think the class name has to match the file name. Therefore `tripal.jobs.api.Test.php` might not work. It has to become `TripalJobsApiTest.php` or `tripal_jobs_api_Test.php` but I prefer the first one since `Test` has to be capitalized.

Thanks!

**Comment by bradfordcondon** [comment]
Some confusion because of the name of our existing pilot test.

Tests for `/tripal/api/tripal.jobs.api.inc` go in `tests/tripal/api/TripalJobsApiTest.php` and define class `TripalJobsApiTest`.

**Comment by bradfordcondon** [comment]
here is a [first draft of testing guidelines](https://www.bradfordcondon.com/2018/05/02/tripal_testing_guidelines/) which i will propose to add to tripal.info when the corresponding testing PR is accepted.  Putting here now for comments.

**Comment by bradfordcondon** [comment]
Discussion on this seems settled.  If theres no feedback to the testing guidelines, I'll add it to tripal.info and close the issue.

**Comment by laceysanderson** [comment]
Sorry, this fell off my list. I just gave it a read through and it's awesome 👍

**Comment by laceysanderson** [comment]
Might it be good to include this as a markdown file in the tests directory? We could link to it on tripal.info so we don't have to update in two places. Thoughts?

**Comment by bradfordcondon** [comment]
oooh putting it as a REAME.md in tests might be the best solution since then its under version control.  fantastic idea.

**Comment by bradfordcondon** [comment]
For the sake of argument, the other place it would make sense to put it is on the github wiki, where it would also be under version control (and could be more easily broken up into sections etc).
I'm happy with README.md for now though.

**Comment by laceysanderson** [comment]
I like it in the repo since that's where the tests will be being added. This way, no one can say they put tests in the wrong place because they didn't find documentation about where it should go ;-)

**Comment by bradfordcondon** [comment]
i started discussing test documenting with @spficklin .  we shoudl get some groundfloor requirements/expectations.



```

  /**
   * Check that the thing does the thing.
   * @throws \Exception
   * @ticket 322
   */
  public function test_ImporterRuns() {
```

* tests start with test
* tests addressing an issue CAN have a ticket tag.  This lets you run a bunch of tests for an issue in isolation.  it also lets people easily refer back to the issue spawning the test.
* tests should have a descriptive name.  Remember the failed test shows the test class name, and the test name, and the failure message.  the above test might fail  like below.
```

1) Tests\SSRLoaderTest::test_ImporterRuns
Failed asserting that an array is not empty.

/Users/chet/UTK/tripal/sites/all/modules/custom/tripal_ssr/tests/SSRLoaderTest.php:32
```

Any other documentation guidelines we want to follow?  Check the manual for available test annotations.  https://phpunit.de/manual/6.5/en/appendixes.annotations.html
