### ISSUE TITLE
New tripal v3 site with chado 1.11 or 2 install fails

### ISSUE THREAD

**Issue by shawnawsu** [tripal/tripal#315]
### System information
* Tripal Version: 7.x-3.x
* Drupal Version: 7.56
* PostgreSQL Version: 9.5.12
* PHP Version: 7.0.28

### Issue description
When standing up a new tripal v3 site choosing chado version 1.11 or 1.2 results in the following error: 
```
PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "chado.tripal_obo_temp" does not exist
LINE 1: DELETE FROM chado.tripal_obo_temp
                    ^ in /var/www/html/tripal15/includes/database/database.inc:2227
```

**Comment by spficklin** [comment]
I cannot duplicate this. I have installed a brand new Tv3 site and installed both Chado v1.11 and Chado v1.2 with full success.  I think this bug must have been fixed by another commit.  I'm marking closed but if it happens again we can reopen.
