### ISSUE TITLE
FASTA loader adds text to the sequence field

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#317]
### System information

* Tripal Version: current master 7.x-3.x
* Drupal Version: 7.56
* PostgreSQL Version: 9.6.1
* PHP Version: 7.1.7

### Issue description
Using the FASTA importer...
Sequence to try: https://raw.githubusercontent.com/statonlab/tripal_dev_mini_dataset/master/sequences/fExcelsior_scaffolds.fasta

uploading a fasta file starting with 

```
>Contig0
TATTATCTTTTTTCTTTATATATACTTGACCTTAATGTAATATCTGATCAACATTTTTTTCTTCTGCTTTTCCATTTTTCAATTCTCTATCAATTGAGGTATTCATCATTTATCAATGGCAGCATCACTACTATTTTTGCATATTTCCTTCAAGTGTTAGTTTCAACTGGTTCTCGTTGATTAATCTTTTCATGGTTGCTCATAGGAAATGCTAAACCTGGTAA
... etc
```

results in the below sequence in the db:

```
656.84K (204.80K loaded)
TATTATCTTTTTTCTTTATATATACTTGACCTTAATGTAATATCTGATCAACATTTTTTTCTTCTGCTTTTCCATTTTTCAATTCTCTATCAATTGAGGTATTCATCATTTATCAATGGCAGCATCACTACTATTTTTGCATATTTCCTTCAAGTGTTAGTTTCAACTGGTTCTCGTTGATTAATCTTTTCATGGTTGCTCATAGGAAATGCTAAACCTGGTAAAGATACTGCAAGTTCAACTTAAAGAAGTCCACGAAAGACTAAGGCAAATCTCTAGAACTATTAGTCAATCATG
...etc
```

The sequence lengths match the text: in the example above, the scaffold size is 656.84k
only se this on features at or around 200kb +

here's the DB pic its happening for the first few (largest) features.

<img width="937" alt="screen shot 2018-03-22 at 4 44 16 pm" src="https://user-images.githubusercontent.com/7063154/37797477-512eb78e-2df0-11e8-840a-c96d882341ae.png">

**Comment by spficklin** [comment]
I have tested this and I cannot duplicate the error. The FASTA loader seems fine for my tests.  Also I cannot find any code in Tripal that creates text that looks like what is inserted into those FASTA records, so it's not clear to me where that could be coming from.

**Comment by bradfordcondon** [comment]
Really?  Could it have something to do with my local memory settings?  

Turns out i get this behavior not just with the local JS file loader, but also supplying a remote path (and presumably a local path as well).

**Comment by bradfordcondon** [comment]
super embarrassing: this text was added by the IDE.  Publishing the entities, the seqeunces are normal: entries are fine in the database.

So sorry.   i am seriously going to stop working sick.
