### ISSUE TITLE
menu settings area for tripal entities?

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#319]
Tripal 3 question:

Previously, one could go to the "menu settings" section of a content type to manage the menu settings.  You could make the content available to be added to menus.    Is it possible to add this for Tripal entities?  It would be nice to allow organisms to appear automatically in a menu list, for example.

Apologies if this is something that is no longer possible going from nodes to entities.

**Comment by laceysanderson** [comment]
@bradfordcondon are you referring to the “menu settings” section on each node edit page? For example, you go to a specific organism page (e.g. spruce), click edit and it was in the vertical tabs near the bottom?

**Comment by bradfordcondon** [comment]
yeah!  For that individual node edit page menu setting option to appear, you have to "make the content type available" for menus, but that option isnt available for tripal bundles

**Comment by laceysanderson** [comment]
I will also need this functionality back :-) although I don't know yet how to make it appear. I imagine this functionality is not node-specific but that making it appear for Tripal Entities is obviously up to us and likely not well documented ;-) Never the less, where there's a will, there's a way.

**Comment by spficklin** [comment]
We do have to implement it on our own because we define the entity.  To add a tab for adding a menu we need to edit the TripalEntituUIController and edit the function tripal_entity_form.   there you will see the fieldset named 'additional_settings' and in there is where we would need to add the code to set the menu for each entity.

**Comment by spficklin** [comment]
Oops... didn't mean to close that.

**Comment by laceysanderson** [comment]
I'm closing this as there has been no movement on this in over a year and our focus has moved to Tripal 4. Please comment if you need this functionality and we will re-open
