### ISSUE TITLE
Tripal Fields with unlimited cardinality are not passing values for fields added through 'add more items' button

### ISSUE THREAD

**Issue by shawnawsu** [tripal/tripal#320]
After significant testing, this is verified as happening across multiple user's installs. 

Currently looking at using default values as a way to force correct value array builds. 

The issue was originally identified in #240 & #249.

This is not a high priority fix because data can still be input it just requires users to save after each input to generate the next available field for input.

**Comment by laceysanderson** [comment]
Assigning myself as a means to add it to my todo list :-)

**Comment by laceysanderson** [comment]
Removing myself as I've made no progress... Is this still an issue @shawnawsu ?

**Comment by shawnawsu** [comment]
Yes, this is still an issue when testing on the 7.x-3.x branch.

**Comment by laceysanderson** [comment]
By the way, I would argue this is a release blocker because it's asking a lot to expect data curators to save between addition of each field. Thoughts @spficklin?

**Comment by bradfordcondon** [comment]
For what its worth, I am able to take an analysis with 0 organisms associated and add 5 in 1 go [using the widget](https://github.com/statonlab/tripal_manage_analyses/blob/master/includes/TripalFields/obi__organism_linker/obi__organism_linker_widget.inc) on my dev site.  Not sure if this is impacting *all* sites or *some* sites, but can confirm that this field is OK for me.

**Comment by laceysanderson** [comment]
Adding the "Address in Tripal 4" tag to make sure everything works perfectly there. No one but me seems concerned with this and I have no time to fix it so I'm also marking it as please contribute.
