### ISSUE TITLE
Tripal Entities API documentation questions

### ISSUE THREAD

**Issue by shawnawsu** [tripal/tripal#323]
- [x] function tripal_entity_permissions --> this is commented out, should it be removed?

- [x] function tripal_insert_entity --> Are we keeping this in? I'm not sure it's finished or what the use case for it is.

- [x] function tripal_update_entity --> This is empty, should this be removed?

Please see the 7.x-3.x-api-docs branch for an updated doc.

**Comment by spficklin** [comment]
Remove the tripal_entity_permission function. If we want to provide entity level permissions we need a full design which is probably why that function is commented out.  

The tripal_insert_entity and tripal_update_entity functions are meant to be used for generic  inserting and updating an entity.    Let's take them out of the Doxygen group but leave the code so we can finish them up later.

**Comment by shawnawsu** [comment]
changes incorporated into 7.x-3.x-api-docs branch
