### ISSUE TITLE
Tripal Fields API documentation questions 

### ISSUE THREAD

**Issue by shawnawsu** [tripal/tripal#324]
- [x] function hook_bundle_fields_info_alter --> I can't find this implemented anywhere in a module_implement nor can I find this being used. Are these in use/required?

- [x] function hook_bundle_instances_info_alter -->  I can't find this implemented anywhere in a module_implement nor can I find this being used. Are these in use/required?

**Comment by laceysanderson** [comment]
I think they are required although I haven’t needed to use them yet. As I understand it, they would allow module developers to alter the way a field registered by another module or core is defined.

**Comment by spficklin** [comment]
I think those are left over from previous iterations of the code and they can go away.   We don't call those hooks anywhere in the code.   If we need them we can put them back in a later version.

**Comment by shawnawsu** [comment]
changes incorporated into 7.x-3.x-api-docs branch
