### ISSUE TITLE
After Tripal v3 rapid install, get "page isn't working...HTTP ERROR 500"

### ISSUE THREAD

**Issue by mdhar1980** [tripal/tripal#325]
### System information

* Tripal Version: v3
* Drupal Version: 7.56
* PostgreSQL Version: 9.5.10
* PHP Version: 7.0.25-0

### Issue description

Hello, and thanks for your attention. I installed Tripal/Drupal using the rapid installation method recommended here (http://tripal.info/tutorials/v3.x/installation/rapid). I then checked the site. It at first said it could not access .htaccess -- I then changed permission on .htaccess in /var/ww/html from 640 to 644. The page then gave the following error:

> This page isn’t working
> 10.230.240.231 is currently unable to handle this request.
> HTTP ERROR 500

I have tried a number of troubleshooting approaches, including opening up permissions on other files in /var/www/html and re-running the installation. I also wrote a dummy index.html ("hello world" basic page) to see if that would load in place, and got the same error. So, I'm not sure if the issue is the .htaccess configuration associated with Tripal, an underlying Apache2 issue, or something else.

Please let me know if you have any recommendations.

Thank you,
Michael

**Comment by bradfordcondon** [comment]
Hi Michael,
if you can't get a dummy `index.html` to show up then the problem is almost certianly with your server setup.  I'm assuming youre following this guide:
http://tripal.info/tutorials/v3.x/installation/server-setup
which OS are you installing under?

**Comment by mdhar1980** [comment]
Hi, Bradford,
Thanks for your response. We have Ubuntu 16.04.2 LTS.

Yes, that's the installation guide use.

Thanks!
--Michael

**Comment by bradfordcondon** [comment]
Sorry for the super slow responses.
According to the guide, apache should give you the default page after:  `   sudo apt-get install apache2` before Tripal or even Drupal enters the scene.


Can you check your server logs at `/var/log/httpd/error_log`  ?  Here's a [general apache 500 error resolution guide](https://www.1and1.com/cloud-community/learn/web-server/server-management/how-to-fix-http-error-code-500-internal-server-error/)


Edit: I should also ask are you running this on a server, or in a virtual machine.

**Comment by almasaeed2010** [comment]
It sounds like the server permissions are not set properly. If the issue persists, I'd recommend setting all folders to 755 and files to 644. Here is a command to do that automatically:
```
# run this from web root (usually /var/www/html)
find . -type d -exec chmod 755 {} \; && find . -type f -exec chmod 644 {} \;
```
That will loop through the entire directory recursively and fix the permissions based on file type (directory vs regular file).

As for `index.html`, if you've put it alongside `.htaccess`, then it was overridden by `index.php` (even if you visited /index.html directly) which explains why you got the same result.

I'd also recommend to check the error log as @bradfordcondon mentioned if the permissions don't fix the issue.

Thanks!

**Comment by mdhar1980** [comment]
Hi, all -- thanks much for these responses, and sorry for my own delay. Will look into these fixes and logs shortly and report back. Thanks!

**Comment by mdhar1980** [comment]
Hi, Bradford -- Just saw your edit: This is a production instance, so it's on a VM. Looking into your other suggestions now. Thanks!

**Comment by mdhar1980** [comment]
(I meant non-production instance)

**Comment by mdhar1980** [comment]
Thanks, Alma -- that command fixed the issue, and the page now loads. Thanks a lot!
