### ISSUE TITLE
Enabling Collections with anything other than data_search/content-type 

### ISSUE THREAD

**Issue by isumoc** [tripal/tripal#327]
Has anyone enabled Data Collections with anything other than the built-in searching ?

This line makes it not happen right now:
https://github.com/tripal/tripal/blob/445cbb56c50fc80f098f82f9f99bee6e73307356/tripal/views_handlers/tripal_views_handler_area_collections.inc#L23

Any notes or pointers would be appreciated.

**Comment by bradfordcondon** [comment]
Our Elasticsearch module creates collections  https://github.com/tripal/tripal_elasticsearch

I've also used collections in an entity converter utility.

What are you trying to do?  It looks like you're trying to use the collections view someplace outside of that view?    Should you instead be using the collections API to write your own new view?  ie in `tripal/api/tripal.collections.api.inc`.

**Comment by spficklin** [comment]
Hi @isumoc once the Pull request #351 is merged in then support for data collections with the Drupal Search API will be supported as well.   It should be merged very soon... just needs one more check.

**Comment by laceysanderson** [comment]
This was merged.
