### ISSUE TITLE
Can entity IDs be filterable for views?

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#328]
Hello,

I'm happy to report I'm making some progress with entity mapping and the cvbrowser.  #297 I don't know that it's still appropriate for core, but, a conversation for another time/place.

I have an array of entity ID's associated with a given node in the CVterm tree.  I want to provide a link for users that they can click that will populate a view with those entities.  (EG, browsing GO I see there are 20 gene entities with a kinase activity, so i click to get a list of them).  Seems to me like the default views under `/data_search` are perfect for this.  

My knowledge of views is not great.  It seems to me like the roadblock I have is that there are no filter handlers for the entity ID.  Trying to enable filtering gives me the below error.

```
Notice: Undefined index: entity_id in views_handler_filter->accept_exposed_input() (line 1279 of /Users/chet/UTK/tripal/sites/all/modules/views/handlers/views_handler_filter.inc).

```

I can, however, expose the entity ID as a viewable column with the current setup.  I just can't enable filtering or sorting for it.

It seems to me liek we can seperate viewing from filtering no problem, so enabling filtering on entity_id has no down sides.  I could be very wrong about this.  What do you all think?

Attached below is a screenshot of the browser: you can see a node would have x entities that a user would click to retrieve.

![screen shot 2018-04-03 at 3 47 26 pm](https://user-images.githubusercontent.com/7063154/38276369-c413f1b2-3762-11e8-8b71-745664a599a0.png)

**Comment by spficklin** [comment]
Hey @bradfordcondon I'm not quite following what you'd like to do.  Do you want a user to be redirected to a Drupal view that lists the entities when the user clicks the 'x records' link in the CV tree?

**Comment by bradfordcondon** [comment]
yes exactly!

I built a custom page to do to this in the interim.    However if I had a view instead I could take advantage of sorting/filtering/collections.

But the problem is entity id is not something that is filterable/sortable so I can't link to a view of say genes based on the entity ID...

**Comment by bradfordcondon** [comment]
Update: I have cases where thousands of entities might  be included, which is too many to pass as an argument.  I therefore restructured the results page to look up the appropriate entities, instead of being supplied them as a list.  That means this is a moot issue for me.

@spficklin please close if you don't see a use for this
