### ISSUE TITLE
Backwards compatibility of Templates

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#33]
When the tripal_ds module is enabled the backwards compatibility support for using old templates doesn't work.

**Comment by shawnawsu** [comment]
I can't reproduce this. What I did find is that during the upgrade process modules required for rendering are disabled, like Tripal Publication or Tripal Bulk Loader. Once those modules are enabled everything renders. 

Are there any screenshots of what you're seeing? Can I get a run down of the steps that led to this problem?

**Comment by shawnawsu** [comment]
Fix in 7.x-3.x-dashboard branch.

Fix deletes the ds layout settings and field groups created when the tripal content type is created.

**Comment by spficklin** [comment]
Hey @shawnawsu Is this fixed?
