### ISSUE TITLE
drush command failed when running in an NFS mounted webroot directory

### ISSUE THREAD

**Issue by chunhuaicheng** [tripal/tripal#334]
### System information
* Tripal Version: 7.x-3.x
* Drupal Version: 7.56
* PostgreSQL Version: 9.4
* PHP Version: 7.0.28

### Issue description
drush command  'drush trp-run-jobs' failed when launching data loading (i.e. 'Importer') jobs in an NFS mounted webroot directory. Tripal tried to load all importers from the local webroot path instead of the NFS path. This was working in 7.x-2.x

**Comment by spficklin** [comment]
@chunhuaicheng you are giving local files to the importer or uploading files?  Also, any chance you can dig into this?  I don't have an NFS mounted filesystem for testing..

**Comment by chunhuaicheng** [comment]
It's a local file.

**Comment by spficklin** [comment]
I'm going to take off the release blocker tag from this because I am not able to test/duplicate this because I don't have Drupal on an NFS file system.   @chunhuaicheng any chance you can dig into it a bit more and see what has changed between Tv2 and Tv3?

**Comment by chunhuaicheng** [comment]
I updated to the latest code and the problem is now gone. I'm closing this issue.
