### ISSUE TITLE
views-sql-compliant-three-tier-naming FAILS after update to Views 3.19

### ISSUE THREAD

**Issue by mdondrup** [tripal/tripal#336]
### System information

* Tripal Version: 7.x-2.x
* Drupal Version: 7.58
* PostgreSQL Version: 9.3
* PHP Version: 5.4

Project views was updated successfully. Installed version is now 7.x-3.19.

### Issue description

After updating to Views 3.19 today, the sql-compliant-three-tier-naming patch reports 2 failed hunks. Tripal Views do not work after the failed patch.

drupal/sites/all/modules/views $ patch -p1 < ../tripal/tripal_views/views-sql-compliant-three-tier-naming-1971160-22.patch
patching file includes/handlers.inc
Hunk #1 succeeded at 1641 (offset 111 lines).
Hunk #2 succeeded at 1664 with fuzz 1 (offset 112 lines).
Hunk #3 succeeded at 1747 (offset 117 lines).
Hunk #4 FAILED at 1662.
Hunk #5 succeeded at 1789 (offset 120 lines).
Hunk #6 succeeded at 1858 (offset 128 lines).
1 out of 6 hunks FAILED -- saving rejects to file includes/handlers.inc.rej
patching file includes/view.inc
Hunk #1 succeeded at 234 with fuzz 1 (offset 32 lines).
Hunk #2 succeeded at 944 (offset 40 lines).
patching file plugins/views_plugin_query_default.inc
Hunk #1 FAILED at 1290.
1 out of 1 hunk FAILED -- saving rejects to file plugins/views_plugin_query_default.inc.rej

I have restored the previous version of Views from drush backup for now.

<-- PS. Also feel free to ask questions, start discussions, suggest improvements We welcome any and all feedback! -->

**Comment by laceysanderson** [comment]
We have a patch for this in Tripal3 (thanks @abretaud ) but have yet to backport it. In the mean time you can use it directly by downloading it here: https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado_views/views-sql-compliant-three-tier-naming-1971160-30.patch

**Comment by laceysanderson** [comment]
This is fixed thanks to the PR by @abretaud :-)

**Comment by nathanweeks** [comment]
I just updated to Views 3.20, and the latest patch doesn't seem to apply cleanly:

```
$ patch -p1 <  ../tripal/tripal_views/views-sql-compliant-three-tier-naming-1971160-30.patch
Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/includes/handlers.inc b/includes/handlers.inc
|index 680a54d..1d72aed 100644
|--- a/includes/handlers.inc
|+++ b/includes/handlers.inc
--------------------------
Patching file includes/handlers.inc using Plan A...
Hunk #1 succeeded at 1729 (offset 92 lines).
Hunk #2 succeeded at 1750 (offset 12 lines).
Hmm...  The next patch looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/includes/view.inc b/includes/view.inc
|index d9fb43f..1cf5c50 100644
|--- a/includes/view.inc
|+++ b/includes/view.inc
--------------------------
Patching file includes/view.inc using Plan A...
Hunk #1 succeeded at 234 with fuzz 1 (offset 32 lines).
Hunk #2 succeeded at 912 (offset 10 lines).
Hmm...  The next patch looks like a unified diff to me...
The text leading up to this was:
--------------------------
|diff --git a/plugins/views_plugin_query_default.inc b/plugins/views_plugin_query_default.inc
|index 7468dd9..f092515 100644
|--- a/plugins/views_plugin_query_default.inc
|+++ b/plugins/views_plugin_query_default.inc
--------------------------
Patching file plugins/views_plugin_query_default.inc using Plan A...
Hunk #1 failed at 1290.
1 out of 1 hunks failed--saving rejects to plugins/views_plugin_query_default.inc.rej
done
```

**Comment by nathanweeks** [comment]
Whoops, sorry---false alarm. I had an old version of the patch. The latest version seems to work.
