### ISSUE TITLE
Trouble creating publish jobs programmatically

### ISSUE THREAD

**Issue by abretaud** [tripal/tripal#337]
### System information

* Tripal Version: 7.x-3.x
* Drupal Version: 7.58
* PostgreSQL Version: 9.5
* PHP Version: 7.2

### Issue description

Hi,
Still trying to support some tripal 3 stuff in python-tripal.
I'd like to create jobs for publishing content. I've seen that the jobs should call the tripal_chado::tripal_chado_publish_records callback to do this. So I have a function which creates this job using this callback.

But I have 2 problems:

- the function needs a `bundle_name` like `bio_data_2` in the arguments. How can I determine this, given the bundle label (e.g. Analysis)?
- there is a `filters` field to restrict publishing to some entities only. Can I use a chado id (e.g. analysis_id) to be sure to publish a specific entity?

**Comment by bradfordcondon** [comment]
Hello,
sorry you didnt get an answer to this yet.

>the function needs a bundle_name like bio_data_2 in the arguments. How can I determine this, given the bundle label (e.g. Analysis)?

You can select bundle_id from public.chado_bundle where data_table = 'organism'.  the bundle name is then bio_data_ . $bundle_id

You could also use `tripal_load_bundle_entity($values)` where $values = ['label' => 'organism]. BUT people are free to change the label of their bundles so its better to go through the data_table.


edit: you can also do something like this:

```
  $term = tripal_load_term_entity(array('vocabulary' => 'EDAM', 'accession' => '1333'));
  $bundle = tripal_load_bundle_entity(array('term_id' => $term->id));
```

So use the CVterm for organism to load the term, then use teh term to get the bundle, and bundle will be an object with the bundle_name as a key.

>there is a filters field to restrict publishing to some entities only. Can I use a chado id (e.g. analysis_id) to be sure to publish a specific entity?

I wrote a test to check this and i think the answer is no.  `    $values = ['bundle_name' => 'bio_data_' . $bundle, 'record_id' => $organism->organism_id];` publishes all organisms not just the one passed via `$organism->organism_id`.   Do you think its really important to be able to publish specific records? if so maybe we can ask/suggest the ability to do so.

**Comment by bradfordcondon** [comment]
Follow up: `tripal_chado_publish_records` only publishes unpublished records.  If a record is already published, it wont be updated etc.  The below test publishes 200 then 1 organism, and the second run only publishes 1 organism. 

```
    factory('chado.organism', 200)->create();


    //get bundle ID for organism
    $bundle = db_select('public.chado_bundle', 'CB')
      ->fields('CB', ['bundle_id'])
      ->condition('data_table', 'organism')
      ->execute()->fetchField();

    $values = ['bundle_name' => 'bio_data_' . $bundle];

    $bool = tripal_chado_publish_records($values);

    
    $organism = factory('chado.organism')->create();

    $bool = tripal_chado_publish_records($values);
```


```
NOTE: publishing records is performed using a database transaction.
If the load fails or is terminated prematurely then the entire set of
is rolled back with no changes to the database

196 of 200 records. (98.00%) Memory: 42,755,240 bytes
NOTE: publishing records is performed using a database transaction.
If the load fails or is terminated prematurely then the entire set of
is rolled back with no changes to the database

0 of 1 records. (0.00%) Memory: 42,761,640 bytes

Time: 14.56 seconds, Memory: 44.00MB

```

**Comment by spficklin** [comment]
Hey @abretaud, yes apologies this didn't get a quicker reply.   @bradfordcondon's suggestions should work.  I'm just checking in to see how it's going.

**Comment by bradfordcondon** [comment]
Hi @abretaud I'm assuming you've got this sorted out?  If not please let us know and we'll reopen.

**Comment by abretaud** [comment]
Sorry, I was distracted by many other things and couldn't look into it. I'll reopen if I still have problems later
Thanks for your help!

**Comment by bradfordcondon** [comment]
no problem, im guilty of this in plenty of places myself :)
