### ISSUE TITLE
Question: Tripal 3 Organism Page Example

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#34]
Hello,

After upgrading to Tripal 3, the organism, feature and analysis pages are not displaying the left sidebar they used to. Is that the intended behavior?

| Tripal 2 | Tripal 3 |
| -------- | ------------- |
|  ![screen shot 2017-03-07 at 12 49 09 pm](https://cloud.githubusercontent.com/assets/1512664/23670227/0f68ecf2-0335-11e7-9f98-ce3d56cc5130.png)  |  ![screen shot 2017-03-07 at 12 48 41 pm](https://cloud.githubusercontent.com/assets/1512664/23670232/136ff426-0335-11e7-92c6-527602956239.png)|
 

Thanks!

**Comment by spficklin** [comment]
Hello. It looks like you may not have enabled the tripal_ds module.   If you turn that on and then navigate to Administer -> Structure ->  Tripal Content Types.  Then click on 'manage display' for the Organism content type.  At the top you'll find a link that says "Apply Default Tripal Layout" and click that.  It will then apply the layout that you're accustomed too, but with some variation.   

You'll have to do this with any content types that were created prior to installing the tripal_ds module.  Any new content types you create in the future will automatically have the layout applied.

**Comment by spficklin** [comment]
Also.... the reason the tripal_ds module is separate and not part of the core of Tripal, and not automatically installed, is to give those who want more freedom the ability to turn off that module and manage the display of their content types with total freedom.

**Comment by almasaeed2010** [comment]
Thanks for the quick response! That solved the issue.
