### ISSUE TITLE
Rapid installation Error, Tripal 3

### ISSUE THREAD

**Issue by dedenmatra** [tripal/tripal#340]
Dear Tripal Admin,

I try to install Tripal through Rapid installation but its not complete. I atached error log below 

HTTP request sent, awaiting response... 200 OK
Length: 3277833 (3.1M) [application/x-gzip]
Saving to: 'drupal-7.56.tar.gz'

drupal-7.56.tar.gz               100%[=========================================================>]   3.13M  9.84MB/s    in 0.3s    

2018-04-18 07:43:17 (9.84 MB/s) - 'drupal-7.56.tar.gz' saved [3277833/3277833]

Password for user tripal3: 
You are about to DROP all tables in your 'tripal3' database. Do you want to continue? (y/n): y
Password for user tripal3: 
Password for user tripal3: 
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
Password for user tripal3: 
psql:/tmp/drush_o99rfa:1: ERROR:  syntax error at or near ":"
LINE 1: DROP TABLE perl: warning: Please check that your locale sett...
                       ^
Starting Drupal installation. This takes a few seconds ...                                                              [ok]
WD php: Exception: To start over, you must empty your existing database.To install to a different database, edit the    [error]
appropriate settings.php file in the sites folder.To upgrade an existing installation, proceed to the update script.View
your existing site. in install_verify_completed_task() (line 840 of /var/www/html/includes/install.core.inc).
WD php: Warning: Cannot modify header information - headers already sent by (output started at                          [warning]
/usr/share/php/drush/includes/output.inc:37) in drupal_send_headers() (line 1486 of
/var/www/html/includes/bootstrap.inc).
Exception: <ul><li>To start over, you must empty your existing database.</li><li>To install to a different database, edit the appropriate <em>settings.php</em> file in the <em>sites</em> folder.</li><li>To upgrade an existing installation, proceed to the <a href="http://localhost/usr/share/php/drush/update.php">update script</a>.</li><li>View your <a href="http://localhost/usr/share/php/drush">existing site</a>.</li></ul> in install_verify_completed_task() (line 840 of /var/www/html/includes/install.core.inc).
Drush command terminated abnormally due to an unrecoverable error.                                                      [error]

**Comment by btski** [comment]
Are you trying to install over an existing installation of Tripal? What are your dependencies (Drupal Version, PostgreSQL Version, PHP Version, operating system)?

**Comment by spficklin** [comment]
Hi @dedenmatra were you able to resolve the issue?

**Comment by dedenmatra** [comment]
@spficklin This problem have solved.. thank you

**Comment by laceysanderson** [comment]
I'm glad you found a solution @dedenmatra!
