### ISSUE TITLE
Problem/Error implementing basic search filtering via TripalFieldQuery 

### ISSUE THREAD

**Issue by isumoc** [tripal/tripal#341]
* Tripal Version: 3.x (latest via github)
* Drupal Version: 7.56
* PostgreSQL Version: 9.5.10
* PHP Version: 7.1.13

I get this error message when attempting a basic filter: 
Query callback function did not provide a numeric value: tripal_field_storage_query

This error message comes from an exception thrown and logged here:
https://github.com/tripal/tripal/blob/a98e03f0e4b357c67d8b44b7b5c4ce75cac1cf51/tripal/tripal_views_query.inc#L319

As far as I can tell tripal_field_storage_query will never return numeric - it returns an array.

If you don't enable the advance logging for views the error is silent ( due to vpr() ) and you just get zero results in the search.

For example:
http://demo.tripal.info/3.x/data_search/individual   ( all records )
versus:
http://demo.tripal.info/3.x/data_search/individual?data__identifier_op=contains&data__identifier=Basmati&schema__name_op=contains&schema__name=&data__accession_op=contains&data__accession=&obi__organism_op=contains&obi__organism=
( zero records )

Thanks in advance for any pointers to what might be the problem here.

**Comment by spficklin** [comment]
Hi @isumoc.  I am not able to duplicate the error.  However, I can duplicate the issue that the filters are not working.  I have committed a fix to this branch of Tripal:  7.x-3.x-issue-341

Can you pull that branch and test it for me to see if you still have issues?

**Comment by isumoc** [comment]
@spficklin looks like this has been merged to master and all is well! Thanks for the fix.
