### ISSUE TITLE
Tripal Collections + Drupal Search API Incompatibility

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#342]
### System information
* Tripal Version: 7.x-3.x
* Drupal Version: 7.x

### Issue description
Currently the Tripal Collections Views Handler requires the attached view to be using the query plugin `tripal_views_query`. This is not the case for views based on the Drupal Search API. Furthermore, the current Tripal Collections Views Handler form is geared towards displaying options for a single entity type.

### Solution
We need to make a new Tripal Collections Views handler compatible with Drupal Search API views. Luckily, Tripal Collections already support collections containing multiple entity type (Tripal content types) so it's more a matter of supporting the generic query plugin for views and providing a good UI for choosing additional fields.

**Comment by laceysanderson** [comment]
PR Submitted: #351

**Comment by spficklin** [comment]
The PR for this got merged. I'm assuming this is resolved.
