### ISSUE TITLE
Data Collections for Anonymous Users

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#343]
As requested by @isumoc.  Can we support anonymous users with Data Collections.

**Comment by spficklin** [comment]
I'm adding a suggestion to this issue from @almasaeed2010 on PR #592 related to the search form not appearing for anonymous users.  

> My suggestion for this though is to add a message at the bottom to inform the user that they could save the results if they create an account. But this will probably require checking if the admin is allowing new user registrations.

**Comment by laceysanderson** [comment]
I'm closing this issue as there has been no movement in over a year. If you still need this functionality, please comment and we'll look into it further.
