### ISSUE TITLE
Tripal site incredibly slow due to tripal_analysis_blast module?

### ISSUE THREAD

**Issue by btski** [tripal/tripal#348]
* Tripal Version: 3
* Drupal Version: 5.10.0
* PostgreSQL Version: 9.5.12
* PHP Version: 7.0

I've noticed incredibly slow load times on every page of my Tripal site. Some quick research told me the likely cause was a misbehaving module. Admittedly, when attempting to install tripal_analysis_blast, I made several mistakes and did not properly disable/uninstall. However, there seems to be an additional problem. I did a complete backup and exported my current Tripal site to another server. The tripal_analysis_blast module was not transferred, but it was enabled. Despite having an enabled module that was not installed, the site worked significantly better (less than 1 second loads instead of nearly 10 seconds). I then attempted to install tripal_analysis_blast, only for it to fail:

Directory /home/ubuntu/.drush/cache/default exists, but is not       [error]
writable. Please check directory permissions.
The following module is missing from the file system: <em            [warning]
class="placeholder">tripal_analysis_blast</em>. For information about
how to fix this, see <a
href="https://www.drupal.org/node/2487215">the documentation
page</a>. bootstrap.inc:1143
Directory /var/www/html/sites/all/modules exists, but is not         [error]
writable. Please check directory permissions.
Project tripal_analysis_blast (7.x-2.1) could not be downloaded to   [error]
/var/www/html/sites/all/modules/tripal_analysis_blast.

Following the failed installation, the site performance has dropped again. I've tried to clear the drush cache but that doesn't seem to have improved anything. Any advice? I've tracked down and deleted/disabled all files/directories corresponding to the tripal_analysis_blast module. There seems to be something else that's causing issues.

Edit 1 - The problem is not contained within the database used to install Tripal (dropdb doesn't fix it). Attempting to follow instruction 2 from [source](https://www.drupal.org/node/2487215) results in error: 
drush sql-query "DELETE from system where type = 'module' AND name = 'tripal_analysis_blast';"
No database to operate on.                                           [error]
Query failed.                                                                    [error]

**Comment by bradfordcondon** [comment]
Hi, 

When errors get written to watchdog it can slow down the site considerably.  Deleting any module without first disabling will cause this problem.  

You said you tried reinstalling but could not: how are you doing that?
I would `git clone https://github.com/tripal/tripal_analysis_blast.git` into `/var/www/html/sites/all/modules/tripal_analysis_blast` (which is where Drupal is looking for your module). then drush disable and uninstall.

**Comment by bradfordcondon** [comment]
Regarding option 2 (if you can redownload the module and disable ie follow step 1, my above suggestion, your life will be easier):

```
drush sql-query "DELETE from system where type = 'module' AND name = 'tripal_analysis_blast';"
No database to operate on. [error]
```

How about `drush sql-query "DELETE from public.system where type = 'module' AND name = 'tripal_analysis_blast';"`  (note **public**.system)

**Comment by bradfordcondon** [comment]
hi @btski 
after reviewing your issue again, a couple more things:

```
drush sql-query "DELETE from system where type = 'module' AND name = 'tripal_analysis_blast';"
No database to operate on. [error]
Query failed. [error]
```

this is telling you that drush couldnt connect to the db.  make sure you are running this command in `/var/www/html`

you also have permissions issues

```
Directory /var/www/html/sites/all/modules exists, but is not [error]
writable. Please check directory permissions.
```

run this from web root (usually /var/www/html)  to fix

```

find . -type d -exec chmod 755 {} \; && find . -type f -exec chmod 644 {} \;

```

**Comment by btski** [comment]
Thanks @bradfordcondon for the helpful suggestions. I can't recall if I was appropriately running drush from the /var/www/html directory. I seem to forget to do that fairly often. I have now run "DELETE from public.system where type = 'module' AND name = 'tripal_analysis_blast';" on two servers/instances. I have also run find . -type d -exec chmod 755 {} \; && find . -type f -exec chmod 644 {} \; (from cd /var/www/html). The bulk of permissions could not be changed ("Operation not permitted"). Unfortunately, load time has not been reduced (do I need to restart anything?). Currently takes 10+ seconds to load a basic page.

Sorry if I wasn't clear early. When I mentioned that tripal_analysis_blast was failing to load, I was aware of why it wasn't loading (after the fact). What I don't understand is the impact failure to load had on my website. Despite the error returning "could not be downloaded", something still slowed performance.

I'll work on installing and properly disabling/uninstalling tripal_analysis_blast and see if that makes a difference.

**Comment by almasaeed2010** [comment]
Hello @btski 

I noticed that you are trying to install tripal_analysis_blast using `drush`. Unfortunately, the version in drush does not support Tripal 3. To install the module correctly, you'll have to use `git`. 

```shell
cd /var/www/html/sites/all/modules
git clone https://github.com/tripal/tripal_analysis_blast.git
cd tripal_analysis_blast
git checkout 7.x-3.x
drush dis -y tripal_analysis_blast; drush pm-uninstall -y tripal_analysis_blast; drush en -y tripal_analysis_blast
```

This guarantees you have the version that supports Tripal 3. Note the last command may take a few minutes.

Regarding the permissions issue, if you have root access (sudo privileges), please run the find command again using sudo as such:

```shell
cd /var/www/html
sudo find . -type d -exec chmod 755 {} \; && sudo find . -type f -exec chmod 644 {} \;
```

It is important for the permissions to be correctly setup in order for Drupal to function appropriately.

As for the speed of the site, could you please clarify what you mean by a basic page? Tripal handles only specific content type, so knowing what the page type is (node, front page, Gene, etc) would help a lot in narrowing your issue.

Thanks!

**Comment by btski** [comment]
Sorry for the slow response. By speed of the site, I'm referring to the navigation time to any page on the Tripal site. Displaying any page (including Tripal admin pages) is slow, perhaps to varying degrees, but at least 10+ seconds to load. I've attempted to follow @almasaeed2010 's advice. On a server with tripal_analysis_blast already installed (incorrectly with drush):

```
cd /var/www/html/sites/all/modules
git clone https://github.com/tripal/tripal_analysis_blast.git
```
fatal: destination path 'tripal_analysis_blast' already exists and is not an empty directory.
`git checkout 7.x-3.x`
fatal: Not a git repository (or any of the parent directories): .git
`drush dis -y tripal_analysis_blast; drush pm-uninstall -y tripal_analysis_blast; drush en -y tripal_analysis_blast`
tripal_analysis_blast is already disabled.                           [ok]
There were no extensions that could be disabled.                     [ok]
tripal_analysis_blast is already uninstalled.                        [ok]
There were no modules that could be uninstalled.                     [ok]
The following extensions will be enabled: tripal_analysis_blast
Do you really want to continue? (y/n): y
WD php: DatabaseSchemaObjectExistsException: Table                   [error]
tripal_analysis_blast already exists. in
DatabaseSchema->createTable() (line 663 of
/var/www/html/includes/database/schema.inc).
Cannot modify header information - headers already sent by (output   [warning]
started at /usr/share/php/drush/includes/output.inc:37)
bootstrap.inc:1486
DatabaseSchemaObjectExistsException: Table tripal_analysis_blast already exists. in DatabaseSchema->createTable() (line 663 of /var/www/html/includes/database/schema.inc).
Drush command terminated abnormally due to an unrecoverable error.   [error]


I then attempted to disable and remove tripal_analysis_blast:
`drush pm-disable tripal_analysis_blast`
WD menu: PDOException: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction [error]
is aborted, commands ignored until end of transaction block: SELECT r.filename AS filename
FROM 
{registry} r
WHERE  (r.name ILIKE :db_condition_placeholder_0) AND (r.type = :db_condition_placeholder_1) ;
Array
(
    [:db_condition_placeholder_0] => views\_ui
    [:db_condition_placeholder_1] => trait
)
 in _registry_check_code() (line 3483 of /var/www/html/includes/bootstrap.inc).
tripal_analysis_blast was disabled successfully.
`drush pm-uninstall -y tripal_analysis_blast`
tripal_analysis_blast is already uninstalled.                                                    [ok]
There were no modules that could be uninstalled.

The tripal_analysis_blast module still exists as a directory in /var/www/html/sites/all/modules and can be found with "locate". Based on the SQL error, I have doubts that I will be able to return the site to a working condition. It will not be difficult to rebuild from scratch. Going forward, I'll properly install using git instead of drush (I was referring to outdated Tripal v2 instructions, which I hadn't realized). I'll also never remove modules with rm, and disable prior to uninstalling. Thanks for the help!

**Comment by almasaeed2010** [comment]
Just a note, the SQL error is saying that the "bad" changes to the DB have been reverted and therefore your DB should be in its previous state. As for the `fatal: destination path 'tripal_analysis_blast' already exists and is not an empty directory.` error, I should've mentioned that you will need to delete the old module before running the `git clone` command. Sorry that was my bad.

Thanks!

**Comment by spficklin** [comment]
Just checking in... has this been resolved?
