### ISSUE TITLE
Required multi field adds new field on editing

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#349]
Hi guys, so we have a few required fields (allowing multiple values) under the contact content type. It seems that everytime I go to the edit form, an additional multiple field is added. So say I had 2 values under the multifield, when I go to the edit form, I see three appearing with the last one having no value (empty). Because of this, when I try to submit, it says that I must enter a value in the third field. I think this might be a bug.

Please advise?
Thanks!

**Comment by almasaeed2010** [comment]
Hello @risharde 

To be able to help you better, could you please let us know the following:
1. Have you created this content type/bundle manually?
1. Is this a custom field added by a module? Or is it provided with Tripal?
1. To be able to replicate the error on our end, could you please provide the steps to add the field?

Thanks!

**Comment by shawnawsu** [comment]
This is a Drupal issue. Please see this drupal.org discussion about it (there is a patch included in the discussion if you must have required unlimited fields): https://www.drupal.org/project/drupal/issues/980144

If the patch doesn't fix your problem please reopen the ticket.
