### ISSUE TITLE
Bulk loader requires tripal_core

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#354]
For some reason the tripal_bulk_loader.inc file still requires tripal_core.  I don't think this is needed but I'm adding this issue to remind us to check.

**Comment by spficklin** [comment]
@laceysanderson any thoughts on this one?

**Comment by laceysanderson** [comment]
I also don't think this is needed but we'll want to check the bulk loading job node type to make sure it doesn't use the Chado Node API

**Comment by spficklin** [comment]
I've added a PR to fix this:  PR #381

**Comment by spficklin** [comment]
PR #381 was merged. Closing this issue.
