### ISSUE TITLE
Tripal Upgrade from 2.x to 3.x - What happens to URLs, URL Aliases and Redirects ?

### ISSUE THREAD

**Issue by isumoc** [tripal/tripal#355]
* Tripal Version:  latest via github
* Drupal Version:  7.56
* PostgreSQL Version: 9.5.10
* PHP Version: 7.1.13

When migrating content from Tripal 2.x to Tripal 3.x you have the option of migrating your old URL aliases from node/<node_id> to bio_data/<entity_id> - ie updating the url_alias table entries.  This option is on the Drupal menu at /admin/tripal/storage/chado/migrate

The work is done here:
https://github.com/tripal/tripal/blob/445cbb56c50fc80f098f82f9f99bee6e73307356/tripal_chado/includes/tripal_chado.migrate.inc#L828

This does not update a redirection from the bio_data/<entity_id> url.

It is possible to set up "bulk update" data paths/URL Alias and redirection from this menu:
/admin/structure/bio_data/manage/bio_data_<bundle_id>

The work is done here:
https://github.com/tripal/tripal/blob/0819c4eb3cae34e6503edeb0ab66f7c503fd3227/tripal/includes/TripalEntityController.inc#L238

This sets up aliases and invokes the redirect module to update a redirect for that URL.

However, you may only use a quite restrictive 5 tokens from the "Available Tokens" list to set up the alias.  

Thus,  it appears to me that you won't be able use your URL pattern(s) from Tripal 2.x.  when using Tripal 3.x unless you plan to manually update the aliases and redirections needed.

I am not clear if this is all by design or otherwise - but I wanted to put it here as an issue having gone through the most recent code etc.

Thanks in advance for any clarity on this.

**Comment by laceysanderson** [comment]
HI @isumoc,

When you migrate URL alias' from nodes to Tripal Entities, it moves all the current alias' for the node to the entity [here](https://github.com/tripal/tripal/blob/445cbb56c50fc80f098f82f9f99bee6e73307356/tripal_chado/includes/tripal_chado.migrate.inc#L837-L839):

```php
            UPDATE url_alias
            SET source = 'bio_data/" . $entity->entity_id .
            "' WHERE source = 'node/" . $entity->nid . "'";
```

Example: if you had an alias `species/Lens/culinaris` set up for `node/14` and the corresponding TripalEntity is `bio_data_10/46`. Before upgrade public.url_alias would look like this:

| pid | source | alias  | language           |
|----|--------|-------|----------------|
|   4 | node/14 | species/Lens/culinaris | und |

and after upgrade it would look like this:

| pid | source | alias  | language           |
|----|--------|-------|----------------|
|   4 | bio_data_10/46 | species/Lens/culinaris | und |

Furthermore, the observed functionality would be when navigating to [my drupal site]/species/Lens/culinaris I would now see the Tripal 3 Entity rather then the Tripal 2 node.

Is this your desired behavior?

**Comment by isumoc** [comment]
Hi @laceysanderson,

I would like users and search engines never to see /bio_data/<entity_id> urls.

Is this possible ?  Can you let me know how to configure that ?

Thanks again!

**Comment by laceysanderson** [comment]
This should already be the case if you have URL alias' set up for your nodes and have migrated the alias' using the form at `/admin/tripal/storage/chado/migrate`. 

If you are creating new types rather then migrating, this can be done using the form at `/admin/structure/bio_data/manage/bio_data_<bundle_id>` which I think submits a bulk update when you change the alias'. The new URL alias' are more restrictive then the ones for Tripal2 to make sure you don't inadvertently make URLs that are not unique. With this is mind you can only add fields that are required and only support a single value. If you want to use a particular field that is singular, making it required should add it to the list of available tokens.

**Comment by almasaeed2010** [comment]
Hi,

I wanted to point out that there is another little problem with the new URL bulk converter when compared to the Tripal 2 version. The new version, removes more "special" characters such as `.` and `_`, which may result in your new URLs having a slightly different structure than they would've on a Tripal 2 site if your URLs had special characters in them. 

Thanks!

P.S. I am not sure which characters exactly are different, I just remember having to deal with that post migration.

**Comment by spficklin** [comment]
I have submitted a pull request that fixes the issue raised by @almasaeed2010 .  The question posed by @isumoc I believed was answered by @laceysanderson and discussed in a recent online help session.  So I think once the PR is approved this issue can be closed.

**Comment by laceysanderson** [comment]
PR Merged.
