### ISSUE TITLE
Easy PubMed Importer

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#356]
We need an easy way via the GUI to import publications. We have the more complicated publication importer for automating import of new pubs.  But if someone just wants to import a list of PubMed IDs they have to use a drush command. It would be easy, and useful, to have a little form for importing publications from PubMed using IDs.

**Comment by bradfordcondon** [comment]
I would really like this.  Similarly, a reference importer that accepts say bibtex or enl format. Not sure right now which would be easier to code and/or more convenient.

Advantage of a file importer is you can support references that dont have pubmed citations IE DOIs.

**Comment by laceysanderson** [comment]
I have this: https://github.com/UofS-Pulse-Binfo/tripal_bibtex
It only provides a drush command but it might be a good place to start.

**Comment by bradfordcondon** [comment]
I'd propose the path of least resistance, adding this as a tripal 3 importer.

assuming of course that this functionality is needed in core.

**Comment by bradfordcondon** [comment]
oops: I see that module isnt tripal 3 ready.  I'd imagine wouldnt be too much to upgrade it, I can take a look if youre too busy?
If I am going to have to add pubs to my site i definitely want this.

**Comment by laceysanderson** [comment]
That would be amazing if you wanted to take this on :-) It's not a priority for us as our publications are the least of our worries 😝

**Comment by bradfordcondon** [comment]
OK its now tripal3 compatible! I might do a little more work on it later.  I dont know that i'll plan on adding what Stephen has in mind (something that uses the pubmed), since loading in bibtex is good enough for me :D

**Comment by spficklin** [comment]
This would be great. But given lack of time. I"m marking this for maybe later in the hopes someone who wants it will just do it :-)
