### ISSUE TITLE
upgrading CI setup

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#357]
I'm performing some upgrades and changes for the build and testing framework.

### Testing stuff

We've (@almasaeed2010 ) made some cool changes to Tripal Test Suite.  We currently don't use it on this repo: I'm going to change that.  This gives us access to **data factories** : i'll include a few new tests in the PR so we can see how those work and make it really easy to put data into Chado for testing things and remove it when we're done.

### Travis stuff

* Tripal 2 should launch without checking out 7.x-2.x.  Instead we should launch a functional tripal 2 contianer, overwrite with the current env (PR), and execute the upgrade.  see #347 
  - `  - docker run -it -d --rm --name tripal2 -v "$(pwd)":/modules/tripal statonlab/tripal2` accomplishes this, but we need to make sure build of 7.x-2.x is *automated* based on changes to that branch.
* Tripal 3 tests: 
  - Install of current PR as fresh tripal site.  This one is easiest and requires no changes.
  - Upgrading from current RC to current PR.  I think this will be best handled same as Tripal 2 container: when a new RC is tagged, the docker image should update, and we pull that image and test upgrading from it.

edit: Regarding RC versus previous master branch, i guess we can just do the previous master branch.

**Comment by almasaeed2010** [comment]
I wonder if we should consider building the tripal site on the travis environment directly to utilize Travis matrices support. Although this means we have to build a whole Drupal site before really getting to Tripal testing, I think the benefits of matrices outweigh this little problem.

Thoughts?

**Comment by bradfordcondon** [comment]
Yes I agree.  I still think we keep the dockers to demonstrate tripal 2 - 3 upgradability, at least.  It obviously slows tests down but as we have discussed we gain some seriously robust testing in terms of PHP versions, postgres versions...

**Comment by bradfordcondon** [comment]
merged.
