### ISSUE TITLE
feature request: silence all tripal_report_errors

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#358]
I'd like a way to silence `tripal_report_error`.

## Reason for request

Consider the below test case, verifying that tirpal_chado_publish_records does indeed return false when given nonsense bundle:

```php

  public function test_tripal_chado_publish_records_false_with_bad_bundle() {

    $bool = tripal_chado_publish_records(['bundle_name' => 'never_in_a_million_years']);
    $this->assertFalse($bool);
}

```

The test successeds, but will always print `[site http:///usr/local/bin] [TRIPAL ERROR] [TRIPAL_CHADO] Unknown bundle. Could not publish record: The bundle name must be provide` to the console.  This is a pain for testing.

in other cases we suppress console messages using for example php's ob:

```php
    ob_start();//dont display the job message
    $bool = tripal_chado_publish_records($values);
    ob_end_clean();
```
However this only works for STDOUT.

We definitely want to allow and encourage negative test cases like this, without spamming the test console.

## Fix

We could set an environment variable ie`APP_ENV` var.  Then error reporter can `if(getenv('APP_ENV') === 'testing') return;`

Or we could say SUPPRESS_ERRORS or something, like is done with
```php
  if (($severity == TRIPAL_DEBUG) AND (getenv('TRIPAL_DEBUG') != 1)) {
``` 
on line 91, `tripal.notice.api.inc`.

**Comment by bradfordcondon** [comment]
in our upcoming Tests PR I build this in, by returning if `getenv('TRIPAL_SUPPRESS_ERRORS=TRUE')`.  

So in the test, you couch your call  like so:
```
  putenv("TRIPAL_SUPPRESS_ERRORS=TRUE");//this will fail, so we suppress the tripal error reporter
    $bool = tripal_chado_publish_records(['bundle_name' => 'never_in_a_million_years']);
    $this->assertFalse($bool);
    putenv("TRIPAL_SUPPRESS_ERRORS");//unset
```

**Comment by laceysanderson** [comment]
Quick Question: why did you decide to go with `putenv("APP_ENV")` to unset rather then `putenv("TRIPAL_SUPPRESS_ERRORS=FALSE");` which feels more intuitive to me?

**Comment by bradfordcondon** [comment]
oops, edited my post.  should be `putenv("TRIPAL_SUPPRESS_ERRORS");`

That said `putenv("TRIPAL_SUPPRESS_ERRORS")` unsets the variable,  vs `putenv("TRIPAL_SUPPRESS_ERRORS=FALSE")` , keeps the variable but set to FALSE.  So unsetting does a better job  cleaning up.

In practice, someone writing a test could do either.  So long as they dont leave the variable =TRUE.

In the tripal_warning method, it checks if the variable === TRUE.  Maybe i should have it str_to_lower so that people can use TRUE True or true...

**Comment by laceysanderson** [comment]
Thanks for the clarification! 👍 It would probably be best to use str_to_lower() just to be safe and potentially save developers time debugging why they can't suppress errors in their tests ;-)

**Comment by bradfordcondon** [comment]
this was in #362 so can close.
