### ISSUE TITLE
tripal_chado.organism.api.inc has 2 tripal 2 methods that should be upgraded/deprecated

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#360]
`tripal_chado/api/modules/tripal_chado.organism.api.inc`

```
function tripal_get_organism_select_options($syncd_only = TRUE) {
  $org_list = array();
  $org_list[] = 'Select an organism';

  if ($syncd_only) {
    $sql = "
      SELECT *
      FROM [chado_organism] CO
        INNER JOIN {organism} O ON O.organism_id = CO.organism_id
      ORDER BY O.genus, O.species
    ";
    $orgs = chado_query($sql);
```

so should we  upgrade to look up the organism bundle and join on that?

**Comment by bradfordcondon** [comment]
Same for `tripal_get_organism_image_url`, which uses  `chado_get_nid_from_id('organism', $organism->organism_id)`.

edit: updated issue title to reflect.

**Comment by laceysanderson** [comment]
Good catch! I would definitely lean towards update rather then deprecate for `tripal_get_organism_select_options` -your proposed solution sounds great 👍 

As for the second one, I wonder if that's needed at all now that organism images are fields. Thoughts @spficklin?

**Comment by bradfordcondon** [comment]
Happy to  contribute fix to the select options. Waiting to hear about `tripal_get_organism_image_url`  before i go ahead though so i can maybe do both at once.

**Comment by spficklin** [comment]
So, we have a bit of an issue here with both of those.  We do not want to break backwards compatibility when folks upgrade to Tv3 but continue to use Tv2 nodes (which they can do).   

Also, @shawnawsu just went through the process of fixing the naming for all of these API functions and these two got their names fixed as well (see issue #330).  

So, before we make the updates I think we should wait on Shawna's pull request that unifies all the naming for API functions.  Then after that, I think we recreate theses two functions with the original names in the legacy API this way Tv2 sites can continue to use the old name and it will work as before.  Then we fix the newly named function to work with either nodes or entities.  Perhaps we pass a flag to it that indicates which and set the flag to default to entities?

Thoughts?

**Comment by bradfordcondon** [comment]
In the case of `tripal_get_organism_select_options`, you could add a check that tests if version 2 or version 3, and run the corresponding SQL statement (joining on node id for tripal 2, entity id for tripal 3.)  I dont know if thats bad practice though and its better to spawn a new tripal 3 method with a new name...

also havent looked/thought about at the image thing and how relevant it is for tripal 3...

eitehr way im all for putting it off until shawna's PR goes through.

**Comment by spficklin** [comment]
Unfortunately, someone could be running Tv3 but using Tv2 compatibility. I'm not sure how we could be 100% sure when the function should query nodes or query entities.

**Comment by laceysanderson** [comment]
I don't think we worry about making the newly named function handle nodes. 

If they need the node functionality in an extension it will be using the old name (as per @spficklin suggestion this will be in the legacy api & handle nodes). As they upgrade the extension to Tripal 3, they will change the name to the new version and upgrade to use entities rather then nodes thus no longer needing node support. 

As far as someone using the extension, they will just not upgrade it until they are ready to use the entity-based version and the extension should take care of the switch so the user wouldn't need to care.

Right?

**Comment by bradfordcondon** [comment]
I think we can close this issue in favor of #688 

as for the other functions ie `tripal_get_organism_image_url` and `chado_get_nid_from_id` we are keeping these in legacy for backwards compatibility.  I actually use the existence of `chado_get_nid_from_id` to etermine if a site is running tripal 3 or 2
