### ISSUE TITLE
help defining field with default text widget and storage?

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#367]
### Overview 

I'd like to define a field that has a widget that allows you to enter a file system path.  Then it will have a formatter that runs a javascript app on that file.  Nothing is stored in chado.

To this end I define a field instance where the widget is of type `text_textfield`, it uses a custom formatter, and it stores the text in type `field_sql_storage`. 
Is this the correct approach?  If so can I get some help with what I'm doing wrong?

  for example:

```
 $field_name = 'local__cmap_viewer';
    $instances[$field_name] = [
      'field_name' => $field_name,
      'entity_type' => $entity_type,
      'bundle' => $bundle->name,
      'label' => 'cMap',
      'description' => 'A cmap visualization field.',
      'required' => FALSE,
      'storage' => [
        'type' => 'field_sql_storage',
      ],
      'settings' => [
        'auto_attach' => FALSE,
        'text_processing' => 0,
        'max_length' => 10485760,
      ],
      'widget' => [
        'type' => 'text_textfield',
        'required' => FALSE,
        'settings' => [
        ],
      ],
      'display' => [
        'default' => [
          'label' => 'hidden',
          'type' => 'local__cmap_viewer_formatter',
          'settings' => [],
        ],
      ],
    ];
```

My [current attempt is here](https://github.com/statonlab/tripal_cmap_loader/blob/base_viewer_field/includes/tripal_cmap_loader.fields.inc).

What i *can* do is create the field, and use the plain text field (it shows up as a widget).  however theres something wrong with the field storage and/or the widget configuration.

### Problems

No matter what I get undefined indexed notices for the field widget when editing/creating. 

```
Notice: Undefined index: max_length in text_field_widget_form() (line 514 of /Users/chet/UTK/tripal/modules/field/modules/text/text.module).
Notice: Undefined index: text_processing in text_field_widget_form() (line 549 of /Users/chet/UTK/tripal/modules/field/modules/text/text.module).
```

I've tried adding these keys to the widget settings, and also to the field settings.

furthermore, the storage doesnt work: When I submit and go back to re-edit, the field is nulled.

**Comment by bradfordcondon** [comment]
ok no more undefined index errors.  i see that it was looking for max_length in the field settings, NOT the instance settings.

However, field storage still doesnt work.  editing the text value and returning to the edit screen leaves a clear text field.

Additionally I can't even get a `dpm` to show up in hte field's base load method.
this seems to tell me that my field is hooked up totally wrong...


When I select "text field" in the field settings for widget, I have no choices for widget type.

![screen shot 2018-05-07 at 2 39 06 pm](https://user-images.githubusercontent.com/7063154/39718497-779e5b9e-5204-11e8-974d-6f83704f4e67.png)


However if i select a different field utilizing a text field widget IE name, It has text field selected...

**Comment by bradfordcondon** [comment]
I got this field to work by changing the base type itself to text.

```php
    // Then describe the field defined by that term.
    $field_name = 'local__cmap_viewer';
    $fields[$field_name] = [
      'field_name' => $field_name,
      'type' => 'text',
      'cardinality' => 1,
      'locked' => FALSE,
      'module' => 'text',
      'storage' => [
        'type' => 'field_sql_storage',
      ],
      'settings' => [
        'max_length' => 10485760,
      ],
    ];
  
```

However, I don't know how to set the cvterm this way.  The field is broken until you edit it and assign a cvterm in the field settings.

At this point this issue is a) a cautionary tale, and b) a bunch of unanwered questions:

* Is the final approach correct?  (declare the field as text from text module, and then write a custom formatter only?)  
* If yes, how do i assign the cvterm If not through the base class?
* If no, how do you get a tripalfield to use `field_sql_storage` ?

**Comment by laceysanderson** [comment]
How did you end up solving this @bradfordcondon (hoping you did)?

**Comment by spficklin** [comment]
@laceysanderson we have fields with Tripal that do this. Are you needing this functionality?  If you can describe what you are wanting to do I think I can point you at an example.

**Comment by bradfordcondon** [comment]
the snippet i wrote above works, but like i said i wasn't sure if i was doing it the "right" way or not.

I also wasnt setting the cvterm in the field definition which I needed to do, but  I think if I had time to revisit that, wouldnt be too hard to get that done...

**Comment by laceysanderson** [comment]
No, I'm good :-) Just trying to go through old issues and make sure they are solved so we can close them. @spficklin was @bradfordcondon's approach the "right" way?

**Comment by spficklin** [comment]
@bradfordcondon is this still an issue we should keep open?

**Comment by bradfordcondon** [comment]
i dont know.  i think my solution was pretty hacky/bad and had problems with the implementation.

>we have fields with Tripal that do this. 

If you're confident this is the case then we can close-- i cant think of any though (that use default storage but have a custom formatter).

The specific implementation is not an issue anymore though- i advocate using the DRupal core file field instead.  With that in mind, I'm OK closing.
