### ISSUE TITLE
tripal pub cvterm not populated on site install

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#370]
recreated by @laceysanderson 

The publicaiton bundle type field does not display any options.
For some reason this statement returns no results in `schema__additional_type_widget`.
```
      $sql = "
          SELECT
            CVTS.cvterm_id, CVTS.name
          FROM {cvtermpath} CVTP
            INNER JOIN {cvterm} CVTS ON CVTP.subject_id = CVTS.cvterm_id
            INNER JOIN {cvterm} CVTO ON CVTP.object_id = CVTO.cvterm_id
            INNER JOIN {cvterm} CVTT ON CVTP.type_id = CVTT.cvterm_id
            INNER JOIN {dbxref} DBXO ON DBXO.dbxref_id = CVTO.dbxref_id
            INNER JOIN {db} DBO      ON DBO.db_id = DBXO.db_id
          WHERE
            DBO.name = :vocabulary AND DBXO.accession = :accession AND
            (CVTT.name = 'is a' OR CVTT.name = 'is_a') AND
            CVTS.name != CVTO.name AND
            NOT CVTS.is_obsolete = 1
          ORDER BY CVTS.name ASC
       ";

```

We do have tripal_pub cvterms.  however this is is looking basd on db:accession,  for TPUB: 0000015.  I htink my terms all have db = tripal... this might be the problem?

edit: nah terms are there http://localhost:8083/cv/lookup/TPUB ...

**Comment by bradfordcondon** [comment]
cvterm path isnt populate for this CV.

**Comment by bradfordcondon** [comment]
manually populating the cvtermpath for pubs fixes the issues.

Why doesnt cvtermpath populate for tripalpub on install?

**Comment by almasaeed2010** [comment]
Confirmed that new installs of tripal don't have publication types available and that populating cvtermpath for `tripal_pub` fixes the issue.

**Comment by spficklin** [comment]
I think this has been fixed. I have recently installed a new Tripal instance and the publication types are present.  I'm sure we fixed this along the way and forgot to update this issue.
