### ISSUE TITLE
chado_bundle type_id is varchar so we can't join it with cvterm

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#371]
### System information
* Tripal Version: 7.x-3.x (master)
* Drupal Version: 7.59
* PostgreSQL Version: 9.6
* PHP Version: 7.1

### Issue description
The chado_bundle table has a type_id column set to varchar instead of int (or big int). Since type_id is a foreign key referring to `cvterm.cvterm_id`, it should match the column type of big int. Running the following query results in an error:
```sql
select * from chado_bundle CB
  inner join chado.cvterm CV on CB.type_id = CV.cvterm_id 
```

Error:
```
SQL error:

ERROR:  operator does not exist: character varying = bigint
LINE 2:   inner join chado.cvterm CV on CB.type_id = CV.cvterm_id 
                                                   ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
In statement:

select * from chado_bundle CB
  inner join chado.cvterm CV on CB.type_id = CV.cvterm_id 
```

We are currently working around it by explicitly casting type_id to int as such:
```sql
select * from chado_bundle CB
  inner join chado.cvterm CV on CB.type_id::integer = CV.cvterm_id 
```

Should we consider adding an update to fix this or is there a specific reason to having it set as varchar?

Thanks!

**Comment by laceysanderson** [comment]
I think this was a mistake on our part... @spficklin there wasn't a reason to do this, was there?

**Comment by bradfordcondon** [comment]
@laceysanderson @spficklin any thoughts on this?  adding release blocker tag until question is resolved because seems pretty important fix.

**Comment by almasaeed2010** [comment]
I did a little investigation about this. When changing type_id to `bigint`, the operation succeeds but some content types break and produce the following error:

This error is for mRNA content types:
```
PDOException: SQLSTATE[22011]: Substring error: 7 ERROR: negative substring length not allowed: SELECT featureloc_id, srcname, srcfeature_id, strand, srctypename, typename, fmin, fmax, upstream, downstream, adjfmin, adjfmax, substring(residues from (cast(adjfmin as int4) + 1) for cast((upstream + (fmax - fmin) + downstream) as int4)) as residues, genus, species FROM ( SELECT FL.featureloc_id, OF.name srcname, FL.srcfeature_id, FL.strand, OCVT.name as srctypename, SCVT.name as typename, FL.fmin, FL.fmax, OO.genus, OO.species, CASE WHEN FL.strand >= 0 THEN CASE WHEN FL.fmin - :upstream <= 0 THEN 0 ELSE FL.fmin - :upstream END WHEN FL.strand < 0 THEN CASE WHEN FL.fmin - :downstream <= 0 THEN 0 ELSE FL.fmin - :downstream END END as adjfmin, CASE WHEN FL.strand >= 0 THEN CASE WHEN FL.fmax + :downstream > OF.seqlen THEN OF.seqlen ELSE FL.fmax + :downstream END WHEN FL.strand < 0 THEN CASE WHEN FL.fmax + :upstream > OF.seqlen THEN OF.seqlen ELSE FL.fmax + :upstream END END as adjfmax, CASE WHEN FL.strand >= 0 THEN CASE WHEN FL.fmin - :upstream <= 0 THEN FL.fmin ELSE :upstream END ELSE CASE WHEN FL.fmax + :upstream > OF.seqlen THEN OF.seqlen - FL.fmax ELSE :upstream END END as upstream, CASE WHEN FL.strand >= 0 THEN CASE WHEN FL.fmax + :downstream > OF.seqlen THEN OF.seqlen - FL.fmax ELSE :downstream END ELSE CASE WHEN FL.fmin - :downstream <= 0 THEN FL.fmin ELSE :downstream END END as downstream, OF.residues FROM chado.featureloc FL INNER JOIN chado.feature SF on FL.feature_id = SF.feature_id INNER JOIN chado.cvterm SCVT on SF.type_id = SCVT.cvterm_id INNER JOIN chado.feature OF on FL.srcfeature_id = OF.feature_id INNER JOIN chado.cvterm OCVT on OF.type_id = OCVT.cvterm_id INNER JOIN chado.organism OO on OF.organism_id = OO.organism_id WHERE SF.feature_id = :feature_id and NOT (OF.residues = '' or OF.residues IS NULL)) as tbl1 ; Array ( [:upstream] => 0 [:downstream] => 0 [:feature_id] => 191 ) in chado_query() (line 1704 of /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal_chado/api/tripal_chado.query.api.inc).
```

I suppose there is a reason for type_id to remain varchar.

**Comment by spficklin** [comment]
I'm not sure why it's  varchar... I think it should be a bigint as you suggest.   I'll work on a fix.

**Comment by laceysanderson** [comment]
Merged 👍

**Comment by Ferrisx4** [comment]
It looks like this change, and the database update `tripal_chado_update_7329` exposed the fact that one of our entries in that table has `''` (empty string) for `type_id` and is disallowing the update to be performed. This may shed light on why the column had previously been `varchar` (or at least why our site did not complain). However, I doubt it was ever intentional for this field to be an empty string and is some error specific to our site.

**Comment by bradfordcondon** [comment]
hi @Ferrisx4 : are you saying running the `update_db` was unsuccessful because you have a type_id with value `' '` ?  If so I'd suggest creating a fresh issue and we can modify the `update_db` to check for type_ids set this way, as you may not be the only site with that setup.

**Comment by Ferrisx4** [comment]
@bradfordcondon Yes, that is the exact case. I will create a new issue, thank you.
