### ISSUE TITLE
issues upgrading from chado 1.2 to 1.3

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#372]
### System information

* Tripal Version: 3
* Drupal Version:7.59
* PostgreSQL Version:9.3.20
* PHP Version:7.0.27

### Issue description

The chado upgrade process had several road blocks, all of which were from previous versions of chado.   
The instructions do warn that views will cause the upgrade to fail, i suppose.  This whole process is confusing since we dont really know what the state of our chado db is: chadoprop says 1.2 but we have a handful of tables from chado 1.3, all of which were empty.  More a problem of "whats going on with this db we inherited"...  I'm wondering if the tripal upgrader could make it a little smoother though.

* Many views in so are not dropped a the beggining of the 1.2 to 1.3 script, causing it to fial.  This includes, for example, `unorient_inter_transposition` which appears to be from 1.1.
* Public views had to be dropped.
* Deadlocks running upgrade.

I used this sql script to generate a drop script since there are 1600 so views.

```
set search_path=public,so,frange,genetic_code;
select 'drop view "' || viewname || '" cascade;' 
from pg_views where schemaname = 'so';
```

then we deleted the public views

```
drop view public.orgnasim;
drop view public.organism;
drop view public.cvterm;
drop view public.feature_ssr_mview;
```

@almasaeed2010 thinks these were custom-created by HWG, so not Tripal's problem.

We're still trying to work through the deadlock problem... we've disabled cron/ tripal jobs.

### discussion

* should default_schema-1.2-1.3-diff.sql also deal with tables created by 1.1?  It seems like that was our problem with the so views.

**Comment by bradfordcondon** [comment]
deadlock issue could be related to https://github.com/tripal/tripal/issues/278.  However that was `UPDATE variable SET` not alter

**Comment by almasaeed2010** [comment]
It appears that removing (commenting out) variable_set('chado_schema_exists')  lines in the chado_is_local() function resolves the deadlock issue.

**Comment by bradfordcondon** [comment]
while this issue resolved our dev site problem,  we are unable to upgrade chado on our live site.  Please see below error.




```
$ drush trp-run-jobs --username=hwadmin --root=/var/www/html

2018-06-04 10:09:40
Tripal Job Launcher
Running as user 'hwadmin'
-------------------
2018-06-04 10:09:40: There are 1 jobs queued.
2018-06-04 10:09:40: Calling: tripal_chado_install_chado(Upgrade Chado v1.2 to v1.3)
Checking for existing v1.3 tables in v1.2 and fixing bigints...
Incorporating additional changes...
Loading sites/all/modules/tripal/tripal_chado/chado_schema/default_schema-1.2-1.3-diff.sql...
WD tripal_chado: FAILED. Line  3443, 0                                                                                           [error]
SQLSTATE[40P01]: Deadlock detected: 7 ERROR:  deadlock detected
DETAIL:  Process 20554 waits for AccessExclusiveLock on relation 14142549 of database 14142031; blocked by process 21062.
Process 21062 waits for AccessShareLock on relation 14142179 of database 14142031; blocked by process 20554.
HINT:  See server log for query details.:
ALTER TABLE chadoprop
    ALTER chadoprop_id TYPE bigint,
    ALTER type_id TYPE bigint;

[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] FAILED. Line  3443, 0SQLSTATE[40P01]: Deadlock detected: 7 ERROR:  deadlock detectedDETAIL:  Process 20554 waits for AccessExclusiveLock on relation 14142549 of database 14142031; blocked by process 21062.Process 21062 waits for AccessShareLock on relation 14142179 of database 14142031; blocked by process 20554.HINT:  See server log for query details.:ALTER TABLE chadoprop     ALTER chadoprop_id TYPE bigint,    ALTER type_id TYPE bigint;
```

**Comment by bradfordcondon** [comment]
sorry to ping directly but being stuck on chado 1.2 on live is causing me a lot of problems.  Do you have any ideas @laceysanderson @spficklin for how to resolve this?  The best idea I could come up with was to break up the diff sql file into chunks and try running piecemeal...

I am thinking of making this a help desk issue, but @almasaeed2010 may not be able to make it Friday and he is such a better systems admin than me...

**Comment by childers** [comment]
Hi I am still running into this issue on our dev server.  I've been working with @Ferrisx4 and we are not sure why ths chado upgrade is still failing.

**Comment by Ferrisx4** [comment]
Additional notes on Chris' message:
I've been working on a mirrored version of the site on my own VM and on separate hardware and the upgrade process had gone smoothly past this step in both cases.

Chris is running Postgres v9.6 whereas I'm running v10.12 in the VM and v11.8 on the separate hardware.

**Comment by bradfordcondon** [comment]
@Ferrisx4 are you able to replicate the problem by running Postgres 9.6 (in your VM)?
