### ISSUE TITLE
Drupal Views undefined table: relation does not exist -- again...

### ISSUE THREAD

**Issue by oklonova** [tripal/tripal#374]
* Tripal Version: 2
* Drupal Version: 7.59

Hi,

there is a problem in defining views for searching in organism and feature tables. Search does not return any results. A message in the edit view page says "SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "organism" does not exist LINE 5: organism organism ^" (the same for "features"). The problem seems to be independent of the search machinery (whether it is the core search module or Search API).

This question has been asked elsewhere before, cf. [http://gmod.827538.n3.nabble.com/Drupal-Views-quot-feature-quot-does-not-exist-td4055951.html](url) and [http://gmod.827538.n3.nabble.com/Tripal-Views-Feature-Search-problems-after-update-from-Drupal-6-Tripal-1-1-td4052927.html](url).
Still, it does not help to apply the patch as it was recommended in these two cases. Where else can I look for the source of the problem?

Thanks in advance.

Best regards,
Olga

**Comment by mdondrup** [comment]
Hi Olga,

did you see this: https://github.com/tripal/tripal/issues/336 ?
Could you check if you have the most recent version of the patch, and did the patch command 
return any errors (failed hunks)?

Michael

**Comment by oklonova** [comment]
Hi, Michael,

thank you for the answer! I applied the patch from #336, with the following results:

sites/all/modules/views$ patch -p1 <  ../tripal/tripal_views/views-sql-compliant-three-tier-naming-1971160-30.patch
patching file includes/handlers.inc
Hunk #1 FAILED at 1637.
Hunk #2 FAILED at 1728.
2 out of 2 hunks FAILED -- saving rejects to file includes/handlers.inc.rej
patching file includes/view.inc
Hunk #1 succeeded at 239 with fuzz 1 (offset 37 lines).
Hunk #2 succeeded at 955 with fuzz 1 (offset 53 lines).
patching file plugins/views_plugin_query_default.inc
Hunk #1 FAILED at 1290.
1 out of 1 hunk FAILED -- saving rejects to file plugins/views_plugin_query_default.inc.rej

**Comment by laceysanderson** [comment]
Hi @oklonova,
That's definitely your problem then -that patch needs to apply cleanly in order for views to work with Chado. 

What version of Drupal Views do you have? The patch in #336 is meant for Views 3.19+ so if you have a lower version of views you should update.

**Comment by oklonova** [comment]
Thank you, the Views version is 3.20.

The problem is now solved - need to use curl to download the patch, and then use 
patch -p1 <  ./views-sql-compliant-three-tier-naming-1971160-30.patch

**Comment by laceysanderson** [comment]
I'm glad you got it to work 👍
