### ISSUE TITLE
overlay module incompatible with current version?

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#378]
The admin overlay module is causing some odd behavior on the current master branch.  This is with overlay v 7.59
Oddly enough I am only getting this in new installs (on our docker containers) not on our dev site.  Maybe someone can spin up a fresh site elsewhere and see if they can reproduce?

Trying to add new content takes me directly to bio_data/1 instead of bio_data.  The result is i can only add organisms, nothing else!  Disabling the module resolves the issue.  @almasaeed2010 suggests its a weird AJAX issue?

https://github.com/statonlab/docker-containers/issues/12#issuecomment-391493184

**Comment by almasaeed2010** [comment]
I installed a new site on my mac and the issue is not happening. It could be an interference from some other module that we have enabled on the docker container. I'll keep adding modules and testing as we go.

**Comment by laceysanderson** [comment]
Were you able to get to the cause of this?

**Comment by bradfordcondon** [comment]
No.  seems like its a bug unrelated to Tripal and instead something wrong with our docker setup.  The discussion is there at https://github.com/statonlab/docker-containers/issues/12
