### ISSUE TITLE
Docs: Tripal Daemon Documentation

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#387]
We need better documentation for how to install and use the Tripal Daemon on the Tripal v3 User's Guide. Right now new users have to traverse multiple sites to figure it out.

**Comment by laceysanderson** [comment]
Added to the upgrade Docs (`http://tripal.info/node/269`):

> (Optional but Recommended) Tripal Daemon (provides automatic job execution) is now part of the main Tripal. To use it, first enable the module,
>
>  `drush pm-enable tripal_daemon`
>    - NOTE: If you had Tripal Daemon installed with Tripal 2, first disable the module and remove the module directory.
>    - The Tripal Daemon runs in the background, checking periodically for Tripal Jobs and running them once found.
>    - Start the daemon using the following command. For more information about using the Daemon, see the [Jobs Management section](http://tripal.info/tutorials/v3.x/tripal-daemon).
>
> `drush trpjob-daemon start`

Added the contents of the README to http://tripal.info/tutorials/v3.x/tripal-daemon. This is still not ideal but it's a start...

**Comment by laceysanderson** [comment]
Also need to add information here: http://tripal.info/tutorials/v3.x/installation/job-automation.

**Comment by laceysanderson** [comment]
Also need to add it to the user tutorial so no one needs to run the tripal jobs command manually

**Comment by kyrenya** [comment]
hi! I'm trying to use the tripal_blast module, and actually got stuck in the tripal_daemon documentation. 
I get this message 
The Drush Daemon API module requires the PHP-Daemon library v2.0 (Download) Please install it as per the Libraries API Instructions before trying again. (Currently using PHP Daemon Not Installed)

but I cannot figure out how to install the library needed. 
when I do 
l$ drush pm-download Libraries
No release history was found for the requested project (Libraries).                   [error]
Could not download requested project(s).                                              [error]

Any help? 
Thanks in advance!

**Comment by laceysanderson** [comment]
Hi @kyrenya,

I think it's a matter of case sensitivity for your drush command as the following works for me: 
```
drush pm-download libraries
drush pm-enable libraries
```

**Comment by kyrenya** [comment]
yep, oops, I was copy-pasting and I didn't pay attention to that, thanks!

**Comment by laceysanderson** [comment]
Glad it works for you now! I updated the docs with the fix -thank you for bringing it  to our attention!

**Comment by eglabmsu** [comment]
I had trouble with the line
`mv v2.0.tar.gz PHP-Daemon`
in the Job Management instructions.

What worked for me was 
`mv PHP-Daemon-2.0 PHP-Daemon`

**Comment by spficklin** [comment]
Tripal Daemon is so important to Tripal v3 we really need the docs for it here:  https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/automating_job_execution.html

**Comment by laceysanderson** [comment]
Closing this as it's now outdated with the move to Tripal 4.
