### ISSUE TITLE
chado property fields attach load undefined property warning

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#389]
### System information

* Tripal Version: 7.x-3.x
* Drupal Version: 7.58
* PostgreSQL Version: 9.6.1
* PHP Version: 7.1.14

### Issue description

Chado property fields give this error when null

```
Notice: Undefined property: TripalEntity::$tripal__ena_last_update in TripalEntityController->attachLoad() (line 658 of /var/www/html/sites/all/modules/custom/tripal/tripal/includes/TripalEntityController.inc).
```

You can see this on my "data seeded" tripal 3 docker https://hub.docker.com/r/statonlab/tripal3_seeded/ by visiting a biomaterial page.  These property fields were generated automagically by clicking "check for new fields".

Chado properties created manually (via the structure -> fields) as well as those "discovered" via check for new fields have this warning.

**Comment by laceysanderson** [comment]
Can you describe this a little more? What do you mean by null... when the field is empty?

**Comment by bradfordcondon** [comment]
yes.  So creating a new chado property field in the UI, attaching it, and visiting an entity of that content type will give the warning because its empty.

**Comment by laceysanderson** [comment]
Hmmm... I'm unable to duplicate this. 

I added a chado property of type `tripal:analysis_blast_blastdb` to my organism content type. I confirmed that I have no properties in the db of that type. Then I navigated to an organism page (Lens culinaris actually :-)) and did not see an error. I also checked the edit page and the Drupal watchdog logs :-( I even tried clearning the cache a couple of times to see if that helped --no dice.

**Comment by bradfordcondon** [comment]
When visiting an organism page:

```
Notice: Undefined property: TripalEntity::$local__lineage in TripalEntityController->attachLoad() (line 658 of /data/www/html/hardwoods_dev/drupal-7.52/sites/all/modules/tripal/tripal/includes/TripalEntityController.inc).
Notice: Undefined property: TripalEntity::$local__division in TripalEntityController->attachLoad() (line 658 of /data/www/html/hardwoods_dev/drupal-7.52/sites/all/modules/tripal/tripal/includes/TripalEntityController.inc).
Notice: Undefined property: TripalEntity::$local__mitochondrial_genetic_cod in TripalEntityController->attachLoad() (line 658 of /data/www/html/hardwoods_dev/drupal-7.52/sites/all/modules/tripal/tripal/includes/TripalEntityController.inc).
Notice: Undefined property: TripalEntity::$local__genetic_code_name in TripalEntityController->attachLoad() (line 658 of /data/www/html/hardwoods_dev/drupal-7.52/sites/all/modules/tripal/tripal/includes/TripalEntityController.inc).
Notice: Undefined property: TripalEntity::$local__genetic_code in TripalEntityController->attachLoad() (line 658 of /data/www/html/hardwoods_dev/drupal-7.52/sites/all/modules/tripal/tripal/includes/TripalEntityController.inc).
```

These are all tripal fields for organisms that dont have them set (because the NCBI taxon loader wasnt used)....

**Comment by bradfordcondon** [comment]
the fix was so small that i made a PR despite you not being able to reproduce....

**Comment by bradfordcondon** [comment]
from @spficklin in PR:

>I was able to duplicate this bug and this PR does fix it. The source of the problem is in the chado_linker__prop.load() function. At the end if the property does not exist then it manually removes the field from the $entity object. This is the only field that does this and it's a hack to keep the property key from showing up in the TOC on the page when no properties are actually present. I think the fix is fine and while we should probably dig into why we had to put that adjustment in the load() function of the chdao_linker__prop field, this fix corrects the problem and makes the Entity controller more robust.

With the merge I'm going to close, despite Stephen hinting that we might need to think about the linker__prop field more (we can do so by reopening or new issue).
