### ISSUE TITLE
Cleanup unused branches

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#391]
We have a plethora of branches on this project.  Many can be removed.  Here's a checklist of them all. If you know that a branch can be removed can you please comment here so we can clean them up, or if the branch is yours remove it and check the box below.

 - [x]  103-tripal-daemon
- [x]   208-excessive_cron
- [ ]   342-search_api_tripal_collections_handler
- [x]   7.x-1.x-orig
- [x]   7.x-2.x-2694427-chado_v13
- [x]   7.x-2.x-ds
- [ ]   7.x-2.x-issue-253
- [x]   7.x-2.x-obo
- [x]   7.x-2.x-phylogeny
- [x]   7.x-2.x-ws
- [x]   7.x-3.x-GO
- [x]   7.x-3.x-api-docs
- [x]   7.x-3.x-caching
- [x]   7.x-3.x-collections
- [x]   7.x-3.x-dashboard
- [x]   7.x-3.x-entity-crud-api
- [x]   7.x-3.x-files_management
- [x]   7.x-3.x-fixed-cv-admin
- [x]   7.x-3.x-installprofile
- [x]   7.x-3.x-issue-141
- [x]   7.x-3.x-issue-305
- [x]   7.x-3.x-issue-341
- [ ]   7.x-3.x-issue-354
- [x]   7.x-3.x-layout
- [x]   7.x-3.x-oboproblem
- [ ]   7.x-3.x-pull-379
- [x]   7.x-3.x-remotedata
- [x]   7.x-3.x-small_fixes
- [x]   7.x-3.x_cvalue_prop_support_for_field
- [x]   LegumeFederation-multijobs
- [x]   add-license-1
- [x]   chadoprops-norender-whenempty
- [x]   collections
- [x]   fix-deprecated
- [x]   issue253
- [x]   paired-upload
- [x]   pr/252
- [x]   tripal-7.x-3.x-ws_classes

**Comment by bradfordcondon** [comment]
Cleaned up mine.  Other people's that i did not delete but most look deletable based on staleness and not having commits ahead of master, only commits behind ( see image):


![screen shot 2018-05-25 at 4 42 13 pm](https://user-images.githubusercontent.com/7063154/40565435-9cb897fc-603a-11e8-8c9f-7ab06b18e1d0.png)

**Comment by laceysanderson** [comment]
Cleaned up mine :-) 👍 

PS. This list really helped as it mentioned which of my branches had been merged :-) https://github.com/tripal/tripal/branches/yours

**Comment by spficklin** [comment]
That was a very helpful link @laceysanderson .  Thanks.  Also, do you think we need to keep the 7.x-1.x-orig branch?

**Comment by laceysanderson** [comment]
I don't know? I tried to find it in the network graph but it's too old 😝 It's likely safe to remove...

**Comment by shawnawsu** [comment]
Cleaned up the final stragglers of mine.

**Comment by bradfordcondon** [comment]
nice!  FInal unchecked boxes I think have been deleted, these are our remaining branches, which are all active issues, or not on @spficklin 's list.

![screen shot 2018-06-01 at 8 35 29 am](https://user-images.githubusercontent.com/7063154/40840952-c3cf718a-6576-11e8-9281-1a815297ccf8.png)


do we need those stale branches ie `6.x-dev` ?  Other than that I think we can close this out.

**Comment by spficklin** [comment]
Awesome. Thanks folks!  Closing this issue.
