### ISSUE TITLE
git flow

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#392]
This thread is for discussion of branches and git flow.

If you aren't familiar with [Git flow, read this!](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)

Why do we want to discuss this?  We want to buffer live sites from issue development a little bit, particularly as we are granting more people write access.  We have at least two non-exclusive options:

* create more releases.  We expect live sites are running these releases and not the master branch. 
* create a dev branch.  Live sites run a production branch, and we merge into/branch out of the dev branch.  When we merge from dev to live, we create a release.

**Comment by bradfordcondon** [comment]
mightt be interesting to see Drupal's own discussion of [switching to Git flow](https://www.drupal.org/project/pm/issues/2467159).  On that note im curious if Drupal has guidelines or suggestions...

**Comment by shawnawsu** [comment]
I use Git Flow with other projects and it works well for production management so I think it's a good idea. But I did bring this (not Git Flow specifically but Release Schedules) up in a previous user meeting and there didn't seem to be much enthusiasm for it.

**Comment by bradfordcondon** [comment]
Given the lack of discussion I agree with Shawna that without interest this isn't happening.  Closing for now.
