### ISSUE TITLE
error in applying patches "views-sql-compliant-three-tier-naming-1971160-22.patch"

### ISSUE THREAD

**Issue by dedenmatra** [tripal/tripal#397]
### System information

* Tripal Version: 2
* Drupal Version: 7.59
* PostgreSQL Version: 9.5.12
* PHP Version:7.0.30

### Issue description

I tried to install tripal v.2 manually, but when applying patches of views-sql-compliant-three-tier-naming-1971160-22.patch, occurred error, that attached below :

```
PHP Fatal error:  Cannot redeclare view::$search_path in /var/www/vhosts/rujakbase.agrohort.ipb.ac.id/httpdocs/rujakbase/sites/all/modules/views/includes/view.inc on line 244
Drush command terminated abnormally due to an unrecoverable error.                                                              [error]
Error: Cannot redeclare view::$search_path in
/var/www/vhosts/rujakbase.agrohort.ipb.ac.id/httpdocs/rujakbase/sites/all/modules/views/includes/view.inc, line 244
root@rujakbase:/var/www/vhosts/rujakbase.agrohort.ipb.ac.id/httpdocs/rujakbase# drush pm-enable tripal_core
```

**Comment by spficklin** [comment]
Hi @dedenmatra .  There is a new patch that superceeds the one you used. It is named **views-sql-compliant-three-tier-naming-1971160-30.patch** and is found in the Tripal v2 files in the same location as the one you used.  It seems we failed to update the online documentation to use this patch.   So, if you were following those instructions this would be the problem.  I have updated the online documentation.  

To fix this, I would recommend you re-download the view module and try to patch it new.  You can do so with these commands:

```
drush pm-download views
cd /var/www/html/sites/all/modules/views
patch -p1 < ../tripal/tripal_views/views-sql-compliant-three-tier-naming-1971160-30.patch

```
The drush command will ask if you want to overwrite the existing views module and you should do so.

Let us know if this fixes it for you.

**Comment by dedenmatra** [comment]
I tried to apply the coding that you suggest, but errors statement occurred again.

before apply this command, I was disable and remove all modules including views and tripal. and tried new download
```
-----
root@rujakbase:/var/www/vhosts/rujakbase.agrohort.ipb.ac.id/httpdocs/rujakbase/sites/all/modules/views# patch -p1 < ../tripal/tripal_views/views-sql-compliant-three-tier-naming-1971160-30.patch
patching file includes/handlers.inc
Hunk #1 succeeded at 1729 (offset 92 lines).
Hunk #2 succeeded at 1842 (offset 104 lines).
patching file includes/view.inc
Hunk #1 succeeded at 234 with fuzz 1 (offset 32 lines).
Hunk #2 succeeded at 944 (offset 42 lines).
patching file plugins/views_plugin_query_default.inc
Hunk #1 FAILED at 1290.
1 out of 1 hunk FAILED -- saving rejects to file plugins/views_plugin_query_default.inc.rej
```

**Comment by bradfordcondon** [comment]
hi @dedenmatra sorry for the lack of response on this.  Were you able to make any progress?

**Comment by kyrenya** [comment]
hi, I'm exactly at the same point... did you manage to fix this? Thanks

**Comment by laceysanderson** [comment]
Hi @kyrenya, were you able to get this working? I just checked the Tripal 7.x-2.x version of the patch and it applied for me. Can you post your terminal output?

It appears the Tripal 2 documentation has been updated to [specify the correct patch](http://tripal.info/tutorials/v2.x/installation/tripal). As such I'm removing the "Documentation" tag. Was there anywhere else in needed to be fixed @bradfordcondon?

**Comment by kyrenya** [comment]
hi! yes! I found this: 
https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado_views/views-sql-compliant-three-tier-naming-1971160-30.patch
It's a newer version than the one I had apparently, as I didnt know how to download it, I just copied the code in a new file, and it worked :)

**Comment by laceysanderson** [comment]
Ok good :-) That patch is available in Tripal 2 as well: https://github.com/tripal/tripal/blob/7.x-2.x/tripal_views/views-sql-compliant-three-tier-naming-1971160-30.patch. Which version of Tripal2 are you using?

**Comment by kyrenya** [comment]
After patching, the menu 'tripal' didnt appear in my server, but I found this: 

drush pm-enable toolbar
drush pm-enable shortcut

(from https://tripal.info/tutorials/v2.x/upgrade_6.11_to_2.0), I was not upgrading, but installing from scratch, but anyway, once I did it, I was able to see the Tripal Menu in the localhost

**Comment by laceysanderson** [comment]
I haven't experienced that myself but clearing the cache should also have worked

**Comment by spficklin** [comment]
That's a bit bizarre that you had to enable those modules.  They are typically enabled by default when installing Drupal for the first time.  So, am I understanding correctly that the admin menu was there, you patched and then it disappeared?

**Comment by kyrenya** [comment]
nop, the menu was not there. I made this installation, 
https://tripal.info/tutorials/v2.x/installation/tripal
got the patch issues, 
solved them as explained before, 
but then couldnt see the Tripal Menu as expected and shown in this tutorial, 
so I tried the commands above, and then I saw it. 
it was a bit weird for me, but it worked, so I moved on :)

**Comment by spficklin** [comment]
I believe this is resolved.  I'm closing but please comment if there are further issues.
