### ISSUE TITLE
bulk loader template  help

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#401]
### System information

* Tripal Version: 7.x-3.x
* PHP: 7.1.14
* Postgres: 9.6.1

### Issue description

I'm modifying a bulk loader template.  I want to get the organism_id from feature X (parent feature in the image) that exists in the db, and use it to insert for feature Y.  I'm reasonably certain the below setup allows this?

![screen shot 2018-05-31 at 5 10 57 pm](https://user-images.githubusercontent.com/7063154/40808606-bbe77d36-64f5-11e8-80cb-3f334a432ae1.png)

However, after pressing save changes and reopening the field config, this is the configuration

![screen shot 2018-05-31 at 5 12 33 pm](https://user-images.githubusercontent.com/7063154/40808646-d4a35c0a-64f5-11e8-89c9-652de6b68217.png)

edit: i thought this was the reason for my loader failing, but it isnt.  the configuration does in facf get saved, it just doesnt get re-loaded as the default when you re-edit the field.

**Comment by bradfordcondon** [comment]
Looks like the data actually is collected by the form, it just doesnt get loaded as the default.

Minor annoyance at best, apologies.

Still not sure why this loader doesnt want ot work though :P

**Comment by bradfordcondon** [comment]
I'm abandoning the loader for a variety of reasons.  This issue is so minor it doesn't need an issue, although it could be fixed.

Closing.

**Comment by laceysanderson** [comment]
Could you add the reasons here so that one day when I find time to work on the module I can take them into consideration to make it better?

**Comment by bradfordcondon** [comment]
* Testing.  It's much easier to test the importer because I can do so via Tripal Test Suite.  I think we can figure out how to allow testing via cli but would take some thought.
* I eventually got the loader to a state where it looked right to me, but failed with no informative error message.
* I needed to insert feature positions, which meant creating a featuremap for all of the records in the loading job.  ( the loader currently added them as feature props).

At that last point, I knew for sure it would take me longer to understand the bulk loader than to code an importer from the ground up.  I don't think its a feature shortcoming ( I bet its possible with teh bulk loader, the bulk loader is great) .

**Comment by spficklin** [comment]
If you want to share your loader template and a sample data file, and we can check to see if it's a bug or needs changes to the setup.

**Comment by bradfordcondon** [comment]
i dont think its worth anyone's time to do so.

In the case you disagree with me:


https://github.com/statonlab/tripal_ssr/blob/9a39dabc37349aaa8cfa96b3d33750e8c789e5a8/tripal_ssr.install#L185

this template is trying to load the start/stop as featureprops, which isnt ideal and is something I will change in the importer.  Advanced bulk-loader setup would be to use `featureloc` instead.

**Comment by spficklin** [comment]
Right, okay, re-closing.
