### ISSUE TITLE
module collaboration marketplace and showcase

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#402]
In [today's meeting](https://docs.google.com/document/d/1sLJm2ugd5JVAI3_Ggbc15JJm9zjgnZV1wnUSjBWWukM/edit?ts=5b115cbb#) we talked about ways to improve collaboration.   We'll discuss more next month about what makes collaborations successful (thanks @ekcannon !)

One of the offshoots of the initial discussion is the idea of a curated module list.  This already exists on tripal.info, to some extent, but it requires people keep it up to date, which is hard.  Think of it as a community engagement portal, a module showcase/marketplace.    Some ideas...

* what sites use what modules?
* what modules are actively seeking collaboration?
* what modules deal with what sort of data?
* Filter could include the lead on the project
* tag modules that want collaborators, users, new maintainer/projecet lead...
* can we use github api to keep a list of modules tagged with tripal for autodiscovery/maintenance?
* It would be nice to have a listing of the Tripal sites and which modules each site uses. 

What do we think of this idea?

Where would we host it?

How can we maximize its utility while minimizing the work that goes into it?

**Comment by bradfordcondon** [comment]
I'm thinking of doing a writeup for each of my modules.  2 sentences and a screenshot: what does it do, a shot of it in action on HWG.  Then I'll say I welcome collaboration, input, users, feature requests, whatever.

This is what i imagine in an ideal world: something not unlike tripal.info where each module is an entity thats searchable/filterable, maybe a random module is pulled and highlighted on the front page (like how agbiodata has the site cards you can flip through)... but i recognize that's maybe ad odds with the idea of a curated list.

**Comment by spficklin** [comment]
What if we go more simple and just have a table of modules with the module name, brief description, Tripal compatibility (e.g. Tv2 or Tv3 or both), and a link to the repository?  That way it's not too much work for us to maintain on the tripal.info site.

**Comment by bradfordcondon** [comment]
That could work, but is it so much better than someone searching github tags for Tripal?  We could have a direct link to this search on tripal.info and the repo...

I do think a picture is worth a thousand words in terms of showing others what functionality the module brings to the site.

I'd also love to keep it somewhere that anyone can contribute so others can update as they like when we inevitably fall behind...


[I made a showcase repo for my modules](https://github.com/bradfordcondon/condon_tripal_showcase).  I still want to add a picture per repo...

**Comment by bradfordcondon** [comment]
I threw together a github pages for the repo.

https://statonlab.github.io/hardwoods_tripal_showcase/

It wouldnt be so bad to add some badges or categories... and improve the styling (fixed size cards for starters)
<img width="1433" alt="screen shot 2018-06-03 at 10 20 59 pm" src="https://user-images.githubusercontent.com/7063154/40895284-6d14ca9a-677c-11e8-8ca8-43ace9b125d5.png">

Its not too hard for others to contribute (you go to the repo and add a markdown file per module you want to share, and add the image) although using a proper CMS would be easier.  And just having a table would be even easier of course :)

**Comment by bradfordcondon** [comment]
so, the showcase is available for others who want it.  We don't want it for Tripal.

Instead i'm hearing that we should just link the tripal to the [github tripal topics search ](https://github.com/topics/tripal) on tripal.info and this README.

**Comment by laceysanderson** [comment]
I would like to put this to a pmc-vote:

### Proposition: 
Replace [Extensions](http://tripal.info/extensions) menu item with a link to [Github search for Tripal tag](https://github.com/search?q=topic%3Atripal).

### Pros 
- No maintenance needed for Tripal PMC. 
- Helpful to users by providing full details, README's downloads, etc. for each module
- Nice for module developers since they just need to add a tag to be in the list
- Module developers can completely customize the information available.

### Cons
- Only supports projects on GutHub (not GitLab)
- Takes admin outside of Tripal.info so not a continuous UX
- no image shown in the search so may be a little overwhelming
- additional filters (e.g. Tripal/Drupal version compatible with) is difficult and requires adherence to standards for included modules.

### My Vote:
**I vote in favour** this proposition since it provides a maintainable solution with very little effort. I would like to use the GutHub API in the future to move the search back to tripal.info while continuing to pull from github.

**Comment by ekcannon** [comment]
Not on PMC, but I agree with this proposal, in part because keeping descriptions and documentation up to date in two places is challenging. It's better to put these efforts into GitHub only.

**Comment by bradfordcondon** [comment]
@spficklin suggested having an extensions module section on the RTD site. 
Here's what such a page would look like:

![screen shot 2018-11-13 at 5 22 46 pm](https://user-images.githubusercontent.com/7063154/48447695-98265a00-e76a-11e8-8ab1-7efdb0e8307b.png)
 

https://github.com/tripal/tripal/blob/docs_extensions_page/docs/extensions.rst

(I'll build on RTD once it refreshes and update this post...)

### Pro

* summaries are searchable, so users might find what they need in an extension searching the docs
* new additions are visible to community via PR. Releasing a module includes making a PR to core, so hey, everyone will see it!

### Cons

* Harder to maintain than just linking to the github tag



PS stephen has suggested splitting the docs into multiple files by topic which is fine and we can do if we like this approach more...

**Comment by laceysanderson** [comment]
I Really like the RTD idea but also still feel attached to the ease of the github link. Can we compromise by having both? 

I would be tempted to have something very similar to @bradfordcondon's mockup requiring module maintainers to include the general description, repo link and docs link (could just link to readme if that's all they have) and then have a final section like "Explore Github" which mentions that the module they are looking for may already be underdevelopment and that they can search github [here](https://github.com/search?q=topic%3Atripal) for Tripal-related modules.

**Comment by ekcannon** [comment]
RTD? It's kind to spell out acronyms. ;-)

**Comment by bradfordcondon** [comment]
oops sorry ethy :P . read the docs, its the documentation packaged with the code that gets built at https://tripal.readthedocs.io/en/latest/

**Comment by spficklin** [comment]
I vote to include both the short description + link to doc + link to module and the link to all modules with the tripal tag in GitHub.

**Comment by laceysanderson** [comment]
As implied above, I also vote for both the Readthedocs (RTD) implementation while keeping the link to the Github topic for module maintainers who don't create the PR.

Specifically, the RTD implementation should have

> short description + link to doc + link to module and the link to all modules with the tripal tag in GitHub.

(same as Stephen)

**Comment by bradfordcondon** [comment]
i built that branch (420_rtd) on the live readhtedocs.  you can preview it here
https://tripal.readthedocs.io/en/402_rtd_module_list/extensions.html

I have a commented template at the start.  Just edit it to however you'd like I'm ok with what you all specified.

**Comment by laceysanderson** [comment]
Great, thanks @bradfordcondon! I'll work on including all my modules on that branch as well and update the template to that agreed here.

**Comment by laceysanderson** [comment]
Ok, I've added all Tripal3 compatible modules from:
 - github.com/tripal
 - tripal.info/extensions
 - UofS-Pulse-Binfo modules which should have been on tripal.info 🙃 

Additionally, I did a small amount of themeing and expanded categories.

### Are we content with the following categories?
![screen shot 2018-11-14 at 9 46 07 pm](https://user-images.githubusercontent.com/1566301/48528995-d8fb9d00-e856-11e8-98e2-d8f2bfc0adbb.png)
Please check out the current version here: https://tripal.readthedocs.io/en/402_rtd_module_list/extensions.html

**Comment by spficklin** [comment]
I have replaced the Extensions link on the tripal.info file to the page in the documentation where Extension modules are now listed.
