### ISSUE TITLE
Migrating to Tripal 3.  The "prepare chado" step is optional or not-optional?

### ISSUE THREAD

**Issue by isumoc** [tripal/tripal#405]
### System information
* Tripal Version: 2.x -> 3.x ( tripal 3.x via git )
* Drupal Version: 7.x
* PostgreSQL Version: 9.x
* PHP Version: 7.1

### Issue description
I'm going through some migrations from 2.x -> 3.x.  I don't believe you can "skip" the prepare chado step if you had a previous Tripal installation. It has previously broken my migration attempts.

Can anyone verify this ?  I can submit a PR but I'm not certain who if anyone can actually skip it.

The option presented to users is below:

<img src="https://i.imgur.com/CYtoEyG.png">

**Comment by spficklin** [comment]
Hi @isumoc yes, you have to run it during the upgrade.  You really shouldn't skip it.  Can you provide any error messages you are getting when you try the upgrade?

**Comment by bradfordcondon** [comment]
I think you're saying the skip button shouldnt exist?
Or, Tripal sites can't skip it, but the text implies they can?

**Comment by isumoc** [comment]
No error messages.  I am just curious why the option of "skip" is here at all.  When I was first migrating I "skipped" it because I was following the instruction - and skipping borked my upgrade from Tripal 2.x to 3.x.

The text of the paragraph says "If you are upgrading from a previous version of Tripal, you do NOT need to prepare your site.

Can we either remove the "skip" option or change the paragraph to let people know who can actually skip the prepare step ?

**Comment by spficklin** [comment]
Yes, we should change the paragraph.  Those instructions were created very early on and things have since changed but the instructions have not. I'll make that change.  Thanks for pointing it out!  I will also remove the skip button.

**Comment by bradfordcondon** [comment]
merged, closing, thank you :)
