### ISSUE TITLE
Chado tables missing ontology terms

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#407]
This issue is meant as a place holder until all tables in Chado have vocabulary terms associated with every table.  This way Chado will be 100% supported by Tripal v3.  

This issue is being created initially for the protocol, assay and arraydesign tables for PR #398. Once those fixes are made then I will post a list of tables that remain.

**Comment by spficklin** [comment]
These tables are missing vocabulary assignments

- [ ] **analysisfeature**
- [ ] **analysisfeatureprop**
- [ ] **biomaterial_treatment**
- [ ] **cell_line_cvtermprop** (cell_line_cvterm_id)
- [ ] **cell_lineprop_pub** (cell_lineprop_id)
- [ ] **control** (tableinfo_id, row_id)
- [ ] **cvterm** (is_relationshiptype)
- [ ] **cvterm_dbxref** (is_for_definition)
- [ ] **cvtermpath** (pathdistance)
- [ ] **db** (urlprefix)
- [ ] **eimage**
- [ ] **elementresult**
- [ ] **environment_cvterm** (environment_id)
- [ ] **expression_cvterm** (cvterm_type_id)
- [ ] **expression_cvtermprop** (expression_cvterm_id)
- [ ] **feature_cvterm_dbxref** (feature_cvterm_id)
- [ ] **feature_cvterm_pub** (feature_cvterm_id)
- [ ] **feature_cvterm_prop** (feature_cvterm_id)
- [ ] **feature_expressionprop** (feature_expression_id)
- [ ] **feature_genotype** (chromsome_id, cgroup)
- [ ] **feature_pubprop** (feature_pub_id)
- [ ] **feature_relationship_pub** (feature_relationship_id)
- [ ] **feature_relationshipprop** (feature_relationship_id)
- [ ] **feature_relationshipprop_pub** (feature_relationshipprop_id)
- [ ] **featureloc**
- [ ] **featureloc_pub** (featureloc_id)
- [ ] **featureposprop** (featurepos_id)
- [ ] **featureprop_pub** (featureprop_id)
- [ ] **featurerange**
- [ ] **libraryexpressionprop** (library_expression_id)
- [ ] **libraryfeatureprop** (library_feature_id)
- [ ] **library_relationship_pub** (library_relationship_id)
- [ ] **libraryprop_pub** (libraryprop_id)
- [ ] **magedocumentation**
- [ ] **mageml**
- [ ] **all nd_xx tables** (nd_experiment_id)
- [ ] **nd_geolocation**
- [ ] **organism_cvtermprop** (organism_cvterm_id)
- [ ] **organismprop_pub** (organismprop_id)
- [ ] **phenotype** (observable_id, attr_id, cvalue_id)
- [ ] **phenotype_comparison**
- [ ] **phenotype_comparison_cvterm** (phenotype_comparision_id)
- [ ] **phylonde**
- [ ] **project_stock** (stock_id)
- [ ] **protocolparam**
- [ ] **pubauthor**
- [ ] **pubauthor_contact** (pubauthor_id)
- [ ] **quantificationprop** (quantification_id)
- [ ] **all stock tables** (stock_id)
- [ ] **all stockcollection tables** (stockcollection_id)
- [ ] **studyfactorvalue** (studyfactor_id)
- [ ] **studyprop_feature** (studyprop_id)
- [ ] **synonym** (synonym_sgml)

**Comment by bradfordcondon** [comment]
related to #441

**Comment by spficklin** [comment]
I'm going to take this off of a release blocker. we can add updates to a later release.

**Comment by bradfordcondon** [comment]
do we actually want a unique term for each table?

Linker tables, for example, are a base type which has a term (featureloc), and then the linker field provides the second term (featurelocpub)

Also prop is a weird one. In that case, the field providing the cvterm is specifc for each prop, it isnt table-wide.

Base tables yeah we should get a term for each base table.

**Comment by spficklin** [comment]
I'm going to close this out.  When we do the Chado and the Semantic Web paper we will have to visit every Chado table and get any with missing terms resolved.  I agree with @bradfordcondon that we probably don't want a term for tables.
