### ISSUE TITLE
Entities with data in chado.stock table are given an invalid title by default.

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#41]
There's a bug in setting the default title for an entity where the data is stored in the chado.stock table. Currently it's assigned `[stock__name]` which is not a valid token resulting in an empty title for published entities. It should be assigning `[schema__name]` which is the equivalent.

**Comment by spficklin** [comment]
Oh, dump oversight on our part.  Thanks for noticing.  Fixed in the code. It's such a simple fix I'm assuming the behavior is corrected.  But if not please reopen.
