### ISSUE TITLE
OBO loader fails on plant trait ontology

### ISSUE THREAD

**Issue by shawnawsu** [tripal/tripal#411]
The plant trait ontology, https://raw.githubusercontent.com/Planteome/plant-trait-ontology/master/to.obo, is not loading because of it's structure: 

```
[Term]
id: BFO:0000017 ! realizable entity
is_a: BFO:0000020 ! specifically dependent continuant
```

**Comment by srobb1** [comment]
I wonder if it is not loading because it is missing a "name:" field. I think name is required.
