### ISSUE TITLE
TripalImporter doesn't allow class form elements to preceed file upload element.

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#416]
### System information

* Tripal Version: 7.x-3.x dev
* Drupal Version: 7.59

### Expected Functionality
Setting the `#weight` on a form element provided via a custom TripalImporter class should allow the developer to control the order of the form elements on the import form including placing custom form elements above the file import fieldset.

### Issue description
Currently the TripalImporter form groups all the form elements provided by the custom class:
https://github.com/tripal/tripal/blob/7.x-3.x/tripal/includes/tripal.importer.inc#L99
```php
  $importer = new $class();
  $element = array();
  $form['class_elements'] = $importer->form($element, $form_state);
```

This causes any `#weight` attributes set on the custom form elements to only apply to ordering each other and ensures the file upload is always at the top. 

For example, with the new Tripal BibTeX importer we wanted to have some explanation text at the top of the page before the file upload. Thus we set the `#weight => -100` but still the form looks like this:
![screen shot 2018-06-06 at 9 14 04 pm](https://user-images.githubusercontent.com/1566301/41076385-93ebdfba-69ce-11e8-92df-c8f3aff6f01a.png)

### Possible Solutions
There are two possible solutions:
1. Pass the full form into the importer class.
```php
  $importer = new $class();
  $form = $importer->form($element, $form_state);
```
This allows the developer full control over the form and provides them context. However, they could unset the file upload element or parts of the element... too much control could be dangerous :shrugs:

2. Use array merge so that custom form elements are on the base level.
```php
    $importer = new $class();
    $element = array();
    $element = $importer->form($element, $form_state);
    $form = array_merge($form, $element);
```
This still allows the developer to control the order of the elements but ensures that the file upload and analysis fields are left untouched.

I prefer solution 1 since it provides the most control to the developer creating a custom importer. Either way we're going to want to set a fairly light weight (`-15`) to the file upload and analysis form elements to help them stay at the top by default.

Thoughts? @spficklin is there a reason the custom form elements were grouped that I'm missing?

**Comment by spficklin** [comment]
I don't remember a reason for this line of code where the importer's form is added under a 'class_elements' item to the form:
```
  $form['class_elements'] = $importer->form($element, $form_state);
```
I am okay with an array_merge.

**Comment by laceysanderson** [comment]
Awesome :-) I’ll submit a PR in the morning.

**Comment by bradfordcondon** [comment]
pr merged so closing.
