### ISSUE TITLE
Errors when editing Publication field on Organism Entity.

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#42]
You see the following errors at the top of the page when editing the Publication field (Home » Administration » Structure » Tripal Content Types » Organism » Manage fields):

```
Notice: Undefined index: #entity in schema__publication_widget->form() (line 16 of /var/www/XXX/sites/all/modules/tripal/tripal_chado/includes/TripalFields/schema__publication/schema__publication_widget.inc).
Notice: Trying to get property of non-object in schema__publication_widget->form() (line 29 of /var/www/XXX/sites/all/modules/tripal/tripal_chado/includes/TripalFields/schema__publication/schema__publication_widget.inc).
```

**Comment by spficklin** [comment]
This does not appear to a problem in the current 7.x-3.x branch.   I do not see it so I assume its fixed.  Please reopen if you still do.

**Comment by laceysanderson** [comment]
I'm still seeing these errors even after I update the code, the database and deleted/re-added the field as suggested for the relationship in #44. I'll look into it further.

**Comment by laceysanderson** [comment]
Now this is fixed :-)
