### ISSUE TITLE
issue template types

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#420]
Issue templates: we can [have multiple templates](https://blog.github.com/2018-01-25-multiple-issue-and-pull-request-templates/)!  To demonstrate, I added them to my WHG issue repo.  When you press the "new issue" button, this is what it now looks like:

![screen shot 2018-06-08 at 9 49 03 am](https://user-images.githubusercontent.com/7063154/41161640-89a6ffa6-6b01-11e8-8234-2a52cd0ab169.png)

So for Tripal, I would propose the following issue templates

* bug report
* feature request
* discussion/question/other

### Discussion

Please weigh in with your thoughts.  We won't add this until we've had adequate discussion.

#### Pros:
* Much less intimidating for new users/people asking questions: no more page of markdown text asking them for their system info!
* specialize each template so we get more detailed info that would weihg down other issue types

#### Cons:
* you gotta push another button

**Comment by laceysanderson** [comment]
I Love this because I think it makes it even more clear that we want discussion & help questions on GitHub! I also like the suggestion of moving them into a .github folder to unclutter our repo.

**Comment by bradfordcondon** [comment]
well the current general issue template lives in .github/  its the PR template thats in root.  I wish we could move all github stuff into .github, i can look into it.

**Comment by spficklin** [comment]
This is great!  Can it also automatically add labels? or is that wishful thinking....

**Comment by bradfordcondon** [comment]
based on the template submitted, you mean?  interesting question.

Thats 👍 👍 👍 from the PMC so im going to get started on adding it.  I'll post the proposed templates here as I make them.  Further suggestions/feedback are very welcome though.

**Comment by bradfordcondon** [comment]
Proposed **BUG/ERROR report template**

```
## BUG/ERROR report
<!---
INSTRUCTIONS: The following template is meant to provide the information that will help other Tripal developers diagnose and reproduce your issue. Follow the directions below to complete the template.  Feel free to delete sections that are not applicable.
--->



### System information
<!--Please enter the following information (if able). All information is available in your site's administrator report area (Administration Toolbar > Reports > Status Report) -->

* Tripal Version:
* Drupal Version:
* PostgreSQL Version:
* PHP Version:

### Issue description
<!-- Please describe your issue here 
Some information you might want to include: the page you're seeing the issue on,  what behavior you're experiencing versus what you expect, really anything you think might best help us help you! -->

#### Steps to reproduce
<!-- What steps are necessary to recreate the bug/error?  Clear instructions here will make it easier for us to fix the problem! -->
#### Error messages and screenshots
<!-- Please include any error messages you find.  Including them in ``` as below will make the issue more readable. -->
<!-- Screenshots can be really helpful to describe the problem! -->

[```
error message
[```


```

**Comment by bradfordcondon** [comment]
Proposed **FEATURE REQUEST** template.  i need help with this one.
```
## Feature request

<!---
INSTRUCTIONS: The following template is meant to structure your feature request. 
--->

### Description
<!---
A clear and concise description of what you want to happen.
-->


<!---
Is your feature request related to a problem? Please describe.
-->

<!---
Is your feature request something that ALL tripal sites will want?  Please see [link guidelines] to see our manifesto on keeping Tripal bloat-free.

-->

### Additional information/screenshots
<!---
Add any other context or screenshots about the feature request here.
---->

```

**Comment by bradfordcondon** [comment]
proposed **discussion/question/other** template.  Honestlly maybe this should just be blank instead?

```

<!---
INSTRUCTIONS: Thank you for creating an issue! You're in the right place!
You can check out our repo guidelines [HERE].
--->

<!---
Please Select edit the below to specify the issue type.  If other, please describe. 
--->
## Issue type: [Question / Discussion  / Other]

### Description


<!---
Your question or discussion ideas go here!
We're here to help.
--->
```

**Comment by bradfordcondon** [comment]
@laceysanderson apparently i can move ALL github docs into the  [.github/](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/) folder (so why wasnt it autocreated there????).

I'll obviously move the PR_TEMPLATE into there, but what about CONTRIBUTING.md?  I kind of like that in the root of hte project (like say the license, or the README.)

dont think tis major enough to warrant a new thread (probably not a PR either but ill make one) so asking here since you brought it up.

**Comment by laceysanderson** [comment]
I agree with you on keeping CONTRIBUTING.md in the root folder :-) and am excited that we can move the issue/pr templates into .github folder! Thanks for checking into it!

Suggestion for all templates: I think it's easier to read these when they're hard-wrapped :-)

## Bug Report: 
I love this one! Only thing I can think to suggest is adding a newline between the "Steps to reproduce" and "Error messages and screenshots" sections.

## Feature Request
This one is hard right now since we don't yet have good guidelines in place. The following is my first stab at it...
```
## Feature Request/Discussion
<!---
INSTRUCTIONS: The following template is meant to structure your feature request. 
  Please keep in mind, this issue may evolve into discussion for an extension module
  if it's decided the feature is not a good fit for Tripal Core.
--->

<!--- Go over all the following points, and put an `x` in all the boxes that apply. -->
<!--- If you're unsure about any of these, don't hesitate to ask. We're here to help! -->
- [ ] is this feature something ALL Tripal sites will want?
- [ ] do you feel this feature is generally applicable?
- [ ] does this feature attempt to solve an existing problem with Tripal?
- [ ] are you open to developing or collaborating on an extension module if this is not a good fit for Tripal Core (no pressure here -just good to know upfront :-) )
- [ ] do you **Need** this feature ASAP?

### Description
<!--- A clear and concise description of what you want to happen. -->

### Your Specific Use Case
<!--- Please describe how you would use this feature in your own Tripal site and why you need it -->

### Generally Applicable
<!--- Why do you feel this is generally applicable? -->
<!--- Suggest other use cases if possible. -->

### Additional information/screenshots
<!--- Add any other context or screenshots about the feature request here. -->
```

## Discussion/Questions/Etc
What about this? My intent is to mainly encourage people they are in the right spot and we want this sort of feedback/discussion on github.
```
<!---
INSTRUCTIONS: Our intent is to use github as an open forum to help community members connect.
If you are looking to do any of the following, you are in the right place! and Thank You!
  - Ask for help/documentation/clarification of Tripal Functionality and Site Building/Management
  - Discuss controlled vocabulary terms for your data
  - Ask for input on site/module design questions
  - State your intent to develop a specific extension module
  - Really any type of discussion or question -we want to hear from you!
--->
```

**Comment by bradfordcondon** [comment]
thank you for the feedback @laceysanderson : PR submitted.

I imagine we'll revisit the feature request/discussion templates but right now just having them gives users a button to push that opens an issue telling them they are in the right place instead of a confusing list of system requirements so i think it's a really good thing to get it out there.

I submitted as you suggested.  I think the feature request might come across as a little defensive?  Granted our stance is aggressive re feature creep but still...

**Comment by laceysanderson** [comment]
@bradfordcondon, do you have any suggestions to make the feature request less defensive/aggressive? Is it the checkboxes that push it over the edge?

**Comment by bradfordcondon** [comment]
hahah what an oxymoronic critique way to go me

yes its definitely all the checkboxes. I think those points come in the specific use case and generally applicable sections.  I dont know that we need the check box section at all. Alternatively, what if we just got rid of those redundant with the general/use case sections?


```
## Feature Request/Discussion
<!---
INSTRUCTIONS: The following template is meant to structure your feature request. 
  Please keep in mind, this issue may evolve into discussion for an extension module
  if it's decided the feature is not a good fit for Tripal Core.
--->

<!--- Go over all the following points, and put an `x` in all the boxes that apply. -->
<!--- If you're unsure about any of these, don't hesitate to ask. We're here to help! -->
- [ ] does this feature attempt to solve an existing problem with Tripal?
- [ ] are you open to developing or collaborating on an extension module if this is not a good fit for Tripal Core (no pressure here -just good to know upfront :-) )
- [ ] do you **Need** this feature ASAP?

### Description
<!--- A clear and concise description of what you want to happen. -->

### Your Specific Use Case
<!--- Please describe how you would use this feature in your own Tripal site and why you need it -->

### Generally Applicable
<!--- Why do you feel this is generally applicable? -->
<!--- Suggest other use cases if possible. -->

### Additional information/screenshots
<!--- Add any other context or screenshots about the feature request here. -->
```

**Comment by laceysanderson** [comment]
I like it :-) Checkboxes make me happy so I often go overboard with them ;-p

**Comment by bradfordcondon** [comment]
thanks, ill revise the PR.  I think they look confusing when viewed unrendered to novices personally.

**Comment by bradfordcondon** [comment]
cool.

![screen shot 2018-06-11 at 1 48 56 pm](https://user-images.githubusercontent.com/7063154/41248182-3abead74-6d7e-11e8-8379-ad97b6e6ebd7.png)

**Comment by laceysanderson** [comment]
Thanks for closing -I was too busy showing everyone in the office how awesome this change was 🎉
