### ISSUE TITLE
Remote Field Fails with Fatal Error

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#423]
### System information
* Tripal Version: 7.3 (master branch)
* Drupal Version: 7.59
* PostgreSQL Version: 9.6
* PHP Version: 7.1

### Issue description

After adding a remote field to the organism bundle, I get the following error:

```
Notice: Undefined property: stdClass::$site_id in remote__data->makeRemoteRequest() (line 208 of /html/sites/all/modules/tripal/tripal_ws/includes/TripalFields/remote__data/remote__data.inc).
Exception: Please provide a numeric site ID for the tripal_get_remote_content function. in tripal_get_remote_content() (line 217 of /html/Tripal/sites/all/modules/tripal/tripal_ws/api/tripal_ws.api.inc).
```

Seems like a simple error so should be easily fixable.

Thanks!

**Comment by almasaeed2010** [comment]
Resolving the site id issue, produces the following non-fatal error:
```
Notice: Undefined index: label in remote__data_formatter->view() (line 106 of /html/sites/all/modules/tripal/tripal_ws/includes/TripalFields/remote__data/remote__data_formatter.inc).
Notice: Undefined index: ItemPage in remote__data_formatter->view() (line 107 of /html/sites/all/modules/tripal/tripal_ws/includes/TripalFields/remote__data/remote__data_formatter.inc).
```

**Comment by almasaeed2010** [comment]
So the PR #424 addresses the first fatal error but I am not sure what's needed for the second formatter problem.

**Comment by laceysanderson** [comment]
Removing PR submitted (it's merged btw) since now we need a fix for the formatter errors.
> Notice: Undefined index: label in remote__data_formatter->view() (line 106 of /html/sites/all/modules/tripal/tripal_ws/includes/TripalFields/remote__data/remote__data_formatter.inc).
> Notice: Undefined index: ItemPage in remote__data_formatter->view() (line 107 of /html/sites/all/modules/tripal/tripal_ws/includes/TripalFields/remote__data/remote__data_formatter.inc).

**Comment by spficklin** [comment]
Thanks... I'm working on that...

**Comment by laceysanderson** [comment]
Just making sure it didn't fall through the cracks :-)

**Comment by spficklin** [comment]
I added a new pull request to fix the remaining problems.

**Comment by laceysanderson** [comment]
PR Merged.
