### ISSUE TITLE
Content types via prop tables don't insert property

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#427]
### System information

* Tripal Version: 3
* Drupal Version:  7,.58 (or any version really)
* PostgreSQL Version:  10.4
* PHP Version: 7.2

### Issue description

When creating a content type that is differentiated via a prop table, and when inserting a brand new record, the corresponding prop record is not added.  Everything seems to work just fine because the entity is properly linked to the record in Chado.  But if the content type was ever removed it would not be possible to re-publish the records because the prop record is missing.

#### Steps to reproduce

Create a content type of 'Genetic Map'.  It maps to the featuremap table, and uses the featuremapprop table to differentiate.  The type for the featurmapprop is 'map type' and the value is 'genetic'.

#### Error messages and screenshots

```
error message
```

**Comment by spficklin** [comment]
For example consider these content types and their mapping to a prop table.

| Content Type |  Chado Table | Prop Table | Prop Type ID | Prop Value |
| --------------- | -------------- | ----------- | ------------- | ----------- |
| Whole Genome Project | project | projectprop | local:project_type | Whole Genome Project |
| GWAS Project | project | projectprop | local:project_type | GWAS Project |
| Genetic Map | featuremap| featuremapprop| local:May Type | genetic |

When adding a new entity for each of these, the corresponding records that should go in projectprop or featuremapprop that distinguish these records as belonging to the content type are not being created.

**Comment by bradfordcondon** [comment]
This is definitely worth fixing.
they would at least republish as vanilla bundles (assuming you have one defined?).  If anyone has this issue you could use [tripal alchemist](https://github.com/statonlab/tripal_alchemist) to convert the entities back to the correct type (and adding the chado prop), either via a table interface or by creating a collection of the entities to convert.

**Comment by bradfordcondon** [comment]
resolved, way to go @spficklin thanks @almasaeed2010 for reviewing
