### ISSUE TITLE
error in tripal chado's tripal_feature_match_features_page ? 

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#429]
### System information

* Tripal Version: 3
* Drupal Version: 7.59
* PostgreSQL Version: 9.3.23
* PHP Version: 7.0.27

### Issue description

the `tripal_feature_match_features_page()` is giving us errors on our live and dev site.  Specifically theres something wrong with the theme_table call and/or the theme? Code looks reasonable to me though.  I followed the trace and `drupal_attributes` is indeed null when its called in the theme... but why?  Anyway when we provide a URL that points to a feature that doesnt uniquely match a feature in the db (ie mrna and protein have same name) we get the below error message with a 500 error and the page isnt served.
[You can see this error on our dev site here.](http://160.36.205.61:8095/feature/maker-cbr2_scaffold20-snap-gene-0.22-mRNA-1)

#### Steps to reproduce

The error occurs when we a) dont have a url redirect for a feature page, and b) that feature name does not uniquely identify the feature.

#### Error messages and screenshots

```
Notice: Undefined variable: caption in tripal_feature_match_features_page() (line 1186 of /var/www/html/sites/all/modules/tripal/tripal_chado/tripal_chado.module).
Notice: Undefined index: header in theme_table() (line 1989 of /var/www/html/includes/theme.inc).
Notice: Undefined index: rows in theme_table() (line 1990 of /var/www/html/includes/theme.inc).
Notice: Undefined index: attributes in theme_table() (line 1991 of /var/www/html/includes/theme.inc).
Notice: Undefined index: caption in theme_table() (line 1992 of /var/www/html/includes/theme.inc).
Notice: Undefined index: colgroups in theme_table() (line 1993 of /var/www/html/includes/theme.inc).
Notice: Undefined index: sticky in theme_table() (line 1994 of /var/www/html/includes/theme.inc).
Notice: Undefined index: empty in theme_table() (line 1995 of /var/www/html/includes/theme.inc).
TypeError: Argument 1 passed to drupal_attributes() must be of the type array, null given, called in /var/www/html/includes/theme.inc on line 2005 in drupal_attributes() (line 2439 of /var/www/html/includes/common.inc).
```
https://github.com/tripal/tripal/blob/1a335da91a62d6729371f6eb408934d9bbb43393/tripal_chado/tripal_chado.module#L1085-L1188

**Comment by laceysanderson** [comment]
Oh wow, that is old code. The call to theme_table (L1186) is still in the Drupal 6 format. For Drupal 7 all parameters should be combined into a variables array: https://api.drupal.org/api/drupal/includes%21theme.inc/function/theme_table/7.x

Thus it should be
```php
$output .= theme_table(array(
  'header' => $header,
  'rows' => $rows,
  'attributes' => $table_attrs,
  'caption' => $caption
));

**Comment by bradfordcondon** [comment]
@laceysanderson 's bug fix should fix this issue, but the "next" error still occurs as:

```
Warning: Missing argument 1 for db_query(), called in /data/www/html/hardwoods_dev/drupal-7.52/sites/all/modules/tripal_analysis_blast/includes/TripalImporter/BlastImporter.inc on line 847 and defined in db_query() (line 2401 of /data/www/html/hardwoods_dev/drupal-7.52/includes/database/database.inc).
Notice: Undefined variable: query in db_query() (line 2406 of /data/www/html/hardwoods_dev/drupal-7.52/includes/database/database.inc).
PDOException: SQLSTATE[HY000]: General error in BlastImporter->getResultObject() (line 847 of /data/www/html/hardwoods_dev/drupal-7.52/sites/all/modules/tripal_analysis_blast/includes/TripalImporter/BlastImporter.inc).
```

https://github.com/tripal/tripal_analysis_blast/issues/22

I believe we can resolve the issue from here in the tripal_analysis_blast module area, once the above patch is merged.

**Comment by laceysanderson** [comment]
Ok, there is an official PR now 🎉. For some reason the original commit/branch went missing so I had to redo the change.
