### ISSUE TITLE
Web Services croaks when term is missing URL

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#430]
### System information

* Tripal Version: 3
* Drupal Version: 7.48
* PostgreSQL Version:  10.4
* PHP Version:  7.2.

### Issue description

Tripal web services uses JSON-LD and therefore everything has to have a term and every term has to have a URI.   If a database entry does not have a urlprefix then it causes the following error to appear on the page (from treegenes):

```
@context	"https://www.treegenesdb.org/Drupal/sites/default/files/tripal/ws/context/services..json"
@id	"https://www.treegenesdb.org/Drupal/web-services/error"
@type	"error"
error	"Missing a URL for the term: EFO:0000269."
```
Web services should be more robust and not error-out in this case.

#### Steps to reproduce
Remove the urlprefix from any term used as a content type.

#### Error messages and screenshots

```
error message
```

**Comment by laceysanderson** [comment]
Perhaps this could be solved by defaulting to the cv lookup page for the current tripal site? For example, if `SOFP` didn't have a URL prefix but the `SOFP:comment` term was used in a given tripal site, it could link to `[tripal site]/cv/lookup/SOFP/comment`.

![screen shot 2018-06-13 at 11 26 31 am](https://user-images.githubusercontent.com/1566301/41367577-aad8b51c-6efc-11e8-9e59-152f6b8b7119.png)

This would allow the use of local terms in web services.

**Comment by spficklin** [comment]
Very good idea @laceysanderson. I'll implement that and add a PR.

**Comment by laceysanderson** [comment]
PR Merged.
