### ISSUE TITLE
General table prefixing issue in chado_query

### ISSUE THREAD

**Issue by guignonv** [tripal/tripal#431]
Tripal Versions: 2.x and 3.x (13/06/2018)
Drupal Version: not relevant
PostgreSQL Version: not relevant
PHP Version: not relevant

In tripal_core.chado_query.api.inc, the chado_query function prefixes tables using the curly brackets {} for Chado tables and square brackets [] for Drupal tables. The following piece of code is currently used:
```
 $chado_schema_name = chado_get_schema_name('chado');
    $drupal_schema_name = chado_get_schema_name('drupal');
    $sql = preg_replace('/\{(.*?)\}/', $chado_schema_name.'.$1', $sql);
    $sql = preg_replace('/\[(\w+)\]/', $drupal_schema_name.'.$1', $sql);
```
This raises 2 issues:
1) when the user wants to use curly or square brackets for other things that table names, it will be a problem. For instance, if I'd like to select any feature with a uniquename that begins with capital A or B, I would write a query like that (use "drush php" for testing):
```
$sql_query = "SELECT * FROM {feature} WHERE uniquename ~ '^[AB]';"
$results = chado_query($sql_query);
drupal_set_message('Query: ' . $results->getQueryString());

```
Such code will in fact return nothing while there should be some results as the query will be turned into:
`SELECT * FROM chado.feature WHERE uniquename ~ '^public.AB';`

Then

2) replacing the square brackets with just "public." will break Drupal behavior: Drupal uses curly brakets arround table names in order to prefix them with the database prefix used by the Drupal installation (@see https://api.drupal.org/api/drupal/includes%21database%21database.inc/7.x ). For some reasons, people may want or need to prefix all Drupal tables with something and removing curly brackets around Drupal table names prevents Drupal from doing its job.
Some people may wonder why using a table prefix: there are many cases in which it can actually be useful. The first one I think of is when you want to share Drupal users between several Drupal instances. It is possible to specify in your settings.php files that the user table are not prefixed while all the other Drupal tables are. Then when a user is created on a Drupal instance or another, it will be also created on other (well it's a bit more tricky than this but it works).

I'm sorry I don't have a pull request to fix that (yet) and I didn't came up with a good solution yet but if people have ideas to discuss for a fix, feel free. I just wanted to raise the issue so it would be known and people having trouble using queries like mines would understand why sometimes, they might not have expected results... (and also, using Tripal prevents them from using Drupal table prefixing feature).

**Comment by guignonv** [comment]
So far, I thought about something like this :
```
    $chado_table_list = chado_get_all_chado_table_names(); // function to write that returns an array of table names as strings, for instance array('feature', 'featureprop','stock,'...)
    $public_table_list = chado_get_all_public_table_names();
    $sql = preg_replace('/\{(' . implode('|', $chado_table_list) . ')\}/', $chado_schema_name.'.$1', $sql);
    $sql = preg_replace('/\[(' . implode('|', $public_table_list) . ')\]/', $drupal_schema_name.'.{$1}', $sql);

```

**Comment by guignonv** [comment]
Additional notes:

- Drupal uses the protected function setPrefix($prefix) to prefix tables.

- How Drupal can handle table prefixing is explained there:
https://api.drupal.org/api/drupal/sites%21default%21default.settings.php/7.x
 look into the source code documentation for "Database settings".

**Comment by laceysanderson** [comment]
Thank you for reporting this @guignonv! I will have to think on this further before weighing in on a fix as we need to keep efficiency in mind as well.

**Comment by almasaeed2010** [comment]
Hello @guignonv 

Did you try passing your condition as an argument?

```php
chado_query("SELECT * FROM {feature} WHERE uniquename ~ :regexp", [':regexp' => '^[AB]'])
```

I think that should work.

Thanks!

**Comment by almasaeed2010** [comment]
Just a note that this seems like a limitation in the Drupal way of doing the replacement. That is, if we attempt the following query, it will also break the query:

```php
db_query('select * FROM chado.feature where name ~ \'{test}\'')->getQueryString()
// Result
"select * FROM chado.feature where name ~ 'test'"
```

As you can see, it removed `{}` from the `test` condition.

Whereas, if we do the following:
```php
db_query('select * FROM chado.feature where name ~ :regexp', [':regexp' => '{test}'])
```

It properly converts the query to  (you can see this if you can [watch active queries in postgres](https://paquier.xyz/postgresql-2/postgres-9-3-feature-highlight-watch-in-psql/))
```sql
select * FROM chado.feature where name ~ '{test}'
```

Therefore, I believe that our suggestion to pass it as an argument would be the best solution for this. Thoughts?

Thanks!

**Comment by guignonv** [comment]
Yup it works :-) , but I would call it a "workaround" :-s as a basic user/developer who is not aware of that issue will not understand what's going on when he/she will not use a placeholder for a static value that has brackets.
I didn't check if this issue on Drupal core has been reported (I should check I guess... :-p ) but I agree it's a Drupal limitation... for curly brackets! :-)

However, we have the hand on the square brackets and chado_query() and we could do something to avoid that. Maybe just issue a warning somewhere when curly or square brackets are detected inside quotes? ...or we could leave it as is but add some warning in the chado_query() documentation about this issue. I think the "doc" solution would be less efficient but it would be a minimum.

**Anyway, that would solve issue 1 but something should still be done for issue 2.**

**UPDATE for issue 1**: I checked and it is not considered as a Drupal issue but everybody who has met and reported the curly bracket replacement problem has been requested to use placeholders just like you said. The documentation ( https://www.drupal.org/docs/7/api/database-api/static-queries ) does not talk about it clearly but assumes people will understand they must use placeholders for every literal value they use so the problem should not appear. Anyway, many people are lazy (like me) and don't want to bother with a placeholder for a literal value that is static and does not require sanitation... but it's a bad habit! :-) Always use placeholder.

**Comment by guignonv** [comment]
For issue 2, should I create a pull-request with something like that:

```
    $chado_schema_name = chado_get_schema_name('chado');
    $sql = preg_replace('/\{(.*?)\}/', $chado_schema_name.'.$1', $sql);
    $sql = preg_replace('/\[(\w+)\]/', '{$1}', $sql);

```
?

**Comment by spficklin** [comment]
@guignonv I've applied a fix that should correct the first problem you mention. Take a look at the PR I just posed related to this issue.

As per the second issue, I'm not sure I understand why there's a problem.  If you really want to hard code a prefix on a table you can do it.  Drupal just won't try to adjust the schema or add a table prefix.   In the latter case, Tripal isn't compatible with Drupal table prefixes.

**Comment by guignonv** [comment]
PR reviewed.

**Comment by spficklin** [comment]
Thanks @guignonv.  I've merged that PR in and the first issue should now be fixed.   Can you clarify the second issue. I'm not sure what you're looking for. Here's a repeat of my last comment:

> If you really want to hard code a prefix on a table you can do it. Drupal just won't try to adjust the schema or add a table prefix. In the latter case, Tripal isn't compatible with Drupal table prefixes.

**Comment by guignonv** [comment]
Well, I don't really know how to explain that in a few words, I'm afraid. :-s Basically, I don't think Tripal needs to prefix Drupal tables with "public."; it should remain implicit and Tripal could remain compatible with Drupal table prefixing. The SQL query "SET serach_path..." (in tripal_core.chado_general.api.inc) does the job already: PostgreSQL will search into 'chado' first and then 'public' if tables are not prefixed.

For instance, here is a concrete use case. It's for Tripal v2 but it would behave exactly the same with Tripal v3 as we also have linking tables on the "Drupal side" with Drupal entities (just the table names would change). I have "stocks" (germplasm accessions) in collections on Chado side and I have their "nodes" on the Drupal side on which I have linked scientific publications where those accessions were involved. So, for instance, I have a chado.stock entry for a banana plant with an associated public.node entry which has a publication field (Drupal field) which links the node to several other Drupal node that hold publications from the "biblio" Drupal module (https://www.drupal.org/project/biblio).

To get the list of publication nodes associated to accessions (stock) from a given collection, I use the following query (with chado_query() ):
```
SELECT
  n2.nid
FROM {stock} s
  LEFT JOIN [chado_stock] cs ON cs.stock_id = s.stock_id
  LEFT JOIN [node] n1 ON n1.nid = cs.nid
  LEFT JOIN [field_data_field_accession_list] fd ON fd.field_accession_list_nid = n1.nid AND fd.entity_type = 'node'
  LEFT JOIN [node] n2 ON n2.nid = fd.entity_id AND n2.status = '1' AND n2.type = 'biblio'
  JOIN {stockcollection_stock} scs ON scs.stock_id = s.stock_id
  JOIN {stockcollection} sc ON sc.stockcollection_id = scs.stockcollection_id
WHERE
    sc.uniquename = :collection_uniquename
```

If Tripal forces to prefix Drupal tables with "public.", it will be turned into:
```
SELECT
  n2.nid
FROM chado.stock s
  LEFT JOIN public.chado_stock cs ON cs.stock_id = s.stock_id
  LEFT JOIN public.node n1 ON n1.nid = cs.nid
  LEFT JOIN public.field_data_field_accession_list fd ON fd.field_accession_list_nid = n1.nid AND fd.entity_type = 'node'
  LEFT JOIN public.node n2 ON n2.nid = fd.entity_id AND n2.status = '1' AND n2.type = 'biblio'
  JOIN chado.stockcollection_stock scs ON scs.stock_id = s.stock_id
  JOIN chado.stockcollection sc ON sc.stockcollection_id = scs.stockcollection_id
WHERE
    sc.uniquename = :collection_uniquename
```

Which is not good because if I use my multi-chado module to work with several chado instances on a same Drupal public database, I will not be able to make Drupal use the appropriate linking tables that links to the correct chado schema as "public.chado_stock" is explicit. I can't override this with a temporary view that would "redirect" the query to another linking table.
And it would be even worse if I had to use Drupal table prefixing for some reasons. Drupal would not be able to prefix tables.
However, if Tripal did not add "public." in front of Drupal table names, but rather replaces the square brackets with the curly ones, it would work well (both multi-chado and Drupal table prefixing):
```
SELECT
  n2.nid
FROM chado.stock s
  LEFT JOIN {chado_stock} cs ON cs.stock_id = s.stock_id
  LEFT JOIN {node} n1 ON n1.nid = cs.nid
  LEFT JOIN {field_data_field_accession_list} fd ON fd.field_accession_list_nid = n1.nid AND fd.entity_type = 'node'
  LEFT JOIN {node} n2 ON n2.nid = fd.entity_id AND n2.status = '1' AND n2.type = 'biblio'
  JOIN chado.stockcollection_stock scs ON scs.stock_id = s.stock_id
  JOIN chado.stockcollection sc ON sc.stockcollection_id = scs.stockcollection_id
WHERE
    sc.uniquename = :collection_uniquename
```

In fact, I wonder if it was a good idea in first place to ask people to use curly brackets for chado tables in chado queries. Curly brackets could have been left to Drupal table (as in db_query()) and chado table could have been left "as they are" without any brackets. That's the purpose of using "SET search_path = ...;". Otherwise, if Tripal prefixes tables with "chado.", why setting the PostgreSQL search_path then?
But that's my point of view: either using search_path or prefixing but not both.

**Comment by laceysanderson** [comment]
@guignonv I believe this thread has become a little confusing. To summarize, the problem yet to be solved is:
- Removing the brackets around Drupal table names breaks drupal table prefixing (i.e. tableprefix_drupal_table`). Solution is for the Chado Query API to add curly brackets to the Drupal tables after schema prefixing the Chado tables.
- Schema prefixing Drupal tables with `public.` breaks your ability to use multi-chado and everyone's ability to use multiple schema where the Drupal schema may not be named `public`. Solution is to allow the search_path with default to public to handle Drupal tables.

Is that correct?

If so, I like your solution proposed above:
> ```
>    $chado_schema_name = chado_get_schema_name('chado');
>    $sql = preg_replace('/\{(.*?)\}/', $chado_schema_name.'.$1', $sql);
>    $sql = preg_replace('/\[(\w+)\]/', '{$1}', $sql);
> ```

I think it would be great if you could create a PR based on this solution. Ideally it would include PHPunit tests since the Chado Query API is so critical.

**Comment by guignonv** [comment]
I'll do my best. Quite busy on 2 other projects right now... :-s
