### ISSUE TITLE
We need an Array Design field for the Assay content type

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#432]
## Feature Request/Discussion

- [x] does this feature attempt to solve an existing problem with Tripal?
- [ ] are you open to developing or collaborating on an extension module if this is not a good fit for Tripal Core (no pressure here -just good to know upfront :-) )
- [x] do you **Need** this feature ASAP?

### Description

We are missing a TripalField that corresponds to the assay.array_design_id field of Chado.  Currently if a user creates a new Assay they must enter a numeric value that corresponds to the array design ID of the array. 

I'm submitting this in response to this field being missing from PR #398

**Comment by laceysanderson** [comment]
Fixed via PR.
