### ISSUE TITLE
Configure Fields for Drupal Search API-based Tripal Collections

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#437]
## Feature Request/Discussion

- [x] does this feature attempt to solve an existing problem with Tripal?
- [x] are you open to developing or collaborating on an extension module if this is not a good fit for Tripal Core (no pressure here -just good to know upfront :-) )
- [ ] do you **Need** this feature ASAP?

### Description

Currently when saving a Tripal Collection on a view based on a Drupal Search API Index, all fields attached to all bundles in the result set are added to the collection. This is in contrast to creating a Tripal Collection on Tripal Content based views where you are provided the ability to configure which fields you would like in your collection.

Ideally, Tripal Collections for Drupal Search API views would mimic those of Tripal Content views since the user shouldn't need to know the difference.

**Comment by spficklin** [comment]
I think this is resolved as there is a merged PR and no other comments and the PR references follow-up issues.
