### ISSUE TITLE
drush pub importer

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#438]
### System information

* Tripal Version:3

### Issue description
I was really excited about the command line drush importer for pubmed citations.  However the command fails with the below error.  However my sql query shows i only have one cv and one cvterm for the term "Journal Article".

```
                                                           ^
hardwood_dev=> select * from chado.cvterm cvterm INNER JOIN chado.cv cv ON cvterm.cv_id = cv.cv_id where cvterm. name='Journal Article';
2241	22	Journal Article	The predominant publication type for articles and other items indexed for NLM databases.	2721	0	0	22	tripal_pub	Tripal Publiation Ontology. A temporary ontology until a more formal appropriate ontology an be identified.
```
hardwood_dev=>

#### Steps to reproduce
`drush trp-import-pubs --dbxref=PMID:29792315 --username=youradmin`

#### Error messages and screenshots

```
$ drush trp-import-pubs --dbxref=PMID:29792315 --username=hwadmin

NOTE: Loading of publications is performed using a database transaction.
If the load fails or is terminated prematurely then the entire set of
insertions/updates is rolled back and will not be found in the database

WD tripal_cv_api: chado_get_cvterm: The identifiers you passed in were not unique. You passed in Array                                             [error]
(
    [name] => Journal Article
    [cv_id] => Array
        (
            [name] => tripal_pub
        )

)
.
[site http://160.36.205.61:8095] [TRIPAL ERROR] [TRIPAL_CV_API] chado_get_cvterm: The identifiers you passed in were not unique. You passed in Array(    [name] => Journal Article    [cv_id] => Array        (            [name] => tripal_pub        )).
WD tripal_pubmed: Cannot find a valid vocabulary term for the publication type: "Journal Article".                                                 [error]
[site http://160.36.205.61:8095] [TRIPAL ERROR] [TRIPAL_PUBMED] Cannot find a valid vocabulary term for the publication type: "Journal Article".
WD tripal_pub: chado_publication_exists(): The Publication Type is a required property but is missing                                              [error]
[site http://160.36.205.61:8095] [TRIPAL ERROR] [TRIPAL_PUB] chado_publication_exists(): The Publication Type is a required property but is missing
WD tripal_pub: The Publication Type is a required property but is missing                                                                          [error]
[site http://160.36.205.61:8095] [TRIPAL ERROR] [TRIPAL_PUB] The Publication Type is a required property but is missing

Syncing publications with Drupal...
```

**Comment by spficklin** [comment]
@bradfordcondon can you pull this branch and test to see if the fix I committed corrects the problem for you?  branch:  438-tv3-pub_xml_fix

**Comment by spficklin** [comment]
I think the problem was due to the fact that the title and the abstract had embedded HTML.  That threw off the XML parser.

**Comment by bradfordcondon** [comment]
imports as:
```
31	Genomic Variation Among and Within Six Juglans Species.			G3 (Bethesda, Md.)		2018			Stevens KA, Woeste K, Chakraborty S, Crepeau MW, Leslie CA, Martínez-García PJ, Puiu D, Romero-Severson J, Coggeshall M, Dandekar AM, Kluepfel D, Neale DB, Salzberg SL, Langley CH. Genomic Variation Among and Within Six Juglans Species.. G3 (Bethesda, Md.). 2018 May 23.	229	f
```

Thanks @spficklin !  I had no idea that was the problem :P

ps does the citation need to be manually edited to have the hyperlink?  If so I might submit that as a feature request/simple PR>

**Comment by spficklin** [comment]
The hyperlink was programmed to show up automatically if there was a URL or dbxref, I thought.  If it's not working then there's a bug.

**Comment by spficklin** [comment]
I'm going to do a PR for this fix.

**Comment by bradfordcondon** [comment]
it does create the DBxref that links out.  but i didnt think that would show up when the publication is say attached to another entity.  I can check that.

**Comment by bradfordcondon** [comment]
I imported a pub like so
`drush trp-import-pubs --dbxref=PMID:26698853 --username=myadminuname`

* the dbxref entry works and links out properly.

<img width="889" alt="screen shot 2018-07-02 at 5 32 40 pm" src="https://user-images.githubusercontent.com/7063154/42187393-f24509ac-7e1d-11e8-8533-9554038e2e31.png">

* when the publication is attached to another record, there is a linkout in the citation field, even though the citation for the pulbication itself doesnt have it.

<img width="1175" alt="screen shot 2018-07-02 at 5 36 37 pm" src="https://user-images.githubusercontent.com/7063154/42187584-8cd9a0b8-7e1e-11e8-904a-ce7782e19b7b.png">


<img width="1350" alt="screen shot 2018-07-02 at 5 37 13 pm" src="https://user-images.githubusercontent.com/7063154/42187588-9343dc16-7e1e-11e8-911b-896bb7803d5a.png">



so, it works exactly as you describe 👍 im closing issue.
