### ISSUE TITLE
Errors when editing Relationship field on Organism Entity.

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#44]
You see the following errors at the top of the page when editing the Relationship field (Home » Administration » Structure » Tripal Content Types » Organism » Manage fields):

```
Notice: Undefined index: #entity in sbo__relationship_widget->form() (line 18 of /var/www/XXX/sites/all/modules/tripal/tripal_chado/includes/TripalFields/sbo__relationship/sbo__relationship_widget.inc).
Notice: Undefined index: relationships in sbo__relationship->settingsForm() (line 549 of /var/www/XXX/sites/all/modules/tripal/tripal_chado/includes/TripalFields/sbo__relationship/sbo__relationship.inc).
Notice: Undefined index: relationships in sbo__relationship->settingsForm() (line 567 of /var/www/XXX/sites/all/modules/tripal/tripal_chado/includes/TripalFields/sbo__relationship/sbo__relationship.inc).
Notice: Undefined index: relationships in sbo__relationship->settingsForm() (line 578 of /var/www/XXX/sites/all/modules/tripal/tripal_chado/includes/TripalFields/sbo__relationship/sbo__relationship.inc).
Notice: Undefined index: relationships in sbo__relationship->settingsForm() (line 592 of /var/www/XXX/sites/all/modules/tripal/tripal_chado/includes/TripalFields/sbo__relationship/sbo__relationship.inc).
```

**Comment by spficklin** [comment]
Fixed in the 7.x-3.x branch.   Some settings for the field accidentally got misplaced.  But this means that even if you update to the most recent branch you'll still get the same error.  So, to fix this just delete the relationship field.  Then click the '+ Check for new fields' link at the top.  The relationship field will be re-added with the correct settings and the error goes away.

**Comment by spficklin** [comment]
I did a bunch of pushes this morning.  If you pulled prior to this fix you may need to pull again. Could it be you might still need to pull to get the most up to date?

**Comment by laceysanderson** [comment]
I just pulled again and it says I'm up "Already up-to-date"... The errors for the Relationship field are fixed. It's just the publication field that's still causing issues (#42) . I can try on a fresh install on Monday.

**Comment by spficklin** [comment]
Oh I see. My mistake. I've fixed that and noticed the problem in the alternate_name (synonym) field as well.  So, I think that will take care of it.  Fixes have been pushed
