### ISSUE TITLE
delete_me

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#447]
### System information

* Tripal Version: 3.x
* Drupal Version:  7.x
* PostgreSQL Version: N/A
* PHP Version:  N/A

### Issue description

Several fields will sometimes get their default values set to 'delete_me'.  This needs to be fixed.

#### Error messages and screenshots

Create a new Chado Property field on the Organism content type.  Re-edit the field after saving it and you'll see that the default value is set to 'delete_me'.
```
error message
```

**Comment by laceysanderson** [comment]
Fixed via PR.
