### ISSUE TITLE
Annoyances

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#449]
This is just a place to catch small annoyances that need fixing before the release but may or may not be bugs and bugs are minor.

**Comment by spficklin** [comment]
Annoyance 1:  The content types are not sorted alphabetically

**Comment by spficklin** [comment]
Annoyance 2:  The code for autocomplete for specifying a cvterm is duplicated in multiple places. It really should be one function so we can make fixes (if need be) in one place.

**Comment by spficklin** [comment]
Annoyance 3: When changing the field layout for a content type the page loading is too slow.

**Comment by bradfordcondon** [comment]
Annoyance 4:  I often want to look up the bundle and entity id given a chado record and table, but i dont think theres an API to do so.

edit: saw after i posted that this is "needs fixing before release" ... dont know if i feel that way about this.

**Comment by spficklin** [comment]
I'm marking those that have been resolved with a horray emoji

**Comment by bradfordcondon** [comment]
teh cvterm lookup box returns results that aren't valid for term creation.
For example:

<img width="742" alt="screen shot 2018-06-18 at 4 07 26 pm" src="https://user-images.githubusercontent.com/7063154/41559364-d78f163c-7311-11e8-81ed-aa08ac538a85.png">



<img width="673" alt="screen shot 2018-06-18 at 4 07 32 pm" src="https://user-images.githubusercontent.com/7063154/41559362-d3f97fd0-7311-11e8-8606-72b85cbdbfbd.png">

**Comment by spficklin** [comment]
Oh, this is the same problem as the third comment above.   It's because that autocomplete term is a synonym but the lookup code isn't using synonyms.  It got fixed in one place but not in other places.

**Comment by spficklin** [comment]
Annoyance 5: Data Searches should not search by default, but it should be set to require a button press before results are shown.

**Comment by spficklin** [comment]
Annoyance 6:  The Pub Importer still has a link to the old help pages.

**Comment by spficklin** [comment]
Annoyance 7: importing pubs results in warning messages if the pub already exists.

**Comment by spficklin** [comment]
Annoyance 8: non Tripal fields aren't showing up in the web services.

**Comment by spficklin** [comment]
Annoyance 9:  Tripal Bundles don't have the uid integrated with Views and there are no relationships for the user content.

**Comment by spficklin** [comment]
Annoyance 10:  when importing pubs using the Tripal importer the publications are not automatically published like they were in Tripal v2.

**Comment by bradfordcondon** [comment]
@spficklin I would vote in favor of creating child issues for these annoyances since its hard to track what has/has not been done.

**Comment by spficklin** [comment]
Yes, good point.  This document was just meant to be a place to discuss and was meant to collect info for our Sept 7th User's meeting.  So for that reason I think maybe we can close out this discussion.    For the specific issues that got added I think you're right.

**Comment by bradfordcondon** [comment]
ok agreed.  lets close but make any child issues that you want addressed in the future.
