### ISSUE TITLE
Error publishing if fields have defaults

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#450]
### System information

* Tripal Version: 3
* Drupal Version: 7.x
* PostgreSQL Version: N/A
* PHP Version: N/A

### Issue description

If a content type has a field field that has a default value set and you try to publish new entities you get errors that the entity could not be saved.  This is because the EntityController attaches fields to an entity before saving, and becaue the field has a default value it gets attached.  During publishing there is no inserting or updating that goes on so the controller is confused and the storage backend then tries to insert a field when it shouldn't.

#### Steps to reproduce
Go to any content type that has a ChadoProperty field, edit the field and set a default value.  Then try to publish entities of that content type.

#### Error messages and screenshots

```
error message
```

**Comment by laceysanderson** [comment]
PR Merged.
