### ISSUE TITLE
Some field tokens don't work in URLs

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#452]
### System information

* Tripal Version:  3
* Drupal Version:  7.x
* PostgreSQL Version:  N/A
* PHP Version: N/A

### Issue description

It seems some tokens don't work correctly when building URLs for content types.  They are missing from the URL.

#### Steps to reproduce
Setting the mRNA URL to be mRNA/[obi__organism]/[schema__name]

#### Error messages and screenshots

```
error message
```

**Comment by laceysanderson** [comment]
PR Merged.
