### ISSUE TITLE
content page PDO error broken

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#457]
### System information

* Tripal Version:3

#### Steps to reproduce
visit `/admin/content/bio_data` on current master.

```
PDOException: SQLSTATE[42703]: Undefined column: 7 ERROR: column tripal_entity.label does not exist LINE 1: ....id AS entity_id, tripal_entity.bundle AS bundle, tripal_ent... ^: SELECT tripal_entity.id AS entity_id, tripal_entity.bundle AS bundle, tripal_entity.label AS tripal_entitylabel, tripal_entity.changed AS tripal_entitychanged, :entity_type AS entity_type, NULL AS revision_id FROM {tripal_entity} tripal_entity ORDER BY tripal_entity.label ASC, tripal_entity.changed DESC LIMIT 25 OFFSET 0; Array ( [:entity_type] => TripalEntity ) in tripal_content_overview_form() (line 330 of /var/www/html/sites/all/modules/tripal/tripal/includes/TripalEntityUIController.inc).
The website encountered an unexpected error. Please try again later.
```

tripal_entity.label is not a column in the tripal_entity table.

**Comment by bradfordcondon** [comment]
https://github.com/tripal/tripal/blob/3a919514aee0bbd4202ddf63859065108739893d/tripal/includes/TripalEntityUIController.inc#L202-L211

label exists for tripal_bundle.  So we probably meant to get the label column from that table instead.  But where was it added?

https://github.com/tripal/tripal/blob/3a919514aee0bbd4202ddf63859065108739893d/tripal/includes/TripalEntityUIController.inc#L319

here we go.  im reverting it to previous.

**Comment by spficklin** [comment]
Yeah, sorry. That accidentally snuck in another pull request :-/  I removed it in one yesterday.  But I think I fixed it in another PR from yesterday that got merged?  Can you pull the most recent code and see?

**Comment by bradfordcondon** [comment]
Yes, this is on both my dev and my live site as of 5 minutes ago, plus the code i linked is to current master.

**Comment by bradfordcondon** [comment]
thanks for the quick response.  my fault as well for not noticing in review.
