### ISSUE TITLE
Hide Empty panes by default

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#46]
I need the ability to hide empty panes from the display completely. For example, if there are no publications for a given page then that pane shouldn't show up in either the table of contents or alongside the other panes --this is the current functionality in Tripal2. This should likely be a configuration option on the "Manage Display" since some groups have opted for the "display everything even if it's empty" approach with their Tripal2 sites.

NOTE: I can't do this by simply hiding the field in "Manage Display" for a given entity type because I want it to show up on pages that do have data in that field.

**Comment by laceysanderson** [comment]
This is still a really big need! Having Publications show up in the sidebar and then a user clicks on it only to see there are none is misleading. I think this needs to be a **configuration option** since Dorrie Main's group seems to like to show these so users know what information might be available for other content.

This is needed for all fields including those that simply appear in a table with other fields and those residing in their own Tripal Pane.

@spficklin is there enough time for @shawnawsu to get to this before the first release? If not maybe I could fit it in though it depends on how much time it takes to get Tripal Daemon into core.

**Comment by shawnawsu** [comment]
This is available for testing in the 7.x-3.x-dashboard branch I just pushed. I have not fully tested this on non-tripal_ds sites so would be great if that could happen before we merge it into 7.x-3.x.

**Comment by laceysanderson** [comment]
This is perfect for my needs :-) I checked it for both with and without tripal panes and both show/hide empty fields setting and it performs as expected.

Since this is now in the main 7.x-3.x branch, I'm marking this as closed.
