### ISSUE TITLE
PHP/Drupal/Tripal Pro's and Con's

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#461]
In preparation for our upcoming open meeting for the design and needs of Tripal v4. I have created an online document to allow all Tripal users, developers and stake holders to organize thoughts on the pros and cons of PHP/Drupal and Tripal.    I start it out completely blank to allow for free flow of input.   If you are a user of Tripal past or present please consider adding to the document.

Here's a link to the document:

http://goo.gl/DQk3sx

**Comment by bradfordcondon** [comment]
Hi Stephen,

The document is set to view only by default: maybe it should be open-edit?  Or are we meant to make a copy and fill it out seperately?

**Comment by spficklin** [comment]
Whoops, sorry about that. It should be editable now.

**Comment by bradfordcondon** [comment]
I feel like we've got a good path forward with the Python API plan, so I'm closing this.
