### ISSUE TITLE
Publication Content Type has a publication field on it!

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#462]
### System information

* Tripal Version: 3
* Drupal Version:  N/A
* PostgreSQL Version: N/A
* PHP Version:  7.2

### Issue description

The publication content type has a field on it that uses the schema__publication field.  It prevents importing of publications.  This should be looked into.  I did not have time try to duplicate it.

#### Error messages and screenshots

```
error message
```

**Comment by shawnawsu** [comment]
I just did a fresh install of this and it appears to no longer be a problem.
