### ISSUE TITLE
Tripal Pub Importer report isn't working

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#465]
### System information

* Tripal Version: 3
* Drupal Version: 7.x
* PostgreSQL Version: N/A
* PHP Version:  7.2

### Issue description

The Tripal Importer has the ability to generate a report and email a specific user.  The email is sent but no the report is empty.

#### Steps to reproduce

Create a Tripal Importer, then run it manually on the command-line with this command:

```
drush trp-import-pubs --root=/var/www/html --report=[email] -l [site url] --username=[username] --update=Y
```
Be sure to substitute [email], [site url] and [username] appropriately

**Comment by laceysanderson** [comment]
Merged 👍
