### ISSUE TITLE
Tripal Entity Relationships

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#467]
### System information

* Tripal Version:  3.
* Drupal Version:  7.x
* PostgreSQL Version:  N/A
* PHP Version:  N/A

### Issue description

So, it's currently not possible to integrate our Tripal Entities with other 3rd party tools such as [flag](https://www.drupal.org/project/flag) because we have a different Views query handler and typically those modules don't expect anything other than the default Drupal Views query handler.   So, if we wanted to use the flag module to allow people to flag interesting entities it works, but we can't create nice views of their "bookmarks".

**Comment by spficklin** [comment]
I'm currently working on this in branch 467-tv3-entity_relationships

**Comment by bradfordcondon** [comment]
I see this PR was merged, so closing this issue.
