### ISSUE TITLE
Undefined variable notice when preparing chado

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#469]
### System information

* Tripal Version: 3.x
* Drupal Version: 7.59
* PostgreSQL Version: 9.5
* PHP Version: 7.0

### Issue description

When creating the "prepare chado" job on a new site, I get the following notice:
```
Notice: Undefined variable: path in TripalJob->create() (line 163 of /var/www/html/sites/all/modules/tripal/tripal/includes/TripalJob.inc).
```

#### Steps to reproduce
So far I've encountered this only when preparing a new site but it's possible that this would happen when submitting any job.

#### Error messages and screenshots

<img width="1435" alt="screen shot 2018-06-21 at 9 36 11 am" src="https://user-images.githubusercontent.com/1512664/41722431-8f01ceec-7536-11e8-819d-596b1788db01.png">

**Comment by bradfordcondon** [comment]
I see this error for all jobs.

**Comment by spficklin** [comment]
You should review PR #455.  It has a fix for that :-)

**Comment by almasaeed2010** [comment]
Yep PR #455 fixes this for me. Thanks!
