### ISSUE TITLE
Tripal Entities are not fully supported by Views

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#473]
### System information

* Tripal Version: 3
* Drupal Version: 7.x
* PostgreSQL Version: N/A
* PHP Version: N/A

### Issue description

Tripal Entities are not fully supported by Views. It's not possible to use the create date, change date and user who created the content type in Views.  We need to be able to display these, filter them and sort them.

**Comment by spficklin** [comment]
I have started branch 473-tv3-enity_views_support to fix this.

**Comment by spficklin** [comment]
I'm marking this as a release blocker because it's needed for a stable release. Whether we get it into the 6/30/2018 release remains to be seen.

**Comment by bradfordcondon** [comment]
PR submitted by @spficklin  #470 

I requested some minor changes and made a PR to add them.  Need 1 more review.

**Comment by spficklin** [comment]
There are still some additional issues here, but the worst problems are fixed.  The PR was merged so I'm closing this.
