### ISSUE TITLE
Collection files are not generated if an entry is missing a field

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#478]
### System information

* Tripal Version: 3 
* Site: HWG live

### Issue description

Creating a feature collection fails to generate fails if it cant retrieve a value for a field. Instead this error is returned:
```
ParseError: syntax error, unexpected &#039;;&#039; in module_load_include() (line 57 of /var/www/html/sites/all/modules/tripal/tripal/includes/TripalFieldDownloaders/TripalCSVDownloader.inc).
```

https://github.com/tripal/tripal/blob/3302486540c12042fb26e29acb167176e8c1149c/tripal/includes/TripalFieldDownloaders/TripalTabDownloader.inc#L43-L60

I'm able to fix the error by simply checking if the property exists and adding a blank element/continuing if it doesnt.

Note that the field *ISNT BLANK* for these failed records, so im not sure why the problem is occurring.  What I can say is that there are 3 organisms in my collection: one has 100% sequences, one has 0% sequences, and one has 70% sequences.

After fixing the below error by continuing if the property doesnt exist, the FASTA, csv, and tsv files are generated.  While the CSV and FASTA are able to "carry on" and produce the file, with blank sequences for the failed entries, the TSV file is not and only consists of the failed line.  

#### Steps to reproduce

I'm not positive what the source of the problem is.  I create a collection of features and attempt select the name and protein sequence fields.

* [problematic entity](https://www.hardwoodgenomics.org/bio_data/1633342)
* [succesful entity](https://www.hardwoodgenomics.org/bio_data/1909091)

p serotina might be more helpful since it contains records that both fail/succeed:

* [failure](https://www.hardwoodgenomics.org/bio_data/1914787)

* [success](https://www.hardwoodgenomics.org/bio_data/1367387)

Features are the same type, and both have protein sequences (the field that is causing issues for me).

here is a look at the CSV generated:

<img width="513" alt="screen shot 2018-06-26 at 10 19 31 am" src="https://user-images.githubusercontent.com/7063154/41919001-7d437c2a-792b-11e8-9a4e-ba9f7936a4ef.png">

#### error

the below error occurs for both the CSV and tab downloader

```
WD php: ParseError: syntax error, unexpected ';' in module_load_include() (line 57 of                                           [error]
/var/www/html/sites/all/modules/tripal/tripal/includes/TripalFieldDownloaders/TripalCSVDownloader.inc).
ParseError: syntax error, unexpected &#039;;&#039; in module_load_include() (line 57 of /var/www/html/sites/all/modules/tripal/tripal/includes/TripalFieldDownloaders/TripalCSVDownloader.inc).
Drush command terminated abnormally due to an unrecoverable error.                                                              [error]
```

**Comment by bradfordcondon** [comment]
Here is what I added to get the files to be created.

What's curious is that the first few lines i pasted should prevent the error from happening, but they check the array and not the $entity object.

```php
   // If this field is not present for this entity then add an empty
       // element and move on.
       if (!array_key_exists($accession, $this->fields2terms[$site][$bundle_name]['by_accession'])) {
         $col[] = '';
         continue;
       }
  // Get the field from the class variables.
       $field_id = $this->fields2terms[$site][$bundle_name]['by_accession'][$accession];
       $field = $this->fields[$site][$bundle_name][$field_id]['field'];
       $instance = $this->fields[$site][$bundle_name][$field_id]['instance'];
       $field_name = $field['field_name'];
//bradford added this logic below!
        if (!property_exists($entity, $field_name)){
             $col[] = '';
            continue;
            }
       // If we only have one item for this value then add it.
       if (count($entity->{$field_name}['und']) == 1) {
         $value = $entity->{$field_name}['und'][0]['value'];

```

because the field does in fact exist on the feature pages, i am hesitant to call this the solution though.

**Comment by spficklin** [comment]
If the field is missing as a property from the entity then it was not attached to the entity.  The Downloader only attaches fields to entities that are specified in the bundle collection.    The code which gets the fields that need loading is here (line 326):
https://github.com/tripal/tripal/blob/06cb6795c0c217e836be181e18f33af3c607c3db/tripal/includes/TripalFieldDownloaders/TripalFieldDownloader.inc#L322-L330

Then further down the entity is loaded but only with the desired fields:
https://github.com/tripal/tripal/blob/06cb6795c0c217e836be181e18f33af3c607c3db/tripal/includes/TripalFieldDownloaders/TripalFieldDownloader.inc#L344

Later, in the CSV downloader when the entity is formatted for printing you see this code:
https://github.com/tripal/tripal/blob/06cb6795c0c217e836be181e18f33af3c607c3db/tripal/includes/TripalFieldDownloaders/TripalCSVDownloader.inc#L34-L57
That's the location where you added you fix.    Notice that it's iterating through a list of "printable fields".  It is possible to have multiple content types with different fields in the collection.  So, this printable fields is the list of all fields, regardless if they belong to any given content type.  The check on line 45 is supposed to skip a field if it does not belong to a content type.  But in your case the fields to belong to the content type so it moves past that and weirdly you don't have the field attached so it has no value.

I'm wondering, when your collection was added to the database are you certain you added the same field list for all content types?  If the field is missing from one but present in the other then it will be attached to entities of one but not the other.

**Comment by bradfordcondon** [comment]
>I'm wondering, when your collection was added to the database are you certain you added the same field list for all content types? If the field is missing from one but present in the other then it will be attached to entities of one but not the other.

I linked the entities that did or did not cooperate with the field for download.  THey all have the protein sequence field populated with a sequence which is why im a bit puzzled.  edit; they are also all the same bundle type.

**Comment by spficklin** [comment]
What matters is the field specified in the bundle collection, not the fields that are on the page you view.  Can you confirm that the bundle collection records have the fields you are hoping to have?

**Comment by bradfordcondon** [comment]
>I'm wondering, when your collection was added to the database are you certain you added the same field list for all content types? If the field is missing from one but present in the other then it will be attached to entities of one but not the other.

>What matters is the field specified in the bundle collection, not the fields that are on the page you view. Can you confirm that the bundle collection records have the fields you are hoping to have?

@spficklin the collection was created via Elasticsearch so its possible something strange is happening there.  That said I think you just supply a list of entities and the fields, right?  The collection was made in one transaction so i dont know why/how it would attach for some but not all.

   Is there some way I can check the status of the bundle collection record fields?  Particularly for individual entities in the collection, as the field is attached for some but not all?

Here is the collection if i click "View"
![screen shot 2018-06-28 at 7 50 44 am](https://user-images.githubusercontent.com/7063154/42032573-00043f96-7aa8-11e8-915d-d26c6e569e02.png)

**Comment by laceysanderson** [comment]
I'm uncertain from the above conversation if the PR submitted fully fixes the problem. If it does, @almasaeed2010 can you close this issue? I'm unable to duplicate the problem to confirm

**Comment by almasaeed2010** [comment]
I'd ask @bradfordcondon if it's appropriate to close, but we are not longer experiencing this issue live.

**Comment by bradfordcondon** [comment]
i dont think the below is resolved so we should leave open. 

>The check on line 45 is supposed to skip a field if it does not belong to a content type. But in your case the fields to belong to the content type so it moves past that and weirdly you don't have the field attached so it has no value.

put another way, the check was added but i dont think it resolved the problem that the situation should not have arisen.
