### ISSUE TITLE
Ability to control which Tripal panes are shown on page load.

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#48]
My Perspective:
My users are strongly against the long page of content... Thus the default Tripal2 display was really well suited to them :-) I like the new Tripal3 default but would like to only show one pane by default not all of them...

More general suggestion:
It would be good to have the ability to configure in "Manage Display" whether a Tripal pane is shown on page load or not. This way admin could choose which panes to display to their user and thus better control their first impression. The default could remain as it is (all panes on) or be changed to only summary shown by default (more Tripal2-like) based on community input. I'm good either way :-)

**Comment by laceysanderson** [comment]
First suggestion has been solved by @shawnawsu :-) Now only the summary shows by default. However, this behaviour is not configurable. For example, if I wanted to show the most helpful panes but not all of them by default, I couldn't do that. Do we want to revisit having a configuration option for the in the "Manage Display" settings of the Tripal Pane? 

@spficklin what do you think? This maybe isn't necessary for the first release as @shawnawsu's current fix meets my specific needs.

**Comment by shawnawsu** [comment]
So there is a quick fix for this just while it's decided if the configuration option is the best bet. All you need to do is go into "Manage Display" and remove the class 'hideTripalPane' from the panes you want to show on load. Or add it to ones you don't want shown on load (like summary).

**Comment by spficklin** [comment]
How about we add a checkbox to the field formatter settings form so that our non-tech users don't have to worry about messing with classes @shawnawsu

**Comment by shawnawsu** [comment]
@spficklin checkbox now available for testing on 7.x-3.x-dashboard. Will require deleting and re-adding existing content types or rebuilding the display for the content type by "Applying Default Tripal Layout" to test the new functionality.

**Comment by laceysanderson** [comment]
I just tested this functionality and it works great 👍 
Since this is now merged into the main 7.x-3.x branch, I'm marking this issue as closed :-)
