### ISSUE TITLE
Unwarranted warnings when checking for new fields

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#481]
### System information

* Tripal Version: 3.x-dev
* Drupal Version: 7.x

### Issue description
I'm receiving a large number of warning on my Manage Fields page when checking for new fields.

##### Case 1: System tries to add a Chado Propery field even though it already exists.
For example, when checking for new fields on my publication content type, I see the following warnings:
```
A field of type tpub__publisher already exists, yet a property wants to use the same term. The property cannot be added.
A field of type tpub__year already exists, yet a property wants to use the same term. The property cannot be added.
```
This is because those fields already exist as shown in the following screenshot:
![screen shot 2018-06-26 at 12 22 00 pm](https://user-images.githubusercontent.com/1566301/41931530-9699d52e-793b-11e8-9d2f-a7fdbedc5299.png)
Note: I have done no customizing to this content type. All of the fields added here were added automatically by Tripal earlier and have not been changed.

##### Case 2: missing the "term_vocabulary" setting
For example, when checking for new fields on the gene content type, I see the following warnings:
```
    The field instance, data__accession, is missing the "term_vocabulary" setting. The field instance cannot be added. Please check the field settings.
    The field instance, obi__organism, is missing the "term_vocabulary" setting. The field instance cannot be added. Please check the field settings.
    The field instance, data__sequence, is missing the "term_vocabulary" setting. The field instance cannot be added. Please check the field settings.
    The field instance, data__sequence_length, is missing the "term_vocabulary" setting. The field instance cannot be added. Please check the field settings.
    The field instance, data__sequence_checksum, is missing the "term_vocabulary" setting. The field instance cannot be added. Please check the field settings.
    The field instance, data__sequence_coordinates, is missing the "term_vocabulary" setting. The field instance cannot be added. Please check the field settings.
    The field instance, ogi__location_on_map, is missing the "term_vocabulary" setting. The field instance cannot be added. Please check the field settings.
    The field instance, schema__alternate_name, is missing the "term_vocabulary" setting. The field instance cannot be added. Please check the field settings.
```
As you can see in the term column of the following screenshot, the term is set for each of these fields:
![screen shot 2018-06-26 at 12 29 39 pm](https://user-images.githubusercontent.com/1566301/41931880-9ec2e348-793c-11e8-9481-1504ca3c398d.png)
The error is being generated here: 
https://github.com/tripal/tripal/blob/7.x-3.x/tripal/api/tripal.entities.api.inc#L700-L705
and checking $details['settings'] confirms that the term information is missing... clearing the cache multiple times does not solve the problem...

#### Steps to reproduce
1. Navigate to the "Manage Fields" page for a Tripal Content Type. For example, Admin >Structure > Tripal Content Type > Gene > Manage Fields.
2. Click on " + Check for new fields" link near the top of the page.

**Comment by bradfordcondon** [comment]
confirmed that i'm also experiencing this.

<img width="1365" alt="screen shot 2018-06-26 at 3 19 58 pm" src="https://user-images.githubusercontent.com/7063154/41934301-6bc54108-7954-11e8-8f7f-eaa3582109f6.png">

**Comment by spficklin** [comment]
@laceysanderson I don't get the messages about the tpub__publisher field already existing.

@bradfordcondon for your module defined fields you'll need to add the term_vocabulary, term_name and term_accession elements in your  hook_bundle_instances_info() functions.  For example:

```php
$field_name = 'taxrank__infraspecific_taxon';
    $info[$field_name] = array(
      'field_name' => $field_name,
      'entity_type' => $entity_type,
      'bundle' => $bundle->name,
      'label' => 'Infraspecific Taxon',
      'description' => 'The Infraspecific Taxon.',
      'required' => FALSE,
      'settings' => array(
        'auto_attach' => TRUE,
        'chado_table' => 'organism',
        'chado_column' => 'type_id',
        'base_table' => 'organism',
        'term_vocabulary' => 'TAXRANK',
        'term_name' => 'infraspecific_taxon',
        'term_accession' => '0000046',
      ),
      'widget' => array(
        'type' => 'taxrank__infraspecific_taxon_widget',
        'settings' => array(
          'display_label' => 1,
        ),
      ),
      'display' => array(
        'default' => array(
          'label' => 'inline',
          'type' => 'taxrank__infraspecific_taxon_formatter',
          'settings' => array(),
        ),
      ),
    );
```
As an aside, that term information is already part of the TripalField classes you created.  So, to make a better fix, if that information is missing we should change the code in the tripal_create_bundle_fields function to check the class and automatically populate those missing elements from the class.

**Comment by bradfordcondon** [comment]
@spficklin many of those are chado fields ie `data__sequence`

**Comment by spficklin** [comment]
Yes, @laceysanderson is currently fixing those.

**Comment by laceysanderson** [comment]
The referenced PR solves Case #2.

## Case 1: 
```
A field of type tpub__publisher already exists, yet a property wants to use the same term. The property cannot be added.
A field of type tpub__year already exists, yet a property wants to use the same term. The property cannot be added.
```
This is due to there being tpub:publisher & tpub:year properties in my pubprop table. Those terms are also used by pub.pyear and pub.publisher. This causes a conflict...
All my publications were loaded by the Tripal2 pubmed importer so it must have added the year and publisher into the prop table? If so, there will be a number of other sites with this error... Thoughts on the best way to resolve it?

**Comment by spficklin** [comment]
Yes, at one point the pub importer did load to both tables for some fields.  I'm not sure if loads to both now or not.   I think the thinking at the time was that many of those columns in the pub table really are properties and so for consistency they were added to the pubprop table.   So, we obviously don't want to continue with that practice, but even if we fix the importer not to do that we need to deal with the issue.  One suggestion would be to check for these cases specifically for the pub table in the tripal_chado_bundle_[fields/instance]_info functions. 

Edit: This suggestion wouldn't be unprecedented as we already have some checks to ignore properties added by some of the analysis modules.

**Comment by laceysanderson** [comment]
I would be content with the check causing the pub properties for publisher and year to be ignored. Surely no one would ignore the fields in the base table leaving them null and only store those as properties, right?

**Comment by spficklin** [comment]
I believe use case 1 was solve by this PR:  #574.  It was merged so I'm going to mark this issue closed.  Please reopen if there's still something we missed.
