### ISSUE TITLE
When content is publishing the site is unusable

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#486]
### System information

* Tripal Version:  3.x
* Drupal Version: 7.x
* PostgreSQL Version:  N/A
* PHP Version: N/A

### Issue description

When publishing lots of content the site hangs.  Visitors can't pull anything up.   This is a major problem.

**Comment by almasaeed2010** [comment]
I think this issue can be closed in favor fo #530 which has a PR already submitted for it.
