### ISSUE TITLE
Documentation Improvement - Tripal README.md Intro & Installation Link

### ISSUE THREAD

**Issue by htjjen** [tripal/tripal#487]
The link under Installation is invalid. Perhaps it should be updated to either https://tripal.info/tutorials/v2.x/installation or https://tripal.info/tutorials/v3.x/installation?

Also, may I propose some minor changes to the Introduction section of the same [README.md file](https://github.com/tripal/tripal/blob/7.x-3.x/README.md) (before **Features**)

_____________
Background:
As a beginner contributor, I'm working on an assignment for my technical writing course, which requires students to make real-world revisions and have them accepted.

I will follow the [Guidelines](https://github.com/tripal/tripal/blob/7.x-3.x/CONTRIBUTING.md) when making a PR after my revision.  Please feel free to correct me if I missed anything.  Thank you!

**Comment by bradfordcondon** [comment]
Hello,
Thank you for spotting the dead link!  You are correct it should link to https://tripal.info/tutorials/v2.x/installation or https://tripal.info/tutorials/v3.x/installation (we are just shy of officially releasing version 3 so for now we might need to link to both versions?)

If you have further improvements for the README we'd be happy to see them.

Thanks!

**Comment by htjjen** [comment]
@bradfordcondon  Thank you for your reply!

I have made the changes and submitted a pull request using the template. Please feel free to let me know if you'd like me to change anything. Thank you!

**Comment by bradfordcondon** [comment]
hi @htjjen i replied in your PR but I'll also say here:  i want @spficklin to approve your changes, and he is on vacation.  If thats a problem for your school deadline please let me know, I have tripal submodule repos that I am the sole maintainer and can promise you faster turnaround.  For example:

* https://github.com/tripal/tripal_analysis_expression
* https://github.com/statonlab/tripal_alchemist

Let me know if I can help, or reach out to me on twitter @bradfordcondon

Thanks for your contribution!

**Comment by htjjen** [comment]
Hi @bradfordcondon , thanks again for all of your help. My assignment deadline is July 13. My goal for the assignment is to edit documentation. I don't have much knowledge in biology but I'll do my best. If you have any specific documents in mind, please feel free to let me know. Meanwhile, I'll keep exploring.

**Comment by bradfordcondon** [comment]
merged.  Thanks @htjjen and good luck.

**Comment by htjjen** [comment]
@bradfordcondon  Thank you very much!
