### ISSUE TITLE
dbxref widget fails with no warning error

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#489]
### System information

* Tripal Version: 3

### Issue description
On multiple sites, editing the dbxref entry (Cross reference field) for a record does nothing.  revisiting the edit page shows the dbxref as it originally appeared. I tried editing, deleting, and adding a dbxref with the widget: they all do nothing.

I've tested attached to publication and to analysis.

### thoughts

I can't  find it, but didnt we just make changes to the widget validation/submission methods?     We should verify the other widgets as well.

**Comment by laceysanderson** [comment]
Marking this as a potential bug only because I don't have the time to test it to make sure it's repeatable. That said, if this is happening, it's definitely a release blocker.

**Comment by shawnawsu** [comment]
I'm not sure which field this is referencing, is it this one "database cross reference (SBO:0000554)"? If it is I am not finding this on my local with the most recent tripal module.

**Comment by bradfordcondon** [comment]
after deleting and re-adding the field this error is resolved on latest master.
