### ISSUE TITLE
Chado Views error when cache is cleared.

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#49]
I recieve the following chado views error repeated 7 times whenever I clear the cache.

````
Notice: Undefined index: type in tripal_chado_views_views_data() (line 221 of /var/www/XXX/sites/all/modules/tripal/tripal_chado_views/tripal_chado_views.views.inc).
````

**Comment by spficklin** [comment]
I cannot reproduce this now so I assume it's fixed in the 7.x-3.x branch. Please reopen if it is still there after you update.
