### ISSUE TITLE
Remote Field fails if content types are renamed.

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#491]
## BUG/ERROR report

Originally reported when testing PR #439

### System information

* Tripal Version: 3-dev
* Drupal Version: 7.x

### Issue description
If admin of remote sites change the `name` of their content types the Remote Field will not work. This seems to be due to it not using the configured query. For example, when my organism content type is re-named to `Species` I see the following error in my remote field (configured to point at my own dev site):
![](https://user-images.githubusercontent.com/1566301/41997949-be706190-7a16-11e8-9127-557d9000780e.png)
This is despite my field being configured to query `Species?genus=Lens&species=culinaris` [see config](https://user-images.githubusercontent.com/1566301/41828883-eb1e22dc-77f4-11e8-878a-ca5f777be954.png). I've confirmed that changing the `name` back to `Organism` fixes the field.

#### Steps to reproduce

1. Set-up a remote field on your organism content type and confirm it works.
2. Edit the content type at Admin > Structure > Tripal Content Types > Organism > Edit and change the Name: Species.
3. Clear the cache and then refresh your organism page. Your field which was working will now be showing an error.

**Comment by shawnawsu** [comment]
Hi @laceysanderson I just tested this on my local and am unable to reproduce, ie the query does change when I change it in the field settings of the remote data field. Can you confirm this is still an issue?

**Comment by almasaeed2010** [comment]
Hello @laceysanderson and @shawnawsu 

I tested this by following the steps to reproduce mentioned above and managed to replicate the issue:

This is the error I get:

<img width="1015" alt="screen shot 2018-07-24 at 9 02 18 am" src="https://user-images.githubusercontent.com/1512664/43140436-fcd6e786-8f21-11e8-878b-7dccfaac6f60.png">

**Comment by almasaeed2010** [comment]
I am also getting this error now:

```
Notice: Undefined variable: remote_entity_link in remote__data_formatter->view() (line 151 of /Sites/Tripal/sites/all/modules/tripal/tripal_ws/includes/TripalFields/remote__data/remote__data_formatter.inc).
```

**Comment by spficklin** [comment]
Okay, I have submitted a fix via a PR for this.  Can you both test it and let me know how it goes?

**Comment by laceysanderson** [comment]
Fixed via PR.
