### ISSUE TITLE
CDS field does not support CDS loaded via FASTA loader only

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#494]
## Feature Request/Discussion
The CDS field was fixed in this PR by @spficklin  https://github.com/tripal/tripal/pull/453
The field looks for CDS in the `load` function starting with the featureloc table:

```php
$feature = chado_expand_var($feature, 'table', 'featureloc', $options);
    $featurelocs = $feature->featureloc->feature_id;
```

This works so long as CDS were loaded via the GFF.  If a user loaded the CDS sequences using the FASTA importer, specifying the relationship to a parent feature that way, there would be no `featureloc` entry and the field would show no results.

The field should therefore look in feature_relationship as a backup if no results or perhaps via a admin settings form.  (I'm less in favor of the form since this will likely be lost to most users).

### Your Specific Use Case
doesn't  affect HWG but there might be a site out there that has CDS not loaded via GFF.

**Comment by laceysanderson** [comment]
Closing as there has been no movement on this in over a year. If someone is loading CDS by means other then GFF and runs into this problem, they can report the error then.
