### ISSUE TITLE
Publication page layout is a mess after first installation

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#496]
### System information

* Tripal Version:  3.x
* Drupal Version: 7.x
* PostgreSQL Version: N/A
* PHP Version: 7.2

### Issue description

On a fresh in stall of Tripal, when following the online User's Guide it instructions the user to add a publication.  After saving the publication many of the fields are not in a Tripal Pane and it looks like a mess:

![screenshot from 2018-06-29 20-11-14](https://user-images.githubusercontent.com/1719352/42120919-a2300346-7bd8-11e8-87df-26cc6da0a7a8.png)

If I go back to the Publication content type and re-apply the default layout and click "Save" then it fixes the problem.  Those fields that are showing up without being in a Tripal Pane look like they are disabled but they still show up.

**Comment by shawnawsu** [comment]
@spficklin  

Publication is the only content type with custom handling in the tripal_ds module. It looks like a bunch of field names changed, did that happen? If it did, can we connect to go over the new preferred layout?

**Comment by spficklin** [comment]
I don't know how field names changed.  Do you know the before and after names of the fields?   Let's chat when I'm back in town.

**Comment by shawnawsu** [comment]
Apparently, there was a problem with my local, when I delete the publication content type and rebuilt it half the fields disappeared which is why I thought fields were renamed. They are not renamed, they just disappeared.

Given that I had another look and found the problem. I pushed a fix in pull request #508.

**Comment by laceysanderson** [comment]
Merged PR fixes the publication page so it's no longer a mess 👍 

I wonder if we shouldn't discuss a better default though. I think it would be pretty generic to change the settings as follows and **it would show a lot more information by default**. Currently it's annoying for an admin to drag every single chado property into a pane ;-) ([screenshot of settings](https://user-images.githubusercontent.com/1566301/42963500-a493617c-8b51-11e8-80a8-eac311d79cc7.png))

- pull the abstract out of the summary table but within the summary pane
- show all other chado property fields in an "Metadata" pane
- also show the following fields in the "Metadata" pane: publisher, publisher location, page numbers, year, issue, series name, volume, title of the volume.

![firefox_screenshot_2018-07-19t18-44-20 909z](https://user-images.githubusercontent.com/1566301/42963488-935e6bd6-8b51-11e8-8502-a2fc0479816b.png)
