### ISSUE TITLE
analysis type field is not nullable

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#499]
### System information

* Tripal Version: 3

### Issue description
<img width="1429" alt="screen shot 2018-07-02 at 4 58 03 pm" src="https://user-images.githubusercontent.com/7063154/42186043-1b74dda2-7e19-11e8-9d4d-9023a5149e7b.png">

The analysis type field is a property.  There's no requirement I'm aware of for it to be a required field.

**Comment by spficklin** [comment]
I believe this has been fixed with a PR before the v3.0-rc3 release.

**Comment by spficklin** [comment]
Ooops.. shouldn't have closed as this was added after the release.  If you have the up-to-date code then you may have to remove the old analysis_id field and re-add it.

**Comment by bradfordcondon** [comment]
confirmed fixed on current master.  I did indeed have to remove the fields and re-add them.  Thanks @spficklin .  I guess thats the next go-to suggestion after clearing the cache.
