### ISSUE TITLE
Disabled Tripal Panes still show up in the table of contents.

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#50]
When I disable a Tripal pane in manage display, it still shows up in the table of contents on the page. However when I click the link, the disabled pane doesn't show up in the right side. For example, the following screenshot shows the manage display page for a SNP with all but the summary and relationship panes disabled:
![screen shot 2017-03-30 at 8 03 20 pm](https://cloud.githubusercontent.com/assets/1566301/24533299/1036eb6e-1584-11e7-96b8-383dabcea335.png)

However, as you can see in the following screenshot, I still have all the links for the disabled panes in my table of contents:
![screen shot 2017-03-30 at 8 04 50 pm](https://cloud.githubusercontent.com/assets/1566301/24533316/2b798b2a-1584-11e7-8911-d32b9651e103.png)

This is not fixed by clearing the cache.

**Comment by spficklin** [comment]
This problem is now corrected in the 7.x-3.x branch.
