### ISSUE TITLE
Could not find details about the vocabulary

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#500]
### System information

* Tripal Version: 3.x-dev
* Drupal Version: 7.x
* PostgreSQL Version: 9.4.10
* PHP Version: n/a

### Issue description
When clearing the cache I was seeing a huge list of the following drupal_set_messages:
```
    Could not find details about the vocabulary: SUMMARY
    Could not find details about the vocabulary: PATO
    Could not find details about the vocabulary: OMIT
    Could not find details about the vocabulary: NCIT
    Could not find details about the vocabulary: FLOPO
    Could not find details about the vocabulary: OMIT
    Could not find details about the vocabulary: SEARCH
    Could not find details about the vocabulary: SUMMARY
    Could not find details about the vocabulary: SEARCH
    Could not find details about the vocabulary: NCIT
```

#### Solution
This was due to `db2cv_mview` missing ontologies I had recently added. Re-populating the materialized view at Administration » Tripal » Chado Schema » Materialized Views fixed the problem.

#### Steps to reproduce
1. Delete an entry out of db2cv_mview and clear the cache.
2. You should see a drupal_set_message telling you it could not find details about the vocabulary you deleted.

**Perhaps we should update the materialized view when we can't find a vocabulary? Or at least add to the message telling admin that updating db2cv_mview might solve the problem?**

**Comment by spficklin** [comment]
This mview was supposed to be updated when the site was prepared but we had a bug and it didn't work.  It has been fixed in a previous PR. Also, anytime you load a new ontology it automatically updates the mview.  So, you shouldn't ever get out sync again unless you manually or programatically add a new vocabulary.  We could update those API functions to automatically update the mview.

**Comment by laceysanderson** [comment]
In my case I was programmatically creating terms. I feel this will be more common though now that we need terms for each field. As such, I think we should update this materialized view in chado_insert_cvterm().

**Comment by spficklin** [comment]
Coming back to this. If we update the mview each time we call chado_insert_cvterm it would get updated way too often.  There are 156 calls in the tripal_chado.semweb.inc file alone.  I think the solution may be that we need a way to schedule updates of mviews as per request #353.    Would that work for you?

**Comment by laceysanderson** [comment]
Perhaps... However, I would want the ability to turn some mviews on for automatic update but not all. If we had that granularity and this was one was updated automatically by default then it could be a good solution. 

I do think regardless that we should update the warning to tell people that updating this mview might help. I had to dig through the code to solve this which shouldn't be necessary.

**Comment by spficklin** [comment]
Maybe we could allow you to trigger some mviews to be updated on a cache clear and set this mview to do so by default?

**Comment by laceysanderson** [comment]
I think this auto-updating of mviews should be independent of cache clearing. With the new entities, it's best if you greatly limit cache clearing on a production site. The db2cv_mview would definitely need to be updated at times when a cache clear isn't necessary. 

We could link automatic mview updates to drupal cron though. Allowing you to indicate which mviews should be updated by drupal cron with db2cv_mview updated by default should be enough for me :-)

**Comment by spficklin** [comment]
So it sounds like the request on issue #353 is what is needed.  Do you think this is a 3.0 stable release blocker?

**Comment by laceysanderson** [comment]
No, I think it can wait till the next point release since my issue only happens when programmatically inserting terms. 

*For 3.0 stable can we update the warning to mention updating the mview might help?*

**Comment by spficklin** [comment]
What warning do you mean?

**Comment by laceysanderson** [comment]
Originally, I was seeing a number of the following messages:
> Could not find details about the vocabulary: SUMMARY

This was not at all helpful as it implied that vocabulary didn't exist when it did. Instead, can we alter this message to mention that updating db2cv_mview might help? Something along the lines of

> Could not find details about the vocabulary: SUMMARY. If this vocabulary already exists, try re-populating db2cv_mview at Admin > Tripal > Data Storage > Chado > Materialized views.

**Comment by spficklin** [comment]
Ah, okay. Yes. We can do that.

**Comment by spficklin** [comment]
@laceysanderson you get a prize for submitting the 500th Issue!!

**Comment by spficklin** [comment]
Fix submitted (accidentally with PR).
