### ISSUE TITLE
OBO loader does not display details/allow editing

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#501]
### System information

* Tripal Version:3

### Issue description
`admin/tripal/loaders/chado_vocabs/obo_loader`

previously if you selected an OBO, it would populate the fieldset below.  this lets you double check the file, edit the file, etc.

<img width="692" alt="screen shot 2018-07-05 at 3 21 26 pm" src="https://user-images.githubusercontent.com/7063154/42343452-1ac0d79e-8067-11e8-8962-3ae2a11d61dd.png">

Now selecting an OBO does nothing.  It will still run the job but if you make changes I believe it just creates a new entry which can result in duplicate entries with no way to tell whihc is which, like so:

<img width="618" alt="screen shot 2018-07-05 at 3 22 53 pm" src="https://user-images.githubusercontent.com/7063154/42343520-5094f9cc-8067-11e8-98c9-34cde1db79b7.png">

**Comment by bradfordcondon** [comment]
this is the problem.
https://github.com/tripal/tripal/blob/b89cafa81fb50daa95ffd308c4a51a8ecde570bb/tripal_chado/includes/TripalImporter/OBOImporter.inc#L1679

Anyone know whats going on with `class_elements` here?
Setting it to `  return $form['obo_existing'];` fixes the issue, ill make a PR but im confused how this happened

**Comment by spficklin** [comment]
I believe this is resolved with the PR... marking closed.
