### ISSUE TITLE
ERROR during drush rapid installation

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#505]
At the end of the drush execution, I get the following error which I cannot seem to resolve. Any advice on this?
Environment: CENTOS 7

```
Adding permissions for the administrator to view, edit, create, and delete all the newly created content types.
The drush command 'role-add-perm administrator  view bio_data_1, create bio_data_1, edit bio_data_1, delete bio_data_1, view   [error]
bio_data_2, create bio_data_2, edit bio_data_2, delete bio_data_2, view bio_data_3, create bio_data_3, edit bio_data_3, delete
bio_data_3, view bio_data_4, create bio_data_4, edit bio_data_4, delete bio_data_4, view bio_data_5, create bio_data_5, edit
bio_data_5, delete bio_data_5, view bio_data_6, create bio_data_6, edit bio_data_6, delete bio_data_6, view bio_data_7, create
bio_data_7, edit bio_data_7, delete bio_data_7, view bio_data_8, create bio_data_8, edit bio_data_8, delete bio_data_8' could
not be found.  Run `drush cache-clear drush` to clear the commandfile cache if you have installed new extensions.

Installation is now complete. You may navigate to your new site. For more information on using Tripal please see the installation guide on tripal.info.
```

**Comment by bradfordcondon** [comment]
hi @risharde : I've been hesitant to respond because I'm not very involved in the rapid install.

just to confirm, after the install is complete, what happens if you execute this command?
```bash
drush role-add-perm administrator  view bio_data_1, create bio_data_1, edit bio_data_1, delete bio_data_1, view 
bio_data_2, create bio_data_2, edit bio_data_2, delete bio_data_2, view bio_data_3, create bio_data_3, edit bio_data_3, delete
bio_data_3, view bio_data_4, create bio_data_4, edit bio_data_4, delete bio_data_4, view bio_data_5, create bio_data_5, edit
bio_data_5, delete bio_data_5, view bio_data_6, create bio_data_6, edit bio_data_6, delete bio_data_6, view bio_data_7, create
bio_data_7, edit bio_data_7, delete bio_data_7, view bio_data_8, create bio_data_8, edit bio_data_8, delete bio_data_8
```

the drush command `role-add-perm` is part of the base drush package.  I see nothing wrong with the code.  I'll try and recreate the problem and get back to you.

**Comment by risharde** [comment]
Hey Bradford, it just shows drush 'error' message on the right side. Pure
vanilla install, can't explain why it's happening.

**Comment by bradfordcondon** [comment]
the same error message?  The drush command ... could not be found?

here's what i get.  (different error message, dunno why it cant find that permission, but you can see it at least found the drush role-add-perm command)

```
drush role-add-perm administrator  create bio_data_1
Could not find the permission: create                              [error]
```


edit:

for some reason i need to put everythign in quotes.

```
drush role-add-perm 'administrator' 'view bio_data_1'
Added "view bio_data_1" to "administrator"                         [success]
```

**Comment by shawnawsu** [comment]
What is the drush version you're using?

**Comment by risharde** [comment]
drush version 5.9 <--- I'm guessing it's too old?

**Comment by bradfordcondon** [comment]
It seems really likely thats the case, but i cant find the documentation online for version 5.  could you try updating and let us know if that resolves the problem?

**Comment by shawnawsu** [comment]
@risharde Did a drush version update fix this problem?

**Comment by risharde** [comment]
Haven't tried as yet but plan to do create a clean environment hopefully by
the end of the week and will report back on this

**Comment by risharde** [comment]
Using Drush 8.1, I get the following error instead:

> 
Enabling Tripal modules.
The following extensions will be enabled: tripal, tripal_chado, tripal_ds, tripal_ws, php, tripal_chado_views
Do you really want to continue? (y/n): y
Drush command terminated abnormally due to an unrecoverable error.                               [error]
Error: Can't use function return value in write context in
/var/www/html/sites/all/modules/tripal/tripal/includes/tripal.entity.inc, line 385
PHP Fatal error:  Can't use function return value in write context in /var/www/html/sites/all/modules/tripal/tripal/includes/tripal.entity.inc on line 385
The external command could not be executed due to an application error.                          [error]
2018-07-18 18:31:56
Tripal Job Launcher
Running as user 'admin'
-------------------
PHP Fatal error:  Call to undefined function tripal_launch_job() in /var/www/html/sites/all/modules/tripal/tripal/tripal.drush.inc on line 191
Drush command terminated abnormally due to an unrecoverable error.                               [error]
Error: Call to undefined function tripal_launch_job() in
/var/www/html/sites/all/modules/tripal/tripal/tripal.drush.inc, line 191
The external command could not be executed due to an application error.                          [error]

Now preparing the site by creating content types.
Drush command terminated abnormally due to an unrecoverable error.                               [error]
Error: Call to undefined function tripal_add_job() in
/var/www/html/sites/all/modules/tripal/tripal_chado/includes/setup/tripal_chado.setup.inc, line
76
PHP Fatal error:  Call to undefined function tripal_add_job() in /var/www/html/sites/all/modules/tripal/tripal_chado/includes/setup/tripal_chado.setup.inc on line 76
The external command could not be executed due to an application error.                          [error]

2018-07-18 18:31:57
Tripal Job Launcher
Running as user 'admin'
-------------------
PHP Fatal error:  Call to undefined function tripal_launch_job() in /var/www/html/sites/all/modules/tripal/tripal/tripal.drush.inc on line 191
Drush command terminated abnormally due to an unrecoverable error.                               [error]
Error: Call to undefined function tripal_launch_job() in
/var/www/html/sites/all/modules/tripal/tripal/tripal.drush.inc, line 191
The external command could not be executed due to an application error.                          [error]

Adding permissions for the administrator to view, edit, create, and delete all the newly created content types.
pg_query(): Query failed: ERROR:  relation "tripal_bundle" does not exist                        [warning]
LINE 1: SELECT name FROM tripal_bundle
                         ^ tripal_install.drush.inc:216
An error occurred.
Drush command terminated abnormally due to an unrecoverable error.                               [error]

**Comment by risharde** [comment]
I think it might be due to the fact that CENTOS 7 default php version is 5.4. I'll test with a higher version.

**Comment by risharde** [comment]
After using php 5.6 and Drush 8.1, I still remain with the final error:

>  
Adding permissions for the administrator to view, edit, create, and delete all the newly created content types.
The drush command 'role-add-perm administrator  view bio_data_1,     [error]
create bio_data_1, edit bio_data_1, delete bio_data_1, view
bio_data_2, create bio_data_2, edit bio_data_2, delete bio_data_2,
view bio_data_3, create bio_data_3, edit bio_data_3, delete
bio_data_3, view bio_data_4, create bio_data_4, edit bio_data_4,
delete bio_data_4, view bio_data_5, create bio_data_5, edit
bio_data_5, delete bio_data_5, view bio_data_6, create bio_data_6,
edit bio_data_6, delete bio_data_6, view bio_data_7, create
bio_data_7, edit bio_data_7, delete bio_data_7, view bio_data_8,
create bio_data_8, edit bio_data_8, delete bio_data_8' could not be
found.  Run `drush cache-clear drush` to clear the commandfile cache
if you have installed new extensions.

**Comment by shawnawsu** [comment]
Can you please do a `drush status` in that environment and reply to this ticket with the results?

**Comment by shawnawsu** [comment]
@risharde Is there any update on this?

**Comment by risharde** [comment]
Sorry for the delay! Tried to install using latest git but same issue.

**Comment by spficklin** [comment]
This issue is a bit old, and we've reworked the rapid install and tested it so I think this is probably resolved. Please comment if not.
