### ISSUE TITLE
Tripal Contacts submodule not creating Tripal content type automatically?

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#506]
Hi guys, not sure if this is an error or not but I was wondering if it was. When I enable Tripal Contact module in the modules section, the content type does not appear in Tripal Content Types. I have to manually create it. 

Is this normal?
Tripal Version 3 is being used, latest rc.

**Comment by bradfordcondon** [comment]
> When I enable Tripal Contact module in the modules section

Tripal Contact is a legacy Tripal 2 module, so no it should create a new content type.  In Tripal 3, contacts are entirely handled by Tripal Chado.

Tripal Chado doesn't appear to set up any contacts (I seem to remember it previously creating a "person" type contact) after looking at the install. 

I see in the issue for deciding which content types to ship Tripal with, we do plan to include contact, either a generic one or specific subtypes:
https://github.com/tripal/tripal/issues/441

**Comment by risharde** [comment]
Hey @bradfordcondon , thank you so much for responding to this! Because I've been using a dev environment that already has populated data, I assumed it was a content type already created. The fact that it isn't might be an advantage to me since my next project assignment has been to develop a contact module for Tripal which we intend to release to the public if all goes well. If you guys can hold back on going a contact type, then this module can be used to create one and free you guys up to focus on other developments. Let me know since depending on what decision you guys make, I wouldn't want this module to clash with something that you guys will come out with.

Thanks again, as always, I really appreciate your support, it's been really helpful!

**Comment by bradfordcondon** [comment]
Hi @risharde, no worries, happy to help.

If thats the case I recommend coordinating with core (well, tripal_chado) about the contact types.  I think @spficklin would prefer to cover the base tables in tripal core.  For example, Tripal Analysis Expression provides a loader for NCBI biomaterials, but the Bundle for the biomaterials base table is defined in core.

If your module will havel ots of sub-types, then maybe core should include a vanilla "contact" and your module would provide the subtypes.  Either way, you can create the bundles in your module "cautiously" by first checking if you can load the bundle with a given term (this is what tripal_chado does).

**Comment by spficklin** [comment]
related to issue #441
