### ISSUE TITLE
Is php xmlreader a requirement for Tripal 3 ?

### ISSUE THREAD

**Issue by isumoc** [tripal/tripal#513]
Ubuntu ships php xmlreader functionality in the php-xmlreader package.

Is is not mentioned in the documentation here http://tripal.info/tutorials/v3.x/installation/server-setup

**Comment by bradfordcondon** [comment]
hi @isumoc : 
thanks!    Looks like we use the XMLreader in at least the publication and BlastImporter requirements.  So its not included by default in Ubuntu and/or CentOS?

**Comment by spficklin** [comment]
@isumoc are you saying the documentation is missing the right package or that what we have in the instructions is not needed because Ubuntu ships with the right package already?  Sorry, I'm a bit confused.

**Comment by isumoc** [comment]
Ideally the PHP requirements might be noted somewhere separate from the OS.  That way people trying to use other operating systems, CM etc. would not have to try to build and maintain their own changelogs.

I'll take a look at what the latest ubuntu packaging does.  We are using FreeBSD which packages xmlreader separately.  Ditto any dev boxes on MacOS etc.
