### ISSUE TITLE
Documentation for T3 Installation recommends downloading the package via Drush

### ISSUE THREAD

**Issue by isumoc** [tripal/tripal#514]
Is the current best installation method for Tripal 3 to download the package using drush pm-download as documented:

drush pm-download tripal-7.x-3.0-rc1

Or should one do a git clone instead ?

**Comment by bradfordcondon** [comment]
We are currently at [rc3](https://github.com/tripal/tripal/releases/tag/7.x-3.0-rc3).  However the drupal projects page hasnt been updated so I would recommend doing a git clone instead




edit no theres a drupal release at https://www.drupal.org/project/tripal/releases/7.x-3.0-rc3

**Comment by spficklin** [comment]
I believe the documentation you are referring to @isumoc was the upgrade documentation?  If so, I have corrected it, but you can use a git clone or just change the version on the drush command to 7.x-3.0-rc3. I have updated the documentation to just be ```drush pm-download-tripal``` as that should pull the most recent version.

**Comment by spficklin** [comment]
I'm closing this as I think it's resolved, but if you have further questions please re-open
