### ISSUE TITLE
Programmatically get machine name of tripal content type and execute 'check fields'

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#515]
Hi @bradfordcondon @shawnawsu @laceysanderson 
I'm trying to determine if there is a method I can use to get the machine name of a Tripal Content Type / Bundle, is there a method in the api that can retrieve it that will accept the human readable version as a string and return this detail?

Also, I tried tracking back to see if there was a way to programmatically execute the equivalent of clicking the Check for new fields link in the Tripal Content Type manage fields section. Could you guys point me in the right direction?

Thanks!

**Comment by bradfordcondon** [comment]
> accept the human readable version as a string and return this detail?

I think `tripal_load_bundle_entity` is what you need. 
```php

/**
 * Retrieves a TripalBundle entity that matches the given arguments.
 *
 * @param $values
 *   An associative array used to match a bundle.  Valid keys may:
 *     - id: the numeric id of the bundle.
 *     - name:  the bundle name (e.g. 'bio_data_234')
 *     - label: the bundle label (e.g. 'Organism')
 *     - term_id: the term ID to which the bundle belongs
 *
 * @return
 *   A TripalBundle entity object or NULL if not found.
 *
 * @ingroup tripal_entities_api
 */
function tripal_load_bundle_entity($values) {
```

So you would call `tripal_load_bundle_entity(['label' => 'my bundle human readable name'])`.  Providing the `term_id` as well (IE the Chado.cvterm_id of the corresponding cvterm) would be a good idea as well.  In general using the cvterm is better than using the label, because the site users can change the labels.  The returned entity object has keys for most anything you would need for the bundle.

>Also, I tried tracking back to see if there was a way to programmatically execute the equivalent of clicking the Check for new fields link in the Tripal Content Type manage fields section

I'm curious about this as well.  I think we do it this way for a reason, but I could be wrong.  @spficklin @laceysanderson any ideas?

**Comment by shawnawsu** [comment]
You can check for new fields using `tripal_create_bundle_fields($bundle, $term)` which is an API function in the tripal.entities.api.inc file.

**Comment by risharde** [comment]
@shawnawsu thanks for your response, I'll try it!

**Comment by risharde** [comment]
@shawnawsu Could you explain the parameters required? The documentation says it needs the bundle name but I am also seeing $term. Maybe an example would help me out?

**Comment by shawnawsu** [comment]
Sure, here is an example:
````
function tripal_check_new_fields($bundle_name) {
  $bundle = tripal_load_bundle_entity(array('name' => $bundle_name));
  $term = tripal_load_term_entity(array('term_id' => $bundle->term_id));

  $added = tripal_create_bundle_fields($bundle, $term);
  if (count($added) == 0) {
    drupal_set_message('No new fields were added');
  }
  foreach ($added as $field_name) {
    drupal_set_message('Added field: ' . $field_name);
  }

  drupal_goto("admin/structure/bio_data/manage/$bundle_name/fields");
}
````

The `term` is the term object for the bundle which you can get using `tripal_load_term_entity`.

**Comment by shawnawsu** [comment]
@risharde Is there anything else you need on this issue?

**Comment by risharde** [comment]
Thanks, you guys solved it from your answers

**Comment by spficklin** [comment]
Looks like this is resolved.  Marking as closed.
