### ISSUE TITLE
Content type form submission fails when altering field to allow multiple values

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#518]
I'm using a nearly vanilla Tripal V3 installation while building the module as previously stated.
After creation of fields using the check for new fields for a specific Tripal Content Type
If I edit a new field that was autodetected and change the allow values to "Unlimited" and then try to submit data via the default tripal content submission form, 
the follow error is displayed and submission fails, any ideas?:

`
Could not save the entity: Could not insert Chado record into table: "contactprop": Array ( [contact_id] => 13 [value] => ok1 [type_id] => 2828 [rank] => 0 )
Cannot save entity
`

2828 cvterm_id tracks back in the database to:
`
cvterm_id	cv_id	name	definition	
2828                  2	      property	A generic term indicating that represents an attr...	
`

**Comment by bradfordcondon** [comment]
when you say vanilla, are you using hte latest relase of Tripal on the `7.x-3.x` branch?

I cannot replicate this problem: I set a chado property to unlimited, set two values for it, and submitted, and the property was updated appropriately.

![screen shot 2018-07-30 at 11 58 12 am](https://user-images.githubusercontent.com/7063154/43408652-e3d35fee-93ef-11e8-8c6e-707fa76388e7.png)
 
properties in db aftewards:

<img width="962" alt="screen shot 2018-07-30 at 11 59 40 am" src="https://user-images.githubusercontent.com/7063154/43408746-157cf3ca-93f0-11e8-8a48-03ee7ee8f68d.png">

**Comment by shawnawsu** [comment]
Hi @risharde,

Your project seems pretty complicated and we're having a hard time wrapping our heads around each individual ticket. Would you be open to setting a meeting where you give us a run down of what you're doing? Maybe we can also tackle a few tickets while we're at it?

Thanks!
Shawna

**Comment by risharde** [comment]
Hi @bradfordcondon I'm not sure if there's something missing with how I am doing it. Remember I'm creating a new Tripal Content Type and adding the fields programmatically. When I do it that way, it seems only the Genus field is having this strange issue of showing up as 'Text' in the manage fields section and not accepting any input.

Also, yes I am running 3.x latest branch via Drupal official module page

@shawnawsu A meeting sounds good but it really isn't something difficult. I'm basically trying to create a new tripal content type programmatically. So far, the following steps were needed
1. Create the actual content type
2. Add fields which I learnt was actually called 'properties'
3. Be able to apply the check new fields for the tripal content type so users don't have to do that after they install the module.
4. Change some of the default elements from the default text fields to various types like select lists etc (I was able to do this by myself successfully so far and will release that via documentation)

All questions asked are based on the specific steps I had challenges with. In the process of all this, I'm hoping I will get some time to write some documentation for others out there who want to build on Tripal.

**Comment by shawnawsu** [comment]
Hi @risharde,

There are a bunch of updates in the 7.x-3.x branch on github, I would recommend pulling that down instead of using the Tripal 3 release candidate version that's out on drupal.org. I would do this until we have the official Tripal 3 released in September.

I think a meeting would be really helpful for all. Do you have a github repo @bradfordcondon  and I can have a look at before we spend some time tackling tickets? I get the feeling our schedules might be wildly different. I am currently on the west coast of the US, Bradford is on the east coast. What's your timezone (plus or minus GMT is good)? Also, what days in the next two weeks work best for you?

Thanks!
Shawna

**Comment by risharde** [comment]
Hi @shawnawsu , my sincerest apologies for the delay in response! It seems I am using the github branch, my mistake! I am in the process of doing a full re-install to retest this issue just incase.

I currently have a gitlab repo at the moment which can be found here, didn't want to release this until I am sure it's stable but since you requested it, here it is: https://gitlab.com/TreeGenes/tripal_contact_profile

I should be available the following week if you guys can sync and let me know when you would be available. Please let me know. The only current issue holding back my release is:
https://github.com/tripal/tripal/issues/517

For some reason, the field is of type text instead of Chado Property and I suspect it is because there is already a genus field already being used by organism and for some reason it's using the settings from there when it probably shouldn't.

**Comment by shawnawsu** [comment]
Hi @risharde, 

Can you do Monday morning? Bradford and I are both free anytime Monday.

Thanks,
Shawna

**Comment by spficklin** [comment]
There's been no further discussion since August.  I'm assuming this is resolved. Please comment if not.
