### ISSUE TITLE
Disabling a module that defines custom fields causes many errors

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#519]
### System information

* Tripal Version: 7.x-3.x
* Drupal Version: 7.59
* PostgreSQL Version: 9.6
* PHP Version: 7.1

### Issue description

When we disable a custom tripal module that defines fields, the fields don't get removed and a long list of errors start showing up in the `manage fields` page.

#### Steps to reproduce

After enabling a module that defines fields such as [tripal_analysis_expression](https://github.com/tripal/tripal_analysis_expression):
1. attach the field to a bundle. 
  Structure -> Tripal content types -> Organism -> manage fields -> + Check for new fields
2. make sure the field displays as expected
3. Disable the module

#### Error messages and screenshots

![image](https://user-images.githubusercontent.com/1512664/43153645-d74341fe-8f3f-11e8-9918-9635f23ea755.png)

```
Notice: Undefined index: sep__biological_sample in field_ui_existing_field_options() (line 1545 of /Users/Almsaeed/Work/DevSites/Tripal/modules/field_ui/field_ui.admin.inc).
Notice: Undefined index: sep__biological_sample in field_ui_existing_field_options() (line 1545 of /Users/Almsaeed/Work/DevSites/Tripal/modules/field_ui/field_ui.admin.inc).
Notice: Undefined index: sep__biological_sample in field_ui_existing_field_options() (line 1545 of /Users/Almsaeed/Work/DevSites/Tripal/modules/field_ui/field_ui.admin.inc).
Notice: Undefined index: sep__biological_sample in field_ui_existing_field_options() (line 1545 of /Users/Almsaeed/Work/DevSites/Tripal/modules/field_ui/field_ui.admin.inc).
Notice: Undefined index: sep__biological_sample in field_ui_existing_field_options() (line 1545 of /Users/Almsaeed/Work/DevSites/Tripal/modules/field_ui/field_ui.admin.inc).
Notice: Undefined index: sep__biological_sample in field_ui_existing_field_options() (line 1545 of /Users/Almsaeed/Work/DevSites/Tripal/modules/field_ui/field_ui.admin.inc).
Notice: Undefined index: sep__biological_sample in field_ui_existing_field_options() (line 1545 of /Users/Almsaeed/Work/DevSites/Tripal/modules/field_ui/field_ui.admin.inc).
Notice: Undefined index: sep__biological_sample in field_ui_existing_field_options() (line 1545 of /Users/Almsaeed/Work/DevSites/Tripal/modules/field_ui/field_ui.admin.inc).
```

**Comment by spficklin** [comment]
I'm going to remove the release blocker on this one. I've tried to dig into it to see if we can apply a quick fix before release but it's not going to be that straightforward.  

One additional thing to consider..  what happens to the fields that are defined by a module when the module is disabled but not uninstalled.

**Comment by bradfordcondon** [comment]
Because I had to look this up:

https://www.drupal.org/forum/support/post-installation/2011-06-02/difference-between-disabled-and-not-installed-module

when a module disables, its configuration is untouched.

Therefore, only when a module is uninstalled should the fields it is responsible for be uninstalled as well.

When a module is **disabled**, my gut says the fields should also be disabled but not removed. However, this causes the problems Abdullah reports above, as the fields may run API calls etc relying on the disabled module.

Therefore, its probably necessary to delete all associated fields and their data on disable.  If we can keep their configuration but unattach them, that would be best.

**Comment by spficklin** [comment]
Ah. I think I have an easy fix for this.  When I get a free moment I'll work on it.

**Comment by laceysanderson** [comment]
@spficklin since you've been too busy to get to this, can you explain your solution so someone else can take a stab at it?

**Comment by laceysanderson** [comment]
I talked to @spficklin regarding this issue:

> In the function that calls the load() on all the field classes, we just check if the module exists.  I believe if the module is disabled the drupal function for if a module exists will return FALSE.  If that's the case, we just don't call the load function.

So I think the ideal solution here is two-fold:
1. Ensure the field is disabled in the display when the module is disabled.
2. Ensure the load is not called when the module is disabled.

For the first task, this issue might be useful: https://www.drupal.org/project/entity/issues/2223397

For the second task, you will want to add a conditional around https://github.com/tripal/tripal/blob/7.x-3.x/tripal/includes/tripal.field_storage.inc#L61 that only executed the ::load() if the module implementing that field is enabled.

Based on your experience, this could be two separate PRs (one per task) or a single PR.
