### ISSUE TITLE
Alternate Relationship field formatters

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#523]
## Feature Request/Discussion

- [ ] does this feature attempt to solve an existing problem with Tripal?
- [x] are you open to developing or collaborating on an extension module if this is not a good fit for Tripal Core (no pressure here -just good to know upfront :-) )
- [x] do you **Need** this feature ASAP?

### Description

Currently the relationship formatter for Tripal 3 states all relationships in sentence form in a single-columned table. This is quite different from the format for relationships used in Tripal 2 with a multi-columned table per relationship type.

![relationship_formatter_screenshot_from_demo](https://user-images.githubusercontent.com/1566301/43369694-86674b6a-932f-11e8-8512-303575db6675.png)

#### Table per Relationship Type Formatter
This formatter would mimic the Tripal 2 format providing one table per remationship type with the columns shown in the above screenshot (name, uniquename, species, type of related item; eg. stock). I think this one belongs in core since it allows admin to mimic the old pages during upgrade.

~~Comma-separated List for a single relationship type.~~

~~This formatter would allow the admin to choose a single relationship type and either object or subject to display. Then it would simply show a list with the `name (uniquename)` for each relationship of the type. Choosing either subject or object in the formatter makes it flexible enough to handle any relationship type. Furthermore, it would link to the related page the same way the default formatter does.~~

~~Using this formatter the admin can display related items in the summary table (for example). I think this formatter would be generic enough and broadly useful to be included in Tripal Core.~~

### Your Specific Use Case

I need these two formatters as part of the upgrade of KnowPulse to Tripal3. I'm trying to make as few UI changes for the user as possible during this upgrade and thus would like to mimic the old relationship format. 

~~Additionally, I had modified templates in the past to include a list of related items in the summary table for quick jumping between types. For example, my Variant pages have a row for "Markers" in the summary table with a simple list of the features related to the current one via the "is a marker of" relationship. I need a way to duplicate this in Tripal 3 and thus will be developing the formatter regardless.~~

### Generally Applicable

I feel a "Table per Relationship Type Formatter" is generally applicable since it mimics the Tripal2 format. As such, some sites may prefer this format over the new one during upgrade in order to minimize the UI changes during upgrade.

~~I feel a "Comma-separated List for a single relationship type formatter" is generally applicable since it allows condensing of related items into the summary table and is a really simple, comma-separated format.~~

### Additional information/screenshots

I am going to immediately start on implementation of these formatters in such a way that they can be incorporated into core if it's decided they should be :-) This is because I need them regardless and it would be simple to separate them from core if the community decides they are not a good fit since they are single classes. :-)

**Comment by laceysanderson** [comment]
What is the convention on naming alternate formatters? `[cv_name]__[termname]_[shortdescriptor]_formatter`? Also, is there a place I can put it so it's automatically detected (e.g. `/includes/TripalFields/[cv_name]__[termname]/`)?

**Comment by spficklin** [comment]
Hi @laceysanderson I have no objections.  Do you already have this formatter implemented?  If so can you provide a screenshot for what it would look like?

How about this for a folder names:
```
sbo__relationship_table
sbo__relationship_csv
```
And the file could be
```
sbo__relationship_table/sbo__relationship_table_formatter
sbo__relationship_csv/sbo__relationship_csv_formatter
```

**Comment by laceysanderson** [comment]
This formatter is not quite implemented but I'm working on it right now. I'll add screenshots when it's done :-) Hopefully before the meeting on Friday.

**Comment by laceysanderson** [comment]
During implementation I decided the "Comma-separated List for a single relationship type" formatter should actually be an entire field type. This is in order to allow multiple lists one per relationship type and to allow these lists to live alongside the full relationship listing. As such, I've removed that formatter from this issue and will instead develop it separately -likely in tripal fancy fields.

**Comment by laceysanderson** [comment]
It's done! I can add a PR if we decide we want this formatter in core :-)

Notes: Since relationship tables are not very standard, this formatter will omit the uniquename and/or the species column if it's not available in the related table.

## Example Screenshot of the working formatter
![screen shot 2018-08-03 at 8 57 08 am](https://user-images.githubusercontent.com/1566301/43649996-dc04b7f4-96fb-11e8-84dc-83765fdfea76.png)

## Formatter Configuration
![screen shot 2018-08-03 at 8 58 42 am](https://user-images.githubusercontent.com/1566301/43649998-de22114e-96fb-11e8-9770-514a43e39e65.png)

**Comment by laceysanderson** [comment]
This was discussed at the user meeting today and it was decided I should submit a PR :-) 👍 

Additionally, it was decided that alternate formatters are a good candidate for core if they provide a display attempting to mimic Tripal2 which this one does. These alternate formatters would allow admin to maintain consistency of look through the upgrade and thus should be made available to all admin.

Formatters not attempting to mimic Tripal2 should still submit a feature request issue as this one did if you feel they are a good option for core.

**Comment by laceysanderson** [comment]
Merged 👍
