### ISSUE TITLE
tripal_get_active_jobs() throws error

### ISSUE THREAD

**Issue by par12005** [tripal/tripal#524]
### System information

* Tripal Version: 3.x
* Drupal Version: 7.56
* PostgreSQL Version: 9.5.7
* PHP Version: 7.0.30

### Issue description

When I call `tripal_get_active_jobs()` from anywhere I get the error seen below. I believe this is because in the [`tripal.jobs.api.inc`](http://api.tripal.info/api/tripal/tripal%21api%21tripal.jobs.api.inc/3.x) file on line 536 the `$jobs` variable is an array, and tripal is attempting to assign the `$jobs->arguments` property. There is an object in this context, the `$job` variable. Line 536 reads:
```$jobs->arguments = unserialize($job->arguments);```
I believe it should read:
```$job->arguments = unserialize($job->arguments);```
When I made this change I was not seeing the error anymore, and `tripal_get_active_jobs()` was working correctly.

#### Steps to reproduce
Call `tripal_get_active_jobs()`

#### Error messages and screenshots

```
PHP Warning: Attempt to assign property of non-object in /var/www/html/Drupal/sites/all/modules/tripal/tripal/api/tripal.jobs.api.inc on line 536 pid 30056
```

**Comment by almasaeed2010** [comment]
PR submitted #539

**Comment by par12005** [comment]
Thank you!
