### ISSUE TITLE
can the cv lookup tree ignore relationship types (ie not display as root terms?)

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#526]
## Feature Request/Discussion

- [x] does this feature attempt to solve an existing problem with Tripal?
- [x] do you **Need** this feature ASAP?

### Description

The cv browser displays relationship terms associated with the ontology as root terms, because they do not have any relationships.

this means that, for example, the gene ontology displays terms  ends_during and regulates (see image below) 

I propose that the mview which holds root terms ignore cvterms if the `is_relationship` column = 1

if @spficklin disagrees thats fine, we will ignore them within our field for our own purposes.  but i think ignoring them in general is probably a good idea (or maybe tucking htem all away in a "relationships" root node?.

### Additional information/screenshots
at:  https://hardwoodgenomics.org/cv/lookup/GO

<img width="606" alt="screen shot 2018-08-02 at 4 40 03 pm" src="https://user-images.githubusercontent.com/7063154/43609711-bf444172-9672-11e8-948b-c1fc8ee936be.png">

ignore the NFAT term: thats from a very obnoxious issue with very old go terms being inserted that arent in the new OBO.

**Comment by bradfordcondon** [comment]
@spficklin this is question for you:  do you approve if so we'll implement

**Comment by bradfordcondon** [comment]
no response so im assuming its ok to implement because i want it.

Alternatively maybe we want them in which case i can remove them in my cv_xray formatter.

**Comment by spficklin** [comment]
Apologies I missed this discussion request...

**Comment by bradfordcondon** [comment]
thanks @spficklin
