### ISSUE TITLE
Default tripal content types and viewer

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#527]
## Feature Request/Discussion

- [x] does this feature attempt to solve an existing problem with Tripal?
- [ ] are you open to developing or collaborating on an extension module if this is not a good fit for Tripal Core (no pressure here -just good to know upfront :-) )
- [x] do you **Need** this feature ASAP?

### Description

In our Tripal User's Meeting discussion on 2018-08-03 we had two discussion items related to content types. One was regarding issue #441 and the other was the overwhelming nature of the Content Type page when there are lots of content types.  We needed to finalize the list of content types, the "category" that each fell into and we decided we could take advantage of this focus to fix the content type page.
### Your Specific Use Case

The decision was made to 
1.  Create new modules in tripal (that will potentially be moved out as extension modules in future releases (e.g. Tv4):  tripal_genomic, tripal_genetic, tripal_germplasm_breeding.  
2.  Allow content types to specify a category
3.  Update the content type listing page to use a fieldset for each category, and also to provide a list of modules that can be used to support the content type categories (e.g. Staton Lab expression module)

**Comment by spficklin** [comment]
After some additional discussion in the #pmc channel of slack, it was decided not to create separate modules at this time in order to prevent sudden changes to current Tv3 users.  Instead we'll just organize the content types into nice groupings to make them easier to deal with.

**Comment by laceysanderson** [comment]
PR Merged
