### ISSUE TITLE
Need Relationship Widget

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#531]
## Feature Request/Discussion

- [x] does this feature attempt to solve an existing problem with Tripal?
- [x] are you open to developing or collaborating on an extension module if this is not a good fit for Tripal Core (no pressure here -just good to know upfront :-) )
- [x] do you **Need** this feature ASAP?

### Description

Currently there is no ability to edit relationships -the widget exists but the form has been commented out due to not being flexible enough to handle the different relationship tables.

### Your Specific Use Case

I seriously need this widget! Especially for feature, stock and project-based content types.

**Comment by bradfordcondon** [comment]
interesting.  I think it would be do-able, right?  Just much more form-like than our other widgets.  You'd pick if the attached entity is the subject or object, then choose the other partner (via name lookup i guess?  need to consider all tables it woudl attach to ) and finally select a cvterm for the relationship type (ideally dropdown from cvterms that are marked as IS_RELATIONSHIP)?  That's how i'd think of it anyway

**Comment by laceysanderson** [comment]
Yes, I think it should be do-able. There's already a form there that I assume was working in some respects it's just commented out. The in-line comments imply it was due to the differences in table structure and point to the load.

**Comment by spficklin** [comment]
@laceysanderson how are things coming along on this one. Do you need some assistance with it?

**Comment by laceysanderson** [comment]
I've got it started in https://github.com/tripal/tripal/tree/531-t3-relationship_widget. It's been going slow because I was working on automated tests for the form. I can prioritize functionality through so we can get this release out 👍

**Comment by laceysanderson** [comment]
I'm running into a number of deep-seated assumptions in this field which are making this take longer then expected:
 - assumes all base tables have an autocomplete. Ideally this would be fixed by making the autocomplete code generic so there actually is an autocomplete for all base tables.
 - assumes all base tables have a uniquename. This is used when looking up the subject/object if autocomplete was not used and causes a PDO error. It's also used in other places throughout the field so I'm tempted to add determination of the correct column to use to the field constructor.

There are also a number of outstanding bugs including:
 - the default for type selection (vocab + type name autocomplete) assumes the same vocabulary will be chosen for autocomplete but allows you to set different ones causing an unavoidable validation error.
- validation errors don't actually highlight the offending elements red.

_Likely more I haven't found yet_

**Comment by laceysanderson** [comment]
Since the addition of this widget is a new feature rather then a bug fix, I'm removing release blocker status and moving this issue to the Tripal 3.1 milestone. I will continue to work on it but feel free to comment if you need this widget ASAP.

**Comment by laceysanderson** [comment]
Now that 3.0 is released, I am adding back the release blocker tag. 
Justification: the more I work on the widget the more I find deep-rooted concerns in the field. I feel these issues are substantial enough for bug status and as such, must be fixed.

**Comment by laceysanderson** [comment]
Newest version of the widget (47f66b0fb1942412d9a54dfb894cf247efe6f95d) :
 - DOES NOT assume all base tables have a uniquename
 - re-uses the schema definition by saving it to the field object rather then regenerating it in each function.
- doesn't try to use a non-existent autocomplete
- highlights validation errors
- the default for type selection (vocab + type name autocomplete) can select different cvs for each relationship
- adds relationships reliably for all tables on both create and edit 🎉 

Outstanding Known issues:
 - we need autocomplete for all tables
 - testing of other options for relationship type entry
 - more automated testing

**Comment by laceysanderson** [comment]
Automated Testing now works on Travis CI including testing of validation 🎉 🎉 🎉

**Comment by laceysanderson** [comment]
I'm now feeling pretty good about automated testing and have decided to make a first release of this widget without the extra type select options (a solid widget is better then a buggy one with lots of features).

All that leaves outstanding for the first release is autocompletes for all tables.

**Comment by bradfordcondon** [comment]
this has been merged so im closing.

a child issue was created #762 for additional problems with the widget.
