### ISSUE TITLE
Creation of Content Type times out

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#533]
### System information

* Tripal Version: 3.x
* Drupal Version: 7.x
* PostgreSQL Version: N/A
* PHP Version:  N/A

### Issue description

Sometimes creation of content types results in a WSOD.  This seems to happen when there are too many properties in a table (e.g. feature table).

The solution is to create content types using a Tripal job.  So, we need to change the creation form so that it adds a job rather than try to create the type via the GUI.

#### Steps to reproduce
To reproduce this you have to a large site with lots of properties for a table.

#### Error messages and screenshots

Error log in Apache:

```
[Wed Aug 08 11:44:50.328442 2018] [php7:error] [pid 5003] [client 127.0.0.1:48422] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/html/includes/file.inc on line 2169, referer: http://localhost/admin/structure/bio_data/add
```

**Comment by bradfordcondon** [comment]
resolved.  Thank you.


@laceysanderson if you'd like to create a separate issue to allow job-free creation of bundles, but then job-launched attaching of fields (or another solution) please do so.
