### ISSUE TITLE
Data Search View Don't Show All Results

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#535]
### System information

* Tripal Version: 3
* Drupal Version: 7.59
* PostgreSQL Version: 9.6
* PHP Version: 7.1

### Issue description
Data search views that come with tripal (and other custom views at least on our site) are not showing the pager and are not responding to manual page changes. When adding `?page=2` to the url, it doesn't seem to affect it.

This behavior has been noticed on [hardwoogenomics](https://www.hardwoodgenomics.org/data_search/organism) and @laceysanderson's site.
#### Steps to reproduce
1. Go to /data_search/organism (demo site http://demo.tripal.info/3.x/data_search/organism)

#### Error messages and screenshots

No error messages appear

**Comment by bradfordcondon** [comment]
merged
