### ISSUE TITLE
Collaborative Development.

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#540]
How do we encourage and promote positive collaborative development between groups at different institutions.  What are the challenges? What works?

**Comment by bradfordcondon** [comment]
* [We created a website to showcase the modules we are working on ](https://statonlab.github.io/hardwoods_tripal_showcase/).  I dont know that its been particularly successful.  Similarly i dont know that the tripal.info module list has been useful for encouraging collaboration
* I think more informal participation in slack would be really helpful for this.  Even if its just people posting questions, we then have the chance to say 'that sounds cool' or 'hey i have something that does that already'.
* Tripal lab meetings? Groups demo 1 module, or showcase a whole bunch, format hugely undecided.  This gets us more open in terms of getting our stuff in front of new eyes
* Meetings doc asks people to list the modules they are working on this week/what they would be open to collaborate with with 1 sentence of what they do?

**Comment by laceysanderson** [comment]
I like the section on the meeting docs idea. I find most of the collaboration with me has been started by people jumping in when they hear I'm working on something or vise versa.

I also like the demo meetings idea but worry about more meetings and whole-heartedly agree that more slack participation would help!

**Comment by mestato** [comment]
Ditto the concern about more meetings. We used to have people demo'ing or explaining their modules in dev calls more often, and I would like to see that get started up again. It could be a standing agenda item with groups rotating who presents. As long as we keep it short (<10 minutes), I think that would be a great way to keep up with what everyone is doing.

**Comment by mestato** [comment]
I think the in person user meeting/training/collaboration fest in San Diego in January has also been effective at getting people to collaborate. It's great to meet someone in person after only knowing them online for months or years, and then to have the time to talk to them about their work one on one. How do we get more people there or get remote attendees to feel included?

**Comment by laceysanderson** [comment]
> Meetings doc asks people to list the modules they are working on this week/what they would be open to collaborate with with 1 sentence of what they do?

@spficklin can we add a this to the agenda for the next users call (Nov 13)?

**Comment by laceysanderson** [comment]
Another idea is to implement a "collaboration-wanted" tag on GitHub and encourage groups wanting to collaborate to tag their github project with it. This way we could add a link in the developers guide showing an updated list of people open to collaboration.

This idea goes hand-in-hand with my proposal to add a collaboration page to the developers guide with any advice, known pitfalls, etc.

**Comment by bradfordcondon** [comment]
>can we add a this to the agenda for the next users call (Nov 13)?

We have a "discuss at next meeting" tag :)

**Comment by spficklin** [comment]
Report:  we ran out of time to discuss more on this in the 11/13/2018 meeting.

**Comment by bradfordcondon** [comment]
pinging this issue: do we still want to discuss it next meeting?

We've added the module list to the documentation (https://tripal.readthedocs.io/en/latest/extensions.html)


The other suggestion

> Meetings doc asks people to list the modules they are working on this week/what they would be open to collaborate with with 1 sentence of what they do?

Do we want to try this next meeting?  I think thats maybe why i added the "discuss next meeting" tag, but then i didn't read the issue 😆 looks like its been kicked down the road every month...

**Comment by spficklin** [comment]
I'm going to close this out as I think we've the extensions page finished and the badges available. We need to do a better job of advertising this.  We can definitely improve on user engagement but I think this issue has served its purpose for now.
