### ISSUE TITLE
Enabling Ajax for Fields

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#541]
I noticed today that on my local dev site, entities are loading their fields using Ajax instead of preloading them on the server. However, this behavior is not happening on our live site and we'd like to know if it is possible to activate it?

**Comment by almasaeed2010** [comment]
I realized that this is the default behavior but enabling tripal_ds disables it.

**Comment by spficklin** [comment]
If you edit a content type and change the Field Display from "hide empty fields" to "show empty fields" then it loads the non "auto-attach" fields via AJAX.   Originally Tripal v3 loaded all fields via AJAX so that the pages would load quickly.  But many folks did not like fields that were empty to show up.

**Comment by spficklin** [comment]
But as @chunhuaicheng pointed out in issue #538 we probably should try to find a way to make AJAX work either way.

**Comment by almasaeed2010** [comment]
Since we know the pane where data is supposed to go to, then we have enough info to delete the pane if the returned data is not available. This however may create an unwanted effect of things disappearing after a few seconds so we could possibly load the panes as hidden by default and do a little css animations as we get data back from the server?

I'll try to look more into this to see if we can come up with a good solution.

**Comment by laceysanderson** [comment]
Listening in on this. I would Love a solution to have AJAX loaded fields while still hiding empty ones from my users!

**Comment by spficklin** [comment]
Just curious if you were able to figure anything out on this one?

**Comment by almasaeed2010** [comment]
Sorry I haven't gotten to this yet. Will work on it and update here soon.

Thanks!

**Comment by almasaeed2010** [comment]
I started working on this and it looks to me that it's easily doable.

tripal.js loads the fields and it can tell if there is content so it can easily broadcast via events to tripal_ds that a field has completed loading. From there, tripal_ds can check if the entire pane is empty and remove it if it is. We can also take this a step further and have tripal.js broadcast the start of loading which will allow tripal_ds to not hide the pane until it's ready (when ajax has completed).

I can implement this and push a branch up for testing if it sounds good?

**Comment by almasaeed2010** [comment]
The only concern is fields that are placed inside anything other than a tripal_pane such as tables.
Take the `description` field in an `organism` page for example, it's placed in a table by default but it can be moved to a list or something else so JS won't be able to predict how to remove it.

Maybe we can add more information to the returned response from the Ajax call to tell us the type of the parent element.

**Comment by spficklin** [comment]
Can you have the JS code remove the field instead of having back-and-forth with tripal_ds?  There will be problems with fields in tables but only as far as the coloring of rows goes.  I think some JS might be able to reset the 'odd' 'even' class names on those rows though easy enough.

**Comment by almasaeed2010** [comment]
Yeah that sounds good. I'll give this approach a try tomorrow and report back on how it goes.

Thanks!

**Comment by spficklin** [comment]
Thank you for working on it!!!

**Comment by almasaeed2010** [comment]
I submitted a PR for this to showcase how we'd go about implementing it. I don't think the PR is ready but it's there for easy pulling and testing. If anyone gets the chance to test it and experiment with it, it'd be greatly appreciated. 

If we do manage to get this working, I believe we'll see a huge difference in page loading times.

Thanks!

**Comment by laceysanderson** [comment]
PR Merged!

**Comment by spficklin** [comment]
Thanks all for the effort on this one!
