### ISSUE TITLE
Select List Views Exposed Filter for Tripal Fields

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#550]
## Feature Request/Discussion

- [x] does this feature attempt to solve an existing problem with Tripal?
- [x] are you open to developing or collaborating on an extension module if this is not a good fit for Tripal Core (no pressure here -just good to know upfront :-) )
- [x] do you **Need** this feature ASAP?

### Description

I need to be able to choose select list and/or autocomplete as the exposed filter form element for various Tripal Fields when designing my search views. Ideally there would be a very generic views handler that would select from the table the field is attached to finding the currently used values and using them to populate the list. I could also allow it to be configured to just provide all values from the linked table as a faster option. Autocomplete would query on the fly.

I would generically implement it for all foreign key fields and use tokens from the table the foreign key references to make the human-readable option generic. For example, for the feature table, you could use a select list for the organism_id, type_id and dbxref_id; for the organism_id select list the tokens available would be all columns from the organism table.

This is handled in Drupal by having two fields you can add in the views UI: `[field name]` for the straight textfield and `[field name] (Allowed Values)` for the select list. For Drupal Fields the allowed values are set in the instance settings and thus no querying is needed.

Are we content with two options in the views UI for each field attached to a chado foreign key? Also are we content querying for the options? Or should I require options be set in the views ui?

### Your Specific Use Case

Specifically I need:
- organism_id => scientific names
- type_id => cvterm name
- project/analysis => name

### Generally Applicable

I feel select lists in exposed filters are more friendly to users and general expected in web forms.

**Comment by laceysanderson** [comment]
After discussion with @spficklin:

**Clarification:** This would allow admin to add a select list or autocomplete exposed filter for many Tripal/Chado Fields where the values in the list match those already used in the chado table. For example, you could have a select list for a field connected to the feature.type_id where the options are the unique set of feature.type_ids (e.g. sequence_variant, genetic_marker, gene if those are the only 3 unique type_id in the feature table).

**My plan** would be to add a `TripalField::getValueList($keyword = NULL)` method to both TripalField and ChadoField classes. This method would retrieve a list of options for a select list when `$keyword = NULL` or a list of autocomplete options when `$keyword` is set. This allows the query retrieving the distinct list to be customized for custom fields. For non-Tripal/Chado fields I would default to a generic API function (`chado_get_field_value_options`) to retrieve the options.

I would also extend `TripalField::viewsData()` to add an additional "Field" in the Views UI with my custom handler (`tripal_views_handler_filter_fieldbased_select`). This way there would be the original `[field name]`, as well as, `[field name] (Allowed Values)`, where the second allows you to use a select list or autocomplete for the exposed form. This way an admin would simply add `Organism (allowed values)` to the filter section of the views UI if they wanted a select list rather then a text field.

I would also use the Drupal Cache to cache the list to make this more performant.

**Comment by spficklin** [comment]
Sounds good. You may want to add a few more options to your getValueList function as some fields have multiple "levels". For example, the OBI__organism field is attached to feature.organism_id.  If you wanted a filter by genus or species then you may want to adjust your keyword.  Also, going beyond just this use case, for anyone who wanted a list of all values, do you want to add an argument for specifying a DISTINCT vs non distinct search?  How about a pager in case someone only wants the first set of 10 values?  Just some things to think about.

**Comment by laceysanderson** [comment]
How about a generic `$options` array to handle that flexibility?
```
/**
   * Used to retrieve a distinct list of values already used for the current field instance.
   *
   * @param $keyword
   *   A string option used to filter the distinct list. This is used when creating an
   *   autocomplete. For all distinct values, set this to NULL.
   * @param $options
   *   An array where options for how to generate this list can be specified. Supported options TBD
   *
   * @return
   *   An array of values.
   */
   public function getValueList($options = array(), $keyword = NULL)
```

**Comment by spficklin** [comment]
Sounds good.

**Comment by laceysanderson** [comment]
This has been taking me awhile since I decided to write tests for it 😁 and I may be a little over ambitious? I'm trying to test a new ChadoField method for all field instances (essentially all field/bundle chado storage combinations).

## Need Input/Ideas
You can see my current test here: https://github.com/tripal/tripal/compare/550-tv3-views_select_lists?expand=1#diff-9b96ece5f652f733fde586c173cff2a5

Any ideas for a better way to test a given method for all field instances?
My current approach grabs all field instances in the current site and categorizes them. Not only is this time consuming but it's also very dependent upon the site your doing the testing on which doesn't seem like good practice 😝 However, neither does hard-coding a list 😝

I think we would ideally want a bundle and field database seeder but I'm not really sure how to start such an endeavor... and how would I ensure I have all fields tested? @bradfordcondon, @almasaeed2010, @spficklin any ideas?

**Comment by laceysanderson** [comment]
NOTE: all tests and `ChadoField->getValueList()` are fully working :-)

Just need ideas on how to improve the tests! (And to do the views work...)

**Comment by laceysanderson** [comment]
To summarize a slack conversation with @bradfordcondon: 
- convert "retrieveFieldList" method into a  [@dataProvider](https://www.startutorial.com/articles/view/phpunit-beginner-part-2-data-provider). This will simplify my tests by removing the need for the loop.
- populate the database with fake data for tests to make them more generic and help them pass on TravisCI. Factories are a great way to do this. If I need entities, I can publish them using `$this->publish('feature');`
- as far as bundles and fields go, I can rely on bundles I know exist in the default Tripal install. Any others I should create.

**Comment by laceysanderson** [comment]
I'm not feeling motivated to complete this functionality as I've moved away from using Views on KnowPulse. I'm going to close this issue but if anyone needs this functionality -feel free to comment and I'll re-open.
