### ISSUE TITLE
Error in Web Services Module

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#551]
### System information
* Tripal Version: 3
* Drupal Version: 7.59
* PostgreSQL Version: 9.6
* PHP Version: 7.1

### Issue description

A fatal error is showing up for my remote data field.

#### Steps to reproduce

I am not sure when or why this started happening.

#### Error messages and screenshots

<img width="1440" alt="screen shot 2018-08-14 at 10 07 32 am" src="https://user-images.githubusercontent.com/1512664/44096691-e2f0cc4a-9fa9-11e8-9b0a-8991b20ffbed.png">

```
Notice: Trying to get property of non-object in remote__data->makeRemoteRequest() (line 255 of /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal_ws/includes/TripalFields/remote__data/remote__data.inc).
Exception: Please provide a numeric site ID for the tripal_get_remote_content function. in tripal_get_remote_content() (line 247 of /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal_ws/api/tripal_ws.api.inc).
```

**Comment by almasaeed2010** [comment]
PR submitted #552

**Comment by spficklin** [comment]
Seems to be fixed... closing.
