### ISSUE TITLE
Bootstrap 3 typeahead jquery plugin not working

### ISSUE THREAD

**Issue by btski** [tripal/tripal#554]
Tripal Version: 3
Drupal Version: 7.56
PostgreSQL Version: 9.5.12
PHP Version: 7.0

I'm trying to get tagsinput and typeahead working on my site that has the Bootstrap 3 theme. I've downloaded bootstrap-tagsinput.css and bootstrap-tagsinput.js from [here][1]. I've also downloaded bootstrap3-typeahead.js from [here][2]. Now the code I'm trying to use to get everything working is below:

    <link rel="stylesheet" href="/sites/all/libraries/bootstrap-tagsinput/bootstrap-tagsinput.css">
    <script src="/sites/all/libraries/bootstrap-tagsinput/bootstrap-tagsinput.js"></script>
    <script src="/sites/all/libraries/bootstrap-typeahead/bootstrap-typeahead.js"></script>
    
    <script type="jquery">
    $("input").tagsinput({
      typeahead: {
        source: ["Amsterdam", "Washington", "Sydney", "Beijing", "Cairo"]
      }
    });
    </script>
    
    <input type="text" data-role="tagsinput" placeholder="Add tags" class="typeahead" data-provide="typeahead" autocomplete="off" />

Note: I'm relatively unfamiliar with jquery. No errors are returned when debugging. The tagsinput plugin works fine, but typeahead doesn't seem to work. The version of typeahead I chose should be compatible with Bootstrap 3. I'm currently avoiding using Twitter typeahead, which requires using Bootstrap LESS subtheme to avoid CSS conflicts.

Could anything Tripal related cause issues? Any suggestions would be much appreciated. I've also submitted this question to stackoverflow and will update if/when I get a solution.

  [1]: https://codeload.github.com/bootstrap-tagsinput/bootstrap-tagsinput/zip/latest
  [2]: https://github.com/bassjobsen/Bootstrap-3-Typeahead/blob/master/bootstrap3-typeahead.js

**Comment by bradfordcondon** [comment]
Do you have an error message or description of what is not working?  (hint: javascript errors would show up in your web browsers developer console. ie [for chrome](https://developers.google.com/web/tools/chrome-devtools/)  

What version of jquery is required?  See here: https://www.drupal.org/docs/7/theming/working-with-javascript-and-jquery

You may need the jQuery update module enabled depending on the version you need.

**Comment by btski** [comment]
The jquery update module is enabled. Current version appears to be 1.10 (most recent). Can confirm that jquery isn't being called correctly. I can't even get simple jquery demo code to run.

**Comment by btski** [comment]
Accidentally closed, reopened now. Can confirm that jQuery isn't working. Will investigate proper usage of jQuery within Drupal 7. I've got the jQuery update module enabled. The admin page suggests that the active version is 1.10, but I'm not able to find evidence of that via command line search. I've found the base versions of jQuery v1.4.4 and jQuery UI v1.8.7.

**Comment by shawnawsu** [comment]
You can trust the version referenced in your UI if you're using the jquery update module, 1.10 can sometimes cause problems, try changing the version to 1.7 or lower. 

I'm just going to reiterate what Bradford said, are you sure you're not getting any errors in your console (not terminal or db log)?

I think the likelihood that this is Tripal related is very small. 

The code that you're referencing, is that in a tpl file?

**Comment by btski** [comment]
Resolved. There were two problems. Firstly, jQuery wasn't automatically detected as a valid scripting language. I had to use a closure to map jQuery to $ (following documentation provided by Bradford). Second, I was creating the html element after the jQuery script was running. Working code:

```
<link rel="stylesheet" href="/sites/all/libraries/bootstrap-tagsinput/bootstrap-tagsinput.css">
<script src="/sites/all/libraries/bootstrap-tagsinput/bootstrap-tagsinput.js"></script>
<script src="/sites/all/libraries/bootstrap-typeahead/bootstrap-typeahead.js"></script>

<input id="test_this" type="text" data-role="tagsinput" placeholder="Add tags" autocomplete="off">

(function ($) {
$("#test_this").tagsinput({
  typeahead: {
    source: ["Amsterdam", "Washington", "Sydney", "Beijing", "Cairo"]
  }
});
$('input').on('itemAdded', function(event) {
  setTimeout(function(){
    $(">input[type=text]",".bootstrap-tagsinput").val("");
  }, 1);
});
}(jQuery))
```

Thanks for the help.

Edit1 - expanded answer to address a bug. More information can be found [here](https://stackoverflow.com/questions/29360584/twitter-bootstrap-3-typeahead-tagsinput-completing-twice/29413469).
