### ISSUE TITLE
bring user collection files into user file management

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#555]
## Feature Request/Discussion
- [x] does this feature attempt to solve an existing problem with Tripal?

### Description

We have recently added two file management features for users: collection files and user files (user uploads).
The user uploads area is great because we can set a file quota, users can see how much they are using, they can renew their files, etc.

Collection files don't count towards this quota.  They don't show up in the user file area.  Why not?  It's not as if the collection files don't take space, so shouldn't it count towards the quota and show users whats going on?

**Comment by laceysanderson** [comment]
Good call. It would be nice for these two sets of files to be consistent and aggregated. I don't yet use this new functionality yet. What functionality specifically would you like to see? 

Wish List (from original post):
- collection files + user uploaded files both count towards quota
- users can see/manage collection files in their user uploads area

**Comment by bradfordcondon** [comment]
@mestato anything I missed?

**Comment by mestato** [comment]
This would be great.

**Comment by spficklin** [comment]
Yes, they should count towards quotas. I thought they did do that. We'll check on it.

**Comment by bradfordcondon** [comment]
Added!  Thank you @spficklin !
