### ISSUE TITLE
autosort field widgets by required/optional

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#557]
## Feature Request/Discussion
autosort field widgets by required/optional.

Straight forward I think.  Publication in particular, i have a ton of fields and the required ones are all mixed in.  Furthermore the display order might be set with a specific output in mind for the end user, which shuffles the field widgets.

To make it worse, failing to meet validation will lose the entry and you'll get an SQL error instead of a form_validation return.

**Comment by spficklin** [comment]
Hi @bradfordcondon I don't quite understand this issue. Can you provide some examples?

**Comment by bradfordcondon** [comment]
oops.  After your response i fooled around and saw that changing the order of items on the field configuration page also changes the order of the widget (and that furthermore this allows you to configure the widget order separately from the display order).

So, site admins who wish to have all their required fields at the top should simply rearrange their fields under content -> structure -> [content type].

<img width="1359" alt="screen shot 2018-08-21 at 8 40 59 am" src="https://user-images.githubusercontent.com/7063154/44401843-f81bb480-a51d-11e8-8bf4-103561482c1e.png">



as an afterthought, i can think of 3 things that would improve this:

* Info in hte table on if the item 
    - has a widget for the user
    -  is required
* fieldsets for content types with lots of fields.  This is desirable for content types that get lots of chado properties added and therefore lots of chado fields.  I can imagine a content type with hundreds of prop fields attached getting unmanagable very fast.
