### ISSUE TITLE
Check for how cultivars are handled with organism

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#559]
### System information

* Tripal Version:  3.x
* Drupal Version:  7.x
* PostgreSQL Version:  N/A
* PHP Version:  7.2

### Issue description

This may or may not be a bug.  This issue is just to make sure that cultivars are properly handled by Tripal.  An organism can be of type 'cultivar', but if the type is a cultivar then the scientific name should not include the work 'cultivar' but rather just include the cultivar name in quotes (see https://en.wikipedia.org/wiki/Infraspecific_name).

**Comment by laceysanderson** [comment]
Closing as there has been no movement on this in over a year. If users find this is not working correctly, they can report it as an error at that time.
