### ISSUE TITLE
How do I create an entity record and add values?

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#560]
Hi guys (@bradfordcondon @shawnawsu @spficklin), so I've been using the following code to create a Tripal Entity, I believe I found this searching through Tripal code somewhere. The problem is that in this case, the entity record gets created in public.tripal_entity table BUT the corresponding chado_bio_data_<id> table does not get populated with the entity_id and record_id. I guess I'm missing something. How do I add that data via the code below? Any ideas? This is the only thing keeping me back from releasing the first version of Tripal Contact Profile module. Please let me know if you can
Thanks!

>
			$bundle = tripal_load_bundle_entity(array('name' => tripal_contact_profile_getMachineName()));
			$ec = entity_get_controller('TripalEntity');
			$entity = $ec->create(array(
				'bundle' => $bundle->name,
				'term_id' => $bundle->term_id,
			));
			$entity->name = $row->name;
			$entity->title = $row->name;

**Comment by bradfordcondon** [comment]
your entity_controller object should also specify chado `chado_record` and `chado_record_id` when you create it.  Check out the code below:


here is how we publish records in Tripal test suite:

```php

        $chado_entity_table = chado_get_bundle_entity_table($bundle);

  $ec = entity_get_controller('TripalEntity');
            $entity = $ec->create([
                'bundle' => $bundle_name,
                'term_id' => $bundle->term_id,
                // Add in the Chado details for when the hook_entity_create()
                // is called and our tripal_chado_entity_create() implementation
                // can deal with it.
                'chado_record' => chado_generate_var($table, [$pkey_field => $record_id]),
                'chado_record_id' => $record_id,
            ]);
            $entity = $entity->save();
            if (! $entity) {
                throw new Exception('Could not create entity.');
            }

            // Next save the chado entity record.
            $entity_record = [
                'entity_id' => $entity->id,
                'record_id' => $record_id,
            ];

            $result = db_insert($chado_entity_table)->fields($entity_record)->execute();
            if (! $result) {
                throw new Exception('Could not create mapping of entity to Chado record.');
            }
```

It feels like there should be a single API call that would publish an individual chado record to an entity, but I'm not sure one exists.  What do you all think, should we have some publish methods in the `tripal_chado.entity.api.inc`

**Comment by risharde** [comment]
Wow Bradford, thanks for your speedy response! Will test and post a follow
up message!

**Comment by bradfordcondon** [comment]
I should say... I think the main supported way of publishing records is to run the API to publish **all** records for teh bundle, ie `tripal_chado_publish_records`  edit oops, thats deprecated, use `chado_publish_records`

In short this call will check for chado records that match the bundle and publish, so all you have to do is insert into chado.

**Comment by risharde** [comment]
Hmm chado_publish_records seems like what I need for simplicity purposes, I'll be testing this tonight, hopefully early this week I can post a follow up on whether this works for the migration. Thank you so much @bradfordcondon, I would have never discovered this!

**Comment by risharde** [comment]
Just an update, @bradfordcondon , chado_publish_records worked like a charm! Thank you!

**Comment by bradfordcondon** [comment]
ok great.  I'm closing this issue out.  If we want to discuss an API for publishing specific chado records we can create a new issue.  ( know that there's some degree of functionality for this because you can provide filters...)
