### ISSUE TITLE
Collections Permissions Issue

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#563]
### System information

* Tripal Version: 7.x-3.x
* Drupal Version: 7.59
* PostgreSQL Version: 9.6
* PHP Version: 7.1
* Operating System: Centos 7

### Issue description

We are getting an error message in the job log when we generate a downloadable file using Tripal collections.

We have experienced this issue before (and it was fixed). see #293 .

#### Steps to reproduce

1. This is happening on CentOS 7
1. Use one of the data search views to create a collection
1. Click "Generate File for Download"
1. Confirm and run the job
1. The job log should contain the error message

#### Error messages and screenshots

```
Job execution failed: The user's data directory is not writeable: public://tripal/users/1.  
```

## Notes

When we edit the following function to always return true, the collection gets created without any issues.

https://github.com/tripal/tripal/blob/23c8d3f669c720db286480b9e536932d2108c7ea/tripal/api/tripal.files.api.inc#L230-L248

Thanks!

**Comment by spficklin** [comment]
@almasaeed2010 I'm not able to debug what's going on with this because I can't duplicate the problem.  That function has multiple checks to see if the directory is writeable.  Can you comment each check one at a time to see which is failing?

**Comment by almasaeed2010** [comment]
I added var_dump in all of the `if` statements:

```php
function tripal_is_user_files_dir_writeable($user) { 
   $user_dir = tripal_get_user_files_dir($user); 
     
   // First, make sure the directory exists. 
   if (!file_prepare_directory($user_dir, FILE_CREATE_DIRECTORY)) { 
     var_dump("File Prepare Directory Failed");
     //return FALSE; 
   } 
    
   // It has been reported that file_prepare_directory is not properly 
   // detecting if the directory is writeable, so we'll do another 
   // round of checks to be sure. 
   if (!is_dir($user_dir)) { 
     var_dump("It is not a dir");
     //return FALSE; 
   } 
   if (!is_writeable($user_dir)) { 
     var_dump("It is not writeable");
     //return FALSE; 
   } 
   return TRUE; 
 } 
```


The result:
```
2018-08-27 10:56:03: Calling: tripal_create_collection_files(37)
string(29) "File Prepare Directory Failed"
string(19) "It is not writeable"
Writing tab delimeted file.
string(29) "File Prepare Directory Failed"
string(19) "It is not writeable"
Writing comma separated file.
Getting entities for ids 0 to 25 of 25
Got 25 entities.
WD php: Error: Cannot access empty property in                           [error]
TripalTabDownloader->formatEntity() (line 57 of
/var/www/html/sites/all/modules/tripal/tripal/includes/TripalFieldDownloaders/TripalTabDownloader.inc).
Error: Cannot access empty property in TripalTabDownloader->formatEntity() (line 57 of /var/www/html/sites/all/modules/tripal/tripal/includes/TripalFieldDownloaders/TripalTabDownloader.inc).
Drush command terminated abnormally due to an unrecoverable error.       [error]
```

So it says it failed to create the directory but the directory exists. It also says it can't write to the file but the file is there and has content.

There is a separate error here that I am gonna open an issue for. This error appeared after updating to the latest tripal version.

Thanks!

**Comment by spficklin** [comment]
Is that directory writeable by the user running the drush command?

**Comment by almasaeed2010** [comment]
Given that the user is `root` it should be writeable. But also, there is content in the file if we force return true so I am sure it is writeable.

This is puzzling!

**Comment by spficklin** [comment]
You are running drush as root?

**Comment by almasaeed2010** [comment]
Yes we run drush as root because other users don't work for us in some cases. I understand the security implications and should probably correct system permissions to all use apache for it 😅

**Comment by spficklin** [comment]
Just curious.... you are running CentOS right?  Is SELinux getting in the way?

https://www.serverlab.ca/tutorials/linux/web-servers-linux/configuring-selinux-policies-for-apache-web-servers/

**Comment by spficklin** [comment]
That link is several years old, but might help....

**Comment by almasaeed2010** [comment]
Yeah I thought that was it at first but our selinux is actually disabled:

```
$ sestatus
SELinux status:                 disabled
```

**Comment by spficklin** [comment]
Can we consider taking this off the release blocker list?  I'm not able to duplicate it and it doesn't seem to be a problem for others.  We still need to address it but maybe it could be part of a future minor release (e.g. Tripal v3.1)

**Comment by almasaeed2010** [comment]
Yes we can take off the the release blocker. Until I can find a way to replicate the issue, I don’t think this should be considered a bug.

**Comment by almasaeed2010** [comment]
Fixed by changing permissions on our system. Thanks @spficklin for the help!
