### ISSUE TITLE
Web Services Fail to List Entities of a Certain Type

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#565]
### System information

* Tripal Version: 3.x
* Drupal Version: 7.59
* PostgreSQL Version: 9.6
* PHP Version: 7.1

### Issue description

Using web services on our live site to get a list of organisms results in an error (please see below).

#### Steps to reproduce

1. The error can be seen on our live site: [https://hardwoodgenomics.org/web-services/content/v0.1/Organism](https://hardwoodgenomics.org/web-services/content/v0.1/Organism)
1. You can reproduce the error on your site by visiting `/web-services/content/v0.1/Organism`

#### Error messages and screenshots

```
Error: Unsupported operand types in TripalContentService_v0_1->doEntityList() (line 899 of /home/www/sites/all/modules/tripal/tripal_ws/includes/TripalWebService/TripalContentService_v0_1.inc).
```

**Comment by spficklin** [comment]
Thanks for the fix!

**Comment by spficklin** [comment]
Yikes. I'm reopening because the fix did not work.  It did fix the problem with the error preventing the web services from appearing but the result it used for the TotalItems was an object rather than a number. I have applied a new PR to correct this problem.
