### ISSUE TITLE
hosting documentation alongside code

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#566]
We're thinking about including documentation alongside the code, rather than having the documentation on tripal.info.  This allows us to:

1. have version control on documentation, including versions, PR discussion about changes...
2. track who contributes what to documentation
3.  ensure that PRs update or add new documentation

we already do this to a very minor extent:  We have information on testing in `tests/REAMDE.md` for example.

So how does this work?  In short, we would have the text included in the repo in a "documentation" section.  The docs would be written in a way that a framework can read them and generate a full documentation website from them.  They would be built in a CI manner, much like our testing happens.  

The first tool I'll point us to is Read the Docs. Below is a quote from an [intro to the ecosystem](http://ericholscher.com/blog/2016/jul/1/sphinx-and-rtd-for-writers/)

>Read the Docs is a hosting platform for Sphinx-generated documentation. It takes the power of Sphinx and adds version control, full-text search, and other useful features. It pulls down code and doc files from Git, Mercurial, or Subversion, then builds and hosts your documentation. 

So we would have sphinx-generated documentation in the repo, that Read the Docs will hook into and generate fresh documentation on for all branches (ie a tripal 3 and tripal 2 branch).

Unfortunately we would be strongly encouraged to write the documentation in refstructured text  instead of markdown.  (RTD supports md but to get much of hte automated power of sphinx you'd do it in refstructured text).  Sphinx has some PHP adaptations (ie that it could automatically build or stitch in documentation from the PHP code) but its largely a python tool. 

There are read the docs alternatives:  [gitbook](https://www.gitbook.com/) for example.

This thread is for open discussion of what our priorities should be and what our options are.

**Comment by spficklin** [comment]
I very much like this idea.  I agree that Read The Docs is a great place to go.  It's in common use and would be familiar to others and easily is printable as PDF if desired.  I vote  for restructuredText as the format.  It also makes it easier for folks to suggest document changes as that's not possible in our current format on Tirpal.info and we can link to the readthedocs from the Tripal.info site.

**Comment by bradfordcondon** [comment]
@spficklin are working on this.  I've ported my devseed documentation (which included in-depth guides on how to use the TripalImporters) to read the docs and i think its a huge improvement.  

see: https://tripal-devseed.readthedocs.io/en/latest/

vs 

https://github.com/statonlab/tripal_dev_seed/tree/master/docs

We're shooting to have the tripal.info stuff ported over into read the docs for the official tripal 3 release.

### Doxygen integration?

[Breathe](https://breathe.readthedocs.io/en/latest/) bridges Sphinx (the read the docs construction toolkit) and the output of Doxygen, which we create our API documentation with.   I'm havign some errors loading it into the site, if anyone wants to help me work on it...

### Other stuff?
Is there somethign cool we could do with our **modules** section?

### github files

we'll want to update our PR guidelines and our instructions to say how the documentation should be updated and/or how to build the RTD site for testing (this i think can go in a README in the /docs base?).

**Comment by bradfordcondon** [comment]
# USER'S GUIDE PROGRESS.  
Note im not counting sub-pages.

- [x] what is tripal
- [x] install tripal v3
- [x] brief drupal overview
- [x] setup of example genomics site
  - [x] organisms
  - [x] analyses
  - [x] cross refs
  - [x] controlled vocabs
  - [x] genomes and genes
  - [x] importing pubs
- [x] learn chado
- [x] creating content types
- [x] setting page titles and urls
- [x] configurng page display
- [x] materialized views
- [x] searching
- [x] jobs management
- [x] web services
- [x] bulk loader
- [ ] ~~~galaxy integration~~~
- [x] customize your site

# Additional TODOs

- [x] softwrapping for tables
- [ ] add tripal logo and change theme
    - code blocks less hideous?
- [ ] change headers to subheaders to "fix" where subheaders show up article-level components

**Comment by bradfordcondon** [comment]
im almost done with galaxy but after going through it, it seems like it should be hosted separately (IE alongside the tripal_galaxy module not the tripal project).  The in-tripal documentation would then be a single page with an overview and a linkout to those docs.

**Comment by spficklin** [comment]
@bradfordcondon agreed on the Galaxy docs.

**Comment by spficklin** [comment]
It would be nice if we could somehow allow folks to easily link in their documentation for extension modules so that others can find docs in one easy place.

**Comment by bradfordcondon** [comment]
I agree and am thinking about how we can deal with that.  This is definitely an opportunity to rethink how core shares/lists extension modules

**Comment by spficklin** [comment]
The User's Guide is done!  Here's the link to the current build:

https://tripal.readthedocs.io/en/latest/

**Comment by bradfordcondon** [comment]
let's also add instructions on how to build /contribute in CONTRIBUTING.MD and update PR templates to specify

**Comment by bradfordcondon** [comment]
noticed a bad link in https://tripal.readthedocs.io/en/latest/user_guide/example_genomics/organisms.html#further-customizations

  linking is kind of tricky in this format.

**Comment by laceysanderson** [comment]
Cool! This is Awesome! Thanks for all your hard work @bradfordcondon and @spficklin!

**Comment by spficklin** [comment]
PR merged
