### ISSUE TITLE
Legacy titles on Tv2 content types

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#568]
### System information

* Tripal Version: 3.x
* Drupal Version:  7.x
* PostgreSQL Version:  N/A
* PHP Version: N/A

### Issue description

When someone runs a Tripal v3 site in legacy mode they get two sets of content types... one for nodes and one for the new entities.  However, this may be confusing to folks to have two sets of similar content types.  I propose we add the term "(legacy)" to each of the Tv2 content types to clue in users that these are the old node types.

**Comment by bradfordcondon** [comment]
thanks @spficklin
