### ISSUE TITLE
Syncing Pubs in legacy mode

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#577]
### System information

* Tripal Version:  3.x
* Drupal Version:  7.x
* PostgreSQL Version: N/A
* PHP Version: N/A

### Issue description

Consider that a user is running Tv3 in legacy mode and has converted all of their nodes over to entities but are still using Tv2 templates.  If they do a bulk import of publications then Tripal currently checks to see if it is in legacy mode and if so it tries to automatically sync publications.  This is not good because the user has already migrated over to entities.  

We should change the behavior or Tripal v3 to not automatically sync publications even if in Legacy module.   users would need to either Sync or Publish as needed for nodes or entities respectively.

**Comment by bradfordcondon** [comment]
resolved thank you @spficklin
