### ISSUE TITLE
Default Tv3 Content Type views provide results by default

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#578]
### System information

* Tripal Version: 3.x
* Drupal Version: 7.x
* PostgreSQL Version: N/A
* PHP Version: N/A

### Issue description

In the past we've always created default search views for Tripal and those views typically only show results when the search button is clicked.  Currently, for Tv3 the search views show results by default which slows down display of the search form.

**Comment by laceysanderson** [comment]
PR Merged 👍
