### ISSUE TITLE
Possible feature: Phylotree Importer: handle multiple files

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#583]
## Feature Request/Discussion

Offshoot of #290  but really a feature request/not a release blocker.

- [x] does this feature attempt to solve an existing problem with Tripal?
- [ ] are you open to developing or collaborating on an extension module if this is not a good fit for Tripal Core (no pressure here -just good to know upfront :-) )
- [ ] do you **Need** this feature ASAP?

### Description
Newick format can specify multple trees per file, but the importer expects one tree/file.

### Your Specific Use Case
NA for me.

### Generally Applicable
If its a spec of the newick format then its generally applicable.

**Comment by spficklin** [comment]
This is important, but given lack of time I'm going to mark this as Maybe Later. If we get a lot more interest in using the loader to import Newick files we can re-open.  @bradfordcondon If you disagree give your experience prior to your new position please reopen.

**Comment by bradfordcondon** [comment]
nope i approve- the data i was loading didn't need multiple trees, worst case scenario someone can write a script to parse through a multitree file, write out individual trees, and batch import.   When I created the issue i was just aware that this format support multiple trees.
