### ISSUE TITLE
Logging and Error Handling

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#588]
Logging and error handling in Tripal is a bit inconsistent.  We need to clean it up and set a properly documented way to do both.

**Comment by spficklin** [comment]
One problem with job logging is that we don't have the job object in all functions called by the job function and it would be too much of a hassle to have the $job object passed into every possible function that could be called by a job.  But if we don't pass the error messages don't get logged with the job.

**Comment by spficklin** [comment]
See the discussion in PR #616 for another example of problems with exceptions and logging.

**Comment by almasaeed2010** [comment]
The only solution I can think of for this that would be backwards compatible is to put the running job object in the global scope. I realize that global variables should only be used only when necessary but all other solutions can get very complex.

Using this solution, a job callback can access the object as such:
```php
function callback() {
  global $running_job; 
  // log messages, report progress etc...
}
```

If we want to hide the global variable, we can create a function that retrieves it instead and that way we can change the implementation in the future but the function can remain the same:

```php
function tripal_get_running_job() {
  global $running_job;
  return $running_job;
}
```

Would this work?

Thanks!

**Comment by almasaeed2010** [comment]
If we want to steer clear from global variables we could instead use `drupal_static()`.

Setting the active job:
```php
function tripal_set_active_job(TripalJob $job) {
  $data = &drupal_static('tripal_active_job_object');
  $data = $job;
}
```

Retrieving the job:
```php
function tripal_get_active_job() {
  return drupal_static('tripal_active_job_object');
}
```

This guarantees that the object is contained within the process and that it's automatically destroyed by the end of each job even when fatal errors occur (unlike `variable_set()`). This will also work when running jobs in parallel since each process has a separate store for this information.

**Comment by laceysanderson** [comment]
I've tagged this issue to be addressed in Tripal 4. At this point, I think it might be a bit late to consider fixing for Tripal 3 but if anyone needs it ASAP they should feel free to contribute. 

We also welcome any suggestions or wish list items regarding this topic. If you comment here, it may make it into Tripal4!
