### ISSUE TITLE
feature_cvterm evidence levels

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#59]
Copied from Drupal issue queue: https://www.drupal.org/node/2265611

When adding cvterms using KEGG/GO/InterProScan those terms should be annotated with the evidence level of those assignments so that viewers do not assume they are fully curated terms. Using the GO evidence codes (at http://www.geneontology.org/GO.evidence.shtml) may be a good set to follow.

**Comment by laceysanderson** [comment]
@spficklin should this be moved to the issue queue for the individual analysis modules?

**Comment by spficklin** [comment]
This issue is important for the extension modules but not for Tripal core itself.  So removing from here.
