### ISSUE TITLE
Data collections Form doesn't work with anonymous users

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#591]
### System information

* Tripal Version: 3.x
* Drupal Version: 7.x
* PostgreSQL Version:
* PHP Version:

### Issue description

The data collection form shows up on the default Tripal views even if no one is logged in.  We have a request #343 to support anonymous users, but at least for the Tripal v3 stable release we need to fix this bug.

**Comment by laceysanderson** [comment]
Bug Fixed in merged PR 👍
