### ISSUE TITLE
Docs: Exchange Data Between Sites

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#595]
We need documentation for how to exchange data between sites.

**Comment by ng29** [comment]
Hey @laceysanderson 

Can you provide a detailed explanation on this, so that I can pick it up?

**Comment by laceysanderson** [comment]
We need a walkthrough at Tripal Users Guide > Embed Remote Tripal Content (which doesn't yet exist). This can be added using readthedocs within https://github.com/tripal/tripal/tree/7.x-3.x/docs/user_guide following [these guidelines](https://tripal.readthedocs.io/en/latest/contributing/documentation.html). The menu item should be added to https://github.com/tripal/tripal/blob/7.x-3.x/docs/user_guide.rst under web services.

As far as content goes:
The idea is to walk administrators through:
1. create a connection with a remote site using the form at Administration » Tripal » Data Storage » Remote Tripal Sites (requires tripal_ws)
2. Adding a [remote_data](https://github.com/tripal/tripal/tree/7.x-3.x/tripal_ws/includes/TripalFields/remote__data) field to a Tripal content type and configuring it to use the remote data source set-up in step 1
3. Make sure the field is displayed and show it working on a Tripal content page.

**Comment by laceysanderson** [comment]
Closing this as it's now outdated with the move to Tripal 4.
