### ISSUE TITLE
PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "tripal_obo_temp" does not exist

### ISSUE THREAD

**Issue by fishfree** [tripal/tripal#600]
### System information

* Tripal Version:  7.3
* Drupal Version:  7.59
* PostgreSQL Version:  9.5.14
* PHP Version:  7.2

### Issue description
Both using Drush and web UI to install Chado, it failed with this:

#### Error messages and screenshots
```
PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "tripal_obo_temp" does not exist
LINE 1: DELETE FROM tripal_obo_temp
                    ^ in /home/wzzhang/www/tripal_install/includes/database/database.inc:2227
Stack trace:
#0 /home/wzzhang/www/tripal_install/includes/database/database.inc(2227): PDOStatement->execute(Array)
#1 /home/wzzhang/www/tripal_install/includes/database/pgsql/database.inc(111): DatabaseStatementBase->execute(Array, Array)
#2 /home/wzzhang/www/tripal_install/includes/database/database.inc(2406): DatabaseConnection_pgsql->query('DELETE FROM {tr...', Array, Array)
#3 /home/wzzhang/www/tripal_install/sites/all/modules/tripal/tripal_chado/api/tripal_chado.query.api.inc(1732): db_query('DELETE FROM {tr...', Array)
#4 /home/wzzhang/www/tripal_install/sites/all/modules/tripal/tripal_chado/includes/TripalImporter/OBOImporter.inc(559): chado_query('DELETE FROM {tr...')
#5 /home/wzzhang/www/tripal_install/sites/all/modules/tripal/tripal_chado/includes/TripalImporter/OBOImporter.inc(535): OBOImporter->loadOBO_v1_2('/tmp/obo_ZVM5z8', 'Taxonomic Rank')
#6 /home/wzzhang/www/tripal_install/sites/all/modules/tripal/tripal_chado/includes/TripalImporter/OBOImporter.inc(449): OBOImporter->loadOBO_v1_2_url('Taxonomic Rank', 'http://purl.obo...', 0)
#7 /home/wzzhang/www/tripal_install/sites/all/modules/tripal/tripal_chado/includes/TripalImporter/OBOImporter.inc(402): OBOImporter->loadOBO_v1_2_id(Object(stdClass))
#8 /home/wzzhang/www/tripal_install/sites/all/modules/tripal/tripal_chado/includes/setup/tripal_chado.setup.inc(133): OBOImporter->run()
#9 /home/wzzhang/www/tripal_install/sites/all/modules/tripal/tripal_chado/includes/setup/tripal_chado.setup.inc(195): tripal_chado_load_ontologies()
#10 /home/wzzhang/www/tripal_install/sites/all/modules/tripal/tripal/includes/TripalJob.inc(325): tripal_chado_prepare_chado(Object(TripalJob))
#11 /home/wzzhang/www/tripal_install/sites/all/modules/tripal/tripal/api/tripal.jobs.api.inc(421): TripalJob->run()
#12 /home/wzzhang/www/tripal_install/sites/all/modules/tripal/tripal/tripal.drush.inc(184): tripal_launch_job(0, '1', -1, 0)
#13 /home/wzzhang/.composer/vendor/drush/drush/commands/core/core.drush.inc(1158) : eval()'d code(1): drush_tripal_trp_run_jobs_install('wzzhang')
#14 /home/wzzhang/.composer/vendor/drush/drush/commands/core/core.drush.inc(1158): eval()
#15 /home/wzzhang/.composer/vendor/drush/drush/includes/command.inc(366): drush_core_php_eval('module_load_inc...')
#16 /home/wzzhang/.composer/vendor/drush/drush/includes/command.inc(217): _drush_invoke_hooks(Array, Array)
#17 /home/wzzhang/.composer/vendor/drush/drush/includes/command.inc(185): drush_command('module_load_inc...')
#18 /home/wzzhang/.composer/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#19 /home/wzzhang/.composer/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#20 /home/wzzhang/.composer/vendor/drush/drush/drush.php(12): drush_main()
#21 {main}
```

**Comment by spficklin** [comment]
Hi @fishfree thanks for reporting the issue.   In order to help diagnose the problem I need a bit more info.  

1.  Are you using the 3.0-rc3 release or the 7.x-3.x development version?
2.  Did you have any other warnings or error messages during install?
3.  What operating system are you using?

**Comment by bradfordcondon** [comment]
that table is created during the tripal_chado install.   are you following the guide at http://tripal.info/tutorials/v3.x/installation/tripal ???   If youre following the below shell commands, the error occurs when enabling which module?

```
drush pm-enable tripal
drush pm-enable tripal_chado
drush pm-enable tripal_ds tripal_ws
````

**Comment by fishfree** [comment]
@spficklin I just git clone https://github.com/tripal/tripal.git 2 days ago and followed [this instruction](http://tripal.info/tutorials/v3.x/installation/rapid). I installed Tripal in a Ubuntu 16.04 box.

**Comment by fishfree** [comment]
@bradfordcondon The 3 modules you mentioned are already enabled. I followed the [rapid installation method](http://tripal.info/tutorials/v3.x/installation/rapid).

**Comment by spficklin** [comment]
@fishfree sorry for the slow response. We're working on getting some last minute pull requests merged in before our next release. I will run a test install and see if I can duplicate the problem.

**Comment by spficklin** [comment]
Because this may potentially affect stability of our next release I'm bumping this up to a "release blocker"

**Comment by spficklin** [comment]
@fishfree I reran an installation from the ground-up and did not have this problem.  I am, however, installing the 7.x-3.x (develompent version) which is just barely v3.0 stable.   Can you try running again with that branch and let me know if you have the same issue?

**Comment by fishfree** [comment]
@spficklin Thank you! It seems [the updated repo](https://github.com/tripal/tripal) using composer to install Tripal. But there is no related how-to for installation.

**Comment by bradfordcondon** [comment]
hi @fishfree : composer is only used to run tests, not to install the site. You can continue to follow the instruction guide on tripal.info

just use `git clone https://github.com/tripal/tripal.git` prior to `drush pm-enable`

**Comment by fishfree** [comment]
@bradfordcondon Thanks! Finally, I set up Tripal with your newly-update repo by following the manual installation documentation.

**Comment by bradfordcondon** [comment]
great, glad you got it installed.
