### ISSUE TITLE
Update Finding Content Docs to include Tripal Content

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#602]
We should upgrade the [User’s Guide » Brief Drupal Overview » Finding Content](https://tripal.readthedocs.io/en/latest/user_guide/drupal_overview.html#finding-content) page to include discussion of the new Tripal Content tab. We can also use this as an approtunity to clarify the difference between "Content" and "Tripal Content".

**Comment by spficklin** [comment]
Done!
