### ISSUE TITLE
Docs: How to create a custom Data Loader

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#603]
We need documentation on how to use the importer class to make a custom data loader.
https://tripal.readthedocs.io/en/latest/dev_guide/custom_data_loader.html

**Comment by bradfordcondon** [comment]
@laceysanderson have you started this?  I can draft it if not.

**Comment by laceysanderson** [comment]
No I haven't started it yet. Go for it!

**Comment by bradfordcondon** [comment]
First draft posted as PR.  would welcome any and all suggestions.

**Comment by bradfordcondon** [comment]
merged. live at https://tripal.readthedocs.io/en/latest/dev_guide/custom_data_loader.html
