### ISSUE TITLE
Creating entities produces a PHP notice

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#605]
### System information

* Tripal Version: 3.x
* Drupal Version: 7.59
* PostgreSQL Version: 9.6
* PHP Version: 7.1

### Issue description

When creating any new entity, we get the following error:
```
Notice: Undefined variable: created_date in TripalEntityController->save() (line 397 of /Users/Almsaeed/Work/DevSites/Tripal/sites/all/modules/tripal/tripal/includes/TripalEntityController.inc).
```

#### Steps to reproduce

1. create a new organism
1. the error will appear on the newly created organism page

**Comment by almasaeed2010** [comment]
PR submitted

**Comment by laceysanderson** [comment]
PR Merged
