### ISSUE TITLE
PHP Warning in so__cds field

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#608]
### System information

* Tripal Version: 3.x
* Drupal Version: 7.59
* PostgreSQL Version: 9.6
* PHP Version: 7.1

### Issue description

The so__cds field is issuing a PHP warning (see error message below). 

#### Steps to reproduce

I noticed this error in the logs but visiting a feature page after clearing cache should display the message.

#### Error messages and screenshots

<img width="931" alt="screen shot 2018-08-28 at 1 19 15 pm" src="https://user-images.githubusercontent.com/1512664/44739172-13119a00-aac5-11e8-976e-b024f7c9781e.png">

```
Warning: Invalid argument supplied for foreach() in so__cds->load() (line 82 of sites/all/modules/tripal/tripal_chado/includes/TripalFields/so__cds/so__cds.inc).
```

It looks like we are trying to iterate over an int instead of an array:

https://github.com/tripal/tripal/blob/9ee01eca92715d52fec0dcbcdf94b8a9891fb18f/tripal_chado/includes/TripalFields/so__cds/so__cds.inc#L80-L82

I would submit a PR but I am not sure what the loop needs.

Thanks!

**Comment by spficklin** [comment]
It just needs a check to see if featurelocs is an array before running the foreach loop.   I'm guessing that you must have CDS records that don't have a corresponding entry in the featureloc table and the CDS sequence is loaded in the feature.residues column?

**Comment by almasaeed2010** [comment]
That's correct I have CDS but no featureloc records.

But the code is looping over the `feature_id` which doesn't sound right? Or is this an array?
```$featurelocs = $feature->featureloc->feature_id; ```

**Comment by spficklin** [comment]
The featureloc.feature_id column is a one-to-many relationship so the corresponding property in the $feature->featureloc->feature_id actually resolves to an array of matching records.

**Comment by almasaeed2010** [comment]
Thanks @spficklin 

PR submitted.

**Comment by spficklin** [comment]
PR Merged
