### ISSUE TITLE
PHP Undefined Property Notice in TripalEntityController

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#618]
### System information

* Tripal Version: 3.x
* Drupal Version: 7
* PostgreSQL Version: 9.6
* PHP Version: 7.1

### Issue description

Our logs are cluttered with PHP notices for undefined properties. I am not sure why the props doen't exist but I think a simple check will fix this. Example error:

```
PHP Notice: Undefined property: TripalEntity::$sio__annotation in /var/www/html/sites/all/modules/tripal/tripal/includes/TripalEntityController.inc on line 678
```

#### Steps to reproduce

I am not sure how to reproduce this. It is happening only our live site but not my local site.

#### Error messages and screenshots

```
PHP Notice: Undefined property: TripalEntity::$sio__annotation in /var/www/html/sites/all/modules/tripal/tripal/includes/TripalEntityController.inc on line 678
```

**Comment by almasaeed2010** [comment]
The issue seems to be with this line:

https://github.com/tripal/tripal/blob/e60511585bfb577e781b09e168d235887c2b89df/tripal/includes/TripalEntityController.inc#L649

It adds the field as an array to the entities array but does not consider the `$entity` itself.

Will submit a PR to fix this.

**Comment by spficklin** [comment]
PR Merged
