### ISSUE TITLE
Many Content Types Slows Cache Clear Tremendously

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#620]
### System information

* Tripal Version:  3.x
* Drupal Version:  7.x
* PostgreSQL Version: N/A
* PHP Version: N/A

### Issue description

When you have a lot of content types and when you clear your cache it can take many minutes for the site to become responsive.  This is because of the tripal_views_data() function:
```php
function tripal_views_data() {
  $data = array();
  // Job Management System
  tripal_views_data_jobs($data);
  tripal_views_data_tripal_entity($data);
  tripal_views_data_fields($data);

  $data['views']['tripal_area_collections'] = array(
    'title' => t('Tripal Content Data Collections'),
    'help' => t('Save Tripal content search results into a data collection for downloading or use with other tools.'),
    'area' => array(
      'handler' => 'tripal_views_handler_area_collections',
    ),
  );
  return $data;
}
```
This function calls the tripal_views_data_fields() function which is the cause of the slowness. It is trying to integrate every field instance from every content type with Drupal Views.  I have done some investigative work looking into this and there is repetitive calling of the same queries so I'm certain we can improve on this, but it will take some digging into it.

edit:  @chunhuaicheng reported to me this behavior on one of their sites and we weren't sure of the exact cause. I am now seeing this behavior on my dev site as well.

#### Steps to reproduce
Once the new PR #596 gets committed and if you prepare Chado again you will have a slew of new types. This will dramatically slow your site if you clear the cache.  Once you get past the cache being rebuilt performance seems fine.

**Comment by bradfordcondon** [comment]
merged, thanks all.
