### ISSUE TITLE
Documentation: Interacting with Fields

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#623]
It came up in #613 that it would be good to add a page to the documentation with examples on how to interact with fields. For example, how do you create a field instance to programmatically interact with? How can you use field methods in custom forms?

I'm creating this issue as a planning board to discuss how best to organize such a page. Should it be 

A. tutorial-based (e.g. you're creating a custom filter/search form)
B. method-function-based (e.g. ChadoField->getValueList)

**Comment by laceysanderson** [comment]
## How to create a Field instance to interact with:
```php
      // In this example we want the values for the obi__organism field
      // attached to the Tripal Content Type with a machine name of bio_data_17:
      // NOTE: the bundle referenced must have the field already attached to it.
      $field_name = 'obi__organism';
      $bundle_name = 'bio_data_17'; // Bundle Label: Gene.

      // The following two calls get information about the field we want the values for.
      $field_info = field_info_field($field_name);
      $instance_info = field_info_instance('TripalEntity', $field_name, $bundle_name);

      // Construct the Field instance we want the values for.
      $instance = new ChadoField($field_info, $instance_info);
```
Now you can call methods from the ChadoField class on `$instance`. If the field you are interested in uses a custom ChadoField class, make sure you use that name in place of `ChadoField`.

## How to create a select list based on a field (incomplete)
```php
      // In this example we want the values for the obi__organism field
      // attached to the Tripal Content Type with a machine name of bio_data_17:
      $field_name = 'obi__organism';
      $bundle_name = 'bio_data_17';
      // The following two calls get information about the field we want the values for.
      $field_info = field_info_field($field_name);
      $instance_info = field_info_instance('TripalEntity', $field_name, $bundle_name);
      // Construct the Field instance we want the values for.
      $instance = new ChadoField($field_info, $instance_info);
      // Retrieve the values.
      // $values will be an array containing the distinct set of values for this field instance.
      $values = $instance->getValueList();

      $form['select_list'] = array(
        '#type' => 'select',
        '#options' => $values,
      );
```

**Comment by laceysanderson** [comment]
We should link to this documentation from the "Custom Data Loader" page in the developer's guide since this would be a good way to populate values for importer forms.

**Comment by spficklin** [comment]
@laceysanderson does this new doc page address this issue?

https://tripal.readthedocs.io/en/latest/dev_guide/custom_field/create_instance.html

**Comment by laceysanderson** [comment]
Unfortunately not. We need a page showing how to create an instance of the class in order to retrieve select values and/or test it. This would be for use in a custom form, search or views handler.

The documentation you linked to shows how to attach the fields to  content types.

**Comment by spficklin** [comment]
Hmm... I'm not sure the class was ever meant to do that.  I would think you would be able to test the field classes by using the Drupal functions for dealing with entities and making sure that the entity object has the correct elements.

**Comment by laceysanderson** [comment]
I'm closing this issue as the class was not meant to be interacted with in this manner.
