### ISSUE TITLE
Remote Field "Field to Display" expects label rather then token.

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#625]
### System information

* Tripal Version:
* Drupal Version:
* PostgreSQL Version:
* PHP Version:

### Issue description

I noticed when configuring my remote field, the "Field to Display" is expected to be the label rather then the token from the "Available Tokens" list. Specifically, I set up my remote organism.species field as in #491. When I set "Field to Display" = "[taxrank__species]" I received the following error in my remote field:

![organism_ws_error](https://user-images.githubusercontent.com/1566301/44941861-9bad6600-ad63-11e8-8e56-fbc305089b42.png)

However, when I set the "Field to Display" to "species", the remote field displayed "databasica" as I expected. **This was the case regardless of the label of the content type.** 

For full field configuration, reference the following screenshot:
![organism_ws_config](https://user-images.githubusercontent.com/1566301/44941877-ca2b4100-ad63-11e8-9b49-e427775c172c.png)

#### Steps to reproduce

1. Add a new Tripal remote site that really points to the local site. Do this by going to Tripal > Data Storage > Remote Tripal Sites > Configuration. For my local test machine I used the URL http://localhost and version 'v0.1'.
2. Go to the Organism content type: Structure > Tripal Content Types and click manage fields on the Organism content type and create a new field of type 'Remote Tripal Site'. 
   - Set the Remote Tripal Site to the site you created in step 1; 
   - set the query to "Organism?genus=[taxrank__genus]&species=[taxrank__species]"; 
   - set the Field to display to '[taxrank__species]' or any of the other tokens under "Available Tokens". 
3. Make sure the new field shows up on the page by clicking on the 'Manage Display' tab at the top and moving it out of the Disabled section.
4. Go to any organism page that already exists on the site or create a new one. You should see the error shown in the screenshot above.
5. Edit the field and change the "Field to Display" to "species" and then refresh the organism page. Now the remote field works.

**Comment by spficklin** [comment]
Hi @laceysanderson.  So, I think the problem you are having is that the 'Field to Display' does not take a token.  It takes the name of the term or the accession.  So, if you want to show the species you would enter `species` or `TAXRANK:0000006`

Can you try making that change and see if that fixes the problem for you?  If so then perhaps the fix is to improve the description to indicate what is wanted.

**Comment by laceysanderson** [comment]
See 
> However, when I set the "Field to Display" to "species", the remote field displayed "databasica" as I expected. This was the case regardless of the label of the content type.

The change to `species` does fix the problem. I think it's very confusing that this field doesn't take tokens when there are `Available Tokens` listed directly below it. 

If we are simply going to change the description to make it more clear we should also move it so it's not directly above `Available Tokens`. Can we collapse available tokens by default and move it after `Query to execute` with `Field to display` beneath it?

**Comment by spficklin** [comment]
The reason we cannot use tokens is because the tokens are tied to field names and values on the local site which may not be the same as what is coming from the remote site.   I think your suggestions are good so I added a pull request that I hope fixes this for you.
