### ISSUE TITLE
DRUPAL_HOME env variable for User's Guide

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#633]
What do folks think if we alter the User's Guide to include setting an environment variable of $DRUPAL_HOME.  This way, we can use that in the command-line instructions and folks can easily just cut-and-paste rather than cut-and-pasting and then editing if their setup is different?  

We can add notes to the top of major section pages reminding folks that they need the DRUPAL_HOME env set to run the commands on the page.

**Comment by bradfordcondon** [comment]
yep, good idea.

**Comment by bradfordcondon** [comment]
started this.  did one page but ill do the rest: https://github.com/tripal/tripal/tree/633_drupal_home_env

**Comment by bradfordcondon** [comment]
merged, thanks!
