### ISSUE TITLE
Necessary ChadoRecord Improvements

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#634]
## Feature Request/Discussion

- [x] does this feature attempt to solve an existing problem with Tripal?
- [ ] are you open to developing or collaborating on an extension module if this is not a good fit for Tripal Core (no pressure here -just good to know upfront :-) )
- [ ] do you **Need** this feature ASAP?

### Description

PR #632 added a new ChadoRecord class for querying of Chado. It was added specifically to help with fixes/re-write of the OBO loader and as such was merged in without it's full featureset in order for the fixes to make it into the stable 3.0 release. This Issue describes the features and checks needed for the class before it's ready to replace portions of the existing API. NOTE: current API functions will remain for backwards compatibility but will become wrappers for the class functions.

### Fixes and Features Needed
From the original review of the PR:
- We need to be able to specify values through the foreign key:
```php
             $record->setValues([
               'name' => 'My Favourite Plant',
               'uniquename' => 'Plectranthus scutellarioides Trailing Plum Brocade',
               'organism_id' => [ 'genus' => 'Tripalus', 'species' => 'databasica' ],
               'type_id' => [ 'name' => 'sample', 'cv_id' => [ 'name' => 'Sample processing and separation techniques' ] ],
             ]);
```
 - We need to follow foreign keys when returning values.
 - It needs to be a little more fault tolerant.
      - In update & delete, if there is no record_id set, we can execute find to attempt to look it up
      - Need to support the same validation we have in the existing functions.
 - We don't have support for many of the options we did using the api functions directly.
 - We can only select a single record? This is a barrier to replacing chado_select_record().
 - Improve performance by using `RETURNING` for insert to retrieve the newly inserted id.

### Points for Discussion
- Should ChadoRecord->values() be a `chado variable` and should we have generate/expand var functionality in this class?
- What should be checked when values are set? This was easy in the original API functions because it was specific to the action being performed but with the class it's less clear. For example, If I'm intending to find, I should be aloud to not set all required values but if I'm executing an insert/update, then I need them. Perhaps required should be checked in insert/update rather then setValues?
- Should we throw exceptions or use tripal_report_error? or both?

**Comment by laceysanderson** [comment]
For more detail, see the `@todo` comments throughout the ChadoRecord class :-)

**Comment by guignonv** [comment]
* Should ChadoRecord->values() be a chado variable and should we have generate/expand var functionality in this class?

I would say yes. Otherwise, what could it be? A simple (limited) array?

* What should be checked when values are set? This was easy in the original API functions because it was specific to the action being performed but with the class it's less clear. For example, If I'm intending to find, I should be aloud to not set all required values but if I'm executing an insert/update, then I need them. Perhaps required should be checked in insert/update rather then setValues?

What about specifying the field to ignore when using find() and maybe allow some override as well?
```
$dbxref->setValues([
     'db_id' => $db->db_id,
     'accession' => $accession
   ]);

// Search db_id and accession using specified values as default:
$dbxref->find();

// Just search by db_id:
$dbxref->find(array('accession' => FALSE));

// Just search accession:
$dbxref->find(array('db_id' => FALSE));

// Search with same db_id but different accessions:
$dbxref->find(NULL, array('accession' => array($accession1, $accession2)));

```
The find proto would be something like:
```
function find(array $use_values = array(), array $value_overrides = array()) {
...
  // Check if something has been specified for the given field.
  // Note: for relationships, the field may be set but TRUE as a sub-array will be there to tell if
  // some joined table fields should be ignored.
  // ex.: $use_values = array('organism_id' => [ 'genus' => FALSE])
  // In that case, if an organism 'species' has been specified, it will be kept as a filter.
  if (isset($use_values[$field]) && !$use_values[$field]) {
    // Ignore field value.
  }
...
}
```

* Should we throw exceptions or use tripal_report_error? or both?

It depends on the error you want to report I guess. Exceptions would allow more possibilities I think.
