### ISSUE TITLE
Importer jobs fail if web directory is mounted to a different location

### ISSUE THREAD

**Issue by chunhuaicheng** [tripal/tripal#635]
### System information

* Tripal Version: 7.x-3.x
* Drupal Version: 7.59
* PostgreSQL Version: 10.5.1
* PHP Version: 7.2.7

### Issue description

The importer jobs (e.g. FASTA importer or GFF3 importer) will fail if the Drupal web directory is mounted on a different location and Drush command is launched in that mounting point. We have a login node that everyone works on and it has all web directories mounted as NFS shares. Tripal 2 does not have any problem with this setup but Tripal 3 does.

#### Steps to reproduce
1. mount your Drupal web directory on a different location, (e.g mount /local/sites/tripal3 to /mnt):
sudo mount --bind /local/sites/tripal3 /mnt

2. Submit an importer job (e.g: admin/tripal/loaders/chado_gff3_loader or admin/tripal/loaders/chado_fasta_loader)

3. Launch the job from the mounting point and the job will fail
cd /mnt
drush trp-run-jobs --username=admin

#### Error messages and screenshots

```
2018-09-06 11:16:40: There are 1 jobs queued.
2018-09-06 11:16:40: Job ID 5350.
2018-09-06 11:16:40: Calling: tripal_run_importer(7)
PHP Fatal error:  Cannot redeclare hook_handle_uploaded_file() (previously declared in /mnt/sites/all/modules/tripal/tripal/api/tripal.importer.api.inc:36) in /local/sites/tripal3/sites/all/modules/tripal/tripal/api/tripal.importer.api.inc on line 38
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                          [error]
Error: Cannot redeclare hook_handle_uploaded_file() (previously declared in /mnt/sites/all/modules/tripal/tripal/api/tripal.importer.api.inc:36) in
/local/sites/tripal3/sites/all/modules/tripal/tripal/api/tripal.importer.api.inc, line 38

```

**Comment by bradfordcondon** [comment]
thank you for reporting and approving @chunhuaicheng
