### ISSUE TITLE
Undefined callback for menu item in tripal_chado

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#640]
### System information

* Tripal Version: 3.x
* Drupal Version: 7.59
* PostgreSQL Version: 9.6
* PHP Version: 7.1

### Issue description

There is a menu item in the `tripal_chado` module that defined an undefined `page callback`

https://github.com/tripal/tripal/blob/4b321e67e876dba323553a49210a7b2cee98976b/tripal_chado/tripal_chado.module#L452-L459

In the above code, the method `tripal_pub_importer_setup_page_update_remotedb` does not exist but no errors are thrown due to that when visiting `/admin/tripal/loaders/pub/changedb`. 

I am not sure what should we do here. Any thoughts?

Thanks!

**Comment by spficklin** [comment]
Thanks for noticing.  This problem also exists in Tripal v2.  I think it's a left over bit of code that maybe was used in some previous iteration when developing that loader and I suspect it's no longer needed and can just come out.

**Comment by laceysanderson** [comment]
Fixed by @almasaeed2010 in both Tripal3 and Tripal2! Thanks @almasaeed2010
