### ISSUE TITLE
Dashboard PDOException: Undefined table "chado_bio_data_1"

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#647]
### System information

* Tripal Version: 7.x-3.x dev (4b321e67e876dba323553a49210a7b2cee98976b)
* Drupal Version: 7.59

### Issue description

When I click on Dashboard on the administrative toolbar I see the following error:
```
PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "chado_bio_data_1" does not exist LINE 3: chado_bio_data_1 et ^: SELECT et.* FROM {chado_bio_data_1} et; Array ( ) in tripal_block_view() (line 1163 of sites/all/modules/tripal/tripal/tripal.module).
```
This makes sense since in fact there is no `chado_bio_data_1` as all the Tripal Content Type tables are named `bio_data_#`. That said, I also don't have a `bio_data_1` table as I must have deleted that content type?

#### Steps to reproduce

1. Click `Dashboard` on the Administrative Toolbar (Must have the Drupal Core `Dashboard` module enabled).
2. Notice the following error:
![screen shot 2018-09-12 at 2 26 33 pm](https://user-images.githubusercontent.com/1566301/45451436-5a3c8500-b698-11e8-858e-7de880db2aa8.png)

**Comment by almasaeed2010** [comment]
Experiencing the same issue using the latest tripal 3.x

**Comment by spficklin** [comment]
Hi @laceysanderson just a clarification.  The tables should be named 'chado_bio_data_x'.  So, you should have a 'chado_bio_data_1' table if you had a 'bio_data_1' content type.

**Comment by almasaeed2010** [comment]
Ok on a new installation, using the 7.x-3.x, the `chado_bio_data_X` tables are not getting created. Every time I try to add new content, I get an error similar to this:

<img width="646" alt="screen shot 2018-09-14 at 9 50 27 am" src="https://user-images.githubusercontent.com/1512664/45554114-a0622780-b803-11e8-92a0-ea7858892096.png">

~Can someone test creating a new tripal site from the latest branch?~ (No need to test on new installation. This definitely does not happen when starting from scratch.)

**Comment by almasaeed2010** [comment]
Using [TripalDock](https://github.com/statonlab/tripaldock), which installs directly from `7.x-3.x` I am unable to replicate the issue. So this is probably something that happened while testing branches or a missing step in my setup. I am not sure if this issue will show up on sites upgrading to the latest release.

**Comment by laceysanderson** [comment]
Interesting that you can't replicate it on a fresh install. My original report was from a fresh Tripal install which I had yet to test any branches on. I install manually. I will create another one to see if I can duplicate it.

**Comment by almasaeed2010** [comment]
Yeah I don't see why it would be from testing branches either. None of our PRs explicitly deleted those tables :shurgs:

**Comment by spficklin** [comment]
I am able to reproduce this on a fresh install @laceysanderson .  I'm trying to work on a fix....

**Comment by spficklin** [comment]
@laceysanderson the problem does not occur on the 7.x-3.x branch. I was able to successfully install tripal and create all of the chado_bio_data_x tables. However, the problem does occur if you try to install using the 525-tv3-obo_speed_colon branch.  Could it be you were on that branch when you tried your testing?

**Comment by spficklin** [comment]
I believe I have tracked down this problem.  It does look like a problem on the 525-tv3-obo_speed_colon.  The new cvtermpath code had a legacy call to "chado_set_active()" that was being reset in the event of an exception but not otherwise.  This cased the chado_bio_data_x tables to get put into the chado schema rather than the public schema.  I've fixed the code and just committed it.    The CI test on #627 was failing because of this problem.  So if it passes then I say we can close out this issue.  But @laceysanderson we can leave open if you want to confirm.

**Comment by laceysanderson** [comment]
Ah yes, I very likely did install on the 525-tv3-obo_speed_colon branch! I would like to confirm after the tests past that this doesn't happen on the 525-tv3-obo_speed_colon anymore. I think you and @almasaeed2010 have already confirmed it doesn't happen on 7.x-3.x

**Comment by spficklin** [comment]
Yes, that's right. All is good on the 7.x-3.x

**Comment by laceysanderson** [comment]
Also fixed on 525-tv3-obo_speed_colon
