### ISSUE TITLE
Need a function to 'unpublish' content

### ISSUE THREAD

**Issue by chunhuaicheng** [tripal/tripal#649]
## Feature Request/Discussion

- [N] does this feature attempt to solve an existing problem with Tripal?
- [x] are you open to developing or collaborating on an extension module if this is not a good fit for Tripal Core (no pressure here -just good to know upfront :-) )
- [N] do you **Need** this feature ASAP?

### Description

We need a function to 'unpublish' content, similar to the 'cleanup orphaned feature' function in Tripal 2

### Your Specific Use Case

From time to time, our curators may request to delete data in bulk from underlying chado database. We need a 'unpublish content' function to remove the entities associated with those chado records.

**Comment by bradfordcondon** [comment]
We (well, @almasaeed2010 ) have added this functionality to our tripal entity helper tool [tripal_alchemist](https://github.com/statonlab/tripal_alchemist) for now.  If you delete the chado records, then alchemist has a function to "delete orphaned entities" which will remove them.

**Comment by chunhuaicheng** [comment]
This a great. Thanks @bradfordcondon 
Any chance this will be incorporated into Tripal core since this was part of the core functions in T2?

**Comment by bradfordcondon** [comment]
I will wait to see what other community members/PMC members think.  Seems like a good case for including it in the core.

**Comment by bradfordcondon** [comment]
@spficklin @laceysanderson what are your thoughts on porting this feature into core.  This constitutes a new feature and therefore a PMC vote.

**Comment by laceysanderson** [comment]
I think we should definitely have unpublish functionality in core and with it already written in Tripal Alchemist I think that is an amazing place to start!

So consider this **a vote in favor for me** 👍

**Comment by spficklin** [comment]
I agree that it makes sense to have this functionality in core as we had it in Tv2.

**Comment by almasaeed2010** [comment]
I'll start a new PR to port the functionality over from alchemist.

**Comment by almasaeed2010** [comment]
PR submitted https://github.com/tripal/tripal/pull/678

**Comment by laceysanderson** [comment]
Merged so I believe this can be closed 🎉
