### ISSUE TITLE
Delete unwanted nodes(entities) without deleting Chado data

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#65]
Copied from Drupal issue queue:  https://www.drupal.org/node/2784501

In the event that a site developer "syncs" content types that they no longer need/want the only way to remove the nodes without removing the data in Chado is to manually remove the records from the corresponding chado_xxxxx table and then clean up orphaned nodes. This is a bit unfriendly. We should have a way to "unsync"

**Comment by spficklin** [comment]
This initial request is specific to nodes but is also applicable to Tripal v3 entities.

**Comment by bradfordcondon** [comment]
Closing this issue as a) moot because deleting in tripal 3 **doesnt** delete the chado record, and b) duplicate with #660 where we got some discussion.
