### ISSUE TITLE
Brand our ReadtheDocs so it matches tripal.info

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#650]
We should brand our documentation so that it matches tripal.info in theme. This will provide a consistent user experience when jumping between the docs and tripal.info, as well as, make our documentation stand out as "ours".

**Comment by laceysanderson** [comment]
The following screenshots show where I'm currently at. The main thing I still want to change is the visited link colour :-). **I would love feedback, suggestions, comments!**

![screen shot 2018-09-13 at 10 49 48 pm](https://user-images.githubusercontent.com/1566301/45530351-6c591900-b7a7-11e8-9bcd-7829b12ae2e3.png)
![screen shot 2018-09-13 at 10 50 15 pm](https://user-images.githubusercontent.com/1566301/45530352-6cf1af80-b7a7-11e8-97f9-23b87a22d312.png)

**Comment by bradfordcondon** [comment]
totally agree, what you've got so far looks great!
