### ISSUE TITLE
Deleting an entity does not delete its record from the chado_bio_data_X tables

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#652]
### System information

* Tripal Version: 7.x-3.x
* Drupal Version: 7.59
* PostgreSQL Version: 9.6
* PHP Version: 7.1

### Issue description

When deleting an entity using the GUI, the record is removed from `tripal_entity` but is not removed from `chado_bio_data_X`.

#### Steps to reproduce

1. Visit any entity that you'd like to delete
1. Find its `entity_id` and make sure it exists in one of the `chado_bio_data_X` tables.
1. Delete the entity using the GUI: click `Edit` -> `Delete`
1. Check the chado_bio_data_X table once more to make sure it was deleted.
1. In my case, the record still exists.

#### Error messages and screenshots

No error message for this issue.

Thanks!

**Comment by almasaeed2010** [comment]
PR submitted #653

**Comment by bradfordcondon** [comment]
merged by @laceysanderson thank you for the fix @almasaeed2010
