### ISSUE TITLE
Tripal Home Page and About pages Text

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#656]
The blurb at the top of the home page and the text on the About page probably do not give a proper sense for what Tripal is.  Primarily, I don't think it drives home the value of using Tripal as a means for interacting with a larger community of developers and genomic sites.  The true strength of Tripal is not so much all of the functionality that it has but rather the community around it and the ability to share code and collaborate with others.  

I would like to rework that text on the website.  This issue  is meant to collect our thoughts on what really should be stated about Tripal on the home page and about pages of Tripal.info.

**Comment by laceysanderson** [comment]
Collecting my thoughts on a topic I love ;-p as a starting point for discussion.

### What is Tripal:
- toolkit for construction of online biological (genetics, genomics, breeding, etc), community database websites
- collection of core and extension modules for Drupal providing display, search & download for biological data
- easily customizable and extendable open-source project

### Why use Tripal?
- shorten development time of a custom biological database website
- has a huge community of developers providing support, advice and extension modules
- extendable to any type of biological data including those you may not wish to store in a relational database
- easily branded and customized
- facilitates sharing between other Tripal sites through extensive RDFa web-services
- huge drupal community & extension modules for all functionality outside biology such as forums, mailing lists, e-commerce, etc.
- a dedicated Drupal security team making sure Drupal core and extensions like Tripal are secure!

I would add a large block somewhere saying: "We love to collaborate! If there is something you need that Tripal doesn't yet do, please contact us here. Someone may already be working on it!"

**Comment by laceysanderson** [comment]
## Current Blurb
For context, this is what is currently on the front-page of Tripal.info

> Tripal is a toolkit for construction of online biological (genetics, genomics, breeding, etc), community database, and is a member of the GMOD family of tools. Tripal provides by default integration with the GMOD Chado database schema and Drupal, a popular Content Management Systems (CMS). Tripal is licensed under the GNU General Public License version 2.
> 
> Genomics, genetics, breeding and other biological data are increasingly complicated and time consuming to publish online for other researchers to search, browse and make discoveries.   Tripal provides a framework to reduce the complexity of creating such a site, and provides access to a community of similar groups that share community-standards, and interact to address questions and learn best practices for sharing, storing and visualizing complex biological data.

**Comment by laceysanderson** [comment]
## My Suggestion:
Tripal is a toolkit for construction of online biological (genetics, genomics, breeding, etc), community database web portals, and is a member of the [GMOD family of tools](http://www.gmod.org/). Tripal is open-source (GNU General Public License version 2), allows for extensive customization and is backed by a helpful user community. Customization and extension of Tripal can be shared as modules allowing you to leverage many existing tools and visualizations developed by groups around the world, and simultaneously share your work with the global community. To see what features Tripal provides, check out our [users guide](https://tripal.readthedocs.io/en/latest/user_guide.html) and our [developers guide](https://tripal.readthedocs.io/en/latest/dev_guide.html)! If you have any questions, thoughts, or concerns, we would love to hear from you [on our GitHub Issue Queue](https://github.com/tripal/tripal/issues)!

Thoughts? @spficklin does that capture what you were going for?

**Comment by spficklin** [comment]
Yes, I do like the text.  It's better.   One thing I'm wondering if we should make it clear that Tripal is meant for folks who really want to engage their research communities.   It really is mean for "Enterprise" level community databases, and it may be overkill for someone who just wants to put up downloadable FASTA files and leave it at that (although that's not out of the question).  

Alternatively, rather than a paragraph that folks have to read what if we limited that text and did something similar to our Tripal v3 about page:  http://tripal.info/about/tripal_v3

**Comment by laceysanderson** [comment]
I like the idea of an about page! What about instead of the paragraph on the front-page, we do a word-cloud?

PS. On the note of "Enterprise" level, I don't want to scare away the smaller groups like I was when I started ;-p But you're right about it being for "folks who really want to engage their research communities" :-)

**Comment by spficklin** [comment]
> PS. On the note of "Enterprise" level, I don't want to scare away the smaller groups like I was when I started ;-p But you're right about it being for "folks who really want to engage their research communities" :-)

Agreed...  

I'm not a fan of word clouds....  

@shawnamspoor any ideas?

**Comment by spficklin** [comment]
I updated the home page blurb following @laceysanderson's suggestion with a few tweaks.  @laceysanderson if you feel my tweaks need further clarification can you edit the website directly? Drupal 8 is awesome and let's you alter code in-line on the page!

**Comment by laceysanderson** [comment]
I like it, Thanks @spficklin!
