### ISSUE TITLE
Gene Ontology OBO Loader stuck in "Loading paths for biological_process"

### ISSUE THREAD

**Issue by igcbioinformatics** [tripal/tripal#658]
### System information

Ubuntu 16.04 8GB RAM
* Tripal Version: 3
* Drupal Version: 7
* PostgreSQL Version: psql (PostgreSQL) 9.5.14
* PHP Version:  PHP 7.0.30-0ubuntu0.16.04.1

#### Steps to reproduce

After freshly installing a Tripal installation following the tutorial, I now get stuck when loading the Gene Ontology OBO, following the tutorial for the example Genomic Site.

I know it is supposed to take hours, but I don't think it should take days...
Any idea of what may be causing this?

```

"""""
2018-09-17 17:29:04: There are 1 jobs queued.
2018-09-17 17:29:04: Job ID 7.
2018-09-17 17:29:04: Calling: tripal_run_importer(6)

Running 'OBO Vocabulary Loader' importer
NOTE: Loading of file is performed using a database transaction.
If it fails or is terminated prematurely then all insertions and
updates are rolled back and will not be found in the database

Downloading URL http://purl.obolibrary.org/obo/go.obo, saving to /tmp/obo_Gyphly
Step 1: Preloading File /tmp/obo_Gyphly...
Step 2: Loading type defs...emory: 32,544,760 bytes....................
Step 3: Loading terms...%. Memory: 32,545,728 bytes.
Percent complete: 100.00%. Memory: 56,381,176 bytes.
Done.

Updating the cv_root_mview materialized view...
Done.
Updating the db2cv_mview materialized view...
Done.
Updating cvtermpath table.  This may take a while...
- Loading paths for gene_ontology

NOTE: Updating CV Term Path is performed using a database transaction.
If the update fails or is terminated prematurely then any new changes
made will be rolled back.

- Loading paths for external

NOTE: Updating CV Term Path is performed using a database transaction.
If the update fails or is terminated prematurely then any new changes
made will be rolled back.

- Loading paths for biological_process

NOTE: Updating CV Term Path is performed using a database transaction.
If the update fails or is terminated prematurely then any new changes
made will be rolled back.
"""""
```

Then it never gets out of this... even after waiting a few days...
It used to be done overnight...

Any ideas welcome...

Thanks,
Daniel

**Comment by bradfordcondon** [comment]
Hello,
We've been actively working on this issue.  There is an open pull request here:  https://github.com/tripal/tripal/pull/627 that is almost ready to be merged.

You can either wait a day or two longer for us to merge it, or you can check out that branch and use it (we're just waiting on confirmation that the trait ontology loads correctly).

I would only recommend using the development branch on a **non production site**.

```
git pull
git checkout 525-tv3-obo_speed_colon
drush updatedb
```

**Comment by igcbioinformatics** [comment]
OK, Thanks, we'll wait for the merge.

Best,
Daniel

**Comment by bradfordcondon** [comment]
hi @igcbioinformatics the OBO importer update has been merged.  It should now work for GO: please update your code to the latest 7.x-3.x and try again at your leisure

**Comment by bradfordcondon** [comment]
hi @igcbioinformatics im assuming you were able to load this with the new release?  if not please let me know, otherwise im closing this issue.
