### ISSUE TITLE
Update to PR templates and guidelines

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#670]
We need to make changes to contribution guidelines, issue templates, and PR templates.

### Checkboxes

We dont like checkboxes.  They show up as tasks on the issue, we often get issues submitted with the formatting off... let's try to move away from them.

### Documentation

Documentation has moved to RTD

### Testing guidelines

Have moved

**Comment by laceysanderson** [comment]
We do need a non-checklist way to keep track of 
 - if an issue needs updates to documentation and whether it's in the PR
 - bug fix or new feature?

Perhaps we use a fill-in-the-blank style? For example:

## Metadata
- Needs updated documentation: Yes/No/InPR
- New Feature? Yes/No
- Bug Fix? Yes/No

**Comment by bradfordcondon** [comment]
for the documentation... now it will be very clear if the documentation is included in the RTD.   So im actually not sure what it accomplishes.  the people reviewing the PRs should be the ones who check off if the documentation update is sufficient in-code or on RTD.  We just need the guidelines to say "update as appropriate"... or am i missing something?

Bug fix/new feature I agree.  I think we can have different pR templates, like we have issue templates.  So we could have a diff template for Bug fix, new feature, and  pure documentation update, which would have different headers...

**Comment by laceysanderson** [comment]
Oh, different PR templates would be perfect!

Good point on the documentation. Are you suggesting we leave it out altogether since it's a PMC decision vs. a PR author decision? Or do you just think we should restrict the answers to `yes/no`? (can be conviced either way)

**Comment by bradfordcondon** [comment]
Im saying its self evident if documentation was changed or not, and either way its the PMC's task to determine if the documentation changes made are sufficient.  Its not acceptable to say "yes it needs documentation update but i didnt write it"    So i'm for just removing it from the template, but, like you, could be convinced either way.

**Comment by laceysanderson** [comment]
Ok, let's remove it (documentation mention)

**Comment by bradfordcondon** [comment]
I'm making PR templates for:  bug fix, new feature, and documentation.

This leaves out "API-specific change" (breaking change obviously makes 0 sense as a template)... any others?


### Bugfix template:

```md

<!--- Thank you for  contributing! -->
<!--- See our Contribution Guidelines here:
          https://github.com/tripal/tripal/blob/7.x-3.x/CONTRIBUTING.md -->
          
<!--- If it fixes an open issue, please add the issue link below. -->
Issue #

## BUG FIX

## Description
<!--- Describe your changes in detail -->
<!--- Why is this change required? What problem does it solve? -->

## Testing?
<!--- Please describe in detail how to test these changes. -->
<!--- Reviewers will use this section to test the submission! -->
<!--- If you've implemented PHPUnit tests, you can describe the test cases here. -->
<!--- Unit testing guidelines: https://github.com/tripal/tripal/blob/7.x-3.x/tests/README.md -->


## Screenshots (if appropriate):

```

### documentation template 

do we really need anything?  
Links to how to install sphinx and run `make html` probably?

```md
<!--- Thank you for contributing! -->
<!--- Provide a general summary of your changes in the Title above -->
<!--- See our Contribution Guidelines here:
          https://github.com/tripal/tripal/blob/7.x-3.x/CONTRIBUTING.md -->
          
<!--- If there is a matching issue, please link it below. -->
Issue #

## DOCUMENTATION

## Description
<!--- Describe your changes in detail -->
<!--- Why is this change required? What problem does it solve? -->

```

## new feature PR template

```md

<!--- Thank you for contributing! -->
<!--- Provide a general summary of your changes in the Title above -->
<!--- See our Contribution Guidelines here:
          https://github.com/tripal/tripal/blob/7.x-3.x/CONTRIBUTING.md -->
          

<!--- New features MUST have an issue so they can be discussed by the community prior to their implementation! -->


## NEW FEATURE

Issue #

## Description
<!--- Describe your changes in detail -->
<!--- Why is this change required? What problem does it solve? -->

## Testing?
<!--- Please describe in detail how to test these changes. -->
<!--- Reviewers will use this section to test the submission! -->
<!--- If you've implemented PHPUnit tests, you can describe the test cases here. -->
<!--- Unit testing guidelines: https://github.com/tripal/tripal/blob/7.x-3.x/tests/README.md -->

## Screenshots (if appropriate):

## Additional Notes (if any):

<!--- New features should include in-line code documentation. -->
<!--- Would a user or developer guide be helpful for this feature? -->

```

**Comment by laceysanderson** [comment]
I would make `Bug Fix` a higher level title and put it at the top (i.e. `# BUG FIX`). Otherwise, I think it's perfect 🙂

**Comment by bradfordcondon** [comment]
in doing this i realize i need to write some very basic instructions for RTD and put in docs/README.md  we can then link to it for the documentation template.

**Comment by bradfordcondon** [comment]
what about this part of the feature request template?

```

<!--- Go over all the following points, and put an `x` in all the boxes that apply. -->
<!--- If you're unsure about any of these, don't hesitate to ask. We're here to help! -->
- [ ] does this feature attempt to solve an existing problem with Tripal?
- [ ] are you open to developing or collaborating on an extension module if this is not a good fit for Tripal Core (no pressure here -just good to know upfront :-) )
- [ ] do you **Need** this feature ASAP?

```

I'm ok tabling it/leaving as is for now unless anyone has good ideas for how to improve.

**Comment by bradfordcondon** [comment]
i put my proposed templates in tripal alchemist so we can try them out there.

https://github.com/statonlab/tripal_alchemist/issues

unfortunately the multiple PRs means none get populated automatically, and it doesnt give you a nice choice like it does for the issues- instead we need to use the [query parameters](https://help.github.com/articles/about-automation-for-issues-and-pull-requests-with-query-parameters/)?  That sounds bad.  Let me look into it more.
https://blog.github.com/2018-01-25-multiple-issue-and-pull-request-templates/

so it would look something like this:

https://github.com/octo-org/octo-repo/compare/master...pull-request-test?template_x.md

**Comment by bradfordcondon** [comment]
given that we can only have a single PR template, how about this?


```
<!--- Thank you for contributing! -->
<!--- Provide a general summary of your changes in the Title above -->
<!--- See our Contribution Guidelines here:
          https://github.com/tripal/tripal/blob/7.x-3.x/CONTRIBUTING.md -->


<!---  Please set the header below based on the PR type:
# New Feature
# Bux Fix
# Documentation  --->

#


Issue #

## Description
<!--- Describe your changes in detail -->
<!--- Why is this change required? What problem does it solve? -->

## Testing?
<!--- Please describe in detail how to test these changes. -->
<!--- Reviewers will use this section to test the submission! -->
<!--- If you've implemented PHPUnit tests, you can describe the test cases here. -->
<!--- Unit testing guidelines: https://github.com/tripal/tripal/blob/7.x-3.x/tests/README.md -->

## Screenshots (if appropriate):

## Additional Notes (if any):

<!--- New features should include in-line code documentation. -->
<!--- Would a user or developer guide be helpful for this feature? -->
```

**Comment by laceysanderson** [comment]
I think this is perfect 👍 The only thing I would add it an extra line at the bottom pointing to a guide for contributing documentation -but we don't have one yet... See #672 where I've started one. I figure we'll add the link to the PR template as part of that issue once documentation is done.

**Comment by spficklin** [comment]
PR Merged.  I'm assuming this conversation is done so I'm closing.
