### ISSUE TITLE
Documentation Guidelines

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#672]
We need a README added to our docs directory to give contributing developers a quick guide and some guidelines for contributing documentation to Tripal.

**Remember: when this gets done, we need to add the link to the PR template.**

**Comment by laceysanderson** [comment]
# Tripal Documentation

Our documentation is build using **Read the Docs**. All of the Tripal documentation is in this 
directory (`docs/`) and is split into two guides:

1. User Guide: focuses on installation and configuration of Tripal from a content administrator point 
of view.
2. Developers Guide: focuses on developers extending the functionality of Tripal through 
development of extension modules.

## Building and Contributing to Documentation

You can build the docs by installing Sphinx and running:

```bash
# in the docs directory
make html
```

You can open `_build/index.html` in your browser and navigate to the page with your changes to 
check they compiled as expected.

## Guidelines

Please follow these guidelines when updating our docs. Let us know if you have any questions or 
something isn’t clear.

We use the following syntax:

```
Title of File (using title case)
=====================

Introduction text.

Other Heading
---------------

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut 
labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco 
laboris nisi ut aliquip ex ea commodo consequat.

We use backticks to indicate `inline-code` including file names, function and method names, 
paths, etc.

Longer code-blocks should begin with the `.. code-block:: [type]` directive and should 
be indented at least one level. There should also be a blank line before and after it as 
shown below.

.. code-block:: sql
  if ($needs_documentation) {
      use $these_guidelines;
      $contribute_docs = $appreciated;
  }

Sub-section
^^^^^^^^^^^^

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut 
labore et dolore magna aliqua.
```

**Comment by laceysanderson** [comment]
Above is my draft of documentation but I would love discussion, thoughts, corrections before posting a PR.

**Comment by bradfordcondon** [comment]
code styling is double ticks ``
Our use of headings is kind of bad in general.. the "right" way is

```
================
 Document Title
================
----------
 Subtitle
----------

Section Title
=============
Section 1.1 Title
-----------------

Subsection 1.1.1 Title
~~~~~~~~~~~~~~~~~~~~~~

Section 1.2 Title
-----------------
```

So we can consider changing it to the "right" way or keep as is, eithers fine with me... (assuming im not wrong about this ie that document title refers to each guide, not the whole tripal documentation)


Here's what i wrote for the README.md that wll go in docs.  Some overlap so im posting here (i think you're writing my "coming soon" section).


```
The Tripal documentation is written in [**Restructured Text**](http://docutils.sourceforge.net/rst.html), compiled with [Sphinx](http://www.sphinx-doc.org/en/master/usage/quickstart.html), and built/hosted with [ReadTheDocs](https://readthedocs.org/).  This directory, when compiled, is hosted at https://tripal.readthedocs.io/en/latest/

For minor changes, you can simply [Edit the file using the Github editor](https://help.github.com/articles/editing-files-in-your-repository/), which will allow you to make a Pull Request.  Once approved, your changes will be reflected in the documentation automatically! 

# Guide

### Install Sphinx
For minor changes, you don't need to build the documentation!  If you want to see how your changes will look on the built site, however, you will need Sphinx installed.

For more information, please see the Sphinx setup guide:
http://www.sphinx-doc.org/en/master/usage/quickstart.html


### Building your changes

For more extensive edits, or when contributing new guides, you should build the documentation locally. From the `docs` root (eg `/var/www/html/sites/all/modules/tripal/docs/`, execute `make html`.  The built site will be in `docs/_build/html/index.html`.

### Tripal conventions

Please place images in the same folder as the guide text file, following the convention [file_name].[n].[optional description].[extension].  For example, `configuring_page_display.3.rearrange.png` or `configuring_page_display.1.png` are both located in `docs/user_guide/` and are part of the `configuring_page_display.rst` guide.

More guidelines coming soon...
```

Also lets not forget people have other files to use as reference, so i dont think we need to explain too much of how to use RST as opposed ot linking the guide and establishing our own conventions.

**Comment by laceysanderson** [comment]
I added PMC Voting tag to determine what we should do about the header syntax. According to @bradfordcondon above, our current syntax does not match that recommended by ReadtheDocs.

**A) Do we change all our documentation to match the ReadtheDocs standard OR B) do we leave it as is which our own style documented in the README?**

Note: Lets try to vote on this without considering our current demands... I think we should decide what we should do here but not necessarily need to implement it immediately.

**Comment by laceysanderson** [comment]
I'm idealistic so my vote is for A 😝

**Comment by bradfordcondon** [comment]
I don't like B).  I'd rather suggest A) and not get around to updating the headers :)

**Comment by spficklin** [comment]
I thought we were following RTD standards on headers?  We're using restructuredText?  In any event. I like the README and I do have some edits for it. Could we create a branch and put the README there so we can edit?

**Comment by bradfordcondon** [comment]
hmmmm

header listings from RST  areh ere http://docutils.sourceforge.net/docs/user/rst/quickstart.html (the ones i linked above)

here are the header suggestions in Sphinx: they are slightly different and what we use, i guess https://documentation-style-guide-sphinx.readthedocs.io/en/latest/style-guide.html#headings

I dont know that RTD has a seperate suggestion, its probably sphinx's.
I have no preference for one over the other, i just didnt realize they were different.  So, let's formally use Sphinx's which is what we are more or less doing right?  (We dont do the document titles as suggested, for example)

**Comment by laceysanderson** [comment]
Perfect :-) I agree to formally using Sphinx's guidelines. Specifically to leave our format as is which appears to be: use H3 through H6 of the Sphinx's guidelines just as we've documented in our Docs README

**Comment by bradfordcondon** [comment]
ok, looks like your PR was merged, and i apologize for the confusion about the headers.  looks to me like we can close this, thanks lacey.
