### ISSUE TITLE
Tripal DS removes panes that are not empty

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#674]
### System information

* Tripal Version: 3.x
* Drupal Version: 7.59
* PostgreSQL Version: 9.6
* PHP Version: 7.1

### Issue description

When we have multiple fields in a pane and one is empty, tripal ds assumes the entire pane should be removed.

#### Steps to reproduce

1. Make sure hide empty fields option is selected in the bundle settings (Structure>tripal content types>Organism>edit)
1. Go to `manage display` for the same bundle (organism)
1. Move the description field out of the summary table but keep it within the summary pane
1. Create an organism and leave the description field empty
1. The TOC links on the left will be removed but the pane itself stays

#### Bundle Display
<img width="1404" alt="screen shot 2018-09-24 at 9 34 01 am" src="https://user-images.githubusercontent.com/1512664/45955113-12452880-bfdd-11e8-8fd9-c05b53c1f6fc.png">

#### Entity should have Summary link on the left but it doesn't:
<img width="990" alt="screen shot 2018-09-24 at 9 34 16 am" src="https://user-images.githubusercontent.com/1512664/45955144-225d0800-bfdd-11e8-8ad9-291af8678034.png">

### Additional Notes

This issue can be fixed by modifying this function:
https://github.com/tripal/tripal/blob/ab2960de58d43de0e5a9357600273a2cfcd636cf/tripal_ds/tripal_ds.module#L465-L490

The function above assumes there is only 1 field per pane.

Thanks!

**Comment by almasaeed2010** [comment]
@shawnamspoor any ideas on how to fix this?

**Comment by almasaeed2010** [comment]
Since this has to be fixed in order for #664 to merged, I'll mark this as release blocker and urgent.

**Comment by shawnawsu** [comment]
I just pushed an update that should address the menu and the empty field being shown. I've tested it a bit but not as much as I'd like, can you (@almasaeed2010) test it? I pushed the update to the revert-663-revert-628-541-tv3-ajax_fields branch.

**Comment by almasaeed2010** [comment]
The fix works perfectly. Thanks @shawnamspoor!
