### ISSUE TITLE
FASTA Importer requires a regexp if associating with a parent

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#676]
### System information

* Tripal Version: 3

## description

The Tripal FASTA importer requires a regular expression if you choose to associate the features with a parent.  However, this parameter should be optional.  It is optional for other importers (For example the InterPro importer).  
Why?

If I am associating interproscan annotations for a set of proteins, where the protein names === the mRNA names, i should just be able to specify the type (mRNA).  As it is, I also have to provide a regexp ie `>(.*)`

Heres where validation fails:

https://github.com/tripal/tripal/blob/9541d27c4843d2cbfedf01226ef048a4c23daacb/tripal_chado/includes/TripalImporter/FASTAImporter.inc#L280-L289

If we allow this, then we also need to update the importer here:

https://github.com/tripal/tripal/blob/9541d27c4843d2cbfedf01226ef048a4c23daacb/tripal_chado/includes/TripalImporter/FASTAImporter.inc#L538-L543

and set `$subject` to `$accession` (defined right above) instead of `''` by default.

**Comment by bradfordcondon** [comment]
any input from @tripal/project-managent-commitee-pmc on if this change should be made or not?

**Comment by laceysanderson** [comment]
I’ll vote yes for making the regex optional for the fasts loader 🙋‍♀️

**Comment by bradfordcondon** [comment]
ok good enough for me.  simple fix, i can take care of it when i have the chance.
