### ISSUE TITLE
Duplicate field EFO:0000269 for Assay

### ISSUE THREAD

**Issue by abretaud** [tripal/tripal#681]
## BUG/ERROR report

During startup, at the "Creating common Tripal Content Types..." step, I get this warning:

`[TRIPAL WARNING] [TRIPAL_FIELDS] The field, efo__array_design, uses a term, EFO:0000269, that is already in use on this content type. The field instance cannot be added.`

Indeed, the same term is used for [array design](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/tripal_chado.semweb.inc#L748) and [assay design](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/tripal_chado.semweb.inc#L778) fields.

### System information

* Tripal Version: 3.x
* Drupal Version: 7.59
* PostgreSQL Version: 9.5
* PHP Version: 7.x

#### Error messages and screenshots

```
error message
```

**Comment by spficklin** [comment]
Yes, I've noticed that too. We need to track it down but it won't cause a problem for you.  It's just trying to create the same field twice.

**Comment by bradfordcondon** [comment]
I'll point out that its the array_design field in both cases: attaching to array, and to assay.  With that in mind, correcting the typo at https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/tripal_chado.semweb.inc#L778 to be the exact same term (IE array design) should fix the error.


edit: actually this whole block is kind of wonky.


https://github.com/tripal/tripal/blob/dc48c7867f546b793a57b5217b8eea427ff3709b/tripal_chado/includes/tripal_chado.semweb.inc#L761-L783



the preceeding term is defined and assigned 2x.  The "assay design" term is defined but not assigned.

**Comment by laceysanderson** [comment]
How about these changes to fix it?
```diff
diff --git a/tripal_chado/includes/tripal_chado.semweb.inc b/tripal_chado/includes/tripal_chado.semweb.inc
index 4d63e9cc..3f412620 100755
--- a/tripal_chado/includes/tripal_chado.semweb.inc
+++ b/tripal_chado/includes/tripal_chado.semweb.inc
@@ -759,7 +759,7 @@ function tripal_chado_populate_vocab_EFO() {
     'cv_name' => 'efo',
     'definition' => 'An instrument design which describes the design of the array.',
   ]);
-  chado_associate_semweb_term(NULL, 'arraydesign_id', $term);
+  chado_associate_semweb_term('assay', 'arraydesign_id', $term);
 
   $term = chado_insert_cvterm([
     'id' => 'EFO:0005522',
@@ -768,13 +768,7 @@ function tripal_chado_populate_vocab_EFO() {
     'definition' => 'Controlled terms for descriptors of types of array substrates.',
   ]);
   chado_associate_semweb_term('arraydesign', 'substratetype_id', $term);
-  $term = chado_insert_cvterm([
-    'id' => 'EFO:0001728',
-    'name' => 'array manufacturer',
-    'cv_name' => 'efo',
-    'definition' => '',
-  ]);
-  chado_associate_semweb_term('arraydesign', 'manufacturer_id', $term);
+
   $term = chado_insert_cvterm([
     'id' => 'EFO:0001728',
     'name' => 'array manufacturer',
@@ -785,10 +779,12 @@ function tripal_chado_populate_vocab_EFO() {
 
   $term = chado_insert_cvterm([
     'id' => 'EFO:0000269',
-    'name' => 'assay design',
+    'name' => 'array design',
     'cv_name' => 'efo',
     'definition' => 'An instrument design which describes the design of the array.',
   ]);
+  chado_associate_semweb_term('element', 'arraydesign_id', $term);
+
 }
```

**Comment by bradfordcondon** [comment]
FYI the Assay Design bundle (?) is using the term accession for Array design:
https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000269

should be fixed in this issue
