### ISSUE TITLE
Drush version with Tripal v 2.1?

### ISSUE THREAD

**Issue by mdhar1980** [tripal/tripal#687]
Hello!

In order to maintain compatibility with some work we've done before now, my lab is installing Tripal v2.1 (for the time being). The tutorial for that version (http://tripal.info/tutorials/v2.x/installation/drush) says that Drush "7.0-dev branch" is incompatible with Tripal -- but I'm wondering, is that still true, or has it changed since the time of that tutorial's writing? 

Again, we're using Tripal v 2.1 for now. That tutorial says to check out Drush version 6.4.0. Is that still what we need to use, or can we use a later version? The current Drush looks to be version: 8.1.17.

Thank you

**Comment by spficklin** [comment]
Hi @mdhar1980 apologies for the slow response.  Yes, I think that documentation is out of date and we should update it to match the instructions for Tripal v3.   I am certain if you follow these instructions in the Tripal v3 manual for drush that the newer version will work just fine:

https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/drush_installation.html

Also, Tripal v3 is supposed to be fully backwards compatible with Tripal v2 so long as the Tripal API was used appropriately.  If you would like some input on how to proceed with a Tripal v3 update just let us know.

**Comment by mdhar1980** [comment]
OK, thank you!

**Comment by kyrenya** [comment]
hi! I take advantage of this thread to ask a maybe naive question. 
For the installation of the last version of Tripal, is it better to run latest version of drush with 
$ composer global require drush
or use the 7.* version as written here following documentation's link: https://www.drupal.org/node/1248790
$ composer global require drush/drush:7.*

Thanks in advance!

**Comment by bradfordcondon** [comment]
i've run into problems using drush 8 since some of the commands change i think.  I'd recommend using drush 7

**Comment by kyrenya** [comment]
ok, thanks a lot!
