### ISSUE TITLE
chado_get_organism_select_options shouldnt throw errors with default parameters for tripal 3

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#688]
### Description

`chado_get_organism_select_options()` gives this error if called without parameters:

```
Undefined table: 7 ERROR: relation "public.chado_organism" does not exist LINE 1: SELECT * FROM public.chado_organism CO ... ^: SELECT * FROM public.chado_organism CO INNER JOIN chado.organism O ON O.organism_id = CO.organism_id ORDER BY O.genus, O.species ; Array ( ) in chado_query() (line 1715 of /Users/chet/UTK/tripal/sites/all/modules/tripal/tripal_chado/api/tripal_chado.query.api.inc).
```

One needs to set Synced = FALSE to prevent this (`chado_get_organism_select_options(FALSE)`.  

I think this API call could be improved by checking if the site doesnt have a public.chado_organism table and, if it doesn't, instead checking the bio_data_x table to consider published records as those with entities.

**Comment by spficklin** [comment]
Good point. I've set this for a 7.x-3.1 milestone.  Although I've added the PMC voting tag just to make sure it's unanimous.

**Comment by laceysanderson** [comment]
I vote yes :-) That sounds like a good solution @bradfordcondon

**Comment by bradfordcondon** [comment]
its implied that @spficklin approves of this, so thats 3/3 and we can add it to the next Tripal release.  It's in the 3.1 milestone.  hurray!

**Comment by laceysanderson** [comment]
Closing this as it will not be fixed in Tripal 3 if it hasn't been already and it does not apply to Tripal 4.
