### ISSUE TITLE
Creating common Tripal Content Types is slow

### ISSUE THREAD

**Issue by abretaud** [tripal/tripal#690]
### System information

* Tripal Version: 3.x
* Drupal Version: 7.59
* PostgreSQL Version: 9.5
* PHP Version: 7.x

### Issue description

I don't know if it's really a bug, but I noticed that deploying a tripal 3 instance is much slower than it was for tripal 2. Like >15min instead of <5min.
It makes testing more painful, locally, and with travis (for tripal itself, but also python-tripal).
It is the `Creating common Tripal Content Types` step that takes a lot of time.
I've looked into the code a little: it seems like calls to the drupal `field_info_max_weight` functions are slow, when this function calls `field_info_instances` and `field_info_extra_fields`
And `field_info_max_weight` is called from tripal like this (at least):
`tripal_create_bundle_fields` -> `field_create_instance` -> `_field_write_instance` -> `field_info_max_weight`

As a clue, there is a warning in the doc of `field_info_instances` talking about using `field_info_field_map` instead.

I don't know if there's anything that can be done, I gave up when I saw that it could come from the drupal code... Just creating the issue in case someone is interested. Feel free to close.

#### Steps to reproduce

Install a new Tripal instance and wait.

#### Error messages and screenshots

N/A

**Comment by laceysanderson** [comment]
We have also noticed the slow creation time and fixing it is on our radar -especially since it moved content type creation into a Tripal job. 

> As of #593, Content type creation was moved into a tripal job. This was due to the addition of fields based on the property table sometimes causing a WSOD due to timeout. Ideally, we would optimize the process sufficiently to allow it to take place during the page load.

Thank you for your profiling :-) I'm going to close out the other issue as duplicate rather then this one since you provided more information then I did originally :-)

**Comment by spficklin** [comment]
Given we are actively working on Tripal 4 and we have limited time, and improving performance of things like this that delve into the depths of Drupal (which this setup does) I'm suggesting we revisit this for Tv4 and see how performance looks there.

Also, we actively do testing of Tripal with continuous integration and all seems okay, so I'm wondering if this is still an issue?

**Comment by laceysanderson** [comment]
This is still an issue.
