### ISSUE TITLE
Calendar on Tripal.info

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#692]
We should add a calendar with events such as our monthly User's Meetings, Yearly Hackathon and recurring events such as Hactoberfest (so we don't forget it next year).

**Comment by bradfordcondon** [comment]
i like the idea.  i propose using a google calendar so that its easy to manage and a drupal google calendar plugin for the tripal.info site.

**Comment by laceysanderson** [comment]
I created public "Tripal" google calendar here: https://calendar.google.com/calendar/embed?src=37ndpec8u9sav2ujf23m1888is%40group.calendar.google.com&ctz=America%2FRegina

**Thoughts about where we want to put it on tripal.info?** Maybe in a block on the frontpage and/or on it's own page?

Code to embed it for easy reference:
```html
<iframe src="https://calendar.google.com/calendar/embed?src=37ndpec8u9sav2ujf23m1888is%40group.calendar.google.com&ctz=America%2FRegina" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
```

**Comment by bradfordcondon** [comment]
Probably a link in the topmost menu bar.

I dont know where it would make sense to put it on the front page, seems like we'd have to displace something to make room

**Comment by spficklin** [comment]
@shawnamspoor is working on the upgrade to Drupal 8 for our tripal.info site.    @shawnamspoor do you know if it's possible to show upcoming events from our Google calendar on the Tripal home page?

**Comment by spficklin** [comment]
Oh, I just noticed @laceysanderson provided an <iframe> example.

**Comment by spficklin** [comment]
I think a block under the "Sites Using Tripal" would be a good place if there's room.

**Comment by shawnawsu** [comment]
This iframe has a specified time zone, can we create a calendar that adjusts based on the views timezone? Right now it's set to Regina, so I think if we can't we should probably move it to a more recognized time zone, like EST or PST.

**Comment by laceysanderson** [comment]
Ok, I made the default timezone for the calendar EST since there doesn't seem to be a way to not pick a timezone... If people add the Tripal calendar to their own google calendar then it should show the events in their timezone. However, I think the iFrame will always show it in the timezone it's set for.

Pacific
```
<iframe src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;height=600&amp;wkst=2&amp;bgcolor=%23FFFFFF&amp;src=37ndpec8u9sav2ujf23m1888is%40group.calendar.google.com&amp;color=%23333333&amp;ctz=America%2FVancouver" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
```

Eastern
```
<iframe src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;height=600&amp;wkst=2&amp;bgcolor=%23FFFFFF&amp;src=37ndpec8u9sav2ujf23m1888is%40group.calendar.google.com&amp;color=%23333333&amp;ctz=America%2FDetroit" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
```

Saskatchewan
```
<iframe src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;height=600&amp;wkst=2&amp;bgcolor=%23FFFFFF&amp;src=37ndpec8u9sav2ujf23m1888is%40group.calendar.google.com&amp;color=%23333333&amp;ctz=America%2FRegina" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
```

**Comment by bradfordcondon** [comment]
does this help?  use this js library to get the user's timezone?

https://stackoverflow.com/questions/31821974/support-user-time-zone-in-embedded-google-calendar

**Comment by spficklin** [comment]
@shawnawsu just pinging on this one now that the D8 tripal.info is done.

**Comment by laceysanderson** [comment]
Closing as there has been no movement on this in a year and I'm not sure how useful the calendar is as it only contains a single event (Tripal Users Meeting) of interest to the general community.
