### ISSUE TITLE
format vocabulary does not exist warning

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#694]
### System information

* Tripal Version: 3.x
* Drupal Version: 7
* PostgreSQL Version: 9
* PHP Version: 7

### Issue description

A warning of missing vocubalry `format` appears after clearing cache using the latest 7.x-3.x branch. The warning does not go away after re-populating the mview.

#### Steps to reproduce

I am not sure yet if it'll appear on a new site. Currently, it happens for me after clearing cache.

#### Error messages and screenshots

```
Could not find details about the vocabulary: format. Note: if this   [status]
vocabulary does exist, try re-populating the db2cv_mview materialized
view at Admin > Tripal > Data Storage > Chado > Materialized views.
Could not find details about the vocabulary: format. Note: if this   [status]
vocabulary does exist, try re-populating the db2cv_mview materialized
view at Admin > Tripal > Data Storage > Chado > Materialized views.
Could not find details about the vocabulary: format. Note: if this   [status]
vocabulary does exist, try re-populating the db2cv_mview materialized
view at Admin > Tripal > Data Storage > Chado > Materialized views.
```

**Comment by laceysanderson** [comment]
I cannot duplicate this on a clean install after clearing the cache multiple times 😕 Is this still an issue for you @almasaeed2010?

**Comment by almasaeed2010** [comment]
I am not sure how but the issue resolved itself. I don’t have this on any of our sites (dev or live). Thanks for checking @laceysanderson!
