### ISSUE TITLE
Genetic_code, so and frange PostgreSQL schemata ownership when using multi-chado instances

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#70]
Copied from Drupal issue: https://www.drupal.org/node/2825357

From @guignonv:

When using several Chado instances using the Multi-Chado module, on installation of a new instance the common schemata 'genetic_code', 'so' and 'frange' are dropped and re-created.
The PostgreSQL user account used to create the new Chado instance will be the owner of those schemata. The default Drupal account or event other PostgreSQL account used for other instances may not be allowed to access those schemata anymore.
This appends in tripal_core/includes/tripal_core.chado_install.inc:tripal_core_reset_chado_schema().

I don't have the best solution yet but I see several ways to fix it...

#1: we keep those schemata if they exist but then, updating Chado may be an issue if those schema are not updated.

#2: after installation of a new Chado instance, we reassign the ownership to Drupal default user. Then comes the "how do we know a new installation is done?". I'm thinking of 2 possible hooks to solve that: one would be to simply add a "hook_chado_installed" when the installation process is done. Another more flexible possibility would be to add a hook to Tripal jobs API to make it fire hooks when a job is completed so other modules can do some post-processing. Here the Multi-Chado module would reassign the appropriate ownership if the job run was a successful creation of a new Chado instance.

#3: Give a way to alter those common schemata names so the original ones won't be removed by the installation process and the installation SQL scripts could also be altered to they reflect those changes. For instance, if I install Chado in a "private_chado" schema, I would make its PostgreSQL functions use the schemata private_genetic_code, and such...

Other point of views are welcome!

**Comment by spficklin** [comment]
Hi @guignonv .  is this still an issue for you?  it's been in the queue for over 2 years.

**Comment by guignonv** [comment]
Hi! Sorry for the late answer, being in vacation 2 weeks ago and in BrAPI hackathon last week (where my computer died by the way...). Yes, it is still an issue but I have a workaround. If I really need something cleaner, I'll post a PR.

**Comment by spficklin** [comment]
Okay. I'm going to close this out then.  Please comment again if you want us to revisit it and we can reopen it.
