### ISSUE TITLE
Undefined property ogi__location_on_map

### ISSUE THREAD

**Issue by abretaud** [tripal/tripal#702]
### System information

* Tripal Version: 3.0
* Drupal Version: 7.59
* PostgreSQL Version: 9.5
* PHP Version: 7.1

### Issue description

I saw this notice while displaying an mRNA (with data from the Citrus demo from tripal 2.x):
`Notice: Undefined property: TripalEntity::$ogi__location_on_map in TripalEntityController->attachLoad() (line 681 of /var/www/html/sites/all/modules/tripal/tripal/includes/TripalEntityController.inc).`
I have no idea if it has any impact, reporting just in case

#### Error messages and screenshots

Launch docker-tripal, and loaded data with python-tripal with something similar to this: https://github.com/abretaud/docker-tripal-demo/blob/master/data/load.sh
Published mRNA records, and went to an mRNA page

```
Notice: Undefined property: TripalEntity::$ogi__location_on_map in TripalEntityController->attachLoad() (line 681 of /var/www/html/sites/all/modules/tripal/tripal/includes/TripalEntityController.inc).
```

**Comment by laceysanderson** [comment]
I have seen this as well. I'll submit a PR to fix -Thanks for reporting!

**Comment by laceysanderson** [comment]
PR Submitted :-) Can you test that it fixes the issue for you @abretaud?

**Comment by spficklin** [comment]
PR to fix this was approved. I'm closing this.  But comment if there's still issues.
