### ISSUE TITLE
Fields with disabled widgets

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#703]
## Feature Request/Discussion

* This feature [does ] attempt to solve an existing problem with Tripal
* I am] open to developing or collaborating on an extension module if this is not a good fit for Tripal Core
* This feature is [Not Urgent]

### Description

Site admins should be able to disable widgets for a field.  I think being able to disable them based on **permisions** would be extra awesome.

### Your Specific Use Case
Some fields we use sparingly, and only by an admin.    We woudl like undergrad curators to not get bogged down and distracted by these fields when creating content.  Note- without fieldsets, these forms can get scary fast!

Additionally, whati f you like a field to display, and you utilize programmatic ways of populatng it, but you dont want to ever manually set it, but the field provides a widget for it?  An example is the **Annotation** field.  We set that with blast/interpro importers, never manually.

**Comment by laceysanderson** [comment]
I have also come across this need. For example, we have properties we no longer use on our germplasm pages. I do not want to delete the field since I want to display it if it's already set but I do not want people to set this field on edit since it's deprecated.

I also just personally prefer hiding fields rather then deleting them. That way I remember they are there and can easily only show one additional field if I change my mind. Currently I have to delete ant used fields to keep them out of the edit form and then when I next click "Find new fields" they all come back again. This is particularly tiresome on the publication content type which has a lot of property fields that are not necessarily used.

My preferred solution would be able to just select "Hidden" as the widget. This would be as easy as creating a widget with no form that can be used for any field.

**Comment by bradfordcondon** [comment]
i've kind of conflated two issues here:

* Hiding fields

* Hiding based on permissions.

@laceysanderson you sounded your support for the first but not for permissions-based hiding: what do you think?  I see this as critical for tripal HQ.

edit: its possible that we will want to implement the permission-based hiding on tripal_hq's end which is fine.

**Comment by almasaeed2010** [comment]
I think I'd be ok with `hidden` as a widget option as @laceysanderson suggested since I have never felt the need to add data to an auto-populated field. Is there a specific case @bradfordcondon where admins would need to edit some field and at the same time won't let the user (submitter) edit it?

**Comment by bradfordcondon** [comment]
@almasaeed2010 :
>Is there a specific case @bradfordcondon where admins would need to edit some field and at the same time won't let the user (submitter) edit it?


I think all of the lookup fields fall under this category.  Publication, annotation, dbxref.  They are too complicated for an end user and/or require content creation, inserting terms, etc.

**Comment by almasaeed2010** [comment]
Yeah I see how that'd be really helpful! Thanks!

**Comment by laceysanderson** [comment]
I think permissions-based hiding would be useful in some cases but I'm not sure it's generally applicable enough to go in core. I also don't personally need this feature 🤷‍♀️ 

I'm not against seeing it in Tripal HQ though as it seems like a good compliment to the other functionality being developed in that module. All I request is that I don't need to check a large number of permissions checkboxes to make every field available to my users ;-p

**Comment by laceysanderson** [comment]
We should think about a way that we can make it easy for external modules to hook into permissions for fields. I can see this being a common thing external modules would like to do so we should make it as easy and non-hacky as possible for Tripal HQ

**Comment by bradfordcondon** [comment]
@almasaeed2010 brought up that excluding fields from **collections** would also be very desirable.


If i'm presented with 30 fields when creating a collection and only 5 of those would make sense to an end user, we should be able to hide those other ones.

**Comment by bradfordcondon** [comment]
hi all,

this works **out of the box** with the [Field Permissions module](https://www.drupal.org/node/2802067)

In short:

* enable the module
* go to the bundle and click to edit the field
* choose custom permissions in the field settings
* you can choose if people can create, edit, or view the field values

![screen shot 2018-11-09 at 1 56 48 pm](https://user-images.githubusercontent.com/7063154/48282540-f3cdac00-e427-11e8-98e6-11a9e69ff285.png)


I will plan on adding a guide to tripal_HQ.  I see no need to re-do this functionality in Tripal core, and am closing the issue.

**Comment by bradfordcondon** [comment]
HQ guide for this is at:

https://tripal-hq.readthedocs.io/en/latest/setup/install.html#additional-module-installation

and 
https://tripal-hq.readthedocs.io/en/latest/setup/field_permissions.html#field-specific-permissions


Might still be relevant to Tripal non-HQ users who want to hide certain fields from view?  IE lacey's use case she described?

Lacey if you want me to reopen this issue and submit the guide into core, or something else, please lemme know.

**Comment by bradfordcondon** [comment]
after discussing with @laceysanderson I am going propose the guide in tripal core instead, and link to it from tripal HQ.

reopening the issue to match the doc PR.

**Comment by bradfordcondon** [comment]
thanks to abdullah lacey and stephen for the thoughtful review.  merged.
