### ISSUE TITLE
OBO Importer builds malformed terms when loading plant trait ontology (TO) RO sub-terms

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#708]
### System information

* Tripal Version:3

#### Steps to reproduce
Load the trait ontology.  http://purl.obolibrary.org/obo/to.obo

two of our terms lookups are malformed:

```

Performing EBI OLS Lookup for: RO:0002310,056 bytes.
Cannot find the term via an EBI OLS lookup: RO:0002310. EBI Reported: Resource not found. Consider finding the OBO file for this ontology and manually loading it first.
Performing EBI OLS Lookup for: RO:0002577
Cannot find the term via an EBI OLS lookup: RO:0002577. EBI Reported: Resource not found. Consider finding the OBO file for this ontology and manually loading it first.
```
This is because THIS is the call built:

http://www.ebi.ac.uk/ols/api/ontologies/ro/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FBFO_00000500002310

when it should be
https://www.ebi.ac.uk/ols/api/ontologies/ro/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FRO_0002310

so, the namespace is BFO instead of RO.  The OBO actually reflects this so i think its the importer causing the problem.

**Comment by bradfordcondon** [comment]
do we have an OBO Importer guide?  If so we should add a request that people check their error logs and report any they find to our repo

**Comment by laceysanderson** [comment]
Confirmed that this is still a problem and the Trait ontology cannot be imported cleanly by the new/current OBO importer :-(

![Screen Shot 2021-01-27 at 4 05 09 PM](https://user-images.githubusercontent.com/1566301/106060417-a9dd4900-60b9-11eb-8e42-4367a88d5243.png)
