### ISSUE TITLE
undefined legacy function tripal_stock_add_organism_count_mview

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#709]
`tripal_stock_add_organism_count_mview` is called in legacy tripal_stock but is not defined.

reported here:  https://github.com/erasche/docker-tripal/issues/27 by @RichardBruskiewich

**Comment by bradfordcondon** [comment]
Here's the mview definition in 7.x-2.x

https://github.com/tripal/tripal/blob/3b3ddebf8fb420a0cc77cc6572a9dcbba4377a7c/tripal_stock/tripal_stock.install#L110-L178


do we need this mview?  edit: yes we do, its at least used by 
`tripal_stock_load_organism_stock_counts()`

**Comment by RichardBruskiewich** [comment]
The function is in v2.x but not v3.x
http://api.tripal.info/api/tripal/search/current?keyword=tripal_stock_add_organism_count_mview

Who has the power to fix this quickly?  @laceysanderson are you in a position to help with this?

**Comment by bradfordcondon** [comment]
I made a PR to add it back in, just need some eyes to confirm its a good idea.  I think it is though since we've still got functions in the tripal_stock legacy module calling that mview.  @laceysanderson you might be best qualified to double-check me here.

**Comment by laceysanderson** [comment]
It should be added back in 👍 I'll test the PR next week -thanks!

**Comment by bradfordcondon** [comment]
thanks @laceysanderson 

I realize this is a hole in our CI.  we test upgrading from tripal 2 to tripal 3, but we dont do **any testing** on the legacy modules.

I might add a final check at the end and enable them all.

**Comment by RichardBruskiewich** [comment]
@bradfordcondon, I might cherry pick your branch being submitted to the pull request so that I can take one more run at the hill today. I'm on Pacific time so I still have 3 hours in my regular working day!

**Comment by laceysanderson** [comment]
PR Merged 👍
