### ISSUE TITLE
Unable to edit content with Contact Field filled in.

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#718]
### System information

-  Tripal Version: most recent dev
-  Drupal Version: 7.x
-  PostgreSQL Version: 9.4
-  PHP Version: 5.6.7

### Issue description
When trying to edit an existing project with the contact field filled out I receive the following error:

> Could not save the TripalEntity: Could not insert Chado record into table: "project_contact": Array ( [contact_id] => 2 [project_id] => 4 ) 
> Cannot save entity

This happens when I *do not modify the value of the contact field*.

#### Steps to reproduce
1. Go to "Add Tripal Content" > "Project" and create a project with a contact. If necessary, you will need to create a contact first.
2. Edit the same project you created in step 1 and click update **without changing anything**.

**Comment by bradfordcondon** [comment]
i'm going to bet this is the same problem as #717 and will be resolved with  #764

**Comment by bradfordcondon** [comment]
now that #764 is merged, i tested this and did not encounter any errors when updating with no changes or when updating the description of a project, with or without a contact.

closing but please reopen @laceysanderson if you feel this wasnt resolved.
