### ISSUE TITLE
Tripal v2.1 tutorial patches (Views, PostgreSQL) outdated?

### ISSUE THREAD

**Issue by mdhar1980** [tripal/tripal#725]
Hello!

My lab in installing Tripal on a server; because of some things already in place, we're installing Tripal v2.1 at least initially. The existing tutorial for 2.1 (http://tripal.info/tutorials/v2.x/installation/tripal) lists a couple patches after installing Tripal (for Drupal Views and "the bytea data type in PostgreSQL").

We're thinking it's likely these are outdated, but I wanted to confirm: Are these patches still needed? For both Views and CTools, I installed the version 7 modules to work with the Tripal v 2.1 we have.

Thank you!
--Michael

**Comment by laceysanderson** [comment]
Hi @mdhar1980, both patches are still needed as shown in the Tripal 3 documentation here: https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/manual_install/install_tripal.html#apply-patches . To my knowledge the patches in Tripal2 are up to date but you can confirm by comparing the file names to those in the linked Tripal3 documentation.

**Comment by mdhar1980** [comment]
Great, thank you! Patch file names are the same, but directory names slightly different. Anyway, I applied them, but had one failure in the output for the Views patch. Will the following be an issue?

patching file plugins/views_plugin_query_default.inc
Hunk #1 FAILED at 1290.
1 out of 1 hunk FAILED -- saving rejects to file plugins/views_plugin_query_default.inc.rej

**Comment by mdhar1980** [comment]
HI, Lacey,

In Googling, I found that someone else had this same Hunk 1290 failure, user dedenmatra here: https://github.com/tripal/tripal/issues/397

But it doesn't look like that was ever resolved. Do you have any input on that?

Thank you,
Michael

**Comment by mdhar1980** [comment]
We are using Tripal v2.1, as downloaded using the web-based module-loading method, accessed from here: https://www.drupal.org/project/tripal

A sys admin suggested to me that part of the above 1290 failure MAY be because the Drupal site does not list the latest Tripal v2 version. A question regarding that: To remove the Tripal I've already installed, would I just follow a similar procedure to what's listed here? http://tripal.info/tutorials/v2.x/upgrade_2.0_to_2.1

Thank you!

**Comment by mdhar1980** [comment]
Sorry, I meant to say as listed here: https://tripal.info/tutorials/v3.x/upgrade/2.x-to-3.x

**Comment by laceysanderson** [comment]
Yes @mdhar1980, the process of putting your site into maintenance mode, disabling the modules, replacing the directory, re-enabling the modules and disabling maintenance mode is the proper procedure to upgrade the code for any Drupal module including Tripal. Also make sure to run any database updates that might be in the new version.

In reference to the other issue, we were never able to duplicate the problem :-( and I tried this patch again on my own system with no errors. Can you include your system information:

* Tripal Version:
* Drupal Version:
* PostgreSQL Version:
* PHP Version:

Note: All information is available in your site's administrator report area (Administration Toolbar > Reports > Status Report

**Comment by mdhar1980** [comment]
Thanks, Lacey: I will look up this information first thing tomorrow morning.

**Comment by mdhar1980** [comment]
Hi, Lacey,

Here is the system information:
Tripal Version: 7.x-2.1
Drupal Version: 7.59
PostgreSQL Version: PostgreSQL 10.5 (Ubuntu 10.5-0ubuntu0.18.04) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0, 64-bit
PHP Version: 7.2.10-0ubuntu0.18.04.1

Also , a sysadmin on our team found that there are two versions of that Views patch with the same number (1971160-30):

-(7.x-2.x):
https://github.com/tripal/tripal/blob/**7.x-2.x**/tripal_views/views-sql-compliant-three-tier-naming-1971160-30.patch

-(7.x-2.1) :
https://github.com/tripal/tripal/blob/**7.x-2.1**/tripal_views/views-sql-compliant-three-tier-naming-1971160-30.patch

So, that might have something to do with it. (We currently have Tripal v 7.x-2.1, as noted above).

Thank you!
--Michael

**Comment by mdhar1980** [comment]
We removed the Tripal v7.x-2.1, which we'd obtained from the Drupal site (https://www.drupal.org/project/tripal) and installed v7.x-2.x  from Github. The patch then seemed to install without an error message. This was the output:

patching file includes/handlers.inc
patching file includes/view.inc
patching file plugins/views_plugin_query_default.inc

Is that as it should be? If so, the patch may be incompatible with the version 2.1 that's on the Drupal site.

Thanks,
Michael
