### ISSUE TITLE
4th Ontology in Tripal v2 Installation Tutorial? Also, time for GO?

### ISSUE THREAD

**Issue by mdhar1980** [tripal/tripal#730]
Hello!

We are installing Tripal v2 using the tutorial, and it's a little unclear here (http://tripal.info/tutorials/v2.x/installation/tripal) on the ontologies to load. It lists three (Chado feature properties, Sequence ontology, Gene ontology), but the next paragraph says, "Repeat this process for each of the FOUR ontologies." Is there a fourth that needs to be loaded? If so, which one?

Also, I submitted the job for loading the Gene Ontology yesterday, and it's still "running" at 99% completed nearly a day later. I know it says it could take a while, but is that normal, or is there likely something not working?

Thank you!
--Michael

**Comment by bradfordcondon** [comment]
hi michael,  

I wouldnt recommend trying to load GO on Tripal 2.  The ontology can be loaded on Tripal 3 but the fix hasnt been backported yet.

(for reference see #186 , #140 )

You really only need the sequence ontology loaded to follow the tutorial, until you reach the "functional annotation" section where GO is used.

**Comment by mdhar1980** [comment]
Hi, Bradford,

OK, thanks for the response. Do I need to remove what's been loaded for it somehow? As I said, the job is 99% finished. It won't accept a "cancel" call.

Thanks again,
Michael

**Comment by bradfordcondon** [comment]
no.  When the transaction fails  it will roll back the database changes. 

How do you kill the transaction? look up its process ID and kill it. (you can use `ps -A | grep ` to search for specific processes, i dont remember what you will need to search for - postgres?  drupal?  tripal?)
