### ISSUE TITLE
"max_locks_per_transaction" memory setting for Chado load (Tripal v2)?

### ISSUE THREAD

**Issue by mdhar1980** [tripal/tripal#731]
Hello!

I am installing Tripal v2 using the tutorial. At the Chado installation process, I ran into the following Error regarding memory. (Note: This is a re-installation of Chado, as we had previously installed with Tripal v7.x-2.1; we removed that and replaced it with v7.x-2.x from Github in order to get it to work with the Views patch.)

> WD tripal_core: SQLSTATE[53200]: Out of memory: 7 ERROR:  out of shared memory                                            [error]
> HINT:  You might need to increase max_locks_per_transaction.
> [site http://default] [TRIPAL ERROR] [TRIPAL_CORE] SQLSTATE[53200]: Out of memory: 7 ERROR:  out of shared memoryHINT:  You might need to increase max_locks_per_transaction.

So, my question: What level should that max_locks_per_transaction stting for SQL be set to?

Thanks,
Michael

**Comment by btski** [comment]
You shouldn't need to re-install Chado for a minor Tripal update. You just want to re-write the /var/www/html (drupal) directory and add back in your old sites subdirectory. 

What do you get when you run `sudo du -h --max-depth=1 -x` from the /var/lib/postgresql directory? I'm assuming you're capped at 5G, which indicates you're out of shared memory (as your error message indicates). Changing max_locks_per_transaction won't help you. You'll have to clear space
[manually](https://www.digitalocean.com/community/questions/cannot-find-what-is-filling-up-disk-space-dev-vda1-is-100-full) or drop the database and restart. Remember - Tripal features are saved to PostgreSQL, so unless you want a clean Tripal installation, build from a backup database.

Edit - Please clarify what you mean by "re-install Chado". Chado is a schema built within PostgreSQL. It's not something that you would install.

**Comment by mdhar1980** [comment]
Hi, Bradford, thanks for the response -- and sorry for the delay on my end.

It seems that Chado may still be installed from the first time: I was able to add the controlled vocabularies. On the Install Chado Schema page, it does currently list 1.2 as installed.

And I see your edit: By install Chado, I just mean what the tutorial says: "Next, we must next install Chado. In the web browser, navigate to Tripal → Setup Tripal → Install Chado Schema" (http://tripal.info/tutorials/v2.x/installation/tripal).

However, that memory message is concerning; I don't know if it will cause issues with uploading the genomic data. There really shouldn't be a lack of memory, because this is a new server specifically for this Tripal installation. Here is the result of that command you listed:

sudo du -h --max-depth=1 -x
925M	./10
926M	.

Thanks again!

**Comment by almasaeed2010** [comment]
Hello @mdhar1980 

I've encountered this issue before with Postgres. I think the fix is to adjust the settings to allow for more memory if your machine allows for it.

Which version of Postgresql do you use?

Thanks!

**Comment by btski** [comment]
My interpretation was that he re-installed over an existing installation instead of following proper version update protocol or starting from a fresh instance. Note he's linked to instructions to install Tripal v2.x when Chado is already loaded. But I'm pretty confused and might be misunderstanding.

**Comment by mdhar1980** [comment]
Hi,
Yes, I was following the initial Tripal installation guide. We had to go back and install a different version of Tripal (before having done much else) because the patches didn't work with version 2.1. I did not realize that the previous Chado installation would still be there once Tripal 2.1 was removed. In any event, the re-install attempt of Chado did not proceed, so the previous version seems to still be there. Sorry for the confusion.

**Comment by bradfordcondon** [comment]
while all that may be true, i agree with abdullah that if the problem we are discussing is "I am getting a `max_locks_per_transaction` error" then the solution is "adjust your postgres settings".


Have you resolved your issue with the old chado installation?  If so, and thats what we are discussing, should we close the issue?


put another way... you can please summarize your current status on this issue, and what you need help with to move forward?  We don't understand.

**Comment by mdhar1980** [comment]
Agreed. Thanks for your help. I think the Chado situation is fine then. I'll close.

**Comment by mdhar1980** [comment]
Hi, almasaeed2010 -- what settings in Postgres did you change? I have Chado installed, it seemed, but now I am having trouble uploading our GFF. The job just halts, while a smaller file does load. This makes me think it might have something to do with memory, so maybe I do still need to adjust those Postgres settings you were talking about. Thanks!

**Comment by almasaeed2010** [comment]
Hello @mdhar1980 

I found this post helpful: https://stackoverflow.com/questions/40654766/how-to-increase-max-locks-per-transaction

It simply states that you should change the max_locks_per_transaction option in your postgres.conf file. This file can be found by running the following SQL query: `SHOW config_file;`

Thanks!
