### ISSUE TITLE
Gene page improvement: child feature field

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#732]
## Feature Request/Discussion
This issue is a splinter from #100 .  It's a feature request as @laceysanderson and I agree that having better gene pages is a **very desirable thing**. 

### Description

Gene pages aren't great out of the box, and fields just arent designed to work with a typical gene setup.  What do I mean by that?  In short, **Genes need to access child feature information** and they dont, or they do in limited ways.

Lets consider three fields.  I have a vanilla gene here at 
http://167.99.232.220/gene/185
I loaded FASTA sequences for scaffolds, mRNA, CDS, and proteins.  NONE of this information is available on the gene page!  Neither would annotations associated these feature types (unless we loaded them associating via the parent gene via regexp.).

#### Field 1 - transcripts

[Transcripts](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalFields/so__transcript/so__transcript.inc)
The transcript field on the gene page doesnt provide sequences, or any information other than location.

#### Field 2 - sequence 

[Sequences](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalFields/data__sequence/data__sequence.inc) . Per tripal's general philosophy, the sequence field only look as the targeted feature, not related features.  Because I didnt load in the gene FASTA, theres nothing to display, even though i loaded in 4 other feature type fastas, plus the GFF. I thould be able to infer the gene sequence via the GFF, just for starters.

#### Field 3 - protein sequence
[Field code](https://github.com/tripal/tripal/tree/7.x-3.x/tripal_chado/includes/TripalFields/data__protein_sequence)
There are protein sequences associated with this gene, but **indirectly** via the mrna -> CDS.    The protein sequences field therefore does not find them.

# Solution

Some considerations...
* I'd like the solution to work for all feature types, if possible.  Meaning, if im on feature X, it should find and display all features linked to it, nomatter how indirectly.  The field config might allow excluding display of certain SO terms if thast too much.
* Solution should be fast.  We are iterating through each feature_relationship.  I dont want a suite of fields doing that independently and redundantly.  So, we're probably either working on one mega field that displays all child-feature info, or, developing a shared architecture so that it only gets called once per page and cached.
* Sites will want access to, at a minimum, the following info from all children:
  - annotations (feature_cvterm, also blast data)
  - properties  (featureprops)
  - sequences 
   -  coordinate info (featureloc)

Point two sounds to me very similar to cvtermpath for features.  Cvtermpath is a nightmare, BUT for features its much easier to prevent infinite loops, we arent dealing with stanzas, etc.

Point three makes it clear that we are talking about multilpe fields, since displaying annotations AND sequences in the same place is a bit much.

**Comment by bradfordcondon** [comment]
Hi all,

I'd really like some input from the community.

Because my first attempt tried to include all annotations, properties, coordinate info, and sequences, the result is quite cluttered i fear.
![screen shot 2018-11-06 at 5 11 01 pm](https://user-images.githubusercontent.com/7063154/48135087-e4a0ff80-e269-11e8-9e58-0d14135c80a3.png)
I like having the collapsible fieldset: on that screen you've got a gene with each child mRNA (PAC:18136223, 224, etc) in its own fieldset.  In this example the name includes the location info so its extra redundant, and there are no annotations loaded.... 

(The sequence itself is in a popup- its possible the solution is to put even more of the info in a popup, perhaps the whole child table?)

So now i'm considering I instead need to provide alternative formatters for sequence, annotations, and a child-properties field.  These fields would rely on either an mview (featurepath, linking a parent to all child features) or some crazy "load first" data field that would serve the same purpose: gathering all the child features once so you aren't doing it over and over for each field.  


 @tripal/project-managent-commitee-pmc  any ideas?

**Comment by laceysanderson** [comment]
What about going the route the blast module did for blast results? That way you would have a table with each child mRNA (PAC:18136223, 224, etc) including name, id, type, location with an arrow on each row that can expand a hidden panel to show the sub-features?

For example, the first screenshot shows a mock-up when everything is collapsed and the second shows the first mRNA expanded.

**Collapsed**
![screen shot 2018-11-07 at 8 48 53 am](https://user-images.githubusercontent.com/1566301/48138527-22058d00-e26a-11e8-8504-71e6d3628882.png)
**First mRNA Expanded**
![screen shot 2018-11-07 at 8 49 04 am](https://user-images.githubusercontent.com/1566301/48138531-2467e700-e26a-11e8-9d65-27eb298d985c.png)

I personally like how the blast module shows the alignments in the expanded section as well but the pop-up option would make for a less cluttered, more intuitive display.

As far as formatters go, I would make a generic one first and then improved specific versions for important cases. That way we have a generic child location field to catch any edge cases without need for more formatters.

I'm not sure what to do about the annotations tho... Would that normally be a list of cvterms?

**Comment by colthom** [comment]
Hello !

Good idea to take on this problem ! We struggle too with scattered information between gene, mRNA, polypeptide...

As annotations (annotated terms, cross references, relationships...) can be quite extensive, maybe it would be better to leave them on a specific page ? 

Would something like that, for exemple, be more informative ? 
![proposition_annotations](https://user-images.githubusercontent.com/17720870/48256298-77c76a00-e40f-11e8-8d8f-c53ab81431b4.jpg)

**Comment by bradfordcondon** [comment]
hi  @colthom 

thanks for the feedback.

This is pretty much the crux of the issue.  On the one hand, moving annoations, sequences, and properties of *child features* into the associated field makes a lot of sense.  On the other hand, it requires building some shared storage of child feature info (such as for an example an mview), and then extending the existing fields to iterate through these child features as well when providing their info.

I think more and more that this is the best way to do it.  But it requires some sort of field storage solution to keep things fast, and of course the modification of all fields to iterate through child features as well....

**Comment by colthom** [comment]
Concerning the minimum informations to keep on annotations in the shared storage, are you thinking of a cvterm_id list or something like that ?

 I would have use of an information on the link between the annotation and the derived-feature (maybe a list of feature_cvterm_id, feature_dbxref_id, etc), in addition to the annotation itself. This way it's possible to retrieve properties or other linked information.
For example, in our case, we have different type of references or annotated terms, that we want to display separately (distinct panels) : a dbxref can be a synonym ID, a domain, a gene family, ... this 'type' information is stored in feature_dbxrefprop. 

It's a little redondant if we already have the (child)feature_id and the cvterm_id, but I don't know if it's more efficient to have those kind of information from the 'start' (in the mview?), or to retrieve it afterward when extending the fields.

-----------------

In addition to annotations (feature_cvterm, also blast data), properties (featureprops), sequences and coordinate info (featureloc), are there other relevant informations to display on gene pages ? Maybe potential synonyms (feature_synonym), cross references (feature_dbxref) or non structural relationships (feature_relationship) ?

For example, we use the "feature_relationship" table to store some kind of functional annotation : notable homology relationship with a feature from another organism, or correspondance relationship with the 'same' feature in another gene set. (Not sure this information is worth a place in a gene page though, maybe its use is too specific.)

**Comment by bradfordcondon** [comment]
>Concerning the minimum informations to keep on annotations in the shared storage, are you thinking of a cvterm_id list or something like that ?

Ideally it would be a nested structure of feature_ids.  So from the parent feature, you'd have children A and B (say, mrna) and then as keys each of their children C, D, E, (say, CDS), and so on.  As far as the minimum information in addition to that, i dont know.  probably just the IDs.  then each field (sequence, relationship, etc) is responsible for pulling the relevant child info in its load.

If we keep the "shared" child feature skeleton minimal, then its up to eahc field to decide if it wants to look through the children features and pull the info.  So theres already a relationship field.  Now, in addition to listin the parent relationships, it could expand and list each child's relationship.   

This makes the answer to "what additional info" do we need simple: none, just the feature IDs in a nested structure.

If we decide to go with a mega-gene field then this is exactly the problem, we end up needing to get child info for LOTS of different things.  featureprops, dbxrefs, relationships, synonyms, _cvterms, featurelocs.  Those are all good things that you might want to display to users for all children or a subset of children.  Each site makes different use of those tables, so they would probably appreciate being able to control which tables get deep-dived for child feature info, which is another point for "make a central child structure and have each field responsible for getting hte specific info from children".

**Comment by spficklin** [comment]
Here's an idea.... what if instead of trying to display "nested" data on a single page.  What if the nesting occured in the sidebar?  If for instanace, we could add an indent for child features, and clicking on a child feature would open up it's list of fields which a user could click on and have brought up on the page.  

This solution, would require, however, that every child that you wanted in the menu needs to be an entity.

**Comment by bradfordcondon** [comment]
@spficklin and i discussed this today.

In short, the goal is to utilize the relationships field, which has already traversed the feature_relationship table and fetched the child records.  By sharing those records, other fields can simply check to see if that field has loaded, and use the returned children to work with.

The specific gene page implementation is still up in there. trying to support multiple transcripts/mrna is what is tricky.  Options are:

* write fields that display all transcript info.  They'd have to be collapsible, etc

* have a "default transcript" that stuff gets loaded for.  looking at other transcripts brings you to the specific transcript page.

* display transcripts in a pane that essentialy loads teh transcript entity and displays it on the gene page. 

Both of the latter options require transcript entities.  The first option doesnt, but, its the most unwieldy, even if the information is broken up and not in one giant "child feature" field anymore.

**Comment by laceysanderson** [comment]
I'll up my priority on the relationship field. I've made lots of changes in there and don't want us to run into major conflicts 😬

**Comment by bradfordcondon** [comment]
oh yikes, i hadnt thought of that.

All im going to do is add the full expanded record as a base key (ie not in value), so it actually should just be a 1-line change ( i think)....  is most of your work in the base, or the formatter or the widget?

**Comment by laceysanderson** [comment]
My work is throughout and the last small one-line change is why it's not ready for review yet 🙁  Can you give me today to finish it? 😬

**Comment by bradfordcondon** [comment]
>In short, the goal is to utilize the relationships field, which has already traversed the feature_relationship table and fetched the child records.

The relationship field is not actually recursive, so it only fetches direct relationships.  we need to discuss if we want ot make the relationship field recursive, or, have a new "recursive relationship" field for just features that gets all descendant children

**Comment by spficklin** [comment]
I think it would make it overly complex if it is recursive...  However, in line with our previous discussion

1)  Save the record in the relationship field.
2) In your new field use that same record to recursively expand children you are interested in.  

So you do the recursion in your new field rather than in the relationship field.

**Comment by bradfordcondon** [comment]
I've [written a custom "all children info" field.](https://github.com/statonlab/tripal_manage_analyses/tree/gene_field/includes/TripalFields/data__sequence_features)  It uses chado_expand_var to expand the residues, props, _cvterms, and featurelocs of each child feature.  It stores it in an indexed array where each ndoe is the feature_id, with keys info (the expanded info) and children (an array of child feature_IDs of THAT feature).

How do my other fields query info from this field?  For example, im writing the "child property" field.  its going to go through the "all children info" field and collate all the featureprop info there.  Can they just do this in the formatter, hwen the info is guaranteed to be there?  If not and they need to do it in the load, how can i delay that fields `load` method until the parent field is available?

**Comment by bradfordcondon** [comment]
Here is the **child property** field, which consists of collapsible fieldsets.  The idea is the gene has child features for mRNA, which in turn have all sorts of children and grandchildren.  The field collects all featureprops associated iwth all children/grandchildren, etc, and displays them in each mRNA's collapsible fieldset.


![screen shot 2018-12-19 at 11 38 19 am](https://user-images.githubusercontent.com/7063154/50234754-636a7b80-0384-11e9-972c-a1abe833cd15.png)


I plan on taking a similar approach for other fields but properties are the one field that have no equivalent, pre-existing field (as each chado property is its own, independent field).  I still need ot know if the above field's value statement needs to include the information and if so how to delay its load and reference the master field's value.  For now, its all handled in the formatter, because we know the master field has loaded at that step.


I'm also keeping this in my "catch-all" custom module for now.  I'm open for suggestions on if this would go well in core vs a standalone module...

**Comment by laceysanderson** [comment]
Looks good @bradfordcondon! 

>  I'm open for suggestions on if this would go well in core vs a standalone module...

I'm personally leaning towards core as it looks like a nice, generic solution for child/grandchild properties and I can see many uses for it. Is it generic enough to work on any chado table with an associated relationship table (e.g. stock, project)?


>  I still need to know if the above field's value statement needs to include the information

I think it does need to be included in the field's `value` so that this information can be made available on web-services as well

**Comment by bradfordcondon** [comment]
>'m personally leaning towards core as it looks like a nice, generic solution for child/grandchild properties and I can see many uses for it. Is it generic enough to work on any chado table with an associated relationship table (e.g. stock, project)?


no but it easily could be.  It's basically a super-relationship field that loads in stuff about the children via `chado_expand_var`.  So, each content type could have different tables to expand, no problem.  What tables would you want expanded for stock and project?


>need to be included in the field's value

That's fine, but i need help from people in the now on how to make other fields "wait" for the master field to load.  Right now im cheating by loading it in the `formatter` instead, which means of course that the `value` is empty.

**Comment by laceysanderson** [comment]
Found [this comment](https://www.drupal.org/project/computed_field/issues/378312#comment-7755311) regarding controlling the order of field loading (i.e to ensure this field is loaded last)

> After a lot of digging, I have found that the fields are attached to the entity in the order of the "id" column in the "field_config_instance" table. So you can manually fix this by deleting the row and re-adding it, which will give it a higher "id." Try this only if you are comfortable messing around in the database.

**Comment by bradfordcondon** [comment]
I've wandered a bit on this so I'm posting what I've got to solicit feedback.

The proto fields are available at https://github.com/statonlab/tripal_manage_analyses if you want to try them out.


Heres what we have:

`data__sequence_features` is the master field.  it loads first.  It stores data as follows:

```php
$entity->data__sequence_features[$i]['value'] => 

['info'] => #stuff from chado_generate_var and chado_expand_var.  We expand featureloc, feature_cvterm, featureprop.
['children'] => #an array of child feature_id's, each with an info and children key.
```
So each direct child of the entity gets its own value element.  The end result is (hopefully) a data object meeting @spficklin 's requirements.
The formatter for this field is a drawing of child features, with each direct child as its own drawing:

<img width="677" alt="screen shot 2019-01-22 at 3 50 02 pm" src="https://user-images.githubusercontent.com/7063154/51564754-20596780-1e5e-11e9-93a1-18c647348b22.png">


I put this field on HWG dev, and it wasnt any slower than anything else insofar as recursively loading child features.

## Additional fields

These fields load after the master field by setting a weight.  

I have two fields.  One displays a table of properties (via featureprop), the other annotations (feature_cvterm).  Right now they are rolled into the same field while developing.  If this went into core, we would have to decide what to do with the feature_cvterm field since we already have SIO__annotations: perhaps an alternative load and view if attached to a feature of type='gene' ?

<img width="641" alt="screen shot 2019-01-22 at 3 57 25 pm" src="https://user-images.githubusercontent.com/7063154/51564872-6f9f9800-1e5e-11e9-8b80-4e94b5c27bfa.png">
  

### collapsing data

In all cases, each direct child is presented in its own collapsible fieldset.  Only the first fieldset is expanded by default.  This is done because for genes with many transcripts, the amount of info would get overwhelming fast.

Each field is intended to be a "summary" of data for the mRNA/transcript entity page.  It's assumed that the site will also have mrna/transcript entities.  However, these fields a) provide a summary on the gene page  for users, and b) pull the metadata up out of the child features, so that annotations etc get indexed by search engines, etc.

I'd appreciate any feedback.  Unless I hear otherwise I'll adapt these fields into a PR into core.   My hesitation is because I don't feel like we have unanimous enthusiasm from the PMC for this solution.

**Comment by laceysanderson** [comment]
I like this approach and feel it should be core functionality 👍 From discussions with users, I feel this is expected functionality which currently causes our gene pages to fall short. Thanks for all your work on this @bradfordcondon!

**Comment by laceysanderson** [comment]
> I have two fields. One displays a table of properties (via featureprop), the other annotations (feature_cvterm). Right now they are rolled into the same field while developing. If this went into core, we would have to decide what to do with the feature_cvterm field since we already have SIO__annotations: perhaps an alternative load and view if attached to a feature of type='gene' ?

I like the idea of making the feature_cvterm functionality an alternate formatter. I personally think we should simply add the recursive loading to the current SIO__annotations->load() and add a setting for the field to turn off recursive loading. It can be on by default but this way if it provides problems for larger sites then they can turn it off

**Comment by bradfordcondon** [comment]
im not sure what to do about gracefully adding the SIO__annotation information.

heres the base field for reference: https://github.com/tripal/tripal/blob/7.x-3.x_732_gene_pages/tripal_chado/includes/TripalFields/data__sequence_features/data__sequence_features.inc

Heres the relvant part of hte SIO__annotation field

https://github.com/tripal/tripal/blob/effd01dc0da2530865b69455e8778a4c62544654/tripal_chado/includes/TripalFields/sio__annotation/sio__annotation.inc#L305-L318

so for gene X, we end up with an set of [$i] annotations that are for that gene. in the feature_cvterm table.  cool.  Each of those has 4 keys in value: vocab, accession, name, and definition.  Also cool.

we want to tack on protein Y's annotations, which is a grandchild of gene X via the feature_relationship table.  Do we continue where we left off with `$i +1`?  And add an additional key with information about which child feature its related to? What about the annotations for gene X?  do they need a corresponding key indicating that those annotations are directly on gene X?  Note that doing it this way, we lose the feature_relationship information (that protein Y is a child of mrna Z that is a child of gene X).  This seems bad and against what stephen and i talked about.

I'm more tempted to drop the info in `$entity->{$field_name}['und'][0]['child_annotations']` or something like that, preserving the feature relationship structure.  At which point, aren't I better off using a distinct field from annotations?  And configuring the child_annotations field to just appear in the same tripal_pane as SIO__annotations?  I would in that case do something like what i do for the child_properties field, here: https://github.com/tripal/tripal/tree/7.x-3.x_732_gene_pages/tripal_chado/includes/TripalFields/local__child_properties

**Comment by bradfordcondon** [comment]
I've made these fields available [via the `tripal_manage_analyses` module](https://github.com/statonlab/tripal_manage_analyses#gene-page-fields).  These fields don't implement web services correctly as we discussed above: the "child" features just have a value of TRUE, and they "borrow" the information from the parent field in the formatter.  However I just couldnt get the weighted loading to work.  

As such I'm going to close the open PR.   We can either close this and the related issue out, or leave them open for someone else to pick up where I left off here.

**Comment by spficklin** [comment]
In Tripal v3.5 we have an updated transcript field which allows the site admin to customize what appears for each transcript on a gene page.  I think it addresses as best we can the primary issue with this thread.... although there is a lot here and I didn't carefully reread everything.  So, I'm going to close out this issue with the assumption that for Tripal v3 we've provided a solution and we can reopen a new issue if there are issues with that solution.  But please comment if this needs to be reopened.
