### ISSUE TITLE
kegg tripal 3

### ISSUE THREAD

**Issue by kyrenya** [tripal/tripal#733]
hi! 
I'm trying to get a file similar to the hier.tar.gz in the KEGG annotation example. I cannot run Kaas locally cause FTP is not free anymore, and when I do the analysis in the server:  https://www.genome.jp/tools/kaas/ I dont see how to download anything similar.  Do I need to download manually all the .keg files and then compress? 
Thanks in advance.

**Comment by bradfordcondon** [comment]
hi @kyrenya the hier file was discontinued (by KEGG).  You can't generate it anymore so we had to totally redo the

 module.   The tripal 3 version of the module now works with the output from the KAAS tools but requires you to load the KEGG OBO we provide.  

Are you trying to run the tripal 3 or the tripal 2 version?  

I need to write user instructions for the tripal 3 version... if thats where you are at I can get on it sooner so you can try it out.

edit- i have some rough instructions at https://tripal-devseed.readthedocs.io/en/latest/loading_KEGG.html

**Comment by kyrenya** [comment]
hi! precisely I asked how I should proceed with functional annotation because I'm working with tripal v3 (latest). Since I didnt know what doc to follow.. I was just trying to prepare the files I would need (KEGG; BLAST; InterproScan outputs). So yes, I'm very interested in trying what you are preparing.

**Comment by bradfordcondon** [comment]
hi @kyrenya was the doc i linked helpful?  I had to wait a day or two for the kEGG annotation job to finish running for teh citrus demo data, but now that it has I can try and get the "official" guide out this week.  I'll post the draft here for you so you wont have to wait for the PR to get accepted.

**Comment by bradfordcondon** [comment]
OK unfortunately the `tripal_analysis_kegg` module has an incompatibility with the final tripal 3 release.  Please don't try to use it until it's resolved.
https://github.com/tripal/tripal_analysis_kegg/issues/18


Apologies.

**Comment by kyrenya** [comment]
oops, ok, I wait for news!  Same for rest of functional annotation modules? where should I look at for blast, interpro.. ?  Thanks again.

**Comment by bradfordcondon** [comment]
hi @kyrenya 
Those documents are in a PR but not merged yet.  

I have built a beta version of said docuentation for you: you can find it here: https://tripal.readthedocs.io/en/689_tv3_ips/user_guide/example_genomics/func_annots.html

If you have any feedback, please leave it in https://github.com/tripal/tripal/issues/689 .

Thank you!

**Comment by kyrenya** [comment]
that is super nice! thank you so much! I will keep you posted!

**Comment by zhuyiqin** [comment]
hi, 
I'm using tripal v2, and want to upload the kegg annotation. Since the KAAS doesn't provide the hierarchical file any more, can I prepare a similar file from the output of KAAS?

**Comment by bradfordcondon** [comment]
sorry for not responding, i dont undertsand your question.  Can you make your own KAAS heirarchy file?  You might be able to, but I wouldn't know how--- i haven't even seen the file, as it was discontinued by the time i started work...


I'm sorry to report we haven't had time to make hte kegg OBO file compatible with the new OBO loader, so this issue is still open...

**Comment by zhuyiqin** [comment]
hi @bradfordcondon 
I read the doc you provided above and have loaded the kegg obo file.  In the doc the KEGG file is 'f_excelsior_ko.txt', but I don'n know the format of this file. Can you give me an example? Thanks!

**Comment by spficklin** [comment]
I'm going to close this out as this conversation really belongs on the Tripal Analysis KEGG Issue queue: 
 https://github.com/tripal/tripal_analysis_kegg/issues queue.

In summary, the primary hold-up for getting a KEGG module that works is 
1) KEGG stopped providing .heir files for results
2) The KEGG vocabulary does not properly fit into Chado :-/

More details can be found at these issues:
https://github.com/tripal/tripal_analysis_kegg/issues/18
https://github.com/tripal/tripal_analysis_kegg/issues/9

**Comment by spficklin** [comment]
Thanks @bradfordcondon for helping here!

**Comment by spficklin** [comment]
I should also add... if there is anything unresolved related to this, please feel free  to open a new conversation on the Tripal Analysis KEGG Issue queue:
https://github.com/tripal/tripal_analysis_kegg/issues queue.
