### ISSUE TITLE
Docs: exporting and importing field configurations with Drupal Features

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#740]
You can find the guide I wrote for myself to test the feature out and learn about the module here

https://www.bradfordcondon.com/2018-11-09-understanding_drupal_features/

In short, the module lets you configure your fields, their  display, etc, and then export them as simple modules which get enabled.  The tutorial I attach a file upload field (for a FASTA file) to analysis, put it in a tripal pane, etc on a dev site, export it, and import it into another site.

* Do you think some port of this would be helpful in the admin guide area in our tripal documentation?  I can port it over.

* Please see sibling issue #741 regarding feature configs getting loaded disabled.

Thanks to @shawnamspoor for discussing hte module with me a bit.

**Comment by laceysanderson** [comment]
I think this would be great in the developers guide!

**Comment by bradfordcondon** [comment]
ok thanks lacey, I'll look into porting it to RST.

**Comment by bradfordcondon** [comment]
merged, thanks for the reviews

**Comment by spficklin** [comment]
Perhaps we should move this over to the User's Guide? Perhaps we could create a new section for topics related to managing a development and production site.  There really isn't any coding required to export field setups, and it's something a site developer would want, but the site developer may not be a coder and would still want to do this.

**Comment by bradfordcondon** [comment]
>There really isn't any coding required to export field setups

can't argue with that.  

I think it is especially relevant in the user's guide in terms of publishing site configurations as exported field configurations for content types.  This is Tripal's "Genomics" organism config vs breeding organism config for example.


Anywhere in particular you propose?  How about immediately after https://tripal.readthedocs.io/en/latest/user_guide/content_types/configuring_page_display.html

?

**Comment by laceysanderson** [comment]
Sure, sounds like a good place to me 👍

**Comment by bradfordcondon** [comment]
Since writing this guide, I've found two things.

1)  When Tripal creates a field set, it appends random numbers at the end, presumably to make sure its unique.  However, this essentialy breaks support for the Drupal field module.
2)  Using the features module appears to mess with Entiites in some way, such that it can prevent modules from creating entities ([such as HQ](https://github.com/statonlab/tripal_hq/issues/109)).  Whats strange is that you can still edit entities directly, but Tripal HQ could no longer manipulate bundles that had been configured with a feature module.  

I believe this issue is still open because it was proposed ot move it into the user's guide, but i'd like a PR to also at least add warnings about those two facts.  I'm not sure about the viability of using drupal features considering hte above points though.

**Comment by laceysanderson** [comment]
If you are here due to the tag "Good first issue" what needs to be done is: Create a documentation PR adding warnings to https://tripal.readthedocs.io/en/latest/dev_guide/exporting_field_settings.html#drupal-features-tutorial. The warning which need to be added were articulated above by @bradfordcondon

**Comment by laceysanderson** [comment]
Closing this as it's now outdated with the move towards Tripal 4.
