### ISSUE TITLE
ability to override fields being added disabled?

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#741]
I am hoping to use the Drupal Features module (Please see #740  ) to develop field configurations on a dev set and deploy on a live site (which i myself dont have access to).

There are two hurdles.  1) . bundle_ids may not be consistent across sites.  For now, I just suggest relabeling manually.  2) (**this issue**):  fields are imported disabled by default.  
Consider the entire point of this Features pipeline is to export field configurations, i htink its clear that providing a way to import them enabled would be ideal.  Is there a way I can do this, in the field configuration or something?  If not, is it feasible to offer some way to do so (for example give the drupal feature module special override?) . Or, is this *still* a bad idea, and we want admins to have to enable the display of the imported fields?

Thanks!

**Comment by laceysanderson** [comment]
I would also like this ability (attach fields enabled in the display by default). @shawnamspoor is this possible already?

**Comment by shawnawsu** [comment]
For clarity, do you mean fields that are coming in and being added to existing content types?

**Comment by bradfordcondon** [comment]
yes, precisely.  Adding fields with a certain layout to the organism content type, for example.

**Comment by spficklin** [comment]
I realize this isn't an old issue, and its desired, but given that @bradfordcondon would have spearheaded this, and he has moved onto greener pastures, I'm going to mark as "Maybe Later" and close this out.
