### ISSUE TITLE
Improper regex for loading FASTA files causes errors

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#75]
Copied from the Drupal issue queue: https://www.drupal.org/node/2691787

It was reported on the mailing list (https://sourceforge.net/p/gmod/mailman/message/34924927/) that if the regular expression used for importing a FASTA file is incorrect that an error message occurs. This should be handled gracefully with a more intuitive notice given to the user. Here is the message recieved:
```
WD trp-fasta: [error]
array_keys() expects parameter 1 to be array, string given tripal_core.tripal.api.inc:117 [warning]
[site http://default] [TRIPAL ] [TRP-FASTA] Array
strtr() expects parameter 1 to be string, array given syslog.module:115 [warning]
syslog() expects parameter 1 to be long, string given syslog.module:118 [warning]
html_entity_decode() expects parameter 1 to be string, array given unicode.inc:463 [warning]
WD trp-fasta:
```

**Comment by spficklin** [comment]
This is low hanging fruit and has been in the queue for 2 years. We should fix this.

**Comment by bradfordcondon** [comment]
I couldnt recreate this exact error, but i did add validation that I think is pretty straight forward in the form.  In addition i improved the error reporting.

**Comment by spficklin** [comment]
Thanks @bradfordcondon for working on this older issue :+1:
