### ISSUE TITLE
Docs: Port documentation from tripal.info to readthedocs

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#750]
We have many very old documents on the Tripal.info site that are of the content type Document.  I think they need to be removed or moved into the User's Guide.    @laceysanderson would you mind taking a look at those when you have a chance and say what you think?

**Comment by spficklin** [comment]
Also the Tutorial content type is really old as well...

**Comment by laceysanderson** [comment]
I definitely do not want to see any of that documentation removed.

My vote would be to 
1. move anything still applicably to Tripal3 into our new ReadtheDocs documentation
2. port all Tripal2-applicable docs into the Tripal2 user guide "book"
3. port the remaining pages into "Basic Page" format.

This allows you to remove those content types without losing the information.

**Comment by bradfordcondon** [comment]
I'm listing the pages i see as possibly helpful integrations into the RTD guide. I don't distinguish between published /unpublished, just going on titles.  

The rest is stuff for tripal 1 or 2 .  For example, ["Upgrade from Tripal v2.0a to v2.0-rc"](http://tripal.info/documentation/upgrade_2.0a_to_2.0-rc).   Given the objection about deleting, seems unlikely this will get touched as it requires a bit of work to move stuff into the tripal 2 guide, create new pages, etc. But I'll leave open.


### Documentation


* http://tripal.info/node/37
* http://tripal.info/download/development
* http://tripal.info/node/35
* http://tripal.info/documentation/tripal_saml_integration
* http://tripal.info/documentation/genotypes
* http://tripal.info/node/32

### Tutorial

* http://tripal.info/node/256
* http://tripal.info/node/136
* http://tripal.info/node/134
* http://tripal.info/documentation/search_path
* http://tripal.info/node/60
* http://tripal.info/node/25
* http://tripal.info/node/38

**Comment by spficklin** [comment]
I'm going to close this out as it's not critical and those docs are mostly for Tv2 and we're working on Tv4.
