### ISSUE TITLE
cache entiites

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#751]
Right now, fields get cached, but not entities.  The solution we came up with for #732 was to have the relationship field put the returned child feature record in the field (but not in the value.) . This is OK, but could be redundant if lots of fields are doing it.  Instead, they could update the entity itself, but, because we dont think the entity is cached, it wouldnt be available to other fields.

**Comment by spficklin** [comment]
I'm not sure we want to cache an entire entity, but I see your point about having fields caching the record repeatedly.  Maybe we could setup an entity cache that caches the record object so it's always available?

**Comment by laceysanderson** [comment]
Closing as it has been a year with no movement. Please comment if you would like to revive the conversation on entity caching.
