### ISSUE TITLE
migrate satellite documentation in markdown into RTD

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#756]
* Move documentation for contirbuting, testing, etc, into RTD
* Have sub-README link out to RTD instead

pre-approved after discussion with @tripal/project-managent-commitee-pmc

**Comment by bradfordcondon** [comment]
ok, im ready for a PR but i want to wait for #754 
Originally I was going to create a new "contributing" section that has testing, governance, PR guidelines..

should it instead be a "community" section?  And it cna also include the extension module list?

**Comment by laceysanderson** [comment]
I kinda like the idea of it living in the developers guide since that's who it's intended for?

**Comment by bradfordcondon** [comment]
testing definitely, pr guidelines.  i think the governance stuff might be broader than that?  otherwise yeah agree.

**Comment by bradfordcondon** [comment]
heres my previous setup

![screen shot 2018-11-20 at 11 01 49 am](https://user-images.githubusercontent.com/7063154/48785919-b41e8400-ecb3-11e8-86e7-4a110d4dc0e0.png)

new setup per lacey's rec:

![screen shot 2018-11-20 at 11 03 59 am](https://user-images.githubusercontent.com/7063154/48786060-02cc1e00-ecb4-11e8-8eed-c0113b301b60.png)

I'll make the PR for this so we can review easier.

not convinced one way or the other.  Dev guide looking a little crowded...

**Comment by bradfordcondon** [comment]
merged.
