### ISSUE TITLE
Tripal registration page

### ISSUE THREAD

**Issue by shawnawsu** [tripal/tripal#759]
* This feature does attempt to solve an existing problem with Tripal
* I am open to developing or collaborating on an extension module if this is not a good fit for Tripal Core

* This feature is Not Urgent

### Description
Tracking mechanism for tripal use, so we know how many sites are using it and we can notify them when updates are available.
-Registration page:	
--A message for why this is important.
--Checkbox to disable registration reminder.
--Principal Investigator Contact: Name, Email. (required))
--Site admin contact:  Name, Email
--Description of the site
--Funding Source: agency and grant #, funding period (unlimited number)
--Purpose: (radio) Development or Production (required).
--Provide Tripal (not other 3rd party modules) module usage information (Checkbox).

-How to receive this information on Tripal.info?  
-- First-time registration form submits the info to Tripal.info and a new "registration" node is created.
---Views and data analytic tools can be created as needed with the transmitted info.
--Every month the site pings tripal.info to let us know the site is still active and if applicable module usage so we know if new Tripal modules have been installed.

Tripal.info is in the process of being upgraded to Drupal 8 so the new RESTful web services module in core can be leveraged.

### Generally Applicable
This update will allow us to push out notifications about Tripal and Tripal Extension module updates that are ready for download. Additionally, it will provide more accurate usage statistics since many users are not downloading the module through drupal.org.

The form will be an opt-in registration so users can choose not to register the site if it's a dev site or if they simply do not wish to share that they are using Tripal. Users will be reminded to register the site until they either do so or check the 'disable reminders' checkbox.

**Comment by bradfordcondon** [comment]
tracking extension module usage would be so awesome.  I am therefore very excited about this integration.  We should consider additional ways to make this useful to the Tripal community to encourage its use.


Note that 

>--Funding Source: agency and grant #, funding period (unlimited number)

is going to change over time.  It might want to be associated with a time frame.  (2012-2016: NSF XXXX.  2017-2018- NULL.  2019-present: USDA XXXXX)

So i realize now, you pretty much say exactly that.  I wasn't adding anything meaningful, sorry :P)

Should we ask for site archetype?  Breeding vs genomic?

**Comment by spficklin** [comment]
That funding source should have unlimited cardinal so that users can add new sources over time.

**Comment by bradfordcondon** [comment]
this is merged, closing.  Thanks @shawnawsu
