### ISSUE TITLE
Relationship Widget Minor Fixes

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#762]
### System information

* Tripal Version:  3.x
* Drupal Version:  N/A
* PostgreSQL Version  N/A:
* PHP Version: N/A

### Issue description

After @laceysanderson did a wonderful job of fixing the relationship widget, there are a few minor outstanding items that need fixing on the widget.  I've moved them to this new issue from the discussion on PR #726.

1.  When adding a new entity for a content type that has relationships it's not clear how to refer to the record being added such that it can be used in a relationship. It's only possible to set relationships for entities that already exist and editing them.
> Its own name wont fill out the autocomplete box. I can infer that it needs to be genus species based on the autocomplete... Maybe the field instance setting description should be dynamic and describe what the name field is going to consist of? Note that despite the warning, the form does submit and correctly create the relationship. way to go.

> Maybe a more intuitive way to do this is to use form states to hide the subject/object boxes. Then you start with a radio button that says "this record is the subject" and "this record is the object", and only display the other box for looking up the "other" record.

~~2.  If a relationship type (e.g. 'part_of') has two words rather than one then the widget gives a validation error.~~  (see new issue here #801 BC)[original screenshot](https://user-images.githubusercontent.com/1719352/48812484-6ae82780-ece7-11e8-94c7-80bafec84140.png)
3.  When creating a relationship for the project content type the word "project" seems to have an odd pattern for bolded words. [original screenshot](https://user-images.githubusercontent.com/1719352/48812563-c0bccf80-ece7-11e8-9a2f-42063333b675.png)
4. Unable to remove a relationship.
> Its not possible to remove a relationship with this widget. I can manually unset everything, however, the field then fails validation.

5. Formatter for shows "feature" rather then the content type (e.g. "Genetic Marker"). [original screenshot](https://user-images.githubusercontent.com/7063154/48785041-e929d700-ecb1-11e8-8b52-594e839cbf2e.png)
6. On some theme's, the widget expands out of the box. [original screenshot](https://user-images.githubusercontent.com/7063154/48778007-20908780-eca2-11e8-9878-45dd643cbe14.png)

**Comment by bradfordcondon** [comment]
>If a relationship type (e.g. 'part_of') has two words rather than one then the widget gives a validation error. original screenshot

I can use the term `part_of` no problem.

Now that Im looking at your screenshot, you use the term "I-box promoter motif" and thats what is giving you a problem.  I can recreate the error, but look what happens if i look for this cvterm: `select * from chado.cvterm where name='I-box promoter motif';`

I think the actual issue is that there are **Sequence ontology terms in the autocomplete that dont exist**.  I've noticed this problem elsewhere, when randomly grabbing sequence ontology terms to use as type_ids.  I don't think this problem pertains to this PR and is its own distinct issue.  I'll create one.


I can recreate the problem using the ANNOTATION widget when creating a feature:

![screen shot 2018-12-19 at 12 19 22 pm](https://user-images.githubusercontent.com/7063154/50236428-5e0f3000-0388-11e9-9539-08890370fc81.png)
gives me the warning:
```
Cannot find a term that matches the term name and vocabulary.
```

i created a child issue here #801

**Comment by spficklin** [comment]
Hi @laceysanderson just checking on this.  Will we have a fix for the v3.1 release soon?  Thanks.

**Comment by laceysanderson** [comment]
I took some much needed time for family this holiday season :-) Working on it today.

**Comment by laceysanderson** [comment]
### Remaining Issues (original numbering):
1.  When adding a new entity for a content type that has relationships it's not clear how to refer to the record being added such that it can be used in a relationship. It's only possible to set relationships for entities that already exist and editing them.
> Its own name wont fill out the autocomplete box. I can infer that it needs to be genus species based on the autocomplete... Maybe the field instance setting description should be dynamic and describe what the name field is going to consist of? Note that despite the warning, the form does submit and correctly create the relationship. way to go.

> Maybe a more intuitive way to do this is to use form states to hide the subject/object boxes. Then you start with a radio button that says "this record is the subject" and "this record is the object", and only display the other box for looking up the "other" record.

6. On some theme's, the widget expands out of the box. [original screenshot](https://user-images.githubusercontent.com/7063154/48778007-20908780-eca2-11e8-9878-45dd643cbe14.png)

**Comment by laceysanderson** [comment]
PR Submitted for current fixes.

**Comment by spficklin** [comment]
Does the PR fix all the outstanding issues?

**Comment by laceysanderson** [comment]
Unfortunately not. Problems 1 & 6 above are still outstanding. However, they do not need to make it into the 3.1 release (in my opinion).

**Comment by spficklin** [comment]
Okay.  Thanks. I've removed them from the 3.1 milestone/project
