### ISSUE TITLE
Issue with tripal_ds_update_ds_layout function 

### ISSUE THREAD

**Issue by mboudet** [tripal/tripal#763]
### System information

Tripal: 7.x-3.0
Drupal : 7.59
Postgres: 9.5.8
Php: 7.1.23

### Issue description
I'm trying to setup fields and fields group programmatically (As in, enable fields, set them up in the field group, and place them).
The tripal_ds_update_ds_layout function should take some field groups and fields, enable them and set them up. However, nothing happen when the function is used.

The tripal_ds_create_field function use this function, so the same issue should occurs (meaning, the panel is created but not set up)

### Issue details

The issue is the [drupal_write_record](https://github.com/tripal/tripal/blob/3606ca5cf8891a068c0dc5ebe6ac48f245252136/tripal_ds/tripal_ds.module#L435)

We feed layout_info to the drupal_write_record, but the layout_info is just an array, it does not refer to any element of the table, nor a field.

Either layout_info should be a full-on object (like [here](https://github.com/tripal/tripal/blob/7f35a59c5e48bd173d06da51e28d8abbfebc8594/tripal_ds/includes/tripal_ds.field_group.inc#L10)), or we should use db_update to update the select field..

Something like 
```
db_update('ds_layout_settings')
        ->fields(array(
            'settings' => serialize($layout_info),
        ))
        ->condition('ds_layout_settings.id', $ds_identifier, '=')
        ->execute();
```

Also, this function does not check if the field/field group is already in the layout.. it might be good to add a check.

#### Steps to reproduce
Use the tripal_ds_update_ds_layout function. Nothing happen (no change in DB, no error).

#### Others

For now, my workflow to create a field group, add a field to it, and publicize it is as follows : 

1. Create a field group with tripal_ds_create_field
2. Edit the field group in DB to add the field as children
3. Use tripal_ds_update_ds_layout to add both to the layout.

Is there any simpler way? I feel like the tripal_ds_create_field function should have an optional argument to customize the created panel (at least, to add children or parents to it)

**Comment by bradfordcondon** [comment]
>I'm trying to setup fields and fields group programmatically

Have you checked out the Drupal features module?  It lets you do exactly this.  Granted, its for exporting and sharing your field configuration, so if you must define the groupings programmatically to begin with it won't help you.
  I wrote a full tutorial:

https://tripal.readthedocs.io/en/latest/dev_guide/exporting_field_settings.html

**Comment by spficklin** [comment]
I believe this is now resolved given the merged pull request.
