### ISSUE TITLE
functional modules v3.0

### ISSUE THREAD

**Issue by kyrenya** [tripal/tripal#766]
Hi there! 
I'm trying to follow the manual for functional annotation: 
https://tripal.readthedocs.io/en/latest/user_guide/example_genomics/func_annots/setup.html

When checking for new fields in STructure--> Tripal Content Types, the manual says check manage fields in mRNA but the image shows the fields in Gene. Anyway, when I do it in both places, I don't see anything similar to the example. No new fields related to functional modes showing. 
But, if I go to 
Structure --> Content Types: 
![image](https://user-images.githubusercontent.com/43243429/49078613-67e4be00-f236-11e8-83fc-79d933430cf4.png)

I find there content for Blast and Interpro. 

Is this how its supposed to be? 

        Thanks.

**Comment by kyrenya** [comment]
taking a look at the modules, I see I have Tripal extensions: Tripal Blast and Tripal Interpro (probably this is what I am interested in, right?  but tripal V2 Legacy modules are also enabled (dont know when this happened, since I thought I had made a clean installation of tripal 3.0). Should I disable Tripal Core and everything in Tripal V2 Legacy? 

![image](https://user-images.githubusercontent.com/43243429/49079727-4e914100-f239-11e8-8f19-eadd82c7c2c6.png)
![image](https://user-images.githubusercontent.com/43243429/49079743-5b159980-f239-11e8-8d45-cf99bcfb6008.png)

**Comment by bradfordcondon** [comment]
before you can add the field, you need the 7.x-3.x version of the module enabled.  You must follow the git instructions for installing for now until we make an official drupal release.  

* disable and delete the 7.x-2.x versions
* go to the module repo (ie https://github.com/tripal/tripal_analysis_blast), clone the module, and enable it.  
* We have recently made the default branch of each 7.x-3.x, but double check thats the branch you are on.
* re-enable the module
* click "check for new fields" in the gene and/or mRNA bundle, and the blast/interpro fields should bappear.

**Comment by kyrenya** [comment]
ok, I'll do so and let you know. 
other question.. why inside Tripal V2 Legacy the modules are 7.x-3.0 versions? should I then disable all inside that Tripal V2 Legacy box?

**Comment by bradfordcondon** [comment]
those are the legacy modules.  The version is 7.x-3.x because they are distributed with tripal 7.x-3.x and we changed all the versions in that module... maybe it should instead be 7.x-2.x, what do you think @tripal/project-managent-commitee-pmc ?

eitehr way, the answer to your question is, keep them enabled if you are running legacy code, and you can disable them if you are not.

[from the docs:](https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/upgrade_from_tripal2.html?highlight=legacy)

>7 Enable Tripal v2 Legacy modules. Tripal v2 modules are now called ‘legacy modules’. these are the modules that were disabled in step #2. For backwards compatibility, you should re-enable these modules:

So if you are running legacy modules that require them, you might want them enabled.  if not, you can disable.

**Comment by kyrenya** [comment]
ok! Crystal clear! thanks!

**Comment by kyrenya** [comment]
> before you can add the field, you need the 7.x-3.x version of the module enabled. You must follow the git instructions for installing for now until we make an official drupal release.
> 
>     * disable and delete the 7.x-2.x versions
> 
>     * go to the module repo (ie https://github.com/tripal/tripal_analysis_blast), clone the module, and enable it.
> 
>     * We have recently made the default branch of each 7.x-3.x, but double check thats the branch you are on.
> 
>     * re-enable the module
> 
>     * click "check for new fields" in the gene and/or mRNA bundle, and the blast/interpro fields should bappear.

ok, I already git cloned the modules, but now in the site I see this: 
![image](https://user-images.githubusercontent.com/43243429/49098086-063c4800-f266-11e8-9130-4f3aca208f22.png)
This is a thing for you guys to develop this modules.. or am I supposed to update?

**Comment by bradfordcondon** [comment]
oh the recommended version?  yeah dont worry about that, you're all set, you can try to add hte fields now.

**Comment by kyrenya** [comment]
Thxx! I will keep you posted about my progress :)

**Comment by spficklin** [comment]
@bradfordcondon in regards to the version number of the legacy modules. The code that comes in the legacy modules has been gutted quite a bit, and so those modules do merit a major version increment.  So, I think the 3.x version is correct.    Also, we can't downgrade the version now that Tripal v3 is out in the wild.  Drupal stores the current version of the installed modules and upgrades will go sour if we do that.

**Comment by bradfordcondon** [comment]
ah yes of course, forgot we really cant downgrade versions. thanks stephen.

**Comment by spficklin** [comment]
There's been no further conversations in a few months on this.  I'm going to close it out. Please comment if more is needed.
