### ISSUE TITLE
API Embedded in RTD with User's Guide and Dev Handbook

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#768]
So, it is possible to integrate our Doxygen style commenting in Tripal with Sphynx and Read the Docs.  That would place our User's Guide, Developer's Handbook and the API all in one RTD interface.  It would allow us to update the API quicker because we wouldn't have to fight with the Drupal API site we currently maintain.   I really like this idea but there are some caveats.

1.  We have to commit the Doxygen generated XML into the repository so RTD can find it.
2.  We have to add a requirements.txt file so that Sphynx can install the breathe library
3.  We have to manually create a page for each API in our docs folder and use breathe directives to point to the proper API.  It's not hard to do, but just requires someone to do it.
4.  We have to edit *all* of our API functions and add the input type to all of them or breath croaks!  I'll put in a request on the breathe GitHub to see if they can fix that. Otherwise this will be a lot of work and may break stuff!

We did this for the Tripal Galaxy module.  An example can be seen here:  https://tripal-galaxy.readthedocs.io/en/latest/API/api_funcs.html

**Comment by bradfordcondon** [comment]
OK so our previous attempts were unsuccessful because we didnt specify the type for each input parameter the way it expected?

**Comment by bradfordcondon** [comment]
breathe no longer breaks if theres no type on the parameter (although the more info to display, the prettier breathe is).
I've also got it set up on one of my modules: see here . https://tripal-eutils.readthedocs.io/en/latest/development.html

>We have to commit the Doxygen generated XML into the repository so RTD can find it.

actually we can have RTD run doxygen. .  see:  https://breathe.readthedocs.io/en/latest/readthedocs.html
I am doing this on the above linked eutils module.

>We have to manually create a page for each API in our docs folder and use breathe directives to point to the proper API. It's not hard to do, but just requires someone to do it.


yeah, my biggest complaint about breathe integration is that it doesnt create section headesr for functions etc.  If you do a `@group`, and make a page for that group, it wont benefit . from any automated headings ofr each function, etc.  this is disappointing.

All that said, its probably still desirable to make this happen.

**Comment by spficklin** [comment]
I'm going to retract this request. We have the Tripal Galaxy API and it is not as usable as it is the way we have it now.  I prefer our current approach.
