### ISSUE TITLE
Can't remove publication from organism page

### ISSUE THREAD

**Issue by patricksis** [tripal/tripal#769]
### System information

* Tripal Version: 3.0
* Drupal Version: 7.61
* PostgreSQL Version: 9.6.11
* PHP Version: 7.2.11

### Issue description
Publication was link to the organism page instead of reference genome and now the publication cannot be remove from organism page. 

#### Steps to reproduce
Create organism page and link the publication. Attempt to edit and remove publication. Try to save organism. You should get an error

#### Error messages and screenshots

```
Could not save the TripalEntity: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "" LINE 1: ...nism_pub_id = '3', organism_id = '60', pub_id = '' WHERE ... ^
Cannot save entity
```

**Comment by spficklin** [comment]
Hi @patricksis I can confirm that this does occur as you have indicated.  I've marked this as a bug and added it to our milestones to fix before our v3.1 release which we hope to put out in the next few weeks. 

In the meantime I'll look into this and see what's going on and try to make a fix.

**Comment by spficklin** [comment]
@patricksis I believe I have fixed the problem and I've committed a pull request for review by others on the Tripal core development team.  If you feel comfortable with pulling branches would you mind testing to see if the fix works for you?  If not, we'll perform the test and let you know if successful when it's available in the main branch.

**Comment by bradfordcondon** [comment]
merged and confirmed.  thanks for bringing this to our attention!
