### ISSUE TITLE
Creating of proteins by GFF3 loader should be optional

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#77]
Copied from the Drupal issue queue:  https://www.drupal.org/node/2550979

Creation of protein features when importing a GFF3 file was recently added. This was done to make the Tripal GFF loader similar to the perl Chado loader. However, this functionality should be optional as those protein features are technically not in the GFF3 file and may confuse folks when they unexpectedly appear.

**Comment by bradfordcondon** [comment]
Do we still want this feauture?  Should the default still be to ignore them?  I would think the default should be to create, with the option to ignore....

**Comment by bradfordcondon** [comment]
assigning myself because i implemented and wrote some tests because why not.

**Comment by bradfordcondon** [comment]
Can I get some suggestion for the text?

>      '#description' => t('Check the box if you would like to create the proteins described in the GFF file.'),

Also @laceysanderson  we decided to add a category as "loader" for test locations right?  I need to update the README as well...

**Comment by spficklin** [comment]
Issue fixed with PR -- long time overdue.
