### ISSUE TITLE
request: dbxref widget create new accessions like the primary accession widget can

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#770]
## feature request

A checkbox on the dbxref input widget, that allows you to create a dbxref (accession) if it doesnt already exist.

### Description

Right now, it's difficult to create a dbxref accession via the GUI.  If you want to use the GUI, you have to insert a cvterm.  The dbxref admin area only lets you look up, not insert, accessions.

What I propose and @almasaeed2010 supports and will develop is  modifying the input dbxref widget.  We'll add a checkbox that says "create accession".   If checked, the widget will insert a new dbxref record before inserting into the db.

### Your Specific Use Case
We have undergrad annotators, and we want to associate ncbi accessions (bioproject) with stuff as they create it.  Asking them to insert cvterms via the GUI, or to do SQL, is both too hard.

### generally applicable

If you ask me this is a weakness shared by other input widgets where it would be really handy to create the linked record "on the fly".

**Comment by bradfordcondon** [comment]
oops: is this a bug instead?

https://github.com/tripal/tripal/blob/e9f107bf41e70658f003d4e659bbb024d029c7d9/tripal_chado/includes/TripalFields/data__accession/data__accession_widget.inc#L140-L150

@almasaeed2010 can you please provide the message for failed submission with a novel accession?

**Comment by almasaeed2010** [comment]
The error message on a publication entity:

```
Could not save the TripalEntity: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "" LINE 1: ... INTO chado.pub_dbxref (pub_id, dbxref_id) VALUES ('23', '') ^
Cannot save entity
```

Similar error on organism entities:

```
Could not save the TripalEntity: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "" LINE 1: ...o.organism_dbxref (organism_id, dbxref_id) VALUES ('60', '') ^
Cannot save entity
```

**Comment by bradfordcondon** [comment]
sorry i got confused because the c ode i linked above is for data__accession, which is for a primary accession.  we are discussing cases of secondary accessions, handled by the sbo__database_cross_reference widget.  

So we're back to feature request: can this widget also create accessions, gated behind a checkbox (or perhaps a field setting?) if necessary?

either way the bug component is that the validate portion of the cross_reference widget is failing.

**Comment by laceysanderson** [comment]
I Vote yes. I don't even think it needs to be gated behind a checkbox since that's what I would expect to happen
