### ISSUE TITLE
clearing previously set fields is more confusing than it could be

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#776]
https://github.com/tripal/tripal/blob/c3b0ea1914b4a80aeeaf5b62fe638d3987a3a695/tripal_chado/includes/TripalFields/data__sequence/data__sequence_widget.inc#L77-L82

clearing previously set fields is confusing.  you need to remember to set the `value` to something, like above, so that the field storage empties out the field, instead of just ignoring it.  See  #775  for a fix for this issue for required fields.

**Comment by spficklin** [comment]
Agreed. We should find a better way to recognize this condition.

**Comment by spficklin** [comment]
I added this to the 3.2 project so we can revisit it when we start thinking about that release.

**Comment by laceysanderson** [comment]
I'm closing this our focus has moved to Tripal 4 and this is currently functional although I agree not ideal.
