### ISSUE TITLE
Backport of File Usage/Quotas to Tripal v2.

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#777]
The Tripal Galaxy module relies on quotas.  We have the user file quotas in Tripal version 3 but not Tripal version 2 and The Tripal Galaxy module is compatible with both.   We should consider adding that functionality to Tripal v2?

**Comment by laceysanderson** [comment]
I worry there are not the developer hours for this @spficklin... and I believe ppl should be upgrading to Tripal3 (even in legacy mode) at this point. Perhaps this should be closed?

**Comment by spficklin** [comment]
It has been decided by the PMC not to do more updates to Tripal v2 due to the reasons @laceysanderson points out.
