### ISSUE TITLE
missing chunks error when uploading big files (~5G) #34

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#778]
### System information

* Tripal Version:  3.x
* Drupal Version:  7.x
* PostgreSQL Version: N/A
* PHP Version: N/A

### Issue description

This issue was reported on the Tripal Galaxy module, but it is really a Tripal problem because Tripal provide the uploaders.  Please see the issue there for more details.  https://github.com/tripal/tripal_galaxy/issues/34.

#### Steps to reproduce

Upload a really huge file using the Tripal uploader class and see if all the chunks make it.

#### Error messages and screenshots

```
error message
```

**Comment by laceysanderson** [comment]
@spficklin is there any plan to fix this?

**Comment by spficklin** [comment]
I think this issue may not still be present. I've not heard any more complaints of this happening and we use the loader in all of our Tripal Importers so I'm going to close this out and we can reopen if the issue reappears.
