### ISSUE TITLE
Field Pagers

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#783]
### System information

* Tripal Version: 3.x
* Drupal Version:  7.x
* PostgreSQL Version: N/A
* PHP Version: N/A

### Issue description

When creating a pager for a field you are expected to give it a pager index.  Drupal expects that all pagers have an index this is because you can have more than one on a page and the index is used to distinguish which one the user is expecting to use.  Unfortunately, with fields, we never know how many pagers will be on the page and therefore the field developer cannot properly pick a proper index for the pager.  Instead, we need a way for the entity object to maintain a count of the number of pagers so that it can then be used to set the index number for each pager.

**Comment by spficklin** [comment]
Also, the documentation in the developer's User's Guide needs to be updated.

**Comment by laceysanderson** [comment]
I see the documentation made it in https://tripal.readthedocs.io/en/latest/dev_guide/custom_field/custom_formatter.html?highlight=pager#creating-pagers 🎉 

Is this resolved @spficklin?

**Comment by spficklin** [comment]
I'm not sure!  I forgot all the changes made.  I need to check it.

**Comment by spficklin** [comment]
There is no problem it works as advertised!  I added a PR to fix some bug in the spinner but that's all.
