### ISSUE TITLE
Tripal Advisory Committee

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#786]
This issue summarizes discussion from this issue #344 regarding a Tripal Advisory committee for Tripal.  
The Advisory Committee is different from the Project Management Committee (PMC).  The PMC's role is to provide oversight over code development. It ensures quality standards, approves feature requests, and accepts pull requests.  The Advisory Committee is meant to provide guidance for the future of Tripal.

Here's the current proposal put forth by @mestato:

1. Meetings: once per year (January, pre-hackathon with teleconference option?) and as needed other than that, can be called by PMC
2. Director: elected by board at January meeting, responsible for calling votes, calling additional meetings if needed, and making sure meeting notes are posted and communicated to PMC
3. Responsibilities: board members agree to serve for one year at a time, beginning by attend the yearly board meeting (in person or online) and to respond to issues in a timely manner when requested by the PMC or other board members. Their responsibility is to provide high level advice on steering Tripal which may relate to overall approach, development priorities, upgrade timelines, funding, etc. Issues will be available for full community discussion for x number of weeks prior to a vote
4. Eligibility: anyone who has led a group who has published or maintained/updated a publicly available Tripal module within the past 2 years or has funding for Tripal development (core or extension). 
5. Election: anyone who is eligible and willing is welcome
6. Terms: indefinite since its all volunteer based
7. Decision making: Consensus based, vote called when needed by director, all objections recorded in meeting notes
8. Agenda: items can be set by anyone on PMC or board
9. PMC seat: at least one person from PMC has a seat on the board
10. PMC issues: if PMC wants the board to weigh in on an issue outside the yearly meeting, they can request a meeting by notifying the director

**Comment by spficklin** [comment]
Thoughts regarding "Eligibility" (item 4 above).  I would like to broaden that a bit to perhaps allow external folks with a high-level of experience with Cyberinfrastructure and that may or may not be someone within our typical Tripal community.   It is important that Tripal meets scientific needs but also prepared for modern technological advances too.

**Comment by bradfordcondon** [comment]
I believe elsewhere we discussed that Tripal serves users who might not be contributing to the core code and thats a good thing, and we would therefore like to include such a PI to ensure their needs are met.  So I'd 👍 loosening that criteria.

**Comment by bradfordcondon** [comment]
Progress summary from PAG on this issue at: https://docs.google.com/document/d/1cyv3cGDKqAYXpZ9UNsDwPMO4QI7fsJuXUIAiCuzMeEE/edit#heading=h.ss2d09glm34k

im grateful to those present for meeting and discussing.  Were there any action items created in terms of forming the committee/taking first steps?  @mestato ?

**Comment by spficklin** [comment]
Yes, we decided to dedicate Febuary's Tripal User's Meeting to this topic as well as the white paper that Dorrie mentioned.

**Comment by mestato** [comment]
New draft of advisory committee at the end of the "Tripal Community: Draft Guidelines for encouraging open communication" document, which can be found here:

https://docs.google.com/document/d/12bgwGcoH_od6hyle-Aa4USrc-DS8cZ9bbJvfB3jQGyQ/edit?usp=sharing

Comments and edits welcome! For anyone really wanting to dig in deeper on this, I found a few online definitions/examples of advisory board policies that might be worth reading:
- https://en.wikipedia.org/wiki/Advisory_board  (yes, this is the obligatory wikipedia starting point :)
- https://hwm.wisconsin.edu/advisory-board-responsibilities-and-guidelines/
- https://www.asha.org/uploadedFiles/ASHA/About/governance/Resolutions_and_Motions/2015/SOP-Science-Advisory-Board.pdf

**Comment by ekcannon** [comment]
A draft of the formal Tripal governance document is here: 
[https://docs.google.com/document/d/1iRGmZzKnAm8c5Q9yYLiTctSJaRqnT6Bm0eix1uzoTxw](https://docs.google.com/document/d/1iRGmZzKnAm8c5Q9yYLiTctSJaRqnT6Bm0eix1uzoTxw).

Meg and I, acting co-chairs of the Scientific Advisory Committee (SAC), are requesting comments, particularly on the SAC portion of the document by next Monday (Feb 18).

Please add comments to the document or to this issue.

**Comment by guignonv** [comment]
Sounds good to me. Nothing to add. :)

**Comment by mestato** [comment]
A new round of edits and discussion has been added to the document by the interim steering committee:
https://docs.google.com/document/d/1iRGmZzKnAm8c5Q9yYLiTctSJaRqnT6Bm0eix1uzoTxw/edit?usp=sharing

We're getting close to a final version! Please feel free to comment here or on the document. We'll be discussing and voting at the next Tripal dev meeting.

**Comment by spficklin** [comment]
As we have the TAC worked out and documented elsewhere, I'm going to close this out.
