### ISSUE TITLE
Is it (still) possible to join Chado data and Drupal field data in Drupal views?

### ISSUE THREAD

**Issue by guignonv** [tripal/tripal#789]
branch: Tripal 3

I tried to create a Drupal view that would allow me to display both data from Chado and Drupal on a same page without any success. On Tripal 2, this could be achieved using Drupal views relationship between Drupal node and the corresponding Chado table. On Tripal 3, I didn't find the possibility to join those 2 sides.

I can only either create a view on "Chado stock" or create a view on "Accession" for instance, but none of them can "reach the other side of the database".

If you create a "Chado stock"-based view, how could you provide a link to the corresponding Drupal entity?

If you create a "Accession"-based view ("Accession" being the Tripal entity that is related to a type of Chado stock), how could you display the related organism common name (stock.organism_id->organism.organism_id, organism.common_name) for each record or a specific picture (stock.stock_id->stock_dbxref.stock_id/dbxref_id->dbxref.dbxref_id/db_id->db.db_id by filtering on a given db.name)?

I used to do it a lot on my Tripal 2 views but this issue prevents me from migrating to Tripal 3 at the moment.

**Comment by bradfordcondon** [comment]
I think the best solution is to attach fields to the accession (the tripal 3 entity that maps to your chado.stock type of interest).   The first example you give is stock.organism_id.  This maps to the `obi__organism` field: https://github.com/tripal/tripal/tree/7.x-3.x/tripal_chado/includes/TripalFields/obi__organism

it should already be attached to your stock.   if we look at the `query` function, we can see it already provides a way for the view to query genus, species, etc

https://github.com/tripal/tripal/blob/434c0ab2d19cc78571a4b23f1b97613026eb48c6/tripal_chado/includes/TripalFields/obi__organism/obi__organism.inc#L284-L295

I think in your case your organisms are going by common_name so it should be searchable by the "label" field, if you have your organisms set to be labeled with common name.

As for picture via db, im not sure whats going on there. But agian, waht I imagine you will want is to think in terms of fields.  I'd guess you want to write a field that attaches to the "Accession" entity, and displays the picture.  Then, in the query function, you make it queryable by the db name.

**Comment by spficklin** [comment]
I @guignonv all of that Views support from Tripal v2 should still be available.  If it is not working as before then we may have inadvertently broken in.  I'll look at it.

**Comment by guignonv** [comment]
Thanks! So we don't have to deal with relationships in views now and only rely on fields. So far, I gave a quick look into what you proposed and it seems ok. But I need to investigate more. I'll let you know if I face new problems. I also have to investigate other uses cases with a colleague.

**Comment by guignonv** [comment]
Thanks! So we don't have to deal with relationships in views now and only rely on fields. So far, I gave a quick look into what you proposed and it seems ok. But I need to investigate more. I'll let you know if I face new problems. I also have to investigate other uses cases with a colleague and I'm not sure your solution fits but we'll try.

**Comment by spficklin** [comment]
You should be able to use views on Chado tables just like you did in Tripal v2.  I'm sorry I haven't had time to dig into it to make sure it's working yet....

**Comment by guignonv** [comment]
I'm currently investigating the code and I think I got what's wrong.
In "tripal/tripal_chado_biews/tripal_chado_views.views.inc", hook "tripal_chado_views_views_data_alter", the loop line 610:
```
    $tvi_query = db_query('SELECT * FROM {tripal_views} WHERE base_table=1');
    foreach ($tvi_query as $tvi_row) {
```
iterates on base names but these can't be used as linking table. So we got a list of linking table like that "chado_acquisition, chado_analysis, chado_assay,etc." while we should have instead a list like that "chado_bio_data_1,chado_bio_data_2,chado_bio_data_3,etc.".
I'll try to see how to get there but if anybody already got an idea, let me know! :)

**Comment by guignonv** [comment]
I created a pull request #850 that partially solves the problem right now.

**Comment by laceysanderson** [comment]
@guignonv do you still feel the need for a full solution?

**Comment by guignonv** [comment]
Nope.

**Comment by laceysanderson** [comment]
Ok, thank you for getting back to me. I'm going to close the issue for now but if your needs change, please comment and I'll re-open
