### ISSUE TITLE
Allow Bulk Loader to Delete Records

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#79]
Copied from Drupal issue queue: https://www.drupal.org/node/2499299

Valentin expressed a need for the bulk loader to delete records.

From the meeting Notes:

Is there a way to remove (or replace) data that was added via the bulk loader. For instance, for the stock_cvterm table. I have a stock linked to the cvterm ‘in vitro collection’ (through stock_cvterm table) and I’d like to have it linked (during an update job) to the cvterm ‘cryo-preserved’ instead. It means either removing previous relationship and adding the new one or updating the stock_cvterm.cvterm_id. Those 2 terms belong to the same CV but other terms from that CV might be used for current stock and should not be removed.

@guignonv and @laceysanderson  have additional comments on the Drupal issue queue.  Please refer to that conversation.

**Comment by spficklin** [comment]
@laceysanderson this is assigned to you. If you think this won't happen perhaps we should close this out?

**Comment by laceysanderson** [comment]
I can see the utility for sure but I just don't have the time or personal need to implement this myself *hangs head*. @guignonv this request was made quite a while ago. How are you handling this currently? Have you found an acceptable work around?

**Comment by guignonv** [comment]
Well, I handle it in two ways: for some records, before calling the bulk loader, I use some DELETE queries on the database and then, the bulk loader will reload removed records or add new ones. For some other types of records, for instance stock_cvterm, I keep all the associated records but change the stock_cvterm.is_not flag instead. For instance, I store in the stock_cvterm table the way biological materials are stored: cryo, in_vitro and field. If I had a stock that was stored both in cryo and in vitro and which is now stored in cryo and in field, as I cannot remove the in_vitro cvterm association with the bulk loader, I have 3 columns in my data files, one for each storage type and a value for each wich is 'true' or 'false'. So for the update, I will still have the in_cryo cvterm association but with is_not set to true.

**Comment by laceysanderson** [comment]
I'm going to close this issue as @guignonv has a work around and I simply do not have the time to implement this feature. If you still really need this functionality, please comment and I will reconsider
