### ISSUE TITLE
chado_bundle type_id is empty string, blocks tripal_chado_update_7329

### ISSUE THREAD

**Issue by Ferrisx4** [tripal/tripal#797]
### System information

* Tripal Version: 7.x-3.0
* Drupal Version: 7.61
* PostgreSQL Version: 9.5.7
* PHP Version: 7.0.29

### Issue description

In database table chado_bundle, one row has its `type_id` field set as `''` (empty string).
tripal_chado_update_7329, related issue #371, requires that the field be an integer instead of varchar. 
It may be possible, however unlikely, that other sites have this database condition.

#### Error messages and screenshots

Running `drush updatedb` produces the following error:
```
Could not perform update: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: ""
```
chado_bundle table before attempting update: 
![screen shot 2018-12-17 at 10 44 12 am](https://user-images.githubusercontent.com/9593623/50097851-c45d4c80-01e8-11e9-91b0-c545f17d1a94.png)

**Comment by spficklin** [comment]
Hi @Ferrisx4.  Do you know how the empty string was added to that column?  I suspect it may be a result of some older bit of code. As you all were early adopters of Tripal v3 I think it may be safe to just set that record's type_id to NULL and then perform the update.

**Comment by Ferrisx4** [comment]
Hi @spficklin We discussed this issue as part of our meeting just now and we also think that it is an old condition as you suspect.
Setting that field to NULL is not an option currently as the field is constrained to `not null`. Would changing that constraint temporarily break anything as far as compliance with Tripal table schema definition is concerned?

**Comment by bradfordcondon** [comment]
why not assign it a random cvterm_id not used by anything else and unset it after migrating?

**Comment by spficklin** [comment]
Sorry, @Ferrisx4 I was confused.  You're right that column is required.   Every record in that table must have a type_id.  It maps the type for the content type (bundle) to the actual cvterm in Chado.  In the screenshot you provided above, the bundle ID is 28.  It maps to the contact table.  I suspect that without a type ID you're probably not using that bundle?  Can you look in the ``tripal_bundle`` table and see what content type is 28?  It may be that you aren't using it and can just remove that row from the table.

**Comment by Ferrisx4** [comment]
Ah, @spficklin it looks like content type 28 is a "Tripal Contact Profile" type, which is created by an internal module. We're debugging to see why it was not created with a `type_id`.

**Comment by spficklin** [comment]
If you use the Tripal API functions then that content type should have been created with a type_id.  So, I'm guessing it may have been created in the buggy days of the code?   If you need that conent type then we may have to do some SQL additions to get you past this.

**Comment by risharde** [comment]
Hi guys, the following code was used to create the bundle, this was most likely executed a few months ago to create the bundle:

> 

		$args = array(
			'vocabulary' => 'local',
			'accession' => 'tripal_contact_profile',
			'term_name' => 'Tripal Contact Profile',
			'storage_args' => array(
				'data_table' => 'contact',
			)
		);
		$bundle = tripal_create_bundle($args, $error);

@spficklin Any advice on what SQL additions we may need to get past this? Please let us know, thanks!

**Comment by bradfordcondon** [comment]
do you also have the base contact bundle when that code was run? ie with term `local:contact`?  If so you have two bundles trying to use that base table, with no type differentiating them, could result in the lacking type_id.

Similarly.... what is the contact bundle whose tpe_id is 2820? 
  here is my vanilla contact:

```
chado_bundle_id	bundle_id	data_table	type_linker_table	type_column	type_id	type_value	base_type_id
5	5	contact			2916
```


In your table you have two contact types, neither of which says it has a type_id.  So if you set the type_column column to type_id for both contact bundles (or delete the other one) and b) set the type_id  of your custom contact bundle to the cvterm_id of `local: tripal_contact_profile` i think youll be set.

**Comment by bradfordcondon** [comment]
hi @Ferrisx4 any update on this?  thanks

**Comment by Ferrisx4** [comment]
Hi @bradfordcondon, and thanks. The code that was run on our site has been fixed and no longer puts the database in that condition. Between that and a few manual database fixes, we seem to be in good shape.

I'll close this. 
Thanks again
