### ISSUE TITLE
Questions about upgrade from Tv2 to Tv3

### ISSUE THREAD

**Issue by srobb1** [tripal/tripal#800]
CentOS 7.2.15.11
tripal-7.x-2.1-beta2 --> tripal-7.x-3.0-rc3

We are getting errors pretty early on in our upgrade. We are following the instructions on [tripal.info](https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/upgrade_from_tripal2.html).

When we disable tripal-core we find that we are missing many views. What should we do to repair this?

Thank you,
Sofia

```
[drupal@cuttingclass-test html]$ drush pm-disable tripal_core
The following theme is missing from the file system: <em             [warning]
class="placeholder">tripal</em>. For information about how to fix
this, see <a href="https://www.drupal.org/node/2487215">the
documentation page</a>. bootstrap.inc:1143
The following extensions will be disabled: tripal_core, chado_search, tripal_views, tripal_db, tripal_cv, tripal_analysis, tripal_organism, tripal_feature, tripal_analysis_blast, tripal_bulk_loader, tripal_daemon
Do you really want to continue? (y/n): y
tripal_organism was disabled successfully.                           [ok]
tripal_analysis_blast was disabled successfully.                     [ok]
tripal_bulk_loader was disabled successfully.                        [ok]
tripal_cv was disabled successfully.                                 [ok]
tripal_daemon was disabled successfully.                             [ok]
tripal_db was disabled successfully.                                 [ok]
tripal_core was disabled successfully.                               [ok]
tripal_feature was disabled successfully.                            [ok]
tripal_views was disabled successfully.                              [ok]
tripal_analysis was disabled successfully.                           [ok]
chado_search was disabled successfully.                              [ok]
Unable to find a view by the name of 'tripal_bulk_loading_jobs'.     [error]
Unable to disable this view.
Unable to find a view by the name of 'tripal_bulk_loader_templates'. [error]
Unable to disable this view.
Unable to find a view by the name of 'tripal_feature_user_feature'.  [error]
Unable to disable this view.
Unable to find a view by the name of 'tripal_feature_admin_features'.[error]
Unable to disable this view.
Unable to find a view by the name of                                 [error]
'tripal_organism_user_organisms'. Unable to disable this view.
Unable to find a view by the name of                                 [error]
'tripal_organism_admin_organisms'. Unable to disable this view.
Unable to find a view by the name of 'tripal_analysis_user_analyses'.[error]
Unable to disable this view.
Unable to find a view by the name of                                 [error]
'tripal_analysis_admin_analyses'. Unable to disable this view.
Unable to find a view by the name of 'tripal_cv_admin_cvs'. Unable to[error]
disable this view.
Unable to find a view by the name of 'tripal_cv_admin_cvterms'.      [error]
Unable to disable this view.
Unable to find a view by the name of 'tripal_db_admin_dbs'. Unable to[error]
disable this view.
Unable to find a view by the name of 'tripal_db_admin_dbxrefs'.      [error]
Unable to disable this view.
```

**Comment by bradfordcondon** [comment]
those warnings dont worry me too much: for whatever reason you dont have the views, and we're trying to disable them.  We can see the modules are disabled successfully.  I'd continue with the upgrade process.

As for why you dont have them, that i don't know: they are provided by their respective legacy module.

**Comment by srobb1** [comment]
@bradfordcondon Thanks for your help. I just want to make sure I don't skip over any important errors. 

I have no idea either why I would not have those views.

We have more errors. This is about tables already existing.  Are these serious?

`exception 'DatabaseSchemaObjectExistsException' with message 'Table  [error]`

 Here is what we did:

```
[drupal@cuttingclass-test html]$ rm -rf sites/all/modules/tripal*
[drupal@cuttingclass-test html]$ drush pm-download tripal-7.x-3.0-rc3
[drupal@cuttingclass-test html]$ drush pm-enable tripal
The following projects have unmet dependencies:                      [ok]
tripal requires redirect
Would you like to download them? (y/n): y
Project redirect (7.x-1.0-rc3) downloaded to                         [success]
/var/www/html/sites/all/modules/redirect.
The following extensions will be enabled: tripal, redirect
Do you really want to continue? (y/n): y
exception 'DatabaseSchemaObjectExistsException' with message 'Table  [error]
tripal_jobs already exists.' in
/var/www/html/includes/database/schema.inc:663
Stack trace:
#0 /var/www/html/includes/database/database.inc(2776):
DatabaseSchema->createTable('tripal_jobs', Array)
#1 /var/www/html/includes/common.inc(7118):
db_create_table('tripal_jobs', Array)
#2 /var/www/html/includes/module.inc(479):
drupal_install_schema('tripal')
#3 /usr/share/drush/commands/core/drupal/environment_7.inc(143):
module_enable(Array)
#4 /usr/share/drush/commands/pm/pm.drush.inc(1180):
drush_module_enable(Array)
#5 [internal function]: drush_pm_enable('tripal')
#6 /usr/share/drush/includes/command.inc(422):
call_user_func_array('drush_pm_enable', Array)
#7 /usr/share/drush/includes/command.inc(231):
_drush_invoke_hooks(Array, Array)
#8 [internal function]: drush_command('tripal')
#9 /usr/share/drush/includes/command.inc(199):
call_user_func_array('drush_command', Array)
#10 /usr/share/drush/lib/Drush/Boot/BaseBoot.php(67):
drush_dispatch(Array)
#11 /usr/share/drush/includes/preflight.inc(66):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#12 /usr/share/drush/drush.php(12): drush_main()
#13 {main}
[drupal@cuttingclass-test html]$
```

**Comment by bradfordcondon** [comment]
i dont think it will help with this error, but theres a more recent tripal release v3.0, its up on the drupal release too at https://www.drupal.org/project/tripal/releases/7.x-3.0. 

In answer to your question, yeah, now I'd take pause and lets figure out what the problem is.
Tripal 3 supposedly is smart about this:    It moves the old tripal tables and migrates them, see here:

https://github.com/tripal/tripal/blob/33fa7eac5478ae8dda53da8d8b5a3ad6afac395b/tripal/tripal.install#L95-L145

Considering i've never seen this error before and we aren't encountering it on our tripal 2 -> upgrade CI, there must be something wonky going on here.   My first guess is that there is something preventing the Tripal install from renaming the table?

**Comment by srobb1** [comment]
@bradfordcondon 
Let me walk through this to make sure everything is as it should be.

For me to manually rename a table I need to:
```
sudo su - postgres
psql drupal
alter table tripal_jobs rename to tripal_jobs_sofia;
```
Is all of this as expected? Could there be some sort of permissions errors?

**Comment by srobb1** [comment]
I am trying again. And before I started I checked for all those views that can't be found. They are there. Why would be reported as not being there?

**Comment by srobb1** [comment]
Any idea what version of PHP is being used on CentOS 7 when the system is upgraded from Tv2 to Tv3?

**Comment by bradfordcondon** [comment]
in the test environment its 7.1 .

**Comment by srobb1** [comment]
drush version 8.1.16
php version 7.1.25

Thanks. We upgraded to PHP 7.1. This seems better because any other PHP upgrade broke the functionality of the Tv2 site and with this version of PHP Tv2 site is still working! Yeah!

We still get messages about the missing views and the table tripal_jobs already exists.

We tried to proceed to the prepare chado db step. We get this errors. Does anything pop out?

PHP error log:
```
[19-Dec-2018 14:15:15 America/Chicago] PHP Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'tripal_tripal_cron_notification' not found or invalid function name in /var/www/html/sites/all/modules/tripal/tripal_core/api/tripal_core.jobs.api.inc on line 356 pid 1459
[19-Dec-2018 14:15:15 America/Chicago] PHP Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'tripal_expire_collections' not found or invalid function name in /var/www/html/sites/all/modules/tripal/tripal_core/api/tripal_core.jobs.api.inc on line 356 pid 1459
[19-Dec-2018 14:15:15 America/Chicago] PHP Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'tripal_expire_files' not found or invalid function name in /var/www/html/sites/all/modules/tripal/tripal_core/api/tripal_core.jobs.api.inc on line 356 pid 1459
[19-Dec-2018 14:19:15 America/Chicago] PHP Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'tripal_chado_prepare_chado' not found or invalid function name in /var/www/html/sites/all/modules/tripal/tripal_core/api/tripal_core.jobs.api.inc on line 356 pid 1459

```

Postgres error log:
```
ERROR:  relation "tripal_import" does not exist at character 13
STATEMENT:  INSERT INTO tripal_import (uid, class, submit_date, arguments) VALUES ('34', 'OBOImporter', '1545251155', 'a:2:{s:8:"run_args";a:1:{s:6:"obo_id";s:1:"6";}s:5:"files";a:0:{}}')
```

**Comment by bradfordcondon** [comment]
something is very weird.  `tripal_expire_files`,  `tripal_tripal_cron_notification` these are all functions that are defined by the module `tripal`.  erego, you don't seem to have `tripal `enabled.


can you clarify exactly what upgrade step you are at?  can you verify tripal is enabled ie

```
drush pm-enable tripal
```

looking at it again, it looks like you have tripal_core still enabled (ie tripal 2), `/var/www/html/sites/all/modules/tripal/tripal_core/` despite teh message that you successfully disabled it.  can you try re-disabling tripal-core ?

**Comment by srobb1** [comment]
We are going to try from the beginning again to make double sure that we are disabling and deleting the old modules. We have done this a bunch of times now, maybe we missed something this time.  Ill post something helpful soon, hopefully.

**Comment by srobb1** [comment]
We could not resolve these issues. I am going to start with a fresh install of Tv3 and reload all the data.
