### ISSUE TITLE
sequence ontology term autocomplete includes synonyms which form may not handle

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#801]
noticed in #762 but the issue pertains to all sequence ontology lookups.

Some terms appear in the lookup ('I-box promoter motif') but are not in my sequence ontology.

![screen shot 2018-12-19 at 12 19 22 pm](https://user-images.githubusercontent.com/7063154/50236506-93b41900-0388-11e9-832a-e16e14925660.png)

```
select * from chado.cvterm where name='I-box promoter motif';
drupal=>
```

This affects everything that has a term lookup: for example, the annotation field (ie feature_cvterm) or the relationship field.

**Comment by bradfordcondon** [comment]
```
select * from chado.cvterm where name='I-box';
2366	11	I-box	A plant regulatory promoter motif,  composed of a highly conserved hexamer GATAAG (I-box core). [PMID:2347304, PMID:2902624, SO:ml]	2655	0	0
```

![screen shot 2018-12-19 at 12 24 16 pm](https://user-images.githubusercontent.com/7063154/50236667-04f3cc00-0389-11e9-8fd4-53d683956d34.png)

OK figured it out.  the autocomplete includes SYNONYMS.  There is no I-box promoter motif term, just I-box, with the other term serving as a synonym.


.  so we need to either a) cut synonyms, or b) accommodate synonyms when looking up terms.

**Comment by bradfordcondon** [comment]
im proposing to resolve this by not displaying synonyms in the autocomplete box.  the alternative solution means all fields that use autocomplete need to be aware of this issue, OR `chado_get_cvterm` needs to automatically accommodate synonyms which seems weird to me in other contexts.

`chado_get_cvterm` already accomodates synonyms, but it requires the caller to *know* that they are synonyms, which one doesnt know from the select box.  we would have to check synonyms if `chado_generate_var` fails.

**Comment by bradfordcondon** [comment]
note some forms did react to synonyms: consider the chado fasta importer:


```php

 // check to make sure the types exists
    $cvtermsql ="
      SELECT CVT.cvterm_id
      FROM {cvterm} CVT
        INNER JOIN {cv} CV on CVT.cv_id = CV.cv_id
        LEFT JOIN {cvtermsynonym} CVTS on CVTS.cvterm_id = CVT.cvterm_id
      WHERE cv.name = :cvname and (CVT.name = :name or CVTS.synonym = :synonym)
    ";
    $cvterm = chado_query($cvtermsql,
      array(':cvname' => 'sequence',':name' => $type,':synonym' => $type))->fetchObject();
    if (!$cvterm) {
      form_set_error('type', t("The Sequence Ontology (SO) term selected for the sequence type is not available in the database. Please check spelling or select another."));
    }
    if ($rel_type) {
      $cvterm = chado_query($cvtermsql, array(':cvname' => 'sequence',':name' => $parent_type,
        ':synonym' => $parent_type
      ))->fetchObject();
      if (!$cvterm) {
        form_set_error('parent_type', t("The Sequence Ontology (SO) term selected for the parent relationship is not available in the database. Please check spelling or select another."));
      }
```

this change wont break this (although this code is now irrelevant and the check could be removed).

**Comment by bradfordcondon** [comment]
from @spficklin 

>You can use the function `tripal_get_term_lookup_form` to add a CVTerm autocomplete lookup element to your form.  Then you can use the `tripal_get_term_lookup_form_result` function in your validate/submit hooks to get the term selected.

so i think the thing to do is look where autocomplete is used and use these functions instead and see if that resolves the problem.  We will have the issue that the term the user inputs is not the term that ends up being used, but that might be ok.

**Comment by spficklin** [comment]
> so i think the thing to do is look where autocomplete is used and use these functions instead and see if that resolves the problem.

It was my intention to do that and I thought I had.  I guess I forgot some.

**Comment by bradfordcondon** [comment]
`tripal_get_term_lookup_form` will not work as is:
 
I am pretty sure this is because **fields with cardinality dont support fieldsets**.

You can confirm this for yourself by adding the below code to the `form` function of any widget.


```php
    $widget['A'] = [
        '#type' => 'fieldset',
        '#title' => 'I appear on cardinality = 1 fields only',
        '#collapsible' => FALSE,
        '#collapsed' => FALSE,
        '#description' => $element['#description'],
      ];

      $widget['B'] = [
        '#type' => 'textfield',
        '#title' => t('no card text'),
        '#default_value' => 'no cardinality text',
      ];
      return;
```


The fieldset and text field will appear on a field with cardinality = 1 (in my experiment i used `taxrank__infraspecific_taxon_widget`).

For a field with unlimited cardinality such as the fields we are working with here (`sio__annotation_widget`), **only the text field will render**.  The **fieldset will not render**.  I would think this has something to do with unlimited cardinaity fields having their own fieldset/formatting:

<img width="1138" alt="screen shot 2019-01-08 at 11 23 25 am" src="https://user-images.githubusercontent.com/7063154/50844004-d9388600-1337-11e9-98b0-fb916669f3a5.png">


So in order to use that function, we have ot make fieldsets optional, or, figure out why fieldsets dont work on fields with multiple cardinality.

**Comment by spficklin** [comment]
@bradfordcondon can you confirm you mean "fieldsets" in your description above?  As in Drupal form fieldsets?

**Comment by bradfordcondon** [comment]
hi @spficklin yes Drupal form fieldsets.  I cannot add fieldsets to widgets with cardinality > 1

**Comment by bradfordcondon** [comment]
pinging this issue.  Our status is:

* we want term lookups to use synonyms.  (that's the easiest solution: remove synonyms from autofill.  we ruled it out because we want synonym support).
* therefore we encourage use of `tripal_get_term_lookup_form` for cvterm lookup in fields, since it will handle synonyms.
* However, `tripal_get_term_lookup_form` will not work in fields with cardinality `!=` 1, because it utilizes fieldsets which break in such fields.

**Comment by laceysanderson** [comment]
This is non-trivial to fix because of Drupal 7. As such, I'm marking this as something to be addressed in Tripal 4 as it will hopefully be easier in Drupal 8/9.
