### ISSUE TITLE
Rapid install and tripal git repo

### ISSUE THREAD

**Issue by srobb1** [tripal/tripal#803]
Hello,

Are there any suggestions on how to replace the tripal directory created with the rapid install with the tripal git repository? We tried disabling tripal, deleting the directory and cloning the repo. When trying to enable tripal again we get errors that tripal is already enabled. But it isn’t and the site is not functioning.

Thanks,
Sofia

**Comment by laceysanderson** [comment]
In the past I have put the site in maintenance mode, left tripal enabled, deleted the directory and replaced it with the git clone. That said, I'm surprised your method (which is the correct way to replace modules) didn't work...

**Comment by spficklin** [comment]
A cache clear may be needed as well.

**Comment by bradfordcondon** [comment]
> When trying to enable tripal again we get errors that tripal is already enabled.

is this related to your other issue?

disable and uninstall the module and delete the directory. clear the cache as stephen suggests.  You get warnings at this step?

**Comment by srobb1** [comment]
@bradfordcondon Not related to my other issues. This is a 100% new install on a new VM.

When I try to disable it I get this:
```
drush pm-disable tripal
tripal is a required module and can't be disabled. Reason: Field type(s) in use - see Field list.                                       [ok]
The following extensions will be disabled: tripal_chado_views, tripal_chado, tripal_ds, tripal_ws
Do you really want to continue? (y/n):
```

**Comment by srobb1** [comment]
I got it!!

I Did Not disable, I Did Not uninstall. I just deleted the tripal dir and cloned the repo and cleared the cache. Your way @laceysanderson works great!!

Thanks everyone!

**Comment by spficklin** [comment]
Glad you got it!
