### ISSUE TITLE
Fields disappearing even when not empty

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#805]
### System information

* Tripal Version: 3.x
* Drupal Version: 7.x
* PostgreSQL Version: N/A
* PHP Version: N/A

### Issue description

When hiding of empty fields for a content type is turned on, then fields that are marked to not auto attach (meaning they should be loaded via AJAX) are automatically removed from the Tripal Pane table.  This is because they are technically "empty" as data has not yet been added to them (it gets added via AJAX).  This is incorrect behavior.  They should not be removed from the table until after their data is loaded.  The `tripal_field_group_table_rows_alter` function is the culprit.

**Comment by bradfordcondon** [comment]
#806 was merged so closing this as resolved.
