### ISSUE TITLE
JS function calls after AJAX loading of fields

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#807]
## Feature Request/Discussion

* This feature doesattempt to solve an existing problem with Tripal
* I am open to developing or collaborating on an extension module if this is not a good fit for Tripal Core

* This feature is Not Urgent

### Description

When fields load via AJAX (i.e. they are not attached by default to the entity) any content that they provide does not get run through the Drupal.Behaviors infrastructure.  This means that any Javascript/JQuery that normally would get attached to elements in the document don't get attached to returned content.    This is only a problem the first time a page is loaded.  Any subsequent loading of the page uses the field cache so the fields are not loaded via AJAX.   So, on subsequent views of a page all JS in the Drupal.Behaviors should work just fine.  

We need some way for the Drupal.Behaviors code to be called the first time a page is loaded.  One approach is to follow what Drupal does with the `ajax_command_invoke` command which is meant to be used in the `hook_ajax_render_alter` function.   It's not clear to me if we can use that approach or if we need to do something similar.   The AJAX calls for loading fields happen from custom JQuery code in the tripal.js file.

### Your Specific Use Case

Example where this is a problem is with the Tripal Analysis Blast and Tripal Analysis Interpro modules.  Both of those modules provide a feature viewer for looking at alignments of matches.  Creation of those viewers happens in a Drupal.Behaviors stanza.   Well, actually.... they are being adjusted to be that way.  See https://github.com/tripal/tripal_analysis_blast/issues/8

### Generally Applicable

I think anyone who has JavaScript interacting with their field contents will need their AJAX to run both after AJAX loading of field content and on normal page loading when fields are coming from cache.

**Comment by laceysanderson** [comment]
This is a big deal for many of the modules used on KnowPulse. Any thoughts towards a solution?

I'm also labeling this as a bug since it causes behaviour contrary to what is expected. I expect that if my field attaches Javascript the Drupal Way (using behaviours) that it should work with Tripal Fields and currently it doesn't on the first page load.
