### ISSUE TITLE
TODO: move functional docs out to extension modules

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#810]
We have the docuemnts for the tripal blast, interpro and kegg modules inside of the Tripal's User's Guide.  I think we can easily move them over to RTD setups for those modules on their own and then just link to them.  As long as we make sure they continue to use the same example data I don't see a problem with this and it ensures that no extension module docs are in the the core documentation.

What say ye?

**Comment by laceysanderson** [comment]
**My Vote: yes, move it out to each extension module and link to it in the Tripal RTD.**

I like the idea of moving it out since it gives each extension module more presence, better accessible documentation and makes it easier to update the documentation with each code update to the module.

**Comment by bradfordcondon** [comment]
sure.  we do lose searchability is the only drawback i can think of, but im still in favor of moving.

**Comment by spficklin** [comment]
Sounds good! I'll add it to the 3.2 release milestones.

**Comment by bradfordcondon** [comment]
unanimous support so im removing the voting tag.

**Comment by laceysanderson** [comment]
I'm tagging this as a good first issue. If you have reached this issue based on that tag, the task which needs to be done is:

- The docs under https://tripal.readthedocs.io/en/latest/user_guide/example_genomics/func_annots.html are for extension modules not included in this repository.
- Create a PR on each extension module containing the docs page from this repository and adding it to the docs for that module.
- If the extension module does not yet have a readthedocs, create an issue containing the documentation on the extension module repository.
- Finally, create a PR removing this documentation from Tripal Core

**Comment by avats-dev** [comment]
Can I work on this? Also, can anyone elaborate a bit how to resolve this? Thanks

**Comment by swapniljha001** [comment]
Is this issue still unresolved?

**Comment by spficklin** [comment]
@avats-dev and @swapniljha001. It looks like both of you may be new here.  Do either of you currently develop a Tripal site or work on extension modules for Tripal? If so, we would love your help on this issue. The challenge with this one is knowing exactly what documentation to move, where to move it, what our documentation standards are and how to adjust the documentation to make sense for the community of users.

**Comment by laceysanderson** [comment]
This is no longer an issue in the Tripal 4 docs which have moved to https://github.com/tripal/tripal_doc
