### ISSUE TITLE
Tried to import GO get type_id violates not-null constraint for goslim_agr

### ISSUE THREAD

**Issue by srobb1** [tripal/tripal#812]
I have a brand spanking new tripal3 install with the rapid installer. I replaced the tripal module dir with the github repo today.

The very first thing I have tried is to import GO. I am getting an error. Should I have done something else before this. What did I miss???

Is this critical? Or something I can ignore?

Thanks,
Sofia

```
Running 'OBO Vocabulary Loader' importer
NOTE: Loading of file is performed using a database transaction.
If it fails or is terminated prematurely then all insertions and
updates are rolled back and will not be found in the database

[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] chado_select_record: the foreign key definition for 'dbxref_id' on table 'cvterm' returned no results where the definition supplied was Array(    [db_id] => Array        (            [name] => NCIT        )    [accession] => C25693)
[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] chado_select_record: the foreign key definition for 'dbxref_id' on table 'cvterm' returned no results where the definition supplied was Array(    [db_id] => Array        (            [name] => rdfs        )    [accession] => comment)
Downloading URL http://purl.obolibrary.org/obo/go.obo, saving to /tmp/obo_dgoYXf
Step 1: Preloading File /tmp/obo_dgoYXf...
Found the following namespaces: gene_ontology, biological_process, molecular_function, cellular_component, external.
Step 2: Examining relationships...
Step 3: Loading type defs...: 344,098,144  bytes.
Step 4: Loading terms... %. Memory: 344,102,064 bytes.
Cannot add subset, "goslim_agr" to term: GO:0000003. ERROR: ChadoRecord::insert(). Could not insert a record into the table, cvtermprop, with the following values: Array
(
    [cvterm_id] => 2982
    [type_id] =>
    [value] => goslim_agr
)
. ERROR: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "type_id" violates not-null constraint
DETAIL:  Failing row contains (569, 2982, null, goslim_agr, 0)..
[site http://default] [TRIPAL ERROR] [TRIPAL_JOB] Cannot add subset, "goslim_agr" to term: GO:0000003. ERROR: ChadoRecord::insert(). Could not insert a record into the table, cvtermprop, with the following values: Array(    [cvterm_id] => 2982    [type_id] =>     [value] => goslim_agr). ERROR: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "type_id" violates not-null constraintDETAIL:  Failing row contains (569, 2982, null, goslim_agr, 0)..
```

**Comment by bradfordcondon** [comment]
Hello,

Looks like some of the property terms werent defined.  In this case its `addSubset` so should be term `NCIT:C25693`.  This term is inserted on tripal_chado install which makes me nervous.

Can you try running `drush updatedb`?  and/or are the re any jobs in the tripal jobs queue that havent run?

edit- to answer your question, the error itself isnt particularly critical (although it suggests you have a bigger problem), unless the error rolled back loading the gene ontology.

 i suppose i should also ask first: did you have any errors/warnings when setting up the rapid install site?  can you share the console log?

**Comment by srobb1** [comment]
I don't have a log of the console. Is there a log file generated. But I do not remember any errors. I think the GO job completed with the error and It did not roll back.

There are quite a few updates needed:
```
 Tripal_chado  7328  Don't count relationship cvterms as ontology roots.
 Tripal_chado  7329  Fixing the chado_bundle.type_id type.
 Tripal_chado  7330  Associates categories with content types.
 Tripal_chado  7331  Adds a base_type_id to the chado_bundle table.
 Tripal_chado  7332  Adds additional vocabs for the OBO Importer.
 Tripal_chado  7333  Renames the TContact vocabulary database entry to TCONTACT as it should be.
 Tripal_chado  7334  SQL Fix for the db2cv_mview materialized view.
 Tripal_chado  7335  SQL Fix for the cv_root_mview materialized view.
 Tripal_chado  7336  Use correct contact field when linked via linker table.
 Tripal_chado  7337  Update the NCBITaxon DB entry.
 Tripal        7313  Adds a tripal_storage_api setting to all field storage details
```
Perhaps one of these will help with my GO upload.

Ah, now the load is working. So I should up done the updatedb. That is what I missed.

Thank you @bradfordcondon

**Comment by bradfordcondon** [comment]
great.  the rapid install uses discrete releases and i believe its still set to rc3, meaning its quite a bit behind the current master (and we did a 3.0 release after rc3).

So any time you upgrade core its smart to try `drush updatedb`. 

closing.

**Comment by spficklin** [comment]
Just FYI... I have updated the rapid installer to use Drupal 7.61 and Tripal 7.x-3.0.  It still needs testing to make sure there's no unaccounted for side-effects.   Sorry about that @srobb1

**Comment by srobb1** [comment]
@spficklin I can redo my build with the new rapid installer. I will let you know if I see any issues.

Thanks!
Sofia
