### ISSUE TITLE
Unable to create cvterm-based content type

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#813]
### System information

* Tripal Version: 7.x-3.x (668b07ce27c26f0481fa8887005608a9b2fcc67b)
* Drupal Version: 7.61

### Issue description
I get a WSOD when I trying to create a content type where the base table is cvterm. This seems to be caused by a missing function to generate the options for a cvterm content type.

#### Steps to reproduce
1. Go to Admin > Structure > Tripal Content Types > Add Tripal Content Type
2. Choose a term, storage method is chado
3. Select 'cvterm' as the base table and click continue.

#### Error messages and screenshots

```
PHP Fatal error:  Call to undefined function tripal_chado_field_storage_bundle_mapping_form_add_cvterm() in /var/www/sites/all/modules/tripal/tripal_chado/includes/tripal_chado.field_storage.inc on line 1218
```

**Comment by bradfordcondon** [comment]
https://github.com/tripal/tripal/blob/668b07ce27c26f0481fa8887005608a9b2fcc67b/tripal_chado/includes/tripal_chado.field_storage.inc#L1211-L1228

i searched for similar function names, im guessing it was stubbed and never defined?

**Comment by laceysanderson** [comment]
It was defined a long time ago. I had to go back to before 7.x-3.0 to find it.
I started work on branch 813-cvterm_entitytype

**Comment by laceysanderson** [comment]
@spficklin I seem to be missing something... 

I can now fully submit the create content type form for a cvterm-based type. However, when running the job, I get:
```
2019-01-03 06:38:21: Calling: tripal_create_bundle(Array)
WD tripal_entities: Failed to create content type: Cannot create content type. Missing the "data_table" for this bundle..                                                                        [error]
ERROR (TRIPAL_ENTITIES): Failed to create content type: Cannot create content type. Missing the "data_table" for this bundle..
[site http://default] [TRIPAL ERROR] [TRIPAL_ENTITIES] Failed to create content type: Cannot create content type. Missing the "data_table" for this bundle..
Failed to create content type: <em class="placeholder">Cannot create content type. Missing the &quot;data_table&quot; for this bundle.</em>.
[site http://default] [TRIPAL ERROR] [TRIPAL_JOB] Failed to create content type: Cannot create content type. Missing the "data_table" for this bundle..
Failed to create content type: Cannot create content type. Missing the "data_table" for this bundle..  
```

I set the data table here: https://github.com/tripal/tripal/blob/813-cvterm_entitytype/tripal_chado/includes/tripal_chado.field_storage.inc#L1897-L1899

PS. The full changes so far are here: https://github.com/tripal/tripal/compare/813-cvterm_entitytype

**Comment by laceysanderson** [comment]
Got it! PR to follow

**Comment by spficklin** [comment]
@laceysanderson I'm not sure who this got lost, but I'm glad you brought it back. I think the PR fixes this so I'm closing.
