### ISSUE TITLE
Conflict between Drupal table names and CHADO ones

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#82]
Copied from the Drupal issue queue:  https://www.drupal.org/node/2415131

Please see the Drupal issue queue for the in depth discussion by @guignonv  and @laceysanderson about this issue.  Subsequence comments/responses should be made here rather than the Drupal issue queue.

**Comment by laceysanderson** [comment]
I have been unable to reproduce this issue. @guignonv if you are still experiencing this issue, please let us know!

**Comment by spficklin** [comment]
Marking this as closed. Please re-open if issue persists.
