### ISSUE TITLE
Tripal DS should trigger a window resize event after showing a pane

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#824]
### System information

* Tripal Version: 3
* Drupal Version: 7.6
* PostgreSQL Version: 9.6
* PHP Version: 7.1

### Issue description

Tripal DS uses jquery animations to show/hide Tripal panes. Many modules, including tripal_analysis_interpro and tripal_analysis_blast, draw charts that show up after the page has loaded. Since they are in a hidden container, the width/height of the container is 0 by default. This is messing up how modules compute the dimensions of the chart and causing them to display blank results. See screenshot below.

#### Steps to reproduce

see issue https://github.com/tripal/tripal_analysis_interpro/issues/24 for more details on reproducing.

#### Error messages and screenshots

![issue](https://user-images.githubusercontent.com/17642511/51313489-f8c56200-1a4d-11e9-82a2-c4021a7fe1cb.png)

### Solution 

By triggering a resize event on the `window` object after the animation has completed, we can simulate the default behavior of the browser. See below for a working example:

```js
           if (typeof Event !== 'undefined') {
               window.dispatchEvent(new Event('resize'));
           }
           else {
               // Support IE
               var event = window.document.createEvent('UIEvents');
               event.initUIEvent('resize', true, false, window, 0);
               window.dispatchEvent(event);
           }
```

By adding this code right after this line, the issue would be fixed.
https://github.com/tripal/tripal/blob/3244f2dc184513d1c4576fb29b2d72e6f61d4413/tripal_ds/theme/js/tripal_ds.js#L65

Thanks!

**Comment by bradfordcondon** [comment]
merged. thanks for the fix.

**Comment by bradfordcondon** [comment]
I'm reopening this issue: it appears this fix isn't effective for safari or firefox

**Comment by almasaeed2010** [comment]
My opinion is that since manually resizing the window on Safari /FF doesn't fix, then this is a library issue not a Tripal issue. The library may have implemented the event listeners to support only Chrome.

**Comment by almasaeed2010** [comment]
If you want to verify it is not a Tripal issue, simply add a `console.log()` and make sure it fires when you click on the pane link.

```js
$(window).on('resize', function(e) { console.log('it fired!') })
```

**Comment by bradfordcondon** [comment]
updating our featureviewer library to 1.0.4 resolved the problem.  abdullah is correct its a library issue not a Tripal issue.
