### ISSUE TITLE
During upgrade tripal_cv_obo index already exists on Tripal Chado install

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#84]
Following the upgrade instructions in the Tripal 3.x README, I get the following error when I enable Tripal Chado in Step 5:

````
drush pm-enable tripal_chado
The following projects have unmet dependencies:                                                                                                                   [ok]
tripal_chado requires date
Would you like to download them? (y/n): y
Project date (7.x-2.9) downloaded to /var/www/dev/trp-upgrade/sites/all/modules/date.                                                                             [success]
Project date contains 11 modules: date_context, date_repeat_field, date_tools, date_all_day, date_repeat, date_migrate_example, date_migrate, date_popup, date_views, date_api, date.
The following extensions will be enabled: tripal_chado, tripal_chado_views, date_api, date
Do you really want to continue? (y/n): y
WD php: PDOException: SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "tripal_cv_obo_tripal_cv_obo_idx1_idx" already exists: CREATE INDEX                    [error]
"tripal_cv_obo_tripal_cv_obo_idx1_idx" ON {tripal_cv_obo} ("obo_id"); Array
(
)
 in db_create_table() (line 2776 of /var/www/dev/trp-upgrade/includes/database/database.inc).
Cannot modify header information - headers already sent by (output started at /usr/share/php/drush/includes/output.inc:37) bootstrap.inc:1481                     [warning]
PDOException: SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "tripal_cv_obo_tripal_cv_obo_idx1_idx" already exists: CREATE INDEX "tripal_cv_obo_tripal_cv_obo_idx1_idx" ON {tripal_cv_obo} ("obo_id"); Array
(
)
 in db_create_table() (line 2776 of /var/www/dev/trp-upgrade/includes/database/database.inc).
Drush command terminated abnormally due to an unrecoverable error.
````

This causes a PDO Exception at the end of the upgrade process that renders the site completely unusable:

````
tripal_chado: PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "chado_cvterm_mapping" does not exist                                         [error]
LINE 3: chado_cvterm_mapping tcm
        ^: SELECT tcm.mapping_id AS mapping_id
FROM 
{chado_cvterm_mapping} tcm
WHERE  (cvterm_id = :db_condition_placeholder_0) ; Array
(
    [:db_condition_placeholder_0] => 414
)
 in tripal_chado_add_cvterm_mapping() (line 105 of /var/www/dev/trp-upgrade/sites/all/modules/tripal/tripal_chado/includes/tripal_chado.mapping.inc).
````

**Comment by laceysanderson** [comment]
I was able to get around this issue by dropping the index `tripal_cv_obo_tripal_cv_obo_idx1_idx` after Tripal 2 was disabled but before enabling Tripal 3.

`DROP INDEX tripal_cv_obo_tripal_cv_obo_idx1_idx;`

**Comment by shawnawsu** [comment]
It looks like lines 273-298 && 369-380 from the tripal_chado.install file are commented out but they contain updates which would stop this error. I didn't comment these out, so I'd like to check with @spficklin as I assume they were commented out for a reason. On my local once those lines are included the error goes away.

These are the lines that are commented out:
`
if (db_table_exists('tripal_cv_defaults')) {
    // Move the tripal_cv_defaults table out of the way.
    $sql = "ALTER TABLE tripal_cv_defaults RENAME TO tripal_cv_defaults2";
    db_query($sql);
    if (db_query("SELECT 1 FROM pg_indexes WHERE indexname = 'tripal_cv_defaults_pkey'")->fetchField()) {
      $sql = "ALTER INDEX tripal_cv_defaults_pkey RENAME TO tripal_cv_defaults_pkey2";
    }
    else {
      $sql = "CREATE UNIQUE INDEX tripal_cv_defaults_pkey2 ON tripal_cv_defaults2 USING btree (cv_default_id)";
    }
    db_query($sql);
    if (db_query("SELECT 1 FROM pg_indexes WHERE indexname = 'tripal_cv_defaults_tripal_cv_defaults_idx1_idx'")->fetchField()) {
      $sql = "ALTER INDEX tripal_cv_defaults_tripal_cv_defaults_idx1_idx RENAME TO tripal_cv_defaults_tripal_cv_defaults_idx1_idx2";
    }
    else {
      $sql = "CREATE INDEX tripal_cv_defaults_tripal_cv_defaults_idx1_idx2 ON tripal_cv_defaults2 USING btree (table_name, field_name)";
    }
    db_query($sql);
    if (db_query("SELECT 1 FROM pg_indexes WHERE indexname = 'tripal_cv_defaults_tripal_cv_defaults_unq1_key'")->fetchField()) {
      $sql = "ALTER INDEX tripal_cv_defaults_tripal_cv_defaults_unq1_key RENAME TO tripal_cv_defaults_tripal_cv_defaults_unq1_key2";
    }
    else {
      $sql = "CREATE UNIQUE INDEX tripal_cv_defaults_tripal_cv_defaults_unq1_key2 ON tripal_cv_defaults2 USING btree (table_name, field_name, cv_id)";
    }
    db_query($sql);
  }
  // tripal_cv_defaults
  if (db_table_exists('tripal_cv_defaults2')) {
     $sql = "DROP TABLE tripal_cv_defaults";
    db_query($sql);
    $sql = "ALTER TABLE tripal_cv_defaults2 RENAME to tripal_cv_defaults";
    db_query($sql);
    $sql = "ALTER INDEX tripal_cv_defaults_pkey2 RENAME TO tripal_cv_defaults_pkey";
    db_query($sql);
    $sql = "ALTER INDEX tripal_cv_defaults_tripal_cv_defaults_idx1_idx2 RENAME TO tripal_cv_defaults_tripal_cv_defaults_idx1_idx";
    db_query($sql);
    $sql = "ALTER INDEX tripal_cv_defaults_tripal_cv_defaults_unq1_key2 RENAME TO tripal_cv_defaults_tripal_cv_defaults_unq1_key";
    db_query($sql);
  }
`

**Comment by laceysanderson** [comment]
Awesome --Good catch! We'll wait till Stephen weighs in :-)

**Comment by spficklin** [comment]
What version of Tripal v3 are you using?  Is it the most recent beta version or the most recent development head?

**Comment by laceysanderson** [comment]
Most recent development head (See label tripal-7.x-3.x rather then tripal-7.x-3.0-beta3 :-) )

**Comment by spficklin** [comment]
Looks like there's a different index name for the tripal_cv_obo table.  I've committed a fix that will hopefully fix this problem.  Let me know.

**Comment by laceysanderson** [comment]
As of last commit, it's now fixed.
