### ISSUE TITLE
The Drush launcher could not find a Drupal site to operate on

### ISSUE THREAD

**Issue by HadarAmira** [tripal/tripal#841]
Hi,
I am new at Tripal and so far just installed Tripal (http://tripal.info/tutorials/v3.x/installation) under Linux Mint 19.1 Cinnamon 4.0.8 and Bootstrap 3.

I have tried to install BLAST function into a Tripal  site using this command: https://media.readthedocs.org/pdf/tripal-blast-ui/latest/tripal-blast-ui.pdf

I got to the 1.2.3 Install Tripal BLAST stage which says to do the next step: 
cd /var/www/html
drush pm-download tripal_blast libraries
but, when I try to do the first line i get this message:
The Drush launcher could not find a Drupal site to operate on. Please do *one* of the following:
  - Navigate to any where within your Drupal project and try again.
  - Add --root=/path/to/drupal so Drush knows where your site is located.

when I search for drush in any directories of Tripal/Drupal etc. i don't find it.
can someone help me please?

**Comment by bradfordcondon** [comment]
Do you know the exact path of where you installed your drupal website?  The "default" location is `/var/www/html`: this command

```
cd /var/www/html
   wget http://ftp.drupal.org/files/projects/drupal-7.59.tar.gz
```

see the software installation section of http://tripal.info/tutorials/v3.x/installation/drupal if you did the step-by-step install.

Is your install location different from `/var/www/html` ?

**Comment by HadarAmira** [comment]
Thank you for your rapid answer! :)

No. I didn't change anything during the installation or after...
When I am inside the /var/www/html I can see the tripal_install, drupal-7.61, moduls, sites atc. directories

**Comment by almasaeed2010** [comment]
Hi @HadarAmira 

Are you able to visit your site using the browser?

**Comment by HadarAmira** [comment]
Yes :)

**Comment by almasaeed2010** [comment]
Can you try going to `/var/www/html/sites/all/modules` and run `drush pm-download tripal_blast libraries`?

**Comment by HadarAmira** [comment]
Got that message again... 
The Drush launcher could not find a Drupal site to operate on. Please do *one* of the following:
  - Navigate to any where within your Drupal project and try again.
  - Add --root=/path/to/drupal so Drush knows where your site is located.

**Comment by almasaeed2010** [comment]
Hmmm that's odd

Can you run `drush --version`?

**Comment by HadarAmira** [comment]
Now it says the following:

Drush Launcher Version: 0.6.0
The Drush launcher could not find a Drupal site to operate on. Please do *one* of the following:
  - Navigate to any where within your Drupal project and try again.
  - Add --root=/path/to/drupal so Drush knows where your site is located.


whenever I write "drush" I get that message...

**Comment by HadarAmira** [comment]
whenever I write "drush" I get that message...

**Comment by almasaeed2010** [comment]
Ok I am not sure what `Drush Launcher` is. Mine simply says: 
```bash
~ drush --version
 Drush Version   :  8.1.17
```
 How did you install `drush`? Did u follow a certain guide?

**Comment by bradfordcondon** [comment]
drush launcher is a composer based package.  but Drupal 7 doesnt really support composer for the drupal site itself.
Note: drush launcher is **not the same** as drush.  It's a wrapper thats really intended to work with Drupal 8 +.

Other users have reported this issue with a Drupal 7 site:
https://github.com/drush-ops/drush-launcher/issues/45

you could try the fixes there, but we wont be able to help you since we dont use drush-launcher, or drupal 8 yet.

i'd recommend instead installing drush 8 and following the guide there:  https://docs.drush.org/en/8.x/install/

**Comment by bradfordcondon** [comment]
in addition, we've moved the guides over to https://tripal.readthedocs.io/en/latest/user_guide/install_tripal.html . So you might want to follow the documentation there in the future.

**Comment by HadarAmira** [comment]
I installed drush according Drupal guide: https://www.drupal.org/node/1248790 .
I will try to install drush 7 and the fixes there @bradfordcondon 

Thank you both!
have a great weekend :)

**Comment by bradfordcondon** [comment]
that guide works too, **if** you specified drush v7:  `composer global require drush/drush:7.*`

**Comment by almasaeed2010** [comment]
I recommend `Drush 8` (not 9) since it's better maintained and supports Drupal 7.

**Comment by HadarAmira** [comment]
![screenshot from 2019-01-31 16-28-25](https://user-images.githubusercontent.com/33876267/52060706-71134380-2575-11e9-8842-403ea6e0174c.png)

That is what I got when I tried to update the drush version...

**Comment by almasaeed2010** [comment]
Try running the following line by line

```bash
wget https://github.com/drush-ops/drush/releases/download/8.1.18/drush.phar
chmod +x drush.phar && mv drush.phar /usr/local/bin/drush
```

This will update your current drush

**Comment by HadarAmira** [comment]
I wrote the first line and waited until it finished, than I wrote the second line and got that message: 
mv: cannot move 'drush.phar' to '/usr/loca/bin/drush': No such file or directory
@almasaeed2010

**Comment by almasaeed2010** [comment]
There was a typo in the command. I corrected it above. 

Instead of “loca” it should be “local”

**Comment by HadarAmira** [comment]
I have the same message :(

**Comment by almasaeed2010** [comment]
Can you run

which drush

And post the output please?

**Comment by HadarAmira** [comment]
I just removed my VM. I'm trying to start over ...
Thank you!

**Comment by almasaeed2010** [comment]
A quick follow up @HadarAmira. Have you managed to get `drush` to work with your new VM?

Thanks!

**Comment by bradfordcondon** [comment]
Hi @HadarAmira please comment if you need this thread reopened, im assuming its been resolved.
