### ISSUE TITLE
old drupal guide is still up

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#842]
we changed the links on tripal.info to the updated guides, but the pages are still there.    A user was using the old guide, probably landed there via google.

We need to disable, delete, or permission those pages.

**Comment by bradfordcondon** [comment]
see #841 , users are finding the old docs page.

**Comment by laceysanderson** [comment]
Old guide has been unpublished 🤞

**Comment by bradfordcondon** [comment]
if you were using the old guide please find hte new guide at https://tripal.readthedocs.io/en/latest/

(@hadiramira)
