### ISSUE TITLE
publish/unpublish orphaned for ALL bundles

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#851]
## Feature Request/Discussion
If you want to publish or unpublish orphaned content, you have to do it bundle by bundle.

This is annoying for me as I frequently drop all content from my dev site and need to unpublished orphans bundle by bundle (its easier to just rebuild the website from scratch but then I have to do stuff like reload OBOs...).  

I imagine some sites would like to be able to publish all bundle types, though.

I'm talking about the publish/unpublish content links here:

![screen shot 2019-02-12 at 3 38 47 pm](https://user-images.githubusercontent.com/7063154/52666554-9d678200-2edc-11e9-96a5-117694b87da0.png)

**Comment by almasaeed2010** [comment]
Hi!

We decided to limit by bundle for performance related issues. On our live site, it took over 15 minutes to figure out what content has been orphaned when we didn’t limit by bundle. This obviously would be very frustrating for many site maintainers. If you’d like we can add an extra option to select all bundles but we should also warn of how slow the process can be for large sites.

**Comment by spficklin** [comment]
Perhaps we could just add a button that says 'Drop all orphans' so that a user can bypass the summary.

**Comment by laceysanderson** [comment]
@bradfordcondon a PR has been submitted by @par12005 for this functionality. If you have time, it would be great you get your review on it

**Comment by laceysanderson** [comment]
PR Merged
