### ISSUE TITLE
Incorrect behaviour for empty fields

### ISSUE THREAD

**Issue by mboudet** [tripal/tripal#854]
### System information
System info:
Tripal: 7.x-3.0
Drupal : 7.59
Postgres: 9.5.8
Php: 7.1.23

### Issue description

Hello,

Currently, there is an issue for several fields (at least two), where they do not display properly when empty.

![image](https://user-images.githubusercontent.com/17642511/52962778-71497680-339e-11e9-80ce-0d0114bc0345.png)

Based on the code, both fields should display a message such as 'No *** is available', however they are currently empty or malformed.

The issue comes from the default value set in these fields : 
`$entity->{$field_name}['und'][0]['value'] = ''` or `$entity->{$field_name}['und'][0]['value'] = array()`, so it goes into the for each loop even though it is technically empty.

**Comment by bradfordcondon** [comment]
There is the option to hide or display empty fields in the bundle settings (see checkbox at bottom of one of my bundle settings pages).

![screen shot 2019-02-18 at 1 01 16 pm](https://user-images.githubusercontent.com/7063154/52969144-574b6c00-337d-11e9-9c5d-d7feb794e5f4.png)

So what i think we really want is a) fields dont display if empty and box is checked, and b) if show empty fields isnt checked, each field comes with an "empty text message". 

The relationships field does this for the formatter:

```php
  public static $default_settings = array(
    'title' => 'Relationship',
    'empty' => 'There are no relationships',
  );
```
So maybe what we need to do is have formatters default to a  "there are no $field_display s", wit hteh option to pass a custom message via the `empty` key in the field display settings.  That way we can ensure uniform behavior.

I'm going to admit when i develop fields im never sure what the "right" thing to do is.  Often I unset the field from the entity in the field's load.

**Comment by mboudet** [comment]
I'm all for having an 'official' stance on fields behaviour when empty. 
>So what i think we really want is a) fields dont display if empty and box is checked, and b) if show empty fields isnt checked, each field comes with an "empty text message".

Yes I think that would be for the best, since hiding/showing empty field are both valid display choices by the admin, both should be supported fully.

**Comment by bradfordcondon** [comment]
I don't think we need a vote but would like to hear any other @tripal/project-managent-commitee-pmc input

**Comment by bradfordcondon** [comment]
merged but im leaving this issue open until we verify that 
* all fields included behave as we want
* documentation specifies expected behavior
