### ISSUE TITLE
Warnings about sbo__relationship during initialisation

### ISSUE THREAD

**Issue by mboudet** [tripal/tripal#857]
### System information

System info:
Tripal: 7.x-3.0
Drupal : 7.59
Postgres: 9.5.8
Php: 7.1.23

### Issue description
During boot, several warnings pop up relating to the sbo_relationship field.
`Invalid argument supplied for foreach() sbo__relationship.inc:228`      [warning]`

#### Steps to reproduce
It seems to pop up during the init phase, when content types are created.

#### Error messages and screenshots
```
Creating common Tripal Content Types...
This may take awhile if you are upgrading a site that has lots of data...
Creating organism...
Invalid argument supplied for foreach() sbo__relationship.inc:228      [warning]
Invalid argument supplied for foreach() sbo__relationship.inc:228      [warning]
WD tripal_entities: Done.                                                 [info]
INFO (TRIPAL_ENTITIES): Done.
Done.
Creating Analysis...
Invalid argument supplied for foreach() sbo__relationship.inc:228      [warning]
INFO (TRIPAL_ENTITIES): Done.
Done.
WD tripal_entities: Done.                                                 [info]
Creating Project...
Invalid argument supplied for foreach() sbo__relationship.inc:228      [warning]
WD tripal_entities: Done.                                                 [info]
INFO (TRIPAL_ENTITIES): Done.
Done.
Creating Study...
WD tripal_entities: Done.                                                 [info]
INFO (TRIPAL_ENTITIES): Done.
Done.
Creating contact...
Invalid argument supplied for foreach() sbo__relationship.inc:228      [warning]
WD tripal_entities: Done.
```

I fixed the issue by modifying the code in [sbo__relationship.inc](https://github.com/tripal/tripal/blob/7.x-3.x/tripal_chado/includes/TripalFields/sbo__relationship/sbo__relationship.inc#L211)

From 
```
    $this->schema = new ChadoSchema();
    $this->schema = $this->schema->getTableSchema($reltable);
    $this->base_schema = new ChadoSchema();
    $this->base_schema = $this->base_schema->getTableSchema($base_table);
````

to 
```
    $this->schema = chado_get_schema($reltable);
    $this->base_schema = chado_get_schema($base_table);
```

(Which is the way it's written in some other fields).

**Comment by almasaeed2010** [comment]
Hello @mboudet 

Sorry for the delay on this! I tried to replicate this error but I couldn't. It is possible that the underlying issue has been fixed in newer versions. This is the output from the install script on an Ubuntu system https://travis-ci.org/tripal/tripal/jobs/504878022#L798

Could you try using 7.x-3.1 instead of 7.x-3.0?

Thanks!

**Comment by spficklin** [comment]
Since there's been no further conversation in the past month and the issue can't be replicated I'm closing this out. Please respond if we need to keep this issue opened.
