### ISSUE TITLE
Chado Bulk Loader Job Error

### ISSUE THREAD

**Issue by Yosra3** [tripal/tripal#860]
Hello 
I want to load my data using Chado Bulk Loader module.  I have crate a new template with my columns and a new job.

When i run the drush command i have this error 

ERROR : Job execution failed: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR: current transaction is aborted, commands ignored until end of transaction block  

Thank you

**Comment by btski** [comment]
Could you please copy the output for your Bulk Load Template export?

**Comment by bradfordcondon** [comment]
hi @Yosra3 have you resolved this?  We'll need to see your bulk loader template and input file to help.

**Comment by Yosra3** [comment]
Hi !!
Yes i resolved the problem thank you !!
