### ISSUE TITLE
custom importer guide example code has problems

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#861]
The [custom importer guide](https://tripal.readthedocs.io/en/latest/dev_guide/custom_data_loader.html) calls `fgets` on a string instead of on an open file, as reported by user @yosra3

https://github.com/tripal/tripal/pull/643#issuecomment-467811152

>Thank you for the tutorial it is so clear but i have a problem. Now my file ( with 2 columns in your 
> example ) is imported on tripal but i can't find the data (test_gene_1 and test_gene_2) in my database.
> there is a warning with the drush command :
> fgets() expects parameter 1 to be resource, string given ExampleImporter.inc:152 [warning]
> The feature, , does not exist in the database
> 

Looks like ` while ($line = fgets($file_path)) {` failed for you, so it tried to load afeature named `` and couldn't. Looking at the example on the guide, `fgets` is being passed a string and it instead needs to be passed an open file. Something like this:

```
          $in_fh = fopen($file_path, "r");

  while ($line = fgets($in_fh)) {
```

I also think i should push the importer into a repo and link it from the guide so it can be downloaded directly.

@yosra3 if you have more problems with the guide please post here instead of on the merged pull request.

thanks!

**Comment by Yosra3** [comment]
Thank you for your quick reply. Now there is no warning but i wont to know if it is normal to have this : 

The feature, test_gene_1, does not exist in the database
The feature, test_gene_2, does not exist in the database
The feature, test_gene_2, does not exist in the database
array(4) {
  [0]=>
  string(16) "this is running!"
  [1]=>
  string(1) "5"
  [2]=>
  string(67) "/SV/WWW/GEN03/tripal/sites/default/files/tripal/users/1/example.txt"
  [3]=>
  NULL
}

Done.


Thank you

**Comment by bradfordcondon** [comment]
ok great.

`The feature, test_gene_1, does not exist in the database`

This means the feature isn't in your database.  Do you have any features in the `chado.feature` table?   Do you have any whose unique names are `test_gene_1`?  If no, then this is the expected behavior.  

Have you already worked through the [Tripal User's guide ](https://tripal.readthedocs.io/en/latest/user_guide.html)?  If youre just learning thats where i'd start.
