### ISSUE TITLE
Request for a hook when a bundle is updated

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#864]
## Feature Request/Discussion

* This feature [does] attempt to solve an existing problem with Tripal
* I [am] open to developing or collaborating on an extension module if this is not a good fit for Tripal Core
* This feature is [Not Urgent]

### Description

Currently, bundle creation and deletion trigger hooks for other modules to respond to the event. However, we are missing the `update` hook that would get triggered when something changes in an existing bundle.

### Your Specific Use Case

The new version of Tripal Elasticsearch (not released yet), aims to allow for the sharing of content types between sites to include in the cross site search functionality. It would be beneficial to advertise the fact that a bundle label changed to other sites. This allows us to cache the labels for each site rather than querying the sites with every request.

### Generally Applicable

I am not sure if other modules would find this beneficial.

### Additional information/screenshots

Thanks!

**Comment by bradfordcondon** [comment]
I am in favor of this, and think it doesn't warrant a PMC vote.

**Comment by laceysanderson** [comment]
I would welcome a contribution adding such a hook!

Note: with the switch PMC development focus to Tripal 4 there is no current plans by the PMC to add this functionality.

**Comment by laceysanderson** [comment]
Do you still need this @almasaeed2010? Could you contribute it?

**Comment by almasaeed2010** [comment]
We have not added the functionality to ES yet and I don't believe we will be able to in the near future. Since no one else expressed interest in this, I suppose we can close the issue. Thanks!

**Comment by spficklin** [comment]
I think this is still an important issue so I tagged it with 'address in Tripal4'
