### ISSUE TITLE
How do I attach an image field to Tripal Content Types programmatically

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#866]
Hi guys, so I'm looking to add an image field to a Tripal Content Type but I'm not exactly sure how to do that. I see examples when I search in Google on how to do this with a normal drupal content type but I'm not sure that would work for Tripal Content Types. Anyone have any ideas on this?

Please let me know, thanks!
@bradfordcondon @spficklin @mestato

**Comment by risharde** [comment]
I was able to partially attach an image using the following but it wasn't able to assign a cvterm. Could you advise me on the proper code to do that? Here's what I have currently:

> 		if (!field_info_field('tcp_photo')) {
			// Create the field base.
			$field = array(
			  'field_name' => 'tcp_photo', 
			  'type' => 'image', 
			);
			field_create_field($field);

			// Create the field instance on the bundle.
			$instance = array(
			  'field_name' => 'tcp_photo', 
			  'entity_type' => 'TripalEntity', 
			  'label' => 'Photo', 
			  'bundle' => tripal_contact_profile_getMachineName(), 
			  // If you don't set the "required" property then the field wont be required by default.
			  'required' => FALSE,
			  'settings' => array(
				// Here you inform either or not you want this field showing up on the registration form.
				'user_register_form' => 0,
				'file_extensions' => 'png jpg jpeg',
				'file_directory' => 'tripal_contacts/photos',
				'alt_field' => 0,
				'title_field' => 0,
				'default_image' => 0,				
			  ),
			  /*
			  'widget' => array(
				'type' => 'image',
			  ), 
			  */
			);
			field_create_instance($instance);
			drupal_set_message("Photo Field created!", 'success');
		}

**Comment by risharde** [comment]
Anything that could help me on this? Still awaiting a possible solution, can't seem to find anything related on the docs. @bradfordcondon @shawnawsu @mestato @spficklin

**Comment by shawnawsu** [comment]
Hi Risharde,

Have you looked at the organism tripal content type? It has an image field attached to it. The image is attached as such in the tripal_chado.field.inc file:


```
// Add an image field to the Organism type.  This is a Drupal field and
  // not stored in Chado, but is used for backwards compatibility.
  if ($table_name == 'organism') {
    $field_name = 'data__image';
    $info[$field_name] = array(
      'field_name' => $field_name,
      'entity_type' => $entity_type,
      'bundle' => $bundle->name,
      'label' => 'Organism Image',
      'description' => 'An image for the organism',
      'required' => FALSE,
      'settings' => array(
        'term_vocabulary' => 'data',
        'term_name' => 'Image',
        'term_accession' => '2968',
      ),
      'display' => array(
        'default' => array(
          'label' => 'hidden',
        ),
      ),
    );
  }
```

These two bits of code make the previous bit of code work (you don't need to implement these I just wanted to show you how the data__image is handled):
```

// Add an image field to the Organism type.  This is a Drupal field and
  // not stored in Chado, but is used for backwards compatibility.
  if ($table_name == 'organism') {
    $field_name = 'data__image';
    $info[$field_name] = array(
      'field_name' => $field_name,
      'type' => 'image',
      'cardinality' => 1,
      'locked' => FALSE,
      'storage' => array(
        'type' => 'field_sql_storage',
      ),
    );
  }

/**
 * Implements hook_field_views_data_alter();
 */
function tripal_chado_field_views_data_alter(&$result, $field) {

  // This module creates the data__image field for managing images on
  // bio_data content types. But we want it to render correctly
  // so we need to set some handlers.
  if ($field['field_name'] == 'data__image') {
    foreach ($result as $key => $fields) {
      // It's not clear how to identify our bundle types, but they do have
      // a double underscore in their name to separate the vocabulary from
      // the accession, so we'll use that to find them.
      if (preg_match('/__/', $key)) {
        $result[$key]['data__image']['field']['handler'] = 'tripal_views_handler_field_image';
      }
    }
  }
}

```


So if you create the field as a data__image there are functions that should wrap it so it displays correctly.

**Comment by risharde** [comment]
Thank you @shawnawsu ! Really appreciate it!!

**Comment by almasaeed2010** [comment]
Looks like this has been addressed 👍 

Please feel free to reopen if not.
