### ISSUE TITLE
Description field assumes text filter machine name

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#868]
## BUG/ERROR report
After migrating a tripal 2 site to tripal 3 and migrating content, all content with description fields wont display descriptions.
The description widget has the full description, with the text format set to: `-select-`.    Picking any option and submitting results in still no description, and, if i go back to edit, the text format is set back to `-select-`

<img width="1055" alt="screen shot 2019-03-03 at 5 39 01 pm" src="https://user-images.githubusercontent.com/7063154/53703039-57b32080-3ddb-11e9-929b-592b9a7273d9.png">

<img width="942" alt="screen shot 2019-03-03 at 5 40 59 pm" src="https://user-images.githubusercontent.com/7063154/53703054-87622880-3ddb-11e9-93dd-5803ca6cd180.png">

some similarity to #721 , i had those WYSIG editors enabled prior to migration, I deleted them afterwords but no help.

If I change the bundle-level field setting to use hte plain text processing, then the field shows up (but without the html tags being processed, so thats not a fix.  but it suggests to me that something is going on at the widget level)

<img width="527" alt="screen shot 2019-03-03 at 5 45 16 pm" src="https://user-images.githubusercontent.com/7063154/53703119-31da4b80-3ddc-11e9-9648-d76e3c7700f2.png">

The problem also occurs if i create a new organism- i can select the filter type but the field doesnt display and editing shows no filter tpe is selected.

**Comment by bradfordcondon** [comment]
This looks to be the problem: I dont have a `full_html` filter availalbe on this site (despite it showing up in the select box?  and despite it working if i manually create a multiline text field and select the `full_html` filter?)


![screen shot 2019-03-04 at 9 40 08 am](https://user-images.githubusercontent.com/7063154/53740200-ac00e380-3e61-11e9-8d22-5a581e654c09.png)

**Comment by almasaeed2010** [comment]
In a previous version of drupal the text formats were represented as numbers. The new drupal way is to give them a machine name (using alpha numerical characters instead of only numbers). Unfortunately, I don't remember finding a way to fix this issue. I ended up having to create new fields and marking old ones with a do not use label.

**Comment by almasaeed2010** [comment]
Go to `/admin/config/content/formats` to see the formats. Click configure to see the machine name.

**Comment by bradfordcondon** [comment]
Yep that looks like whats going on:

```
select * from filter_format;
format	name	cache	status	weight
4	File Tree	1	0	-7
file_tree	File Tree format	1	0	-7
3	PHP code	0	1	-8
5	Plain text	1	1	-6
filetree	filetree	1	1	-7
2	Full HTML	1	1	-9
1	Filtered HTML	1	1	-10
```

VS the looking online, i see `format` set to `full_html` instead of 1.  You're spot on.

![screen shot 2019-03-04 at 9 46 18 am](https://user-images.githubusercontent.com/7063154/53740516-609b0500-3e62-11e9-9fc0-fc4063e8f3f4.png)

No way to set the machine name.

Is there somewhere in the core code where we assume the machine name = filtered_html?  can we use a Drupal API function stead?

I see plenty of modules using `filtered_html` directly.  Should we instead figure out how to update the text format machine names?

my filter module version is 7.59.

**Comment by bradfordcondon** [comment]
So older sites will have the machine name for their filters as ints instead of, say, `full_html`.  

Users experiencing this problem where they can't set a filter can fix by creating new filters with the expected machine name.  heres what we have on hWG:

```
   format     |            name            | cache | status | weight 
---------------+----------------------------+-------+--------+--------
 markdown      | Markdown                   |     1 |      1 |      0
 php_code      | PHP Code                   |     0 |      1 |      0
 filtered_html | Filtered HTML              |     1 |      1 |      0
 4             | Plain text (DO NOT USE)    |     1 |      1 |      1
 plain_text    | Plain Text                 |     1 |      1 |      0
 full_html     | Full HTML                  |     1 |      1 |      0
 2             | Full HTML (DO NOT USE)     |     1 |      1 |      0
 1             | Filtered HTML (DO NOT USE) |     1 |      1 |     -1
 3             | PHP code (DO NOT USE)      |     0 |      1 |      0
```
note we keep (but rename) the old filters to prevent breaking content using them.

A better fix would be for Tripal to acommodate filters that dont have the expected machine names (but do have the expected human readable names).

**Comment by bradfordcondon** [comment]
this is indeed in the documentation at the end:

https://tripal.readthedocs.io/en/latest/user_guide/install_tripal/upgrade_from_tripal2.html#troubleshooting


I guess this is not something we're able to automate, so I'm closing this.
