### ISSUE TITLE
Warning with the new version Tripal v3.1

### ISSUE THREAD

**Issue by Yosra3** [tripal/tripal#870]
Hello 
After updating tripal v3.1 i have this warning on the home page : 

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in require_once() (line 64 of  /tripal/sites/all/modules/tripal/tripal_chado/tripal_chado.module).

what it means? it is a problem of updating ? 

Thank you

**Comment by almasaeed2010** [comment]
Hello @Yosra3, 

Could you please provide information on your system?

```
Drupal version:
PHP version:
```

Thanks!

**Comment by almasaeed2010** [comment]
You can get this information by visiting the status report page at `/admin/reports/status`

**Comment by Yosra3** [comment]
@almasaeed2010  thanks for your reply 

drupal-7.64
PHP 7.3.2

**Comment by almasaeed2010** [comment]
Ok I managed to get my hands on a vm that has php7.3 installed. This error only happens in php7.3:

<img width="1440" alt="screen shot 2019-03-06 at 9 08 51 am" src="https://user-images.githubusercontent.com/1512664/53887095-89043a00-3fef-11e9-8696-41e09fa41cdf.png">

There is a simple fix for this. I'll push the changes today but it probably won't be available until tripal version 3.2. The easiest way to get rid of this for now is to add the following lines to the end of your `sites/default/settings.php` file:

```php
error_reporting(0); 
$conf['error_level'] = 0;
ini_set('display_errors', false);
ini_set('display_startup_errors', false);
```

Thanks!

**Comment by Yosra3** [comment]
thank you i have no more this warning !!

**Comment by bradfordcondon** [comment]
Thank you @Yosra3 @almasaeed2010  for reporting and fixing.
