### ISSUE TITLE
currval of sequence "feature_feature_id_seq" is not yet defined in this session

### ISSUE THREAD

**Issue by Yosra3** [tripal/tripal#872]
Hello 

I want to import a file of genetic markers on tripal. I used chado bulk loader module. 
After creating a new template and a job, i had this error with the drush command  : 
In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block

On the log file i found this : 
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:  SET search_path TO public
ERROR:  currval of sequence "feature_feature_id_seq" is not yet defined in this session
STATEMENT:  SELECT CURRVAL('chado.feature_feature_id_seq')

Can someone help me please?
Thank you

**Comment by bradfordcondon** [comment]
hi @Yosra3 to help you troubleshoot we will likely need

a) your bulk importer
b) the file you are importing?

Thanks!

**Comment by Yosra3** [comment]
@bradfordcondon  Thank you for your your reply 

**_The bulk importer that i use :_** 

[{"table":"feature","record_id":"Markers","mode":"insert","fields":[{"type":"table field","title":"Organism","field":"organism_id","required":0,"spreadsheet column":"1","exposed":0,"exposed_description":""},{"type":"table field","title":"feature_type","field":"type_id","required":0,"spreadsheet column":"2","exposed":0,"exposed_description":""},{"type":"table field","title":"ID_Marker","field":"uniquename","required":0,"spreadsheet column":"3","exposed":0,"exposed_description":""},{"type":"table field","title":"SNP_ID","field":"feature_id","required":0,"spreadsheet column":"4","exposed":0,"exposed_description":""},{"type":"table field","title":"Sequence","field":"residues","required":0,"spreadsheet column":"6","exposed":0,"exposed_description":""},{"type":"table field","title":"Primer_AlleleX","field":"residues","required":0,"spreadsheet column":"7","exposed":0,"exposed_description":""},{"type":"table field","title":"Primer_AlleleY","field":"residues","required":0,"spreadsheet column":"8","exposed":0,"exposed_description":""},{"type":"table field","title":"Primer_Common","field":"residues","required":0,"spreadsheet column":"9","exposed":0,"exposed_description":""}],"select_if_duplicate":1,"update_if_duplicate":0,"select_optional":0,"disable":0,"optional":0},{"table":"featureloc","record_id":"Localisation","mode":"insert","fields":[{"type":"table field","title":"cM","field":"fmin","required":0,"spreadsheet column":"5","exposed":0,"exposed_description":"cM"},{"type":"table field","title":"Direction","field":"strand","required":0,"spreadsheet column":"10","exposed":0,"exposed_description":""}],"select_if_duplicate":1,"update_if_duplicate":0,"select_optional":0,"disable":0,"optional":0}]

**_And this is the file_ _( just an example to test )**  (.txt tab delimited )_
Organism	feature_type	ID_Marker	SNP_ID	cM	Sequence	Primer_AlleleX	Primer_AlleleY	Primer_Common	Direction
5	1911	I299	767323	58	GCCATTTTCT	GAAGGTGA	GAAGGTCGG	GATTGTGAG	-1
5	1911	I299	767324	58	GTATAR	GAAGGTGACCA	GAAGGTCGGAGTC	GAGTCTGCTAA	1
5	1911	I333	767325	58	AAKANC	GAAGGTGACC	GAAGGTCGGAG	GYTCTAC	-1
5	1911	I332	767326	58	RATTGC	GAAGGTGA	GAAGGTCGGA	CAAGAG	-1
5	1911	I331	767327	58	GATGAT	GAAGGTGACCAAGTT	GAAGGTCG	GACCAGTG	1
5	1911	I330	767328	58	GGARTA	GAAGGTGACCAA	GAAGGTCGG	GATGGA	-1
5	1911	I329	767329	58	AATCTG	GAAGGTGA	GAAGGTC	AAAGT	1

**Comment by Yosra3** [comment]
@bradfordcondon Thank you for your your reply

**_The bulk importer that i use :_**

![image](https://user-images.githubusercontent.com/47979265/53894339-37c86a80-4030-11e9-8c20-15c46d12e987.png)


[{"table":"feature","record_id":"Markers","mode":"insert","fields":[{"type":"table field","title":"Organism","field":"organism_id","required":0,"spreadsheet column":"1","exposed":0,"exposed_description":""},{"type":"table field","title":"feature_type","field":"type_id","required":0,"spreadsheet column":"2","exposed":0,"exposed_description":""},{"type":"table field","title":"ID_Marker","field":"uniquename","required":0,"spreadsheet column":"3","exposed":0,"exposed_description":""},{"type":"table field","title":"SNP_ID","field":"feature_id","required":0,"spreadsheet column":"4","exposed":0,"exposed_description":""},{"type":"table field","title":"Sequence","field":"residues","required":0,"spreadsheet column":"6","exposed":0,"exposed_description":""},{"type":"table field","title":"Primer_AlleleX","field":"residues","required":0,"spreadsheet column":"7","exposed":0,"exposed_description":""},{"type":"table field","title":"Primer_AlleleY","field":"residues","required":0,"spreadsheet column":"8","exposed":0,"exposed_description":""},{"type":"table field","title":"Primer_Common","field":"residues","required":0,"spreadsheet column":"9","exposed":0,"exposed_description":""}],"select_if_duplicate":1,"update_if_duplicate":0,"select_optional":0,"disable":0,"optional":0},{"table":"featureloc","record_id":"Localisation","mode":"insert","fields":[{"type":"table field","title":"cM","field":"fmin","required":0,"spreadsheet column":"5","exposed":0,"exposed_description":"cM"},{"type":"table field","title":"Direction","field":"strand","required":0,"spreadsheet column":"10","exposed":0,"exposed_description":""}],"select_if_duplicate":1,"update_if_duplicate":0,"select_optional":0,"disable":0,"optional":0}]

**_And this is the file _( just an example to test ) (.txt tab delimited )__**


![image](https://user-images.githubusercontent.com/47979265/53894181-f0da7500-402f-11e9-81e5-e9bf0bd47fa6.png)
