### ISSUE TITLE
Should we add php 7.2 and 7.3 to travis

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#874]
Hello,

Now that [php 7.0 is no longer supported (not even security updates)](http://php.net/supported-versions.php), I think we should update .travis.yml to build on 7.1, 7.2 and 7.3.

I'll create a PR for this but this issue is here for discussion.

**Comment by almasaeed2010** [comment]
Turns out drupal 7 only supports 7.1 and 7.2 https://www.drupal.org/docs/7/system-requirements/php-requirements#php_required

**Comment by almasaeed2010** [comment]
PR submitted https://github.com/tripal/tripal/pull/875

**Comment by laceysanderson** [comment]
Merged 👍
