### ISSUE TITLE
Show publication on feature pages

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#876]
## Feature Request/Discussion

* This feature [does] attempt to solve an existing problem with Tripal
* I [am] open to developing or collaborating on an extension module if this is not a good fit for Tripal Core

* This feature is [Not Urgent]

### Description

It would be nice to see which publication a particular feature (gene, mRNA) is associated with if the parent analysis is associated with a publication. Since the `analysisfeature` table is populated with the relationship, it should be simple to add to the schema__publication field to display all associated pubs with features.

### Your Specific Use Case

Example from our site:

- visit [this feature](https://hardwoodgenomics.org/feature/Potri001G4187501) page
- Publication field is not showing up although [the analysis](https://hardwoodgenomics.org/Genome-assembly/1919890) this feature is associated has a publication associated with it

**Comment by bradfordcondon** [comment]
I think you need to distinguish between pubs associated via `feature_analysis` => `analysis_pub` and pubs associated via `feature_pub`.   To me this suggests a custom "analysis-linked pub" field.

**Comment by almasaeed2010** [comment]
If we are taking this route (new field), I think this warrants a PMC vote since it's a new feature. @tripal/project-managent-commitee-pmc

**Comment by laceysanderson** [comment]
I vote in favour of adding a new field to show publications associated with an analysis on a related feature page. I think this would be extremely helpful to users and is generic enough to be useful for multiple groups 👍

**Comment by bradfordcondon** [comment]
I'm also ok with it.  

While we're talking, do we have an ontology term?

**Comment by almasaeed2010** [comment]
I've developed a field to do this for features specifically. I think we can take this field and expand on it to include other types of records as well.

- Code https://github.com/statonlab/tripal_feature_pub
- Demo https://hardwoodgenomics.org/bio_data/158359?tripal_pane=gp_schema__publication49321

The term used here is [sio:000087 (publication)](https://www.ebi.ac.uk/ols/ontologies/sio/terms?iri=http%3A%2F%2Fsemanticscience.org%2Fresource%2FSIO_000087) but if needed we can migrate to a different term.

Let me know what you think!

Thanks.

**Comment by bradfordcondon** [comment]
Awesome!

Looking at the code everything seems 👍 
The only thing im wondering about is the term.  Is it confusing to have schema:publication and sio:publication in use?  I wonder if it would be better to use a local term, to the tune of "indirectly associated publication"

**Comment by spficklin** [comment]
@almasaeed2010 were you going to submit a PR for this field?  It's been several months since this was discussed?

**Comment by bradfordcondon** [comment]
@almasaeed2010  are you still interested in this field?

**Comment by laceysanderson** [comment]
@almasaeed2010 I'm going to close the issue as there has been no movement on this issue for awhile and you do have a working solution. We would still greatly welcome a contribution back so feel free to open a PR to that effect when you find time!
