### ISSUE TITLE
Tripal entity title link uses dash instead of underscore

### ISSUE THREAD

**Issue by guignonv** [tripal/tripal#879]
## BUG/ERROR report
* Tripal Version: 3.x-dev
* Drupal Version: 7.64
* PostgreSQL Version: 9.4
* PHP Version: 7.2

### Issue description
When you go on a Tripal entity page, the title link uses dash instead of underscore and does not link to the entity page (the same page in fact).

#### Steps to reproduce
Create a new Tripal data entry and publish it. Go to its page (using the "admin/content/bio_data" page for instance) and click on the title link. It should lead you to a 404 page while it should link you to the same page. This link is not only used by Tripal entity page content but also in other places where the entity uri callback is used.

#### Error messages and screenshots
![image](https://user-images.githubusercontent.com/7290244/53961479-fb0c7a00-40e8-11e9-9be9-5bc2f29222de.png)

**Comment by guignonv** [comment]
I created a PR #880

**Comment by bradfordcondon** [comment]
oops!   Thank you for the report and the fix.
