### ISSUE TITLE
tripal_feature has some problem.

### ISSUE THREAD

**Issue by dedenmatra** [tripal/tripal#88]
Dear All 

When I installed new tripal 7.x-2.1, then enable the tripal_feature, my site cant open. however, if tripal_feature was disabled, the site can open again. have some bug in tripal_feature?

thank you

--------
-jailshell-4.1$ drush pm-enable tripal_feature
The following extensions will be enabled: tripal_feature
Do you really want to continue? (y/n): y
tripal_feature was enabled successfully.                                                   [ok]
tripal_feature defines the following permissions: access chado_feature content, create chado_feature content, delete chado_feature content, edit chado_feature content, administer tripal feature
Job 'Load OBO Chado Feature Properties' submitted.                                         [status]
Custom table, 'organism_feature_count' ,  created successfully.                            [status]
Materialized view 'organism_feature_count' created                                         [status]
Custom table, 'tripal_gff_temp' ,  created successfully.                                   [status]
Custom table, 'tripal_gffcds_temp' ,  created successfully.                                [status]
Custom table, 'tripal_gffprotein_temp' ,  created successfully.                            [status]
-jailshell-4.1$ drush trp-run-jobs --username=######

2017-04-11 06:25:42
Tripal Job Launcher
Running as user '####'
-------------------
There are 1 jobs queued.
Calling: tripal_cv_load_obo_v1_2_id(5, 4)

NOTE: Loading of this OBO file is performed using a database transaction. 
If the load fails or is terminated prematurely then the entire set of 
insertions/updates is rolled back and will not be found in the database

Step 1: Preloading File //####/sites/all/modules/tripal/tripal_feature/files/feature_property.obo
Parsing Line 457 (100.00%). Memory: 32,026,968 bytes.
Step 2: Loading type defs...
47 of 47 records. (100.00%) Memory: 32,028,768 bytes
Step 3: Loading terms...
0 of 0 records. (100.00%) Memory: 32,024,752 bytes
Updating cvtermpath table.  This may take a while...

Updating cvtermpath for unknown...

Done
-jailshell-4.1$ drush pm-disable tripal_feature
The following extensions will be disabled: tripal_feature
Do you really want to continue? (y/n): y
tripal_feature was disabled successfully.                                                  [ok]
Unable to find a view by the name of 'tripal_feature_user_feature'. Unable to disable this [error]
view.
Unable to find a view by the name of 'tripal_feature_admin_features'. Unable to disable    [error]
this view.

**Comment by laceysanderson** [comment]
Hi @dedenmatra,

I just tried to reproduce your error with a clean install of Tripal 2.1, Drupal 7.54 and did not experience the same issues as you did...

I'm running Debian GNU/Linux 7, PostgreSQL 9.4.5 PHP 5.6.7-1, Apache 2.4.10. What are your system versions?

Clarification: when you say your "site can't open" are you referring to seeing a white screen with no text when you open your website in your browser?

Also, could you check your apache error log for any relevant error messages? On Debian it can be found at /var/log/apache2/error.log and required sudo to look at it.

**Comment by dedenmatra** [comment]
hi @laceysanderson, 

I hosted my site in Bluehost (Shared hosting), and the configuration system refers to Bluehost conf default.  

The site only clear screen without any text.

**Comment by spficklin** [comment]
Hi @dedenmatra it looks like you disabled the tripal_feature module in the log you posted.  Why was that?  Also, I don't see anything in the log you posted that indicates  a problem.   Can you look at your server logs from bluehost and see what error message appears there?

**Comment by dedenmatra** [comment]
thanks @spficklin for your comments.

because I cant open site, i tried to disable tripal_feature module. then, the site can open again. 
but when i was disable the tripal_feature, some error message shown like : 

Unable to find a view by the name of 'tripal_feature_user_feature'. Unable to disable this [error]
view.
Unable to find a view by the name of 'tripal_feature_admin_features'. Unable to disable [error]
this view.

, i will try to find error in my server log.

thank you.

**Comment by dedenmatra** [comment]
hi @spficklin ,

I found error shown in below : 
PHP Parse error:  syntax error, unexpected T_FUNCTION, expecting ')' in /home2/rujakbas/public_html/test/sites/all/modules/tripal/tripal_feature/includes/tripal_feature.gff_loader.inc on line 313

thanks

**Comment by spficklin** [comment]
Hi @dedenmatra 

I believe in bluehost you have the ability to update to a more recent version of PHP.  In your previous comment you indicate that you're using PHP v5.6.7.   Can you try upgrading to PHP 7.  You can find instructions on bluehost here:  https://my.bluehost.com/cgi/help/447

**Comment by spficklin** [comment]
Marking this one as closed. If you still have the problem @dedenmatra please re-open the issue.
