### ISSUE TITLE
Missing query preview for views on Tripal entities.

### ISSUE THREAD

**Issue by guignonv** [tripal/tripal#881]
### System information
* Tripal Version: 7.x-3.x-dev
* Drupal Version: 7.64
* PostgreSQL Version: 9.4
* PHP Version: 7.2

### Issue description
When you create a view on a Tripal entity type and enabled the "show SQL query" on views settings, you will get the following PHP warning in your Drupal logs (Reports > Recent log messages):
`Warning: strtr() expects parameter 1 to be string, object given in views_ui_preview() (line 214 of /<...>/modules/views/includes/admin.inc).
`
#### Steps to reproduce
1. Enable "show SQL query" in "Live preview settings" on views settings (admin/structure/views/settings).
2. Create a new view on a Tripal content type.
3. On the view edit from, click on the button "Update preview".
![image](https://user-images.githubusercontent.com/7290244/53964243-3c078d00-40ef-11e9-95b1-b553d2ea817a.png)
4. Check your Drupal logs (admin/reports/dblog)

#### Error messages and screenshots

![image](https://user-images.githubusercontent.com/7290244/53964551-db2c8480-40ef-11e9-8137-f577d65935e5.png)

```
Warning: strtr() expects parameter 1 to be string, object given in views_ui_preview() (line 214 of /<...>/modules/views/includes/admin.inc).
```

**Comment by bradfordcondon** [comment]
thanks for reporting and resolving @guignonv .  If this issue shouldnt be closed please let me know.
