### ISSUE TITLE
Warning using OBO Vocabulary Loader

### ISSUE THREAD

**Issue by eglabmsu** [tripal/tripal#887]
### System information

* Tripal Version: 7.x-3.x
* Drupal Version: 7.59
* PostgreSQL Version: 10.6
* PHP Version: 7.1

### Issue description

I have a problem similar to closed issue #253 when trying to load a Plant Ontology .obo file from their git repository using the OBO Vocabulary Loader . I also tried a .owl file (http://purl.obolibrary.org/obo/po.owl) with similar results. 

#### Steps to reproduce

New Vocabulary Name: Plant Ontology
Remote URL: https://github.com/Planteome/plant-ontology/blob/master/plant-ontology.obo

#### Error messages and screenshots

```
Downloading URL https://github.com/Planteome/plant-ontology/blob/master/plant-ontology.obo, saving to /tmp/obo_4VEfwu
Step 1: Preloading File /tmp/obo_4VEfwu...
array_key_exists() expects parameter 2 to be array, null given OBOImporter.inc:598 [warning]
array_key_exists() expects parameter 2 to be array, null given OBOImporter.inc:604 [warning]
This OBO is missing the 'default-namespace' header. It is not possible to determine which vocabulary terms without a 'namespace' key should go.  Instead, those terms will be placed in the '' vocabulary.
Step 2: Loading type defs...
Step 3: Loading terms...mory: 41,695,080 bytes.
Percent complete: 0%. Memory: 41,695,192 bytes.
Done.

```

**Comment by eglabmsu** [comment]
Seems the problem was with the .obo file. I sourced http://purl.obolibrary.org/obo/po.obo and the loader is now happy. Please mark resolved. Thanks!

**Comment by laceysanderson** [comment]
Awesome :-) 👍
