### ISSUE TITLE
New fields aren't positioned in default layout

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#89]
The Tripal Analysis Blast module is trying to add a new field 'Blast Results' to any bundle associated with the Sequence Ontology (vocabulary == 'SO').  When adding this new field it shows ups as disabled in the display for the entity.  This is probably a good thing because it allows users to turn it on for the bundles they want it turned on for.  But if the user wants to enable it they are forced to create the Tripal Pane then the Tripal fieldset.  Can we find an easier way to do this automatically for the field?

**Comment by shawnawsu** [comment]
Can we ask the user during the process of adding the field in the Tripal Analysis Blast if they'd like it to be a Tripal Pane? Then we can just set a simple function that wraps and builds the Tripal Pane for them.  If that's not ideal maybe we can add another button at the top of the "Manage Fields" tab that  is for creating a new tripal pane, we can have an auto-populated list of fields to choose from based on the entity type.

**Comment by laceysanderson** [comment]
I hate to be "that person" ;-) but I think that we should have both 
1. an API function that creates a Tripal Pane and adds a set of fields to it
2. a button on Manage Fields that creates an empty Tripal Pane.

The first would allow Tripal Analysis and other modules to automatically put their fields into panes (preferably after prompting the user :-) ) and the second would allow Tripal Admin who are re-organizing their pages to quickly create an empty Tripal Pane to move fields into. I was working on KnowPulse custom Tripal Fields yesterday and felt the need for both...

**Comment by shawnawsu** [comment]
Do we want the button created empty tripal pane (2) to be placed in a region or have it placed in the disabled section?

**Comment by laceysanderson** [comment]
We might want to revisit this now that the hierarchy of Tripal Panes has been reduced. This was needed before because admin had to create both a Tripal pane and a fieldset and then move the new field within. Now they just create a TripalPane (no nested fieldset) which seems simple enough. Thus I don't think we need this button. The API function would still be helpful though.

Thoughts?

**Comment by shawnawsu** [comment]
I've got the button working and think it makes sense because to achieve the float functionality (hidden at initial page load) you need to get the classes applied correctly, so the button removes that possible misstep. But I'm not attached to it if it makes more sense to remove it.

**Comment by shawnawsu** [comment]
I am going to close this issue out and if it crops up again as problematic we can reopen or start a new ticket.
