### ISSUE TITLE
How to migrate external node references to entity references for Tripal 3.1 templates?

### ISSUE THREAD

**Issue by mdondrup** [tripal/tripal#893]
I have a content type that is linked to tripal features by their node reference. 

See https://blowfly-test.cbu.uib.no/node/884214
and https://blowfly-test.cbu.uib.no/node/711864

![image](https://user-images.githubusercontent.com/893151/54473688-61755480-47db-11e9-8a9e-77c76c1053eb.png)
![image](https://user-images.githubusercontent.com/893151/54473909-78697600-47de-11e9-85bb-3c36b1e207aa.png)

In more detail, to store RNA-interference experiments in a LIMS-like fashion, we reference the target gene/transcript and organism via node references in the content type RNAi. Then on the gene's page, we link back to the experiment via a view taking the node id as a filter parameter. 

Now, in order to migrate to Tripal 3 templates, we would have to migrate all node references to entity reference, correct? I haven't expected that to become a problem, to be honest, but there are now over 400 experiments of this type. Could someone guide me on how to first achieve the migration from node to entity reference, and possibly also how to embed additional panes into the feature pages.

The most important task is, of course, to migrate the node references without losing the association between experiment and its affected gene. I think I would have to:

- for each content of type RNAi (entity):
- get the node reference for the tripal 2 node
- find the node reference the tripal 3 entity that belongs to it (this is the hard part I guess)
- enter the entity reference to the tripal 3 node

This is the code that embeds the view, btw:

gene-template:
```
  // embedd the pre-defined block view to add the associated RNAi for this chado feature
  echo views_embed_view('rnai_experiments_block_view', 'rnai_block_feature', $node->nid);

```

```
function tripal_gene_node_view($node, $view_mode, $langcode) {
  switch ($node->type) {
     case 'chado_feature':
      // Show feature browser and counts
      if ($view_mode == 'full') {   
...
       $node->content['tripal_gene_rnai'] = array(
          '#markup' => theme('tripal_gene_rnai', array('node' => $node)),
          '#tripal_toc_id'    => 'RNAi',
          '#tripal_toc_title' => 'Associated RNAi experiments',
          '#weight' => -1,
        );
...
```

**Comment by bradfordcondon** [comment]
I'm confused- is your RNAi content type a feature?  And/or any other Chado content type?  Is it associated with the parent gene feature in some way- feature_relationship, etc?

If so the best solution is to write a simple custom field.  In general things are going to work better "out of the box" with Tripal if you are making use of Chado.


Let's say you did want/need to only use node references, which you now need to update to entity references.  The upgrade should store the node id in the corresponding `chado_bio_data_x` table, in the `nid` column.  So, you could look up the nid in the correct `chado_bio_data_x` table, to retrieve the entity id.

**Comment by mdondrup** [comment]
Sorry for the confusion, making our LIMS the way we did felt to be the most agile way at that time ;)

> I'm confused- is your RNAi content type a feature? And/or any other Chado content type? Is it associated with the parent gene feature in some way- feature_relationship, etc?

RNAi is, in fact, a pure Drupal content type (entity), it contains node references to chado feature nodes though. It contains a bunch of other data types, like dates, drupal taxonomy fields for the phenotypes, and other annotation. This is our complete LIMS containing the collected results from 8 years of experiments, so I cannot simply scrap it.  

> Let's say you did want/need to only use node references, which you now need to update to entity references. The upgrade should store the node id in the corresponding chado_bio_data_x table, in the nid column. So, you could look up the nid in the correct chado_bio_data_x table, to retrieve the entity id.

I will try that out, after we decide if we can move to entities at all. This all depends on the sequence issue.

**Comment by bradfordcondon** [comment]
OK.  So you want to update the Tripal-type node references on the RNAi  non-Chado entity.  In that case, i would write a script that crawls the field instances and looks up  the `nid` in `chado_bio_data_x`.

Check out this gist i have for [migrating Drupal-based fields into Chado](https://gist.github.com/bradfordcondon/0dddfd015ff6ef1f545364c2ceff1f0b): you'll want to be doing pretty much the same thing, except instead of inserting a property into chado, you'll update the nid to the entity id for that field instance (the field on your RNAi linking to chado nodes that are being replaced).

**Comment by bradfordcondon** [comment]
hi @mdondrup how did this turn out? any further thoughts or needs for help?  Can I close the issue?

**Comment by spficklin** [comment]
I submitted a PR to include a link to @bradfordcondon 's documentation in our upgrade docs online so this knowledge is not lost.

**Comment by spficklin** [comment]
PR has been merged. I'm closing this out.
