### ISSUE TITLE
Tripal 3 Field Warning on New Install

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#908]
### System information

* Tripal Version: 7.x-3.x
* Drupal Version: 7.6
* PostgreSQL Version: 9.6
* PHP Version: 7.1

### Issue description

I've been getting the following warning when preparing Drupal and Chado.

```php
The field, efo__array_design, uses a term, EFO:0000269, that is already in use on this content    [warning]
type. The field instance cannot be added.
```

Does this mean that we are trying to attach the same field twice?

#### Steps to reproduce

Install Tripal3 from master on a new server/site and run the prepare Drupal and Chado job.

This error also happens on Travis: https://travis-ci.org/tripal/tripal/jobs/510976463#L891

Thanks!

**Comment by bradfordcondon** [comment]
duplicate with https://github.com/tripal/tripal/issues/681
