### ISSUE TITLE
Fieldset shows up as title in Tripal Pane

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#91]
The purpose in nesting a fieldset inside of a Tripal Pane was so that someone could swap out the fieldset for something else if they didn't like the fieldset. However, the titles in the TOC are using the fieldset titles rather than the Tripal Pane titles.   We need to fix the TOC so it uses the Pane title rather than the fieldset.  Maybe needs more discussion....

**Comment by laceysanderson** [comment]
I agree that the Tripal Pane title would be most intuitive as the title in the TOC :-)

**Comment by shawnawsu** [comment]
After discussion next steps are:
- Remove the intermediary fieldset from the tripal_ds layout build, this will result in boxes that do not collapse
- Title and description fields from Tripal Pane will now be displayed in the right box 
- Title of Tripal Pane will be TOC link text
- Summary will be the only Tripal Pane displayed on initial page load

**Comment by shawnawsu** [comment]
All updates in branch 7.x-3.x-dashboard, ready for testing.

**Comment by laceysanderson** [comment]
This is now in the main branch and looks perfect :-) Thanks @shawnawsu!
