### ISSUE TITLE
relationship formatter does not find subject or object analysis entity name

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#911]
### System information

* Tripal Version: 7.x-3.1
* Drupal Version: 7.59
* PostgreSQL Version:  9.2.23
* PHP Version: 7.1.15

### Issue description

Working on a side upgrading from t2 to t3, i came across the relationship reporting a relationship as:  "The analysis, , derives from analysis, "  Both analyses have `analysis.names`, and the name field is populated.  Yet, `schema:name` is empty for both the subject and object (see dpm).  This problem occurs on bot the subject and object.

![Screen Shot 2019-03-27 at 1 15 13 PM](https://user-images.githubusercontent.com/7063154/55097534-67e4b580-5092-11e9-969d-7d974ea7c0c4.png)

**Comment by bradfordcondon** [comment]
Easy fix:

The constructor doesnt set`  $this->base_name_columns` for analysis, biomaterial, cell_line, quantification, and acquisition.

https://github.com/tripal/tripal/blob/d0d52df57057600aa987d2372c6ab36254828784/tripal_chado/includes/TripalFields/sbo__relationship/sbo__relationship.inc#L237-L278



setting it to `['name']` populates the field (although i still dont have entity links).

![Screen Shot 2019-03-27 at 1 24 20 PM](https://user-images.githubusercontent.com/7063154/55098162-ae86df80-5093-11e9-8f0e-c63a593e3867.png)


resolved as well, using `substr_replace` instead of regexp replace:


![Screen Shot 2019-03-27 at 1 49 01 PM](https://user-images.githubusercontent.com/7063154/55099992-2d314c00-5097-11e9-9313-be34b72e1ddc.png)

**Comment by laceysanderson** [comment]
PR Merged 🎉
