### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by kyrenya** [tripal/tripal#914]
Hi there, I'm using Drupal core 7.65, Tripal 7.x-3.1. 
It happens that when I use the search form to find Genes, or CDS, and get a table with results, 
when I click in any of them, instead of taking me to the Gene or to the CDS page, I get an **Access denied page**. I have all permissions enabled to administrator, and I'm logged in. The curious thing is that this doesnt happen when I use the filters to search an mRNA, I can pick any of the mRNAs listed in the results table, click on it, and it takes me to the mRNA page. 

Any help on this? Thanks!

**Comment by shawnawsu** [comment]
That sounds very odd. In the table results what are the urls of the links that give you the access denied result?

**Comment by kyrenya** [comment]
Hi! Great clue! 
So I didnt know that the order in these elements (pic)
![image](https://user-images.githubusercontent.com/43243429/55241681-7dddac00-5233-11e9-9eb7-cf7ba6e0a12f.png)
is key to decide where the link of the feature points at: 
issue solved just by ensuring that entity ID is the first in the list. 

Thanks!

**Comment by shawnawsu** [comment]
Great! Ok for me to close out this issue?

**Comment by kyrenya** [comment]
yes! Thx!

**Comment by mario-lopez-c** [comment]
Hi! I wonder if you can help me with an issue...
I have uploaded sequences for an organism, like show the next pic:
![image](https://user-images.githubusercontent.com/45463665/114902967-5343f900-9de4-11eb-9e7e-d37d20108586.png)
So, I want to click on each feature to redirect me to its page. But I don't know how to do it, if I click, I get this page: 
![image](https://user-images.githubusercontent.com/45463665/114903338-b5046300-9de4-11eb-83d7-e0e2a844d02e.png)
And if I change the link path of the field, like this: 
![image](https://user-images.githubusercontent.com/45463665/114904549-fa756000-9de5-11eb-8417-4468567458a2.png)
I get access denied:
![image](https://user-images.githubusercontent.com/45463665/114904704-1f69d300-9de6-11eb-856a-c09d8e121019.png)
I would appreciate if you could help me solve this, thanks

**Comment by spficklin** [comment]
HI @mario-lopez-c I'm not familiar with this "Feature User Search" view. Is this a custom view you've made?

**Comment by spficklin** [comment]
Oh, nevermind... I am familiar with it. That's a Legacy view.  Do you need to have the legacy feature module enabled?

**Comment by mario-lopez-c** [comment]
Hi @spficklin! Yes, I guess that is that, How can I enable it?
The legacy view that I chose, is one of these:
![image](https://user-images.githubusercontent.com/45463665/114915160-3a8e1000-9df1-11eb-8f95-e6b03376c220.png)

**Comment by laceysanderson** [comment]
Closing this as stale.
