### ISSUE TITLE
Warning error during adding additional value to multifield

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#915]
Hi guys, so I'm experiencing the following error when trying to add an additional value to a text multifield within tripal

` Notice: Undefined offset: 1 in chado_linker__prop_widget->form() (line 55 of 
/var/www/html/sites/all/modules/tripal/tripal_chado/includes/TripalFields/chado_linker__prop/chado_linker__prop_widget.inc).`

Users are reporting the error but it seems to not affect saving the form (which is good). Any ideas on what could be causing this? I've traced back the error line to:

`$record_id` = $form_state['values'][$field_name]['und'][$delta]['chado-' . $field_table . '__' . $pkey];`

Is this a known issue with Tripal and if not, how do I generate this value manually to resolve the issue? Any advice would be appreciated.

Thanks!

Tagging @spficklin @bradfordcondon @shawnawsu @mestato

**Comment by shawnawsu** [comment]
Hi Risharde,

I don't know if this is a known issue in Tripal, I don't think I've seen other tickets about it but I might have missed them.

Is this problem happening only when updating existing content? Are you using AJAX to set values in the form?

If you're working on a production site you should have error message turned off, it's best practice.

-s

**Comment by spficklin** [comment]
@risharde.  In the process of trying to duplicate the problem I see there is something wrong here with saving new properties.  I'll add this to be fixed for v3.2 release.

**Comment by laceysanderson** [comment]
@spficklin do you remember what the problems with saving new properties are? Descriptions would allow others to fix the problems -time permitting.

**Comment by laceysanderson** [comment]
Not able to replicate thus assuming it's been fixed since this is an old issue. If you run into this problem in the current dev version please comment here with more details.
