### ISSUE TITLE
Powered by Tripal block not displayed correctly on pages with existing path prefix

### ISSUE THREAD

**Issue by mdondrup** [tripal/tripal#918]
## BUG/ERROR report

This is just a minor issue affecting the Powered by Tripal block, but it might cause hard to debug race conditions on pages that contain ajax calls and include this block as a footer (in particular when using extension code that uses $_SESSION variables). 

### System information

* Tripal Version: 7.x-2.x I just noticed that this only affects 2.x! 
* Drupal Version: not relevant
* PostgreSQL Version: not relevant
* PHP Version: 7.1

### Issue description

The Tripal logo is not displayed correctly on pages that include an existing path prefix in their URLS (e.g. /search) 

The following line should be changed to yield the absolute image path (/sites/all/modules/...), not the relative one:
 
https://github.com/tripal/tripal/blob/aaea04188a2b6292a31c32ea905b83aec96fdf58/tripal/tripal.module#L688

 `'#markup' => '<a href="http://tripal.info"><img border="0" src="/' . drupal_get_path('module', 'tripal') . '/theme/images/' . $image . '"></a>', 
`

#### Steps to reproduce

- Activate the 'Powered by Tripal' block 
- navigate to https://yoursite/search/ 

The logo is not displayed, but instead a web server thread will be loading until request timeout because of the incorrect image request URL sent to site search: /search/sites/all/modules/tripal/tripal_core/theme/images/powered_by_tripal_small.png 

#### Error messages and screenshots

Screenshots from before and after changing to absolute path, displaying the block from: /search/gene

![image](https://user-images.githubusercontent.com/893151/55328872-a52fb580-548d-11e9-8603-de5f2f05da3b.png)
![image](https://user-images.githubusercontent.com/893151/55328926-c85a6500-548d-11e9-87f7-d58d547fea49.png)

**Comment by bradfordcondon** [comment]
this seems straight forward to me, i'd welcome a PR to fix

**Comment by mdondrup** [comment]
Sorry, this is only in 2.x not 3.x. In 3, $base_path is used which does give the correct path.
