### ISSUE TITLE
Some more warning errors during submitting custom TripalEntity

### ISSUE THREAD

**Issue by risharde** [tripal/tripal#919]
Hi guys, also received the following repeatable errors with Tripal 3 (seems to be the latest at the time of writing but nearly sure this happens in older v3 tripal as well) and have some questions. The following seems to happen on submitting the form for Tripal Contact Profile (our customized contact TripalEntity). It seems I might not be generating the $field in an array format and throwing a text string at it. Can you advise me on what $field array should contain so I can fix this or if it's something else that might be causing it? It doesn't seem to affect the writing of the field to the database but I'm uncertain what's going on here as well. Want to get rid of all these warnings. Please advise! Thanks!

@spficklin @mestato @shawnawsu @bradfordcondon 

> 
    Warning: array_key_exists() expects parameter 2 to be array, string given in tripal_field_is_empty() (line 146 of /var/www/html/sites/all/modules/tripal/tripal/api/tripal.fields.api.inc).
    Warning: array_key_exists() expects parameter 2 to be array, string given in tripal_field_is_empty() (line 146 of /var/www/html/sites/all/modules/tripal/tripal/api/tripal.fields.api.inc).
    Warning: Invalid argument supplied for foreach() in tripal_chado_field_storage_write_merge_fields() (line 499 of /var/www/html/sites/all/modules/tripal/tripal_chado/includes/tripal_chado.field_storage.inc).
    Warning: array_key_exists() expects parameter 2 to be array, string given in tripal_chado_field_storage_write_merge_fields() (line 519 of /var/www/html/sites/all/modules/tripal/tripal_chado/includes/tripal_chado.field_storage.inc).

**Comment by bradfordcondon** [comment]
I'm thinking that the problem was changing the cardinality of fields directly instead of using the `field_info_instance` API.

In general i encourage you to use the `hook_field_info` and `hook_bundle_instances_info` hooks to attach fields to bundles: theres [a chapter in the guide here](https://tripal.readthedocs.io/en/latest/dev_guide/custom_field/create_instance.html).  It should prevent you from running into some of these errors.

**Comment by spficklin** [comment]
There's not been any additional messages on this so I'm going to close it out. Please comment if more is needed.
