### ISSUE TITLE
add all contributors section and bot to acknowledge project contributors?

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#933]
The spec-

https://allcontributors.org/

The idea- 

People who contribute to Tripal get to be acknowledged in a cute little graphic at the bottom of the README.  Maintaining/creating it is super easy thanks to the bot. 

I put it up on one ouf or modules to demo:

https://github.com/tripal/tripal_analysis_expression#contributors

![image](https://user-images.githubusercontent.com/7063154/56908494-6b45d500-6a74-11e9-9804-d2ddd7684bbe.png)

Advantages:

- Acknowledge non-coder contributions, such as:
    - bug reports
    - grant writing
- simple badge shows contributor count
- easy to use
- big project so not likely to go away

Disadvantages

- clutter README?
- one more feature?
- overlap with tripal.info and/or what about institutions?

**Comment by laceysanderson** [comment]
I'm definitely in favour of this functionality. 

I love that tripal.info shows the contributing organizations since that is succinct and visual for tripal.info. I feel that adding this section to our github readme reaches a different audience; specifically, tripal.info reaches the PIs and planners, whereas, github reaches those asked to implement Tripal. This section will hopefully make the "implementer's" feel welcome and like their contributions (even to the issue queue) will be recognized and appreciated. It also validates the section on Tripal.info by showing the people behind the organization.

**Comment by bradfordcondon** [comment]
no negative thoughts so im going to init it.  we can almost remove and disable if we dont like it.
I'm actually not sure what all icons to add for PMC members so im going to start small

**Comment by bradfordcondon** [comment]
@all-contributors please add @spficklin  for code

**Comment by laceysanderson** [comment]
Ooo! Theres a `projectManagement` icon that we could use for PMC members :-D

**Comment by bradfordcondon** [comment]
i did the first round via the command line #937 .  I added projectManagement for PMC.  it would be cool to also acknowledge advisory committee.  Grantwriters too.

**Comment by spficklin** [comment]
Just thought of something. This requires that all contributors have GitHub accounts. But some folks, especially the folks who find funding may not.... we don't want to leave folks off because they don't have github accounts.

**Comment by bradfordcondon** [comment]
we could hardcode them in.  Having a GitHub account [isn't a requirement of the spec](https://allcontributors.org/docs/en/specification#mandatory).  It just makes it much much easier.

**Comment by almasaeed2010** [comment]
@all-contributors please add @almasaeed2010 for code

**Comment by spficklin** [comment]
Some additional contributions:

@all-contributors please add @shawnawsu for content,doc,code,review
@all-contributors please add @jlwegrzyn for fundingFinding
@all-contributors please add @ekcannon for ideas,eventOrganizing
@all-contributors please add @mestato  for eventOrganizing
@all-contributors please add @spficklin for eventOrganizing

**Comment by spficklin** [comment]
@all-contributors please add @shawnawsu for content,doc,code,review

**Comment by spficklin** [comment]
@all-contributors please add @shawnawsu for content ,doc, code, review
@all-contributors please add @jlwegrzyn for fundingFinding
@all-contributors please add @ekcannon for ideas, eventOrganizing
@all-contributors please add @mestato for eventOrganizing
@all-contributors please add @spficklin for eventOrganizing

**Comment by spficklin** [comment]
@all-contributors please add @shawnawsu for content, doc, code, review
@all-contributors please add @jlwegrzyn for fundingFinding
@all-contributors please add @ekcannon for ideas, eventOrganizing
@all-contributors please add @mestato for eventOrganizing
@all-contributors please add @spficklin for eventOrganizing

**Comment by spficklin** [comment]
oh goodness gracious....

@all-contributors please add @shawnawsu for content, doc, code, review

**Comment by spficklin** [comment]
@all-contributors please add @jlwegrzyn for fundingFinding

**Comment by spficklin** [comment]
@all-contributors please add @ekcannon for ideas, eventOrganizing

**Comment by spficklin** [comment]
@all-contributors please add @mestato for eventOrganizing

**Comment by spficklin** [comment]
@all-contributors please add @spficklin for eventOrganizing

**Comment by spficklin** [comment]
@all-contributors please add @laceysanderson for eventOrganizing

**Comment by spficklin** [comment]
@all-contributors please add @bradfordcondon for eventOrganizing

**Comment by spficklin** [comment]
So, I have learned from this, you should only do this one at a time, and merge the PR before issuing another!

**Comment by bradfordcondon** [comment]
im closing this issue.  if anyone wants to keep using it as a scratch pad adding users, they can continue to do so.

**Comment by spficklin** [comment]
@all-contributors please add @par12005 for code

**Comment by spficklin** [comment]
@all-contributors please add @katherynbuble for code

**Comment by spficklin** [comment]
@all-contributors please add @srobb1 for code

**Comment by spficklin** [comment]
@all-contributors please add @risharde for code

**Comment by spficklin** [comment]
@all-contributors please add @srobb1 for code

**Comment by spficklin** [comment]
@all-contributors please add @katherynbuble for code

**Comment by spficklin** [comment]
@all-contributors please add @srobb1 for code
