### ISSUE TITLE
Performance issues with fields.

### ISSUE THREAD

**Issue by spficklin** [tripal/tripal#939]
### System information

* Tripal Version: 3.x
* Drupal Version: 7.x
* PostgreSQL Version:
* PHP Version:

### Issue description

1) When fields use code that also has AJAX the field code won't run properly if the field was loaded using AJAX.  For example cv_xray module field that is attached to an organism.   

2) Also, Tripal may load fields that are hidden from display are also loaded.

**Comment by laceysanderson** [comment]
@spficklin could you describe this further? Do you have a potential solution in mind?

**Comment by laceysanderson** [comment]
Closing this as there is not enough detail available.
