### ISSUE TITLE
search missing info

### ISSUE THREAD

**Issue by kyrenya** [tripal/tripal#941]
Hi there! 
When using my search forms, now I dont have any information in some of the results fields: 

![image](https://user-images.githubusercontent.com/43243429/57768145-e9f07280-7702-11e9-9137-a7fa1391606f.png)

I don't know if this has something to do with views module, but anyway, its updated and patched! 
Any help? 

(Using last version of drupal core as well). 

Thanks a lot

**Comment by laceysanderson** [comment]
Hi @kyrenya, are the fields behind `Gene` and `Product` displayed on your Tripal Content page (i.e. enabled on Admin > Structure > Tripal Content Types > mRNA > Manage Display)? If not, it needs to be in order to see it in views to ensure the same data is shown across services.

**Comment by kyrenya** [comment]
solved! It was that!  Thanks a mil!!

**Comment by laceysanderson** [comment]
Awesome! Glad it worked :-)
