### ISSUE TITLE
Tripal Installation Profile

### ISSUE THREAD

**Issue by laceysanderson** [tripal/tripal#95]
We need to remember to make Tripal Installation profiles for Tripal3! This would make Tripal way easier to set-up and could provide more guidance to new users.

I think these should be geared towards subject area (e.g. Genomic, Breeding, etc.) and include: 
- enable Tripal modules (pre-select those relevant to the particular area), 
- install Chado,
- load relevant ontologies,
- include relevant extension modules,
- configuration screens.

The intent is that after the installation process you should have a full functional Tripal site that you just need to load data into. It would also be nice to use a better looking default theme ;-).

**Comment by shawnawsu** [comment]
Can we start building out this doc with the different installation profiles that are needed: https://docs.google.com/document/d/1XxpyimeaZWv4axm0-YY7VzLB7_-HZWIhb1xuW6btbwc/edit?usp=sharing

I would suggest we publish some content (maybe a few small content types, like organism) to demonstrate what the site can do. Maybe we only do that for a demo site install profile.

**Comment by laceysanderson** [comment]
I've started (not complete) 3 profile specs: generic, genomic, breeding. I think that all should share the same theme with the main difference being extension modules and content types.

When it comes to demo functionality and demo content, I think it would be helpful to have a step in the installation for all 3 profiles that let's them say: "Yes, load demo content" :-)

I would also like to see the profiles include configuration... For example, if Tripal BLAST is included there are configuration options to set.

**Comment by laceysanderson** [comment]
There should be enough information in the GoogleDoc for you to start :-) It's not complete but it's safe to assume all items in black will be staying.

**Comment by shawnawsu** [comment]
Is there a preference for theme? I'm inclined just to throw a bootstrap or foundation theme on. If there is a drupal theme that works better for science sites please let me know, I'm still new to this!

**Comment by laceysanderson** [comment]
Not a huge preference :-) It seems that Tripal admin prefer to 
- have excessive top menus
- like to colour code their sites based on crop/organism. 
- I love fluid width and think it's important b/c you can show more data but that said, KnowPulse is the only fluid-width tripal site and it can be a burden development wise. 
- It should be a more modern theme then Bartik b/c not all Tripal sites will bother to change more then the colours.
- It shouldn't read as a business site and a slideshow at the top is not desirable.
- It should have lots of flexibility to be changed through the interface.

I'm liking Scholarly Lite (project: https://www.drupal.org/project/scholarly_lite; Demo: http://demo.drupalizing.com/?theme=scholarly-lite) for it's simplicity and features but a better frontpage & drop-down menus would be helpful.

This theme is a good one for menu/frontpage (http://demo.weebpal.com/#education) though I think the theme as a whole is too distracting and the rotating header makes me want to scream. Specifically, the support for excessive sub-items and pictures within menu's is great so maybe we could just add an extension module to the other theme to accomplish that?

**Comment by shawnawsu** [comment]
We've moved this into an install drush command. We can build out different install drush commands as needed. So I am going to close this out and we can open single tickets for each new drush command we want to create.
