### ISSUE TITLE
questions about uploading files

### ISSUE THREAD

**Issue by theBowja** [tripal/tripal#956]
Hi I have a few questions and I first have to mention that I don't have a background in biology.

I have a gff file that I wish to upload via the gff3 file loader however there may be problems with my gff file. More specifically, the ID attribute for both gene and mRNA features are the same.
Example: gene and mRNA both have the ID=002606F-0.0 and mRNA has parent=002606F-0.0
![image](https://user-images.githubusercontent.com/12958524/59942215-0df35200-942d-11e9-95d3-f3e329b5dbc0.png)

Furthermore I have two other fasta files (one protein, one mRNA) that contain the ID 002606F-0.0
mRNA:
![image](https://user-images.githubusercontent.com/12958524/59942955-0d5bbb00-942f-11e9-9543-362aeda0c3d8.png)
protein:
![image](https://user-images.githubusercontent.com/12958524/59942985-26646c00-942f-11e9-83e6-645929f54a8f.png)

I want to ask what are the best changes I should make to my files in order for everything to be correct for Tripal. Are the extra attributes in the gff such as '_AED' also stored somewhere? In the fasta files, are the annotations after the ID stripped during loading?

**Comment by spficklin** [comment]
Hi @theBowja.  That's a great question.   Sometimes GFF/FASTA files do require some massaging because to make them compatible.  I see you closed it the issue. Were you able to answer the question on your own?

**Comment by theBowja** [comment]
I only resolved my problem with IDs. Turns out my gff file was a stripped version so just need to unstrip "-mRNA-1" from the ID for mRNA (and also from all the parent attributes). From there I just need to add "-mRNA-1" to every ID in the fasta file. Not sure if the IDs of the CDS being identical will cause problems though.

I still want to ask the last two questions: Are the extra attributes in the gff such as '_AED' also stored somewhere? In the fasta files, are the annotations after the ID stripped during loading?

**Comment by bradfordcondon** [comment]
hi @theBowja , extra attributes are going to end up as annotations and will be displayed on the feature's page (with some configuration).  The parser stores it in featureprop or feature_cvterm depending on the annotation (and i think AED goes in featureprop.

Assuming Tripal 3, once you've run the importer, if you check for new fields, it should create new featureprop fields for them.

**Comment by theBowja** [comment]
thanks, I found those extra attributes
