### ISSUE TITLE
deleting uploaded data

### ISSUE THREAD

**Issue by theBowja** [tripal/tripal#957]
Let's say that I recently uploaded a fasta file or gff file that I want to undo. How would I go about doing that?

Thanks

**Comment by theBowja** [comment]
I'm thinking of creating a backup before each upload I do. Would this suffice or is there a better way?

**Comment by btski** [comment]
Depends on upload size. If you track inserted records (option for bulk loads), you can just revert the upload. However, the track upload option can cause issues for largish uploads, as it uses memory inefficiently (from my experience). If you max memory while uploading, the upload breaks. Don't think you can revert at that point, making the memory difficult to free.

Alternatively, you can manually remove the records using SQL from the Chado schema. Wouldn't advise doing this unless you understand the schema structure fairly well to avoid accidentally removing default table values (such as all the different cvterm definitions).

Your proposed solution will work. Just may not be the most straightforward approach.

**Comment by spficklin** [comment]
Unfortunately, there's not a good way to remove data once it's in using core Tripal.  I'm tagging this as a feature request as this is something we probably should look into.  

But I wonder if the [Tripal Headquarters](https://tripal-hq.readthedocs.io/en/latest/introduction.html)  module might help. @bradfordcondon or @almasaeed2010 what do you think?

**Comment by bradfordcondon** [comment]
Tripal headquarters is for creating "draft" records with an end-user focus- letting users propose chado records that need to be approved before they go into Chado.  It sounds like @theBowja wants to rollback FASTA/GFF imports which is pretty different- headquarters would be more for letting users propose an anaysis record and upload/link the FASTA file, that the admin would later load.

Backups are a fairly straightforward solution.  SQL might be easier.    If you can clear out an entire organism, then the below query works. Heck maybe just delete teh organism and cascade instead.  If you need something more nuanced you can work something out from the [feature schema](https://chado.readthedocs.io/en/rtd/_static/schemaspy_integration/tables/feature.html)

```
DELETE FROM chado.feature where organism_id = x  CASCADE
```


PS you can use drush to access the SQL command line easily.  `drush sql-cli`

**Comment by bradfordcondon** [comment]
hi @theBowja did any of the responses help you?  Any more questions before i close this?

**Comment by theBowja** [comment]
Unfortunately I didn't have the time to figure this one out. I'll close this since I probably won't be working on this question anymore.
