### ISSUE TITLE
Sequence Ontology Loader Fails to Update Existing Records

### ISSUE THREAD

**Issue by almasaeed2010** [tripal/tripal#97]
Hello all,

Attempting to update our sequence ontology causes the following error:
```
Calling: tripal_cv_load_obo_v1_2_id(8, 1537)
Downloading URL http://purl.obolibrary.org/obo/so.obo, saving to /data/tmp/obo_CwZJ4K

NOTE: Loading of this OBO file is performed using a database transaction. 
If the load fails or is terminated prematurely then the entire set of 
insertions/updates is rolled back and will not be found in the database

Step 1: Preloading File /data/tmp/obo_CwZJ4K
Parsing Line 22251 (100.00%). Memory: 44,381,776 bytes.
Step 2: Loading type defs...
RIGHT HERE: inserting variant_of with name SOWD tripal_core: chado_insert_record; Cannot insert duplicate record into cvterm table: Array                                                                                                           [error]
(
    [cv_id] => 7
    [name] => variant_of
    [definition] => A' is a variant (mutation) of A = definition every instance of A' is either an immediate mutation of some instance of A, or there is a chain of immediate mutation processes
linking A' to some instance of A. [SO:immuno_workshop]
    [dbxref_id] => 195913
    [is_obsolete] => 0
    [is_relationshiptype] => 1
)

ERROR (TRIPAL_CORE): chado_insert_record; Cannot insert duplicate record into cvterm table: Array
(
    [cv_id] => 7
    [name] => variant_of
    [definition] => A' is a variant (mutation) of A = definition every instance of A' is either an immediate mutation of some instance of A, or there is a chain of immediate mutation processes linking A' to some instance of A. [SO:immuno_workshop]
    [dbxref_id] => 195913
    [is_obsolete] => 0
    [is_relationshiptype] => 1
)

[site http://160.36.205.61:8095] [TRIPAL ERROR] [TRIPAL_CORE] chado_insert_record; Cannot insert duplicate record into cvterm table: Array(    [cv_id] => 7    [name] => variant_of    [definition] => A' is a variant (mutation) of A = definition every instance of A' is either an immediate mutation of some instance of A, or there is a chain of immediate mutation processes linking A' to some instance of A. [SO:immuno_workshop]    [dbxref_id] => 195913    [is_obsolete] => 0    [is_relationshiptype] => 1)
WD tripal_cv: Failed to insert the relationship term: variant_of (cv: sequence db: SO)                                                                                                                 [warning]
[site http://160.36.205.61:8095] [TRIPAL WARNING] [TRIPAL_CV] Failed to insert the relationship term: variant_of (cv: sequence db: SO)
WD T_obo_loader: Cannot add the term variant_of                                                                                                                                                        [error]
[site http://160.36.205.61:8095] [TRIPAL ERROR] [T_OBO_LOADER] Cannot add the term variant_of
Drush command terminated abnormally due to an unrecoverable error. 
```

My understanding is that the record should be updated if it exists but tripal_cv is not finding the existing record and attempts to add a new one causing the duplicate records error.

Any help on this matter is appreciated. Thanks!

**Comment by spficklin** [comment]
Hi @almasaeed2010 yes, it should perform an update rather than an insert.   What is the OBO you're trying to load?   Have you loaded it before successfully and now you're trying to update or is this message from the first attempt to load it?

**Comment by spficklin** [comment]
Oh, and which verion of Tripal is this?  v2.1 or development 2.x or 3.x branch?

**Comment by almasaeed2010** [comment]
Hello Stephen,

This is the latest stable 2.1 version. We were attempting to update the sequence ontology that's provided by this URL: http://purl.obolibrary.org/obo/so.obo. When attempting on a fresh install, everything works fine. However, updating a preexisting term is what's causing the issue.

Thanks!

**Comment by spficklin** [comment]
I've tested re loading the SO on an existing database and I have no issues....  Could you do me a favor and run this SQL query:

> SELECT CV.name as cvname, DB.name as dbname
> FROM dbxref DBX
>   INNER JOIN cvterm CVT on CVT.dbxref_id = DBX.dbxref_id
>   INNER JOIN cv CV on CV.cv_id = CVT.cv_id
>   INNER JOIN db DB on DB.db_id = DBX.db_id
> where DBX.dbxref_id = 195913

**Comment by almasaeed2010** [comment]
That's what I got when running the query:
```sql
SELECT CV.name as cvname, DB.name as dbname
FROM chado.dbxref DBX
INNER JOIN chado.cvterm CVT on CVT.dbxref_id = DBX.dbxref_id
INNER JOIN chado.cv CV on CV.cv_id = CVT.cv_id
INNER JOIN chado.db DB on DB.db_id = DBX.db_id
where DBX.dbxref_id = 195913;
 cvname | dbname 
--------+--------
(0 rows)
```

**Comment by spficklin** [comment]
Wow, this got away from us.  Does this problem still exist for you?

**Comment by almasaeed2010** [comment]
I haven't attempted to load it again but I think the issue persists since issue #120 seems to address a similar "duplicate unique value" and null values.

I'll close this issue and follow up on #120.

**Comment by spficklin** [comment]
Actually let's keep this one open as it may be two different issues.  At least that way we can be certain that if #120 is fixed that we need to check this as well to make sure it's fixed too..

**Comment by mpoelchau** [comment]
We're having the same issue, and I get the same result as @almasaeed2010 with the query listed above. Has anyone else been able to figure this out?

**Comment by almasaeed2010** [comment]
this problem apparently still persists in Tripal2 but not on Tripal3. @mpoelchau is going to attempt to load it using tripal 3 since v2 isn't working.

**Comment by almasaeed2010** [comment]
The obo loader has been completely reworked. I think we can close this issue. Please reopen if you think it's worth keeping.

Thanks!
