### ISSUE TITLE
Problems of displaying functional annotations in tripal3

### ISSUE THREAD

**Issue by songtaogui** [tripal/tripal#974]
Hi, 

I have had some problems when uploading Functional Annotation data (Blast, GO & Interpro) to tripal3. The uploading step was following the [offical tutorial](https://tripal.readthedocs.io/en/latest/user_guide/example_genomics/func_annots.html), and no error occured during the uploading. 

However, after uploaded the annotation data, they can be searchable in the `search gene` chardo search:

>![image](https://user-images.githubusercontent.com/14274330/60856092-9731c380-a238-11e9-80f4-218566d5efd8.png)

but no `InterProScan` or `Homology(Blast)` tag was displayed in the detailed gene page:

>
![image](https://user-images.githubusercontent.com/14274330/60856413-b11fd600-a239-11e9-8f5b-982033755f2b.png)

I have tested the same data on tripal 2, and everything works fine.
Do I miss something?

Any suggestion would be appreciated.

Thank you.

Best wishes

Songtao Gui

**Comment by bradfordcondon** [comment]
hello, did you follow the [setup section](https://tripal.readthedocs.io/en/latest/user_guide/example_genomics/func_annots/setup.html) for this guide?  Specifically-

- did you remember to press the `check for new fields` button on the gene bundle configuration page?
- did you remember to **enable the display** of the new fields in the display configuration page?


your gene bundle display page should look something like this from the guide, can you confirm?

![image](https://user-images.githubusercontent.com/7063154/60890022-6b0e4680-a228-11e9-891f-7dbefe799487.png)

**Comment by songtaogui** [comment]
Hi，@bradfordcondon

Thank you for your kindly reply. We have tried to `check for new field` and it said `No new fields were added`.

**Comment by bradfordcondon** [comment]
hi @songtaogui can you please share a screenshot of your field display config (the far right tab of the bundle) so we can confirm these fields are configured to  display correctly?

**Comment by songtaogui** [comment]
hi @bradfordcondon , sorry for the late reply. The problem was solved, it is because that the uploaded annotation was based on protein IDs rather than the gene IDs. 

Sorry for the careless and thank you for your kindly help.
