### ISSUE TITLE
Get the Entity_ID from the Feature_ID (in the features table) in V3.2

### ISSUE THREAD

**Issue by webfaqtory** [tripal/tripal#975]
I am converting our search module from V2 to V3.

In the V2 the version the search returns a list of feature_id(s) from The Chado features table and then loads the node with:

```
$nid = chado_get_nid_from_id('feature', $feature_id);
node = node_load($nid);
```
We then create a link to the Feature's page with:

`l($node->title, 'node/' . $node->nid) ;`

My question is: In V3, how do I get the link to the Features page from the feature_id of the Chado features table?

**Comment by bradfordcondon** [comment]
https://github.com/tripal/tripal/blob/82e052df1c3d912d8616756af735a262067ee893/tripal_chado/api/tripal_chado.entity.api.inc#L51-L68

So it is simply: `chado_get_record_entity_by_table('feature', $feature_id)`


Then to link, you can link to `/bio_data/x`.  If im not mistaken, the `entity` also has a `title` key just like node.

**Comment by bradfordcondon** [comment]
hi @webfaqtory did this answer your question?  If not please let us know, otherwise ill close out this issue.

**Comment by webfaqtory** [comment]
Hi Bradford,

Yes all good. Many thanks
