### ISSUE TITLE
indexing items immediately

### ISSUE THREAD

**Issue by theBowja** [tripal/tripal#979]
Hi.

I have an custom index on two bundles: mRNA and Transcript (I added this one). When I publish tripal content like mrna or transcript, the index does not show that there are any new things to index. It'll say something like 0/0 indexed. I have to disable then enable the index in order for those published content to show up for indexing.

Within the edit tab for adding an index there is an option "Index items immediately". I would like to either get this working or figure out how to make indexing as a tripal job instead. Currently I have to click "Index now" in the browser and leave it open which is very tiring if there is a lot of records to index.

Does anyone have any insight to my problem or where I should start? I'm using tripal 7.x-3.1.

Thanks

**Comment by bradfordcondon** [comment]
Sounds like you talking about [tripal elasticsearch](https://github.com/tripal/tripal_elasticsearch) integration?  In theory there is a hook that triggers when an entity is published that will index the new entity.  I've created an issue on that module, hopefully someone will be able to look into it.

**Comment by theBowja** [comment]
I do not have elasticsearch module enabled. I am using [Search API](https://tripal.readthedocs.io/en/latest/user_guide/searching/search_api.html). Do you think elasticsearch supports what I'm looking for?

**Comment by theBowja** [comment]
Is there hook for when a publish job ends?

**Comment by spficklin** [comment]
Hi @theBowja.  If I remember correctly, the Search API is quite slow and problematic which is one of the reasons the Tripal ElasticSearch module exists. It works wonderfully well with Tripal v3.  @laceysanderson perhaps remembers the issues we had with the Search API.

**Comment by theBowja** [comment]
Hi. I'm not sure if Tripal ElasticSearch can do what I'm looking for. I want to join the organism, organismprop, feature, and featureprop tables to search and filter: scientific name and common name in organism table, order in organism prop, name in feature table, and description in featureprop table. At first glance, it seems like Tripal ElasticSearch can only index fields from a single table?

**Comment by almasaeed2010** [comment]
Hello @theBowja 

If you can create a Materialized View containing the data you want, ElasticSearch will be able to generate a form for you and index the data from your MView. However, this means that you have find a way to auto-update the mview when data is added and then update the index after the mview is created. I am not sure if it's possible to reach complete autonomy.

**Comment by theBowja** [comment]
hey @almasaeed2010 I'm not sure how to work this out.

I've created the materialized view with
`CREATE MATERIALIZED VIEW keywordsearch AS select etc...`

When I go to Tripal ElasticSearch Create Index and select 'Database Table' for Index type, I don't see my materialized view in select tables.

**Comment by almasaeed2010** [comment]
I think you have to create the materialized view using the Tripal interface at `/admin/tripal/storage/chado/mviews/new` That's where ES looks for mviews.
