### ISSUE TITLE
Possible bug in so__genotype->load($entity)

### ISSUE THREAD

**Issue by par12005** [tripal/tripal#980]
### System information

* Tripal Version: 7.x-3.1
* Drupal Version: 7.67
* PostgreSQL Version: 10.9
* PHP Version: 7.2.19

### Issue description

I am having a problem with the default so__genotype Tripal Field class that comes with tripal_chado. Whenever I add this field to a Tripal Bundle, I don't experience any errors, but all of my Tripal Content with this field shows "no genotypes found", even though I have properly configured the field, my chado linking tables, and the schema(s) for all of the chado tables involved. I will include a patch with this issue which I believe fixes this bug. The change I made is based off of the functionality [here](https://github.com/tripal/tripal/blob/a18b5002e3d1af91c1762809c8ab7aff531401ed/tripal_chado/includes/TripalFields/sbo__phenotype/sbo__phenotype.inc#L120) in the sbo__phenotype Tripal Field class. When I make this change and reload my Tripal Content, the genotypes I expected to see show up when I view the content.

#### Steps to reproduce

1. Add and configure the sbo__genotype Tripal Field to any Tripal Content.
2. Populate chado with data that should associate a genotype with some existing Tripal Content.
3. Publish the Tripal Content.
4. See that no genotypes are found, despite the data existing in chado.

**Comment by par12005** [comment]
patch:
```
diff --git a/tripal_chado/includes/TripalFields/so__genotype/so__genotype.inc b/tripal_chado/includes/TripalFields/so__genotype/so__genotype.inc
index f77f1f0f..72b2e73a 100755
--- a/tripal_chado/includes/TripalFields/so__genotype/so__genotype.inc
+++ b/tripal_chado/includes/TripalFields/so__genotype/so__genotype.inc
@@ -144,7 +144,7 @@ class so__genotype extends ChadoField {
       ],
     ];
     $record = chado_expand_var($record, 'table', $linker_table, $options);
-    $genotype_linkers = isset($record->$linker_table->$fkey_rcolumn) ? $record->$linker_table->$fkey_rcolumn : '';
+    $genotype_linkers = $record->$linker_table;
     if ($genotype_linkers) {
       foreach ($genotype_linkers as $i => $genotype_linker) {
         $genotype = $genotype_linker->genotype_id;
```

**Comment by spficklin** [comment]
This is great @par12005 .  Thanks for contributing.  Are you comfortable enough creating a pull request with this fix? If so, then you will get credit within the GitHub and the Tripal repo for this fix. It also helps us keep track of how many code contributions we get from those outside of the core developers.

**Comment by par12005** [comment]
Thanks @spficklin! I think I can figure out a pull request, is it the same process as creating pull requests for extension module badge updates?

**Comment by spficklin** [comment]
Hi @par12005. Yes I believe it is.  You should be able to make your changes through the GitHub web GUI and submit as a pull request.  Alternatively, you can fork Tripal, make the changes in your fork and then follow instructions in GitHub to push the pull request back to the core Tripal repository.  For simple changes the former is probably easiest, for larger changes the latter would be easier.

**Comment by par12005** [comment]
@spficklin, I created the pull request: #985. Please let me know if there is anything else I can do!

**Comment by spficklin** [comment]
Wonderful thanks! When I get a bit of free time today I'll test it.

**Comment by spficklin** [comment]
I @par12005 .  I merged in your pull request. Thanks for the submission.

I do have a question for you though... specifically how are you getting that field to work on your site?  The reason is that the code in Tripal that would automatically attach that field to a content type (bundle) is commented out. So neither the so__genotype or sbo__phenotype will get attached to a field on it's own and it's not possible to add them to any content type.  I believe the reason is that we originally wanted to make these fields, but there was no consensus on how to store and display these in a general way, so work on them was paused.  Can you describe how you are getting them to work?  

I did merge in the code change, but it's similar to the code in the sbo__phenotype, you say it works for you and since we don't consider those fields completed, I didn't see any harm in it.

**Comment by par12005** [comment]
Thanks @spficklin! Here is the code snippet where I add the so__genotype field to my bundle:
```php
  $genotype_term = chado_get_cvterm(array(
    'name' => 'genotype',
    'cv_id' => array(
      'name' => 'sequence',
    ),
  ), array(
    'include_fk' => array(
      'dbxref_id' => 1,
    ),
  ));

  $info = field_info_field('so__genotype');
  if (empty($info['bundles']['TripalEntity'])) {
    field_create_field(array(
      'field_name' => 'so__genotype',
      'type' => 'so__genotype',
      'settings' => array(
        'storage' => 'field_chado_storage',
      ),
      'storage' => array(
        'type' => 'field_chado_storage',
        'module' => 'tripal_chado',
        'active' => 1,
      ),
    ));
  }

  field_create_instance(array(
    'field_name' => 'so__genotype',
    'entity_type' => 'TripalEntity',
    'label' => 'Genotype',
    'bundle' => $bundle->name,
    'required' => FALSE,
    'settings' => array(
      'user_register_form' => 0,
      'term_vocabulary' => $genotype_term->dbxref_id->db_id->name,
      'term_name' => $genotype_term->name,
      'term_accession' => $genotype_term->dbxref_id->accession,
      'base_table' => 'stock',
      'chado_table' => 'stock_genotype',
      'chado_column' => 'genotype_id',
      'auto_attach' => 1,
      'term_fixed' => 0,
    ),
  ));
```

In this excerpt, the `$bundle` variable comes from:

```php
$bundle = tripal_load_bundle_entity(array('label' => 'Stock'));
```

And the "Stock" bundle is the new Tripal Content Type that I created with `tripal_create_bundle`.

**Comment by spficklin** [comment]
Okay, I see.  So you have your own module and you wrote code to make this happen. Great!  The only thing about those fields is that we never completed them.  I'm glad you found use out of them the  way they are.  But, if we ever do get around to finishing them you may have a problem in that they change on you.... which wouldn't be good.  So to prevent that from happening to you, could you participate in a conversation about those fields?  First,
1.  Could you share how you are storing your genotype/phenotype data in Chado?  What types of genotypes, phenotypes are you storing, etc.
2.  If you'd be willing to help contribute to make these fields active as part of core Tripal that would be well accepted.

**Comment by par12005** [comment]
Yes, this code is part of the [TPPS module](https://github.com/par12005/TPPS). The functions that do the actual storing of genotype/phenotype data can be found in [this file](https://github.com/par12005/TPPS/blob/7.x-1.x/includes/file_parsing.inc). More specifically, phenotype information is stored in the database starting on [this line](https://github.com/par12005/TPPS/blob/7.x-1.x/includes/file_parsing.inc#L53), and genotype information is stored starting on [this line](https://github.com/par12005/TPPS/blob/7.x-1.x/includes/file_parsing.inc#L520).

The content of the data we are storing comes from landscape/popgen genomics studies which associate genotype, phenotype, and/or environmental data with georeferenced trees, for example [this study on TreeGenes](https://treegenesdb.org/tpps_details/accession/TGDR122).

In chado, individual trees are stored in the stock table, and genotypes are stored in the genotype table. In the case of the example above, I believe our genotype data is diploid SSR data, so the genotype data is linked to the stock through a `chado.stock_genotype` linking table, as well as `chado.genotype_call`, which is a custom table we have that compactly stores genotype calls. The genotype field in question uses the `chado.stock_genotype` linking table to find associations between genotypes and stocks.

Let me know if there is any other information I can provide that would be helpful. The mechanism that TPPS uses to actually put data in chado (featured in [this file](https://github.com/par12005/TPPS/blob/7.x-1.x/includes/create_record.inc)) is not from the chado query API and can be kind of confusing, but I would be happy to walk you through that as well if you're interested.

**Comment by bradfordcondon** [comment]
thanks for the contribution
