### ISSUE TITLE
404 not found when uploading files

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal#981]
### System information

* Tripal Version: 7.x-3. latest
* Drupal Version: 7.64
* PostgreSQL Version: 9.5.14
* PHP Version: 7.1

### Issue description
I'm struggling with a error with all file uploads handled by the tripal importer class. 
the upload dialog simply returns Not Found, with two urls in the network tab giving a 404:

```
GET https://mysiteroot.com/tripal/upload/0-tripal_importer/amel_cds.fasta/check/?module=tripal&chunk_size=2048000&file_size=8791

PUT  https://mysiteroot.com/tripal/upload/0-tripal_importer/amel_cds.fasta/save/0 
```

the files are not added to my site/default/files.... I tested Drupal's standard file field attached to analysis and i can upload files with that OK, so i dont think its a file system permission issue (although i ran the Drupal file permission drush helper to try and rule that out).

**Comment by spficklin** [comment]
Does your `admin/config/media/file-system` page look like this:

![image](https://user-images.githubusercontent.com/1719352/62956840-79f89380-bda8-11e9-8847-d32b824edcfe.png)

**Comment by bradfordcondon** [comment]
yes, it did originally.  I was following some suggestions and changed the temp directory to a new temp deirectory, tmp2 , but this didn't work.  I also have private files pointed at  `/var/www/private`

**Comment by spficklin** [comment]
@bradfordcondon that GET and PUT URLs look okay to me.  I just checked that I'm seeing the same thing on a test upload.  Did you check the Apache log file to see if there are any messages there?

**Comment by bradfordcondon** [comment]
this is a [known issue](https://github.com/galaxy-genome-annotation/docker-tripal/issues/41) with how the docker Tripal stack hosts the site at `somewhere.com/tripal`.  hopefully i'll resolve there eventually but not a Tripal issue so closing.
