### ISSUE TITLE
Custom field not displaying

### ISSUE THREAD

**Issue by webfaqtory** [tripal/tripal#982]
We have a Custom field that displays a panel containing a jBrowse genome browser that is working fine. However if 'Hide empty fields' is checked on the the bundle's edit page, our menu link & panel never shows. I'm sure we are missing some simple setting in hook_bundle_instances_info() or the ChadoField sub class but can't find anything. Help please.

**Comment by bradfordcondon** [comment]
your field probably doesn't have the `value` set.  In the base field class (not the formatter) make sure that the field value is set.  Something like ` $entity->{$field_name}['und'][0]['value']`.  If the field doesnt use load any data yo ucan simple set it to true or 1.

If that doesnt fix your issue please link the field code so we can better troubleshoot.

**Comment by webfaqtory** [comment]
Many thanks, all sorted now
