### ISSUE TITLE
Tripal 3 error when loading GFF3

### ISSUE THREAD

**Issue by jhumann** [tripal/tripal#993]
### System information
* Tripal Version: 7.x-3.2
* Drupal Version: 7.67
* PostgreSQL Version: 10.10
* PHP Version: 7.0.33

### Issue description
I was loading a GFF3 file of genome scaffolds and the GFF loaded fine, but during the final steps of the process, I got this error message:

Remapping Chado Controlled vocabularies to Tripal Terms...
WD tripal_chado: PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "arraydesign" does not exist                                    [error]
LINE 1:            SELECT platformtype_id           FROM  arraydesig...
                                                          ^:            SELECT platformtype_id           FROM { arraydesign}           GROUP BY
platformtype_id         ; Array
(
)
in chado_query() (line 1790 of /local/sites/www.pulsedb.org/drupal-7.41/sites/all/modules/tripal/tripal_chado/api/tripal_chado.query.api.inc).
FAILED: Rolling back database changes...

This problem appears to be related to the 'chado_query' API change in Tripal 3.2 and Tripal saying that a database table is not found when it does exist in our database.

**Comment by laceysanderson** [comment]
Hi @jhumann, I believe this was fixed in this PR: https://github.com/tripal/tripal/pull/954. To test, you could either update to the development version of Tripal or try to apply the patch from that PR: https://patch-diff.githubusercontent.com/raw/tripal/tripal/pull/954.patch

**Comment by jhumann** [comment]
@laceysanderson , that did the trick.  My file loaded fine.  Thanks a bunch!
