### ISSUE TITLE
About  ERROR:  relation "arraydesign" does not exist 

### ISSUE THREAD

**Issue by EugeneKim76** [tripal/tripal#994]
Dear all,
I'm now installing Tripal 3.0 as in the manual of 'tripal.info'.
However, after 'prepare both Drupal and Chado' process. the error message below was shown.

WD tripal_chado: PDOException: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "arraydesign" does not exist                                                                                                                                                   [error]
LINE 1:            SELECT platformtype_id           FROM  arraydesig...
                                                          ^:            SELECT platformtype_id           FROM { arraydesign}           GROUP BY platformtype_id         ; Array
(
)
 in chado_query() (line 1790 of /srv/www/htdocs/sites/all/modules/tripal/tripal_chado/api/tripal_chado.query.api.inc).
FAILED: Rolling back database changes...

I installed all modules shown in 'tripal.info' before that process.
Is there anyway to solve the error? 

Best,

**Comment by bradfordcondon** [comment]
If you dont [have the arraydesign table](https://chado.readthedocs.io/en/rtd/_static/schemaspy_integration/tables/arraydesign.html), then something is wrong with your Chado setup.

- Are you installing Tripal from scratch, or upgrading from Tripal 2?  If installing, are you following the rapid or step-by-step guide?  See the guides at: https://tripal.readthedocs.io/en/latest/user_guide/install_tripal.html

Can you paste the full error message/the message above so we can have context of when the problem occurs?

**Comment by almasaeed2010** [comment]
I think this issue is caused by a typo that we've fixed here https://github.com/tripal/tripal/pull/954

Specifically, notice the space before `arraydesign` in `SELECT platformtype_id FROM { arraydesign} GROUP BY platformtype_id `

Did you download tripal from github or drupal (using drush or other methods)?

**Comment by EugeneKim76** [comment]
I downloaded tripal using command line below.
drush pm-download tripal
I think the error is related to the tripal downloaded from drupal.

After downloading tripal from github, tripal was successfully installed.
Thanks for kind comments!
