### ISSUE TITLE
Title of Publication Feature page is truncated at certain formatting

### ISSUE THREAD

**Issue by jhumann** [tripal/tripal#995]
### System information

* Tripal Version: 7.x-3.2
* Drupal Version: 7.67
* PostgreSQL Version: 10.10
* PHP Version: 7.0.33

### Issue description
This is an issue with the T3 Pub Importer.  It truncates and stores the title in the title field of the 'tripal_entity' table.

When a publication title has italics or super/sub-script formatting, the feature page title is being truncated.  The complete title is in the details, just the page title is affected (examples: https://www.pulsedb.org/Publication/9972, https://www.pulsedb.org/Publication/9973).  If we click edit and immediately update (save) the page (without making changes) it solves the problem, but is a pain.  

Thanks,
Jodi

**Comment by risharde** [comment]
The TreeGenes team could not reproduce this issue on our development environment.
I also was unable to reproduce this specific issue but ended up with another issue 1005 which has been posted.

**Comment by bradfordcondon** [comment]
>just the page title is affected (examples: https://www.pulsedb.org/Publication/9972, https://www.pulsedb.org/Publication/9973). If we click edit and immediately update (save) the page (without making changes) it solves the problem, but is a pain

This makes me think that verifying the entity's title configuration would be helpful.

If you go to admin -> structure -> tripal content types -> Publication, and click "edit", what does your page title config look like?

<img width="453" alt="Screen Shot 2019-10-08 at 8 22 51 AM" src="https://user-images.githubusercontent.com/7063154/66395250-e48f0f80-e9a4-11e9-970b-c0b2965fdec3.png">

if theres no problems there, then it sounds like something is happening on entity update that isnt happening on entity create with regards to the title.

Also, would you be able to link an NCBI record that is causing problems for you?

**Comment by jhumann** [comment]
I double checked the entity's title configuration and it is as you show above, so that is set correctly.

As far as the NCBI record request, are you looking for the file that the pub importer is actually pulling from NCBI?

**Comment by laceysanderson** [comment]
I was also unable to duplicate this. I used the following importer:
![Screen Shot 2019-10-27 at 10 44 19 AM](https://user-images.githubusercontent.com/1566301/67638099-c1ba9180-f8a6-11e9-8afb-882da9437e24.png)
and ran the job:
```
Calling: chado_execute_pub_importer(1, 1, )
INFO (PUB_IMPORT): Importing of publications for this importer is performed using a database transaction. If the load fails or is terminated prematurely then the entire set of deletions is rolled back and will not be found in the database
Importing of publications for this importer is performed using a database transaction. If the load fails or is terminated prematurely then the entire set of deletions is rolled back and will not be found in the database
INFO (PUB_IMPORT): Executing Importer: Test issue 995.
Executing Importer: Test issue 995.
INFO (PUB_IMPORT): Querying PMID for up to 100 pubs that match the criteria.
Querying PMID for up to 100 pubs that match the criteria.
INFO (PUB_IMPORT): Found 1 publications.
Found <em class="placeholder">1</em> publications.
INFO (PUB_IMPORT): Publishing publications with Drupal...
Publishing publications with Drupal...
INFO (PUBLISH_RECORDS): There are 2 records to publish.
There are 2 records to publish.
INFO (PUBLISH_RECORDS): Successfully published 2 Publication record(s).
Successfully published 2 Publication record(s).
INFO (PUB_IMPORT): Done.
Done.
```
Then looked at the published page without editing:
![Screen Shot 2019-10-27 at 10 45 37 AM](https://user-images.githubusercontent.com/1566301/67638111-e6166e00-f8a6-11e9-9860-9da3afee7b8b.png)



@jhumann can you try using the most recent version of Tripal 7.x-3.x dev? Also, could you share your exact importer like I did above?

**Comment by laceysanderson** [comment]
@jhumann what version of Tripal are you using? Can you screenshot your exact Tripal Pub importer page as I did above?

**Comment by jhumann** [comment]
@laceysanderson, sorry for the delayed response.  We are pretty sure this is a display issue, not an importer issue.  We are doing some internal testing and will get back to you.  We haven't seen this issue on recently imported pubs, so it may be resolved.  We will let you know if we can replicate it.

**Comment by laceysanderson** [comment]
Thank you for the update! Please also let us know if you are not able to replicate it so we can close the issue.

**Comment by jhumann** [comment]
Okay, we cannot replicate it anymore.  The Tripal updates must have fixed it.
