### ISSUE TITLE
Number of published items not displayed properly

### ISSUE THREAD

**Issue by jhumann** [tripal/tripal#996]
### System information
Tripal Version: 7.x-3.2
Drupal Version: 7.67
PostgreSQL Version: 10.10
PHP Version: 7.0.33

### Issue description
Just a minor thing I observed when publishing some recently uploaded genes and mRNA.  I did confirm that all the data actually loaded.  The terminal output seems to only publish the last 3 digits of the number of successfully loaded items.  e.g. 134 genes were published out of 45134 and 213 mRNA out of 58213.  The publish function works fine, just made me panic that some of the data failed for some reason.

![image](https://user-images.githubusercontent.com/31292946/64808846-ddfbac80-d54c-11e9-9147-b7cd6d7fb173.png)

**Comment by btski** [comment]
Could it be working as intended? Is it possible that 58,000 records already existed prior to attempting to publish all 58,213; resulting in only 213 unique records being published? It sounds like you ended up with what you wanted/expected.

**Comment by jhumann** [comment]
I uploaded a new genome annotation and all the records were brand new and not in the database before.  That is why I was initially panicked that only 213 had been published.

**Comment by laceysanderson** [comment]
I've created PR #1017 to fix this issue. @jhumann could you test it please?

**Comment by chunhuaicheng** [comment]
The fix works! Thank you.
